/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_app_alarm_def.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   MTK resgenerator XML parser
 *
 *******************************************************************************/


#ifndef _MMI_RP_APP_ALARM_DEF_H
#define _MMI_RP_APP_ALARM_DEF_H




/******************** Menu resource IDs - begin ********************/
typedef enum
{
    ORGANIZER_ALARM_MENU = 44355 + 1, /* BASE_ID + 1 */
    MENU_ID_ALM_REPEAT_TYPE_MAIN,
    MENU_ID_ALM_REPEAT_TYPE_CUSTOM_OPTION_MENU,
    MMI_RP_APP_ALARM_MENU_MAX
}mmi_rp_app_alarm_menu_enum;
/******************** Menu resource IDs - finish ********************/


/******************** String resource IDs - begin ********************/
typedef enum
{
    ALARMS_SNOOZE_STRINGID = 44355 + 1, /* BASE_ID + 1 */
    ALARM_REPEAT_STRING,
    ALARM_ONCE_STRING,
    ALARM_HOURLY_STRING,
    ALARM_EVREYDAY_STRING,
    ALARM_DAYS_STRING,
    ALARM_WEEKLY_STRING,
    ALARM_MONTHLY_STRING,
    ALARM_SEASONLY_STRING,
    ALARM_YEARLY_STRING,
    ALARM_TITHI_STRING,
    ALARMS_POWER_ON,
    ALARMS_SETTING_SNOOZE_INTERVAL,
    STR_ID_ALM_DISABLE_ASK,
    STR_ID_ALM_NO_MARKED,
    MMI_RP_APP_ALARM_STR_MAX
}mmi_rp_app_alarm_str_enum;
/******************** String resource IDs - finish ********************/


/******************** Screen resource IDs - begin ********************/
typedef enum
{
    SCR_ID_ALM_LIST = 44355 + 1, /* BASE_ID + 1 */
    SCR_ID_ALM_SAVE_CONFIRM,
    SCR_ID_ALM_INDICATION,
    SCR_ID_ALM_PWRON_CONFIRM,
    SCR_ID_ALM_EDITOR,
    SCR_ID_ALM_AUDIO_OPT_FMRADIO,
    SCR_ID_ALM_AUDIO_OPT_FMRADIO_CHANNEL_LIST,
    SCR_ID_ALM_AUDIO_OPT_FMRDO_CHANNEL_OPT,
    SCR_ID_ALM_FMRDO_PREV,
    SCR_ID_ALM_FMRDO_MANUAL_INPUT,
    SCR_ID_ALM_FMRDO_MANUAL_INPUT_OPT,
    SCR_ID_ALM_TONE_SETUP,
    SCR_ID_ALM_TONE_SETUP_EXT_MELODY,
    SCR_ID_ALM_TONE_SETUP_EXT_MELODY_DRV,
    SCR_ID_ALM_SETTING,
    SCR_ID_ALM_CUSTOM_REPEAT_TYPE,
    SCR_ID_ALM_TOTAL,
    GRP_ID_ALM_LIST,
    GRP_ID_ALM_IND,
    GRP_ID_ALM_EDITOR,
    GRP_ID_ALM_AUDIO_OPTION,
    GRP_ID_ALM_AUDIO_OPTION_MAN_INPUT,
    GRP_ID_ALM_AUDIO_FM_CHANNEL_OPTION,
    GRP_ID_ALM_AUDIO_FM_MAN_OPTION,
    GRP_ID_ALM_REPEAT_TYPE_MENU,
    GRP_ID_ALM_TOTAL,
    MMI_RP_APP_ALARM_SCR_MAX
}mmi_rp_app_alarm_scr_enum;
/******************** Screen resource IDs - finish ********************/


/******************** Timer resource IDs - begin ********************/
typedef enum
{
    ALARM_ALERT_NOTIFYDURATION_TIMER = 44355 + 1, /* BASE_ID + 1 */
    ALARM_TIMER_WAIT_FOR_CALL,
    MMI_RP_APP_ALARM_TIMER_MAX
}mmi_rp_app_alarm_timer_enum;
/******************** Timer resource IDs - finish ********************/
/******************** Template resource IDs - Begin ********************/
/******************** Template resource IDs - End ********************/

/******************** Venus XML resource IDs - Begin ********************/
typedef enum 
{

    MMI_RP_APP_ALARM_VXML_LAYOUT_MAX
} mmi_rp_app_alarm_vxml_layout_enum;
/******************** Venus XML resource IDs - End ********************/



/******************** Image resource IDs - begin ********************/
typedef enum
{
    ALARMS_EDIT_SOFTKEY_IMAGEID = 44355 + 1, /* BASE_ID + 1 */
    ALARM_ANIMATION_INDICATION_IMAGEID,
    ORGANIZER_MENU_ALARMS_IMAGEID,
    ALARMS_SET_ALERT_TYPE_IMAGEID,
    MMI_RP_APP_ALARM_IMG_MAX
}mmi_rp_app_alarm_img_enum;
/******************** Image resource IDs - finish ********************/


#endif /* _MMI_RP_APP_ALARM_DEF_H */
