/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_srv_nw_name_def.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   MTK resgenerator XML parser
 *
 *******************************************************************************/


#ifndef _MMI_RP_SRV_NW_NAME_DEF_H
#define _MMI_RP_SRV_NW_NAME_DEF_H




/******************** String resource IDs - begin ********************/
typedef enum
{
    STR_ID_NWNAME_LIMITED_SERVICE = 28329 + 1, /* BASE_ID + 1 */
    STR_ID_NWNAME_INVALID_SIM,
    STR_ID_NWNAME_NO_SERVICE,
    STR_ID_NWNAME_INSERT_SIM,
    STR_ID_NWNAME_SIM_ACCESS_ERROR,
    STR_ID_NWNAME_SIM_BLOCKED,
    STR_ID_NWNAME_SIM_DISCONNECTED,
    STR_ID_NWNAME_SIM_ACCESS_PROFILE,
    STR_ID_NWNAME_SELECT_NETWORK,
    STR_ID_NWNAME_FLIGHT_MODE,
    STR_ID_NWNAME_SIM_CLOSED,
    STR_ID_NWNAME_INVALID_IMEI,
    STR_ID_NWNAME_SAME_IMEI,
    STR_ID_NWNAME_PREPAREING_SIM_CARD,
    MMI_RP_SRV_NW_NAME_STR_MAX
}mmi_rp_srv_nw_name_str_enum;
/******************** String resource IDs - finish ********************/


/******************** Events resource IDs - begin ********************/
typedef enum
{
    EVT_ID_SRV_NW_NAME_CHANGED = 28329 + 1, /* BASE_ID + 1 */
    EVT_ID_SRV_NW_NAME_SIM_CHANGED_BY_SAT,
    MMI_RP_SRV_NW_NAME_EVENT_MAX
}mmi_rp_srv_nw_name_event_enum;
/******************** Events resource IDs - begin ********************/
/******************** Template resource IDs - Begin ********************/
/******************** Template resource IDs - End ********************/

/******************** Venus XML resource IDs - Begin ********************/
typedef enum 
{

    MMI_RP_SRV_NW_NAME_VXML_LAYOUT_MAX
} mmi_rp_srv_nw_name_vxml_layout_enum;
/******************** Venus XML resource IDs - End ********************/



#endif /* _MMI_RP_SRV_NW_NAME_DEF_H */
