/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_app_filemanager_def.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   MTK resgenerator XML parser
 *
 *******************************************************************************/


#ifndef _MMI_RP_APP_FILEMANAGER_DEF_H
#define _MMI_RP_APP_FILEMANAGER_DEF_H




/******************** Menu resource IDs - begin ********************/
typedef enum
{
    MENU_ID_FMGR_DRIVE_OPTIONS = 40495 + 1, /* BASE_ID + 1 */
    MENU_ID_FMGR_APP_DRIVE_OPTIONS,
    MENU_ID_FMGR_DRIVE_OPEN,
    MENU_ID_FMGR_DRIVE_FORMAT,
    MENU_ID_FMGR_DRIVE_SELECT_DONE,
    MENU_ID_FMGR_CARD_DETAIL,
    MENU_ID_FMGR_FOLDER_OPTIONS,
    MENU_ID_FMGR_APP_FOLDER_OPTIONS,
    MENU_ID_FMGR_FOLDER_OPEN,
    MENU_ID_FMGR_FOLDER_CREATE,
    MENU_ID_FMGR_FOLDER_SELECT_DONE,
    MENU_ID_FMGR_HYPERLINK_OPTIONS,
    MENU_ID_FMGR_HYPERLINK_APP_FUNC,
    MENU_ID_FMGR_TREE_OPTIONS,
    MENU_ID_FMGR_TREE_SELECT,
    MENU_ID_FMGR_TREE_OPEN,
    MENU_ID_FMGR_GEN_TYPE_OPTIONS,
    MENU_ID_FMGR_GEN_OPTION_FORWARD_USE,
    MENU_ID_FMGR_GEN_OPTION_FORWARD_SEND,
    MENU_ID_FMGR_GEN_OPTION_DETAIL,
    MENU_ID_FMGR_GEN_OPTION_MORE_RITS,
    MENU_ID_FMGR_GEN_OPTION_RENAME,
    MENU_ID_FMGR_GEN_OPTION_COPY,
    MENU_ID_FMGR_GEN_OPTION_MOVE,
    MENU_ID_FMGR_GEN_OPTION_DELETE,
    MENU_ID_FMGR_GEN_OPTION_SORT,
    MENU_ID_FMGR_SORT_BY_NAME,
    MENU_ID_FMGR_SORT_BY_TYPE,
    MENU_ID_FMGR_SORT_BY_TIME,
    MENU_ID_FMGR_SORT_BY_SIZE,
    MENU_ID_FMGR_EDITOR_OPTION,
    MENU_ID_FMGR_EDITOR_DONE,
    MENU_ID_FMGR_EDITOR_INPUT_METHOD,
    MMI_RP_APP_FILEMANAGER_MENU_MAX
}mmi_rp_app_filemanager_menu_enum;
/******************** Menu resource IDs - finish ********************/


/******************** String resource IDs - begin ********************/
typedef enum
{
    STR_FMGR_TITLE = 40495 + 1, /* BASE_ID + 1 */
    STR_ID_FMGR_NO_FORWARD_OPTION,
    STR_ID_FMGR_NOT_AVAILABLE,
    STR_FMGR_FOLDER_CREATE,
    STR_FMGR_FORMAT,
    STR_FMGR_FORMATING,
    STR_FMGR_UNMOUNTING,
    STR_FMGR_CARD_NAME,
    STR_ID_FMGR_TOTAL_SIZE,
    STR_ID_FMGR_FREE_SIZE,
    STR_FMGR_USE,
    STR_FMGR_COPY_TO,
    STR_FMGR_MOVE_TO,
    STR_FMGR_SORT_BY_NAME,
    STR_FMGR_SORT_BY_TYPE,
    STR_FMGR_SORT_BY_TIME,
    STR_FMGR_SORT_BY_SIZE,
    STR_ID_FMGR_DRV_FREE_SPACE,
    STR_ID_FMGR_DRV_TOTAL_SPACE,
    STR_ID_FMGR_FILE_DATE,
    STR_ID_FMGR_FILE_SIZE,
    STR_ID_FMGR_SYSTEM_BUSY_TO_DECODE,
    STR_ID_FMGR_QUESTION_MARK,
    STR_ID_FMGR_NEW_FOLDER_LSK,
    STR_ID_FMGR_FOLDER_NAME,
    STR_ID_FMGR_NO_FILES,
    STR_ID_FMGR_NO_FOLDERS,
    MMI_RP_APP_FILEMANAGER_STR_MAX
}mmi_rp_app_filemanager_str_enum;
/******************** String resource IDs - finish ********************/


/******************** Timer resource IDs - begin ********************/
typedef enum
{
    FMGR_AUDIO_TIMER = 40495 + 1, /* BASE_ID + 1 */
    FMGR_SCR_TIMER,
    MMI_RP_APP_FILEMANAGER_TIMER_MAX
}mmi_rp_app_filemanager_timer_enum;
/******************** Timer resource IDs - finish ********************/
/******************** Template resource IDs - Begin ********************/
/******************** Template resource IDs - End ********************/

/******************** Venus XML resource IDs - Begin ********************/
typedef enum 
{

    MMI_RP_APP_FILEMANAGER_VXML_LAYOUT_MAX
} mmi_rp_app_filemanager_vxml_layout_enum;
/******************** Venus XML resource IDs - End ********************/



/******************** Image resource IDs - begin ********************/
typedef enum
{
    IMG_ID_FMGR_DRIVE_MEM_CARD = 40495 + 1, /* BASE_ID + 1 */
    IMG_ID_FMGR_DRIVE_PHONE,
    IMG_ID_FMGR_ICON_FILE_TYPE_FOLDER,
    IMG_ID_FMGR_ICON_FILE_TYPE_UNKNOWN,
    IMG_ID_FMGR_FILE_TYPE_UNKNOWN,
    IMG_ID_FMGR_FILE_TYPE_FOLDER,
    IMG_ID_FMGR_DRM_LOCKED,
    MMI_RP_APP_FILEMANAGER_IMG_MAX
}mmi_rp_app_filemanager_img_enum;
/******************** Image resource IDs - finish ********************/


#endif /* _MMI_RP_APP_FILEMANAGER_DEF_H */
