/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_app_mmi_wap_prof_def.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   MTK resgenerator XML parser
 *
 *******************************************************************************/


#ifndef _MMI_RP_APP_MMI_WAP_PROF_DEF_H
#define _MMI_RP_APP_MMI_WAP_PROF_DEF_H




/******************** String resource IDs - begin ********************/
typedef enum
{
    STR_ID_WAP_PROF_CBM_BROWSER = 48174 + 1, /* BASE_ID + 1 */
    STR_ID_WAP_PROF_DTCNT_ALREADY_CONFIGURED,
    STR_ID_WAP_PROF_PROV_BOOKMARKS_COLON,
    STR_ID_WAP_PROF_PROV_BOOKMARK,
    STR_ID_WAP_PROF_COLON_CHAR,
    STR_ID_WAP_PROF_PROV_ERR_MSG_BKM_NOT_AVAILABLE,
    STR_ID_WAP_PROF_ERR_MSG_INVALID_DATA_ACCOUNT,
    STR_ID_WAP_PROF_PROV_MMS_SETTINGS,
    STR_ID_WAP_PROF_PROV_MMS_SETTING_CM_COLON,
    STR_ID_WAP_PROF_PROV_MMS_SETTING_RM_COLON,
    STR_ID_WAP_PROF_PROV_MMS_SETTING_MA_COLON,
    STR_ID_WAP_PROF_PROV_MMS_SETTING_MS_COLON,
    STR_ID_WAP_PROF_PROV_MMS_SETTING_PCADDR_COLON,
    STR_ID_WAP_PROF_PROV_MMS_SETTING_VALUE_RESTRICTED,
    STR_ID_WAP_PROF_PROV_MMS_SETTING_VALUE_WARNING,
    STR_ID_WAP_PROF_PROV_MMS_SETTING_VALUE_FREE,
    STR_ID_WAP_PROF_PROV_MMS_SETTING_VALUE_DISABLE,
    STR_ID_WAP_PROF_PROV_MMS_SETTING_VALUE_ENABLE,
    STR_ID_WAP_PROF_PROV_MMS_SETTING_VALUE_LOCKED,
    MMI_RP_APP_MMI_WAP_PROF_STR_MAX
}mmi_rp_app_mmi_wap_prof_str_enum;
/******************** String resource IDs - finish ********************/


/******************** Screen resource IDs - begin ********************/
typedef enum
{
    GRP_ID_WAP_PROF_DTCNT_DISPLAY = 48174 + 1, /* BASE_ID + 1 */
    SCR_ID_WAP_PROF_PROV_DISPLAY_INFO,
    MMI_RP_APP_MMI_WAP_PROF_SCR_MAX
}mmi_rp_app_mmi_wap_prof_scr_enum;
/******************** Screen resource IDs - finish ********************/
/******************** Template resource IDs - Begin ********************/
/******************** Template resource IDs - End ********************/

/******************** Venus XML resource IDs - Begin ********************/
typedef enum 
{

    MMI_RP_APP_MMI_WAP_PROF_VXML_LAYOUT_MAX
} mmi_rp_app_mmi_wap_prof_vxml_layout_enum;
/******************** Venus XML resource IDs - End ********************/



#endif /* _MMI_RP_APP_MMI_WAP_PROF_DEF_H */
