/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_all_defs.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Include all auto generated header files (for res IDs) by XML resgen
 *
 * Author:
 * -------
 *   MTK resgenerator XML parser
 *
 *******************************************************************************/

#include "mmi_rp_app_mre_def.h"
#include "mmi_rp_app_bluetooth_def.h"
#include "mmi_rp_app_bootup_def.h"
#include "mmi_rp_app_nw_info_def.h"
#include "mmi_rp_app_sim_ctrl_def.h"
#include "mmi_rp_app_shutdown_def.h"
#include "mmi_rp_app_security_setting_def.h"
#include "mmi_rp_cui_verify_def.h"
#include "mmi_rp_cui_password_def.h"
#include "mmi_rp_app_camera_def.h"
#include "mmi_rp_app_imageviewer_def.h"
#include "mmi_rp_cui_imageviewer_def.h"
#include "mmi_rp_cui_toneselector_def.h"
#include "mmi_rp_app_soundrecorder_def.h"
#include "mmi_rp_app_audioplayer_def.h"
#include "mmi_rp_app_webcam_def.h"
#include "mmi_rp_app_camco_def.h"
#include "mmi_rp_app_worldclock_def.h"
#include "mmi_rp_app_callset_def.h"
#include "mmi_rp_app_ss_def.h"
#include "mmi_rp_app_apn_control_def.h"
#include "mmi_rp_app_unifiedcomposer_def.h"
#include "mmi_rp_app_mmi_certman_def.h"
#include "mmi_rp_app_rmgr_def.h"
#include "mmi_rp_app_dataaccount_def.h"
#include "mmi_rp_app_umms_mms_def.h"
#include "mmi_rp_app_mmi_wap_push_def.h"
#include "mmi_rp_app_calllog_def.h"
#include "mmi_rp_app_profiles_def.h"
#include "mmi_rp_app_filemanager_def.h"
#include "mmi_rp_srv_screensaver_def.h"
#include "mmi_rp_srv_wallpaper_def.h"
#include "mmi_rp_srv_spof_def.h"
#include "mmi_rp_srv_phnset_onoff_def.h"
#include "mmi_rp_srv_flight_mode_def.h"
#include "mmi_rp_app_calibration_def.h"
#include "mmi_rp_app_setting_new_def.h"
#include "mmi_rp_app_phonesetting_new_def.h"
#include "mmi_rp_app_restore_def.h"
#include "mmi_rp_app_netset_def.h"
#include "mmi_rp_app_mode_switch_def.h"
#include "mmi_rp_app_setting_menu_effect_def.h"
#include "mmi_rp_app_setting_download_cal_data_def.h"
#include "mmi_rp_app_sat_def.h"
#include "mmi_rp_app_services_sat_def.h"
#include "mmi_rp_app_mobile_service_def.h"
#include "mmi_rp_app_customer_service_def.h"
#include "mmi_rp_app_setting_version_def.h"
#include "mmi_rp_app_shortcuts_def.h"
#include "mmi_rp_app_venus_homescreen_wg_mobile_internet_def.h"
#include "mmi_rp_app_venus_homescreen_wg_wo_store_def.h"
#include "mmi_rp_app_calculator_def.h"
#include "mmi_rp_srv_syncml_def.h"
#include "mmi_rp_app_syncml_def.h"
#include "mmi_rp_srv_mmi_theme_def.h"
#include "mmi_rp_app_cbs_def.h"
#include "mmi_rp_app_alarm_def.h"
#include "mmi_rp_app_nitz_def.h"
#include "mmi_rp_app_ntp_def.h"
#include "mmi_rp_app_organizer_def.h"
#include "mmi_rp_app_calendar_def.h"
#include "mmi_rp_app_todolist_def.h"
#include "mmi_rp_app_lunar_query_def.h"
#include "mmi_rp_app_note_def.h"
#include "mmi_rp_app_udx_def.h"
#include "mmi_rp_app_dialer_def.h"
#include "mmi_rp_srv_vobject_def.h"
#include "mmi_rp_srv_vcalendar_def.h"
#include "mmi_rp_srv_vcard_def.h"
#include "mmi_rp_srv_vbookmark_def.h"
#include "mmi_rp_app_ucm_def.h"
#include "mmi_rp_app_reminder_def.h"
#include "mmi_rp_app_sms_def.h"
#include "mmi_rp_app_mot_def.h"
#include "mmi_rp_app_vdoply_def.h"
#include "mmi_rp_app_vdorec_def.h"
#include "mmi_rp_app_unifiedmessage_def.h"
#include "mmi_rp_app_search_web_def.h"
#include "mmi_rp_app_mmi_wap_prof_def.h"
#include "mmi_rp_app_mainmenu_def.h"
#include "mmi_rp_app_cca_def.h"
#include "mmi_rp_app_usbmmi_def.h"
#include "mmi_rp_app_viewsetting_def.h"
#include "mmi_rp_app_tts_setting_def.h"
#include "mmi_rp_app_cbm_def.h"
#include "mmi_rp_app_nss_def.h"
#include "mmi_rp_app_downloadagent_def.h"
#include "mmi_rp_motion_sensor_def.h"
#include "mmi_rp_app_package_concurrent_def.h"
#include "mmi_rp_app_sso_def.h"
#include "mmi_rp_cui_sso_def.h"
#include "mmi_rp_framework_asm_def.h"
#include "mmi_rp_srv_nmgr_def.h"
#include "mmi_rp_app_phonebook_def.h"
#include "mmi_rp_app_funandgames_def.h"
#include "mmi_rp_srv_status_icons_def.h"
#include "mmi_rp_srv_prof_def.h"
#include "mmi_rp_srv_sms_def.h"
#include "mmi_rp_srv_unifiedmessage_def.h"
#include "mmi_rp_srv_gps_def.h"
#include "mmi_rp_srv_mot_def.h"
#include "mmi_rp_srv_gcall_def.h"
#include "mmi_rp_app_idle_homescreen_def.h"
#include "mmi_rp_app_uiframework_def.h"
#include "mmi_rp_srv_input_method_def.h"
#include "mmi_rp_srv_editor_def.h"
#include "mmi_rp_srv_inline_editor_def.h"
#include "mmi_rp_srv_sim_ctrl_def.h"
#include "mmi_rp_srv_nw_info_def.h"
#include "mmi_rp_srv_bootup_def.h"
#include "mmi_rp_srv_shutdown_def.h"
#include "mmi_rp_srv_secset_def.h"
#include "mmi_rp_srv_sat_def.h"
#include "mmi_rp_srv_cphs_def.h"
#include "mmi_rp_app_charger_def.h"
#include "mmi_rp_srv_charbat_def.h"
#include "mmi_rp_app_engineermode1_def.h"
#include "mmi_rp_app_factorymode_def.h"
#include "mmi_rp_srv_filemanager_def.h"
#include "mmi_rp_srv_pns_def.h"
#include "mmi_rp_app_connectivity_mainmenu_def.h"
#include "mmi_rp_app_usbsrv_def.h"
#include "mmi_rp_app_extra_def.h"
#include "mmi_rp_app_devapp_def.h"
#include "mmi_rp_srv_downloadagent_def.h"
#include "mmi_rp_srv_mms_def.h"
#include "mmi_rp_srv_mdi_def.h"
#include "mmi_rp_srv_mdi_audply_def.h"
#include "mmi_rp_srv_mdi_aud_info_def.h"
#include "mmi_rp_srv_mdi_vdoply_def.h"
#include "mmi_rp_srv_mdi_vdoply_v_def.h"
#include "mmi_rp_srv_mdi_vdoply_a_def.h"
#include "mmi_rp_srv_mdi_vdoply_qvga_def.h"
#include "mmi_rp_srv_mdi_vdoply_cif_def.h"
#include "mmi_rp_srv_mdi_vdoply_preview_def.h"
#include "mmi_rp_srv_mdi_vdoply_info_def.h"
#include "mmi_rp_srv_mdi_vdoply_mp4_def.h"
#include "mmi_rp_srv_mdi_vdoply_qvga_mpeg4sp_def.h"
#include "mmi_rp_srv_mdi_vdoply_subtitle_def.h"
#include "mmi_rp_srv_mdi_camera_standard_def.h"
#include "mmi_rp_srv_mdi_camera_full_def.h"
#include "mmi_rp_srv_mdi_camera_only_cap_lcd_def.h"
#include "mmi_rp_srv_mdi_camera_only_cap_lcd_disable_jaia_def.h"
#include "mmi_rp_srv_mdi_camera_cap_vga_below_def.h"
#include "mmi_rp_srv_mdi_camera_autorama_def.h"
#include "mmi_rp_srv_mdi_camera_cap_hdr_def.h"
#include "mmi_rp_srv_mdi_camera_cap_mav_def.h"
#include "mmi_rp_srv_ucm_def.h"
#include "mmi_rp_cui_sim_sel_def.h"
#include "mmi_rp_srv_wap_prof_def.h"
#include "mmi_rp_app_mre_appmgr_def.h"
#include "mmi_rp_srv_virtual_keyboard_misc_def.h"
#include "mmi_rp_srv_venus_component_normal_mode_menu_def.h"
#include "mmi_rp_srv_sensor_def.h"
#include "mmi_rp_srv_gpio_def.h"
#include "mmi_rp_app_gpio_def.h"
#include "mmi_rp_srv_btcm_def.h"
#include "mmi_rp_srv_mmi_charset_def.h"
#include "mmi_rp_srv_cbm_def.h"
#include "mmi_rp_app_appmgr_test_1_def.h"
#include "mmi_rp_app_appmgr_test_2_def.h"
#include "mmi_rp_app_appmgr_test_3_def.h"
#include "mmi_rp_app_appmgr_test_4_def.h"
#include "mmi_rp_app_mediawall_def.h"
#include "mmi_rp_app_font_manager_def.h"
#include "mmi_rp_app_font_effects_def.h"
#include "mmi_rp_srv_wgtmgr_def.h"
#include "mmi_rp_srv_cbs_def.h"
#include "mmi_rp_srv_netset_def.h"
#include "mmi_rp_srv_callset_def.h"
#include "mmi_rp_srv_ss_def.h"
#include "mmi_rp_srv_modeswitch_def.h"
#include "mmi_rp_srv_pen_calibration_def.h"
#include "mmi_rp_srv_general_setting_def.h"
#include "mmi_rp_srv_dtcnt_def.h"
#include "mmi_rp_app_idle_def.h"
#include "mmi_rp_app_idle_nmgr_def.h"
#include "mmi_rp_cui_dialer_def.h"
#include "mmi_rp_app_scr_locker_def.h"
#include "mmi_rp_srv_nw_name_def.h"
#include "mmi_rp_srv_eons_def.h"
#include "mmi_rp_app_shellapp_base_def.h"
#include "mmi_rp_app_venus_shell_iv_def.h"
#include "mmi_rp_app_venus_shell_mediaplayer_def.h"
#include "mmi_rp_app_venus_shell_settings_def.h"
#include "mmi_rp_app_venus_shell_msg_viewer_def.h"
#include "mmi_rp_app_venus_notepaper_def.h"
#include "mmi_rp_app_venus_shell_fc_def.h"
#include "mmi_rp_app_venus_shell_scrlock_def.h"
#include "mmi_rp_app_venus_wallpaper_def.h"
#include "mmi_rp_app_venus_wallpaper_total_def.h"
#include "mmi_rp_app_venus_wallpaper_wave_def.h"
#include "mmi_rp_app_venus_wallpaper_spangle_def.h"
#include "mmi_rp_app_venus_wallpaper_chipset_def.h"
#include "mmi_rp_app_venus_wallpaper_comet_def.h"
#include "mmi_rp_app_venus_wallpaper_space_def.h"
#include "mmi_rp_app_venus_wallpaper_matrix_def.h"
#include "mmi_rp_app_venus_wallpaper_wildworld_def.h"
#include "mmi_rp_app_venus_wallpaper_firefly_def.h"
#include "mmi_rp_app_venus_homescreen_def.h"
#include "mmi_rp_app_venus_homescreen_wg_calendar_def.h"
#include "mmi_rp_app_venus_homescreen_wg_date_def.h"
#include "mmi_rp_app_venus_homescreen_wg_memo_def.h"
#include "mmi_rp_app_venus_homescreen_wg_clock_def.h"
#include "mmi_rp_app_venus_homescreen_wg_pet_def.h"
#include "mmi_rp_app_venus_homescreen_wg_snow_def.h"
#include "mmi_rp_app_venus_homescreen_wg_mre_def.h"
#include "mmi_rp_app_venus_homescreen_wg_profile_def.h"
#include "mmi_rp_app_venus_homescreen_wg_operator_name_def.h"
#include "mmi_rp_app_venus_homescreen_wg_event_inbox_def.h"
#include "mmi_rp_app_venus_homescreen_wg_next_alarm_def.h"
#include "mmi_rp_app_venus_homescreen_wg_audioplayer_def.h"
#include "mmi_rp_app_venus_homescreen_wg_fmradio_def.h"
#include "mmi_rp_app_venus_homescreen_wg_photo_def.h"
#include "mmi_rp_srv_calllog_def.h"
#include "mmi_rp_app_venus_hs_wg_bkm_def.h"
#include "mmi_rp_app_venus_hs_wg_baidu_def.h"
#include "mmi_rp_app_venus_hs_todo_def.h"
#include "mmi_rp_app_imageflow_def.h"
#include "mmi_rp_app_sim_me_lock_def.h"
#include "mmi_rp_app_cb_mgr_def.h"
#include "mmi_rp_app_auto_rotate_def.h"
#include "mmi_rp_srv_reminder_def.h"
#include "mmi_rp_srv_todolist_def.h"
#include "mmi_rp_srv_soundrec_def.h"
#include "mmi_rp_srv_push_def.h"
#include "mmi_rp_app_simspace_def.h"
#include "mmi_rp_srv_datetime_def.h"
#include "mmi_rp_srv_alarm_def.h"
#include "mmi_rp_srv_phb_def.h"
#include "mmi_rp_srv_restore_def.h"
#include "mmi_rp_srv_nitz_def.h"
#include "mmi_rp_cui_alert_def.h"
#include "mmi_rp_srv_datalock_def.h"
#include "mmi_rp_srv_rights_mgr_def.h"
#include "mmi_rp_srv_cnmgr_def.h"
#include "mmi_rp_vapp_video_player_cp_def.h"
#include "mmi_rp_srv_appmgr_def.h"
#include "mmi_rp_cui_use_detail_def.h"
#include "mmi_rp_srv_nss_def.h"
#include "mmi_rp_srv_safe_mode_def.h"
#include "mmi_rp_core_ucm_def.h"
#include "mmi_rp_srv_gdi_def.h"
#include "mmi_rp_srv_venus_theme_def.h"
#include "mmi_rp_app_am_def.h"
#include "mmi_rp_app_gb_winguo_def.h"
#include "mmi_rp_app_gb_winguo_net_def.h"
#include "mmi_rp_app_npr_tts_def.h"
#include "mmi_rp_app_kjx_def.h"
