/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_cache_table.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   03 13 2011 yan.liang
 *
 *******************************************************************************/
#ifndef MMI_RP_MMI_CACHE_TABLE_H
#define MMI_RP_MMI_CACHE_TABLE_H


#include "nvram_enums.h"
#include "custom_nvram_config.h"


extern kal_uint16 mmi_rp_mmi_cache_get_byte_number(void);
extern kal_uint16 mmi_rp_mmi_cache_get_short_number(void);
extern kal_uint16 mmi_rp_mmi_cache_get_double_number(void);


extern const kal_uint16 MMI_CACHE_BYTE_ENUM_TABLE[];
extern const kal_uint16 MMI_CACHE_SHORT_ENUM_TABLE[];
extern const kal_uint16 MMI_CACHE_DOUBLE_ENUM_TABLE[];


extern const kal_uint32 NVRAM_EF_MMI_CACHE_BYTE_KEY_DEFAULT[];
extern const kal_uint32 NVRAM_EF_MMI_CACHE_SHORT_KEY_DEFAULT[];
extern const kal_uint32 NVRAM_EF_MMI_CACHE_DOUBLE_KEY_DEFAULT[];


extern void nvram_restore_byte_cache(nvram_reset_category_enum category,nvram_app_id_enum app_id, kal_uint8 *buffer);
extern void nvram_restore_short_cache(nvram_reset_category_enum category,nvram_app_id_enum app_id, kal_uint8 *buffer);
extern void nvram_restore_double_cache(nvram_reset_category_enum category,nvram_app_id_enum app_id, kal_uint8 *buffer);
extern kal_int16 mmi_rp_mmi_cache_search_index(kal_uint16 nDataItemId, kal_uint8 nDataType);


#endif /* MMI_CACHE_TABLE_H */