/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_app_cbs_def.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   MTK resgenerator XML parser
 *
 *******************************************************************************/


#ifndef _MMI_RP_APP_CBS_DEF_H
#define _MMI_RP_APP_CBS_DEF_H




/******************** Menu resource IDs - begin ********************/
typedef enum
{
    MENU_ID_CBS_CHANNELS = 44054 + 1, /* BASE_ID + 1 */
    MENU_ID_CBS_LANGUAGES,
    MENU_ID_CBS_INBOX,
    MENU_ID_CBS_RECEIVE_MODE_ON,
    MENU_ID_CBS_RECEIVE_MODE_OFF,
    MENU_ID_CBS_CHNL_OPT_SUBSCRIBE,
    MENU_ID_CBS_CHNL_OPT_UNSUBSCRIBE,
    MENU_ID_CBS_CHNL_OPT_ADD,
    MENU_ID_CBS_CHNL_OPT_EDIT,
    MENU_ID_CBS_CHNL_OPT_DELETE,
    MENU_ID_CBS_VIEWER_OPT_DELETE,
    MENU_ID_CBS_VIEWER_OPT_USE_NUM,
    MENU_ID_CBS_RECEIVE_MODE,
    MENU_ID_CBS_MAIN,
    MENU_ID_CBS_CHNL_OPTIONS,
    MENU_ID_CBS_VIEWER_OPTIONS,
    MMI_RP_APP_CBS_MENU_MAX
}mmi_rp_app_cbs_menu_enum;
/******************** Menu resource IDs - finish ********************/


/******************** String resource IDs - begin ********************/
typedef enum
{
    STR_ID_CBS_CAPTION = 44054 + 1, /* BASE_ID + 1 */
    STR_ID_CBS_NEW_MSG_TITLE,
    STR_ID_CBS_NEW_MSG_FROM,
    STR_ID_CBS_RECEIVE_MODE,
    STR_ID_CBS_CHANNELS,
    STR_ID_CBS_LANGUAGES,
    STR_ID_CBS_INBOX,
    STR_ID_CBS_SUBSCRIBE,
    STR_ID_CBS_CANCEL_SUBSCRIPTION,
    STR_ID_CBS_NOT_READY_YET,
    STR_ID_CBS_CHNL_FULL,
    STR_ID_CBS_CHNL_DUPLICTED,
    STR_ID_CBS_ALL_LANGS,
    STR_ID_CBS_LANG_OTHERS,
    STR_ID_CBS_LANG_UNSPECIFIED,
    STR_ID_CBS_CHNL_NAME,
    STR_ID_CBS_CHNL_NUMBER,
    STR_ID_CBS_MSG_BODY,
    STR_ID_CBS_ADD_CHNL,
    STR_ID_CBS_EDIT_CHNL,
    STR_ID_CBS_LANG_ARABIC,
    STR_ID_CBS_LANG_CZECH,
    STR_ID_CBS_LANG_DANISH,
    STR_ID_CBS_LANG_GERMAN,
    STR_ID_CBS_LANG_GREEK,
    STR_ID_CBS_LANG_ENGLISH,
    STR_ID_CBS_LANG_SPANISH,
    STR_ID_CBS_LANG_FINNISH,
    STR_ID_CBS_LANG_FRENCH,
    STR_ID_CBS_LANG_HEBREW,
    STR_ID_CBS_LANG_HUNGARIAN,
    STR_ID_CBS_LANG_ICELANDIC,
    STR_ID_CBS_LANG_ITALIAN,
    STR_ID_CBS_LANG_DUTCH,
    STR_ID_CBS_LANG_NORWEGIAN,
    STR_ID_CBS_LANG_POLISH,
    STR_ID_CBS_LANG_PORTUGUESE,
    STR_ID_CBS_LANG_RUSSIAN,
    STR_ID_CBS_LANG_SWEDISH,
    STR_ID_CBS_LANG_TURKISH,
    MMI_RP_APP_CBS_STR_MAX
}mmi_rp_app_cbs_str_enum;
/******************** String resource IDs - finish ********************/


/******************** Screen resource IDs - begin ********************/
typedef enum
{
    SCR_ID_CBS_SIM_SELECT = 44054 + 1, /* BASE_ID + 1 */
    SCR_ID_CBS_MAIN_MENU,
    SCR_ID_CBS_RECEIVE_MODE,
    SCR_ID_CBS_LANG_LIST,
    SCR_ID_CBS_CHNL_LIST,
    SCR_ID_CBS_CHNL_LIST_OPTIONS,
    SCR_ID_CBS_ADD_CHNL,
    SCR_ID_CBS_EDIT_CHNL,
    SCR_ID_CBS_INBOX_LIST,
    SCR_ID_CBS_VIEWER,
    SCR_ID_CBS_VIEWER_OPTION,
    SCR_ID_CBS_NEW_NORMAL_IND,
    SCR_ID_CBS_NEW_IMMEDIATE_IND,
    MMI_RP_APP_CBS_SCR_MAX
}mmi_rp_app_cbs_scr_enum;
/******************** Screen resource IDs - finish ********************/
/******************** Template resource IDs - Begin ********************/
/******************** Template resource IDs - End ********************/

/******************** Venus XML resource IDs - Begin ********************/
typedef enum 
{

    MMI_RP_APP_CBS_VXML_LAYOUT_MAX
} mmi_rp_app_cbs_vxml_layout_enum;
/******************** Venus XML resource IDs - End ********************/



/******************** Image resource IDs - begin ********************/
typedef enum
{
    IMG_ID_CBS_COMMON = 44054 + 1, /* BASE_ID + 1 */
    IMG_ID_CBS_CHNL_NAME,
    IMG_ID_CBS_CHNL_NUMBER,
    IMG_ID_CBS_SUBSCRIBE,
    IMG_ID_CBS_UNSUBSCRIBE,
    MMI_RP_APP_CBS_IMG_MAX
}mmi_rp_app_cbs_img_enum;
/******************** Image resource IDs - finish ********************/


#endif /* _MMI_RP_APP_CBS_DEF_H */
