/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_srv_mot_def.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   MTK resgenerator XML parser
 *
 *******************************************************************************/


#ifndef _MMI_RP_SRV_MOT_DEF_H
#define _MMI_RP_SRV_MOT_DEF_H




/******************** String resource IDs - begin ********************/
typedef enum
{
    STR_SRV_MOT = 7606 + 1, /* BASE_ID + 1 */
    STR_ID_SRV_MOT_CAT_ACTION_ADVENTURE,
    STR_ID_SRV_MOT_CAT_ROMANCE_ETHICS,
    STR_ID_SRV_MOT_CAT_COMEDY_HUMOR,
    STR_ID_SRV_MOT_CAT_TV_DRAMA,
    STR_ID_SRV_MOT_CAT_ANIMATION_SCIFI,
    STR_ID_SRV_MOT_CAT_THRILLER_MYSTERY,
    STR_ID_SRV_MOT_CAT_MUSIC_PERFORMANCE,
    STR_ID_SRV_MOT_CAT_DOCUMENTARY,
    STR_ID_SRV_MOT_CAT_OTHERS,
    STR_ID_SRV_MOT_CAT_RECENT_PLAY,
    STR_ID_SRV_MOT_CAT_ALL,
    STR_ID_SRV_MOT_DEFAULT_UNNAMED,
    STR_ID_SRV_MOT_DEFAULT_UNKNOWN,
    STR_ID_SRV_MOT_DEFAULT_NO_DETAILS,
    STR_ID_SRV_MOT_UNKNOWN_ERR,
    STR_ID_SRV_MOT_FS_ERR,
    STR_ID_SRV_MOT_DB_CANNOT_OPEN,
    STR_ID_SRV_MOT_DB_FREESPACE_NOT_ENOUGH,
    MMI_RP_SRV_MOT_STR_MAX
}mmi_rp_srv_mot_str_enum;
/******************** String resource IDs - finish ********************/
/******************** Template resource IDs - Begin ********************/
/******************** Template resource IDs - End ********************/

/******************** Venus XML resource IDs - Begin ********************/
typedef enum 
{

    MMI_RP_SRV_MOT_VXML_LAYOUT_MAX
} mmi_rp_srv_mot_vxml_layout_enum;
/******************** Venus XML resource IDs - End ********************/



#endif /* _MMI_RP_SRV_MOT_DEF_H */
