/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_app_shortcuts_def.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   MTK resgenerator XML parser
 *
 *******************************************************************************/


#ifndef _MMI_RP_APP_SHORTCUTS_DEF_H
#define _MMI_RP_APP_SHORTCUTS_DEF_H




/******************** Menu resource IDs - begin ********************/
typedef enum
{
    EXTRA_SHORTCUTS_OPTION_ADD_MENUID = 43312 + 1, /* BASE_ID + 1 */
    EXTRA_SHORTCUTS_OPTION_EDIT_MENUID,
    EXTRA_SHORTCUTS_OPTION_DELETE_MENUID,
    EXTRA_SHORTCUTS_OPTION_DELETEALL_MENUID,
    EXTRA_SHORTCUTS_OPTION_CHAGNE_ORDER_MENUID,
    EXTRA_SHORTCUTS_OPTION_MENUID,
    EXTRA_SHORTCUTS_MENUID,
    MMI_RP_APP_SHORTCUTS_MENU_MAX
}mmi_rp_app_shortcuts_menu_enum;
/******************** Menu resource IDs - finish ********************/


/******************** String resource IDs - begin ********************/
typedef enum
{
    STR_MAIN_MENU_ID = 43312 + 1, /* BASE_ID + 1 */
    SHORTCUTS_TITLE_STRING_ID,
    SHORTCUTS_FULL_MSG_STRING_ID,
    SHORTCUTS_CHANGE_ORDER_STRING_ID,
    MMI_RP_APP_SHORTCUTS_STR_MAX
}mmi_rp_app_shortcuts_str_enum;
/******************** String resource IDs - finish ********************/


/******************** Screen resource IDs - begin ********************/
typedef enum
{
    GRP_ID_SHCT_QUICK_MENU_CFG = 43312 + 1, /* BASE_ID + 1 */
    GRP_ID_SHCT_DEDICATED_KEY_CFG,
    GRP_ID_SHCT_QUICK_MENU,
    SCR_ID_SHCT_IDLE_SHORTCUT,
    SCR_ID_SHCT_MAIN_MENU,
    SCR_ID_SHCT_EDIT,
    SCR_ID_SHCT_ORDER,
    SCR_ID_SHCT_DEDICATED_KEYS,
    SCR_ID_SHCT_EDIT_DEDICATED_KEYS,
    SCR_ID_SHCT_APP_SELECT,
    MMI_RP_APP_SHORTCUTS_SCR_MAX
}mmi_rp_app_shortcuts_scr_enum;
/******************** Screen resource IDs - finish ********************/
/******************** Template resource IDs - Begin ********************/
/******************** Template resource IDs - End ********************/

/******************** Venus XML resource IDs - Begin ********************/
typedef enum 
{

    MMI_RP_APP_SHORTCUTS_VXML_LAYOUT_MAX
} mmi_rp_app_shortcuts_vxml_layout_enum;
/******************** Venus XML resource IDs - End ********************/



/******************** Image resource IDs - begin ********************/
typedef enum
{
    IMG_ID_SHORTCUTS_MAINMENU = 43312 + 1, /* BASE_ID + 1 */
    IMG_SETTING_SHORTCUT,
    MMI_RP_APP_SHORTCUTS_IMG_MAX
}mmi_rp_app_shortcuts_img_enum;
/******************** Image resource IDs - finish ********************/


#endif /* _MMI_RP_APP_SHORTCUTS_DEF_H */
