/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_app_rmgr_def.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   MTK resgenerator XML parser
 *
 *******************************************************************************/


#ifndef _MMI_RP_APP_RMGR_DEF_H
#define _MMI_RP_APP_RMGR_DEF_H




/******************** Menu resource IDs - begin ********************/
typedef enum
{
    MENU_ID_RMGR_LIST_RO = 38613 + 1, /* BASE_ID + 1 */
    MENU_ID_RMGR_INFO,
    MENU_ID_RMGR,
    MENU_ID_RMGR_LIST_RO_DETAIL,
    MENU_ID_RMGR_LIST_RO_DELETE,
    MENU_ID_RMGR_LIST_RO_DELETEALL,
    MENU_ID_RMGR_RO_OPTIONS,
    MENU_ID_RMGR_DB_CHECK,
    MENU_ID_RMGR_SCAN_DISK,
    MENU_ID_RMGR_DB_SWEEP,
    MENU_ID_RMGR_DB_PROC,
    MENU_ID_RMGR_LIST_RO_ALIAS_OPTION,
    MMI_RP_APP_RMGR_MENU_MAX
}mmi_rp_app_rmgr_menu_enum;
/******************** Menu resource IDs - finish ********************/


/******************** String resource IDs - begin ********************/
typedef enum
{
    STR_ID_RMGR = 38613 + 1, /* BASE_ID + 1 */
    STR_ID_RMGR_LIST_RO,
    STR_ID_RMGR_INFO,
    STR_ID_RMGR_DB_PROC,
    STR_ID_RMGR_SWEEP,
    STR_ID_RMGR_SCAN_DISK,
    STR_ID_RMGR_SCANNING,
    STR_ID_RMGR_SWEEP_REMOVE_RIGHTS,
    STR_ID_RMGR_BACKUP_AND_REBOOT,
    STR_ID_RMGR_RESTORE_AND_REBOOT,
    STR_ID_RMGR_DELETE_QUERY,
    STR_ID_RMGR_DELETE_ALL_QUERY,
    STR_ID_RMGR_SPACE_CHECK,
    STR_ID_RMGR_SPACE_PROMPT,
    STR_ID_DRM_INVALID_KEY,
    STR_ID_DRM_EOF,
    STR_ID_DRM_TRUNCATED,
    STR_ID_DRM_PROCESS_ERROR,
    STR_ID_DRM_DB_LOCKED_BY_APP,
    STR_ID_DRM_NO_RIGHT_SPACE,
    STR_ID_DRM_PLAY,
    STR_ID_DRM_DISPLAY,
    STR_ID_DRM_EXECUTE,
    STR_ID_DRM_PRINT,
    STR_ID_RMGR_DETAIL_RIGHT,
    STR_ID_RMGR_DETAIL_PROTECTED,
    STR_ID_RMGR_DETAIL_UNPROTECTED,
    STR_ID_RMGR_DETAIL_UNLIMITED,
    STR_ID_RMGR_DETAIL_COUNT,
    STR_ID_RMGR_DETAIL_START,
    STR_ID_RMGR_DETAIL_END,
    STR_ID_RMGR_SUMMARY,
    STR_ID_DRM_INVALID_RO,
    STR_ID_RMGR_DETAIL_LEFT_COUNT,
    STR_ID_RMGR_DETAIL_LEFT_TIME,
    STR_ID_RMGR_DETAIL_LEFT_DAYS,
    STR_ID_RMGR_DETAIL_LEFT_HOURS,
    STR_ID_RMGR_DETAIL_LEFT_LAST,
    STR_ID_RMGR_DETAIL_INSTALLABLE,
    STR_ID_RMGR_DETAIL_UNINSTALLABLE,
    STR_ID_RMGR_DETAIL_FORWARDABLE,
    STR_ID_RMGR_DETAIL_UNFORWARDABLE,
    STR_ID_RMGR_DETAIL_PRINTABLE,
    STR_ID_RMGR_VERSION,
    STR_ID_RMGR_TIME,
    STR_ID_RMGR_REQ_RIGHTS,
    STR_ID_RMGR_REQ_RITS,
    STR_ID_RMGR_MORE_RITS,
    STR_ID_RMGR_MORE_RITS_QUERY,
    STR_ID_RMGR_REQ_RITS_EXPIRE_DETAIL,
    STR_ID_RMGR_REQ_RITS_EXTEND_DETAIL,
    STR_ID_RMGR_USE_NOW,
    STR_ID_RMGR_RO_RECEIVED,
    STR_ID_RMGR_ACTIVATE_COMPLETED,
    STR_ID_RMGR_PROCESSING,
    STR_ID_RMGR_COLON,
    MMI_RP_APP_RMGR_STR_MAX
}mmi_rp_app_rmgr_str_enum;
/******************** String resource IDs - finish ********************/


/******************** Screen resource IDs - begin ********************/
typedef enum
{
    SCR_ID_RMGR_MAIN = 38613 + 1, /* BASE_ID + 1 */
    SCR_ID_RMGR_LIST_RO_MAIN,
    SCR_ID_RMGR_LIST_RO_OPTION,
    SCR_ID_RMGR_LIST_RO_DELETE,
    SCR_ID_RMGR_LIST_RO_DETAIL,
    SCR_ID_RMGR_WHITE_LIST_MAIN,
    SCR_ID_RMGR_WHITE_LIST_OPTION,
    SCR_ID_RMGR_WHITE_LIST_EDIT,
    SCR_ID_RMGR_WHITE_LIST_EDIT_OPTION,
    SCR_ID_RMGR_WHITE_LIST_CLEAN,
    SCR_ID_RMGR_GEN_INFO_MAIN,
    SCR_ID_RMGR_PROGRESS,
    SCR_ID_RMGR_DB_PROC,
    SCR_ID_DRM_AUTH,
    SCR_ID_DRM_SHOW_PERCENTAGE,
    SCR_ID_DRM_GET_CONFIRM,
    SCR_ID_DRM_NOTIFY_INFO,
    SCR_ID_DRM_PROCESSING_START,
    SCR_ID_DRM_START_REGISTER_AGENT,
    SCR_ID_DRM_START_ACQUIRE_RO,
    SCR_ID_DRM_START_DOMAIN_JOIN,
    SCR_ID_DRM_START_DOMAIN_LEAVE,
    SCR_ID_DRM_START_PREVIEW_DOWNLOAD,
    SCR_ID_DRM_START_SILENT_DOWNLOAD,
    SCR_ID_DRM_START_TIME_SYNC,
    SCR_ID_DRM_PROCESSING_END,
    SCR_ID_RMGR_ACTIVATE_PROCESS,
    SCR_ID_RMGR_ACTIVATE_CONFIRM,
    SCR_ID_RMGR_CONFIRM,
    SCR_ID_RMGR_USE_NOW_CONFIRM,
    MMI_RP_APP_RMGR_SCR_MAX
}mmi_rp_app_rmgr_scr_enum;
/******************** Screen resource IDs - finish ********************/


/******************** Timer resource IDs - begin ********************/
typedef enum
{
    BOOTUP_POPUP_TIMER = 38613 + 1, /* BASE_ID + 1 */
    RMGR_SCAN_DISK_TIMER,
    MMI_RP_APP_RMGR_TIMER_MAX
}mmi_rp_app_rmgr_timer_enum;
/******************** Timer resource IDs - finish ********************/
/******************** Template resource IDs - Begin ********************/
/******************** Template resource IDs - End ********************/

/******************** Venus XML resource IDs - Begin ********************/
typedef enum 
{

    MMI_RP_APP_RMGR_VXML_LAYOUT_MAX
} mmi_rp_app_rmgr_vxml_layout_enum;
/******************** Venus XML resource IDs - End ********************/



/******************** MMI Cache IDs - Begin ********************/
typedef enum
{
    NVRAM_RMGR_DB_CHECK = 38613 + 1, /* BASE_ID + 1 */          /*         BYTE */ 
    MMI_RP_APP_RMGR_MMI_CACHE_MAX
} mmi_rp_app_rmgr_mmi_cache_enum;
/******************** MMI Cache IDs - End ********************/


/******************** Image resource IDs - begin ********************/
typedef enum
{
    IMG_ID_RMGR_ICON = 38613 + 1, /* BASE_ID + 1 */
    IMG_ID_RMGR_LOCK,
    IMG_ID_RMGR_UNLOCK,
    MMI_RP_APP_RMGR_IMG_MAX
}mmi_rp_app_rmgr_img_enum;
/******************** Image resource IDs - finish ********************/


#endif /* _MMI_RP_APP_RMGR_DEF_H */
