/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_app_audioplayer_def.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   MTK resgenerator XML parser
 *
 *******************************************************************************/


#ifndef _MMI_RP_APP_AUDIOPLAYER_DEF_H
#define _MMI_RP_APP_AUDIOPLAYER_DEF_H




/******************** String resource IDs - begin ********************/
typedef enum
{
    STR_ID_AUDPLY_TITLE = 35855 + 1, /* BASE_ID + 1 */
    STR_ID_AUDPLY_LIST_FULL,
    STR_ID_AUDPLY_OPEN_FILE_ERROR,
    STR_ID_AUDPLY_COMMAND_ERROR,
    STR_ID_AUDPLY_DEVICE_BUSY,
    STR_ID_AUDPLY_BAD_FORMAT,
    STR_ID_AUDPLY_NO_SPACE,
    STR_ID_AUDPLY_ERROR,
    STR_ID_AUDPLY_UNSUPPORTED_CHANNEL,
    STR_ID_AUDPLY_UNSUPPORTED_FREQ,
    STR_ID_AUDPLY_UNSUPPORTED_TYPE,
    STR_ID_AUDPLY_NO_AUDIO_TRACK,
    STR_ID_AUDPLY_DECODER_NOT_SUPPORT,
    STR_ID_AUDPLY_UNSUPPORTED_SPEED,
    MMI_RP_APP_AUDIOPLAYER_STR_MAX
}mmi_rp_app_audioplayer_str_enum;
/******************** String resource IDs - finish ********************/


/******************** Screen resource IDs - begin ********************/
typedef enum
{
    SCR_ID_AUDPLY_BASE = 35855 + 1, /* BASE_ID + 1 */
    SCR_ID_AUDPLY_PLAY_ANIMATION,
    GRP_ID_AUDPLY_PLAY_ANIMATION,
    MMI_RP_APP_AUDIOPLAYER_SCR_MAX
}mmi_rp_app_audioplayer_scr_enum;
/******************** Screen resource IDs - finish ********************/


/******************** Timer resource IDs - begin ********************/
typedef enum
{
    AUDPLY_PROCESS_ADD_FILE_TIMER = 35855 + 1, /* BASE_ID + 1 */
    AUDPLY_COUNT_PLAY_TIMER,
    AUDPLY_DELAY_PLAY_TIMER,
    AUDPLY_SINGLE_PLAY_TIMER,
    AUDPLY_SEEKING_TIMER,
    AUDPLY_STATUS_ICON_TIMER,
    AUDPLY_DISPLAY_LYRICS_TIMER,
    MMI_RP_APP_AUDIOPLAYER_TIMER_MAX
}mmi_rp_app_audioplayer_timer_enum;
/******************** Timer resource IDs - finish ********************/
/******************** Template resource IDs - Begin ********************/
/******************** Template resource IDs - End ********************/

/******************** Venus XML resource IDs - Begin ********************/
typedef enum 
{

    MMI_RP_APP_AUDIOPLAYER_VXML_LAYOUT_MAX
} mmi_rp_app_audioplayer_vxml_layout_enum;
/******************** Venus XML resource IDs - End ********************/



/******************** MMI Cache IDs - Begin ********************/
typedef enum
{
    NVRAM_AUDPLY_SINGLE_VOL = 35855 + 1, /* BASE_ID + 1 */      /*         BYTE */ 
    MMI_RP_APP_AUDIOPLAYER_MMI_CACHE_MAX
} mmi_rp_app_audioplayer_mmi_cache_enum;
/******************** MMI Cache IDs - End ********************/


/******************** Image resource IDs - begin ********************/
typedef enum
{
    IMG_ID_AUDPLY_PLAY_ANIMATION = 35855 + 1, /* BASE_ID + 1 */
    MMI_RP_APP_AUDIOPLAYER_IMG_MAX
}mmi_rp_app_audioplayer_img_enum;
/******************** Image resource IDs - finish ********************/


#endif /* _MMI_RP_APP_AUDIOPLAYER_DEF_H */
