typedef enum
{
	SCR_ID_EM_XXX =  + 1,

	SCR_ID__ALL
} mmi_scr_id_enum;


typedef enum
{
	SCR_ID_PHNSET_POWER_ON =  + 1,
	SCR_ID_PHNSET_POWER_ON_SYSTEM_LIST,
	SCR_ID_PHNSET_POWER_ON_SYSTEM_VIEW,
	SCR_ID_PHNSET_POWER_ON_SYSTEM_VIEW_2,
	SCR_ID_PHNSET_POWER_ON_USER_VIEW,
	SCR_ID_PHNSET_POWER_OFF,
	SCR_ID_PHNSET_POWER_OFF_SYSTEM_LIST,
	SCR_ID_PHNSET_POWER_OFF_SYSTEM_VIEW,
	SCR_ID_PHNSET_POWER_OFF_SYSTEM_VIEW_2,
	SCR_ID_PHNSET_POWER_OFF_USER_VIEW,
	SCR_ID_PHNSET_POWER_ON_OFF_LAST,
	GRP_ID_POWER_ON_OFF_MAIN,
	GRP_ID_POWER_ON_OFF_SYSTEM,
	GRP_ID_POWER_ON_OFF_PREVIEW,
	SCR_ID_PHNSET_POWER_ON,
	SCR_ID_PHNSET_POWER_ON_SYSTEM_LIST,
	SCR_ID_PHNSET_POWER_ON_SYSTEM_VIEW,
	SCR_ID_PHNSET_POWER_ON_SYSTEM_VIEW_2,
	SCR_ID_PHNSET_POWER_ON_USER_VIEW,
	SCR_ID_PHNSET_POWER_OFF,
	SCR_ID_PHNSET_POWER_OFF_SYSTEM_LIST,
	SCR_ID_PHNSET_POWER_OFF_SYSTEM_VIEW,
	SCR_ID_PHNSET_POWER_OFF_SYSTEM_VIEW_2,
	SCR_ID_PHNSET_POWER_OFF_USER_VIEW,
	SCR_ID_PHNSET_POWER_ON_OFF_LAST,
	GRP_ID_POWER_ON_OFF_MAIN,
	GRP_ID_POWER_ON_OFF_SYSTEM,
	GRP_ID_POWER_ON_OFF_PREVIEW,

	SCR_ID_SRV_PHNSET_ONOFF_ALL
} mmi_srv_phnset_onoffscr_id_enum;


typedef enum
{
	SCR_ID_FUNANDGAMEG_GROUP = FUN_GAMES_BASE + 1,
	SCR_ID_IG_MAIN,

	SCR_ID_APP_FUNANDGAMES_ALL
} mmi_app_funandgamesscr_id_enum;


typedef enum
{
	SCR_EXTRA = EXTRA_APP_BASE + 1,
	SCR9147_APHORISM_TEXT,

	SCR_ID_APP_EXTRA_ALL
} mmi_app_extrascr_id_enum;


typedef enum
{
	GRP_ID_SHCT_QUICK_MENU_CFG =  + 1,
	GRP_ID_SHCT_DEDICATED_KEY_CFG,
	GRP_ID_SHCT_QUICK_MENU,
	SCR_ID_SHCT_IDLE_SHORTCUT,
	SCR_ID_SHCT_MAIN_MENU,
	SCR_ID_SHCT_EDIT,
	SCR_ID_SHCT_ORDER,
	SCR_ID_SHCT_DEDICATED_KEYS,
	SCR_ID_SHCT_EDIT_DEDICATED_KEYS,
	SCR_ID_SHCT_APP_SELECT,

	SCR_ID_APP_SHORTCUTS_ALL
} mmi_app_shortcutsscr_id_enum;


typedef enum
{
	SCR9003_INITIALSETUP =  + 1,
	SCR9146_WELCOME_TEXT,
	SETTINGS_SETHOMECITY_SCREENID,
	SCR_ID_PHNSET_UART_REBOOT_PROCESSING,
	GRP_ID_PHNSET_MENU,
	GRP_ID_PHNSET_DISP_SETUP,
	GRP_ID_PHNSET_TIME_DATE,
	GRP_ID_PHNSET_FLIGHT_MODE,
	GRP_ID_PHNSET_SCHEDULE_POWER,
	GRP_ID_PHNSET_UART_SETUP,
	GRP_ID_PHNSET_FONT_SIZE,
	GRP_ID_PHNSET_DEF_ENCODING_TYPE,
	GRP_ID_PHNSET_WELCOME_TEXT,
	SCR_LANGUAGE_SELECTION,
	GRP_ID_PHNSET_LANGUAGE,
	GRP_ID_PHNSET_DATETIME_MAIN,
	GRP_ID_PHNSET_SET_HOME_FOREIGN_CITY,
	GRP_ID_PHNSET_CHANGE_DATE_TIME,
	GRP_ID_PHNSET_SET_TIME_AND_DATE,
	GRP_ID_PHNSET_SET_TIME_AND_DATE_FORMAT,
	GRP_ID_PHNSET_SEPARATE_SET_DT_AND_FORMAT,
	GRP_ID_PHNSET_MAINMENU_STYLE,
	GRP_ID_PHNSET_DIAL_STYLE,
	GRP_ID_PHNSET_VUI_HOMESCREEN,
	GRP_ID_PHNSET_VUI_MAINMENU_EFFECT,
	GRP_ID_PHNSET_HOMESCREEN,
	GRP_ID_PHNSET_SCRSWITCH_EFFECT,
	GRP_ID_PHNSET_IDLE_CLOCK_TYPE,
	GRP_ID_PHNSET_SHOW_OPN,
	GRP_ID_PHNSET_SHOW_DT_TIME,
	GRP_ID_PHNSET_DUAL_CLOCK_IDLESCREEN,
	GRP_ID_PHNSET_CALENDAR_IDLESCREEN,
	GRP_ID_PHNSET_SHOW_OWNER_NUMBER,
	GRP_ID_SETTING_MAIN_MENU,
	GRP_ID_PHNSET_WIDGET_MGR,
	SCR_ID_PHNSET_WIDGET_MGR_DISP_SETTINGS,
	SCR_ID_PHNSET_WIDGET_MGR_ORDER_SETTINGS,
	SCR_ID_PHNSET_WIDGET_MGR_ORDER_SETTINGS_2,
	GRP_ID_PHNSET_SHORT_CUT,
	SCR_ID_PHNSET_SHORT_CUT,
	SCR9003_INITIALSETUP,
	SCR9146_WELCOME_TEXT,
	SETTINGS_SETHOMECITY_SCREENID,
	SCR_ID_PHNSET_UART_REBOOT_PROCESSING,
	GRP_ID_PHNSET_MENU,
	GRP_ID_PHNSET_DISP_SETUP,
	GRP_ID_PHNSET_TIME_DATE,
	GRP_ID_PHNSET_FLIGHT_MODE,
	GRP_ID_PHNSET_SCHEDULE_POWER,
	GRP_ID_PHNSET_UART_SETUP,
	GRP_ID_PHNSET_FONT_SIZE,
	GRP_ID_PHNSET_DEF_ENCODING_TYPE,
	GRP_ID_PHNSET_WELCOME_TEXT,
	SCR_LANGUAGE_SELECTION,
	GRP_ID_PHNSET_LANGUAGE,
	GRP_ID_PHNSET_DATETIME_MAIN,
	GRP_ID_PHNSET_SET_HOME_FOREIGN_CITY,
	GRP_ID_PHNSET_CHANGE_DATE_TIME,
	GRP_ID_PHNSET_SET_TIME_AND_DATE,
	GRP_ID_PHNSET_SET_TIME_AND_DATE_FORMAT,
	GRP_ID_PHNSET_SEPARATE_SET_DT_AND_FORMAT,
	GRP_ID_PHNSET_MAINMENU_STYLE,
	GRP_ID_PHNSET_DIAL_STYLE,
	GRP_ID_PHNSET_VUI_HOMESCREEN,
	GRP_ID_PHNSET_VUI_MAINMENU_EFFECT,
	GRP_ID_PHNSET_HOMESCREEN,
	GRP_ID_PHNSET_SCRSWITCH_EFFECT,
	GRP_ID_PHNSET_IDLE_CLOCK_TYPE,
	GRP_ID_PHNSET_SHOW_OPN,
	GRP_ID_PHNSET_SHOW_DT_TIME,
	GRP_ID_PHNSET_DUAL_CLOCK_IDLESCREEN,
	GRP_ID_PHNSET_CALENDAR_IDLESCREEN,
	GRP_ID_PHNSET_SHOW_OWNER_NUMBER,
	GRP_ID_SETTING_MAIN_MENU,
	GRP_ID_PHNSET_WIDGET_MGR,
	SCR_ID_PHNSET_WIDGET_MGR_DISP_SETTINGS,
	SCR_ID_PHNSET_WIDGET_MGR_ORDER_SETTINGS,
	SCR_ID_PHNSET_WIDGET_MGR_ORDER_SETTINGS_2,
	GRP_ID_PHNSET_SHORT_CUT,
	SCR_ID_PHNSET_SHORT_CUT,

	SCR_ID_APP_PHONESETTING_NEW_ALL
} mmi_app_phonesetting_newscr_id_enum;


typedef enum
{
	GRP_ID_CCONV =  + 1,
	SCR_ID_CCONV_RATE_INPUT,
	SCR_ID_CCONV_COMPUTE,
	SCR_ID_CCONV_SAVE_CONFIRM,

	SCR_ID_APP_CURRENCYCONVERTER_ALL
} mmi_app_currencyconverterscr_id_enum;


typedef enum
{
	SCR_ID_DTV_PLAYER_APP_BASE = DTV_PLAYER_BASE + 1,
	SCR_ID_DTV_PLAYER_APP,
	SCR_ID_DTV_PLAYER_OPTION_MENU,
	SCR_ID_DTV_PLAYER_CHANNEL_LIST,
	SCR_ID_DTV_PLAYER_BAND,
	SCR_ID_DTV_PLAYER_SAVE_CONFIRM,
	SCR_ID_DTV_PLAYER_SCANNING,
	SCR_ID_DTV_PLAYER_SAVING,
	SCR_ID_DTV_PLAYER_DELETING,
	SCR_ID_DTV_PLAYER_DUMMY,
	SCR_ID_DTV_PLAYER_UPDATE_LIST,
	SCR_ID_DTV_PLAYER_ESG_DOWNLOAD,
	SCR_ID_DTV_PLAYER_OPTION_EB_MSG_LIST,
	SCR_ID_DTV_PLAYER_CARD_INFO,
	SCR_ID_DTV_PLAYER_EB_MSG,
	SCR_ID_DTV_PLAYER_CHANNEL_DETAIL,
	SCR_ID_DTV_PLAYER_WARNING_MESSAGE,
	SCR_ID_DTV_PLAYER_HELP,
	SCR_ID_DTV_PLAYER_UPDATE_APPROACH,
	SCR_ID_DTV_PLAYER_SPECIFY_CITY,
	SCR_ID_DTV_PLAYER_TAB_ALL_CHANNEL,
	SCR_ID_DTV_PLAYER_TAB_FAVORITE_CHANNEL,
	SCR_ID_DTV_PLAYER_TAB_ACCOUNT_MANAGE,
	SCR_ID_DTV_PLAYER_TAB_PROGRAM_REMINDER,
	SCR_ID_DTV_PLAYER_CMMB_MODE_CONFIRM,
	SCR_ID_DTV_PLAYER_MBBMS_MODE_CONFIRM,
	SCR_ID_DTV_PLAYER_PROGRAM_LIST,
	SCR_ID_DTV_PLAYER_PROGRAM_DETAIL,
	SCR_ID_DTV_PLAYER_MBBMS_UPDATE,
	SCR_ID_DTV_PLAYER_MANAGE_ORDER_CONFIRM,
	SCR_ID_DTV_PLAYER_MANAGE_ORDER,
	SCR_ID_DTV_PLAYER_TAB_SUBSCRIBED_ORDER,
	SCR_ID_DTV_PLAYER_TAB_UNSUBSCRIBED_ORDER,
	SCR_ID_DTV_PLAYER_PROGRAM_DETAIL,
	SCR_ID_DTV_PLAYER_SEARCH_RESULT,
	SCR_ID_DTV_PLAYER_PROCESS,
	SCR_ID_DTV_PLAYER_CONFIRM,
	SCR_ID_DTV_PLAYER_CITY_LIST_RECOMMEND,
	SCR_ID_DTV_PLAYER_CITY_LIST_RECOMMEND,
	SCR_ID_DTV_PLAYER_CITY_LIST_LEVEL_1,
	SCR_ID_DTV_PLAYER_CITY_LIST_LEVEL_2,
	SCR_ID_DTV_PLAYER_CITY_LIST_LEVEL_3,
	SCR_ID_DTV_PLAYER_PLAY_INFO,
	SCR_ID_DTV_PLAYER_CONTENT_INTER,
	SCR_ID_DTV_PLAYER_SERVICE_INTER,
	SCR_ID_DTV_PLAYER_SERVICE_INTER_LIST,
	SCR_ID_DTV_PLAYER_STORAGE,
	SCR_ID_DTV_PLAYER_IMAGE_VIEWER,
	GRP_ID_DTV_PLAYER,
	GRP_ID_DTV_PLAYER_CL_SETTING,
	GRP_ID_DTV_PLAYER_CL_SETTING_OPTION,
	GRP_ID_DTV_PLAYER_CL_SETTING_RESTORE_CONFIRM,
	GRP_ID_DTV_PLAYER_FREQUENCY_MODE,
	SCR_ID_DTV_PLAYER_CMMB_SERVICE_TERMS,
	GRP_ID_DTV_CMMB_2GPP_HELP,

	SCR_ID_APP_DTV_PLAYER_ALL
} mmi_app_dtv_playerscr_id_enum;


typedef enum
{
	SCR_HEALTH_MENU =  + 1,

	SCR_ID_APP_HEALTH_ALL
} mmi_app_healthscr_id_enum;


typedef enum
{
	SCR_DICTIONARY_MAIN = DICTIONARY_BASE + 1,
	SCR_DICTIONARY_RESULT,
	SCR_DICTIONARY_OPTION,
	SCR_DICTIONARY_WILDCARD_EXACT_EDITOR,
	SCR_DICTIONARY_WILDCARD_RESULT_LIST,
	SCR_DICTIONARY_WELCOME_SCREEN,
	SCR_DICTIONARY_TTS_SETTING,

	SCR_ID_APP_DICTIONARY_ALL
} mmi_app_dictionaryscr_id_enum;


typedef enum
{
	GRP_ID_CHARGER_ROOT = CHARGER_BASE + 1,
	SCR_CHARGER_POWER_ON,
	SCR_CHARGING_COMPLETE,
	SCR_ABNORMAL_CHARGING,
	SCR_LOW_POWEROFF_SCR,

	SCR_ID_APP_CHARGER_ALL
} mmi_app_chargerscr_id_enum;


typedef enum
{
	SCR_ID_THM_MENU =  + 1,
	SCR_ID_THM_OPTIONS,
	SCR_ID_THM_UPDATE_PERIOD,
	SCR_ID_THM_SET_ORDER,
	SCR_ID_DOWNLOAD_THM_INFO,
	SCR_ID_DOWNLOAD_THM_STORAGE,
	SCR_ID_DOWNLOAD_THM_COMPLETE,
	SCR_ID_DOWNLOAD_ENTER_ADDRESS,
	SCR_ID_DOWNLOAD_EDIT_ADDRESS,
	SCR_ID_DOWNLOAD_DONE_OPTION,
	SCR_ID_DOWNLOAD_ENTER_ADDRESS_OPTIONS,
	SCR_ID_THEME_MOVE_CHECK_CONFIRM,
	SCR_ID_THEME_CONFIRM,
	SCR_ID_THEME_END,
	GRP_ID_THM_BEGIN,
	GRP_ID_THM_MAIN,
	GRP_ID_THM_SET_ORDER,
	GRP_ID_THM_DOWNLOAD,
	GRP_ID_THM_FMGR_ACTIVE,
	GRP_ID_THM_END,
	SCR_ID_THM_MENU,
	SCR_ID_THM_OPTIONS,
	SCR_ID_THM_UPDATE_PERIOD,
	SCR_ID_THM_SET_ORDER,
	SCR_ID_DOWNLOAD_THM_INFO,
	SCR_ID_DOWNLOAD_THM_STORAGE,
	SCR_ID_DOWNLOAD_THM_COMPLETE,
	SCR_ID_DOWNLOAD_ENTER_ADDRESS,
	SCR_ID_DOWNLOAD_EDIT_ADDRESS,
	SCR_ID_DOWNLOAD_DONE_OPTION,
	SCR_ID_DOWNLOAD_ENTER_ADDRESS_OPTIONS,
	SCR_ID_THEME_MOVE_CHECK_CONFIRM,
	SCR_ID_THEME_CONFIRM,
	SCR_ID_THEME_END,
	GRP_ID_THM_BEGIN,
	GRP_ID_THM_MAIN,
	GRP_ID_THM_SET_ORDER,
	GRP_ID_THM_DOWNLOAD,
	GRP_ID_THM_FMGR_ACTIVE,
	GRP_ID_THM_END,

	SCR_ID_SRV_MMI_THEME_ALL
} mmi_srv_mmi_themescr_id_enum;


typedef enum
{
	GRP_GB_WINGUO_NET_SCREEN = GB_WINGUO_NET_BASE + 1,
	SCR_GB_WINGUO_NET_SCREEN,

	SCR_ID_APP_GB_WINGUO_NET_ALL
} mmi_app_gb_winguo_netscr_id_enum;


typedef enum
{
	SCR_ID_CUI_SIM_SEL_LIST = CUI_SIM_SEL_BASE + 1,

	SCR_ID_CUI_SIM_SEL_ALL
} mmi_cui_sim_selscr_id_enum;


typedef enum
{
	SCR_ID_VS_MM_MAIN = SDK_TEST_BASE + 1,
	SCR_ID_VS_MM_AUDIO,
	SCR_ID_VS_MM_AUDIO_PLAY,
	SCR_ID_VS_MM_AUDIO_BG_PLAY,
	SCR_ID_VS_MM_AUDIO_RECORD,
	SCR_ID_VS_MM_AUDIO_TTS,
	SCR_ID_VS_MM_AUDIO_EQ,
	SCR_ID_VS_MM_AUDIO_REVERB,
	SCR_ID_VS_MM_AUDIO_SURROUND,
	SCR_ID_VS_MM_AUDIO_VIBRATOR,
	SCR_ID_VS_MM_AUDIO_SPECTRUM,
	SCR_ID_VS_MM_AUDIO_STRETCH,
	SCR_ID_VS_MM_AUDIO_SPEECH,
	SCR_ID_VS_MM_AUDIO_FRM,
	SCR_ID_VS_MM_AUDIO_MMA,
	SCR_ID_VS_MM_AUDIO_STREAM,
	SCR_ID_VS_MM_AUDIO_BASS,
	SCR_ID_VS_MM_AUDIO_BT_VOLUME,
	SCR_ID_VS_MM_AUDIO_FMR_RDS,
	SCR_ID_VS_MM_AUDIO_BG_PLAY_BY_APP,
	SCR_ID_VS_MM_AUDIO_030,
	SCR_ID_VS_MM_AUDIO_031,
	SCR_ID_VS_MM_AUDIO_032,
	SCR_ID_VS_MM_AUDIO_033,
	SCR_ID_VS_MM_AUDIO_034,
	SCR_ID_VS_MM_VIDEO,
	SCR_ID_VS_MM_VIDEO_FILE_OPTION,
	SCR_ID_VS_MM_VIDEO_FILE_SETTING,
	SCR_ID_VS_MM_VIDEO_001_FILE_PLAY,
	SCR_ID_VS_MM_VIDEO_0_FILE_PLAY,
	SCR_ID_VS_MM_VIDEO_007_CLIP_PLAY,
	SCR_ID_VS_MM_VIDEO_011,
	SCR_ID_VS_MM_VIDEO_012,
	SCR_ID_VS_MM_VIDEO_013,
	SCR_ID_VS_MM_VIDEO_014,
	SCR_ID_VS_MM_VIDEO_015,
	SCR_ID_VS_MM_CAMERA_011,
	SCR_ID_VS_MM_CAMERA_012,
	SCR_ID_VS_MM_CAMERA_013,
	SCR_ID_VS_MM_CAMERA_014,
	SCR_ID_VS_MM_CAMERA_015,
	SCR_ID_VS_MM_CAMERA,
	SCR_ID_VS_MM_DRM,
	SCR_ID_VS_MM_BITSTREAM,
	SCR_ID_VS_MM_BITSTREAM_AUDIO_RECORD,
	SCR_ID_VS_PROFILE_001,
	SCR_ID_VS_PROFILE_002,
	SCR_ID_VS_PROFILE_003,
	SCR_ID_VS_PROFILE_004,
	SCR_ID_VS_PROFILE_005,
	SCR_ID_VS_PROFILE_006,
	SCR_ID_VS_PROFILE_007,
	SCR_ID_VS_PROFILE_008,
	SCR_ID_VS_PROFILE_009,
	SCR_ID_VS_PROFILE_010,
	SCR_ID_VS_IDLESCREEN_001,
	SCR_ID_VS_IDLESCREEN_002,
	SCR_ID_VS_IDLESCREEN_003,
	SCR_ID_VS_IDLESCREEN_004,
	SCR_ID_VS_IDLESCREEN_005,
	SCR_ID_VS_IDLESCREEN_006,
	SCR_ID_VS_IDLESCREEN_007,
	SCR_ID_VS_IDLESCREEN_008,
	SCR_ID_VS_IDLESCREEN_009,
	SCR_ID_VS_IDLESCREEN_010,
	GRP_ID_AVK,
	SCR_ID_AVK_SCN_0,
	SCR_ID_AVK_SCN_1,
	SCR_ID_AVK_SCN_2,
	SCR_ID_AVK_SCN_3,
	SCR_ID_AVK_SCN_4,
	SCR_ID_AVK_SCN_5,
	SCR_ID_AVK_SCN_6,
	SCR_ID_AVK_SCN_7,
	SCR_ID_AVK_SCN_8,
	SCR_ID_AVK_SCN_9,
	SCR_ID_AVK_SCN_10,
	SCR_ID_AVK_SCN_11,
	SCR_ID_AVK_SCN_12,
	SCR_ID_AVK_SCN_13,
	SCR_ID_AVK_SCN_14,
	GRP_ID_1,
	GRP_ID_2,

	SCR_ID_APP_SDK_TEST_ALL
} mmi_app_sdk_testscr_id_enum;


typedef enum
{
	SCR_ID_ZAKAT_MAIN_OPTIONS =  + 1,
	SCR_ID_ZAKAT_CALCULATION_OPTIONS,
	SCR_ID_ZAKAT_ASSETS_OPTIONS,
	SCR_ID_ZAKAT_CATTLE_OPTIONS,
	SCR_ID_ZAKAT_BULLION_CASH_OPTIONS,
	SCR_ID_ZAKAT_GOLD_OPTIONS,
	SCR_ID_ZAKAT_AGRICULTURE_OPTIONS,
	SCR_ID_ZAKAT_DEDUCTIONS_OPTIONS,
	SCR_ID_ZAKAT_INPUT_OPTIONS,
	SCR_ID_ZAKAT_DESCRIPTION,
	SCR_ID_ZAKAT_COMMON_INPUT,
	SCR_ID_ZAKAT_24K_GOLD_SILVER_INPUT,
	SCR_ID_ZAKAT_GOLD_INPUT,
	SCR_ID_ZAKAT_SETTINGS,
	SCR_ID_ZAKAT_NISAB_INPUT,
	SCR_ID_ZAKAT_PAYABLE,
	SCR_ID_ZAKAT_DETAIL,

	SCR_ID_APP_ZAKAT_CALCULATOR_ALL
} mmi_app_zakat_calculatorscr_id_enum;


typedef enum
{
	SCR_ID_EC_CLB_CHOICE =  + 1,
	SCR_ID_EC_ROTATION,
	SCR_ID_EC_ANIMATION,
	SCR_ID_EC_DIRECTION,
	SCR_ID_EC_OPTIONS,
	SCR_ID_EC_SET_COUNTRY,
	SCR_ID_EC_SET_CITY,
	SCR_ID_EC_DECLINATION,
	SCR_ID_EC_MAN_CHOICE,

	SCR_ID_APP_ECOMPASS_ALL
} mmi_app_ecompassscr_id_enum;


typedef enum
{
	GRP_ID_BMI =  + 1,
	SCR_BMI_WELCOME,
	SCR_BMI_INPUT,
	SCR_BMI_RESULT,
	SCR_POPUP_HEALTH,

	SCR_ID_APP_HEALTHBMI_ALL
} mmi_app_healthbmiscr_id_enum;


typedef enum
{
	SCR_ID_CUI_USE_DETAIL_EDIT = CUI_USE_DETAIL_BASE + 1,
	SCR_ID_CUI_USE_DETAIL_VIEW_LIST,

	SCR_ID_CUI_USE_DETAIL_ALL
} mmi_cui_use_detailscr_id_enum;


typedef enum
{
	GRP_ID_BAIDU_SEARCH_WIDGET = VENUS_HS_WG_BAIDU_BASE + 1,
	VAPP_HS_SCR_WG_BAIDU_SEARCH_EDIT,
	VAPP_HS_SCR_WG_BAIDU_SEARCH_EDIT_OPTION,

	SCR_ID_APP_VENUS_HS_WG_BAIDU_ALL
} mmi_app_venus_hs_wg_baiduscr_id_enum;


typedef enum
{
	GRP_ID_MENU_EFFECT_PREVIEW =  + 1,
	SCR_ID_MENU_EFFECT_SWITCH_1,
	SCR_ID_MENU_EFFECT_SWITCH_2,
	GRP_ID_MENU_EFFECT_PREVIEW,
	SCR_ID_MENU_EFFECT_SWITCH_1,
	SCR_ID_MENU_EFFECT_SWITCH_2,

	SCR_ID_APP_SETTING_MENU_EFFECT_ALL
} mmi_app_setting_menu_effectscr_id_enum;


typedef enum
{
	SCR_ID_MOTION_DICE_APP =  + 1,
	SCR_ID_MOTION_DICE_PLAY,
	SCR_ID_MOTION_DICE_SHOW_EVENT,
	SCR_ID_MOTION_DICE_GAME_SETTING,
	SCR_ID_MOTION_DICE_EVENT_SETTING,
	SCR_ID_MOTION_DICE_HELP,
	SCR_ID_MOTION_DICE_EVENT_OPTION,
	SCR_ID_MOTION_DICE_EVENT_EDIT,
	SCR_ID_MOTION_DICE_EVENT_TEXT_EDITOR,
	SCR_ID_MOTION_DICE_EVENT_TEXT_EDITOR_OPTION,
	SCR_ID_MOTION_DICE_EVENT_FILE_SELECT_OPTION,
	SCR_ID_MOTION_DICE_EVENT_FILE_VIEW_IMAGE,
	SCR_ID_MOTION_DICE_EVENT_FILE_PLAY_VIDEO,
	NUM_OF_MOTION_DICE_SCR_ID,
	SCR_ID_MOTION_DJ_APP,
	SCR_ID_MOTION_DJ_SETTING,
	SCR_ID_MOTION_DJ_EDIT,
	SCR_ID_MOTION_DJ_PLAY,
	SCR_ID_MOTION_DJ_DUMMY,
	SCR_ID_MOTION_DJ_VOL_SETTING,
	SCR_ID_MOTION_DJ_HELP,
	NUM_OF_MOTION_DJ_SCR_ID,
	SCR_ID_GAME,
	SCR_ID_GAME_SETTING,
	SCR_ID_MOTION_APP,
	SCR_ID_3D_GAME_LIST,
	SCR_ID_3D_GAME,
	GFX_MENU_SCREEN,
	GFX_GAME_SCREEN,
	GFX_LEVEL_SCREEN,
	GFX_GRADE_SCREEN,
	GFX_HELP_SCREEN,
	GFX_GAMEOVER_SCREEN,

	SCR_ID_APP_GAMES_ALL
} mmi_app_gamesscr_id_enum;


typedef enum
{
	GRP_ID_IME_MENU = EDITOR_BASE + 1,
	GRP_ID_ADVANCE_SETTING_MENU,
	GRP_ID_FEEDBACK_SETTING_MENU,
	GRP_ID_AUTO_SPC_AND_CAP_MENU,
	GRP_ID_FUZZY_PINYIN_MENU,
	SCR_INPUT_LANG_FOLLOW_KEYBRD,
	GRP_ID_PHNSET_HANDWRITING,

	SCR_ID_SRV_EDITOR_ALL
} mmi_srv_editorscr_id_enum;


typedef enum
{
	GRP_ID_EM_ROOT = ENGINEER_MODE1_BASE + 1,
	SCR_ID_EM_CMN_SCRN,
	SCR_ID_EM_DUALMODE_SWITCH_PROGRESS,
	SCR_ID_EM_NW_INFO_LOG,
	SCR_ID_EM_NW_WCDMA_PRO,
	SCR_ID_EM_IVSR,
	SCR_ID_EM_NETWORK_NETWORK_EVENT_UPDATE,
	SCR_ID_EM_NETWORK_NETWORK_EVENT_FILTER_SETTING,
	SCR_ID_EM_NETWORK_NETWORK_EVENT_GROUP,
	SCR_ID_EM_3G_INFO,
	SCR_ID_EM_TDD,
	SCR_ID_EM_DEV_GPIO_LIST,
	SCR_ID_EM_DEV_EINT,
	SCR_ID_EM_DEV_ADC,
	SCR_ID_EM_DEV_UART_POWER_ONOFF_MENU,
	GRP_ID_EM_DEV_MTV_SETTING,
	GRP_ID_EM_DEV_VIDEO_SETTING,
	GRP_ID_EM_DEV_VIDEO_STREAMING_SETTING,
	SCR_ID_EM_DEV_USB_BOOT_MODE,
	SCR_ID_EM_DEV_FM_RADIO_RSSI_INFO,
	SCR_ID_EM_DEV_FM_RADIO_RSSI_INFO_OTHER,
	SCR_ID_EM_DEV_TST_OUTPUT_MODE,
	SCR_ID_EM_DEV_USB_LOGGING,
	GRP_ID_EM_DEV_CAM_AF_CONTSHOT,
	GRP_ID_EM_DEV_CAM_AF_CONTSHOT_AF_RANGE,
	GRP_ID_EM_DEV_CAM_AF_CONTSHOT_RAW_SAVE,
	GRP_ID_EM_DEV_CAM_AF_CONTSHOT_APP_START,
	GRP_ID_EM_DEV_CAM_AF_CONTSHOT_CAP_SIZE,
	GRP_ID_EM_DEV_CAM_AF_CONTSHOT_STORAGE,
	GRP_ID_EM_DEV_CAM_AF_CONTSHOT_SHADING,
	SCR_ID_EM_DEV_CAM_AF_CONTSHOT,
	SCR_ID_EM_DEV_CAM_AF_CONTSHOT_AF_RANGE,
	SCR_ID_EM_DEV_CAM_AF_CONTSHOT_RAW_SAVE,
	SCR_ID_EM_DEV_CAM_AF_CONTSHOT_RAW_SAVE_TYPE,
	SCR_ID_EM_DEV_CAM_AF_CONTSHOT_CAP_SIZE,
	SCR_ID_EM_DEV_CAM_AF_CONTSHOT_APP_START,
	SCR_ID_EM_DEV_CAM_AF_CONTSHOT_SHADING,
	SCR_ID_EM_DEV_MINIGPS_MAIN,
	SCR_ID_EM_DEV_MINIGPS_SKY_CHART,
	SCR_ID_EM_DEV_MINIGPS_STATUS,
	SCR_ID_EM_DEV_MINIGPS_NMEA,
	SCR_ID_EM_DEV_MINIGPS_SETTING,
	SCR_ID_EM_DEV_MINIGPS_TTFF,
	SCR_ID_EM_DEV_MINIGPS_MA_STATUS,
	SCR_ID_EM_MOTION_APP_SHOW,
	SCR_ID_EM_DEV_SPEECH_LCD,
	SCR_ID_EM_AUD_SIDE_TONE,
	SCR_ID_EM_PXS_RAW_DATA,
	SCR_ID_EM_NFC,
	GRP_ID_EM_NFC,
	SCR_ID_MMI_EM_NFC_START_PROGRESS,
	SCR_ID_MMI_EM_NFC_STOP_PROGRESS,
	SCR_ID_MMI_EM_NFC_TAG_DET_INFO,
	SCR_ID_MMI_EM_NFC_P2P_INFO,
	SCR_ID_MMI_EM_NFC_SHOW_TEXT,
	SCR_ID_EM_AUD_RING_TONE,
	SCR_ID_EM_AUD_RING_TONE_MENU,
	SCR_ID_EM_GPRS_SEND_DATA_EDITOR,
	SCR_ID_EM_GPRS_ACTIVATE_PDP_MENU,
	GRP_ID_FAST_DORMANCY,
	GRP_ID_EM_MISC_INET_APP_USER_AGENT,
	GRP_ID_EM_MISC_INET_APP_ACCEPT_HEADER,
	GRP_ID_EM_MISC_INET_APP_MMS_VERSION,
	GRP_ID_MMI_EM_MISC_CHECK_DRIVE,
	SCR_ID_MMI_EM_MISC_CHECK_DRIVE_ANIMATION,
	GRP_ID_EM_MISC_DM_SELF_REGISTER,
	SCR_ID_EM_MISC_DM_SELF_REGISTER,
	GRP_ID_EM_MISC_DM_SELF_REGISTER_RESULT_SIM,
	SCR_ID_EM_MISC_DM_SELF_REGISTER_RESULT_SIM,
	GRP_ID_EM_MISC_DM_SELF_REGISTER_PORT,
	SCR_ID_EM_MISC_DM_SELF_REGISTER_PORT,
	GRP_ID_EM_MISC_DCD_NW_PARAM,
	SCR_ID_EM_MISC_FOTA_DEBUG_UPGRADE_ANIMATION,
	SCR_ID_EM_MISC_AUTO_TEST_SETTING,
	SCR_ID_EM_MISC_AUTO_TEST_ADD,
	SCR_ID_EM_AUTO_TEST_ENTER_PRIORITY,
	SCR_ID_EM_MISC_AUTO_TEST_CHANGE_PRIORITY,
	SCR_ID_EM_MISC_TOUCH_SCREEN_PEN_EVENT,
	GRP_ID_EM_MISC_TOUCH_SCREEN_PEN_EVENT,
	GRP_ID_EM_MISC_TOUCH_SCREEN_ACCUCARY,
	SCR_ID_EM_MISC_TOUCH_SCREEN_ACC_ACCURACY,
	GRP_ID_EM_MISC_TOUCH_SCREEN_PARAM_SETTING,
	SCR_ID_EM_MISC_TOUCH_SCREEN_MULTI_TOUCH,
	GRP_ID_EM_MISC_TOUCH_SCREEN_MULTI_TOUCH,
	SCR_ID_EM_MISC_RF_DESENSE_LIST,
	SCR_ID_EM_MISC_RF_DESENSE_EDIT,
	SCR_ID_MMI_EM_DEBUG_DRIVE_LETTER,
	GRP_ID_IPERF,
	SCR_ID_EM_IPERF_SETTING,
	SCR_ID_EM_IPERF_REPORT,
	GRP_ID_EM_PROFILING_SWLA_RESULT_INFOR_GROUP,
	SCR_ID_EM_PROFILING_SWLA_RESULT_INFOR_SCRN,
	SCR_ID_EM_PROFILING_MEMORY_MONITOR,
	GRP_ID_EM_PROFILING_MEMORY_MONITOR,
	SCR_ID_EM_PROFILING_MEMORY_STATISTIC,
	GRP_ID_EM_PROFILING_MEMORY_STATISTIC,
	SCR_ID_EM_PROFILING_VENUS_DEBUG_PANEL,
	GRP_ID_EM_PROFILING_VENUS_DEBUG_PANEL,
	SCR_ID_EM_DUALMODE_SWITCH_PROGRESS,
	GRP_ID_CONF_TEST,
	GRP_ID_CONF_TEST_CTA,
	GRP_ID_CONF_TEST_OPERATOR_TEST,
	SCR_ID_EM_RF_TEST_GSM_POWER_SCAN_RESULT,
	SCR_ID_EM_RF_WIFI_TX_DAC_OFFSET,
	SCR_ID_EM_RF_WIFI_RX_CONT_PKT,

	SCR_ID_APP_ENGINEERMODE1_ALL
} mmi_app_engineermode1scr_id_enum;


typedef enum
{
	SCR_ID_NMGR_MESSGAGE_CONFIRM = SRV_NMGR_BASE + 1,
	SCR_ID_ALARM_SUBLCD_IND,
	SCR_ID_UCM_INCOMING_CALL_SUBLCD,
	SCR_ID_UCM_OUTGOING_CALL_SUBLCD,

	SCR_ID_SRV_NMGR_ALL
} mmi_srv_nmgrscr_id_enum;


typedef enum
{
	SCR_ID_VIEW_SETTING_COMMON_FILE_PREVIEW =  + 1,
	SCR_ID_VIEW_SETTING_COMMON_WAITING_POPUP,
	GRP_ID_VIEW_SETTING_COMMON_FMGR,
	GRP_ID_VIEW_SETTING_FILE_COMMON_PREVIEW,
	SCR_ID_VIEW_SETTING_COMMON_FILE_PREVIEW,
	SCR_ID_VIEW_SETTING_COMMON_WAITING_POPUP,
	GRP_ID_VIEW_SETTING_COMMON_FMGR,
	GRP_ID_VIEW_SETTING_FILE_COMMON_PREVIEW,

	SCR_ID_APP_VIEWSETTING_ALL
} mmi_app_viewsettingscr_id_enum;


typedef enum
{
	GRP_ID_VAPP_WALLPAPER_MRE_ASM =  + 1,

	SCR_ID_VAPP_WALLPAPER_MRE_ALL
} mmi_vapp_wallpaper_mrescr_id_enum;


typedef enum
{
	SCR_ID_DLS_WAIT =  + 1,
	SCR_ID_DLS_QUERY,

	SCR_ID_APP_MRE_ALL
} mmi_app_mrescr_id_enum;


typedef enum
{
	SCR_ID_NMGR_DUMMY = APP_IDLE_NMGR_BASE + 1,
	SCR_ID_NMGR_NOTIFY,
	SCR_ID_NMGR_NOTIFY_ON_IDLE,

	SCR_ID_APP_IDLE_NMGR_ALL
} mmi_app_idle_nmgrscr_id_enum;


typedef enum
{
	GRP_ID_IDLE_SIM_SPACE = APP_SIMSPACE_BASE + 1,
	SCR_ID_IDLE_SIM_SPACE_VIEW,
	SCR_ID_IDLE_SIM_SPACE_SETTING,

	SCR_ID_APP_SIMSPACE_ALL
} mmi_app_simspacescr_id_enum;


typedef enum
{
	SCR_ID_ALIPAY_DEMO = APP_ALIPAY_ADP_BASE + 1,
	SCR_ID_ALIPAY_START,
	SCR_ID_ALIPAY_INPUT,

	SCR_ID_APP_ALIPAY_ADP_ALL
} mmi_app_alipay_adpscr_id_enum;


typedef enum
{
	GRP_ID_SSV_MAIN = APP_SCR_SAVER_BASE + 1,
	SCR_ID_SSV_MAIN,

	SCR_ID_APP_SCR_SAVER_ALL
} mmi_app_scr_saverscr_id_enum;


typedef enum
{
	GRP_ID_DMAPP_SETTING = SRV_DM_BASE + 1,
	GRP_ID_DMAPP_GLOBAL,
	GRP_ID_DMAPP_OTA,
	SCR_ID_DM_NOTIFICATION_CNF,
	SCR_ID_DM_ALERT_CNF,
	SCR_ID_DMUI_MAIN,
	SCR_ID_DMUI_OPTION,
	SCR_ID_DMUI_UPDATE,
	SCR_ID_DMUI_UPDATE_DEFER,
	SCR_ID_DMUI_DOWNLOAD,
	SCR_ID_DMUI_DOWNLOAD_PROGRESS,
	SCR_ID_DMUI_ENTER_PIN,
	SCR_ID_DMUI_REBOOT,
	SCR_ID_DMUI_ALERT_INPUT,
	SCR_ID_DMUI_VIEW_INFO,
	SCR_ID_DMUI_ALERT_SINGLE_CHOICE,
	SCR_ID_DMUI_ALERT_MULTI_CHOICE,
	SCR_ID_DMUI_WAITING,
	SCR_ID_DMUI_OTA_CONFIRM,
	SCR_ID_DM_OTA_PROVISIONING_INFO,
	SCR_ID_DM_OTA_SERVERID_LIST,
	SCR_ID_DMUI_PROMPT_MESSAGE,
	SCR_ID_DMUI_POPUP,
	SCR_ID_DMUI_POPUP_CONFIRM,
	SCR_ID_DM_DL_RESUME_CNF,

	SCR_ID_SRV_DM_ALL
} mmi_srv_dmscr_id_enum;


typedef enum
{
	VAPP_HS_SCR_CLOCK_SETTING = VENUS_HOMESCREEN_WIDGET_CLOCK_BASE + 1,
	VAPP_HS_SCR_CLOCK_DISPLAY_SETTING,

	SCR_ID_APP_VENUS_HOMESCREEN_WG_CLOCK_ALL
} mmi_app_venus_homescreen_wg_clockscr_id_enum;


typedef enum
{
	SCR_ID_SML_LOCK_MENU = APP_SIM_ME_LOCK_BASE + 1,
	SCR_ID_SML_UNLOCK_MENU,
	SCR_ID_SML_ADD_MENU,
	SCR_ID_SML_REMOVE_MENU,
	SCR_ID_SML_DEACTIVATE_MENU,
	SCR_ID_SML_QUERY_POPUP,
	SCR_ID_SML_FILL_DATA,
	SCR_ID_SML_AUTOKEY_CONFIRM,
	SCR_ID_SML_REMOVE_CONFIRM,
	SCR_ID_SML_DEACTIVATE_CONFIRM,
	SCR_ID_SML_INPUT_KEY,
	SCR_ID_SML_CONFIRM_KEY,
	SCR_ID_SML_DUMMY,
	GRP_ID_SML_SIMS,
	GRP_ID_SML_MAIN,
	GRP_ID_SML_DATA,
	GRP_ID_SML_PSWD,

	SCR_ID_APP_SIM_ME_LOCK_ALL
} mmi_app_sim_me_lockscr_id_enum;


typedef enum
{
	SCR_MAIN_WALLPAPER =  + 1,
	SCR_MAIN_WALLPAPER_FIX,
	SCR_WALLPAPER_SYSTEM_LIST,
	SCR_WALLPAPER_VIEW,
	SCR_WALLPAPER_VIEW_2,
	SCR_WALLPAPER_DOWNLOAD_VIEW,
	SCR_ID_PHNSET_IDLE_CLOCK_TYPE,
	SCR_IDLE_SCR_DISP_WP_PREVIEW,
	SCR_IDLE_SCR_DISP_WPSS_WAITING,
	GRP_ID_DISPLAY_FMGR_COMMON,
	GRP_ID_WALLPAPER_MAIN,
	GRP_ID_WALLPAPER_SYSTEM,
	GRP_ID_WALLPAPER_SYSTEM_SUB,
	GRP_ID_WALLPAPER_PREVIEW,
	GRP_ID_WALLPAPER_LIVE_WALLPAPER,
	GRP_ID_WALLPAPER_ROTATE,
	GRP_ID_WALLPAPER_HOME_WALLPAPER,
	GRP_ID_WALLPAPER_LOCK_WALLPAPER,
	SCR_MAIN_WALLPAPER,
	SCR_MAIN_WALLPAPER_FIX,
	SCR_WALLPAPER_SYSTEM_LIST,
	SCR_WALLPAPER_VIEW,
	SCR_WALLPAPER_VIEW_2,
	SCR_WALLPAPER_DOWNLOAD_VIEW,
	SCR_ID_PHNSET_IDLE_CLOCK_TYPE,
	SCR_IDLE_SCR_DISP_WP_PREVIEW,
	SCR_IDLE_SCR_DISP_WPSS_WAITING,
	GRP_ID_DISPLAY_FMGR_COMMON,
	GRP_ID_WALLPAPER_MAIN,
	GRP_ID_WALLPAPER_SYSTEM,
	GRP_ID_WALLPAPER_SYSTEM_SUB,
	GRP_ID_WALLPAPER_PREVIEW,
	GRP_ID_WALLPAPER_LIVE_WALLPAPER,
	GRP_ID_WALLPAPER_ROTATE,
	GRP_ID_WALLPAPER_HOME_WALLPAPER,
	GRP_ID_WALLPAPER_LOCK_WALLPAPER,

	SCR_ID_SRV_WALLPAPER_ALL
} mmi_srv_wallpaperscr_id_enum;


typedef enum
{
	GRP_ID_NTP_APP =  + 1,
	GRP_ID_NTP_APP,

	SCR_ID_APP_NTP_ALL
} mmi_app_ntpscr_id_enum;


typedef enum
{
	SCR_ID_SCREEN_LOCK_KEY_IMG_SETTING_SYS = APP_SCREEN_LOCK_KEY_IMG_SETTING_BASE + 1,
	SCR_ID_SCREEN_LOCK_KEY_IMG_SETTING_USR_STORE,
	SCR_ID_SCREEN_LOCK_KEY_IMG_SETTING_SYS,
	SCR_ID_SCREEN_LOCK_KEY_IMG_SETTING_USR_STORE,

	SCR_ID_APP_SCREEN_LOCK_KEY_IMG_SETTING_ALL
} mmi_app_screen_lock_key_img_settingscr_id_enum;


typedef enum
{
	SCR_MAIN_SCREENSAVER =  + 1,
	SCR_SCREENSAVER_SETTING,
	SCR_SCREENSAVER_SELECT,
	SCR_SCREENSAVER_SYSTEM_LIST,
	SCR_SCREENSAVER_VIEW,
	SCR_SCREENSAVER_VIEW_2,
	SCR_SCREENSAVER_DOWNLOAD_VIEW,
	GRP_ID_SCREENSAVER_SETTING,
	GRP_ID_SCREENSAVER_SYSTEM,
	GRP_ID_SCREENSAVER_MAIN,
	SCR_MAIN_SCREENSAVER,
	SCR_SCREENSAVER_SETTING,
	SCR_SCREENSAVER_SELECT,
	SCR_SCREENSAVER_SYSTEM_LIST,
	SCR_SCREENSAVER_VIEW,
	SCR_SCREENSAVER_VIEW_2,
	SCR_SCREENSAVER_DOWNLOAD_VIEW,
	GRP_ID_SCREENSAVER_SETTING,
	GRP_ID_SCREENSAVER_SYSTEM,
	GRP_ID_SCREENSAVER_MAIN,

	SCR_ID_SRV_SCREENSAVER_ALL
} mmi_srv_screensaverscr_id_enum;


typedef enum
{
	SCR_ID_MCARE_LIST =  + 1,
	GRP_ID_MCARE_LIST,
	GRP_ID_MCARE_TOTAL,

	SCR_ID_TENCENT_MCARE_ALL
} mmi_tencent_mcarescr_id_enum;


typedef enum
{
	GRP_ID_A2DP_SETTINGS = A2DP_BASE + 1,
	SCR_ID_A2DP_SETTINGS,

	SCR_ID_APP_A2DP_ALL
} mmi_app_a2dpscr_id_enum;


typedef enum
{
	SCR_ID_MOBILE_TV_PLAYER_APP_BASE = MOBILE_TV_PLAYER_BASE + 1,
	SCR_ID_MOBILE_TV_PLAYER_APP,
	SCR_ID_MOBILE_TV_PLAYER_OPTION_MENU,
	SCR_ID_MOBILE_TV_PLAYER_CHANNEL_LIST,
	SCR_ID_MOBILE_TV_PLAYER_BAND,
	SCR_ID_MOBILE_TV_PLAYER_SAVE_CONFIRM,
	SCR_ID_MOBILE_TV_PLAYER_SCANNING,
	SCR_ID_MOBILE_TV_PLAYER_SAVING,
	SCR_ID_MOBILE_TV_PLAYER_DELETING,
	SCR_ID_MOBILE_TV_PLAYER_DUMMY,
	SCR_ID_MOBILE_TV_PLAYER_UPDATE_LIST,
	SCR_ID_MOBILE_TV_PLAYER_ESG_DOWNLOAD,
	SCR_ID_MOBILE_TV_PLAYER_OPTION_EB_MSG_LIST,
	SCR_ID_MOBILE_TV_PLAYER_CARD_INFO,
	SCR_ID_MOBILE_TV_PLAYER_EB_MSG,
	SCR_ID_MOBILE_TV_PLAYER_CHANNEL_DETAIL,
	SCR_ID_MOBILE_TV_PLAYER_WARNING_MESSAGE,
	SCR_ID_MOBILE_TV_PLAYER_HELP,
	SCR_ID_MOBILE_TV_PLAYER_UPDATE_APPROACH,
	SCR_ID_MOBILE_TV_PLAYER_SPECIFY_CITY,
	SCR_ID_MOBILE_TV_PLAYER_TAB_ALL_CHANNEL,
	SCR_ID_MOBILE_TV_PLAYER_TAB_FAVORITE_CHANNEL,
	SCR_ID_MOBILE_TV_PLAYER_TAB_PROGRAM_REMINDER,
	SCR_ID_MOBILE_TV_PLAYER_CMMB_MODE_CONFIRM,
	SCR_ID_MOBILE_TV_PLAYER_MBBMS_MODE_CONFIRM,
	SCR_ID_MOBILE_TV_PLAYER_PROGRAM_LIST,
	SCR_ID_MOBILE_TV_PLAYER_PROGRAM_DETAIL,
	SCR_ID_MOBILE_TV_PLAYER_MBBMS_UPDATE,
	SCR_ID_MOBILE_TV_PLAYER_MANAGE_ORDER_CONFIRM,
	SCR_ID_MOBILE_TV_PLAYER_MANAGE_ORDER,
	SCR_ID_MOBILE_TV_PLAYER_TAB_SUBSCRIBED_ORDER,
	SCR_ID_MOBILE_TV_PLAYER_TAB_UNSUBSCRIBED_ORDER,
	SCR_ID_MOBILE_TV_PLAYER_PROGRAM_DETAIL,
	SCR_ID_MOBILE_TV_PLAYER_SEARCH_RESULT,
	SCR_ID_MOBILE_TV_PLAYER_PROCESS,
	GRP_ID_MOBILE_TV_PLAYER,
	GRP_ID_MOBILE_TV_PLAYER_CL_SETTING,
	GRP_ID_MOBILE_TV_PLAYER_CL_SETTING_OPTION,
	GRP_ID_MOBILE_TV_PLAYER_CL_SETTING_RESTORE_CONFIRM,

	SCR_ID_APP_MOBILE_TV_PLAYER_ALL
} mmi_app_mobile_tv_playerscr_id_enum;


typedef enum
{
	GRP_ID_AM = AM_BASE + 1,
	SCR_ID_AM_LOADING,
	SCR_ID_AM_LAUNCH_APP_LOADING,
	SCR_ID_AM_MAIN,
	SCR_ID_AM_UPDATE_CDR,
	SCR_ID_AM_UPDATE_CDR_WAIT,
	SCR_ID_AM_DETAILS,
	SCR_ID_DLA_APP,
	SCR_ID_DLA_MAIN,
	SCR_ID_DLA_LIST,
	SCR_ID_DLA_LIST_DETAIL,
	SCR_ID_AM_PSMGR_APP,
	SCR_ID_AM_PSMGR_MAIN,
	GRP_ID_AM,
	SCR_ID_AM_LAUNCH_APP_LOADING,

	SCR_ID_APP_AM_ALL
} mmi_app_amscr_id_enum;


typedef enum
{
	SCR_ID_MCARE_LIST = APP_TENCENT_MCARE_BASE + 1,
	GRP_ID_MCARE_LIST,
	GRP_ID_MCARE_TOTAL,

	SCR_ID_APP_TENCENT_MCARE_ALL
} mmi_app_tencent_mcarescr_id_enum;


typedef enum
{
	GRP_ID_CALC =  + 1,
	SCR_ID_CALC_APP,
	GRP_ID_CALC_OPTION,

	SCR_ID_APP_CALCULATOR_ALL
} mmi_app_calculatorscr_id_enum;


typedef enum
{
	GRP_ID_IDLE_MAIN = APP_IDLE_BASE + 1,
	SCR_ID_IDLE_MAIN,
	SCR_ID_IDLE_SUBLCD,

	SCR_ID_APP_IDLE_ALL
} mmi_app_idlescr_id_enum;


typedef enum
{
	GRP_ID_NSS_GROUP =  + 1,
	SRN_ID_NSS_APPLIST_SCREEN,
	SRN_ID_NSS_BACKGROUND_DATA_SCREEN,
	GRP_ID_NSS_GROUP,
	SRN_ID_NSS_APPLIST_SCREEN,
	SRN_ID_NSS_BACKGROUND_DATA_SCREEN,

	SCR_ID_APP_NSS_ALL
} mmi_app_nssscr_id_enum;


typedef enum
{
	SCR_ID_APP_DEVAPP = DEVAPP_BASE + 1,

	SCR_ID_APP_DEVAPP_ALL
} mmi_app_devappscr_id_enum;


typedef enum
{
	VAPP_HS_SCR_WG_MEMO_EDIT = VENUS_HOMESCREEN_WIDGET_MEMO_BASE + 1,
	VAPP_HS_SCR_WG_MEMO_EDIT_OPTION,

	SCR_ID_APP_VENUS_HOMESCREEN_WG_MEMO_ALL
} mmi_app_venus_homescreen_wg_memoscr_id_enum;


typedef enum
{
	SCR_COMPOSE_RINGTONE =  + 1,
	SCR_ID_RNGC_MAIN,
	SCR_COMPOSE_RINGTONE_OPTION,
	SCR_COMPOSE_RINGTONE_OPTION_PLAY,
	SCR_COMP_RINGTONE_ADD_OPT,
	SCR_COMP_RINGTONE_SPEED,
	SCR_COMP_RINGTONE_STYLE,
	SCR_COMP_RINGTONE_INSTRUMENT,
	SCR_COMP_RINGTONE_SAVEFILE,
	SCR_COMP_RINGTONE_SAVE_OPT,
	SCR_COMPOSER_ENGINE,
	SCR_COMPOSE_RINGTONE_DELETE,
	SCR_COMPOSE_RINGTONE_DELETE_CNF,
	SCR_COMP_RINGTONE_SAVE_CNF,

	SCR_ID_APP_RINGTONECOMPOSER_ALL
} mmi_app_ringtonecomposerscr_id_enum;


typedef enum
{
	GRP_ID_PHNSET_SCHEDULE_POWER_CONFIRM =  + 1,
	SCR_ID_SPOF_CONFIRM,
	GRP_ID_PHNSET_SCHEDULE_POWER_CONFIRM,
	SCR_ID_SPOF_CONFIRM,

	SCR_ID_SRV_SPOF_ALL
} mmi_srv_spofscr_id_enum;


typedef enum
{
	CUI_INLINE_MAIN_SCREEN_SCRN_ID = INLINE_EDITOR_BASE + 1,
	CUI_INLINE_FULLSCREEN_EDIT_SCRN_ID,
	CUI_INLINE_FULLSCREEN_OPTION_LIST_SCRN_ID,
	CUI_INLINE_IMAGETEXT_EDIT_SCRN_ID,
	CUI_INLINE_IMAGETEXT_OPIONT_LIST_SCRN_ID,

	SCR_ID_SRV_INLINE_EDITOR_ALL
} mmi_srv_inline_editorscr_id_enum;


typedef enum
{
	GRP_ID_UCONV =  + 1,
	SCR_ID_UCONV_MENU,
	SCR_ID_UCONV_WEIGHT,
	SCR_ID_UCONV_LENGTH,

	SCR_ID_APP_UNITCONVERTER_ALL
} mmi_app_unitconverterscr_id_enum;


typedef enum
{
	GRP_ID_NETSET_MAIN =  + 1,
	GRP_ID_NETSET_NW_SELECT,
	GRP_ID_NETSET_PREF_MODE,
	GRP_ID_NETSET_PREF_LIST,
	GRP_ID_NETSET_SERVICE_SELECTION,
	GRP_ID_NETSET_3G_SERVICE_SWITCH,
	SCR_ID_NETSET_MAIN,
	SCR_ID_NETSET_SIM,
	SCR_ID_NETSET_NETWORK_SELECTION,
	SCR_ID_NETSET_NETWORK_SELECTION_REGISTER_PROGRESS,
	SCR_ID_NETSEL_AUTO_REGISTER_PROGRESS,
	SCR_ID_NETSEL_MANUAL_SEARCH_PROGRESS,
	SCR_ID_NETSEL_MANUAL_REGISTER_PROGRESS,
	SCR_ID_NETSEL_MANUAL_SEARCH_SHOW_PLMN,
	SCR_ID_NETSEL_SELECT_MODE,
	SCR_ID_NETSEL_ADDTIONAL_INFORMATION,
	SCR_ID_NETSEL_ADDTIONAL_INFORMATION_PROGRESS,
	SCR_ID_NETSET_PREF_LIST,
	SCR_ID_NETSET_PREF_LIST_OPT_ADD_NWK_LIST,
	SCR_ID_NETSET_PREF_LIST_OPT_ADD_NWK_LIST_INFO,
	SCR_ID_NETSET_PREF_MODE,
	SCR_ID_NETSET_PREF_MODE_PROGRESS,
	SCR_ID_NETSET_SERVICE_SELECTION,
	SCR_ID_NETSET_SET_RAT_PROGRESS,
	SCR_ID_NETSET_RAT_QUERY,
	SCR_ID_NETSET_NETWORK_INFO,
	SCR_ID_NETSET_GPRS_CONNECTION,
	SCR_ID_NETSET_SET_GPRS_PROGRESS,
	SCR_ID_NETSET_SET_PCH_PROGRESS,
	SCR_ID_NETSET_SET_PCH_CONFIRM,
	SCR_ID_NETSET_HSPA,
	SCR_ID_NETSET_HSPA_PROGRESS,
	SCR_ID_NETSET_HSPA_LIST,
	SCR_ID_NETSET_3G_SERVICE_SWITCH,
	SCR_ID_NETSET_3G_SERVICE_SWITCH_PROGRESS,
	GRP_ID_NETSET_MAIN,
	GRP_ID_NETSET_NW_SELECT,
	GRP_ID_NETSET_PREF_MODE,
	GRP_ID_NETSET_PREF_LIST,
	GRP_ID_NETSET_SERVICE_SELECTION,
	GRP_ID_NETSET_3G_SERVICE_SWITCH,
	SCR_ID_NETSET_MAIN,
	SCR_ID_NETSET_SIM,
	SCR_ID_NETSET_NETWORK_SELECTION,
	SCR_ID_NETSET_NETWORK_SELECTION_REGISTER_PROGRESS,
	SCR_ID_NETSEL_AUTO_REGISTER_PROGRESS,
	SCR_ID_NETSEL_MANUAL_SEARCH_PROGRESS,
	SCR_ID_NETSEL_MANUAL_REGISTER_PROGRESS,
	SCR_ID_NETSEL_MANUAL_SEARCH_SHOW_PLMN,
	SCR_ID_NETSEL_SELECT_MODE,
	SCR_ID_NETSEL_ADDTIONAL_INFORMATION,
	SCR_ID_NETSEL_ADDTIONAL_INFORMATION_PROGRESS,
	SCR_ID_NETSET_PREF_LIST,
	SCR_ID_NETSET_PREF_LIST_OPT_ADD_NWK_LIST,
	SCR_ID_NETSET_PREF_LIST_OPT_ADD_NWK_LIST_INFO,
	SCR_ID_NETSET_PREF_MODE,
	SCR_ID_NETSET_PREF_MODE_PROGRESS,
	SCR_ID_NETSET_SERVICE_SELECTION,
	SCR_ID_NETSET_SET_RAT_PROGRESS,
	SCR_ID_NETSET_RAT_QUERY,
	SCR_ID_NETSET_NETWORK_INFO,
	SCR_ID_NETSET_GPRS_CONNECTION,
	SCR_ID_NETSET_SET_GPRS_PROGRESS,
	SCR_ID_NETSET_SET_PCH_PROGRESS,
	SCR_ID_NETSET_SET_PCH_CONFIRM,
	SCR_ID_NETSET_HSPA,
	SCR_ID_NETSET_HSPA_PROGRESS,
	SCR_ID_NETSET_HSPA_LIST,
	SCR_ID_NETSET_3G_SERVICE_SWITCH,
	SCR_ID_NETSET_3G_SERVICE_SWITCH_PROGRESS,

	SCR_ID_APP_NETSET_ALL
} mmi_app_netsetscr_id_enum;


typedef enum
{
	GRP_ID_SETTING_VERSION =  + 1,
	SCR_ID_VERSION_INFO,
	GRP_ID_SETTING_VERSION,
	SCR_ID_VERSION_INFO,

	SCR_ID_APP_SETTING_VERSION_ALL
} mmi_app_setting_versionscr_id_enum;


typedef enum
{
	GRP_ID_SLK_MAIN = APP_SCR_LOCKER_BASE + 1,
	SCR_ID_SLK_MAIN,
	GRP_ID_SLK_SETTING,
	SCR_ID_SLK_POPUP,

	SCR_ID_APP_SCR_LOCKER_ALL
} mmi_app_scr_lockerscr_id_enum;


typedef enum
{
	GRP_ID_FONT_MGR = FONT_MANAGER_BASE + 1,
	SCR_ID_FONT_MGR_FONT_LIST,
	SCR_ID_FONT_MGR_FONT_LIST_OPTION,
	SCR_ID_FONT_MGR_FONT_LIST_SET_PRIORITY,
	SCR_ID_FONT_MGR_ACTIVATE_QUERY,

	SCR_ID_APP_FONT_MANAGER_ALL
} mmi_app_font_managerscr_id_enum;


typedef enum
{
	SCR_RESTORE =  + 1,
	SCR_RESTORE_PROCESSING,
	SCR_SETTING_RESTORE_CONFIRM,
	GRP_ID_PHNSET_RESTORE,
	SCR_RESTORE,
	SCR_RESTORE_PROCESSING,
	SCR_SETTING_RESTORE_CONFIRM,
	GRP_ID_PHNSET_RESTORE,

	SCR_ID_APP_RESTORE_ALL
} mmi_app_restorescr_id_enum;


typedef enum
{
	SCR_ID_OP11_HS_PERSONALISATION = APP_OP11_HS32_BASE + 1,
	SCR_ID_OP11_HS_EDIT_HS_ITEM,
	SCR_ID_OP11_HS_SELECT_HS_ITEM,
	SCR_ID_OP11_HS_PLACE_HS_ITEM,
	SCR_ID_OP11_HS_PLACE_HS_AGAIN,
	SCR_ID_OP11_HS_ADD_HS_ITEM_SELECT,
	SCR_ID_OP11_HS_ADD_HS_ITEM_PLACE,
	SCR_ID_OP11_HS_ADD_HS_ITEM_REORDER,
	SCR_ID_OP11_HS_REMOVE_HS_ITEM,
	SCR_ID_OP11_HS_REMOVE_HS_ITEM_CONF,
	SCR_ID_OP11_HS_OPTIONS,
	SCR_ID_OP11_HS_MORE_SETTING,
	SCR_ID_OP11_HS_SETTING_CLK_SIZE,
	SCR_ID_OP11_HS_SETTING_DUAL_CLK,
	SCR_ID_OP11_HS_SETTING_SHOW_MY_NUM,
	SCR_ID_OP11_HS_DUMMY,
	SCR_ID_OP11_HS_SET_VIP,
	SCR_ID_OP11_HS_EDIT_VIP,
	SCR_ID_OP11_HS_SET_ACCOUNT,
	SCR_ID_OP11_HS_EDIT_ACCOUNT,
	SCR_ID_OP11_HS_DEV_STATUS,
	SCR_ID_OP11_HS_US_VIP,
	SCR_ID_OP11_HS_VIP_OPTION,
	SCR_ID_OP11_HS_WP_MGR,
	SCR_ID_OP11_HS_WP_SEL,
	SCR_ID_OP11_HS_WP_ATTACH,
	SCR_ID_OP11_HS_SETTING_KEYPAD_SEARCH,
	SCR_ID_OP11_HS_MORE_SETTING_HELP,
	SCR_ID_OP11_RRD_SHCT_SELECT,
	SCR_ID_OP11_RRD_SHCT_PLACE,
	SCR_ID_OP11_HS_MAX_ITEMS_REACHED,
	SCR_ID_OP11_HS_INPUT_MY_NUMBER,
	SCR_ID_OP11_HS_EDIT_SIDEBAR_ICONS,
	SCR_ID_OP11_HS_FLIGHTMODE_PROGRESS,

	SCR_ID_APP_OP11_HS32_ALL
} mmi_app_op11_hs32scr_id_enum;


typedef enum
{
	SCR_ID_HS_WRITE_MESSAGE = IDLE_APP_HS_BASE + 1,
	SCR_ID_HS_MENU_SETTING,
	SCR_ID_HS_MENU_SETTING_OPT,
	SCR_ID_HS_GOTO,
	SCR_ID_HS_DEVICE_STATUS,
	SCR_ID_HS_PERSONALISATION,
	SCR_ID_HS_ORGANIZE_SIDEBAR,
	SCR_ID_HS_PRE_DND,
	SCR_ID_HS_DND,
	SCR_ID_HS_SOFTNOTE,
	SCR_ID_HS_SOFTNOTE_DUMMY,
	SCR_ID_HS_RECENT_EVENT,
	SCR_ID_HS_RECENT_EVENT_RETRY,
	SCR_ID_HS_RECENT_EVENT_PROCESSING,
	SCR_ID_HS_RECENT_EVENT_CLEAR_ALL_PROCESSING,

	SCR_ID_APP_IDLE_HOMESCREEN_ALL
} mmi_app_idle_homescreenscr_id_enum;


typedef enum
{
	SCR_ID_PHNSET_APP_ICON_MAIN = APPICON_BASE + 1,
	SCR_ID_APPICON_MAIN,
	SCRN_ID_APPICON_SYSTEM_LIST_VIEW,
	SCR_ID_PHNSET_APPICON_DOWNLOAD,
	SCR_ID_PHNSET_APPICON_SYSTEM,
	SCRN_ID_APPICON_VIEW1,
	SCRN_ID_APPICON_VIEW2,
	GRP_ID_APPICON_MAIN,
	GRP_ID_APPICON_VIEW,
	GRP_ID_APPICON_SYSTEM,
	SCR_ID_PHNSET_APP_ICON_MAIN,
	SCR_ID_APPICON_MAIN,
	SCRN_ID_APPICON_SYSTEM_LIST_VIEW,
	SCR_ID_PHNSET_APPICON_DOWNLOAD,
	SCR_ID_PHNSET_APPICON_SYSTEM,
	SCRN_ID_APPICON_VIEW1,
	SCRN_ID_APPICON_VIEW2,
	GRP_ID_APPICON_MAIN,
	GRP_ID_APPICON_VIEW,
	GRP_ID_APPICON_SYSTEM,

	SCR_ID_APP_SETTING_APPICON_ALL
} mmi_app_setting_appiconscr_id_enum;


typedef enum
{
	SCR_ID_MODE_SWITCH_START =  + 1,
	SCR_ID_MODE_SWITCH_SIM_SELECTION,
	SCR_ID_MODE_SWITCH_QUERY_CONFIRM,
	SCR_ID_MODE_SWITCH_SWITCH_PROGRESS,
	GRP_ID_MODE_SWITCH_SETTING,
	GRP_ID_MODE_SWITCH_TYPE,
	GRP_ID_MODE_SWITCH_QUERY,
	SCR_ID_MODE_SWITCH_END,
	GRP_ID_NETSET_SIM_NAME_SETTING,
	GRP_ID_NETSET_SIM_NAME_EDIT,
	SCR_ID_MODE_SWITCH_START,
	SCR_ID_MODE_SWITCH_SIM_SELECTION,
	SCR_ID_MODE_SWITCH_QUERY_CONFIRM,
	SCR_ID_MODE_SWITCH_SWITCH_PROGRESS,
	GRP_ID_MODE_SWITCH_SETTING,
	GRP_ID_MODE_SWITCH_TYPE,
	GRP_ID_MODE_SWITCH_QUERY,
	SCR_ID_MODE_SWITCH_END,
	GRP_ID_NETSET_SIM_NAME_SETTING,
	GRP_ID_NETSET_SIM_NAME_EDIT,

	SCR_ID_APP_MODE_SWITCH_ALL
} mmi_app_mode_switchscr_id_enum;


typedef enum
{
	SCR_FLIGHT_MODE_PROGRESS =  + 1,
	SCR_FLIGHT_MODE_PROGRESS,

	SCR_ID_SRV_FLIGHT_MODE_ALL
} mmi_srv_flight_modescr_id_enum;


typedef enum
{
	SCR_ID_GPS_SETTING_MAIN = GPS_BASE + 1,
	SCR_ID_GPS_SETTING_AGPS_SETTING,
	SCR_ID_GPS_SETTING_AGPS_PROFILE,
	SCR_ID_GPS_SETTING_AGPS_PROFILE_OPTION,
	SCR_ID_GPS_SETTING_AGPS_PROFILE_EDIT,
	SCR_ID_GPS_SETTING_ASK_SAVE_SCREEN,
	SCR_ID_GPS_SETTING_BT_PAIRING,
	SCR_ID_GPS_SETTING_INPUT_EDITOR,
	SCR_ID_GPS_SETTING_INPUT_EDITOR_OPTION,
	SCR_ID_GIS_SETTING_PORT_CHOOSE,
	SCR_ID_GPS_SETTING_DUMMY,
	SRC_ID_GPS_MGR_NOTIFY,
	SRC_ID_GPS_MGR_MTLR_NOTIFY,
	SCR_ID_AGPS_SUPL_OTAP_PROF_INFO,
	SCR_ID_AGPS_SUPL_OTAP_PROF_LIST,

	SCR_ID_SRV_GPS_ALL
} mmi_srv_gpsscr_id_enum;


typedef enum
{
	GRP_ID_GPIO_ROOT = APP_GPIO_BASE + 1,
	GRP_ID_GPIO_BACKLIGHT_SETTING,
	GRP_ID_GPIO_LED_SETTING,
	SCR_ID_GPIO_BACKLIGHT_SETTING,
	SCR_ID_GPIO_CONTRAST_SETTING,
	SCR_ID_GPIO_COVER_SETTING,

	SCR_ID_APP_GPIO_ALL
} mmi_app_gpioscr_id_enum;


typedef enum
{
	GRP_ID_MY_FAVORITE = MY_FAVORITE_BASE + 1,
	SCR_MY_FAVORITE_MAIN,
	GRP_ID_MY_FAVORITE_OPTION,

	SCR_ID_APP_MYFAVORITE_ALL
} mmi_app_myfavoritescr_id_enum;


typedef enum
{
	GRP_ID_NMC = NMC_BASE + 1,
	SCR_ID_NMC_MAIN,
	SCR_ID_NMC_EDITBOX,

	SCR_ID_APP_NMC_ALL
} mmi_app_nmcscr_id_enum;


typedef enum
{
	SCR_ID_IG_MAIN = IG_3DGAME_BASE + 1,
	SCR_ID_IG_MAIN,

	SCR_ID_APP_IG_3DGAME_ALL
} mmi_app_ig_3dgamescr_id_enum;


typedef enum
{
	SCR_ID_TTS_SETTING_MIAN = APP_NPR_TTS_BASE + 1,
	SCR_ID_TTS_ABOUT,
	SCR_ID_TTS_VOLUME_SET,
	SCR_ID_TTS_VOICE_SEL,
	SCR_ID_TTS_SMS_READ_SET,
	SCR_ID_TTS_TIME_READ_SET,

	SCR_ID_APP_NPR_TTS_ALL
} mmi_app_npr_ttsscr_id_enum;


typedef enum
{
	SCR_ID_PHONE_0 = APP_KJX_BASE + 1,
	SCR_ID_PHONE_1,
	SCR_ID_PHONE_2,
	SCR_ID_KJX_SHOW_STRING,
	SCR_ID_KJX_SCREEN_TEST,
	SCR_ID_KJX_IMAGE,

	SCR_ID_APP_KJX_ALL
} mmi_app_kjxscr_id_enum;


typedef enum
{
	GRP_ID_CUI_DIALER_SEARCH_SETTING = CUI_DIALER_BASE + 1,
	SCR_ID_CUI_DIALER_MAIN,
	SCR_ID_CUI_DIALER_SEARCH_CONFIG,
	GRP_ID_SIM_SELECT,
	GRP_ID_CUI_DIALER_TTS_SETTING,

	SCR_ID_CUI_DIALER_ALL
} mmi_cui_dialerscr_id_enum;


typedef enum
{
	SCR_STOPWATCH =  + 1,
	SCR_TYPICAL_STOPWATCH,
	SCR_MULTIPURPOSE_STOPWATCH,
	SCR_STOP_OPTIONS,
	SCR_SPLIT_TIMING,
	SCR_VIEW_RECORD,
	SCR_ENTER_RECORD_NAME,
	SCR_SAVE_OPTIONS,
	SCR_VIEW_RECORD_OPTIONS,
	SCR_VIEW_SAVED_RECORD,
	SCR_REPLACE_RECORD,
	GRP_ID_STOPWATCH,

	SCR_ID_APP_STOPWATCH_ALL
} mmi_app_stopwatchscr_id_enum;


typedef enum
{
	GRP_ID_DTV_MBBMS_ESG = DTV_MBBMS_ESG_BASE + 1,

	SCR_ID_APP_DTV_MBBMS_ESG_ALL
} mmi_app_dtv_mbbms_esgscr_id_enum;


typedef enum
{
	GRP_GB_WINGUO_SCREEN = GB_WINGUO_BASE + 1,
	SCR_GB_WINGUO_SCREEN,
	SCR_GB_WINGUO_SHOW_SIM,
	SCR_GB_WINGUO_SELECT_SIM,
	SCR_GB_WINGUO_SELECT_GPRS,
	SCR_ID_GB_IDLEHW,

	SCR_ID_APP_GB_WINGUO_ALL
} mmi_app_gb_winguoscr_id_enum;


typedef enum
{
	GRP_ID_MENS =  + 1,
	SCR_ID_MENS_WELCOME,
	SCR_ID_MENS_INPUT,
	SCR_ID_MENS_RESULT,
	SCR_ID_MENS_PROB,

	SCR_ID_APP_HEALTHMENSTRUAL_ALL
} mmi_app_healthmenstrualscr_id_enum;


typedef enum
{
	SCR_ID_FM_MISC_AUTO_TEST_SETTING = FACTORY_MODE_BASE + 1,
	SCR_ID_FM_MISC_AUTO_TEST_ADD,
	SCR_ID_FM_AUTO_TEST_ENTER_PRIORITY,
	SCR_ID_FM_MISC_AUTO_TEST_CHANGE_PRIORITY,
	SCR_ID_FM_ROOT,
	SCR_ID_FM_VERSION,
	SCR_ID_FM_VERSION_SUMMARY,
	SCR_ID_FM_RESOURCE_BIN,
	SCR_ID_FM_RESOURCE_AUDIO,
	SCR_ID_FM_RESOURCE_IMAGE,
	SCR_ID_FM_RESOURCE_STR,
	SCR_ID_FM_RESOURCE_FONT,
	SCR_ID_FM_BBCHIP_VER,
	SCR_ID_FM_DSPCODE_VER,
	SCR_ID_FM_DSPATCH_VER,
	SCR_ID_FM_SW_VER,
	SCR_ID_FM_HW_VER,
	SCR_ID_FM_MELODY_VER,
	SCR_ID_FM_ISN,
	SCR_ID_FM_BUILD_TIME,
	SCR_ID_FM_LED,
	SCR_ID_FM_LCD,
	SCR_ID_FM_LCD_AUTO,
	SCR_ID_FM_LCD_R,
	SCR_ID_FM_LCD_G,
	SCR_ID_FM_LCD_B,
	SCR_ID_FM_LCD_W,
	SCR_ID_FM_LCD_CONTRAST,
	SCR_ID_FM_LCD_CONTRAST_MAINLCD,
	SCR_ID_FM_LCD_CONTRAST_SUBLCD,
	SCR_ID_FM_KEYPAD,
	SCR_ID_FM_LOUDSPK,
	SCR_ID_FM_EACHLOOP,
	SCR_ID_FM_VIBRATOR,
	SCR_ID_FM_ADC,
	SCR_ID_FM_RECEIVER,
	SCR_ID_FM_RTC,
	SCR_ID_FM_HEADSET,
	SCR_ID_FM_CHARGER,
	SCR_ID_FM_RINGTONE,
	SCR_ID_FM_AUTO_TEST_ROOT,
	SCR_ID_FM_AUTO_TEST_REPORT,
	SCR_ID_FM_AUTO_TEST_SUMMARY,
	SCR_ID_FM_AUTO_TEST_RESULT,
	SCR_ID_FM_AUTO_TEST_START,
	SCR_ID_FM_MEMORY_CARD,
	SCR_ID_FM_NAND_FLASH,
	SCR_ID_FM_CAMERA_TEST,
	SCR_ID_FM_CAMERA_TEST_DUMMY,
	SCR_ID_FM_CAMERA,
	SCR_ID_FM_CAMERA_SENSOR_SETTING,
	SCR_ID_FM_CAMERA_ISP_SETTING,
	SCR_ID_FM_SETCAMERAPARA,
	SCR_ID_FM_MTBF,
	SCR_ID_FM_MOTION_CALI,
	SCR_ID_FM_UART,
	SCR_ID_FM_PARALLEL_PEN,
	SCR_ID_FM_N_CROSS_M_PEN,
	SCR_ID_FM_FM_RADIO,
	SCR_ID_FM_FM_RADIO_CHANNEL_TEST,
	SCR_ID_FM_KEYPAD_TEST,
	SCR_ID_FM_KEYPAD_TEST_RESULT,
	SCR_ID_FM_PXS_RAW_DATA,
	SCR_ID_FM_TOUCH_PANEL,
	GRP_ID_FM_ROOT,
	GRP_ID_FM_TOUCH_PANEL,
	SCR_ID_FM_DUAL_TOUCH_CALIBRATION,
	GRP_ID_ID_FM_DUAL_TOUCH_CALIBRATION,
	GRP_ID_FM_NFC,
	SCR_ID_FM_NFC_SHOW_PROGRESS,
	SCR_ID_FM_NFC_SHOW_UID,
	SCR_ID_FM_GPS,
	SCR_ID_FM_RFID,
	SCR_ID_FM_BLE,
	SCR_ID_FM_PRESSURE,
	SCR_ID_FM_SENSOR,

	SCR_ID_APP_FACTORYMODE_ALL
} mmi_app_factorymodescr_id_enum;


typedef enum
{
	GRP_ID_PHB_TTS_SETTING_MENU =  + 1,
	GRP_ID_SMS_TTS_SETTING_MENU,
	GRP_ID_PHB_TTS_SETTING_MENU,
	GRP_ID_SMS_TTS_SETTING_MENU,

	SCR_ID_APP_TTS_SETTING_ALL
} mmi_app_tts_settingscr_id_enum;


