#include "MMI_features.h"
#include "CustResDef.h"

<?xml version="1.0" encoding="UTF-8"?>
<APP id="APP_VENUS_SHELL_MEDIAPLAYER">

#ifdef __MMI_VUI_SHELL_MEDIA_PLAYER__

    #define SHELL_COMMON_PATH CUST_IMG_PATH"\\\\MainLCD\\\\VUI\\\\Shell\\\\Common\\\\"
    #define SHELL_MEDIAPLAYER_PATH    CUST_IMG_PATH"\\\\MainLCD\\\\VUI\\\\Shell\\\\MediaPlayer\\\\"
    #define SHELL_MEDIAPLAYER_PATH_BUTTON    CUST_IMG_PATH"\\\\MainLCD\\\\VUI\\\\Shell\\\\MediaPlayer\\\\Button\\\\"
    #define SHELL_MEDIAPLAYER_PATH_VOLUME    CUST_IMG_PATH"\\\\MainLCD\\\\VUI\\\\Shell\\\\MediaPlayer\\\\VolumeLevel\\\\"
    #define SHELL_MEDIAPLAYER_PATH_PROGRESS    CUST_IMG_PATH"\\\\MainLCD\\\\VUI\\\\Shell\\\\MediaPlayer\\\\Progress\\\\"
    
    <IMAGE id="IMG_ID_SHELL_MEDIAPLAYER_ARTIST_ICON">SHELL_MEDIAPLAYER_PATH"Artist.png"</IMAGE>    
    <IMAGE id="IMG_ID_SHELL_MEDIAPLAYER_ALBUM_ICON">SHELL_MEDIAPLAYER_PATH"Album.png"</IMAGE>
    <IMAGE id="IMG_ID_SHELL_MEDIAPLAYER_ALBUM_COVER">SHELL_MEDIAPLAYER_PATH"Music_BG.png"</IMAGE>    
    <IMAGE id="IMG_ID_SHELL_MEDIAPLAYER_ALBUM_GLOSS">SHELL_MEDIAPLAYER_PATH"Music_HighGloss.png"</IMAGE>    
    <IMAGE id="IMG_ID_SHELL_MEDIAPLAYER_ALBUM_NO_MUSIC">SHELL_MEDIAPLAYER_PATH"NoMusic.png"</IMAGE>    
    <IMAGE id="IMG_ID_SHELL_MEDIAPLAYER_OK_DIS">SHELL_MEDIAPLAYER_PATH"OK_Dis.png"</IMAGE>    
    <IMAGE id="IMG_ID_SHELL_MEDIAPLAYER_OK_NOR">SHELL_MEDIAPLAYER_PATH"OK_Nor.png"</IMAGE>    
    <IMAGE id="IMG_ID_SHELL_MEDIAPLAYER_OK_PRE">SHELL_MEDIAPLAYER_PATH"OK_Pre.png"</IMAGE>    

    #if defined(__MMI_VUI_SHELL_MEDIA_PLAYER_SLIM__) && defined(__MMI_MAINLCD_320X480__)
        <IMAGE id="IMG_ID_SHELL_MEDIAPLAYER_CELL_PLAY_ICON">SHELL_MEDIAPLAYER_PATH"List_PlayInd.png"</IMAGE>
        <IMAGE id="IMG_ID_SHELL_MEDIAPLAYER_CELL_BG">SHELL_MEDIAPLAYER_PATH"List_Panel_Slim.png"</IMAGE>
        <IMAGE id="IMG_ID_SHELL_MEDIAPLAYER_CELL_NO_IMAGE">SHELL_MEDIAPLAYER_PATH"List_NoImage_Slim.png"</IMAGE>
    #else
        #if defined(__MMI_MAINLCD_240X320__) && defined(__MMI_VUI_SHELL_MEDIA_PLAYER_SLIM__) && (defined(MT6253)||defined(MT6253D)||defined(MT6253T)||defined(MT6253E)||defined(MT6253L)||defined(MT6252H)||defined(MT6252))
            <IMAGE id="IMG_ID_SHELL_MEDIAPLAYER_CELL_BG">SHELL_MEDIAPLAYER_PATH"List_Panel_slim.bmp"</IMAGE>
        #else
            <IMAGE id="IMG_ID_SHELL_MEDIAPLAYER_CELL_BG">SHELL_MEDIAPLAYER_PATH"List_Panel.png"</IMAGE>    
        #endif
        <IMAGE id="IMG_ID_SHELL_MEDIAPLAYER_CELL_PLAY_ICON">SHELL_MEDIAPLAYER_PATH"List_PlayInd.png"</IMAGE>
        <IMAGE id="IMG_ID_SHELL_MEDIAPLAYER_CELL_NO_IMAGE">SHELL_MEDIAPLAYER_PATH"List_NoImage.png"</IMAGE>
    #endif

    <!-- Buttom -->
    <IMAGE id="IMG_ID_SHELL_MEDIAPLAYER_NEXT_DIS">SHELL_MEDIAPLAYER_PATH_BUTTON"Button_Next_Dis.png"</IMAGE>      
    <IMAGE id="IMG_ID_SHELL_MEDIAPLAYER_NEXT_NOR">SHELL_MEDIAPLAYER_PATH_BUTTON"Button_Next_Nor.png"</IMAGE>    
    <IMAGE id="IMG_ID_SHELL_MEDIAPLAYER_NEXT_PRE">SHELL_MEDIAPLAYER_PATH_BUTTON"Button_Next_Pre.png"</IMAGE>    
    <IMAGE id="IMG_ID_SHELL_MEDIAPLAYER_PAUSE_NOR">SHELL_MEDIAPLAYER_PATH_BUTTON"Button_Pause_Nor.png"</IMAGE>    
    <IMAGE id="IMG_ID_SHELL_MEDIAPLAYER_PAUSE_PRE">SHELL_MEDIAPLAYER_PATH_BUTTON"Button_Pause_Pre.png"</IMAGE>    
    <IMAGE id="IMG_ID_SHELL_MEDIAPLAYER_PLAY_DIS">SHELL_MEDIAPLAYER_PATH_BUTTON"Button_Play_Dis.png"</IMAGE>      
    <IMAGE id="IMG_ID_SHELL_MEDIAPLAYER_PLAY_NOR">SHELL_MEDIAPLAYER_PATH_BUTTON"Button_Play_Nor.png"</IMAGE>    
    <IMAGE id="IMG_ID_SHELL_MEDIAPLAYER_PLAY_PRE">SHELL_MEDIAPLAYER_PATH_BUTTON"Button_Play_Pre.png"</IMAGE>    
    <IMAGE id="IMG_ID_SHELL_MEDIAPLAYER_PREV_DIS">SHELL_MEDIAPLAYER_PATH_BUTTON"Button_Previous_Dis.png"</IMAGE>      
    <IMAGE id="IMG_ID_SHELL_MEDIAPLAYER_PREV_NOR">SHELL_MEDIAPLAYER_PATH_BUTTON"Button_Previous_Nor.png"</IMAGE>    
    <IMAGE id="IMG_ID_SHELL_MEDIAPLAYER_PREV_PRE">SHELL_MEDIAPLAYER_PATH_BUTTON"Button_Previous_Pre.png"</IMAGE> 
    <IMAGE id="IMG_ID_SHELL_MEDIAPLAYER_REPALL_OFF">SHELL_MEDIAPLAYER_PATH_BUTTON"Button_RepAll_Off.png"</IMAGE> 
    <IMAGE id="IMG_ID_SHELL_MEDIAPLAYER_REPALL_ON">SHELL_MEDIAPLAYER_PATH_BUTTON"Button_RepAll_On.png"</IMAGE>     
    <IMAGE id="IMG_ID_SHELL_MEDIAPLAYER_REPONE_OFF">SHELL_MEDIAPLAYER_PATH_BUTTON"Button_RepOne_Off.png"</IMAGE> 
    <IMAGE id="IMG_ID_SHELL_MEDIAPLAYER_REPONE_ON">SHELL_MEDIAPLAYER_PATH_BUTTON"Button_RepOne_On.png"</IMAGE>     
    <IMAGE id="IMG_ID_SHELL_MEDIAPLAYER_SHUFFLE_OFF">SHELL_MEDIAPLAYER_PATH_BUTTON"Button_Shuffle_Off.png"</IMAGE> 
    <IMAGE id="IMG_ID_SHELL_MEDIAPLAYER_SHUFFLE_ON">SHELL_MEDIAPLAYER_PATH_BUTTON"Button_Shuffle_On.png"</IMAGE>     
    <IMAGE id="IMG_ID_SHELL_MEDIAPLAYER_VOLUME_DIS">SHELL_MEDIAPLAYER_PATH_BUTTON"Button_Volume_Dis.png"</IMAGE>      
    <IMAGE id="IMG_ID_SHELL_MEDIAPLAYER_VOLUME_NOR">SHELL_MEDIAPLAYER_PATH_BUTTON"Button_Volume_Nor.png"</IMAGE>    
    <IMAGE id="IMG_ID_SHELL_MEDIAPLAYER_VOLUME_PRE">SHELL_MEDIAPLAYER_PATH_BUTTON"Button_Volume_Pre.png"</IMAGE> 

    <!-- Progress -->
    <IMAGE id="IMG_ID_SHELL_MEDIAPLAYER_PROGRESS_BAR_ON">SHELL_MEDIAPLAYER_PATH_PROGRESS"Pro_Bar01.9slice.png"</IMAGE>
    <IMAGE id="IMG_ID_SHELL_MEDIAPLAYER_PROGRESS_BAR_OFF">SHELL_MEDIAPLAYER_PATH_PROGRESS"Pro_BG.9slice.png"</IMAGE>

    <!-- VolumeLevel -->
    <IMAGE id="IMG_ID_SHELL_MEDIAPLAYER_VOL_BAR01">SHELL_MEDIAPLAYER_PATH_VOLUME"Vol_Bar01.9slice.png"</IMAGE>
    <IMAGE id="IMG_ID_SHELL_MEDIAPLAYER_VOL_BAR02">SHELL_MEDIAPLAYER_PATH_VOLUME"Vol_Bar02.9slice.png"</IMAGE>
    <IMAGE id="IMG_ID_SHELL_MEDIAPLAYER_VOL_BAR03">SHELL_MEDIAPLAYER_PATH_VOLUME"Vol_Bar03.png"</IMAGE>
    <IMAGE id="IMG_ID_SHELL_MEDIAPLAYER_VOL_BG">SHELL_MEDIAPLAYER_PATH_VOLUME"Vol_BG.9slice.png"</IMAGE>
    
    <IMAGE id="IMG_ID_SHELL_MEDIAPLAYER_VOLUME">SHELL_MEDIAPLAYER_PATH_VOLUME"Volume_NOR.png"</IMAGE>
    <IMAGE id="IMG_ID_SHELL_MEDIAPLAYER_VOLUME_MUTE">SHELL_MEDIAPLAYER_PATH_VOLUME"Mute_NOR.png"</IMAGE>
    <IMAGE id="IMG_ID_SHELL_MEDIAPLAYER_PROGRESS_BAR_ON">SHELL_MEDIAPLAYER_PATH_PROGRESS"Pro_Bar01.9slice.png"</IMAGE>

    <STRING id="STR_ID_SHELL_MEDIAPLAYER_LIBRARY"/>
    <STRING id="STR_ID_SHELL_MEDIAPLAYER_MUSIC"/>
    <STRING id="STR_ID_SHELL_MEDIAPLAYER_NO_MUSIC"/>
    <STRING id="STR_ID_SHELL_MEDIAPLAYER_TOUCH_TO_ADD"/>
    <STRING id="STR_ID_SHELL_MEDIAPLAYER_TOUCH_LIBRARY_TO_SELECT_PLST"/>
    <STRING id="STR_ID_SHELL_MEDIAPLAYER_BD_ERROR"/>
    <STRING id="STR_ID_SHELL_MEDIAPLAYER_UNKNOWN_INFO"/>    
    <STRING id="STR_ID_SHELL_MEDIAPLAYER_TITLE"/>
#endif    
</APP>
