#include "mmi_features.h"
#include "custresdef.h"

<?xml version="1.0" encoding="UTF-8"?>

<APP id="VAPP_DTCNT" name="STR_ID_VAPP_DTCNT" type="venus">
#ifdef __TCPIP__
    <MEMORY base="512000" />

    // string id
    <STRING id="STR_ID_VAPP_DTCNT_DATA_ACCOUNT_ENTRY_HINT"/>
    <STRING id="STR_ID_VAPP_DTCNT_EDIT_NOT_ALLOWED"/>
    <STRING id="STR_ID_VAPP_DTCNT_DELETE_NOT_ALLOWED"/>
    <STRING id="STR_ID_VAPP_DTCNT_GROUP_PROXY"/>
    <STRING id="STR_ID_VAPP_DTCNT_GROUP_OTHERS"/>
    <STRING id="STR_ID_VAPP_DTCNT_APN_NEEDED"/>
    <STRING id="STR_ID_VAPP_DTCNT_NUMBER_NEEDED"/>
    <STRING id="STR_ID_VAPP_DTCNT_INVALID_HOMEPAGE"/>
    <STRING id="STR_ID_VAPP_DTCNT_INVALID_PROXY_ADDRESS"/>
    <STRING id="STR_ID_VAPP_DTCNT_INVALID_PROXY_PORT"/>
    <STRING id="STR_ID_VAPP_DTCNT_ADD_DATA_ACCOUNT"/>
    <STRING id="STR_ID_VAPP_DTCNT_EDIT_PS_ACCOUNT"/>
    <STRING id="STR_ID_VAPP_DTCNT_EDIT_CSD_ACCOUNT"/>
    <STRING id="STR_ID_VAPP_DTCNT_VIEW_PS_ACCOUNT"/>
    <STRING id="STR_ID_VAPP_DTCNT_VIEW_CSD_ACCOUNT"/>
    <STRING id="STR_ID_VAPP_DTCNT_VIEW_CSD_ACCOUNT"/>
    <STRING id="STR_ID_VAPP_DTCNT_INVALID_PRIMARY_DNS"/>
    <STRING id="STR_ID_VAPP_DTCNT_INVALID_SECONDARY_DNS"/>
    <STRING id="STR_ID_VAPP_DTCNT_INVALID_IP_ADDRESS"/>
    <STRING id="STR_ID_VAPP_DTCNT_INVALID_SUBNET_MASK"/>
    <STRING id="STR_ID_VAPP_DTCNT_SET_DEFAULT"/>
    <STRING id="STR_ID_VAPP_DTCNT_PROXY_USERNAME"/>
    <STRING id="STR_ID_VAPP_DTCNT_USERNAME"/>
    <STRING id="STR_ID_VAPP_DTCNT_DELETE_DATA_ACCOUNT"/>
    <STRING id="STR_ID_VAPP_DTCNT_CHANGE_TO_SIM1"/>
    <STRING id="STR_ID_VAPP_DTCNT_CHANGE_TO_SIM2"/>
    <STRING id="STR_ID_VAPP_DTCNT_CHANGE_TO_SIM3"/>
    <STRING id="STR_ID_VAPP_DTCNT_CHANGE_TO_SIM4"/>
    <STRING id="STR_ID_VAPP_DTCNT_RENAME"/>
    <STRING id="STR_ID_VAPP_DTCNT_DIAL_NUMBER"/>
    <STRING id="STR_ID_VAPP_DTCNT_DIAL_TYPE"/>
    <STRING id="STR_ID_VAPP_DTCNT_DATA_RATE"/>
    <STRING id="STR_ID_VAPP_DTCNT_ADVANCED_SETTING"/>
    <STRING id="STR_ID_VAPP_DTCNT_HOME_PAGE"/>
    <STRING id="STR_ID_VAPP_DTCNT_CONNECTION_TYPE"/>
    <STRING id="STR_ID_VAPP_DTCNT_USE_PROXY"/>
    <STRING id="STR_ID_VAPP_DTCNT_PROXY_ADDRESS"/>
    <STRING id="STR_ID_VAPP_DTCNT_PROXY_PORT"/>
    <STRING id="STR_ID_VAPP_DTCNT_PROXY_PASS_WORD"/>
    <STRING id="STR_ID_VAPP_DTCNT_DNS_ADDRESS1"/>
    <STRING id="STR_ID_VAPP_DTCNT_DNS_ADDRESS2"/>
    <STRING id="STR_ID_VAPP_DTCNT_IP_ADDRESS"/>
    <STRING id="STR_ID_VAPP_DTCNT_SUBNET_MASK"/>
    <STRING id="STR_ID_VAPP_DTCNT_ADD_CSD"/>
    <STRING id="STR_ID_VAPP_DTCNT_ADD_GPRS"/>
    <STRING id="STR_ID_VAPP_DTCNT_ALWAYS_ASK"/>
    <STRING id="STR_ID_VAPP_DTCNT_COLON"/>
    <STRING id="STR_ID_VAPP_DTCNT_GPRS_PAP_AUTH"/>
    <STRING id="STR_ID_VAPP_DTCNT_GPRS_CHAP_AUTH"/>
    <STRING id="STR_ID_VAPP_DTCNT_GPRS_APN"/>
    <STRING id="STR_ID_VAPP_DTCNT_GPRS_AUTH_TYP"/>
    <STRING id="STR_ID_VAPP_DTCNT_ANALOGUE_STR"/>
    <STRING id="STR_ID_VAPP_DTCNT_ISDN_STR"/>
    <STRING id="STR_ID_VAPP_DTCNT_RATE_STR_ZERO"/>
    <STRING id="STR_ID_VAPP_DTCNT_RATE_STR_ONE"/>
    <STRING id="STR_ID_VAPP_DTCNT_RATE_STR_TWO"/>
    <STRING id="STR_ID_VAPP_DTCNT_RATE_STR_THREE"/>
    <STRING id="STR_ID_VAPP_DTCNT_RATE_STR_FOUR"/>
    <STRING id="STR_ID_VAPP_DTCNT_CONNECTION_TYPE_WAP"/>
    <STRING id="STR_ID_VAPP_DTCNT_CONNECTION_TYPE_HTTP"/>
    <STRING id="STR_ID_VAPP_DTCNT_NAME_INVALID"/>
    <STRING id="STR_ID_VAPP_DTCNT_USED_WLAN"/>
    <STRING id="STR_ID_VAPP_DTCNT_DELETE_ACCOUNT_PREFIX"/>
    <STRING id="STR_ID_VAPP_DTCNT_DELETE_ACCOUNT_SUFFIX"/>
    <STRING id="STR_ID_VAPP_DTCNT_EMPTY_LIST"/>
    <STRING id="STR_ID_VAPP_DTCNT_SIM_PREFER_NOT_ALLOW_CHANGED"/>
    <STRING id="STR_ID_VAPP_DTCNT_ACCT_MAX_NUM"/>
    <STRING id="STR_ID_VAPP_DTCNT_NO_AVAILABLE_ACCOUNT"/>

    // img
    <IMAGE id = "IMG_ID_VAPP_DTCNT_SET_DEFAULT">RES_IMG_ROOT"\\\\Settings\\\\ToolbarIcon\\\\ChangeDefault.png"</IMAGE>
    <IMAGE id = "IMG_ID_VAPP_DTCNT_READ_ONLY">RES_IMG_ROOT"\\\\Settings\\\\ListIcon\\\\OnlyRead.png"</IMAGE>
    // receiver
    <RECEIVER id="EVT_ID_SRV_SIM_CTRL_HOME_PLMN_CHANGED" proc="vappDtcntOnHomePlmnChanged"/>
    <RECEIVER id="EVT_ID_SRV_SIM_CTRL_AVAILABILITY_CHANGED" proc="vappDtcntSimChanged"/>
    <RECEIVER id="EVT_ID_SRV_CBM_BEARER_INFO" proc="vappDtcntBearerInfoChanged"/>
#endif
</APP>

