/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_app_dataaccount.c
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   MTK resgenerator XML parser
 *
 *******************************************************************************/
#include "CustDataProts.h"
#include "mmi_rp_app_dataaccount_def.h"

/* Application specified header files for using old res IDs */
#include "MMI_features.h"
#include "MMIDataType.h"    /* for resource base */

#include "CustResDef.h"         /* for image/audio path */
#include "GlobalMenuItems.h"    /* for menu resource */

#include "GlobalResDef.h"
#include "SettingResDef.h"


/*****************************************************************************
* FUNCTION
*  mmi_rp_app_dataaccount_populate
* DESCRIPTION
*  Automatically generated populate function for mmi_rp_app_dataaccount_populate
* PARAMETERS
*  void
* RETURNS
*  void
*****************************************************************************/
void mmi_rp_app_dataaccount_populate(void)
{
    /*----------------------------------------------------------------*/
    /* Local Variables                                                */
    /*----------------------------------------------------------------*/

    /*----------------------------------------------------------------*/
    /* Code Body                                                      */
    /*----------------------------------------------------------------*/

/******************** Menu resource IDs - begin ********************/
    ADD_APPLICATION_MENUITEM5((
        MENU_ID_DTCNT_SIM_1,
        MENU_ID_DATA_CONNECTION_SIM,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_SIM_1,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_DATA_CONNECTION_SIM,
        0,
        1,
        MENU_ID_DTCNT_SIM_1,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_DATA_CONNECTION_SIM,
        0));

    ADD_APPLICATION_MENUITEM5((
        SERVICES_DATA_CONNECT_MAIN_MENU_ID,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_DATA_ACCOUNTS,
        SERVICES_DATA_CONNECT_IMAGE_ID));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_DTCNT_OPT_ADD_GPRS,
        MENU_ID_DTCNT_ACCOUNT_OPTION,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_DTCNT_ADD_GPRS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_DTCNT_ACCOUNT_OPTION,
        0,
        4,
        MENU_ID_DTCNT_OPT_EDIT,
        MENU_ID_DTCNT_OPT_ADD_GPRS,
        MENU_ID_DTCNT_OPT_DELETE,
        MENU_ID_DTCNT_OPT_CHANGE_DEFAULT,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_OPTIONS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_DTCNT_OPT_EDIT,
        MENU_ID_DTCNT_ACCOUNT_OPTION,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_EDIT,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_DTCNT_OPT_DELETE,
        MENU_ID_DTCNT_ACCOUNT_OPTION,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_DELETE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_DTCNT_OPT_CHANGE_DEFAULT,
        MENU_ID_DTCNT_ACCOUNT_OPTION,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_DTCNT_CHANGE_DEFAULT,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_DTCNT_OPT2_ADD_GPRS,
        MENU_ID_DTCNT_ACCOUNT_OPTION2,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_DTCNT_ADD_GPRS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_DTCNT_ACCOUNT_OPTION2,
        0,
        1,
        MENU_ID_DTCNT_OPT2_ADD_GPRS,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_OPTIONS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_DTCNT_OPT3_ADD_GPRS,
        MENU_ID_DTCNT_ACCOUNT_OPTION3,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_DTCNT_ADD_GPRS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_DTCNT_ACCOUNT_OPTION3,
        0,
        3,
        MENU_ID_DTCNT_OPT3_VIEW,
        MENU_ID_DTCNT_OPT3_ADD_GPRS,
        MENU_ID_DTCNT_OPT3_CHANGE_DEFAULT,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_OPTIONS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_DTCNT_OPT3_VIEW,
        MENU_ID_DTCNT_ACCOUNT_OPTION3,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_VIEW,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_DTCNT_OPT3_CHANGE_DEFAULT,
        MENU_ID_DTCNT_ACCOUNT_OPTION3,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_DTCNT_CHANGE_DEFAULT,
        0));

/******************** Menu resource IDs - finish ********************/

/******************** Menu Hilite/Hint Handlers - begin ********************/
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_DATA_CONNECTION_SIM, mmi_data_connection_sim_hilite_hdlr);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(SERVICES_DATA_CONNECT_MAIN_MENU_ID, DataConnectHiliteHandler);
/******************** Menu Hilite/Hint Handlers - finish ********************/
}
