/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_app_npr_tts.c
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   MTK resgenerator XML parser
 *
 *******************************************************************************/
#include "CustDataProts.h"
#include "mmi_rp_app_npr_tts_def.h"

/* Application specified header files for using old res IDs */


/*****************************************************************************
* FUNCTION
*  mmi_rp_app_npr_tts_populate
* DESCRIPTION
*  Automatically generated populate function for mmi_rp_app_npr_tts_populate
* PARAMETERS
*  void
* RETURNS
*  void
*****************************************************************************/
void mmi_rp_app_npr_tts_populate(void)
{
    /*----------------------------------------------------------------*/
    /* Local Variables                                                */
    /*----------------------------------------------------------------*/

    /*----------------------------------------------------------------*/
    /* Code Body                                                      */
    /*----------------------------------------------------------------*/

/******************** Menu resource IDs - begin ********************/
    ADD_APPLICATION_MENUITEM5((
        MENU_ID_TTS_SETTING,
        0,
        6,
        MENU_ID_TTS_MENU_READ,
        MENU_ID_TTS_INCOMING_CALL_READ,
        MENU_ID_TTS_SMS_READ_SET,
        MENU_ID_TTS_KEYPAD_READ,
        MENU_ID_TTS_VOL_SET,
        MENU_ID_TTS_ABOUT,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_TTS_SETTING_MENU_TEXT,
        IMG_ID_TTS_SETTING_MENU_ICON));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_TTS_MENU_READ,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_TTS_MENU_READ,
        NULL));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_TTS_INCOMING_CALL_READ,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_TTS_INCOMING_CALL_READ,
        NULL));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_TTS_KEYPAD_READ,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_TTS_KEYPAD_READ,
        NULL));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_TTS_ABOUT,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_TTS_ABOUT,
        NULL));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_TTS_VOL_SET,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_TTS_VOL_SET,
        NULL));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_TTS_SMS_READ_SET,
        0,
        2,
        MENU_ID_TTS_SMS_RECV_READ,
        MENU_ID_TTS_SMS_AUTO_READ,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_TTS_SMS_READ_SET,
        NULL));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_TTS_SMS_RECV_READ,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_TTS_SMS_RECV_READ,
        NULL));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_TTS_SMS_AUTO_READ,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_TTS_SMS_AUTO_READ,
        NULL));

/******************** Menu resource IDs - finish ********************/

/******************** Menu Hilite/Hint Handlers - begin ********************/
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_TTS_SETTING, NPR_TTS_MainScreenHighlight);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_TTS_MENU_READ, NPR_TTS_MenuScrenHighlight);
    ADD_APPLICATION_MENUITEM_HINT_HANDLER(MENU_ID_TTS_MENU_READ, NPR_TTS_MenuStatus_Hint);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_TTS_INCOMING_CALL_READ, NPR_TTS_IncomingCallHighlight);
    ADD_APPLICATION_MENUITEM_HINT_HANDLER(MENU_ID_TTS_INCOMING_CALL_READ, NPR_TTS_IncomingCallHint);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_TTS_KEYPAD_READ, NPR_TTS_KeyplayHighlight);
    ADD_APPLICATION_MENUITEM_HINT_HANDLER(MENU_ID_TTS_KEYPAD_READ, NPR_TTS_KeyplayHint);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_TTS_ABOUT, NPR_TTS_AboutScreenHighlight);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_TTS_VOL_SET, NPR_TTS_VolumeScreenHighlight);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_TTS_SMS_READ_SET, NPR_TTS_SmsReadSetingHighlight);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_TTS_SMS_RECV_READ, NPR_TTS_SmsRecvHighlight);
    ADD_APPLICATION_MENUITEM_HINT_HANDLER(MENU_ID_TTS_SMS_RECV_READ, NPR_TTS_SmsRecvHint);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_TTS_SMS_AUTO_READ, NPR_TTS_SmsAutoHighlight);
    ADD_APPLICATION_MENUITEM_HINT_HANDLER(MENU_ID_TTS_SMS_AUTO_READ, NPR_TTS_SmsAutoReadHint);
/******************** Menu Hilite/Hint Handlers - finish ********************/
}
