/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_app_calllog.c
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   MTK resgenerator XML parser
 *
 *******************************************************************************/
#include "CustDataProts.h"
#include "mmi_rp_app_calllog_def.h"

/* Application specified header files for using old res IDs */
#include "MMI_features.h"
#include "MMIDataType.h"    /* for resource base */

#include "CustResDef.h"         /* for image/audio path */
#include "GlobalMenuItems.h"    /* for menu resource */

#include "GlobalResDef.h"


/*****************************************************************************
* FUNCTION
*  mmi_rp_app_calllog_populate
* DESCRIPTION
*  Automatically generated populate function for mmi_rp_app_calllog_populate
* PARAMETERS
*  void
* RETURNS
*  void
*****************************************************************************/
void mmi_rp_app_calllog_populate(void)
{
    /*----------------------------------------------------------------*/
    /* Local Variables                                                */
    /*----------------------------------------------------------------*/

    /*----------------------------------------------------------------*/
    /* Code Body                                                      */
    /*----------------------------------------------------------------*/

/******************** Menu resource IDs - begin ********************/
    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLOG_CALL_COST,
        MENU_ID_CLOG_ADVANCED,
        5,
        MENU_ID_CLOG_CCOST_LAST,
        MENU_ID_CLOG_CCOST_TOTAL,
        MENU_ID_CLOG_CCOST_RESET,
        MENU_ID_CLOG_CCOST_MAX,
        MENU_ID_CLOG_CCOST_PPU,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_APP_SUB,
        STR_ID_CLOG_CALL_COST,
        IMG_ID_CLOG_CALL_COST));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLOG_CCOST_LAST,
        MENU_ID_CLOG_CALL_COST,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CLOG_CCOST_LAST,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLOG_CCOST_TOTAL,
        MENU_ID_CLOG_CALL_COST,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CLOG_CCOST_TOTAL,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLOG_CCOST_RESET,
        MENU_ID_CLOG_CALL_COST,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CLOG_CCOST_RESET,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLOG_CCOST_MAX,
        MENU_ID_CLOG_CALL_COST,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CLOG_CCOST_MAX,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLOG_CCOST_PPU,
        MENU_ID_CLOG_CALL_COST,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CLOG_CCOST_PPU,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLOG_GPRS_COUNT,
        MENU_ID_CLOG_ADVANCED,
        5,
        MENU_ID_CLOG_GPRS_LAST_SENT,
        MENU_ID_CLOG_GPRS_LAST_RECVED,
        MENU_ID_CLOG_GPRS_ALL_SENT,
        MENU_ID_CLOG_GPRS_ALL_RECVED,
        MENU_ID_CLOG_GPRS_RESET,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_APP_SUB,
        STR_ID_CLOG_GPRS_COUNT,
        IMG_ID_CLOG_GPRS_COUNT));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLOG_GPRS_LAST_SENT,
        MENU_ID_CLOG_GPRS_COUNT,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CLOG_GPRS_LAST_SENT,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLOG_GPRS_LAST_RECVED,
        MENU_ID_CLOG_GPRS_COUNT,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CLOG_GPRS_LAST_RECVED,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLOG_GPRS_ALL_SENT,
        MENU_ID_CLOG_GPRS_COUNT,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CLOG_GPRS_ALL_SENT,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLOG_GPRS_ALL_RECVED,
        MENU_ID_CLOG_GPRS_COUNT,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CLOG_GPRS_ALL_RECVED,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLOG_GPRS_RESET,
        MENU_ID_CLOG_GPRS_COUNT,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CLOG_GPRS_RESET,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLOG_DIALED_CALL,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_DIALLED_CALLS,
        IMG_ID_CLOG_DIALED_CALL));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLOG_MISSED_CALL,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_MISSED_CALLS,
        IMG_ID_CLOG_MISSED_CALL));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLOG_RECVED_CALL,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_RECEIVED_CALLS,
        IMG_ID_CLOG_RECVED_CALL));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLOG_ALL_CALL,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CLOG_ALL_CALL,
        IMG_ID_CLOG_ALL_CALL));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLOG_SEND_SMS,
        MENU_ID_CLOG_OPTION,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_SEND_TEXT_MESSAGE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLOG_SEND_MMS,
        MENU_ID_CLOG_OPTION,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_SEND_MULTIMEDIA_MESSAGE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLOG_DELETE,
        MENU_ID_CLOG_OPTION,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_DELETE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLOG_DELETE_ALL,
        MENU_ID_CLOG_OPTION,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_DELETE_ALL,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLOG_ADVANCED,
        MENU_ID_CLOG_OPTION,
        3,
        MENU_ID_CLOG_CALL_TIME,
        MENU_ID_CLOG_CALL_COST,
        MENU_ID_CLOG_GPRS_COUNT,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_APP_SUB,
        STR_GLOBAL_ADVANCED,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLOG_OPTION,
        0,
        10,
        MENU_ID_CLOG_VIEW,
        MENU_ID_CLOG_MAKE_CALL,
        MENU_ID_CLOG_SEND_SMS,
        MENU_ID_CLOG_SEND_MMS,
        MENU_ID_CLOG_SAVE_TO_PHB,
        MENU_ID_CLOG_ADD_TO_BLACK_LIST,
        MENU_ID_CLOG_EDIT_BEFORE_CALL,
        MENU_ID_CLOG_DELETE,
        MENU_ID_CLOG_DELETE_ALL,
        MENU_ID_CLOG_ADVANCED,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_OPTIONS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLOG_VIEW,
        MENU_ID_CLOG_OPTION,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_VIEW,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLOG_MAKE_CALL,
        MENU_ID_CLOG_OPTION,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_DIAL,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLOG_SAVE_TO_PHB,
        MENU_ID_CLOG_OPTION,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_SAVE_TO_PHONEBOOK,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLOG_ADD_TO_BLACK_LIST,
        MENU_ID_CLOG_OPTION,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CLOG_ADD_TO_BLACK_LIST,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLOG_EDIT_BEFORE_CALL,
        MENU_ID_CLOG_OPTION,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_EDIT_BEFORE_CALL,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLOG_CALL_TIME,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CLOG_CALL_TIME,
        IMG_ID_CLOG_CALL_TIME));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLOG_CTIME_OPTION,
        0,
        1,
        MENU_ID_CLOG_CTIME_RESET_ALL_SIM1,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_OPTIONS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLOG_CTIME_RESET_ALL_SIM1,
        MENU_ID_CLOG_CTIME_OPTION,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CLOG_CTIME_RESET_ALL,
        0));

/******************** Menu resource IDs - finish ********************/

/******************** Menu Hilite/Hint Handlers - begin ********************/
/******************** Menu Hilite/Hint Handlers - finish ********************/
}
