/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_app_camera.c
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   MTK resgenerator XML parser
 *
 *******************************************************************************/
#include "CustDataProts.h"
#include "mmi_rp_app_camera_def.h"

/* Application specified header files for using old res IDs */
#include "MMI_features.h"
#include "MMIDataType.h"    /* for resource base */

#include "CustResDef.h"         /* for image/audio path */
#include "GlobalMenuItems.h"    /* for menu resource */

#include "SlideShowResDef.h"
#include "GlobalResDef.h"
#include "FileMgrServiceResDef.h"
#include "ImageViewerResDef.h"
#include "PopulateRes.h"


/*****************************************************************************
* FUNCTION
*  mmi_rp_app_camera_populate
* DESCRIPTION
*  Automatically generated populate function for mmi_rp_app_camera_populate
* PARAMETERS
*  void
* RETURNS
*  void
*****************************************************************************/
void mmi_rp_app_camera_populate(void)
{
    /*----------------------------------------------------------------*/
    /* Local Variables                                                */
    /*----------------------------------------------------------------*/

    /*----------------------------------------------------------------*/
    /* Code Body                                                      */
    /*----------------------------------------------------------------*/

/******************** Menu resource IDs - begin ********************/
    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CAMERA_TO_IMGVIEW,
        MENU_ID_CAMERA_OPTION,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CAMERA_TO_IMGVIEW,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CAMERA_CAMERA_SETTING,
        MENU_ID_CAMERA_OPTION,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CAMERA_CAMERA_SETTING,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CAMERA_IMAGE_SETTING,
        MENU_ID_CAMERA_OPTION,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CAMERA_IMAGE_SETTING,
        0));

    ADD_APPLICATION_MENUITEM5((
        MAIN_MENU_OPTION_CAMERA_APP,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CAMERA_APP_NAME,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CAMERA_WB_AUTO,
        MENU_ID_CAMERA_WB,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CAMERA_WB_AUTO,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CAMERA_WB_DAYLIGHT,
        MENU_ID_CAMERA_WB,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CAMERA_WB_DAYLIGHT,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CAMERA_WB_TUNGSTEN,
        MENU_ID_CAMERA_WB,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CAMERA_WB_TUNGSTEN,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CAMERA_WB_FLUORESCENT,
        MENU_ID_CAMERA_WB,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CAMERA_WB_FLUORESCENT,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CAMERA_WB_CLOUD,
        MENU_ID_CAMERA_WB,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CAMERA_WB_CLOUD,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CAMERA_WB_INCANDESCENCE,
        MENU_ID_CAMERA_WB,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CAMERA_WB_INCANDESCENCE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CAMERA_DSC_MODE_AUTO,
        MENU_ID_CAMERA_DSC_MODE,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CAMERA_DSC_MODE_AUTO,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CAMERA_DSC_MODE_NIGHT,
        MENU_ID_CAMERA_DSC_MODE,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CAMERA_DSC_MODE_NIGHT,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CAMERA_EFFECT_NORMAL,
        MENU_ID_CAMERA_EFFECT_SETTING,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CAMERA_EFFECT_NORMAL,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CAMERA_EFFECT_GRAYSCALE,
        MENU_ID_CAMERA_EFFECT_SETTING,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CAMERA_EFFECT_GRAYSCALE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CAMERA_EFFECT_SEPIA,
        MENU_ID_CAMERA_EFFECT_SETTING,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CAMERA_EFFECT_SEPIA,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CAMERA_EFFECT_SEPIA_GREEN,
        MENU_ID_CAMERA_EFFECT_SETTING,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CAMERA_EFFECT_SEPIA_GREEN,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CAMERA_EFFECT_SEPIA_BLUE,
        MENU_ID_CAMERA_EFFECT_SETTING,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CAMERA_EFFECT_SEPIA_BLUE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CAMERA_EFFECT_COLOR_INVERT,
        MENU_ID_CAMERA_EFFECT_SETTING,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CAMERA_EFFECT_COLOR_INVERT,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CAMERA_STORAGE_PHONE,
        MENU_ID_CAMERA_STORAGE,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_PHONE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CAMERA_STORAGE_MEMORY_CARD,
        MENU_ID_CAMERA_STORAGE,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_MEMORY_CARD,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CAMERA_RESTORE_DEFAULT,
        MENU_ID_CAMERA_OPTION,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CAMERA_RESTORE_DEFAULT,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CAMERA_CONFIRM_OPTION_DELETE,
        MENU_ID_CAMERA_CONFIRM_OPTION,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_DELETE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CAMERA_FORWARD_OPTION_TO_MMS,
        MENU_ID_CAMERA_FORWARD_OPTION,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_AS_MULTIMEDIA_MSG,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CAMERA_FORWARD_OPTION_TO_BT,
        MENU_ID_CAMERA_FORWARD_OPTION,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_VIA_BLUETOOTH,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CAMERA_FORWARD_OPTION_TO_EMAIL,
        MENU_ID_CAMERA_FORWARD_OPTION,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_AS_EMAIL,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CAMERA_APP,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CAMERA_APP_NAME,
        IMG_ID_CAMERA_APP_ICON));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CAMERA_OPTION,
        0,
        8,
        MENU_ID_CAMERA_TO_IMGVIEW,
        MENU_ID_CAMERA_CAMERA_SETTING,
        MENU_ID_CAMERA_IMAGE_SETTING,
        MENU_ID_CAMERA_WB,
        MENU_ID_CAMERA_DSC_MODE,
        MENU_ID_CAMERA_EFFECT_SETTING,
        MENU_ID_CAMERA_STORAGE,
        MENU_ID_CAMERA_RESTORE_DEFAULT,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_OPTIONS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CAMERA_EFFECT_CUSTOM_FX_SET_OPTION,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_OPTIONS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CAMERA_EFFECT_CUSTOM_FX_EDIT_OPTION,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_OPTIONS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CAMERA_STORAGE,
        0,
        2,
        MENU_ID_CAMERA_STORAGE_PHONE,
        MENU_ID_CAMERA_STORAGE_MEMORY_CARD,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_STORAGE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CAMERA_WB,
        0,
        6,
        MENU_ID_CAMERA_WB_AUTO,
        MENU_ID_CAMERA_WB_DAYLIGHT,
        MENU_ID_CAMERA_WB_TUNGSTEN,
        MENU_ID_CAMERA_WB_FLUORESCENT,
        MENU_ID_CAMERA_WB_CLOUD,
        MENU_ID_CAMERA_WB_INCANDESCENCE,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_ID_CAMERA_WB,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CAMERA_DSC_MODE,
        0,
        2,
        MENU_ID_CAMERA_DSC_MODE_AUTO,
        MENU_ID_CAMERA_DSC_MODE_NIGHT,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_ID_CAMERA_DSC_MODE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CAMERA_EFFECT_SETTING,
        0,
        6,
        MENU_ID_CAMERA_EFFECT_NORMAL,
        MENU_ID_CAMERA_EFFECT_GRAYSCALE,
        MENU_ID_CAMERA_EFFECT_SEPIA,
        MENU_ID_CAMERA_EFFECT_SEPIA_GREEN,
        MENU_ID_CAMERA_EFFECT_SEPIA_BLUE,
        MENU_ID_CAMERA_EFFECT_COLOR_INVERT,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_ID_CAMERA_EFFECT_SETTING,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CAMERA_CONFIRM_OPTION,
        0,
        2,
        MENU_ID_CAMERA_FORWARD_OPTION,
        MENU_ID_CAMERA_CONFIRM_OPTION_DELETE,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_OPTIONS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CAMERA_FORWARD_OPTION,
        0,
        3,
        MENU_ID_CAMERA_FORWARD_OPTION_TO_MMS,
        MENU_ID_CAMERA_FORWARD_OPTION_TO_EMAIL,
        MENU_ID_CAMERA_FORWARD_OPTION_TO_BT,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_SEND,
        0));

/******************** Menu resource IDs - finish ********************/

/******************** Menu Hilite/Hint Handlers - begin ********************/
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MAIN_MENU_OPTION_CAMERA_APP, mmi_camera_hilight_app);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_CAMERA_FORWARD_OPTION_TO_MMS, mmi_camera_hilight_forward_to_mms);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_CAMERA_APP, mmi_camera_hilight_app);
/******************** Menu Hilite/Hint Handlers - finish ********************/
}
