/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_app_mre.c
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   MTK resgenerator XML parser
 *
 *******************************************************************************/
#include "CustDataProts.h"
#include "mmi_rp_app_mre_def.h"

/* Application specified header files for using old res IDs */
#include "MMI_features.h"
#include "MMIDataType.h"    /* for resource base */

#include "CustResDef.h"         /* for image/audio path */
#include "GlobalMenuItems.h"    /* for menu resource */

#include "mmi_rp_app_am_def.h"
#include "GlobalResDef.h"
#include "mmi_rp_app_filemanager_def.h"


/*****************************************************************************
* FUNCTION
*  mmi_rp_app_mre_populate
* DESCRIPTION
*  Automatically generated populate function for mmi_rp_app_mre_populate
* PARAMETERS
*  void
* RETURNS
*  void
*****************************************************************************/
void mmi_rp_app_mre_populate(void)
{
    /*----------------------------------------------------------------*/
    /* Local Variables                                                */
    /*----------------------------------------------------------------*/

    /*----------------------------------------------------------------*/
    /* Code Body                                                      */
    /*----------------------------------------------------------------*/

/******************** Menu resource IDs - begin ********************/
    ADD_APPLICATION_MENUITEM5((
        MENU_ID_MRE_APP_CALCULATOR_SHORTCUT,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_AM_APP_NAME_CALCULATOR,
        IMG_ID_AM_APP_CALCULATOR_SHORTCUT));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_MRE_APP_HEALTH_SHORTCUT,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_AM_APP_NAME_HEALTH,
        IMG_ID_AM_APP_HEALTH_SHORTCUT));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_MRE_APP_STOPWATCH_SHORTCUT,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_AM_APP_NAME_STOPWATCH,
        IMG_ID_AM_APP_STOPWATCH_SHORTCUT));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_MRE_APP_CONVERTER_SHORTCUT,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_AM_APP_NAME_CONVERTER,
        IMG_ID_AM_APP_CONVERTER_SHORTCUT));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_MRE_APP_ZAKAT_SHORTCUT,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_AM_APP_NAME_ZAKAT,
        IMG_ID_AM_APP_ZAKAT_SHORTCUT));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_MRE_APP_EGYPTCODE_SHORTCUT,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_AM_APP_NAME_EGYPTCODE,
        IMG_ID_AM_APP_EGYPTCODE_SHORTCUT));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_MRE_APP_GIRLSLOT_SHORTCUT,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_AM_APP_NAME_GIRLSLOT,
        IMG_ID_AM_APP_GIRLSLOT_SHORTCUT));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_MRE_APP_GOLDMINER_SHORTCUT,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_AM_APP_NAME_GOLDMINER,
        IMG_ID_AM_APP_GOLDMINER_SHORTCUT));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_MRE_APP_HAPPYEGG_SHORTCUT,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_AM_APP_NAME_HAPPYEGG,
        IMG_ID_AM_APP_HAPPYEGG_SHORTCUT));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_MRE_APP_HAPPYWAR_SHORTCUT,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_AM_APP_NAME_HAPPYWAR,
        IMG_ID_AM_APP_HAPPYWAR_SHORTCUT));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_MRE_APP_KINGCOMBAT_SHORTCUT,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_AM_APP_NAME_KINGCOMBAT,
        IMG_ID_AM_APP_KINGCOMBAT_SHORTCUT));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_MRE_APP_MOTO_SHORTCUT,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_AM_APP_NAME_MOTO,
        IMG_ID_AM_APP_MOTO_SHORTCUT));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_MRE_APP_PARKOUR_SHORTCUT,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_AM_APP_NAME_PARKOUR,
        IMG_ID_AM_APP_PARKOUR_SHORTCUT));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_MRE_APP_TWITTER_SHORTCUT,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_AM_APP_NAME_TWITTER,
        IMG_ID_AM_APP_TWITTER_SHORTCUT));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_MRE_APP_GAMELOFT_LIVE_SHORTCUT,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_AM_APP_NAME_GAMELOFT_GLIVE,
        IMG_ID_AM_APP_GAMELOFT_GLIVE_SHORTCUT));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_MRE_APP_GMOBI_APPSTORE_SHORTCUT,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_AM_APP_NAME_GMOBI_APPSTORE,
        IMG_ID_AM_APP_GMOBI_APPSTORE_SHORTCUT));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_MRE_APP_MBOUNCE_APPSTORE_SHORTCUT,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_AM_APP_NAME_MBOUNCE_APPSTORE,
        IMG_ID_AM_APP_MBOUNCE_APPSTORE_SHORTCUT));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FMGR_MRE_FILE_OPEN,
        MENU_ID_FMGR_MRE_TYPE_OPTIONS,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_OPEN,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FMGR_MRE_OPTION_INSTALL,
        MENU_ID_FMGR_MRE_TYPE_OPTIONS,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_INSTALL,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FMGR_MRE_TYPE_OPTIONS,
        0,
        12,
        MENU_ID_FMGR_MRE_OPTION_INSTALL,
        MENU_ID_FMGR_MRE_FILE_OPEN,
        MENU_ID_FMGR_GEN_OPTION_FORWARD_SEND,
        MENU_ID_FMGR_GEN_OPTION_FORWARD_USE,
        MENU_ID_FMGR_FOLDER_CREATE,
        MENU_ID_FMGR_GEN_OPTION_MORE_RITS,
        MENU_ID_FMGR_GEN_OPTION_RENAME,
        MENU_ID_FMGR_GEN_OPTION_DELETE,
        MENU_ID_FMGR_GEN_OPTION_SORT,
        MENU_ID_FMGR_GEN_OPTION_COPY,
        MENU_ID_FMGR_GEN_OPTION_MOVE,
        MENU_ID_FMGR_GEN_OPTION_DETAIL,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_OPTIONS,
        0));

/******************** Menu resource IDs - finish ********************/

/******************** Menu Hilite/Hint Handlers - begin ********************/
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_MRE_APP_CALCULATOR_SHORTCUT, mmi_mre_shortcut_calculator_highlight_hdlr);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_MRE_APP_HEALTH_SHORTCUT, mmi_mre_shortcut_health_highlight_hdlr);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_MRE_APP_STOPWATCH_SHORTCUT, mmi_mre_shortcut_stopwatch_highlight_hdlr);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_MRE_APP_CONVERTER_SHORTCUT, mmi_mre_shortcut_converter_highlight_hdlr);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_MRE_APP_ZAKAT_SHORTCUT, mmi_mre_shortcut_zakat_highlight_hdlr);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_MRE_APP_EGYPTCODE_SHORTCUT, mmi_mre_shortcut_egyptcode_highlight_hdlr);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_MRE_APP_GIRLSLOT_SHORTCUT, mmi_mre_shortcut_girlslot_highlight_hdlr);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_MRE_APP_GOLDMINER_SHORTCUT, mmi_mre_shortcut_goldminer_highlight_hdlr);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_MRE_APP_HAPPYEGG_SHORTCUT, mmi_mre_shortcut_happyegg_highlight_hdlr);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_MRE_APP_HAPPYWAR_SHORTCUT, mmi_mre_shortcut_happywar_highlight_hdlr);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_MRE_APP_KINGCOMBAT_SHORTCUT, mmi_mre_shortcut_kingcombat_highlight_hdlr);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_MRE_APP_MOTO_SHORTCUT, mmi_mre_shortcut_moto_highlight_hdlr);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_MRE_APP_PARKOUR_SHORTCUT, mmi_mre_shortcut_parkour_highlight_hdlr);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_MRE_APP_TWITTER_SHORTCUT, mmi_mre_shortcut_twitter_highlight_hdlr);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_MRE_APP_GAMELOFT_LIVE_SHORTCUT, mmi_mre_shortcut_gameloft_live_highlight_hdlr);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_MRE_APP_GMOBI_APPSTORE_SHORTCUT, mmi_mre_shortcut_gmobi_appstore_highlight_hdlr);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_MRE_APP_MBOUNCE_APPSTORE_SHORTCUT, mmi_mre_shortcut_mbounce_appstore_highlight_hdlr);
/******************** Menu Hilite/Hint Handlers - finish ********************/
}
