/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_app_engineermode1.c
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   MTK resgenerator XML parser
 *
 *******************************************************************************/
#include "CustDataProts.h"
#include "mmi_rp_app_engineermode1_def.h"

/* Application specified header files for using old res IDs */
#include "MMI_features.h"
#include "MMIDataType.h"    /* for resource base */

#include "CustResDef.h"         /* for image/audio path */
#include "GlobalMenuItems.h"    /* for menu resource */

#include "MMI_features.h"
#include "MMIDataType.h"
#include "GlobalResDef.h"


/*****************************************************************************
* FUNCTION
*  mmi_rp_app_engineermode1_populate
* DESCRIPTION
*  Automatically generated populate function for mmi_rp_app_engineermode1_populate
* PARAMETERS
*  void
* RETURNS
*  void
*****************************************************************************/
void mmi_rp_app_engineermode1_populate(void)
{
    /*----------------------------------------------------------------*/
    /* Local Variables                                                */
    /*----------------------------------------------------------------*/

    /*----------------------------------------------------------------*/
    /* Code Body                                                      */
    /*----------------------------------------------------------------*/

/******************** Menu resource IDs - begin ********************/
    ADD_APPLICATION_MENUITEM5((
        MENU_ID_EM_MISC_ON,
        MENU_ID_EM_AUD_VM_SUPPORT,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_ON,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_EM_MISC_OFF,
        MENU_ID_EM_AUD_VM_SUPPORT,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_OFF,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_EM_TRUE,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_EM_TRUE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_EM_FALSE,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_EM_FALSE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_EM_MAIN_MENU,
        0,
        4,
        MENU_ID_EM_DEVICE,
        MENU_ID_EM_AUDIO,
        MENU_ID_EM_MISC,
        MENU_ID_EM_PROFILING,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_APP_MAIN,
        STR_ID_EM_APP_NAME,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_EM_DEVICE,
        0,
        3,
        MENU_ID_EM_DEV_SET_UART,
        MENU_ID_EM_MM_COLOR,
        MENU_ID_EM_DEV_DCM_MODE,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_APP_SUB,
        STR_ID_EM_DEVICE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_EM_MM_COLOR,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_EM_DEV_MM_COLOR,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_EM_DEV_SET_UART,
        0,
        1,
        MENU_ID_EM_DEV_UART_SETTING,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_APP_SUB,
        STR_ID_EM_DEV_SET_UART,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_EM_DEV_UART_SETTING,
        MENU_ID_EM_DEV_SET_UART,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_EM_DEV_SET_UART_SETTING,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_EM_DEV_DCM_MODE,
        0,
        2,
        MENU_ID_EM_DEV_DCM_MODE_ON,
        MENU_ID_EM_DEV_DCM_MODE_OFF,
        SHOW,
        MMI_RG_MENU_FLAG_RADIO,
        MMI_RG_MENU_TYPE_APP_SUB,
        STR_ID_EM_DEV_DCM_MODE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_EM_DEV_DCM_MODE_ON,
        MENU_ID_EM_DEV_DCM_MODE,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_ON,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_EM_DEV_DCM_MODE_OFF,
        MENU_ID_EM_DEV_DCM_MODE,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_OFF,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_EM_AUDIO,
        0,
        1,
        MENU_ID_EM_AUD_AUTO_VM_SETTING,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_APP_SUB,
        STR_ID_EM_AUDIO,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_EM_AUD_VM_SUPPORT,
        0,
        2,
        MENU_ID_EM_MISC_ON,
        MENU_ID_EM_MISC_OFF,
        SHOW,
        MMI_RG_MENU_FLAG_RADIO,
        MMI_RG_MENU_TYPE_APP_SUB,
        STR_ID_EM_AUD_VM_SUPPORT,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_EM_AUD_AUTO_VM_SPH,
        0,
        2,
        MENU_ID_EM_MISC_ON,
        MENU_ID_EM_MISC_OFF,
        SHOW,
        MMI_RG_MENU_FLAG_RADIO,
        MMI_RG_MENU_TYPE_APP_SUB,
        STR_ID_EM_AUD_AUTO_VM_SPH,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_EM_AUD_AUTO_VM_SETTING,
        0,
        2,
        MENU_ID_EM_MISC_ON,
        MENU_ID_EM_MISC_OFF,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_APP_SUB,
        STR_ID_EM_AUD_AUTO_VM_SETTING,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_EM_MISC,
        0,
        2,
        MENU_ID_EM_MISC_MEMORY_DUMP,
        MENU_ID_EM_MRE,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_APP_SUB,
        STR_ID_EM_MISC,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_EM_MISC_MEMORY_DUMP,
        0,
        2,
        MENU_ID_EM_MISC_ON,
        MENU_ID_EM_MISC_OFF,
        SHOW,
        MMI_RG_MENU_FLAG_RADIO,
        MMI_RG_MENU_TYPE_APP_SUB,
        STR_ID_EM_MISC_MEMORY_DUMP,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_EM_MRE,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_EM_MRE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_EM_PROFILING,
        0,
        2,
        MENU_ID_EM_PROFILING_FRAMEWORK,
        MENU_ID_EM_PROFILING_SWLA,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_APP_SUB,
        STR_ID_EM_PROFILING,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_EM_PROFILING_SWLA,
        0,
        2,
        MENU_ID_EM_PROFILING_SWLA_ON,
        MENU_ID_EM_PROFILING_SWLA_OFF,
        SHOW,
        MMI_RG_MENU_FLAG_RADIO,
        MMI_RG_MENU_TYPE_APP_SUB,
        STR_ID_EM_PROFILING_SWLA,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_EM_PROFILING_SWLA_ON,
        MENU_ID_EM_PROFILING_SWLA,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_ON,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_EM_PROFILING_SWLA_OFF,
        MENU_ID_EM_PROFILING_SWLA,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_OFF,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_EM_PROFILING_FRAMEWORK,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_APP_SUB,
        STR_ID_EM_PROFILING_FRM,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_EM_PROFILING_OPTION,
        0,
        2,
        MENU_ID_EM_PROFILING_START,
        MENU_ID_EM_PROFILING_SETTING,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_OPTIONS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_EM_PROFILING_START,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_START,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_EM_PROFILING_SETTING,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_SETTINGS,
        0));

/******************** Menu resource IDs - finish ********************/

/******************** Menu Hilite/Hint Handlers - begin ********************/
/******************** Menu Hilite/Hint Handlers - finish ********************/
}
