#include "mmi_features.h"
#include "custresdef.h"

<?xml version="1.0" encoding="UTF-8"?>

#if defined(__MMI_ATV_SUPPORT__)

<APP id="VAPP_ATV"  
package_name="native.mtk.atv" 
name="STR_ID_VAPP_ATV_APP_NAME" 
img = "MAIN_MENU_ATV_ICON" 
launch = "vapp_atv_launch" 
package_proc = "vapp_atv_package_proc" 
type="venus">

#if defined(__ATV_RECORD_SUPPORT__)
<MEMORY heap="300*1024" 
  extra_base="VAPP_ATV_SERVICE_SIZE + base(SRV_MDI_ATV_REC) + base(SRV_MDI_VDOPLY_PREVIEW) + VAPP_ATV_THUMBNAIL_SIZE" 
          fg="max(max(fg(SRV_MDI_ATV_REC), base(SRV_MDI_ATV_REC)+fg(SRV_MDI_VDOPLY_PREVIEW)), fg(SRV_MDI_ATV_REC) + VAPP_ATV_SNAPSHOT_SIZE) + VAPP_ATV_LAYER_SIZE " 
          inc="vapp_atv_gprot.h"/>
#else
<MEMORY heap="300*1024" 
  extra_base="VAPP_ATV_SERVICE_SIZE + base(SRV_MDI_ATV) + VAPP_ATV_THUMBNAIL_SIZE" 
          fg="fg(SRV_MDI_ATV) + VAPP_ATV_SNAPSHOT_SIZE + VAPP_ATV_LAYER_SIZE" 
          vrt_mem_factor = "1.5"
          inc="vapp_atv_gprot.h"/>
#endif

<!----------------------------------------------------------------------------------------
******** String section
------------------------------------------------------------------------------------------>
    <STRING id="STR_ID_VAPP_ATV_APP_NAME"/>
    <STRING id="STR_ID_VAPP_ATV_SCAN_LOCATION"/>
    <STRING id="STR_ID_VAPP_ATV_SCAN"/>
    <STRING id="STR_ID_VAPP_ATV_SCANNING"/>
    <STRING id="STR_ID_VAPP_ATV_INITIALIZING"/>
    <STRING id="STR_ID_VAPP_ATV_NO_SERVICE_ASK"/>
    <STRING id="STR_ID_VAPP_ATV_SAVE_RECORD_ASK"/>
    <STRING id="STR_ID_VAPP_ATV_SAVE_PATH_CONFIRM"/>
    <STRING id="STR_ID_VAPP_ATV_IS_BACKGROUND_CALL"/>
    <STRING id="STR_ID_VAPP_ATV_BT_IS_WORKING"/>
    <STRING id="STR_ID_VAPP_ATV_AUD_MODE"/>
    <STRING id="STR_ID_VAPP_ATV_CHANGE_SCAN_LOCATION"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_START"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_AFGHANISTAN"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_ARGENTINA"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_AUSTRALIA"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_BRAZIL"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_CAMBODIA"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_CANADA"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_CHILE"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_CHINA"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_HONGKONG"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_SHENZHEN"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_CONGO"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_EUROPE_EASTERN"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_FRANCE"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_GABON"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_INDIA"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_INDONESIA"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_IRAN"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_IRELAND"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_ITALY"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_IVORYCOAST"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_JAPAN"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_KOREA"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_LAOS"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_MADAGASCAR"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_MALAYSIA"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_MEXICO"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_MOROCCO"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_MYANMAR"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_NEWZEALAND"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_PAKISTAN"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_PARAGUAY"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_PHILIPPINES"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_PORTUGAL"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_REUNION"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_RUSSIA"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_RWANDA"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_SENEGAL"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_SINGAPORE"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_SOUTHAFRICA"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_SPAIN"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_TAIWAN"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_THAILAND"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_TURKEY"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_UNITED_ARAB_EMIRATES"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_UNITED_KINGDOM"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_USA"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_URUGUAY"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_VENEZUELA"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_VIETNAM"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_EUROPE_WESTERN"/>
    <STRING id="STR_ID_VAPP_ATV_COUNTRY_END"/>
    <STRING id="STR_ID_VAPP_ATV_AUD_MODE_MONO"/>
    <STRING id="STR_ID_VAPP_ATV_AUD_MODE_MTS_STEREO"/>
    <STRING id="STR_ID_VAPP_ATV_AUD_MODE_MTS_SAP"/>
    <STRING id="STR_ID_VAPP_ATV_AUD_MODE_MPS_MONO"/>
    <STRING id="STR_ID_VAPP_ATV_AUD_MODE_MPS_STEREO"/>
    <STRING id="STR_ID_VAPP_ATV_AUD_MODE_MPS_SUB"/>
    <STRING id="STR_ID_VAPP_ATV_AUD_MODE_MPS_MAIN_SUB"/>
    <STRING id="STR_ID_VAPP_ATV_AUD_MODE_MPS_MAIN"/>
    <STRING id="STR_ID_VAPP_ATV_AUD_MODE_FM_MONO"/>
    <STRING id="STR_ID_VAPP_ATV_AUD_MODE_A2_STEREO"/>
    <STRING id="STR_ID_VAPP_ATV_AUD_MODE_A2_DUAL1"/>
    <STRING id="STR_ID_VAPP_ATV_AUD_MODE_A2_DUAL2"/>
    <STRING id="STR_ID_VAPP_ATV_AUD_MODE_NICAM_MONO"/>
    <STRING id="STR_ID_VAPP_ATV_AUD_MODE_NICAM_STEREO"/>
    <STRING id="STR_ID_VAPP_ATV_AUD_MODE_NICAM_DUAL1"/>
    <STRING id="STR_ID_VAPP_ATV_AUD_MODE_NICAM_DUAL2"/>

    <STRING id="STR_ID_VAPP_ATV_PLAYER_SETTINGS"/>
    <STRING id="STR_ID_VAPP_ATV_BRIGHTNESS"/>
    <STRING id="STR_ID_VAPP_ATV_CONTRAST"/>
    <STRING id="STR_ID_VAPP_ATV_SATURATION"/>
    <STRING id="STR_ID_VAPP_ATV_SET_PLAYER_SETTING"/>
    <STRING id="STR_ID_VAPP_ATV_RECORD_SIZE"/>
    <STRING id="STR_ID_VAPP_ATV_176X144"/>
    <STRING id="STR_ID_VAPP_ATV_320X240"/>
    <STRING id="STR_ID_VAPP_ATV_480X320"/>
    <STRING id="STR_ID_VAPP_ATV_NOTIFY_HW_NOT_READY"/>
	<STRING id="STR_ID_VAPP_ATV_NOTIFY_INSERT_MEMORY_CARD"/>
<!----------------------------------------------------------------------------------------
******** Image section
------------------------------------------------------------------------------------------>
#ifndef __MMI_ATV_SLIM__
    #define ATV_SIGNAL_PATH     RES_IMG_ROOT"\\\\Atv\\\\Signal\\\\"
    #define ATV_RECORD_PATH     RES_IMG_ROOT"\\\\ATV\\\\record\\\\"
    #define ATV_TOOLBAR_PATH    RES_IMG_ROOT"\\\\ATV\\\\Toolbar\\\\"
    #define ATV_ADJUST_PATH     RES_IMG_ROOT"\\\\ATV\\\\adjust\\\\"
    #define ATV_WHEEL_PATH      RES_IMG_ROOT"\\\\ATV\\\\wheel\\\\"
#else
	#define ATV_SIGNAL_PATH     RES_IMG_ROOT"\\\\Redesign\\\\Atv\\\\Signal\\\\"
    #define ATV_RECORD_PATH     RES_IMG_ROOT"\\\\Redesign\\\\ATV\\\\record\\\\"
    #define ATV_TOOLBAR_PATH    RES_IMG_ROOT"\\\\Redesign\\\\ATV\\\\Toolbar\\\\"
    #define ATV_ADJUST_PATH     RES_IMG_ROOT"\\\\Redesign\\\\ATV\\\\adjust\\\\"
    #define ATV_WHEEL_PATH      RES_IMG_ROOT"\\\\Redesign\\\\ATV\\\\wheel\\\\"
#endif

    <THEME>
        <IMAGE id="MAIN_MENU_ATV_ICON" desc="Main menu mobile TV icon">RES_IMG_ROOT"\\\\"__MMI_MAINMENU_ICON_DEFAULT_PATH__"\\\\MobileTV.png"</IMAGE>
    </THEME>
    <IMAGE id="IMG_ID_VAPP_ATV_SIGNAL_LEVEL_0">ATV_SIGNAL_PATH"signal_0.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_ATV_SIGNAL_LEVEL_1">ATV_SIGNAL_PATH"signal_1.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_ATV_SIGNAL_LEVEL_2">ATV_SIGNAL_PATH"signal_2.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_ATV_SIGNAL_LEVEL_3">ATV_SIGNAL_PATH"signal_3.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_ATV_SIGNAL_LEVEL_4">ATV_SIGNAL_PATH"signal_4.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_ATV_TBAR_BTN_HIDE">ATV_TOOLBAR_PATH"btn_hide.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_ATV_TBAR_BTN_SHOW">ATV_TOOLBAR_PATH"btn_show.png"</IMAGE>
    
    <IMAGE id="IMG_ID_VAPP_ATV_TBAR_SCAN">ATV_TOOLBAR_PATH"icon_search.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_ATV_TBAR_SCAN_LOCATION">ATV_TOOLBAR_PATH"icon_scan_location.png"</IMAGE>
    
    <IMAGE id="IMG_ID_VAPP_ATV_TBAR_SNAPSHOT">ATV_TOOLBAR_PATH"icon_snapshot.png"</IMAGE>
    #ifndef __MMI_ATV_SLIM__
    <IMAGE id="IMG_ID_VAPP_ATV_TBAR_SNAPSHOT_D">ATV_TOOLBAR_PATH"icon_snapshot_d.png"</IMAGE>
    #else
	  <IMAGE id="IMG_ID_VAPP_ATV_TBAR_SNAPSHOT_D">RES_IMG_ROOT"\\\\ATV\\\\Toolbar\\\\icon_snapshot_d.png"</IMAGE>
	  #endif
    <IMAGE id="IMG_ID_VAPP_ATV_TBAR_AUD_MODE">ATV_TOOLBAR_PATH"icon_stereo.png"</IMAGE>
    #ifndef __MMI_ATV_SLIM__
    <IMAGE id="IMG_ID_VAPP_ATV_TBAR_AUD_MODE_D">ATV_TOOLBAR_PATH"icon_stereo_d.png"</IMAGE>
		#else
		<IMAGE id="IMG_ID_VAPP_ATV_TBAR_AUD_MODE_D">RES_IMG_ROOT"\\\\ATV\\\\Toolbar\\\\icon_stereo_d.png"</IMAGE>
		#endif

    <IMAGE id="IMG_ID_VAPP_ATV_TBAR_BG">ATV_TOOLBAR_PATH"pannel_bg.9slice.png"</IMAGE>
    #ifndef __MMI_ATV_SLIM__
    <IMAGE id="IMG_ID_VAPP_ATV_TBAR_BG_LINE">ATV_TOOLBAR_PATH"pannel_line.png"</IMAGE>
		#else
		<IMAGE id="IMG_ID_VAPP_ATV_TBAR_BG_LINE">RES_IMG_ROOT"\\\\ATV\\\\Toolbar\\\\pannel_line.png"</IMAGE>
		#endif
    
    #ifndef __MMI_ATV_SLIM__
    <IMAGE id="IMG_ID_VAPP_ATV_ADJUST_LIST_BG">ATV_ADJUST_PATH"list_bg.9slice.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_ATV_ADJUST_SOFTKEY_BG_N">ATV_ADJUST_PATH"softkeybar_n.9slice.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_ATV_ADJUST_SOFTKEY_BG_D">ATV_ADJUST_PATH"softkeybar_d.9slice.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_ATV_ADJUST_SOFTKEY_LINE">ATV_ADJUST_PATH"splitline.png"</IMAGE>

    <IMAGE id="IMG_ID_VAPP_ATV_REC_START">ATV_RECORD_PATH"btn_record.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_ATV_REC_PAUSE">ATV_RECORD_PATH"btn_pause.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_ATV_REC_STOP">ATV_RECORD_PATH"btn_stop.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_ATV_REC_STATUS">ATV_RECORD_PATH"icon_rec.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_ATV_REC_PAUSE_STATUS">ATV_RECORD_PATH"icon_pause.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_ATV_REC_LEFT_BG_D">ATV_RECORD_PATH"left_bg_d.9slice.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_ATV_REC_LEFT_BG_N">ATV_RECORD_PATH"left_bg_n.9slice.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_ATV_REC_RIGHT_BG_D">ATV_RECORD_PATH"right_bg_d.9slice.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_ATV_REC_RIGHT_BG_N">ATV_RECORD_PATH"right_bg_n.9slice.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_ATV_REC_LAST_FRAME">ATV_RECORD_PATH"last_frame.png"</IMAGE>
	#endif

    <IMAGE id="IMG_ID_VAPP_ATV_TBAR_RECORD">ATV_TOOLBAR_PATH"icon_record.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_ATV_TBAR_RECORD_D">ATV_TOOLBAR_PATH"icon_record_d.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_ATV_TBAR_SETTINGS">ATV_TOOLBAR_PATH"icon_settings.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_ATV_TBAR_SELECT_STORAGE">ATV_TOOLBAR_PATH"icon_storage.png"</IMAGE>

	#ifndef __MMI_ATV_SLIM__
    <IMAGE id="IMG_ID_VAPP_ATV_WHEEL_ARROW_UP">ATV_WHEEL_PATH"arrow_up.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_ATV_WHEEL_ARROW_DOWN">ATV_WHEEL_PATH"arrow_down.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_ATV_WHEEL_BTN_UP_N">ATV_WHEEL_PATH"btn_up_n.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_ATV_WHEEL_BTN_UP_D">ATV_WHEEL_PATH"btn_up_d.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_ATV_WHEEL_BTN_DOWN_N">ATV_WHEEL_PATH"btn_down_n.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_ATV_WHEEL_BTN_DOWN_D">ATV_WHEEL_PATH"btn_down_d.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_ATV_WHEEL_BG">ATV_WHEEL_PATH"wheel_bg.png"</IMAGE>
	#else
	<IMAGE id="IMG_ID_VAPP_ATV_WHEEL_ARROW">ATV_WHEEL_PATH"arrow.png"</IMAGE>
	<IMAGE id="IMG_ID_VAPP_ATV_WHEEL_PANNEL">ATV_WHEEL_PATH"pannel_bg.9slice.png"</IMAGE>
	#endif
    
</APP>

#endif /* __MMI_ATV_SUPPORT__ */
