/*
 * Generated by MTK DrvGen Version 10.01.0 for MT6260NP. Copyright MediaTek Inc. (C) 2012.
 * Wed Dec 02 16:34:00 2020
 * Do Not Modify the File.
 */

#ifndef _PMIC_DRV_H
#define _PMIC_DRV_H


//init setting
//Application name


#endif /* _PMIC_DRV_H */


