#include "mmi_features.h"
#include "custresdef.h"

<?xml version="1.0" encoding="UTF-8"?>

<APP id="VAPP_IMGEDT" name="STR_ID_VAPP_IMGEDT_AP_NAME"
     package_name = "native.mtk.imgedt"
     launch = "vapp_imgedt_launch"
     package_proc = "vapp_imgedt_package_proc" 
     hidden_in_mainmenu = "true"
     type="venus">
#ifdef __MMI_COSMOS_PHOTOEDITOR__

#if defined(__MMI_COSMOS_IMGEDT_SLIM__)
    <MEMORY heap="512*1024"
            extra_base="(6*1024*1024) + (GDI_LCD_WIDTH*GDI_LCD_HEIGHT*6)"/>
#elif defined(__MMI_COSMOS_IMGEDT_PARTIAL__)
    <MEMORY heap="512*1024"
            extra_base="(8*1024*1024) + (GDI_LCD_WIDTH*GDI_LCD_HEIGHT*6)"/>
#else
    <MEMORY heap="512*1024"
            extra_base="(10*1024*1024) + (GDI_LCD_WIDTH*GDI_LCD_HEIGHT*6)"/>
#endif /* __MMI_COSMOS_IMGEDT_SLIM__ */

    <STRING id="STR_ID_VAPP_IMGEDT_ROTATE"/>
    <STRING id="STR_ID_VAPP_IMGEDT_CROP"/>
    <STRING id="STR_ID_VAPP_IMGEDT_ADJUST"/>
    <STRING id="STR_ID_VAPP_IMGEDT_EFFECT"/>
    <STRING id="STR_ID_VAPP_IMGEDT_FLIP"/>
    <STRING id="STR_ID_VAPP_IMGEDT_RESIZE"/>
    <STRING id="STR_ID_VAPP_IMGEDT_FRAME"/>
    <STRING id="STR_ID_VAPP_IMGEDT_CLIPART"/>
    <STRING id="STR_ID_VAPP_IMGEDT_TEXT"/>
    <STRING id="STR_ID_VAPP_IMGEDT_DOODLE"/>
    <STRING id="STR_ID_VAPP_IMGEDT_RATIO_FREE"/>
    <STRING id="STR_ID_VAPP_IMGEDT_RATIO_ORIGINAL"/>
    <STRING id="STR_ID_VAPP_IMGEDT_RATIO_SCREEN"/>
    <STRING id="STR_ID_VAPP_IMGEDT_RATIO_1_1"/>
    <STRING id="STR_ID_VAPP_IMGEDT_RATIO_3_4"/>
    <STRING id="STR_ID_VAPP_IMGEDT_RATIO_4_3"/>
    <STRING id="STR_ID_VAPP_IMGEDT_RATIO_9_16"/>
    <STRING id="STR_ID_VAPP_IMGEDT_RATIO_16_9"/>
    <STRING id="STR_ID_VAPP_IMGEDT_BRIGHTNESS"/>
    <STRING id="STR_ID_VAPP_IMGEDT_CONTRAST"/>
    <STRING id="STR_ID_VAPP_IMGEDT_SATURATION"/>
    <STRING id="STR_ID_VAPP_IMGEDT_HUE"/>
    <STRING id="STR_ID_VAPP_IMGEDT_NO_EFFECT"/>
    <STRING id="STR_ID_VAPP_IMGEDT_ADD_TEXT"/>
    <STRING id="STR_ID_VAPP_IMGEDT_COLOR"/>
    <STRING id="STR_ID_VAPP_IMGEDT_PEN_SIZE"/>
    <STRING id="STR_ID_VAPP_IMGEDT_ERASE_SIZE"/>
    <STRING id="STR_ID_VAPP_IMGEDT_PHOTO_NAME"/>
    <STRING id="STR_ID_VAPP_IMGEDT_PHOTO_SIZE"/>
    <STRING id="STR_ID_VAPP_IMGEDT_CROP_RATIO"/>
    <STRING id="STR_ID_VAPP_IMGEDT_SEPIA"/>
    <STRING id="STR_ID_VAPP_IMGEDT_GRAYSCALE"/>
    <STRING id="STR_ID_VAPP_IMGEDT_SHARPEN"/>
    <STRING id="STR_ID_VAPP_IMGEDT_WATER_COLOR"/>
    <STRING id="STR_ID_VAPP_IMGEDT_NEGATIVE"/>
    <STRING id="STR_ID_VAPP_IMGEDT_MIRROR"/>
    <STRING id="STR_ID_VAPP_IMGEDT_AP_NAME"/>
    <STRING id="STR_ID_VAPP_IMGEDT_OVER_WRITE"/>

    #define IMGEDT_ROOT_PATH          RES_IMG_ROOT"\\\\PhotoEditor\\\\"

    //common & others
    <IMAGE id="IMG_ID_IMGEDT_ADD_ICON">IMGEDT_ROOT_PATH"Add.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_REDUCE_ICON">IMGEDT_ROOT_PATH"Reduce.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_BALL_SMALL">IMGEDT_ROOT_PATH"CropBall01.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_BALL_LARGE">IMGEDT_ROOT_PATH"CropBall_01.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_FLIP_VERT">IMGEDT_ROOT_PATH"MirrorIcon_V.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_FLIP_HORZ">IMGEDT_ROOT_PATH"MirrorIcon_H.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_HUE_BG">IMGEDT_ROOT_PATH"HUE.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_ROTATE_BG">IMGEDT_ROOT_PATH"Round.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_RECT_FRAME">IMGEDT_ROOT_PATH"Sideline.9slice.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_RECT_FRAME_HL">IMGEDT_ROOT_PATH"Sideline_H.9slice.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_BLACK_BG">IMGEDT_ROOT_PATH"Black_BG.9slice.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_BUTTON_HALO">RES_THEME_ROOT"\\\\Theme1\\\\Common\\\\halo.png"</IMAGE>	
    <IMAGE id="IMG_ID_IMGEDT_BOTTOM_BAR">IMGEDT_ROOT_PATH"ToolBar.9slice.png"</IMAGE>
    //<IMAGE id="IMG_ID_IMGEDT_TITLE_BAR">IMGEDT_ROOT_PATH"TitleBar.9slice.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_TITLE_BAR_HORZ">IMGEDT_ROOT_PATH"TitleBar_H.9slice.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_TITLE_BAR_VERT">IMGEDT_ROOT_PATH"TitleBar_V.9slice.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_BOTTOM_HL">IMGEDT_ROOT_PATH"Button_H.9slice.png"</IMAGE>

    //titlebar icon
    <IMAGE id="IMG_ID_IMGEDT_TITLEBAR_ADJUST">IMGEDT_ROOT_PATH"TitleIcon\\\\Adjust.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_TITLEBAR_CLIPART">IMGEDT_ROOT_PATH"TitleIcon\\\\Clipart.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_TITLEBAR_CLIP">IMGEDT_ROOT_PATH"TitleIcon\\\\Crop.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_TITLEBAR_EFFECT">IMGEDT_ROOT_PATH"TitleIcon\\\\Effect.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_TITLEBAR_FLIP">IMGEDT_ROOT_PATH"TitleIcon\\\\Flip.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_TITLEBAR_FRAME">IMGEDT_ROOT_PATH"TitleIcon\\\\Frame.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_TITLEBAR_ROTATE">IMGEDT_ROOT_PATH"TitleIcon\\\\Ratate.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_TITLEBAR_RESIZE">IMGEDT_ROOT_PATH"TitleIcon\\\\Resize.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_TITLEBAR_TEXT">IMGEDT_ROOT_PATH"TitleIcon\\\\Text.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_TITLEBAR_DOODLE">IMGEDT_ROOT_PATH"TitleIcon\\\\Doodle.png"</IMAGE>

    //bottombar icon
    <IMAGE id="IMG_ID_IMGEDT_BOTTOMBAR_OK">IMGEDT_ROOT_PATH"ToolBarIcon\\\\Ok.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_BOTTOMBAR_BACK">IMGEDT_ROOT_PATH"ToolBarIcon\\\\Back.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_BOTTOMBAR_FOLD">IMGEDT_ROOT_PATH"ToolBarIcon\\\\Fold.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_BOTTOMBAR_SAVE">IMGEDT_ROOT_PATH"ToolBarIcon\\\\Save.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_BOTTOMBAR_UNDO">IMGEDT_ROOT_PATH"ToolBarIcon\\\\Undo.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_BOTTOMBAR_REDO">IMGEDT_ROOT_PATH"ToolBarIcon\\\\Redo.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_BOTTOMBAR_CANCEL">IMGEDT_ROOT_PATH"ToolBarIcon\\\\Cancel.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_BOTTOMBAR_ADJUST_BCS">IMGEDT_ROOT_PATH"ToolBarIcon\\\\Birghtness.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_BOTTOMBAR_ADJUST_HUE">IMGEDT_ROOT_PATH"ToolBarIcon\\\\Colour.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_BOTTOMBAR_BRUSH_COLOR">IMGEDT_ROOT_PATH"ToolBarIcon\\\\Brush_Colour.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_BOTTOMBAR_BRUSH_GALLEY">IMGEDT_ROOT_PATH"ToolBarIcon\\\\Brush_Gallery.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_BOTTOMBAR_BRUSH_SIZE">IMGEDT_ROOT_PATH"ToolBarIcon\\\\Brush_Size.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_BOTTOMBAR_BRUSH_ERASER">IMGEDT_ROOT_PATH"ToolBarIcon\\\\Eraser.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_BOTTOMBAR_CLIP_LIST">IMGEDT_ROOT_PATH"ToolBarIcon\\\\Cut.png"</IMAGE>
 
    //effect
    <IMAGE id="IMG_ID_IMGEDT_EFFECT_NONE">IMGEDT_ROOT_PATH"Filter\\\\Default.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_EFFECT_SEPIA">IMGEDT_ROOT_PATH"Filter\\\\Sepia.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_EFFECT_GRAYSCALE">IMGEDT_ROOT_PATH"Filter\\\\Gray.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_EFFECT_MIRROR">IMGEDT_ROOT_PATH"Filter\\\\Mirror.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_EFFECT_NEGATIVE">IMGEDT_ROOT_PATH"Filter\\\\Nagetive.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_EFFECT_OILPAINT">IMGEDT_ROOT_PATH"Filter\\\\Painting.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_EFFECT_SHARPNESS">IMGEDT_ROOT_PATH"Filter\\\\Shappness.png"</IMAGE>
    
    //frame
    <IMAGE id="IMG_ID_IMGEDT_FRAME_VERT_L1">IMGEDT_ROOT_PATH"PhotoFrame\\\\Vertical\\\\01.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_FRAME_VERT_L2">IMGEDT_ROOT_PATH"PhotoFrame\\\\Vertical\\\\02.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_FRAME_VERT_L3">IMGEDT_ROOT_PATH"PhotoFrame\\\\Vertical\\\\03.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_FRAME_VERT_L4">IMGEDT_ROOT_PATH"PhotoFrame\\\\Vertical\\\\04.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_FRAME_VERT_L5">IMGEDT_ROOT_PATH"PhotoFrame\\\\Vertical\\\\05.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_FRAME_HORZ_L1">IMGEDT_ROOT_PATH"PhotoFrame\\\\Horizontal\\\\01.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_FRAME_HORZ_L2">IMGEDT_ROOT_PATH"PhotoFrame\\\\Horizontal\\\\02.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_FRAME_HORZ_L3">IMGEDT_ROOT_PATH"PhotoFrame\\\\Horizontal\\\\03.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_FRAME_HORZ_L4">IMGEDT_ROOT_PATH"PhotoFrame\\\\Horizontal\\\\04.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_FRAME_HORZ_L5">IMGEDT_ROOT_PATH"PhotoFrame\\\\Horizontal\\\\05.png"</IMAGE>

    //clipArt
    <IMAGE id="IMG_ID_IMGEDT_ICON_L1">IMGEDT_ROOT_PATH"Clipart\\\\01.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_ICON_L2">IMGEDT_ROOT_PATH"Clipart\\\\02.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_ICON_L3">IMGEDT_ROOT_PATH"Clipart\\\\03.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_ICON_L4">IMGEDT_ROOT_PATH"Clipart\\\\04.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_ICON_L5">IMGEDT_ROOT_PATH"Clipart\\\\05.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_ICON_L6">IMGEDT_ROOT_PATH"Clipart\\\\06.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_ICON_L7">IMGEDT_ROOT_PATH"Clipart\\\\07.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_ICON_L8">IMGEDT_ROOT_PATH"Clipart\\\\08.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_ICON_L9">IMGEDT_ROOT_PATH"Clipart\\\\09.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_ICON_L10">IMGEDT_ROOT_PATH"Clipart\\\\10.png"</IMAGE>

    //brush
    <IMAGE id="IMG_ID_IMGEDT_BRUSH_L1">IMGEDT_ROOT_PATH"Brushwork\\\\1.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_BRUSH_L2">IMGEDT_ROOT_PATH"Brushwork\\\\2.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_BRUSH_L3">IMGEDT_ROOT_PATH"Brushwork\\\\3.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_BRUSH_L4">IMGEDT_ROOT_PATH"Brushwork\\\\4.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_BRUSH_L5">IMGEDT_ROOT_PATH"Brushwork\\\\5.png"</IMAGE>

    //erase
    <IMAGE id="IMG_ID_IMGEDT_ERASE_L1">IMGEDT_ROOT_PATH"Draw\\\\A_03.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_ERASE_L2">IMGEDT_ROOT_PATH"Draw\\\\A_05.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_ERASE_L3">IMGEDT_ROOT_PATH"Draw\\\\A_07.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_ERASE_L4">IMGEDT_ROOT_PATH"Draw\\\\A_09.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_ERASE_L5">IMGEDT_ROOT_PATH"Draw\\\\A_11.png"</IMAGE>

    //text
    <IMAGE id="IMG_ID_IMGEDT_TEXT_L1">IMGEDT_ROOT_PATH"Text\\\\01.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_TEXT_L2">IMGEDT_ROOT_PATH"Text\\\\02.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_TEXT_L3">IMGEDT_ROOT_PATH"Text\\\\03.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_TEXT_L4">IMGEDT_ROOT_PATH"Text\\\\04.png"</IMAGE>

    //balloon
    <IMAGE id="IMG_ID_IMGEDT_BALLOON_LEFT">IMGEDT_ROOT_PATH"Ballon\\\\Balloon_L.9slice.png" </IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_BALLOON_CENTER">IMGEDT_ROOT_PATH"Ballon\\\\Balloon_M.9slice.png" </IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_BALLOON_RIGHT">IMGEDT_ROOT_PATH"Ballon\\\\Balloon_R.9slice.png" </IMAGE>
#endif /* __MMI_COSMOS_PHOTOEDITOR__ */
</APP>


<APP id = "VCUI_IMGCLIP" name="STR_ID_VCUI_IMGCLIP" type="venus">
#ifdef __MMI_COSMOS_IMAGECLIPPER__ 
    <MEMORY base="128 *1024"
            fg="(GDI_LCD_HEIGHT*GDI_LCD_HEIGHT*2) + (GDI_LCD_WIDTH*GDI_LCD_HEIGHT*2)"/>

    <STRING id="STR_ID_VCUI_IMGEDT_UNSUPPORTED_RESOLUTION"/>
    <STRING id="STR_ID_VCUI_IMGEDT_FS_ACCESS_DENIED_TEXT"/>
    <STRING id="STR_ID_VCUI_IMGEDT_FS_MSDC_NOT_PRESENT_TEXT"/>

#ifndef __MMI_COSMOS_PHOTOEDITOR__

    #define IMGEDT_ROOT_PATH          RES_IMG_ROOT"\\\\PhotoEditor\\\\"

    <IMAGE id="IMG_ID_IMGEDT_BALL_SMALL">IMGEDT_ROOT_PATH"CropBall01.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_BALL_LARGE">IMGEDT_ROOT_PATH"CropBall_01.png"</IMAGE>
    //<IMAGE id="IMG_ID_IMGEDT_BUTTON_HALO">RES_THEME_ROOT"\\\\Theme1\\\\Common\\\\halo.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_TITLE_BAR_VERT">IMGEDT_ROOT_PATH"TitleBar_V.9slice.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_RECT_FRAME_HL">IMGEDT_ROOT_PATH"Sideline_H.9slice.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_RECT_FRAME">IMGEDT_ROOT_PATH"Sideline.9slice.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_RECT_FRAME_HL">IMGEDT_ROOT_PATH"Sideline_H.9slice.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_BOTTOM_HL">IMGEDT_ROOT_PATH"Button_H.9slice.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_BOTTOMBAR_OK">IMGEDT_ROOT_PATH"ToolBarIcon\\\\Ok.png"</IMAGE>
    <IMAGE id="IMG_ID_IMGEDT_BOTTOMBAR_BACK">IMGEDT_ROOT_PATH"ToolBarIcon\\\\Back.png"</IMAGE>

	<THEME>
		<IMAGE id="IMG_ID_IMGEDT_BUTTON_HALO" desc="Button halo"></IMAGE>
	</THEME> 

#endif /* __MMI_COSMOS_PHOTOEDITOR__ */
#endif /* __MMI_COSMOS_IMAGECLIPPER__ */
</APP>

