#include "mmi_features.h"
#include "custresdef.h"

<?xml version="1.0" encoding="UTF-8"?>

<APP id="VAPP_KEY_MAINMENU" type="venus">
	  <INCLUDE file="GlobalResDef.h"/>
#ifdef __MMI_VUI_MAIN_MENU_SWITCH_EFFECT__
		<INCLUDE file="mmi_rp_vcp_page_menu_transition_def.h"/>
#endif
    <STRING id="STR_ID_VAPP_KMM_UNINSTALL"/>
    <STRING id="STR_ID_VAPP_KMM_UNINSTALLING"/>
    <STRING id="STR_ID_VAPP_KMM_EFFECT"/>
    
		<STRING id="STR_ID_VAPP_KMM_EFFECT_RANDOM"/>
		<STRING id="STR_ID_VAPP_KMM_LIMIT_NUM"/>
		<STRING id="STR_ID_KMM_EXIT_RUNNING_APP"/>

    
    
    #define ROOT_PATH CUST_IMG_PATH"\\\\MainLCD\\\\VUI\\\\LauncherKey\\\\MainMenu\\\\"
    <IMAGE id="IMG_ID_VAPP_KMM_EDITOR_BG">ROOT_PATH"move.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_KMM_ICON_BG">ROOT_PATH"0.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_KMM_HIGHLIGHT_ICON">ROOT_PATH"01_SELECT.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_KMM_ICON">ROOT_PATH"1.png"</IMAGE>
    
    <IMAGE id="IMG_ID_VAPP_KMM_INDICATOR_BG">ROOT_PATH"Indicator_BG.9slice.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_KMM_INDICATOR_DOT_H">ROOT_PATH"doc_big.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_KMM_INDICATOR_DOT_N">ROOT_PATH"doc_small.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_KMM_BG">ROOT_PATH"class_BG.9slice.png"</IMAGE>
    
    <IMAGE id="IMG_ID_VAPP_KMM_PREINSTALL_ICON">ROOT_PATH"App_download.png"</IMAGE>
    
     #define SOFTKEY_PATH CUST_IMG_PATH"\\\\MainLCD\\\\VUI\\\\LauncherKey\\\\HS\\\\"
     <IMAGE id="IMG_ID_VAPP_KMM_SOFTKEY_BG">SOFTKEY_PATH"hone_softkey.9slice.png"</IMAGE>
     <IMAGE id="IMG_ID_VAPP_KMM_SOFTKEY_OPTION">SOFTKEY_PATH"home_option.png"</IMAGE>
     <IMAGE id="IMG_ID_VAPP_KMM_SOFTKEY_OK">SOFTKEY_PATH"home_ok.png"</IMAGE>
     <IMAGE id="IMG_ID_VAPP_KMM_SOFTKEY_BACK">SOFTKEY_PATH"home_back.png"</IMAGE>
     
    #define POINT_PATH CUST_IMG_PATH"\\\\MainLCD\\\\VUI\\\\Launcher\\\\Mainmenu\\\\"
	  <IMAGE id="IMG_ID_VAPP_KMM_APP_COUNTER_BG">POINT_PATH"Point_BG.9slice.png"</IMAGE>
		
    #define UNINSTALL_ROOT_PATH CUST_IMG_PATH"\\\\MainLCD\\\\VUI\\\\Launcher\\\\Widget\\\\"
    <IMAGE id="IMG_ID_VAPP_KMM_APP_UNINSTALL">UNINSTALL_ROOT_PATH"Uninstall.png"</IMAGE>
    
  	#define ROOT_ICONS_PATH CUST_IMG_PATH"\\\\MainLCD\\\\VUI\\\\LauncherKey\\\\MainMenu\\\\"
		<IMAGE id="IMG_ID_VAPP_KMM_ALARM_ICON">ROOT_ICONS_PATH"Alarm.png"</IMAGE>
#if defined(__MMI_AUDIO_PLAYER__)
		<IMAGE id="IMG_ID_VAPP_KMM_APLY_ICON">ROOT_ICONS_PATH"AudioPlayer.png"</IMAGE>
#endif
#ifdef __MMI_AZAAN_ALARM__
		<IMAGE id="IMG_ID_VAPP_KMM_AALARM_ICON">ROOT_ICONS_PATH"Azaan_alarm.png"</IMAGE>
#endif
#if defined(__MMI_SEARCH_WEB_BAIDU__)
		<IMAGE id="IMG_ID_VAPP_KMM_BAIDU_ICON">ROOT_ICONS_PATH"Baidu.png"</IMAGE>
#endif
#ifdef __MMI_BT_SUPPORT__
		<IMAGE id="IMG_ID_VAPP_KMM_BT_ICON">ROOT_ICONS_PATH"BlueTooth.png"</IMAGE>
#endif
#if defined(__MMI_CALCULATOR__)
		<IMAGE id="IMG_ID_VAPP_KMM_CALCULATOR_ICON">ROOT_ICONS_PATH"Calculator.png"</IMAGE>
#endif
#if defined(__MMI_CALENDAR__)
		<IMAGE id="IMG_ID_VAPP_KMM_CALENDAR_ICON">ROOT_ICONS_PATH"Calendar.png"</IMAGE>
#endif
		<IMAGE id="IMG_ID_VAPP_KMM_CLOG_ICON">ROOT_ICONS_PATH"CallLog.png"</IMAGE>
#if defined(__MMI_CAMCORDER__)
		<IMAGE id="IMG_ID_VAPP_KMM_CAMCORDER_ICON">ROOT_ICONS_PATH"Camcorder.png"</IMAGE>
#endif
#if defined (__MMI_CAMERA__)
		<IMAGE id="IMG_ID_VAPP_KMM_CAMERA_ICON">ROOT_ICONS_PATH"Camera.png"</IMAGE>
#endif
		<IMAGE id="IMG_ID_VAPP_KMM_CONNECT_ICON">ROOT_ICONS_PATH"Connect.png"</IMAGE>
#if defined(__MMI_CURRENCY_CONVERTER__)
		<IMAGE id="IMG_ID_VAPP_KMM_CURRENCY_ICON">ROOT_ICONS_PATH"Currency.png"</IMAGE>
#endif
		<IMAGE id="IMG_ID_VAPP_KMM_DIALER_ICON">ROOT_ICONS_PATH"Call.png"</IMAGE>
#ifdef __MMI_EBOOK_READER__
		<IMAGE id="IMG_ID_VAPP_KMM_EBOOK_ICON">ROOT_ICONS_PATH"Ebook.png"</IMAGE>
#endif
		<IMAGE id="IMG_ID_VAPP_KMM_EMAIL_ICON">ROOT_ICONS_PATH"Email.png"</IMAGE>
		<IMAGE id="IMG_ID_VAPP_KMM_FMGR_ICON">ROOT_ICONS_PATH"FMGR.png"</IMAGE>
#ifdef __MMI_FM_RADIO__
		<IMAGE id="IMG_ID_VAPP_KMM_FMRDO_ICON">ROOT_ICONS_PATH"FmRadio.png"</IMAGE>
#endif
#if defined(__MMI_BMI__) || defined(__MMI_MENSTRUAL__)
		<IMAGE id="IMG_ID_VAPP_KMM_HEALTH_ICON">ROOT_ICONS_PATH"Health.png"</IMAGE>
#endif
		<IMAGE id="IMG_ID_VAPP_KMM_IVIEWER_ICON">ROOT_ICONS_PATH"ImageViewer.png"</IMAGE>
		<IMAGE id="IMG_ID_VAPP_KMM_JAVA_ICON">ROOT_ICONS_PATH"Java.png"</IMAGE>
		<IMAGE id="IMG_ID_VAPP_KMM_MPLYER_ICON">ROOT_ICONS_PATH"MediaPlayer.png"</IMAGE>
		<IMAGE id="IMG_ID_VAPP_KMM_MESSAGE_ICON">ROOT_ICONS_PATH"Message.png"</IMAGE>
#if defined(__MMI_ATV_SUPPORT__)
		<IMAGE id="IMG_ID_VAPP_KMM_MTV_ICON">ROOT_ICONS_PATH"MobileTV.png"</IMAGE>
#endif
#ifdef __MMI_NOTE_APP__
		<IMAGE id="IMG_ID_VAPP_KMM_NOTE_ICON">ROOT_ICONS_PATH"Note.png"</IMAGE>
#endif
		<IMAGE id="IMG_ID_VAPP_KMM_PHB_ICON">ROOT_ICONS_PATH"Contact.png"</IMAGE>
#ifdef __MMI_PHOTOEDITOR__
		<IMAGE id="IMG_ID_VAPP_KMM_PEDITOR_ICON">ROOT_ICONS_PATH"PhotoEditor.png"</IMAGE>
#endif
		<IMAGE id="IMG_ID_VAPP_KMM_PROFILES_ICON">ROOT_ICONS_PATH"Profile.png"</IMAGE>
#ifdef __SYNCML_SUPPORT__
		<IMAGE id="IMG_ID_VAPP_KMM_PSYNC_ICON">ROOT_ICONS_PATH"PSync.png"</IMAGE>
		<IMAGE id="IMG_ID_VAPP_KMM_SYNC_ICON">ROOT_ICONS_PATH"Sync.png"</IMAGE>
#endif
		<IMAGE id="IMG_ID_VAPP_KMM_SETTING_ICON">ROOT_ICONS_PATH"Setting.png"</IMAGE>
		<IMAGE id="IMG_ID_VAPP_KMM_SERVICE_ICON">ROOT_ICONS_PATH"SAT.png"</IMAGE>
		<IMAGE id="IMG_ID_VAPP_KMM_RECORDER_ICON">ROOT_ICONS_PATH"SoundRecorder.png"</IMAGE>
#if defined(__MMI_TODOLIST__)
		<IMAGE id="IMG_ID_VAPP_KMM_TODO_ICON">ROOT_ICONS_PATH"Tasks.png"</IMAGE>
#endif
#if defined(__MMI_UNIT_CONVERTER__)
		<IMAGE id="IMG_ID_VAPP_KMM_UCONVERTER_ICON">ROOT_ICONS_PATH"Converter.png"</IMAGE>
#endif
#if defined(__MMI_VIDEO_PLAYER__)
		<IMAGE id="IMG_ID_VAPP_KMM_VPLY_ICON">ROOT_ICONS_PATH"VideoPlayer.png"</IMAGE>
#endif
		<IMAGE id="IMG_ID_VAPP_KMM_WIFI_ICON">ROOT_ICONS_PATH"WiFi.png"</IMAGE>
#ifdef __MMI_BROWSER_2__
		<IMAGE id="IMG_ID_VAPP_KMM_BROWSER_ICON">ROOT_ICONS_PATH"Browser.png"</IMAGE>
#endif
#if defined (__MMI_WORLD_CLOCK__)
		<IMAGE id="IMG_ID_VAPP_KMM_WCLOCK_ICON">ROOT_ICONS_PATH"WorldClock.png"</IMAGE>
#endif
#ifdef __SOCIAL_NETWORK_SUPPORT__
		<IMAGE id="IMG_ID_VAPP_KMM_SNS_ICON">ROOT_ICONS_PATH"Sns.png"</IMAGE>
#endif
		<IMAGE id="IMG_ID_VAPP_KMM_VCALL_ICON">ROOT_ICONS_PATH"VideoCall.png"</IMAGE>
#if defined(__MMI_3D_GAME_INTERGRAFX__)
		<IMAGE id="IMG_ID_VAPP_KMM_3DGAME_ICON">ROOT_ICONS_PATH"3dGame.png"</IMAGE>
#endif
		<IMAGE id="IMG_ID_VAPP_KMM_OPERA_ICON">ROOT_ICONS_PATH"Opera.png"</IMAGE>
#if defined(__MMI_VIDEO_RECORDER__)
		<IMAGE id="IMG_ID_VAPP_KMM_VREC_ICON">ROOT_ICONS_PATH"VideoRecorder.png"</IMAGE>
#endif
#ifdef __MMI_PROV_MESSAGE_SUPPORT__
		<IMAGE id="IMG_ID_VAPP_KMM_SETTINGMSG_ICON">ROOT_ICONS_PATH"setting_message.png"</IMAGE>
#endif
#ifdef __MMI_MOT_SUPPORT__
		<IMAGE id="IMG_ID_VAPP_KMM_MOT_ICON">ROOT_ICONS_PATH"MOT.png"</IMAGE>
#endif
#if defined(__MMI_YOUTUBE_SHORTCUT__)
		<IMAGE id="IMG_ID_VAPP_KMM_YOUTUBE_ICON">ROOT_ICONS_PATH"youtube.png"</IMAGE>
#endif
	  <SENDER id="EVT_ID_VAPP_KMM_EMAIL_UNREAD_NOTIFY" hfile="vapp_launcher_key_mainmenu_gprot.h"/>
    <MENUITEM id="MENU_ID_VAPP_KMM_MOVE" str="STR_GLOBAL_MOVE" />
    <MENUITEM id="MENU_ID_VAPP_KMM_OPEN" str="STR_GLOBAL_OPEN" />
    <MENUITEM id="MENU_ID_VAPP_KMM_UNINSTALL" str="STR_ID_VAPP_KMM_UNINSTALL" />
// MENU  do not modify the order
#ifdef __MMI_VUI_MAIN_MENU_SWITCH_EFFECT__
		<MENUITEM id="MENU_ID_VAPP_KMM_EFFECT_RANDOM" str="STR_ID_VAPP_KMM_EFFECT_RANDOM" />
		<MENUITEM id="MENU_ID_VAPP_KMM_EFFECT_NONE" str="STR_ID_VCP_PAGE_MENU_TRANSITION_TYPE_NORMAL" />
		
		<MENUITEM id="MENU_ID_VAPP_KMM_BALL" str="STR_ID_VCP_PAGE_MENU_TRANSITION_TYPE_BALL" />
		<MENUITEM id="MENU_ID_VAPP_KMM_SPACE_BEAM" str="STR_ID_VCP_PAGE_MENU_TRANSITION_TYPE_SPACE_BEAM" />
		<MENUITEM id="MENU_ID_VAPP_KMM_JUMP_UP" str="STR_ID_VCP_PAGE_MENU_TRANSITION_TYPE_JUMP_UP" />
		<MENUITEM id="MENU_ID_VAPP_KMM_PHOTO_WAVE" str="STR_ID_VCP_PAGE_MENU_TRANSITION_TYPE_WAVE" />
		<MENUITEM id="MENU_ID_VAPP_KMM_TILT" str="STR_ID_VCP_PAGE_MENU_TRANSITION_TYPE_TILT" />
		<MENUITEM id="MENU_ID_VAPP_KMM_ROLL" str="STR_ID_VCP_PAGE_MENU_TRANSITION_TYPE_ROLL" />
		<MENUITEM id="MENU_ID_VAPP_KMM_SLIDE_DOWN" str="STR_ID_VCP_PAGE_MENU_TRANSITION_TYPE_SLIDE_DOWN" />
		<MENUITEM id="MENU_ID_VAPP_KMM_SLIDE_UP" str="STR_ID_VCP_PAGE_MENU_TRANSITION_TYPE_SLIDE_UP" />
		<MENUITEM id="MENU_ID_VAPP_KMM_EFFECT_COLLECTION_MM" str="STR_ID_VCP_PAGE_MENU_TRANSITION_TYPE_COLLECTION_MM" />
		<MENUITEM id="MENU_ID_VAPP_KMM_COLLECTION_TB" str="STR_ID_VCP_PAGE_MENU_TRANSITION_TYPE_COLLECTION_TB" />
		<MENUITEM id="MENU_ID_VAPP_KMM_CYLINDER" str="STR_ID_VCP_PAGE_MENU_TRANSITION_TYPE_CYLINDER" />
		<MENUITEM id="MENU_ID_VAPP_KMM_TORNADO" str="STR_ID_VCP_PAGE_MENU_TRANSITION_TYPE_TORNADO" />
		<MENUITEM id="MENU_ID_VAPP_KMM_CUBE" str="STR_ID_VCP_PAGE_MENU_TRANSITION_TYPE_CUBE" />

    <MENU id="MENU_ID_VAPP_KMM_EFFECT" str="STR_ID_VAPP_KMM_EFFECT" flag="RADIO"> 
    	<MENUITEM_ID>MENU_ID_VAPP_KMM_EFFECT_RANDOM</MENUITEM_ID>
    	<MENUITEM_ID>MENU_ID_VAPP_KMM_EFFECT_NONE</MENUITEM_ID>
    	<MENUITEM_ID>MENU_ID_VAPP_KMM_BALL</MENUITEM_ID>
    	<MENUITEM_ID>MENU_ID_VAPP_KMM_SPACE_BEAM</MENUITEM_ID>   
    	<MENUITEM_ID>MENU_ID_VAPP_KMM_JUMP_UP</MENUITEM_ID>
    	<MENUITEM_ID>MENU_ID_VAPP_KMM_PHOTO_WAVE</MENUITEM_ID>
    	<MENUITEM_ID>MENU_ID_VAPP_KMM_TILT</MENUITEM_ID>
    	<MENUITEM_ID>MENU_ID_VAPP_KMM_ROLL</MENUITEM_ID>  
    	<MENUITEM_ID>MENU_ID_VAPP_KMM_SLIDE_DOWN</MENUITEM_ID>
    	<MENUITEM_ID>MENU_ID_VAPP_KMM_SLIDE_UP</MENUITEM_ID>
    	<MENUITEM_ID>MENU_ID_VAPP_KMM_EFFECT_COLLECTION_MM</MENUITEM_ID>
    	<MENUITEM_ID>MENU_ID_VAPP_KMM_COLLECTION_TB</MENUITEM_ID> 
    	<MENUITEM_ID>MENU_ID_VAPP_KMM_CYLINDER</MENUITEM_ID>
    	<MENUITEM_ID>MENU_ID_VAPP_KMM_TORNADO</MENUITEM_ID>
    	<MENUITEM_ID>MENU_ID_VAPP_KMM_CUBE</MENUITEM_ID>
    </MENU>
#endif
    <MENU id="MENU_ID_VAPP_KMM_OPTION" str="STR_GLOBAL_OPTIONS"> 
    	<MENUITEM_ID>MENU_ID_VAPP_KMM_OPEN</MENUITEM_ID>
    	<MENUITEM_ID>MENU_ID_VAPP_KMM_MOVE</MENUITEM_ID>
    	<MENUITEM_ID>MENU_ID_VAPP_KMM_UNINSTALL</MENUITEM_ID>
#ifdef __MMI_VUI_MAIN_MENU_SWITCH_EFFECT__
    	<MENUITEM_ID>MENU_ID_VAPP_KMM_EFFECT</MENUITEM_ID>   
#endif
    </MENU>
    
    <SCREEN id="GRP_ID_KEY_MAINMENU_OPTION"/>
    <SCREEN id="VAPP_LAUNCHER_MM_SCRN_ID"/>
      
</APP>

