/*Needed header files of the compile option in XML files */
#include "mmi_features.h"
#include "CustResDef.h"
<?xml version = "1.0" encoding = "UTF-8"?>

<APP id="VAPP_RMGR" name="STR_ID_RMGR_VAPP">
	<INCLUDE file="GlobalResDef.h"/>
	<MEMORY base="200*1024" />
	
#define RMGR_TOOL_BAR_IMG_PATH         CUST_IMG_PATH_ROOT"\\\\MainLCD\\\\Default\\\\Components\\\\Toolbar\\\\CommonIcon\\\\"
#define RMGR_TB_IMG_PATH    	    CUST_IMG_PATH"\\\\MainLCD\\\\ToolBar\\\\" 
			<!--------------------------------------------------------------------------------------------------------------------->
         <!--String Resource Area-->
         <!--String Resource Area-->	
#ifdef __MMI_RMGR__
     <CACHEDATA type="byte" id="NVRAM_RMGR_DB_CHECK" restore_flag="TRUE">
     <DEFAULT_VALUE> [0x00] </DEFAULT_VALUE>
     <DESCRIPTION> Byte Cache </DESCRIPTION>
     </CACHEDATA>
    <STRING id="STR_ID_RMGR_DETAIL_END_COSMOS"/>
    <STRING id="STR_ID_RMGR_DETAIL_START_COSMOS"/>
    <STRING id="STR_ID_RMGR_NAME"/>
	<STRING id="STR_ID_RMGR_DEL_ALL_EXP"/>
	<STRING id="STR_ID_RMGR_DEL_VALID_LIC"/>
	<STRING id="STR_ID_RMGR_VALID"/>
	<STRING id="STR_ID_RMGR_EXPIRED"/>
	<STRING id="STR_ID_RMGR_ADVANCED"/>
    <STRING id="STR_ID_RMGR_LIC_DETAILS"/>
	<STRING id="STR_ID_DELETE_EXPIRED"/>
	<STRING id="STR_ID_RMGR_CANCELLED"/>
	<STRING id="STR_ID_RMGR_SPACE_LOW"/>
	<STRING id="STR_ID_RMGR_DL_LICENSE"/>
    <STRING id="STR_ID_RMGR_EXP_LIC"/>
	<STRING id="STR_ID_RMGR_LOCKED_BY_APP"/>
	 <STRING id="STR_ID_RMGR"/>
        <STRING id="STR_ID_RMGR_VAPP"/>
		<STRING id="STR_ID_RMGR_NO_LIC"/>
	<STRING id="STR_ID_RMGR_LIST_RO"/>
	<STRING id="STR_ID_RMGR_INFO"/>
	<STRING id="STR_ID_RMGR_DB_PROC"/>
	<STRING id="STR_ID_RMGR_SWEEP"/>
	#ifdef __DRM_V02__
	<STRING id="STR_ID_RMGR_WHITE_LIST"/>
	<STRING id="STR_ID_RMGR_TRANS"/>
	<STRING id="STR_ID_RMGR_BACKUP"/>
	<STRING id="STR_ID_RMGR_RESTORE"/>
	<STRING id="STR_ID_RMGR_CERMGR"/>
	#endif /* __DRM_V02__ */
	<STRING id="STR_ID_RMGR_SCAN_DISK"/>
	<STRING id="STR_ID_RMGR_SCANNING"/>
	<STRING id="STR_ID_RMGR_SWEEP_REMOVE_RIGHTS"/>
	<STRING id="STR_ID_RMGR_BACKUP_AND_REBOOT"/>
	<STRING id="STR_ID_RMGR_RESTORE_AND_REBOOT"/>
	#ifdef __DRM_V02__
	<STRING id="STR_ID_RMGR_WHITE_LIST_EDIT_ENTER_ADDRESS"/>
	<STRING id="STR_ID_RMGR_WHITE_LIST_EMPTY"/>
	<STRING id="STR_ID_RMGR_WHITE_LIST_DUPLICATE"/>
	#endif /* __DRM_V02__ */
	<STRING id="STR_ID_RMGR_DELETE_QUERY"/>
	<STRING id="STR_ID_RMGR_DELETE_ALL_QUERY"/>
	<STRING id="STR_ID_RMGR_SPACE_CHECK"/>
	<STRING id="STR_ID_RMGR_SPACE_PROMPT"/>
	<TIMER id="BOOTUP_POPUP_TIMER"/>
	<TIMER id="RMGR_SCAN_DISK_TIMER"/>

#endif /* __MMI_RMGR__ */

#ifdef __DRM_SUPPORT__
	#if __DRM_V02__
	<STRING id="STR_ID_DRM_REGISTRATION_SUCCESS"/>
	<STRING id="STR_ID_DRM_RO_ACQUISITION_SUCCESS"/>
	<STRING id="STR_ID_DRM_DOMAIN_JOIN_SUCCESS"/>
	<STRING id="STR_ID_DRM_DOMAIN_LEAVE_SUCCESS"/>
	<STRING id="STR_ID_DRM_REG_FAILED"/>
	<STRING id="STR_ID_DRM_NOT_IN_DOMAIN"/>
	<STRING id="STR_ID_DRM_DOMAIN_JOIN_FAILED"/>
	<STRING id="STR_ID_DRM_DOMAIN_LEAVE_FAILED"/>
	<STRING id="STR_ID_DRM_ROAP_UNKNOWN_ERROR"/>
	<STRING id="STR_ID_DRM_ERROR_CODE"/>
	<STRING id="STR_ID_DRM_NOT_REGISTERED"/>
	<STRING id="STR_ID_DRM_RIGHTS_ISSUER"/>
	<STRING id="STR_ID_DRM_ALLOW_REGISTER"/>
	<STRING id="STR_ID_DRM_ALLOW_JOIN"/>
	<STRING id="STR_ID_DRM_ALLOW_DOMAIN_LEAVE"/>
	<STRING id="STR_ID_DRM_DOMAIN"/>
	<STRING id="STR_ID_DRM_UNKNOWN"/>
	<STRING id="STR_ID_DRM_GOTO_RI_DOMAIN"/>
	<STRING id="STR_ID_DRM_ALLOW_PREVIEW_DOWNLOAD"/>
	<STRING id="STR_ID_DRM_ALLOW_SILENT_DOWNLOAD"/>
	<STRING id="STR_ID_DRM_BECAME_PLAYABLE"/>
	<STRING id="STR_ID_DRM_NOTE_FUTURERIGHTS"/>
	<STRING id="STR_ID_DRM_NOTE_VALIDRIGHTS"/>
	<STRING id="STR_ID_DRM_SERVER_ERRORMESSAGE"/>
	<STRING id="STR_ID_DRM_ERROR_REDIRECT_URL"/>
	<STRING id="STR_ID_DRM_BROWSE_REGISTER"/>
	<STRING id="STR_ID_DRM_ALLOW_TIMESYNC"/>
	<STRING id="STR_ID_DRM_IS_DEVICETIME_CORRECT"/>
	<STRING id="STR_ID_DRM_TIMEBASED_NOT_PLAYABLE"/>
	<STRING id="STR_ID_DRM_START_REGISTER_AGENT"/>
	<STRING id="STR_ID_DRM_START_ACQUIRE_RO"/>
	<STRING id="STR_ID_DRM_START_DOMAIN_JOIN"/>
	<STRING id="STR_ID_DRM_START_DOMAIN_LEAVE"/>
	<STRING id="STR_ID_DRM_START_PREVIEW_DOWNLOAD"/>
	<STRING id="STR_ID_DRM_START_SILENT_DOWNLOAD"/>
	<STRING id="STR_ID_DRM_START_TIME_SYNC"/>
	<STRING id="STR_ID_DRM_REGISTER"/>
	<STRING id="STR_ID_DRM_ACQUIRE"/>
	<STRING id="STR_ID_DRM_JOIN"/>
	<STRING id="STR_ID_DRM_LEAVE"/>
	#endif /* __DRM_V02__ */
	
	#if __DRM_V02__
	<STRING id="STR_ID_DRM_KEY_NOT_FOUND"/>
	<STRING id="STR_ID_DRM_CERT_NOT_FOUND"/>
	<STRING id="STR_ID_DRM_CERT_ROOT_NOT_FOUND"/>
	<STRING id="STR_ID_DRM_CERT_EXPIRED"/>
	<STRING id="STR_ID_DRM_INVALID_CERT"/>
	<STRING id="STR_ID_DRM_DOMAIN_EXPIRED"/>
	<STRING id="STR_ID_DRM_NEED_DOMAIN_UPGD"/>
	<STRING id="STR_ID_DRM_INVALID_DRMTIME"/>
	<STRING id="STR_ID_DRM_NETWORK_ERROR"/>
	<STRING id="STR_ID_DRM_DATABASE_ERROR"/>
	<STRING id="STR_ID_DRM_TIME_UNTRUSTED"/>
	<STRING id="STR_ID_DRM_NOT_FOUND"/>
	<STRING id="STR_ID_DRM_NO_MEMORY"/>
	<STRING id="STR_ID_DRM_NOT_ARCHIVE"/>
	#endif
	
	<STRING id="STR_ID_DRM_INVALID_KEY"/>
	<STRING id="STR_ID_DRM_EOF"/>
	<STRING id="STR_ID_DRM_TRUNCATED"/>
	<STRING id="STR_ID_DRM_PROCESS_ERROR"/>
	<STRING id="STR_ID_DRM_DB_LOCKED_BY_APP"/>
	<STRING id="STR_ID_DRM_NO_RIGHT_SPACE"/>
	<STRING id="STR_ID_VAPP_DRM_PLAY"/>
	<STRING id="STR_ID_VAPP_DRM_DISPLAY"/>
	<STRING id="STR_ID_VAPP_DRM_EXECUTE"/>
	<STRING id="STR_ID_VAPP_DRM_PRINT"/>
	
	#if __DRM_V02__
	<STRING id="STR_ID_DRM_EXPORT"/>
	#endif /* __DRM_V02__ */
	
	<STRING id="STR_ID_RMGR_DETAIL_RIGHT"/>
	<STRING id="STR_ID_RMGR_DETAIL_PROTECTED"/>
	<STRING id="STR_ID_RMGR_DETAIL_UNPROTECTED"/>
	<STRING id="STR_ID_RMGR_DETAIL_UNLIMITED"/>
	<STRING id="STR_ID_RMGR_DETAIL_COUNT_COSMOS"/>
	<STRING id="STR_ID_RMGR_DETAIL_START"/>
	<STRING id="STR_ID_RMGR_DETAIL_END"/>
	<STRING id="STR_ID_RMGR_SUMMARY"/>
	<STRING id="STR_ID_DRM_INVALID_RO"/>
	
	#ifdef __MMI_RMGR_SIMPLE_DETAILS__
	<STRING id="STR_ID_RMGR_DETAIL_LEFT_COUNT"/>
	<STRING id="STR_ID_RMGR_DETAIL_LEFT_TIME"/>
	<STRING id="STR_ID_RMGR_DETAIL_LEFT_DAYS"/>
	<STRING id="STR_ID_RMGR_DETAIL_LEFT_HOURS"/>
	<STRING id="STR_ID_RMGR_DETAIL_LEFT_LAST"/>
	<STRING id="STR_ID_RMGR_DETAIL_INSTALLABLE"/>
	<STRING id="STR_ID_RMGR_DETAIL_UNINSTALLABLE"/>
	<STRING id="STR_ID_RMGR_DETAIL_FORWARDABLE"/>
	<STRING id="STR_ID_RMGR_DETAIL_UNFORWARDABLE"/>
	<STRING id="STR_ID_RMGR_DETAIL_PRINTABLE"/>
	#endif
	
	#if __DRM_V02__
	<STRING id="STR_ID_RMGR_DETAIL_ACCUMULATED"/>
	<STRING id="STR_ID_RMGR_DETAIL_TIMEDCOUNT"/>
	<STRING id="STR_ID_RMGR_DETAIL_TIMEDCOUNT_TIME"/>
	<STRING id="STR_ID_RMGR_DETAIL_SEC"/>
	<STRING id="STR_ID_RMGR_MULTI_PART"/>
	<STRING id="STR_ID_RMGR_SHARED_RO"/>
	<STRING id="STR_ID_RMGR_STATUS"/>
	#endif
	
	<STRING id="STR_ID_RMGR_VERSION"/>
	<STRING id="STR_ID_RMGR_TIME"/>
	<STRING id="STR_ID_RMGR_REQ_RIGHTS"/>
	<STRING id="STR_ID_RMGR_REQ_RITS"/>
	<STRING id="STR_ID_RMGR_MORE_RITS"/>
	<STRING id="STR_ID_RMGR_MORE_RITS_QUERY"/>
	<STRING id="STR_ID_RMGR_REQ_RITS_EXPIRE_DETAIL"/>
	<STRING id="STR_ID_RMGR_REQ_RITS_EXTEND_DETAIL"/>
	<STRING id="STR_ID_RMGR_USE_NOW"/>
	<STRING id="STR_ID_RMGR_RO_RECEIVED"/>
	<STRING id="STR_ID_RMGR_ACTIVATE_COMPLETED"/>
	<STRING id="STR_ID_RMGR_PROCESSING"/>
	<STRING id="STR_ID_RMGR_COLON"/>

#endif /* __DRM_SUPPORT__ */

#ifdef __MMI_RMGR__

	<IMAGE id = "IMG_ID_VAPP_RMGR_DELETE">             RMGR_TOOL_BAR_IMG_PATH"Delete.png"             </IMAGE>
	<IMAGE id = "IMG_ID_VAPP_RMGR_DETAIL">             RMGR_TB_IMG_PATH"TB_delete.png"             </IMAGE>
	<IMAGE id="IMG_ID_RMGR_ICON">CUST_IMG_PATH"\\\\MainLCD\\\\RightsManager\\\\RM_DRMManger.pbm"</IMAGE>
	<IMAGE id="IMG_ID_RMGR_LOCK">CUST_IMG_PATH"\\\\MainLCD\\\\RightsManager\\\\RM_DRMlock.pbm"</IMAGE>
	<IMAGE id="IMG_ID_RMGR_UNLOCK">CUST_IMG_PATH"\\\\MainLCD\\\\RightsManager\\\\RM_DRMunlock.pbm"</IMAGE>

	 			<!--End Image Resource Area-->
        <!--End Image Resource Area-->
        <!--------------------------------------------------------------------------------------------------------------------->

<RECEIVER id="EVT_ID_SRV_RMGR_DL_NOTIFY" proc="vapp_rmgr_show_process_info"/>	

#endif /* __MMI_RMGR__ */

</APP>

