/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 *    ImeGprotEnums.h
 *
 * Project:
 * --------
 *   Maui_Software
 *
 * Description:
 * ------------
 *
 * Author:
 * -------
 * -------
 *
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/

#ifndef __IMEGROTENUMS_H__
#define __IMEGROTENUMS_H__

/* The flag passed from application to category is U32, out of which
 * editor takes the higher 8bit and pass the lower 24 bits to IME.
 * The IME 24 bits can be accesed by using the Mask flag  INPUT_TYPE_MASK
 * which is defined as 
 * #define INPUT_TYPE_MASK  0x00ffffff 
 *---------------------------------------------------------------------------------------
 * The 24 bits of IME are internally divided two parts
 * 1. 0-19 bit are used for generic cases (Currently 18 bits out of thsi are being used)
 * 2. 20-24 bit are used for external input types for special scenarios
 *---------------------------------------------------------------------------------------
 * 0 t0 19 th bit is defined in following enum, out of which
 * currently all 19 bits are being used. 
 
 */
typedef enum
{
    IMM_INPUT_TYPE_NONE = 0,
    IMM_INPUT_TYPE_NUMERIC = 0x1,  /*For Number only */
    IMM_INPUT_TYPE_PHONE_NUMBER = (0x1 << 1),  /* For Phone Number */
    IMM_INPUT_TYPE_DECIMAL_NUMERIC = (0x1 << 2), /*For  Number with Decimal */
    IMM_INPUT_TYPE_SIGNED_NUMERIC = (0x1 << 3), /* For Signed Numbers */
    IMM_INPUT_TYPE_SIGNED_DECIMAL_NUMERIC = (0x1 << 4),/* For Signed Numbers with Decimal */
    IMM_INPUT_TYPE_URL = (0x1 << 5), /* For url input */
    IMM_INPUT_TYPE_QUICK_SEARCH = (0x1 << 6), /* For quick search */
    IMM_INPUT_TYPE_SENTENCE = (0x1 << 7), /* all kind of character are allowed  */
    IMM_INPUT_TYPE_ENGLISH_SENTENCE = (0x1 << 8), /* only English character are allowed. */
    IMM_INPUT_TYPE_USER_SPECIFIC = (0x1 << 9), /* App defines the input method iit wants */
    IMM_INPUT_TYPE_KEYPAD_NUMERIC = (0x1 << 10), /* For all numbers mapped on keyboard 0-9 * and # */ 
    IMM_INPUT_TYPE_SIM_NUMERIC = (0x1 << 11), /* for numeric input with + and * */
    IMM_INPUT_TYPE_ENGLISH_SENTENCE_UPPERCASE = (0x1 << 12) , /* English  with Uppercase */
    IMM_INPUT_TYPE_ENGLISH_SENTENCE_LOWERCASE = (0x1 << 13) , /* English  with Lowercase */
    IMM_INPUT_TYPE_EMAIL = (0x01 << 14), /* For Email Input */
    IMM_INPUT_TYPE_PHONE_NUMBER_WILDCHAR = (0x01 << 15), /* For Phone number with + , p , w and ? */
    IMM_INPUT_TYPE_NUMERIC_SYMBOL = (0x01 << 16), /* For number input with symbold allowed */
    IMM_INPUT_TYPE_ASCII_CHAR = (0x01 << 17), /* ALL ASCII Characters  */
    IMM_INPUT_TYPE_NO_TITLECASE_SENTENCE = (0x01 << 18) /* All characters , but no titlecase */
} mmi_imm_input_type_enum;

/* The IME internal bits from 20th - 24th can be accesed by using the MASK IMM_INPUT_TYPE_MASK
 * whihc is defined below
 */
#define    IMM_INPUT_TYPE_MASK                              0xf80000 

/* The 20th - 24th bit are all being used below
 */	 
#define    IMM_INPUT_TYPE_EXT_PASSWORD                    	0x800000 /* 24th bit */
#define    IMM_INPUT_TYPE_OVERRIDE_DEFAULT              	0x400000 /* 23th bit */
#define    IMM_INPUT_TYPE_EXT_MULTITAP                      0x200000 /* 22th bit */
#define    IMM_INPUT_TYPE_ADD_NEW_WORD                      0x100000 /* 21th bit */
#define    IMM_INPUT_TYPE_EXT_ENGLISH_UPPERCASE             0x080000 /* 20th bit */

/* For special cases like the VK for Dialer search, we will use the 8 bits of the editor
 * THIS TYES CANT BE USED BY THE APPLICATION AND ONLY THE CATEGORY WILL PASS THIS FLAG TO THE 
 * IME as the 1st parameter to the API mmi_imm_set_required_mode_list() 
 *----------------------------------------------------------------------------------------------
 * FOLLOWING FLAGS ARE TO BEUSED BY CATEGORY ONLY
 */
/* Mask for higher 8 bits of editor being used by category for providing information to IME */
#define		IMM_INPUT_TYPE_SPECIAL_EXT_MASK								0xff000000 
#define    	IMM_INPUT_TYPE_SPECIAL_EXT_SHOW_DIALER_VK             		0x01000000 /* 25th bit */
/* For future use */
//#define		IMM_INPUT_TYPE_SPECIAL_EXT_FLAG_2             		0x02000000 /* 26th bit */
//#define		IMM_INPUT_TYPE_SPECIAL_EXT_FLAG_3             		0x04000000 /* 27th bit */
//#define		IMM_INPUT_TYPE_SPECIAL_EXT_FLAG_4             		0x08000000 /* 28th bit */
//#define		IMM_INPUT_TYPE_SPECIAL_EXT_FLAG_5             		0x10000000 /* 29th bit */
//#define		IMM_INPUT_TYPE_SPECIAL_EXT_FLAG_6             		0x20000000 /* 30th bit */
//#define		IMM_INPUT_TYPE_SPECIAL_EXT_FLAG_7             		0x40000000 /* 31st bit */
//#define		IMM_INPUT_TYPE_SPECIAL_EXT_FLAG_8             		0x80000000 /* 32nd bit */


#define    IMM_INPUT_TYPE_SAT_NUMERIC_PASSWORD      (IMM_INPUT_TYPE_KEYPAD_NUMERIC |IMM_INPUT_TYPE_EXT_PASSWORD)
#define    IMM_INPUT_TYPE_DECIMAL_NUMERIC_PASSWORD  (IMM_INPUT_TYPE_DECIMAL_NUMERIC | IMM_INPUT_TYPE_EXT_PASSWORD)
#define    IMM_INPUT_TYPE_SIGNED_NUMERIC_PASSWORD   (IMM_INPUT_TYPE_SIGNED_NUMERIC | IMM_INPUT_TYPE_EXT_PASSWORD)
#define    IMM_INPUT_TYPE_SIGNED_DECIMAL_NUMERIC_PASSWORD (IMM_INPUT_TYPE_SIGNED_DECIMAL_NUMERIC | IMM_INPUT_TYPE_EXT_PASSWORD)
#define    IMM_INPUT_TYPE_NUMERIC_PASSWORD                (IMM_INPUT_TYPE_NUMERIC | IMM_INPUT_TYPE_EXT_PASSWORD)
#define    IMM_INPUT_TYPE_ALPHANUMERIC_PASSWORD       (IMM_INPUT_TYPE_ENGLISH_SENTENCE | IMM_INPUT_TYPE_NUMERIC_SYMBOL | IMM_INPUT_TYPE_EXT_PASSWORD)
#define    IMM_INPUT_TYPE_ASCII_PASSWORD              (IMM_INPUT_TYPE_ASCII_CHAR | IMM_INPUT_TYPE_EXT_PASSWORD)
#define    IMM_INPUT_TYPE_MULTITAP_SENTENCE             (IMM_INPUT_TYPE_EXT_MULTITAP | IMM_INPUT_TYPE_SENTENCE)

#define MMI_IMM_MAX_INPUT_METHOD_NUM  100


typedef enum
{
IMM_INPUT_MODE_NONE = 0,
IMM_INPUT_MODE_123,
IMM_INPUT_MODE_123_SYMBOLS,
/* English */
IMM_INPUT_MODE_MULTITAP_UPPERCASE_ABC,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_ABC,
IMM_INPUT_MODE_MULTITAP_UPPERCASE_ABC_NO_NUMERIC,
IMM_INPUT_MODE_MULTITAP_LOWERCASE_ABC_NO_NUMERIC,
// DOM-NOT_FOR_SDK-BEGIN
/* The above 6 input modes are used by Q03C WCSS editor, and the
 * editor requires the input modes values are smaller than 0x1F,
 * so we should make sure the input modes used in UI_check_WCSS_normal_character() 
 * of gui_inputs.c are smaller than 0x1F
 */
// DOM-NOT_FOR_SDK-END
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_ABC, 
IMM_INPUT_MODE_SMART_LOWERCASE_ABC, 
IMM_INPUT_MODE_SMART_UPPERCASE_ABC, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_ABC,

IMM_INPUT_MODE_ARABIC_NUMERIC,
IMM_INPUT_MODE_FLOAT_123,
IMM_INPUT_MODE_HK_STROKE,    
IMM_INPUT_MODE_KEYPAD_NUMERIC,
IMM_INPUT_MODE_MAGIC_NUMBER,
IMM_INPUT_MODE_PHONE_NUMBER,
IMM_INPUT_MODE_PHONE_NUMBER_WILDCHAR,
IMM_INPUT_MODE_SIGNED_123,
IMM_INPUT_MODE_SIGNED_FLOAT_123,
IMM_INPUT_MODE_SIM_NUMERIC,

/*Afrikaans*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_AFRIKAANS,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_AFRIKAANS,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_AFRIKAANS, 
IMM_INPUT_MODE_SMART_LOWERCASE_AFRIKAANS, 
IMM_INPUT_MODE_SMART_UPPERCASE_AFRIKAANS, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_AFRIKAANS,
/*Albanian*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_ALBANIAN,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_ALBANIAN,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_ALBANIAN, 
IMM_INPUT_MODE_SMART_LOWERCASE_ALBANIAN, 
IMM_INPUT_MODE_SMART_UPPERCASE_ALBANIAN, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_ALBANIAN,
/*Armenian*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_ARMENIAN,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_ARMENIAN,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_ARMENIAN, 
IMM_INPUT_MODE_SMART_LOWERCASE_ARMENIAN, 
IMM_INPUT_MODE_SMART_UPPERCASE_ARMENIAN, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_ARMENIAN,
/*Arabic*/
IMM_INPUT_MODE_MULTITAP_ARABIC,    
IMM_INPUT_MODE_SMART_ARABIC,
/*Assamese*/
IMM_INPUT_MODE_MULTITAP_ASSAMESE,    
IMM_INPUT_MODE_SMART_ASSAMESE,
/*Azerbaijani*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_AZERBAIJANI,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_AZERBAIJANI,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_AZERBAIJANI, 
IMM_INPUT_MODE_SMART_LOWERCASE_AZERBAIJANI, 
IMM_INPUT_MODE_SMART_UPPERCASE_AZERBAIJANI, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_AZERBAIJANI,
/*Basque*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_BASQUE,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_BASQUE,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_BASQUE, 
IMM_INPUT_MODE_SMART_LOWERCASE_BASQUE, 
IMM_INPUT_MODE_SMART_UPPERCASE_BASQUE, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_BASQUE,
/*Bengali*/
IMM_INPUT_MODE_MULTITAP_BENGALI,    
IMM_INPUT_MODE_SMART_BENGALI,
/*Bulgarian*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_BULGARIAN,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_BULGARIAN,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_BULGARIAN, 
IMM_INPUT_MODE_SMART_LOWERCASE_BULGARIAN, 
IMM_INPUT_MODE_SMART_UPPERCASE_BULGARIAN, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_BULGARIAN,
/*Catalan*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_CATALAN,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_CATALAN,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_CATALAN, 
IMM_INPUT_MODE_SMART_LOWERCASE_CATALAN, 
IMM_INPUT_MODE_SMART_UPPERCASE_CATALAN, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_CATALAN,
/*Croatian*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_CROATIAN,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_CROATIAN,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_CROATIAN, 
IMM_INPUT_MODE_SMART_LOWERCASE_CROATIAN, 
IMM_INPUT_MODE_SMART_UPPERCASE_CROATIAN, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_CROATIAN,
/*Czech*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_CZECH,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_CZECH,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_CZECH, 
IMM_INPUT_MODE_SMART_LOWERCASE_CZECH, 
IMM_INPUT_MODE_SMART_UPPERCASE_CZECH, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_CZECH,
/*Danish*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_DANISH,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_DANISH,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_DANISH, 
IMM_INPUT_MODE_SMART_LOWERCASE_DANISH, 
IMM_INPUT_MODE_SMART_UPPERCASE_DANISH, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_DANISH,
/*Dutch*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_DUTCH,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_DUTCH,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_DUTCH, 
IMM_INPUT_MODE_SMART_LOWERCASE_DUTCH, 
IMM_INPUT_MODE_SMART_UPPERCASE_DUTCH, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_DUTCH,
/*Estonian*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_ESTONIAN,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_ESTONIAN,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_ESTONIAN, 
IMM_INPUT_MODE_SMART_LOWERCASE_ESTONIAN, 
IMM_INPUT_MODE_SMART_UPPERCASE_ESTONIAN, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_ESTONIAN,
/*Filipino*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_FILIPINO,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_FILIPINO,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_FILIPINO, 
IMM_INPUT_MODE_SMART_LOWERCASE_FILIPINO, 
IMM_INPUT_MODE_SMART_UPPERCASE_FILIPINO, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_FILIPINO,
/*Finnish*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_FINNISH,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_FINNISH,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_FINNISH, 
IMM_INPUT_MODE_SMART_LOWERCASE_FINNISH, 
IMM_INPUT_MODE_SMART_UPPERCASE_FINNISH, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_FINNISH,
/*French*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_FRENCH,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_FRENCH,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_FRENCH, 
IMM_INPUT_MODE_SMART_LOWERCASE_FRENCH, 
IMM_INPUT_MODE_SMART_UPPERCASE_FRENCH, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_FRENCH,
/*Galician*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_GALICIAN,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_GALICIAN,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_GALICIAN, 
IMM_INPUT_MODE_SMART_LOWERCASE_GALICIAN, 
IMM_INPUT_MODE_SMART_UPPERCASE_GALICIAN, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_GALICIAN,
/*Georgian*/
IMM_INPUT_MODE_MULTITAP_GEORGIAN,    
IMM_INPUT_MODE_SMART_GEORGIAN,
/*German*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_GERMAN,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_GERMAN,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_GERMAN, 
IMM_INPUT_MODE_SMART_LOWERCASE_GERMAN, 
IMM_INPUT_MODE_SMART_UPPERCASE_GERMAN, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_GERMAN,
/*Greek*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_GREEK,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_GREEK,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_GREEK, 
IMM_INPUT_MODE_SMART_LOWERCASE_GREEK, 
IMM_INPUT_MODE_SMART_UPPERCASE_GREEK, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_GREEK,
/*Gujarati*/
IMM_INPUT_MODE_MULTITAP_GUJARATI,    
IMM_INPUT_MODE_SMART_GUJARATI,
/*Hausa*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_HAUSA,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_HAUSA,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_HAUSA, 
IMM_INPUT_MODE_SMART_LOWERCASE_HAUSA, 
IMM_INPUT_MODE_SMART_UPPERCASE_HAUSA, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_HAUSA,
/*Hebrew*/
IMM_INPUT_MODE_MULTITAP_HEBREW,    
IMM_INPUT_MODE_SMART_HEBREW,
/*Hindi*/
IMM_INPUT_MODE_MULTITAP_HINDI,    
IMM_INPUT_MODE_SMART_HINDI,
/*Hungarian*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_HUNGARIAN,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_HUNGARIAN,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_HUNGARIAN, 
IMM_INPUT_MODE_SMART_LOWERCASE_HUNGARIAN, 
IMM_INPUT_MODE_SMART_UPPERCASE_HUNGARIAN, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_HUNGARIAN,
/*Icelandic*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_ICELANDIC,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_ICELANDIC,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_ICELANDIC, 
IMM_INPUT_MODE_SMART_LOWERCASE_ICELANDIC, 
IMM_INPUT_MODE_SMART_UPPERCASE_ICELANDIC, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_ICELANDIC,
/*Igbo*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_IGBO,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_IGBO,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_IGBO, 
IMM_INPUT_MODE_SMART_LOWERCASE_IGBO, 
IMM_INPUT_MODE_SMART_UPPERCASE_IGBO, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_IGBO,
/*Indonesian*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_INDONESIAN,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_INDONESIAN,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_INDONESIAN, 
IMM_INPUT_MODE_SMART_LOWERCASE_INDONESIAN, 
IMM_INPUT_MODE_SMART_UPPERCASE_INDONESIAN, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_INDONESIAN,
/*Irish*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_IRISH,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_IRISH,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_IRISH, 
IMM_INPUT_MODE_SMART_LOWERCASE_IRISH, 
IMM_INPUT_MODE_SMART_UPPERCASE_IRISH, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_IRISH,
/*Italian*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_ITALIAN,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_ITALIAN,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_ITALIAN, 
IMM_INPUT_MODE_SMART_LOWERCASE_ITALIAN, 
IMM_INPUT_MODE_SMART_UPPERCASE_ITALIAN, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_ITALIAN,
/*Kannada*/
IMM_INPUT_MODE_MULTITAP_KANNADA,    
IMM_INPUT_MODE_SMART_KANNADA,
/*Kazakh*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_KAZAKH,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_KAZAKH,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_KAZAKH, 
IMM_INPUT_MODE_SMART_LOWERCASE_KAZAKH, 
IMM_INPUT_MODE_SMART_UPPERCASE_KAZAKH, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_KAZAKH,
IMM_INPUT_MODE_MULTITAP_KOREAN,
/*Latvian*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_LATVIAN,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_LATVIAN,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_LATVIAN, 
IMM_INPUT_MODE_SMART_LOWERCASE_LATVIAN, 
IMM_INPUT_MODE_SMART_UPPERCASE_LATVIAN, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_LATVIAN,
/*Lithuanian*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_LITHUANIAN,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_LITHUANIAN,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_LITHUANIAN, 
IMM_INPUT_MODE_SMART_LOWERCASE_LITHUANIAN, 
IMM_INPUT_MODE_SMART_UPPERCASE_LITHUANIAN, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_LITHUANIAN,
/*Macedonian*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_MACEDONIAN,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_MACEDONIAN,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_MACEDONIAN, 
IMM_INPUT_MODE_SMART_LOWERCASE_MACEDONIAN, 
IMM_INPUT_MODE_SMART_UPPERCASE_MACEDONIAN, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_MACEDONIAN,
/*Malay*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_MALAY,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_MALAY,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_MALAY, 
IMM_INPUT_MODE_SMART_LOWERCASE_MALAY, 
IMM_INPUT_MODE_SMART_UPPERCASE_MALAY, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_MALAY,
/*Malayalam*/
IMM_INPUT_MODE_MULTITAP_MALAYALAM,    
IMM_INPUT_MODE_MULTITAP_LAO,
IMM_INPUT_MODE_SMART_LAO,
IMM_INPUT_MODE_MULTITAP_KHMER,
IMM_INPUT_MODE_SMART_KHMER,
IMM_INPUT_MODE_MULTITAP_MYANMAR,
IMM_INPUT_MODE_SMART_MYANMAR,

IMM_INPUT_MODE_SMART_MALAYALAM,
/*Marathi*/
IMM_INPUT_MODE_MULTITAP_MARATHI,    
IMM_INPUT_MODE_SMART_MARATHI,
/*Moldovan*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_MOLDOVAN,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_MOLDOVAN,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_MOLDOVAN, 
IMM_INPUT_MODE_SMART_LOWERCASE_MOLDOVAN, 
IMM_INPUT_MODE_SMART_UPPERCASE_MOLDOVAN, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_MOLDOVAN,
/*Norwegian*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_NORWEGIAN,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_NORWEGIAN,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_NORWEGIAN, 
IMM_INPUT_MODE_SMART_LOWERCASE_NORWEGIAN, 
IMM_INPUT_MODE_SMART_UPPERCASE_NORWEGIAN,
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_NORWEGIAN,
/*Oriya*/
IMM_INPUT_MODE_MULTITAP_ORIYA,    
IMM_INPUT_MODE_SMART_ORIYA,
/*Persian*/ 
IMM_INPUT_MODE_MULTITAP_PERSIAN,    
IMM_INPUT_MODE_SMART_PERSIAN,
/*Polish*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_POLISH,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_POLISH,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_POLISH, 
IMM_INPUT_MODE_SMART_LOWERCASE_POLISH, 
IMM_INPUT_MODE_SMART_UPPERCASE_POLISH, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_POLISH,
/*Portuguese*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_PORTUGUESE,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_PORTUGUESE,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_PORTUGUESE, 
IMM_INPUT_MODE_SMART_LOWERCASE_PORTUGUESE, 
IMM_INPUT_MODE_SMART_UPPERCASE_PORTUGUESE, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_PORTUGUESE,
/*Punjabi*/
IMM_INPUT_MODE_MULTITAP_PUNJABI,    
IMM_INPUT_MODE_SMART_PUNJABI,
/*Romanian*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_ROMANIAN,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_ROMANIAN,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_ROMANIAN, 
IMM_INPUT_MODE_SMART_LOWERCASE_ROMANIAN, 
IMM_INPUT_MODE_SMART_UPPERCASE_ROMANIAN, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_ROMANIAN,
/*Russian*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_RUSSIAN,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_RUSSIAN,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_RUSSIAN, 
IMM_INPUT_MODE_SMART_LOWERCASE_RUSSIAN, 
IMM_INPUT_MODE_SMART_UPPERCASE_RUSSIAN, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_RUSSIAN,
/*Serbian*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_SERBIAN,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_SERBIAN,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_SERBIAN, 
IMM_INPUT_MODE_SMART_LOWERCASE_SERBIAN, 
IMM_INPUT_MODE_SMART_UPPERCASE_SERBIAN, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_SERBIAN,
/*Sesotho*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_SESOTHO,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_SESOTHO,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_SESOTHO, 
IMM_INPUT_MODE_SMART_LOWERCASE_SESOTHO, 
IMM_INPUT_MODE_SMART_UPPERCASE_SESOTHO, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_SESOTHO,
/*Slovak*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_SLOVAK,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_SLOVAK,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_SLOVAK, 
IMM_INPUT_MODE_SMART_LOWERCASE_SLOVAK, 
IMM_INPUT_MODE_SMART_UPPERCASE_SLOVAK, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_SLOVAK,
/*Slovenian*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_SLOVENIAN,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_SLOVENIAN,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_SLOVENIAN, 
IMM_INPUT_MODE_SMART_LOWERCASE_SLOVENIAN, 
IMM_INPUT_MODE_SMART_UPPERCASE_SLOVENIAN, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_SLOVENIAN,
/*Spanish*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_SPANISH,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_SPANISH,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_SPANISH, 
IMM_INPUT_MODE_SMART_LOWERCASE_SPANISH, 
IMM_INPUT_MODE_SMART_UPPERCASE_SPANISH, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_SPANISH,
/*Swahili*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_SWAHILI,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_SWAHILI,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_SWAHILI, 
IMM_INPUT_MODE_SMART_LOWERCASE_SWAHILI, 
IMM_INPUT_MODE_SMART_UPPERCASE_SWAHILI, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_SWAHILI,
/*Swedish*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_SWEDISH,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_SWEDISH,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_SWEDISH, 
IMM_INPUT_MODE_SMART_LOWERCASE_SWEDISH, 
IMM_INPUT_MODE_SMART_UPPERCASE_SWEDISH, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_SWEDISH,
/*Tagalog*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_TAGALOG,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_TAGALOG,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_TAGALOG, 
IMM_INPUT_MODE_SMART_LOWERCASE_TAGALOG, 
IMM_INPUT_MODE_SMART_UPPERCASE_TAGALOG, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_TAGALOG,
/*Tamil*/
IMM_INPUT_MODE_MULTITAP_TAMIL,    
IMM_INPUT_MODE_SMART_TAMIL,
/*Telugu*/
IMM_INPUT_MODE_MULTITAP_TELUGU,    
IMM_INPUT_MODE_SMART_TELUGU,
/*Thai*/
IMM_INPUT_MODE_MULTITAP_THAI,    
IMM_INPUT_MODE_SMART_THAI,
/*Turkish*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_TURKISH,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_TURKISH,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_TURKISH, 
IMM_INPUT_MODE_SMART_LOWERCASE_TURKISH, 
IMM_INPUT_MODE_SMART_UPPERCASE_TURKISH, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_TURKISH,
/*Ukrainian*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_UKRAINIAN,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_UKRAINIAN,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_UKRAINIAN, 
IMM_INPUT_MODE_SMART_LOWERCASE_UKRAINIAN, 
IMM_INPUT_MODE_SMART_UPPERCASE_UKRAINIAN, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_UKRAINIAN,
/*Urdu*/
IMM_INPUT_MODE_MULTITAP_URDU,    
IMM_INPUT_MODE_SMART_URDU,
/*Vietnamese*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_VIETNAMESE,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_VIETNAMESE,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_VIETNAMESE, 
IMM_INPUT_MODE_SMART_LOWERCASE_VIETNAMESE, 
IMM_INPUT_MODE_SMART_UPPERCASE_VIETNAMESE, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_VIETNAMESE,
/*Xhosa*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_XHOSA,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_XHOSA,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_XHOSA, 
IMM_INPUT_MODE_SMART_LOWERCASE_XHOSA, 
IMM_INPUT_MODE_SMART_UPPERCASE_XHOSA, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_XHOSA,
/*Yoruba*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_YORUBA,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_YORUBA,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_YORUBA, 
IMM_INPUT_MODE_SMART_LOWERCASE_YORUBA, 
IMM_INPUT_MODE_SMART_UPPERCASE_YORUBA, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_YORUBA,
/*Zulu*/ 
IMM_INPUT_MODE_MULTITAP_UPPERCASE_ZULU,    
IMM_INPUT_MODE_MULTITAP_LOWERCASE_ZULU,
IMM_INPUT_MODE_MULTITAP_FIRST_UPPERCASE_ZULU, 
IMM_INPUT_MODE_SMART_LOWERCASE_ZULU, 
IMM_INPUT_MODE_SMART_UPPERCASE_ZULU, 
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_ZULU,

/* Dialects */
IMM_INPUT_MODE_SMART_UPPERCASE_UK_ABC,
IMM_INPUT_MODE_SMART_LOWERCASE_UK_ABC,
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_UK_ABC,
IMM_INPUT_MODE_SMART_UPPERCASE_CA_FRENCH,
IMM_INPUT_MODE_SMART_LOWERCASE_CA_FRENCH,
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_CA_FRENCH,
IMM_INPUT_MODE_SMART_UPPERCASE_HINGLISH,
IMM_INPUT_MODE_SMART_LOWERCASE_HINGLISH,
IMM_INPUT_MODE_SMART_UPPERCASE_SA_SPANISH,
IMM_INPUT_MODE_SMART_LOWERCASE_SA_SPANISH,
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_SA_SPANISH,
IMM_INPUT_MODE_SMART_UPPERCASE_SA_PORTUGUESE,
IMM_INPUT_MODE_SMART_LOWERCASE_SA_PORTUGUESE,
IMM_INPUT_MODE_SMART_FIRST_UPPERCASE_SA_PORTUGUESE,

/* Chinese*/
IMM_INPUT_MODE_TR_BOPOMO,
IMM_INPUT_MODE_TR_MULTITAP_BOPOMO,
IMM_INPUT_MODE_TR_STROKE,
IMM_INPUT_MODE_QUICK_SEARCH_BOPOMO,
IMM_INPUT_MODE_QUICK_SEARCH_HK_STROKE,    
IMM_INPUT_MODE_QUICK_SEARCH_PINYIN,
IMM_INPUT_MODE_QUICK_SEARCH_SM_STROKE,
IMM_INPUT_MODE_QUICK_SEARCH_TR_STROKE,
IMM_INPUT_MODE_SM_MULTITAP_PINYIN,
IMM_INPUT_MODE_SM_PINYIN,
IMM_INPUT_MODE_SM_STROKE,

IMM_INPUT_MODE_MAX_NUM
} mmi_imm_input_mode_enum;



#endif /* #ifndef __IMEGROTENUMS_H__ */


