#include "mmi_features.h"
#include "custresdef.h"

<?xml version="1.0" encoding="UTF-8"?>

<APP id="VAPP_CBS"  name="STR_ID_VAPP_CBS_MAIN_TITLE" type="venus">
    <LAYOUT file="vapp_cbs.xml"/>
    <!--Include Area-->
    #if 0
    <STRING id="STR_ID_VAPP_CBS_NOT_READY_YET"/>
    #endif /*slim for 6260, this string never be used*/


		<STRING id="STR_ID_VAPP_CBS_MAIN_TITLE"/>
		<STRING id="STR_ID_VAPP_CBS_MAIN_ACTIVATION"/>
		<STRING id="STR_ID_VAPP_CBS_MAIN_RECEIVING_CHANNELS"/>
		<STRING id="STR_ID_VAPP_CBS_MAIN_LANGUAGES"/>
		#if 0
		<STRING id="STR_ID_VAPP_CBS_CHANNEL_NORMAL_TITLE"/>
		#endif /*slim for 6260, this string never be used*/
		<STRING id="STR_ID_VAPP_CBS_CHANNEL_DELETE_TITLE"/>
		<STRING id="STR_ID_VAPP_CBS_CHANNEL_DELETE_CONFIRM_1"/>
		#if 0
		<STRING id="STR_ID_VAPP_CBS_CHANNEL_DELETE_CONFIRM_2"/>
		<STRING id="STR_ID_VAPP_CBS_CHANNEL_DELETE_FAILED_1"/>
		<STRING id="STR_ID_VAPP_CBS_CHANNEL_DELETE_FAILED_2"/>
		#endif /*slim for 6260, this string never be used*/
		<STRING id="STR_ID_VAPP_CBS_CHANNEL_EMPTY_STRING"/>

		
		<STRING id="STR_ID_VAPP_CBS_MSG_LIST_NORMAL_TITLE"/>
		<STRING id="STR_ID_VAPP_CBS_MSG_LIST_DELETE_TITLE"/>
		<STRING id="STR_ID_VAPP_CBS_MSG_LIST_DELETE_CONFIRM_1"/>
		#if 0
		<STRING id="STR_ID_VAPP_CBS_MSG_LIST_DELETE_CONFIRM_SINGLE"/>
		<STRING id="STR_ID_VAPP_CBS_MSG_LIST_DELETE_CONFIRM_2"/>
		#endif /*slim for 6260, this string never be used*/
		<STRING id="STR_ID_VAPP_CBS_MSG_LIST_DELETE_FAILED_1"/>
		<STRING id="STR_ID_VAPP_CBS_MSG_LIST_DELETE_FAILED_2"/>
		<STRING id="STR_ID_VAPP_CBS_MSG_LIST_EMPTY_STRING"/>

		<STRING id="STR_ID_VAPP_CBS_CHANNEL_EDITOR_TITLE"/>
		<STRING id="STR_ID_VAPP_CBS_CHANNEL_EDITOR_CHANNEL_NAME"/>
		<STRING id="STR_ID_VAPP_CBS_CHANNEL_EDITOR_CHANNEL_NUMBER"/>
		<STRING id="STR_ID_VAPP_CBS_CHANNEL_EDITOR_CHANNEL_SUBSCRIBE"/>
		#if 0
		<STRING id="STR_ID_VAPP_CBS_CHANNEL_EDITOR_CHANNEL_UNSUBSCRIBE"/>
		<STRING id="STR_ID_VAPP_CBS_CHANNEL_EDITOR_SAVE_CONFIRM"/>
    <STRING id="STR_ID_VAPP_CBS_CHANNEL_EDITOR_CHNL_FULL"/>
    <STRING id="STR_ID_VAPP_CBS_CHANNEL_EDITOR_SAVE_FAILED"/>
     #endif /*slim for 6260, this string never be used*/
    <STRING id="STR_ID_VAPP_CBS_CHANNEL_EDITOR_CHNL_DUPLICTED"/>
    <STRING id="STR_ID_VAPP_CBS_CHANNEL_EDITOR_NUM_LEN_EXCEEDED"/>
    <STRING id="STR_ID_VAPP_CBS_CHANNEL_EDITOR_FUNCBAR_NEXT"/>
    <STRING id="STR_ID_VAPP_CBS_CHANNEL_EDITOR_FUNCBAR_PREV"/>
    
		<STRING id="STR_ID_VAPP_CBS_NUM_CANNOT_BE_EMPTY"/>
		#if 0
		<STRING id="STR_ID_VAPP_CBS_CHANNEL_VIEWER_USE_DETAIL"/>
		#endif /*slim for 6260, this string never be used*/
		<STRING id="STR_ID_VAPP_CBS_CHANNEL_VIEWER_DELETE_CONFIRM"/>
		<STRING id="STR_ID_VAPP_CBS_CHANNEL_VIEWER_DELETE_INFORM"/>
		<STRING id="STR_ID_VAPP_CBS_CHANNEL_VIEWER_FROM"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_AFAR"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_ABKHAZIAN"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_AFRIKAANS"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_AMHARIC"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_ARABIC"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_ASSAMESE"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_AYMARA"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_AZERBAIJANI"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_BASHKIR"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_BYELORUSSIAN"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_BULGARIAN"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_BIHARI"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_BISLAMA"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_BENGALI"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_TIBETAN"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_BRETON"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_CATALAN"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_CORSICAN"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_CZECH"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_WELSH"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_DANISH"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_GERMAN"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_BHUTANI"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_GREEK"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_ENGLISH"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_ESPERANTO"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_SPANISH"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_ESTONIAN"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_BASQUE"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_PERSIAN"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_FINNISH"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_FIJI"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_FAROESE"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_FRENCH"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_FRISIAN"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_IRISH"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_SCOTS_GAELIC"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_GALICIAN"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_GUARANI"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_GUJARATI"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_HAUSA"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_HEBREW"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_HINDI"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_CROATIAN"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_HUNGARIAN"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_ARMENIAN"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_INTERLINGUA"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_INDONESIAN"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_INTERLINGUE"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_INUPIAK"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_ICELANDIC"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_ITALIAN"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_INUKTITUT"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_JAPANESE"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_JAVANESE"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_GEORGIAN"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_KAZAKH"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_GREENLANDIC"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_CAMBODIAN"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_KANNADA"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_KOREAN"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_KASHMIRI"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_KURDISH"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_KIRGHIZ"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_LATIN"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_LINGALA"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_LAOTHIAN"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_LITHUANIAN"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_LATVIAN"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_MALAGASY"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_MAORI"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_MACEDONIAN"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_MALAYALAM"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_MONGOLIAN"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_MOLDAVIAN"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_MARATHI"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_MALAY"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_MALTESE"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_BURMESE"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_NAURU"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_NEPALI"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_DUTCH"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_NORWEGIAN"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_OCCITAN"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_OROMO"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_ORIYA"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_PUNJABI"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_POLISH"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_PASHTO"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_PORTUGUESE"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_QUECHUA"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_RHAETO_ROMANCE"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_KIRUNDI"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_ROMANIAN"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_RUSSIAN"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_KINYARWANDA"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_SANSKRIT"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_SINDHI"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_SANGHO"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_SERBO_CROATIAN"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_SINHALESE"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_SLOVAK"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_SLOVENIAN"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_SAMOAN"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_SHONA"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_SOMALI"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_ALBANIAN"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_SERBIAN"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_SISWATI"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_SESOTHO"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_SUNDANESE"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_SWEDISH"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_SWAHILI"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_TAMIL"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_TELUGU"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_TAJIK"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_THAI"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_TIGRINYA"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_TURKMEN"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_TAGALOG"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_SETSWANA"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_TONGA"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_TURKISH"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_TSONGA"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_TATAR"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_TWI"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_UIGHUR"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_UKRAINIAN"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_URDU"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_UZBEK"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_VIETNAMESE"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_VOLAPUK"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_WOLOF"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_XHOSA"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_YIDDISH"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_YORUBA"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_ZHUANG"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_CHINESE"/>
	<STRING id="STR_ID_VAPP_CBS_LANG_ZULU"/>
	<STRING id="STR_ID_VAPP_CBS_SIM"/>
	<STRING id="STR_ID_VAPP_CBS_UNAVAILABLE_SIM"/>
			 
  #if 0		 
  <STRING id="STR_ID_VAPP_CBS_LANG_UNSPECIFIED"/>
  #endif /*slim for 6260, this string never be used*/
	<STRING id="STR_ID_VAPP_CBS_LANG_OTHERS"/>	
		<STRING id="STR_ID_VAPP_CBS_LANG_ALL_LANGS"/>	
    <!-------------Resource for Image---------------------------------------------->

<THEME>
#if 0
    <IMAGE id="IMG_ID_VAPP_CBS_VIEWER_TITLE_ICON"  desc="CBS message viewer title icon"/>
    <IMAGE id="IMG_ID_VAPP_CBS_VIEWER_TITLE_LIST_ICON"  desc="CBS channel list icon for subscribed channel"/>
    <IMAGE id="IMG_ID_VAPP_CBS_VIEWER_TITLE_LIST_ICON_UNSUB" desc="CBS channel list icon for unsubscribed channel"/>
    <IMAGE id="IMG_ID_VAPP_CBS_VIEWER_USE_DETAIL" desc="CBS message viewer use detail toolbar icon"/>
    <IMAGE id="IMG_ID_VAPP_CBS_CHANNEL_LIST_EDIT" desc="CBS channel list icon for edit channel button"/>
    <IMAGE id="IMG_ID_VAPP_CBS_VIEWER_TITLE_BG" desc="CBS message viewer title background"/>
#endif
    <IMAGE id="IMG_ID_VAPP_CBS_VIEWER_TITLE_BG_BORDER" desc="CBS message viewer title icon border"/>
    <IMAGE id="IMG_ID_VAPP_CBS_VIEWER_TITLE_BG_IMAGE"  desc="CBS message viewer title icon background"/>
	</THEME>

 
	  #define ROOT_PATH RES_THEME_ROOT"\\\\Default\\\\Message\\\\"  
    <IMAGE id="IMG_ID_VAPP_CBS_VIEWER_TITLE_ICON">ROOT_PATH"cb.png"</IMAGE>    
    <IMAGE id="IMG_ID_VAPP_CBS_VIEWER_TITLE_LIST_ICON">ROOT_PATH"ListIcon\\\\CB_Subscirbe.png"</IMAGE>   
    <IMAGE id="IMG_ID_VAPP_CBS_VIEWER_TITLE_LIST_ICON_UNSUB">ROOT_PATH"ListIcon\\\\CB_Unsubscirbe.png"</IMAGE>   

    #define ROOT_PATH RES_THEME_ROOT"\\\\Default\\\\Message\\\\ToolbarIcon\\\\"     
#ifdef __MMI_SMS_DETAILS_INFO__
    <IMAGE id="IMG_ID_VAPP_CBS_VIEWER_USE_DETAIL">ROOT_PATH"Use_Detail.png"</IMAGE>    
#endif
    <IMAGE id="IMG_ID_VAPP_CBS_CHANNEL_LIST_EDIT">RES_THEME_ROOT"\\\\Default\\\\Common\\\\Button\\\\Edit.png"</IMAGE> 
#if 0
    #define ROOT_PATH RES_THEME_ROOT"\\\\Default\\\\Components\\\\TitleBar\\\\"    
    <IMAGE id="IMG_ID_VAPP_CBS_VIEWER_TITLE_BG">ROOT_PATH"DTitleBar.9slice.png"</IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CBS_VIEWER_TITLE_BG_BORDER">RES_THEME_ROOT"\\\\Theme1\\\\Components\\\\Photo_Border_BG\\\\Default_01.9slice.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CBS_VIEWER_TITLE_BG_IMAGE">RES_THEME_ROOT"\\\\Theme1\\\\Components\\\\Photo_Border_BG\\\\Default_02.9slice.png"</IMAGE> 
#endif

    
		<EVENT id="EVT_ID_VAPP_CBS_MSG_VIEWED_IND" type="SENDER"/>.
	
	
    <RECEIVER id="EVT_ID_SRV_CBS_NEW_MSG_IND" proc="vapp_cbs_msg_event_proc"/>
</APP>

