//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by plugin_mte.rc
//
#define IDOK                            1
#define IDCANCEL                        2
#define IDD_DIALOG_COLORS               130
#define IDB_BITMAP_HSB                  130
#define IDB_BITMAP_RGB                  131
#define ID_THEME_SAVE                   141
#define ID_THEME_APPLY                  142
#define IDC_STATIC_RGB_RECT             1000
#define IDC_STATIC_HSB_RECT             1001
#define IDC_EDIT_RED                    1002
#define IDC_SPIN_RED                    1003
#define IDC_EDIT_GREEN                  1004
#define IDC_SPIN_GREEN                  1005
#define IDC_EDIT_BLUE                   1006
#define IDC_SPIN_BLUE                   1007
#define IDC_STATIC_OLD                  1008
#define IDC_STATIC_NEW                  1009
#define IDC_EDIT_HUE                    1010
#define IDC_SPIN_HUE                    1011
#define IDC_EDIT_SAT                    1012
#define IDC_SPIN_SAT                    1013
#define IDC_EDIT_VAL                    1014
#define IDC_SPIN_VAL                    1015
#define IDI_MTE2                        3002
#define IDD_DIALOG_THEME                10000
#define IDD_DIALOG_THEME_EDITOR         3026
#define IDC_SCROLLBAR1                  3029
#define IDC_SCROLLBAR2                  3030
#define IDEDIT                          3030
#define IDCOPYASNEW                     3031
#define IDOUTPUT                        3033
#define IDR_MENU_THEME                  3034
#define IDC_EDIT_ALPHA                  3035
#define IDLOADTHEME                     3035
#define IDD_DIALOG_FIND_COMPONENT       3035
#define IDC_LIST_THEME_EDITOR           3036
#define IDSAVETHEME                     3036
#define IDD_DIALOG_GOTO_SCREEN          3036
#define ID_THEME_EDITOR_EDIT            3037
#define IDC_EDIT_COMPONENT_NAME         3038
#define IDD_DIALOG_THEME_SETTING        3039
#define IDC_COMBO1                      3039
#define IDD_DIALOG_THEME_INDEX          3040
#define IDC_CHECK1                      3041
#define IDC_EDIT_INDEX                  3042
#define IDC_EDIT_NAME                   3043
#define IDC_EDIT_FROM                   3044
#define IDD_DIALOG_COLOR                3044
#define IDD_DIALOG_PROCESS              3045
#define IDC_COMBO_COMPONENT_GROUP       3046
#define IDC_COLOR                       3047
#define IDI_MTE                         3048
#define IDC_FILLER_C                    3049
#define IDC_FILLER_AC                   3051
#define IDI_MTE1                        3052
#define IDC_STATIC_COLOR                3056
#define IDC_FILLER_SC                   3057
#define IDC_FILLER_BC                   3058
#define IDC_STATIC_FILLER               3059
#define IDC_FILLER_IMAGE                3060
#define IDC_IMAGE                       3061
#define IDC_STATIC_SIZE                 3061
#define IDC_STATIC_IMAGE                3062
#define IDC_SLIDER_R                    3063
#define IDC_STATIC_RGB_COLOR            3064
#define IDC_STATIC_R_COLOR              3065
#define IDC_EDITR                       3067
#define IDC_BUTTON_BOX                  3068
#define IDC_STATIC_REC                  3069
#define IDC_STATIC_IMAGE_REC            3070
#define IDC_SLIDER_G                    3070
#define IDC_STATIC_REC_WH               3071
#define IDC_STATIC_G_COLOR              3071
#define IDC_STATIC_REC_MWH              3072
#define IDC_EDITG                       3072
#define IDC_STATIC_REC2                 3073
#define IDC_SLIDER_B                    3073
#define IDC_STATIC_B_COLOR              3074
#define IDC_EDITB                       3075
#define IDC_BUTTON_HSB                  3076
#define IDC_COLOUR                      3077
#define IDC_CHECK_BOARDER               3078
#define IDC_PROGRESS1                   3079
#define IDC_STATIC_GROUP_FILLER         3081
#define IDC_STATIC_TEXT_COLOR           3083
#define IDC_STATIC_TEXT_BC              3084
#define IDC_STATIC_FILLER_IMAGE         3085
#define IDC_STATIC_INTEGER              3086
#define IDC_EDIT_INTEGER                3087
#define IDC_STATIC_MAXMIN               3088
#define IDC_CHECK_FILLER_BORDER         3089
#define IDC_BUTTON_IMAGE                3090
#define IDC_COMBO_COMPONENT_GROUP_EX    3091
#define IDC_COMBOBOXEX1                 3092
#define IDDELETE                        3095
#define IDC_LIST_THEME                  3096
#define IDC_EDIT_COLOR                  3097
#define IDC_CHECK_TRANSPARENT           3098
#define IDC_BUTTON_UPINT                3100
#define IDC_ANIMATION_IMAGE_SEQUENCE    3101
#define IDC_ANIMATION_IMAGE_PREVIEWER   3102
#define IDC_ANIMATION_IMAGE_ONE         3103
#define IDC_ANIMATION_IMAGE_TWO         3104
#define IDC_ANIMATION_IMAGE_THREE       3105
#define IDC_ANIMATION_IMAGE_FOUR        3106
#define IDC_ANIMATION_IMAGE_FIVE        3107
#define IDC_ANIMATION_IMAGE_ADD         3108
#define IDC_ANIMATION_IMAGE_REMOVE      3109
#define IDC_ANIMATION_IMAGE_LABEL_ONE   3110
#define IDC_ANIMATION_IMAGE_LABEL_TWO   3111
#define IDC_ANIMATION_IMAGE_LABEL_THREE 3112
#define IDC_ANIMATION_IMAGE_LABEL_FOUR  3113
#define IDC_ANIMATION_IMAGE_LABEL_FIVE  3114
#define IDC_ANIMATION_DELAY             3115
#define IDC_ANIMATION_LABEL_DELAY       3116
#define IDC_ANIMATION_REPEAT            3117
#define IDC_ANIMATION_LABEL_REPEAT      3118
#define IDC_SLICE_LEFT                  3119
#define IDC_SLICE_TOP                   3120
#define IDC_SLICE_RIGHT                 3121
#define IDC_SLICE_BOTTOM                3122
#define IDC_BUTTON_DELAY_SETTING        3134
#define IDC_SPECIAL_SCREEN_WARNING      3135
#define IDC_STATIC_LEFT                 3136
#define IDC_STATIC_TOP                  3137
#define IDC_STATIC_RIGHT                3138
#define IDC_STATIC_BOTTOM               3139
#define IDC_BUTTON_SILCE_SET            3140
#define IDC_RADIO_SETTING_LEFT          3141
#define IDC_RADIO_SETTING_TOP           3142
#define IDC_RADIO_SETTING_RIGHT         3143
#define IDC_RADIO_SETTING_BOTTOM        3144
#define ID_FIND_COMPONENT               32792
#define ID_GOTO_SCREEN                  32793
#define ID_MENU_ENGLISH                 32799
#define ID_MENU_SIMCHINESE              32800
#define ID_SETTING                      32801
#define ID_UNDO                         32804
#define ID_REDO                         32805
#define ID_MTE_UG                       32806

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        5001
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         5000
#define _APS_NEXT_SYMED_VALUE           5000
#endif
#endif
