/* Needed header files of the compile option in XML files, if you need others need to add here */
#include "mmi_features.h"
#include "custresdef.h"

<?xml version="1.0" encoding="UTF-8"?>

<APP id="VAPP_CALLSET" name="STR_ID_VAPP_CALLSET_CALL_SETTING" type="venus">
#ifdef __MMI_VIDEO_TELEPHONY__
    <MEMORY extra_base="VAPP_UCM_RES_MAX_W*VAPP_UCM_RES_MAX_H*VAPP_UCM_VDO_FRAME_FACTOR"
    #ifdef __MMI_UCM_REJECT_BY_SMS__
            cui="max(VCUI_FMGR, VCUI_MSGCOMPOSER, VCUI_VERIFY, VCUI_CONTACT_LIST)"
    #else
            cui="max(VCUI_FMGR, VCUI_VERIFY, VCUI_CONTACT_LIST)"
    #endif
            fg="base(SRV_MDI_VT) + VAPP_UCM_RES_MAX_W*VAPP_UCM_RES_MAX_H*MDI_VT_SRV_FACTOR"
            inc="med_global.h,Vapp_ucm_res_def.h,vfx_sys_config.h" />
#else /* __MMI_VIDEO_TELEPHONY__ */
    <MEMORY
        #ifndef __LOW_COST_SUPPORT_COMMON__
            cui="max(VCUI_MSGCOMPOSER, VCUI_VERIFY, VCUI_CONTACT_LIST)"
        #else
            cui="max(VCUI_VERIFY, VCUI_CONTACT_LIST)"
        #endif
    />
#endif /* __MMI_VIDEO_TELEPHONY__ */

    <LAYOUT file="vapp_callset.xml" />

    /* When you use any ID of other module, you need to add
       that header file here, so that Resgen can find the ID */
    <!--Include Area-->
    <INCLUDE file="GlobalResDef.h,SettingResDef.h,GlobalMenuItems.h"/>
    <INCLUDE file="Mmi_rp_all_defs.h"/>

    <RECEIVER id="EVT_ID_SRV_CALLSET_CFU_STATUS_IND" proc="vapp_callset_hdlr_cfu_status_ind"/>

    <!-----------------------------------------------------String Resource Area----------------------------------------------------->
    /* String ID of you Application, we will get string from ref_list.txt for all languages */
    
    <STRING id="STR_ID_VAPP_CALLSET_LEFT_PARENTHESIS"/>
    <STRING id="STR_ID_VAPP_CALLSET_RIGHT_PARENTHESIS"/>
    <STRING id="STR_ID_VAPP_CALLSET_SEC"/>
    <STRING id="STR_ID_VAPP_CALLSET_SECS"/>
    <STRING id="STR_ID_VAPP_CALLSET_UNKNOWN"/>
    <STRING id="STR_ID_VAPP_CALLSET_CALL_SETTING"/>
    <STRING id="STR_ID_VAPP_CALLSET_LIST_NUM"/>
    <STRING id="STR_ID_VAPP_CALLSET_LIST_ADD"/>
    <STRING id="STR_ID_VAPP_CALLSET_INPUT_NUMBER"/>
    <STRING id="STR_ID_VAPP_CALLSET_SEL_PHB"/>
#ifdef __MMI_CM_BLACK_LIST__
    <STRING id="STR_ID_VAPP_CALLSET_BLACKLIST"/>
    <STRING id="STR_ID_VAPP_CALLSET_BLACKLIST_HINT"/>
    <STRING id="STR_ID_VAPP_CALLSET_BLACKLIST_FROM_LIST"/>
    <STRING id="STR_ID_VAPP_CALLSET_BLACKLIST_INPUT_NUMBER"/>
    <STRING id="STR_ID_VAPP_CALLSET_BLACKLIST_DEL_CNF"/>
#endif /* __MMI_CM_BLACK_LIST__ */
#ifdef __MMI_UCM_AUTO_REJECT_NO_CALL_ID__
    <STRING id="STR_ID_VAPP_CALLSET_BLACKLIST_REJ_UNKNOWN_NUM"/>
    <STRING id="STR_ID_VAPP_CALLSET_BLACKLIST_REJ_UNKNOWN_NUM_HINT"/>
#endif /* __MMI_UCM_AUTO_REJECT_NO_CALL_ID__ */
#ifdef __MMI_CM_WHITE_LIST__
    <STRING id="STR_ID_VAPP_CALLSET_WHITELIST"/>
    <STRING id="STR_ID_VAPP_CALLSET_WHITELIST_HINT"/>
    <STRING id="STR_ID_VAPP_CALLSET_WHITELIST_FROM_LIST"/>
    <STRING id="STR_ID_VAPP_CALLSET_WHITELIST_INPUT_NUMBER"/>
#endif /* __MMI_CM_WHITE_LIST__ */
    <STRING id="STR_ID_VAPP_CALLSET_AUTOREDIAL"/>
    <STRING id="STR_ID_VAPP_CALLSET_AUTOREDIAL_ALWAYS"/>
    <STRING id="STR_ID_VAPP_CALLSET_AUTOREDIAL_NEVER"/>
    <STRING id="STR_ID_VAPP_CALLSET_AUTOREDIAL_CONF"/>
#ifdef __MMI_CALLSET_CTD_CONFIGURABLE__
    <STRING id="STR_ID_VAPP_CALLSET_CTD"/>
    <STRING id="STR_ID_VAPP_CALLSET_CTD_HINT"/>
#endif /* __MMI_CALLSET_CTD_CONFIGURABLE__ */
#ifdef __IP_NUMBER__
    <STRING id="STR_ID_VAPP_CALLSET_IP_NUMBER"/>
    <STRING id="STR_ID_VAPP_CALLSET_IP_EDIT"/>
    <STRING id="STR_ID_VAPP_CALLSET_IP_SET"/>
#endif /* __IP_NUMBER__ */
    <STRING id="STR_ID_VAPP_CALLSET_CTR"/>
    <STRING id="STR_ID_VAPP_CALLSET_CTR_SING"/>
    <STRING id="STR_ID_VAPP_CALLSET_CTR_PERIOD"/>
    <STRING id="STR_ID_VAPP_CALLSET_CTR_TIME"/>
    <STRING id="STR_ID_VAPP_CALLSET_CTR_RANGE_SING"/>
    <STRING id="STR_ID_VAPP_CALLSET_CTR_RANGE_PERIODIC"/>
#ifdef __MMI_CH_QUICK_END__
    <STRING id="STR_ID_VAPP_CALLSET_QUICK_END"/>
    <STRING id="STR_ID_VAPP_CALLSET_QUICK_END_HINT1"/>
    <STRING id="STR_ID_VAPP_CALLSET_QUICK_END_HINT2"/>
    <STRING id="STR_ID_VAPP_CALLSET_QUICK_END_TIME"/>
    <STRING id="STR_ID_VAPP_CALLSET_QUICK_END_DURATION"/>
    <STRING id="STR_ID_VAPP_CALLSET_QUICK_END_INPUT_TIME"/>
#endif /* __MMI_CH_QUICK_END__ */
#ifdef __MMI_UCM_REJECT_BY_SMS__
    <STRING id="STR_ID_VAPP_CALLSET_REJ_BY_SMS"/>
    <STRING id="STR_ID_VAPP_CALLSET_REJ_BY_SMS_HINT"/>
    <STRING id="STR_ID_VAPP_CALLSET_REJ_BY_SMS_USE"/>
    <STRING id="STR_ID_VAPP_CALLSET_REJ_BY_SMS_REJ_AFTER_SEND"/>
    <STRING id="STR_ID_VAPP_CALLSET_REJ_BY_SMS_TEMPLATE"/>
#endif /* __MMI_UCM_REJECT_BY_SMS__ */
#ifdef __MMI_CONNECT_NOTICE__
    <STRING id="STR_ID_VAPP_CALLSET_CONNECT_NOTICE"/>
    <STRING id="STR_ID_VAPP_CALLSET_CONNECT_NOTICE_HINT"/>
#endif
#ifdef __MMI_CLAMSHELL__
    <STRING id="STR_ID_VAPP_CALLSET_ANS_MODE_CLAMSHELL"/>
#endif
    <STRING id="STR_ID_VAPP_CALLSET_ANS_MODE_AUTO"/>
    <STRING id="STR_ID_VAPP_CALLSET_CTM"/>
    <STRING id="STR_ID_VAPP_CALLSET_CTM_HINT"/>
    <STRING id="STR_ID_VAPP_CALLSET_CTM_MODE"/>
    <STRING id="STR_ID_VAPP_CALLSET_CTM_SEL_MODE"/>
    <STRING id="STR_ID_VAPP_CALLSET_CTM_MANUAL"/>
    <STRING id="STR_ID_VAPP_CALLSET_CTM_BAUDOT"/>
    <STRING id="STR_ID_VAPP_CALLSET_CTM_HCO"/>
    <STRING id="STR_ID_VAPP_CALLSET_CTM_VCO"/>
#ifdef __MMI_VIDEO_TELEPHONY__
    <STRING id="STR_ID_VAPP_CALLSET_VT"/>
    <STRING id="STR_ID_VAPP_CALLSET_VT_HINT"/>
    <STRING id="STR_ID_VAPP_CALLSET_VT_PREVIEW"/>
    <STRING id="STR_ID_VAPP_CALLSET_VT_DIAL_MODE"/>
    <STRING id="STR_ID_VAPP_CALLSET_VT_ANS_MODE"/>
    <STRING id="STR_ID_VAPP_CALLSET_VT_START_CAM"/>
    <STRING id="STR_ID_VAPP_CALLSET_VT_STOP_CAM"/>
    <STRING id="STR_ID_VAPP_CALLSET_VT_PROMPT"/>
    <STRING id="STR_ID_VAPP_CALLSET_VT_OPEN_MIC"/>
    <STRING id="STR_ID_VAPP_CALLSET_VT_OPEN_SPEAKER"/>
    <STRING id="STR_ID_VAPP_CALLSET_VT_CAM_FRONT"/>
    <STRING id="STR_ID_VAPP_CALLSET_VT_CAM_REAR"/>
    <STRING id="STR_ID_VAPP_CALLSET_VT_CAM_OFF"/>
    <STRING id="STR_ID_VAPP_CALLSET_VT_NIGHT_MODE"/>
    <STRING id="STR_ID_VAPP_CALLSET_VT_SEL_PIC"/>
    <STRING id="STR_ID_VAPP_CALLSET_VIDEO"/>
    <STRING id="STR_ID_VAPP_CALLSET_VIDEO_2"/>
    <STRING id="STR_ID_VAPP_CALLSET_EV_P4"/>
    <STRING id="STR_ID_VAPP_CALLSET_EV_P3"/>
    <STRING id="STR_ID_VAPP_CALLSET_EV_P2"/>
    <STRING id="STR_ID_VAPP_CALLSET_EV_P1"/>
    <STRING id="STR_ID_VAPP_CALLSET_EV_0"/>
    <STRING id="STR_ID_VAPP_CALLSET_EV_N1"/>
    <STRING id="STR_ID_VAPP_CALLSET_EV_N2"/>
    <STRING id="STR_ID_VAPP_CALLSET_EV_N3"/>
    <STRING id="STR_ID_VAPP_CALLSET_EV_N4"/>
    <STRING id="STR_ID_VAPP_CALLSET_IMG_NOT_AVAILABLE"/>
#endif /* __MMI_VIDEO_TELEPHONY__ */
    <STRING id="STR_ID_VAPP_CALLSET_MORE"/>
    <STRING id="STR_ID_VAPP_CALLSET_MORE_HINT"/>
    <STRING id="STR_ID_VAPP_CALLSET_SEL_SIM"/>
    <STRING id="STR_ID_VAPP_CALLSET_CID_HIDE"/>
    <STRING id="STR_ID_VAPP_CALLSET_CID_HINT"/>
    <STRING id="STR_ID_VAPP_CALLSET_CALLWAIT"/>
    <STRING id="STR_ID_VAPP_CALLSET_CALLWAIT_HINT"/>
    <STRING id="STR_ID_VAPP_CALLSET_CALLFWD"/>
#ifdef __MMI_CALLSET_CUG__
    <STRING id="STR_ID_VAPP_CALLSET_CUG"/>
    <STRING id="STR_ID_VAPP_CALLSET_CUG_EDIT"/>
    <STRING id="STR_ID_VAPP_CALLSET_CUG_INPUT_NAME"/>
    <STRING id="STR_ID_VAPP_CALLSET_CUG_EDIT_HINT"/>
    <STRING id="STR_ID_VAPP_CALLSET_CUG_EDIT_NAME"/>
    <STRING id="STR_ID_VAPP_CALLSET_CUG_NAME"/>
#endif /* __MMI_CALLSET_CUG__ */
    <STRING id="STR_ID_VAPP_CALLSET_LINE_SWITCH"/>
    <STRING id="STR_ID_VAPP_CALLSET_LSW_SEL_LINE"/>
    <STRING id="STR_ID_VAPP_CALLSET_LSW_LINE1"/>
    <STRING id="STR_ID_VAPP_CALLSET_LSW_LINE2"/>
    <STRING id="STR_ID_VAPP_CALLSET_VOICE"/>
    <STRING id="STR_ID_VAPP_CALLSET_DATA"/>
    <STRING id="STR_ID_VAPP_CALLSET_VOICE_2"/>
    <STRING id="STR_ID_VAPP_CALLSET_DATA_2"/>
    <STRING id="STR_ID_VAPP_CALLSET_CFU"/>
    <STRING id="STR_ID_VAPP_CALLSET_CFNRC"/>
    <STRING id="STR_ID_VAPP_CALLSET_CFNRY"/>
    <STRING id="STR_ID_VAPP_CALLSET_CFNRY_TIME"/>
    <STRING id="STR_ID_VAPP_CALLSET_CFB"/>
    <STRING id="STR_ID_VAPP_CALLSET_CF_EDIT"/>
    <STRING id="STR_ID_VAPP_CALLSET_CF_TO"/>
    <STRING id="STR_ID_VAPP_CALLSET_CF_NUM"/>
    <STRING id="STR_ID_VAPP_CALLSET_CF_INPUT_NUM"/>
    <STRING id="STR_ID_VAPP_CALLSET_CB_INPUT_PASSWD"/>
    <STRING id="STR_ID_VAPP_CALLSET_CFNRY_5_SEC"/>
    <STRING id="STR_ID_VAPP_CALLSET_CFNRY_10_SEC"/>
    <STRING id="STR_ID_VAPP_CALLSET_CFNRY_15_SEC"/>
    <STRING id="STR_ID_VAPP_CALLSET_CFNRY_20_SEC"/>
    <STRING id="STR_ID_VAPP_CALLSET_CFNRY_25_SEC"/>
    <STRING id="STR_ID_VAPP_CALLSET_CFNRY_30_SEC"/>
    <STRING id="STR_ID_VAPP_CALLSET_CALL_BAR"/>
    <STRING id="STR_ID_VAPP_CALLSET_CB_OUT"/>
    <STRING id="STR_ID_VAPP_CALLSET_CB_IN"/>
    <STRING id="STR_ID_VAPP_CALLSET_CB_CHANGEPASS"/>
    <STRING id="STR_ID_VAPP_CALLSET_CB_OUT_BAOC"/>
    <STRING id="STR_ID_VAPP_CALLSET_CB_OUT_BOIC"/>
    <STRING id="STR_ID_VAPP_CALLSET_CB_OUT_BOICEXHC"/>
    <STRING id="STR_ID_VAPP_CALLSET_CB_IN_BAIC"/>
    <STRING id="STR_ID_VAPP_CALLSET_CB_IN_BAICROAM"/>
    <STRING id="STR_ID_VAPP_CALLSET_CB_PASSWD"/>
    <STRING id="STR_ID_VAPP_CALLSET_CB_PASSWD_OLD"/>
    <STRING id="STR_ID_VAPP_CALLSET_CB_PASSWD_NEW"/>
    <STRING id="STR_ID_VAPP_CALLSET_CB_PASSWD_CNF"/>
    <STRING id="STR_ID_VAPP_CALLSET_DEACTIVATED"/>
    <STRING id="STR_ID_VAPP_CALLSET_CTD"/>
    <STRING id="STR_ID_VAPP_CALLSET_PREV"/>
    <STRING id="STR_ID_VAPP_CALLSET_NEXT"/>
    <STRING id="STR_ID_VAPP_CALLSET_ACTIVATE_CNF"/>
    <STRING id="STR_ID_VAPP_CALLSET_AUTO_ANS"/>


    <!-----------------------------------------------------Image Resource Area------------------------------------------------------>
    /* Image Id and path of you Application , you can use compile option in Path, but need out of "" */

    <IMAGE id="IMG_ID_CALLSET_MAIN">RES_IMG_ROOT"\\\\Settings\\\\Call.png"</IMAGE>

#if defined(__MMI_CM_BLACK_LIST__) || defined(__MMI_CM_WHITE_LIST__)
    <IMAGE id="IMG_ID_CALLSET_DEL">RES_IMG_ROOT"\\\\Common\\\\Button\\\\Delete.png"</IMAGE>
#endif /* defined(__MMI_CM_WHITE_LIST__) || defined(__MMI_CM_WHITE_LIST__) */
    <IMAGE id="IMG_ID_CALLSET_CHANGE_PASSWD">RES_IMG_ROOT"\\\\UCM\\\\ToolbarIcon\\\\ChangePassword.png"</IMAGE>

#ifdef __MMI_CALLSET_CUG__
    <IMAGE id="IMG_ID_CALLSET_EDIT_GROUP">RES_IMG_ROOT"\\\\Contact\\\\ToolbarIcon\\\\Edit_Group.png"</IMAGE>
#endif /* __MMI_CALLSET_CUG__ */

#ifdef __MMI_VIDEO_TELEPHONY__
    <IMAGE id="IMG_ID_CALLSET_VT_ZOOMIN">RES_THEME_ROOT"\\\\Theme1\\\\UCM\\\\Add.png"</IMAGE>
    <IMAGE id="IMG_ID_CALLSET_VT_ZOOMOUT">RES_THEME_ROOT"\\\\Theme1\\\\UCM\\\\Reduce.png"</IMAGE>
    <IMAGE id="IMG_ID_CALLSET_VT_EV">RES_THEME_ROOT"\\\\Theme1\\\\UCM\\\\Brightness.png"</IMAGE>
    <IMAGE id="IMG_ID_CALLSET_VT_DEFAULT_IMAGE">RES_THEME_ROOT"\\\\Theme1\\\\Common\\\\Avatar_02.png"</IMAGE>
#endif /* __MMI_VIDEO_TELEPHONY__ */

#ifdef __IP_NUMBER__
    <IMAGE id="IMG_ID_CALLSET_VICON_SIM1">CUST_IMG_PATH"\\\\MainLCD\\\\DualSIM\\\\IPdial\\\IP 1.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CALLSET_VICON_SIM2">CUST_IMG_PATH"\\\\MainLCD\\\\DualSIM\\\\IPdial\\\IP 2.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CALLSET_VICON_BOTH">CUST_IMG_PATH"\\\\MainLCD\\\\DualSIM\\\\IPdial\\\IP 12.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CALLSET_VICON_SIM12">RES_THEME_ROOT"\\\\Theme2\\\\Common\\\ipsim.png"</IMAGE>
#endif



    <!------------------------------------------------------Other Resource---------------------------------------------------------->



</APP>
