/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_app_cbs.c
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   MTK resgenerator XML parser
 *
 *******************************************************************************/
#include "CustDataProts.h"
#include "mmi_rp_app_cbs_def.h"

/* Application specified header files for using old res IDs */
#include "MMI_features.h"
#include "MMIDataType.h"    /* for resource base */

#include "CustResDef.h"         /* for image/audio path */
#include "GlobalMenuItems.h"    /* for menu resource */

#include "GlobalResDef.h"
#include "SmsAppResDef.h"


/*****************************************************************************
* FUNCTION
*  mmi_rp_app_cbs_populate
* DESCRIPTION
*  Automatically generated populate function for mmi_rp_app_cbs_populate
* PARAMETERS
*  void
* RETURNS
*  void
*****************************************************************************/
void mmi_rp_app_cbs_populate(void)
{
    /*----------------------------------------------------------------*/
    /* Local Variables                                                */
    /*----------------------------------------------------------------*/

    /*----------------------------------------------------------------*/
    /* Code Body                                                      */
    /*----------------------------------------------------------------*/

/******************** Menu resource IDs - begin ********************/
    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CBS_CHANNELS,
        MENU_ID_CBS_MAIN,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CBS_CHANNELS,
        IMG_ID_CBS_COMMON));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CBS_LANGUAGES,
        MENU_ID_CBS_MAIN,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CBS_LANGUAGES,
        IMG_ID_CBS_COMMON));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CBS_INBOX,
        MENU_ID_CBS_MAIN,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CBS_INBOX,
        IMG_ID_CBS_COMMON));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CBS_RECEIVE_MODE_ON,
        MENU_ID_CBS_RECEIVE_MODE,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_ON,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CBS_RECEIVE_MODE_OFF,
        MENU_ID_CBS_RECEIVE_MODE,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_OFF,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CBS_CHNL_OPT_SUBSCRIBE,
        MENU_ID_CBS_CHNL_OPTIONS,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CBS_SUBSCRIBE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CBS_CHNL_OPT_UNSUBSCRIBE,
        MENU_ID_CBS_CHNL_OPTIONS,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CBS_CANCEL_SUBSCRIPTION,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CBS_CHNL_OPT_ADD,
        MENU_ID_CBS_CHNL_OPTIONS,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_ADD,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CBS_CHNL_OPT_EDIT,
        MENU_ID_CBS_CHNL_OPTIONS,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_EDIT,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CBS_CHNL_OPT_DELETE,
        MENU_ID_CBS_CHNL_OPTIONS,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_DELETE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CBS_VIEWER_OPT_DELETE,
        MENU_ID_CBS_VIEWER_OPTIONS,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_DELETE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CBS_VIEWER_OPT_USE_NUM,
        MENU_ID_CBS_VIEWER_OPTIONS,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_SMS_USE_NUM_ADDRESS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CBS_RECEIVE_MODE,
        MENU_ID_CBS_MAIN,
        2,
        MENU_ID_CBS_RECEIVE_MODE_ON,
        MENU_ID_CBS_RECEIVE_MODE_OFF,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_APP_SUB,
        STR_ID_CBS_RECEIVE_MODE,
        IMG_ID_CBS_COMMON));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CBS_MAIN,
        0,
        4,
        MENU_ID_CBS_RECEIVE_MODE,
        MENU_ID_CBS_CHANNELS,
        MENU_ID_CBS_LANGUAGES,
        MENU_ID_CBS_INBOX,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_APP_MAIN,
        STR_ID_CBS_CAPTION,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CBS_CHNL_OPTIONS,
        0,
        5,
        MENU_ID_CBS_CHNL_OPT_SUBSCRIBE,
        MENU_ID_CBS_CHNL_OPT_UNSUBSCRIBE,
        MENU_ID_CBS_CHNL_OPT_ADD,
        MENU_ID_CBS_CHNL_OPT_EDIT,
        MENU_ID_CBS_CHNL_OPT_DELETE,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_OPTIONS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CBS_VIEWER_OPTIONS,
        0,
        2,
        MENU_ID_CBS_VIEWER_OPT_DELETE,
        MENU_ID_CBS_VIEWER_OPT_USE_NUM,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_OPTIONS,
        0));

/******************** Menu resource IDs - finish ********************/

/******************** Menu Hilite/Hint Handlers - begin ********************/
/******************** Menu Hilite/Hint Handlers - finish ********************/
}
