/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_app_mmi_wap_push.c
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   MTK resgenerator XML parser
 *
 *******************************************************************************/
#include "CustDataProts.h"
#include "mmi_rp_app_mmi_wap_push_def.h"

/* Application specified header files for using old res IDs */
#include "MMI_features.h"
#include "MMIDataType.h"    /* for resource base */

#include "CustResDef.h"         /* for image/audio path */
#include "GlobalMenuItems.h"    /* for menu resource */

#include "GlobalResDef.h"
#include "mmi_rp_app_mmi_wap_push_def.h"
#include "mmi_rp_app_unifiedmessage_def.h"


/*****************************************************************************
* FUNCTION
*  mmi_rp_app_mmi_wap_push_populate
* DESCRIPTION
*  Automatically generated populate function for mmi_rp_app_mmi_wap_push_populate
* PARAMETERS
*  void
* RETURNS
*  void
*****************************************************************************/
void mmi_rp_app_mmi_wap_push_populate(void)
{
    /*----------------------------------------------------------------*/
    /* Local Variables                                                */
    /*----------------------------------------------------------------*/

    /*----------------------------------------------------------------*/
    /* Code Body                                                      */
    /*----------------------------------------------------------------*/

/******************** Menu resource IDs - begin ********************/
    ADD_APPLICATION_MENUITEM5((
        MENU_ID_PUSH_INBOX,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_PUSH_INBOX,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_PUSH_MSG_OPTION,
        0,
        3,
        MENU_ID_PUSH_SERVICE_MSG_GOTO,
        MENU_ID_PUSH_SERVICE_MSG_DELETE,
        MENU_ID_PUSH_SERVICE_MSG_DELETE_ALL,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_OPTIONS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_PUSH_SERVICE_MSG_GOTO,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_GO_TO,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_PUSH_SERVICE_MSG_ADD_BOOKMARK,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_PUSH_INBOX_ADD_BOOKMARK,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_PUSH_SERVICE_MSG_DELETE,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_DELETE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_PUSH_SERVICE_MSG_DELETE_ALL,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_DELETE_ALL,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_SERVICE_MESSAGE,
        0,
        2,
        MENU_ID_WAP_PUSH_INBOX,
        MENU_ID_SERVICE_MSG_SETTING,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_APP_SUB,
        STR_ID_PUSH_SERVICE_MESSAGE,
        IMG_ID_WAP_PUSH_INBOX));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_WAP_PUSH_INBOX,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_INBOX,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_SERVICE_MSG_SETTING,
        0,
        2,
        MENU_ID_SERVICE_MSG_ENABLE,
        MENU_ID_SERVICE_MSG_SL_SETTING,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_APP_SUB,
        STR_ID_PUSH_INBOX_SETTING,
        IMG_BRW_PUSH_CAPTION));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_SERVICE_MSG_ENABLE,
        0,
        2,
        MENU_ID_PUSH_ENABLE_SETTING_ACCEPT_ALL,
        MENU_ID_PUSH_ENABLE_SETTING_DISABLE,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_ID_PUSH_INBOX_ENABLE_PUSH,
        IMG_BRW_PUSH_CAPTION));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_SERVICE_MSG_SL_SETTING,
        0,
        3,
        MENU_ID_PUSH_SL_SETTING_PROMPT,
        MENU_ID_PUSH_SL_SETTING_AUTO_LAUNCH,
        MENU_ID_PUSH_SL_SETTING_DISABLE,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_ID_PUSH_ENABLE_SERVICE_LOADING,
        IMG_BRW_PUSH_CAPTION));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_PUSH_ENABLE_SETTING_ACCEPT_ALL,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_PUSH_ENABLE_SETTING_ACCEPT_ALL,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_PUSH_ENABLE_SETTING_DISABLE,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_PUSH_DISABLE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_PUSH_SL_SETTING_PROMPT,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_PUSH_SL_SETTING_PROMPT,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_PUSH_SL_SETTING_AUTO_LAUNCH,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_PUSH_SL_SETTING_AUTO_LAUNCH,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_PUSH_SL_SETTING_DISABLE,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_PUSH_DISABLE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_PUSH_TB_LIVE_OPTION,
        0,
        4,
        MENU_ID_PUSH_TB_VIEW,
        MENU_ID_PUSH_TB_CALL,
        MENU_ID_PUSH_TB_DELETE,
        MENU_ID_PUSH_OP12_TOOL_BAR_SETTING,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_OPTIONS,
        IMG_GLOBAL_OPTIONS));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_PUSH_TB_LIVE_OPTION_IN_CALL,
        0,
        3,
        MENU_ID_PUSH_TB_VIEW_IN_CALL,
        MENU_ID_PUSH_TB_DELETE_IN_CALL,
        MENU_ID_PUSH_OP12_TOOL_BAR_SETTING_IN_CALL,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_OPTIONS,
        IMG_GLOBAL_OPTIONS));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_PUSH_TB_CALL,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_DIAL,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_PUSH_TB_VIEW,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_VIEW,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_PUSH_TB_VIEW_IN_CALL,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_VIEW,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_PUSH_TB_DELETE,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_DELETE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_PUSH_TB_DELETE_IN_CALL,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_DELETE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_PUSH_OP12_TOOL_BAR_SETTING,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_BRW_PUSH_TB_SETTINGS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_PUSH_OP12_TOOL_BAR_SETTING_IN_CALL,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_BRW_PUSH_TB_SETTINGS,
        0));

/******************** Menu resource IDs - finish ********************/

/******************** Menu Hilite/Hint Handlers - begin ********************/
    ADD_APPLICATION_MENUITEM_HINT_HANDLER(MENU_ID_SERVICE_MSG_ENABLE, mmi_wap_push_enable_push_hint_hdlr);
    ADD_APPLICATION_MENUITEM_HINT_HANDLER(MENU_ID_SERVICE_MSG_SL_SETTING, mmi_wap_push_sl_setting_hint_hdlr);
/******************** Menu Hilite/Hint Handlers - finish ********************/
}
