/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_app_factorymode.c
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   MTK resgenerator XML parser
 *
 *******************************************************************************/
#include "CustDataProts.h"
#include "mmi_rp_app_factorymode_def.h"

/* Application specified header files for using old res IDs */
#include "MMI_features.h"
#include "MMIDataType.h"    /* for resource base */

#include "CustResDef.h"         /* for image/audio path */
#include "GlobalMenuItems.h"    /* for menu resource */

#include "MMI_features.h"
#include "MMIDataType.h"
#include "GlobalResDef.h"
#include "SettingDefs.h"
#include "custresdef.h"


/*****************************************************************************
* FUNCTION
*  mmi_rp_app_factorymode_populate
* DESCRIPTION
*  Automatically generated populate function for mmi_rp_app_factorymode_populate
* PARAMETERS
*  void
* RETURNS
*  void
*****************************************************************************/
void mmi_rp_app_factorymode_populate(void)
{
    /*----------------------------------------------------------------*/
    /* Local Variables                                                */
    /*----------------------------------------------------------------*/

    /*----------------------------------------------------------------*/
    /* Code Body                                                      */
    /*----------------------------------------------------------------*/

/******************** Menu resource IDs - begin ********************/
    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FM_ROOT,
        0,
        15,
        MENU_ID_FM_VERSION,
        MENU_ID_FM_EACHLOOP,
        MENU_ID_FM_KEYPAD,
        MENU_ID_FM_VIBRATOR,
        MENU_ID_FM_RINGTONE,
        MENU_ID_FM_BAT_LED,
        MENU_ID_FM_LCD,
        MENU_ID_FM_ADC,
        MENU_ID_FM_HEADSET,
        MENU_ID_FM_MEMORY_CARD,
        MENU_ID_FM_GPS,
        MENU_ID_FM_RFID,
        MENU_ID_FM_PRESSURE,
        MENU_ID_FM_SENSOR,
        MENU_ID_FM_CALL,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_APP_SUB,
        STR_ID_FM_ROOT,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FM_EACHLOOP,
        MENU_ID_FM_ROOT,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_FM_EACHLOOP,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FM_KEYPAD,
        MENU_ID_FM_ROOT,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_FM_KEYPAD,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FM_VIBRATOR,
        MENU_ID_FM_ROOT,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_FM_VIBRATOR,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FM_RINGTONE,
        MENU_ID_FM_ROOT,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_RINGTONE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FM_BAT_LED,
        MENU_ID_FM_ROOT,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_FM_BAT_LED,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FM_ADC,
        MENU_ID_FM_ROOT,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_FM_ADC,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FM_HEADSET,
        MENU_ID_FM_ROOT,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_FM_HEADSET,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FM_MEMORY_CARD,
        MENU_ID_FM_ROOT,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_MEMORY_CARD,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FM_GPS,
        MENU_ID_FM_ROOT,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_FM_GPS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FM_RFID,
        MENU_ID_FM_ROOT,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_FM_RFID,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FM_PRESSURE,
        MENU_ID_FM_ROOT,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_FM_PRESSURE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FM_SENSOR,
        MENU_ID_FM_ROOT,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_FM_SENSOR,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FM_CALL,
        MENU_ID_FM_ROOT,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_FM_CALL,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FM_MISC_AUTO_TEST_SETTING,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_APP_SUB,
        STR_ID_FM_MISC_AUTO_TEST_SETTING,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FM_AUTO_TEST_OPTIONS,
        0,
        3,
        MENU_ID_FM_AUTO_TEST_ADD,
        MENU_ID_FM_AUTO_TEST_CHANGE_PRIORITY,
        MENU_ID_FM_AUTO_TEST_REMOVE,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_OPTIONS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FM_AUTO_TEST_ADD,
        MENU_ID_FM_AUTO_TEST_OPTIONS,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_FM_AUTO_TEST_ADD,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FM_AUTO_TEST_CHANGE_PRIORITY,
        MENU_ID_FM_AUTO_TEST_OPTIONS,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_FM_AUTO_TEST_CHANGE_PRIORITY,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FM_AUTO_TEST_REMOVE,
        MENU_ID_FM_AUTO_TEST_OPTIONS,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_REMOVE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FM_VERSION,
        0,
        8,
        MENU_ID_FM_IMEI,
        MENU_ID_FM_SW_VER,
        MENU_ID_FM_ISN,
        MENU_ID_FM_BBCHIP_VER,
        MENU_ID_FM_DSPCODE_VER,
        MENU_ID_FM_DSPATCH_VER,
        MENU_ID_FM_HW_VER,
        MENU_ID_FM_BUILD_TIME,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_APP_SUB,
        STR_ID_FM_VERSION,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FM_IMEI,
        MENU_ID_FM_VERSION,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_FM_IMEI,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FM_SW_VER,
        MENU_ID_FM_VERSION,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_FM_SW_VER,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FM_ISN,
        MENU_ID_FM_VERSION,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_FM_ISN,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FM_BBCHIP_VER,
        MENU_ID_FM_VERSION,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_FM_BBCHIP_VER,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FM_DSPCODE_VER,
        MENU_ID_FM_VERSION,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_FM_DSPCODE_VER,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FM_DSPATCH_VER,
        MENU_ID_FM_VERSION,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_FM_DSPATCH_VER,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FM_HW_VER,
        MENU_ID_FM_VERSION,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_FM_HW_VER,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FM_BUILD_TIME,
        MENU_ID_FM_VERSION,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_FM_BUILD_TIME,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FM_LCD,
        0,
        6,
        MENU_ID_FM_LCD_AUTO,
        MENU_ID_FM_LCD_R,
        MENU_ID_FM_LCD_G,
        MENU_ID_FM_LCD_B,
        MENU_ID_FM_LCD_W,
        MENU_ID_FM_LCD_BLACK,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_APP_SUB,
        STR_ID_FM_LCD,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FM_LCD_AUTO,
        MENU_ID_FM_LCD,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_FM_LCD_AUTO,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FM_LCD_R,
        MENU_ID_FM_LCD,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_FM_LCD_R,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FM_LCD_G,
        MENU_ID_FM_LCD,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_FM_LCD_G,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FM_LCD_B,
        MENU_ID_FM_LCD,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_FM_LCD_B,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FM_LCD_W,
        MENU_ID_FM_LCD,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_FM_LCD_W,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FM_LCD_BLACK,
        MENU_ID_FM_LCD,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_FM_LCD_BLACK,
        0));

/******************** Menu resource IDs - finish ********************/

/******************** Menu Hilite/Hint Handlers - begin ********************/
/******************** Menu Hilite/Hint Handlers - finish ********************/
}
