/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_app_ucm.c
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   MTK resgenerator XML parser
 *
 *******************************************************************************/
#include "CustDataProts.h"
#include "mmi_rp_app_ucm_def.h"

/* Application specified header files for using old res IDs */
#include "MMI_features.h"
#include "MMIDataType.h"    /* for resource base */

#include "CustResDef.h"         /* for image/audio path */
#include "GlobalMenuItems.h"    /* for menu resource */

#include "GlobalResDef.h"
#include "mmi_rp_app_ucm_def.h"
#include "ConnectivityResDef.h"
#include "mmi_rp_srv_editor_def.h"
#include "mmi_rp_app_mainmenu_def.h"


/*****************************************************************************
* FUNCTION
*  mmi_rp_app_ucm_populate
* DESCRIPTION
*  Automatically generated populate function for mmi_rp_app_ucm_populate
* PARAMETERS
*  void
* RETURNS
*  void
*****************************************************************************/
void mmi_rp_app_ucm_populate(void)
{
    /*----------------------------------------------------------------*/
    /* Local Variables                                                */
    /*----------------------------------------------------------------*/

    /*----------------------------------------------------------------*/
    /* Code Body                                                      */
    /*----------------------------------------------------------------*/

/******************** Menu resource IDs - begin ********************/
    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UCM_OUTGOING_OPTION,
        0,
        3,
        MENU_ID_UCM_OUTGOING_OPTION_DIALER,
        MENU_ID_UCM_OUTGOING_OPTION_HAND_HELD,
        MENU_ID_UCM_OUTGOING_OPTION_HAND_FREE,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_OPTIONS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UCM_INCOMING_OPTION,
        0,
        7,
        MENU_ID_UCM_INCOMING_OPTION_ANSWER,
        MENU_ID_UCM_INCOMING_OPTION_DIALER,
        MENU_ID_UCM_INCOMING_OPTION_DEFLECT,
        MENU_ID_UCM_INCOMING_OPTION_REPLACE,
        MENU_ID_UCM_INCOMING_OPTION_END_ALL_ACTIVE,
        MENU_ID_UCM_INCOMING_OPTION_END_ALL_HELD,
        MENU_ID_UCM_INCOMING_OPTION_REJ_BY_SMS,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_OPTIONS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UCM_INCALL_OPTION,
        0,
        14,
        MENU_ID_UCM_INCALL_OPTION_HOLD,
        MENU_ID_UCM_INCALL_OPTION_RETRIEVE,
        MENU_ID_UCM_INCALL_OPTION_SWAP,
        MENU_ID_UCM_INCALL_OPTION_CONF,
        MENU_ID_UCM_INCALL_OPTION_SPLIT,
        MENU_ID_UCM_INCALL_OPTION_END_SINGLE,
        MENU_ID_UCM_INCALL_OPTION_END_CONF,
        MENU_ID_UCM_INCALL_OPTION_END_ALL,
        MENU_ID_UCM_INCALL_OPTION_TRANSFER,
        MENU_ID_UCM_INCALL_OPTION_NEW_CALL,
        MENU_ID_UCM_INCALL_OPTION_MAIN_MENU,
        MENU_ID_UCM_INCALL_OPTION_SOUND_RECORDER,
        MENU_ID_UCM_INCALL_OPTION_DTMF,
        MENU_ID_UCM_INCALL_OPTION_SPEAKER_VOLUME,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_OPTIONS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UCM_OUTGOING_OPTION_DIALER,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_UCM_DIALER,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UCM_OUTGOING_OPTION_HAND_HELD,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_UCM_HAND_HELD,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UCM_OUTGOING_OPTION_HAND_FREE,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_UCM_HAND_FREE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UCM_INCOMING_OPTION_ANSWER,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_UCM_ANSWER,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UCM_INCOMING_OPTION_DIALER,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_UCM_DIALER,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UCM_INCOMING_OPTION_DEFLECT,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_UCM_DEFLECT,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UCM_INCOMING_OPTION_REPLACE,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_REPLACE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UCM_INCOMING_OPTION_END_ALL_ACTIVE,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_UCM_END_ALL_ACTIVE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UCM_INCOMING_OPTION_END_ALL_HELD,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_UCM_END_ALL_HELD,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UCM_INCOMING_OPTION_REJ_BY_SMS,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_UCM_REJ_BY_SMS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UCM_INCALL_OPTION_HOLD,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_UCM_HOLD,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UCM_INCALL_OPTION_RETRIEVE,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_UCM_RETRIEVE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UCM_INCALL_OPTION_SWAP,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_UCM_SWAP,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UCM_INCALL_OPTION_CONF,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_UCM_CONFERENCE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UCM_INCALL_OPTION_SPLIT,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_UCM_SPLIT,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UCM_INCALL_OPTION_END_SINGLE,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_UCM_END_SINGLE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UCM_INCALL_OPTION_END_CONF,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_UCM_END_CONFERENCE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UCM_INCALL_OPTION_END_ALL,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_UCM_END_ALL,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UCM_INCALL_OPTION_TRANSFER,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_UCM_TRANSFER,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UCM_INCALL_OPTION_NEW_CALL,
        0,
        1,
        MENU_ID_UCM_INCALL_OPTION_NEW_CALL_VOICE,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_ID_UCM_NEW_CALL,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UCM_INCALL_OPTION_MAIN_MENU,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_UCM_MAIN_MENU,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UCM_INCALL_OPTION_SOUND_RECORDER,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_UCM_SOUND_RECORDER,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UCM_INCALL_OPTION_DTMF,
        0,
        2,
        MENU_ID_UCM_INCALL_OPTION_DTMF_ON,
        MENU_ID_UCM_INCALL_OPTION_DTMF_OFF,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_ID_UCM_DTMF,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UCM_INCALL_OPTION_DTMF_ON,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_ON,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UCM_INCALL_OPTION_DTMF_OFF,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_OFF,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UCM_INCALL_OPTION_SPEAKER_VOLUME,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_VOLUME,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UCM_INCALL_OPTION_NEW_CALL_VOICE,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_UCM_VOICE_CALL,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UCM_NEW_CALL_OPTION,
        0,
        2,
        MENU_ID_UCM_NEW_CALL_OPTION_DIAL,
        MENU_ID_UCM_NEW_CALL_OPTION_SAVE,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_OPTIONS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UCM_NEW_CALL_OPTION_DIAL,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_DIAL,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UCM_NEW_CALL_OPTION_SAVE,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_SAVE_TO_PHONEBOOK,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UCM_IN_CALL_DIALER_OPTION,
        0,
        2,
        MENU_ID_UCM_IN_CALL_DIALER_OPTION_DIAL,
        MENU_ID_UCM_IN_CALL_DIALER_OPTION_SAVE,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_OPTIONS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UCM_IN_CALL_DIALER_OPTION_DIAL,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_DIAL,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UCM_IN_CALL_DIALER_OPTION_SAVE,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_SAVE_TO_PHONEBOOK,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UCM_CALL_TYPE,
        0,
        1,
        MENU_ID_UCM_CALL_TYPE_VOICE,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_DIAL,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UCM_CALL_TYPE_VOICE,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_UCM_VOICE_CALL,
        0));

/******************** Menu resource IDs - finish ********************/

/******************** Menu Hilite/Hint Handlers - begin ********************/
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_UCM_CALL_TYPE_VOICE, mmi_ucm_highlight_call_type_voice);
/******************** Menu Hilite/Hint Handlers - finish ********************/
}
