
#include "mmi_features.h"
#include "custresdef.h"

<?xml version = "1.0" encoding = "UTF-8"?>

#define RES_IMG_CAL_BUTTON_PATH    RES_THEME_ROOT"\\\\Default\\\\Calendar\\\\Button\\\\"
#define RES_IMG_CAL_LISTICON_PATH   RES_THEME_ROOT"\\\\Default\\\\Calendar\\\\ListIcon\\\\"
#define RES_IMG_CAL_REMINDER_PATH    RES_THEME_ROOT"\\\\Default\\\\Calendar\\\\Reminder\\\\"
#define RES_IMG_THEME1_PATH         RES_THEME_ROOT"\\\\Theme1\\\\Calendar\\\\"

#ifndef __MMI_CAL_SLIM__
#define __MMI_TASK_APP__
#define __MMI_CAL_EXPIRY__
#define __MMI_CAL_FUNCBAR__
#endif


<APP id="VAPP_CALENDAR" package_name="native.mtk.calendar" name="STR_ID_VAPP_CALENDAR" img="IMG_ID_VAPP_CALENDAR" launch="vapp_calendar_launch" type="venus">


    <INCLUDE file = "GlobalResDef.h"/> 

    <MEMORY heap="550*1024" cui="VCUI_BT_SEND_PREPARE" vrt_mem_factor = "2.0"/>

    <!----------------------------------------------------- string resource ---------------------------------------------------------->
    <STRING id="STR_ID_VAPP_CALENDAR"/>
    #ifdef __MMI_VCALENDAR__
    <STRING id="STR_ID_VAPP_CAL_VCALENDAR"/>  
    <STRING id="STR_ID_VAPP_CAL_SHARE"/>
    <STRING id="STR_ID_VAPP_CAL_SHARE_CAL"/> 
    <STRING id="STR_ID_VAPP_CAL_BY_SMS"/> 
    <STRING id="STR_ID_VAPP_CAL_BY_MMS"/> 
    <STRING id="STR_ID_VAPP_CAL_BY_EMAIL"/> 
    <STRING id="STR_ID_VAPP_CAL_BY_BT"/> 
    <STRING id="STR_ID_VAPP_CAL_SAVE_TO_CAL"/> 
    <STRING id="STR_ID_VAPP_CAL_UNSUPPORT_FORMAT"/>
    #endif
    <STRING id="STR_ID_VAPP_CAL_CHINESE_CHU"/>
    <STRING id="STR_ID_VAPP_CAL_CHINESE_NO1"/>
    <STRING id="STR_ID_VAPP_CAL_CHINESE_NO2"/>
    <STRING id="STR_ID_VAPP_CAL_CHINESE_NO3"/>
    <STRING id="STR_ID_VAPP_CAL_CHINESE_NO4"/>
    <STRING id="STR_ID_VAPP_CAL_CHINESE_NO5"/>
    <STRING id="STR_ID_VAPP_CAL_CHINESE_NO6"/>
    <STRING id="STR_ID_VAPP_CAL_CHINESE_NO7"/>
    <STRING id="STR_ID_VAPP_CAL_CHINESE_NO8"/>
    <STRING id="STR_ID_VAPP_CAL_CHINESE_NO9"/>
    <STRING id="STR_ID_VAPP_CAL_CHINESE_NO10"/>
    <STRING id="STR_ID_VAPP_CAL_CHINESE_NO20"/>
    <STRING id="STR_ID_VAPP_CAL_CHINESE_NO30"/>
    <STRING id="STR_ID_VAPP_CAL_SOLARTERM1"/>
    <STRING id="STR_ID_VAPP_CAL_SOLARTERM2"/>
    <STRING id="STR_ID_VAPP_CAL_SOLARTERM3"/>
    <STRING id="STR_ID_VAPP_CAL_SOLARTERM4"/>
    <STRING id="STR_ID_VAPP_CAL_SOLARTERM5"/>
    <STRING id="STR_ID_VAPP_CAL_SOLARTERM6"/>
    <STRING id="STR_ID_VAPP_CAL_SOLARTERM7"/>
    <STRING id="STR_ID_VAPP_CAL_SOLARTERM8"/>
    <STRING id="STR_ID_VAPP_CAL_SOLARTERM9"/>
    <STRING id="STR_ID_VAPP_CAL_SOLARTERM10"/>
    <STRING id="STR_ID_VAPP_CAL_SOLARTERM11"/>
    <STRING id="STR_ID_VAPP_CAL_SOLARTERM12"/>
    <STRING id="STR_ID_VAPP_CAL_SOLARTERM13"/>
    <STRING id="STR_ID_VAPP_CAL_SOLARTERM14"/>
    <STRING id="STR_ID_VAPP_CAL_SOLARTERM15"/>
    <STRING id="STR_ID_VAPP_CAL_SOLARTERM16"/>
    <STRING id="STR_ID_VAPP_CAL_SOLARTERM17"/>
    <STRING id="STR_ID_VAPP_CAL_SOLARTERM18"/>
    <STRING id="STR_ID_VAPP_CAL_SOLARTERM19"/>
    <STRING id="STR_ID_VAPP_CAL_SOLARTERM20"/>
    <STRING id="STR_ID_VAPP_CAL_SOLARTERM21"/>
    <STRING id="STR_ID_VAPP_CAL_SOLARTERM22"/>
    <STRING id="STR_ID_VAPP_CAL_SOLARTERM23"/>
    <STRING id="STR_ID_VAPP_CAL_SOLARTERM24"/>
    #ifndef __MMI_CAL_SLIM__
    <STRING id="STR_ID_VAPP_CAL_KAN1"/>
    <STRING id="STR_ID_VAPP_CAL_KAN2"/>
    <STRING id="STR_ID_VAPP_CAL_KAN3"/>
    <STRING id="STR_ID_VAPP_CAL_KAN4"/>
    <STRING id="STR_ID_VAPP_CAL_KAN5"/>
    <STRING id="STR_ID_VAPP_CAL_KAN6"/>
    <STRING id="STR_ID_VAPP_CAL_KAN7"/>
    <STRING id="STR_ID_VAPP_CAL_KAN8"/>
    <STRING id="STR_ID_VAPP_CAL_KAN9"/>
    <STRING id="STR_ID_VAPP_CAL_KAN10"/>
    <STRING id="STR_ID_VAPP_CAL_CHI1"/>
    <STRING id="STR_ID_VAPP_CAL_CHI2"/>
    <STRING id="STR_ID_VAPP_CAL_CHI3"/>
    <STRING id="STR_ID_VAPP_CAL_CHI4"/>
    <STRING id="STR_ID_VAPP_CAL_CHI5"/>
    <STRING id="STR_ID_VAPP_CAL_CHI6"/>
    <STRING id="STR_ID_VAPP_CAL_CHI7"/>
    <STRING id="STR_ID_VAPP_CAL_CHI8"/>
    <STRING id="STR_ID_VAPP_CAL_CHI9"/>
    <STRING id="STR_ID_VAPP_CAL_CHI10"/>
    <STRING id="STR_ID_VAPP_CAL_CHI11"/>
    <STRING id="STR_ID_VAPP_CAL_CHI12"/>
    #endif
    <STRING id="STR_ID_VAPP_CAL_LEAP"/>
    <STRING id="STR_ID_VAPP_CAL_MONTH"/>
    <STRING id="STR_ID_VAPP_CAL_WEEK"/>
    <STRING id="STR_ID_VAPP_CAL_DAY"/>  
    <STRING id="STR_ID_VAPP_CAL_MONTH_SHORT"/>
    <STRING id="STR_ID_VAPP_CAL_WEEK_SHORT"/>
    <STRING id="STR_ID_VAPP_CAL_DAY_SHORT"/> 
    <STRING id="STR_ID_VAPP_CAL_WEEK_SUN"/>
    <STRING id="STR_ID_VAPP_CAL_WEEK_MON"/>
    <STRING id="STR_ID_VAPP_CAL_WEEK_TUE"/>
    <STRING id="STR_ID_VAPP_CAL_WEEK_WED"/>
    <STRING id="STR_ID_VAPP_CAL_WEEK_THU"/>
    <STRING id="STR_ID_VAPP_CAL_WEEK_FRI"/>
    <STRING id="STR_ID_VAPP_CAL_WEEK_SAT"/>
    <STRING id="STR_ID_VAPP_CAL_WEEK_SUNDAY"/>
    <STRING id="STR_ID_VAPP_CAL_WEEK_MONDAY"/>
    <STRING id="STR_ID_VAPP_CAL_WEEK_TUESDAY"/>
    <STRING id="STR_ID_VAPP_CAL_WEEK_WEDESDAY"/>
    <STRING id="STR_ID_VAPP_CAL_WEEK_THURSDAY"/>
    <STRING id="STR_ID_VAPP_CAL_WEEK_FRIDAY"/>
    <STRING id="STR_ID_VAPP_CAL_WEEK_SATURDAY"/>
    <STRING id="STR_ID_VAPP_CAL_ADD"/>
    <STRING id="STR_ID_VAPP_CAL_EDIT"/>    
    <STRING id="STR_ID_VAPP_CAL_EDIT_EVT"/>
    <STRING id="STR_ID_VAPP_CAL_SAVE"/>
    <STRING id="STR_ID_VAPP_CAL_CANCEL"/>
    <STRING id="STR_ID_VAPP_CAL_SUBJECT"/>
    <STRING id="STR_ID_VAPP_CAL_START"/>    
    <STRING id="STR_ID_VAPP_CAL_TO"/>
    <STRING id="STR_ID_VAPP_CAL_ALL_DAY"/>
    <STRING id="STR_ID_VAPP_CAL_CATEGORY"/>
    <STRING id="STR_ID_VAPP_CAL_REMINDER"/>
    <STRING id="STR_ID_VAPP_CAL_REPEATITION"/>
    <STRING id="STR_ID_VAPP_CAL_LOC"/>
    <STRING id="STR_ID_VAPP_CAL_NOTE"/>  
    <STRING id="STR_ID_VAPP_CAL_PERSONAL"/> 
    <STRING id="STR_ID_VAPP_CAL_MEETING"/> 
    <STRING id="STR_ID_VAPP_CAL_SPEC_DAY"/>
    <STRING id="STR_ID_VAPP_CAL_BIRTHDAY"/>  
    <STRING id="STR_ID_VAPP_CAL_OTHERS"/>
    <STRING id="STR_ID_VAPP_CAL_NEVER"/> 
    <STRING id="STR_ID_VAPP_CAL_DAILY"/> 
    <STRING id="STR_ID_VAPP_CAL_WEEKDAY"/> 
    <STRING id="STR_ID_VAPP_CAL_WEEKLY"/> 
    <STRING id="STR_ID_VAPP_CAL_MONTHLY"/> 
    <STRING id="STR_ID_VAPP_CAL_YEARLY"/>
    <STRING id="STR_ID_VAPP_CAL_5MIN_EARLIER"/> 
    <STRING id="STR_ID_VAPP_CAL_15MIN_EARLIER"/> 
    <STRING id="STR_ID_VAPP_CAL_30MIN_EARLIER"/> 
    <STRING id="STR_ID_VAPP_CAL_1H_EARLIER"/> 
    <STRING id="STR_ID_VAPP_CAL_1D_EARLIER"/> 
    <STRING id="STR_ID_VAPP_CAL_3D_EARLIER"/> 
    <STRING id="STR_ID_VAPP_CAL_1W_EARLIER"/> 
    <STRING id="STR_ID_VAPP_CAL_EVENTS"/> 
    <STRING id="STR_ID_VAPP_CAL_DELETE"/> 
    <STRING id="STR_ID_VAPP_CAL_DELETE_EVT"/> 
    <STRING id="STR_ID_VAPP_CAL_DELETE_ONE_EVT"/>
    <STRING id="STR_ID_VAPP_CAL_MARK_ALL"/> 
    <STRING id="STR_ID_VAPP_CAL_UNMARK_ALL"/>
    <STRING id="STR_ID_VAPP_CAL_DELETE_EVENT_ASK"/> 
    <STRING id="STR_ID_VAPP_CAL_DELETE_ALL_REPEAT_ASK"/>
    <STRING id="STR_ID_VAPP_CAL_EVT_SAVED"/> 
    <STRING id="STR_ID_VAPP_CAL_ADD_EVT"/> 
    #ifndef __MMI_CAL_SLIM__
    <STRING id="STR_ID_VAPP_CAL_HIGH"/> 
    <STRING id="STR_ID_VAPP_CAL_MEDIUM"/> 
    <STRING id="STR_ID_VAPP_CAL_LOW"/> 
    <STRING id="STR_ID_VAPP_CAL_TASKS"/>
    <STRING id="STR_ID_VAPP_CAL_SHARE_TASK"/>
    <STRING id="STR_ID_VAPP_CAL_DELETE_TASKS"/>
    <STRING id="STR_ID_VAPP_TASK_DELETE_TASK_TITLE"/>
    <STRING id="STR_ID_VAPP_CAL_NO_TASK"/>
    <STRING id="STR_ID_VAPP_CAL_TASK_SAVED"/>  
    <STRING id="STR_ID_VAPP_CAL_SAVE_TO_TASK"/> 
    <STRING id="STR_ID_VAPP_CAL_ADD_TASK"/> 
    <STRING id="STR_ID_VAPP_CAL_PRIORITY"/>
    <STRING id="STR_ID_VAPP_CAL_EDIT_TASK"/>
    <STRING id="STR_ID_VAPP_CAL_DELETE_ONE_TASK"/>
    <STRING id="STR_ID_VAPP_CAL_DELETE_TASK"/>
    <STRING id="STR_ID_VAPP_CAL_DELETE_EXPIRED_EVENTS"/> 
    <STRING id="STR_ID_VAPP_CAL_EXPIRED"/>
    <STRING id="STR_ID_VAPP_CAL_SELECT_EXPIRED"/> 
    <STRING id="STR_ID_VAPP_CAL_BIR_POSTFIX"/>
    <STRING id="STR_ID_VAPP_CAL_SEARCH"/>
    <STRING id="STR_ID_VAPP_CAL_PREV"/>
    <STRING id="STR_ID_VAPP_CAL_NEXT"/>
    #endif
    <STRING id="STR_ID_VAPP_CAL_ENDTIME_CHECK_NOTE"/> 
    <STRING id="STR_ID_VAPP_CAL_SNOOZE"/> 
    <STRING id="STR_ID_VAPP_CAL_DIMISS"/> 
    <STRING id="STR_ID_VAPP_CAL_JUMP_TO_DATE"/> 
    <STRING id="STR_ID_VAPP_CAL_NO_EVTS"/> 
    <STRING id="STR_ID_VAPP_CAL_OLD_EVT"/>
    <STRING id="STR_ID_VAPP_CAL_INCOMING_EVT"/>
    <STRING id="STR_ID_VAPP_CAL_TODAY"/>
    <STRING id="STR_ID_VAPP_CAL_GO"/>
    <STRING id="STR_ID_VAPP_CAL_ALARM_EXPIRED"/>
    <STRING id="STR_ID_VAPP_CAL_ALARM_EXPIRED_SHORT"/>
    <STRING id="STR_ID_VAPP_CAL_NO_CONTENT"/>
    <STRING id="STR_ID_VAPP_CAL_DATE"/>
    <STRING id="STR_ID_VAPP_CAL_DUE_TO"/>
    <STRING id="STR_ID_VAPP_CAL_DATE_SETTING"/>
    <STRING id="STR_ID_VAPP_CAL_TIME_SETTING"/>
    <STRING id="STR_ID_VAPP_CAL_YEAE_BEYOND_MIN"/>
    <STRING id="STR_ID_VAPP_CAL_YEAE_BEYOND_MAX"/>
    <STRING id="STR_ID_VAPP_CAL_MEM_FULL"/>
    <STRING id="STR_ID_VAPP_CAL_REMINDER_DISMISS"/> 
    <STRING id="STR_ID_VAPP_CAL_REMINDER_SNOOZE"/> 
    <STRING id="STR_ID_VAPP_CAL_LEFT_PARENTHESES"/>
    <STRING id="STR_ID_VAPP_CAL_RIGHT_PARENTHESES"/>
    <STRING id="STR_ID_VAPP_CAL_QUESTION_MARK"/>
    <STRING id="STR_ID_VAPP_CAL_DELETE_EVENT_TITLE"/>
    <STRING id="STR_ID_VAPP_CAL_SNOOZE_4MIN"/>
    <STRING id="STR_ID_VAPP_CAL_LOADING"/> 
    <STRING id="STR_ID_VAPP_CAL_LOCAL"/>
    <STRING id="STR_ID_VAPP_CAL_ALL"/>
    
 
    <!----------------------------------------------------- Image resource ---------------------------------------------------------->
    #ifdef __MMI_TASK_APP__
    <IMAGE id="IMG_ID_VAPP_CAL_LOW">RES_IMG_CAL_LISTICON_PATH"Low.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAL_MEDIUM">RES_IMG_CAL_LISTICON_PATH"Medium.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAL_HIGH">RES_IMG_CAL_LISTICON_PATH"High.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAL_TASK_UNDO">RES_IMG_CAL_BUTTON_PATH"Task_Undo.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAL_TASK_DONE">RES_IMG_CAL_BUTTON_PATH"Task_Done.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAL_TASK_REMINDER">RES_IMG_CAL_LISTICON_PATH"Task.png"</IMAGE>
    #endif
    <IMAGE id="IMG_ID_VAPP_CAL_PERSONAL">RES_IMG_CAL_LISTICON_PATH"Personal.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAL_MEETING">RES_IMG_CAL_LISTICON_PATH"Meeting.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAL_SPECIAL">RES_IMG_CAL_LISTICON_PATH"Special_Day.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAL_BIRTHDAY">RES_IMG_CAL_LISTICON_PATH"Birthday.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAL_OTHER">RES_IMG_CAL_LISTICON_PATH"Others.png"</IMAGE>
    
    #ifdef __MMI_SNS_CALENDAR__
    <IMAGE id="IMG_ID_VAPP_CAL_LOCAL">RES_IMG_CAL_LISTICON_PATH"Local.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAL_ALL">RES_IMG_CAL_LISTICON_PATH"ALL.png"</IMAGE>
    #endif
   

    #ifdef __MMI_CAL_EXPIRY__
    <IMAGE id="IMG_ID_VAPP_CAL_EXPIRED">RES_THEME_ROOT"\\\\Default\\\\Calendar\\\ToolbarIcon\\\\Expired.png"</IMAGE>
    #endif
    
    #ifdef __MMI_VCALENDAR__
    <IMAGE id="IMG_ID_VAPP_CAL_VCALENDAR">RES_IMG_ROOT"\\\\Message\\\\ListIcon\\\\Vcalendar_File.png"</IMAGE>
    #endif
   
    #ifndef __LOW_COST_SUPPORT_COMMON__
    <IMAGE id="IMG_ID_VAPP_CAL_REMINDER_CARD_BG">RES_IMG_CAL_REMINDER_PATH"BG_N.9slice.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAL_REMINDER_ARROW_UP">RES_IMG_CAL_REMINDER_PATH"Arrow_Up.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAL_REMINDER_ARROW_DOWN">RES_IMG_CAL_REMINDER_PATH"Arrow_Down.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAL_REMINDER_CARD_SHADOW_UP">RES_IMG_CAL_REMINDER_PATH"BG_H_Up.9slice.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAL_REMINDER_CARD_SHADOW_DOWN">RES_IMG_CAL_REMINDER_PATH"BG_H_Down.9slice.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAL_REMINDER_CARD_SHADOW_MID">RES_IMG_CAL_REMINDER_PATH"BG_H_Middle.9slice.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAL_REMINDER_SHADOW_UP">RES_IMG_CAL_REMINDER_PATH"Shadow_Up.9slice.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAL_REMINDER_SHADOW_DOWN">RES_IMG_CAL_REMINDER_PATH"Shadow_Down.9slice.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAL_REMINDER_CARD_ARROW_UP">RES_IMG_CAL_REMINDER_PATH"Triangle_Up.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAL_REMINDER_CARD_ARROW_DOWN">RES_IMG_CAL_REMINDER_PATH"Triangle_Down.png"</IMAGE>
    #endif

    <!----------------------------------------------------- Callback manager ---------------------------------------------------------->
    <RECEIVER id="EVT_ID_SRV_REMINDER_NOTIFY" proc="vapp_cal_reminder_notify_proc"/>   
    #if defined(__MMI_TASK_APP__)
	<RECEIVER id="EVT_ID_SRV_TDL_OP" proc="vapp_cal_reminder_set_proc"/>	
	#endif
    <RECEIVER id="EVT_ID_SRV_TDL_EVENT_OP" proc="vapp_cal_event_reminder_set_proc"/>




    <!------------------------------------------------------ File Type ----------------------------------------------------------->
    #ifdef __MMI_VCALENDAR__ 
    <MENU id="MENU_ID_VAPP_CAL_OPEN_FROM_FMG" type="OPTION" str="STR_GLOBAL_OPTIONS">
        <MENUITEM id="MENU_ID_VAPP_CAL_VIEW_FROM_FMG_LAUNCH" str="STR_GLOBAL_OPEN"/>
    </MENU>
    
	<FILE_TYPES>
    	<FILE_OPTION_HDLR option = "MENU_ID_VAPP_CAL_VIEW_FROM_FMG_LAUNCH" handler = "vapp_cal_view_detail_from_FMGR_launch"/>
	    <FILE_TYPE type_id="FMGR_TYPE_VCS" extension="VCS" small_icon="IMG_ID_VAPP_CAL_VCALENDAR" large_icon="IMG_ID_VAPP_CAL_VCALENDAR" option="MENU_ID_VAPP_CAL_OPEN_FROM_FMG"/>
    </FILE_TYPES>
    #endif

	<THEME>

    <IMAGE id="IMG_ID_VAPP_CALENDAR" desc="Main menu calendar icon">RES_IMG_ROOT"\\\\"__MMI_MAINMENU_ICON_DEFAULT_PATH__"\\\\Calendar.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAL_DATE_BG" desc="data bg image"></IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAL_DAY_SELECT" desc="day selectimage"></IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAL_TIPS" desc="tips image"></IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAL_TITLE_BG" desc="title bg image"></IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAL_TITLE2_BG" desc="title2 bg image"></IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAL_TODAY" desc="today bg image"></IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAL_WEEK_BG" desc="weekly bg image"></IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAL_REMINDER" desc="reminder hint image"></IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAL_REPEAT" desc="repeat hint image"></IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CAL_PICKER_SEPERATOR" desc="picker seperator image"></IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAL_LEFT_ARROW" desc="Arrow Left image"></IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAL_RIGHT_ARROW" desc="Arrow Right image"></IMAGE>  
   
    <COLOR id="VCP_COL_VAPP_CAL_EVENT_COLOR" desc="color of cell having event"/>  
    <COLOR id="VCP_COL_VAPP_CAL_WEEK_CELL_COLOR" desc="color of cell"/>
	</THEME>
	
</APP>

<APP id="VAPP_CALENDAR_REMINDER" name="STR_ID_VAPP_CALENDAR_REMINDER" type="venus">
    <MEMORY base="0" />
    <STRING id="STR_ID_VAPP_CALENDAR_REMINDER">"Calendar"</STRING>
</APP>



