/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_app_mot_def.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   MTK resgenerator XML parser
 *
 *******************************************************************************/


#ifndef _MMI_RP_APP_MOT_DEF_H
#define _MMI_RP_APP_MOT_DEF_H




/******************** Menu resource IDs - begin ********************/
typedef enum
{
    MENU_ID_MOT_APP = 46868 + 1, /* BASE_ID + 1 */
    MENU_ID_MOT_CATEGORY_LIST_OPEN,
    MENU_ID_MOT_CATEGORY_LIST_REFRESH,
    MENU_ID_MOT_CATEGORY_LIST_OPTIONS,
    MENU_ID_MOT_VIDEO_LIST_PLAY_VIDEO,
    MENU_ID_MOT_VIDEO_LIST_DETAILS,
    MENU_ID_MOT_VIDEO_LIST_OPTIONS,
    MMI_RP_APP_MOT_MENU_MAX
}mmi_rp_app_mot_menu_enum;
/******************** Menu resource IDs - finish ********************/


/******************** String resource IDs - begin ********************/
typedef enum
{
    STR_ID_MOT_APP_NAME = 46868 + 1, /* BASE_ID + 1 */
    STR_ID_MOT_DURATION,
    STR_ID_MOT_UNKNOWN_FILENAME,
    STR_ID_MOT_UNKNOWN_CLASS,
    STR_ID_MOT_FILENAME,
    STR_ID_MOT_MOVIE_NAME,
    STR_ID_MOT_STARRING,
    STR_ID_MOT_YEAR,
    STR_ID_MOT_PLOT,
    STR_ID_MOT_CATEGORY,
    MMI_RP_APP_MOT_STR_MAX
}mmi_rp_app_mot_str_enum;
/******************** String resource IDs - finish ********************/


/******************** Screen resource IDs - begin ********************/
typedef enum
{
    GRP_ID_MOT = 46868 + 1, /* BASE_ID + 1 */
    GRP_ID_MOT_VIDEO_CATEGORY,
    GRP_ID_MOT_VIDEO_DETAILS,
    SCR_ID_MOT_WAITING_SCREEN,
    SCR_ID_MOT_VIDEO_CAT_LIST,
    SCR_ID_MOT_VIDEO_LIST,
    SCR_ID_MOT_VIDEO_DETAILS,
    MMI_RP_APP_MOT_SCR_MAX
}mmi_rp_app_mot_scr_enum;
/******************** Screen resource IDs - finish ********************/
/******************** Template resource IDs - Begin ********************/
/******************** Template resource IDs - End ********************/

/******************** Venus XML resource IDs - Begin ********************/
typedef enum 
{

    MMI_RP_APP_MOT_VXML_LAYOUT_MAX
} mmi_rp_app_mot_vxml_layout_enum;
/******************** Venus XML resource IDs - End ********************/



/******************** Image resource IDs - begin ********************/
typedef enum
{
    IMG_ID_MOT_APP_ICON = 46868 + 1, /* BASE_ID + 1 */
    IMG_ID_MOT_DEFAULT_THUMBNAIL,
    MMI_RP_APP_MOT_IMG_MAX
}mmi_rp_app_mot_img_enum;
/******************** Image resource IDs - finish ********************/


#endif /* _MMI_RP_APP_MOT_DEF_H */
