/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_app_imageviewer_def.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   MTK resgenerator XML parser
 *
 *******************************************************************************/


#ifndef _MMI_RP_APP_IMAGEVIEWER_DEF_H
#define _MMI_RP_APP_IMAGEVIEWER_DEF_H




/******************** Menu resource IDs - begin ********************/
typedef enum
{
    MENU_ID_IMGVIEW_APP = 35211 + 1, /* BASE_ID + 1 */
    MENU_ID_IMGVIEW_VIEW_DETAIL,
    MENU_ID_IMGVIEW_VIEW_STYLE_LIST,
    MENU_ID_IMGVIEW_VIEW_STYLE_MATRIX,
    MENU_ID_IMGVIEW_VIEW_STYLE,
    MENU_ID_IMGVIEW_STORAGE,
    MENU_ID_IMGVIEW_VIEW_OPTION_PLAY,
    MENU_ID_IMGVIEW_VIEW_OPTION_ROTATE_VIEW,
    MENU_ID_IMGVIEW_VIEW_OPTION_USE,
    MENU_ID_IMGVIEW_VIEW_OPTION_SEND,
    MENU_ID_IMGVIEW_VIEW_OPTION_INFO,
    MENU_ID_IMGVIEW_VIEW_OPTION,
    MENU_ID_IMGVIEW_OPTION_IMG_INFORMATION,
    MENU_ID_IMGVIEW_OPTION_IMG_VIEW,
    MENU_ID_IMGVIEW_FILE_OPTION,
    MENU_ID_IMGVIEW_EMPTY_FOLDER_OPTION,
    MMI_RP_APP_IMAGEVIEWER_MENU_MAX
}mmi_rp_app_imageviewer_menu_enum;
/******************** Menu resource IDs - finish ********************/


/******************** String resource IDs - begin ********************/
typedef enum
{
    STR_ID_IMGVIEW_NAME = 35211 + 1, /* BASE_ID + 1 */
    STR_ID_IMGVIEW_ROTATE_VIEW,
    STR_ID_IMGVIEW_VIEW_STYLE,
    STR_ID_IMGVIEW_VIEW_STYLE_LIST,
    STR_ID_IMGVIEW_VIEW_STYLE_MATRIX,
    STR_ID_IMGVIEW_OPTION_IMG_INFO,
    STR_ID_IMGVIEW_OPTION_IMG_INFO_FILENAME,
    STR_ID_IMGVIEW_OPTION_IMG_INFO_RESOLUTION,
    STR_ID_IMGVIEW_OPTION_IMG_INFO_SIZE,
    STR_ID_IMGVIEW_OPTION_IMG_INFO_CREATE_TIME,
    MMI_RP_APP_IMAGEVIEWER_STR_MAX
}mmi_rp_app_imageviewer_str_enum;
/******************** String resource IDs - finish ********************/


/******************** Screen resource IDs - begin ********************/
typedef enum
{
    SCR_ID_IMGVIEW_VIEW = 35211 + 1, /* BASE_ID + 1 */
    SCR_ID_IMGVIEW_IMG_INFO,
    MMI_RP_APP_IMAGEVIEWER_SCR_MAX
}mmi_rp_app_imageviewer_scr_enum;
/******************** Screen resource IDs - finish ********************/
/******************** Template resource IDs - Begin ********************/
/******************** Template resource IDs - End ********************/

/******************** Venus XML resource IDs - Begin ********************/
typedef enum 
{

    MMI_RP_APP_IMAGEVIEWER_VXML_LAYOUT_MAX
} mmi_rp_app_imageviewer_vxml_layout_enum;
/******************** Venus XML resource IDs - End ********************/



/******************** MMI Cache IDs - Begin ********************/
typedef enum
{
    NVRAM_IMGVIEW_VIEW_SYTLE = 35211 + 1, /* BASE_ID + 1 */     /*         BYTE */ 
    NVRAM_IMGVIEW_STORAGE,                                      /*        SHORT */ 
    MMI_RP_APP_IMAGEVIEWER_MMI_CACHE_MAX
} mmi_rp_app_imageviewer_mmi_cache_enum;
/******************** MMI Cache IDs - End ********************/


/******************** Image resource IDs - begin ********************/
typedef enum
{
    IMG_ID_IMGVIEW_MAIN_ICON = 35211 + 1, /* BASE_ID + 1 */
    IMG_ID_IV_ERROR,
    IMG_ID_IV_LOAD,
    IMG_ID_IV_ERROR_NO_RIGHT,
    MMI_RP_APP_IMAGEVIEWER_IMG_MAX
}mmi_rp_app_imageviewer_img_enum;
/******************** Image resource IDs - finish ********************/


#endif /* _MMI_RP_APP_IMAGEVIEWER_DEF_H */
