/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_app_soundrecorder_def.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   MTK resgenerator XML parser
 *
 *******************************************************************************/


#ifndef _MMI_RP_APP_SOUNDRECORDER_DEF_H
#define _MMI_RP_APP_SOUNDRECORDER_DEF_H




/******************** Menu resource IDs - begin ********************/
typedef enum
{
    MENU_ID_SNDREC_MAIN = 35554 + 1, /* BASE_ID + 1 */
    MENU_ID_SNDREC_NEW_RECORD,
    MENU_ID_SNDREC_RECORD_PLAY,
    MENU_ID_SNDREC_APPEND,
    MENU_ID_SNDREC_RENAME,
    MENU_ID_SNDREC_DELETE,
    MENU_ID_SNDREC_RECORD_LIST,
    MENU_ID_SNDREC_SETTING,
    MENU_ID_SNDREC_FORWARD_USE,
    MENU_ID_SNDREC_FORWARD_SEND,
    MENU_ID_SNDREC_OPTION,
    MENU_ID_SNDREC_LIST_PLAY,
    MENU_ID_SNDREC_LIST_APPEND,
    MENU_ID_SNDREC_REC_OPTION,
    MENU_ID_SNDREC_RENAME_OPTION,
    MMI_RP_APP_SOUNDRECORDER_MENU_MAX
}mmi_rp_app_soundrecorder_menu_enum;
/******************** Menu resource IDs - finish ********************/


/******************** String resource IDs - begin ********************/
typedef enum
{
    STR_ID_SNDREC_MAIN = 35554 + 1, /* BASE_ID + 1 */
    STR_ID_SNDREC_NEW_RECORD,
    STR_ID_SNDREC_APPEND,
    STR_ID_SNDREC_SETTING_QUALITY,
    STR_ID_SNDREC_PLS_RECORD,
    STR_ID_SNDREC_RECORDING,
    STR_ID_SNDREC_REC_PAUSED,
    STR_ID_SNDREC_PLAYING,
    STR_ID_SNDREC_PLAY_PAUSED,
    STR_ID_SNDREC_SYSTEM_ERROR,
    STR_ID_SNDREC_AUTO_RECORD_ON,
    STR_ID_SNDREC_AUDIO_PLAY_FAIL,
    STR_ID_SNDREC_REC_ERROR,
    STR_ID_SNDREC_SPEECH_OFF,
    STR_ID_SNDREC_SMS_RECORD_TIMEOUT,
    STR_ID_SNDREC_DISC_FULL,
    MMI_RP_APP_SOUNDRECORDER_STR_MAX
}mmi_rp_app_soundrecorder_str_enum;
/******************** String resource IDs - finish ********************/


/******************** Screen resource IDs - begin ********************/
typedef enum
{
    GRP_ID_SNDREC_START_BASE = 35554 + 1, /* BASE_ID + 1 */
    GRP_ID_SNDREC_MAIN,
    GRP_ID_SNDREC_OPTION,
    GRP_ID_SNDREC_SETTING,
    GRP_ID_SNDREC_PLAYER,
    GRP_ID_SNDREC_CREATING,
    GRP_ID_SNDREC_RENAME,
    SCR_ID_SNDREC_MAIN,
    SCR_ID_SNDREC_OPTION,
    SCR_ID_SNDREC_SETTING,
    SCR_ID_SNDREC_PLAYER,
    SCR_ID_SNDREC_CREATING,
    SCR_ID_SNDREC_DELETE_ANIMATION,
    MMI_RP_APP_SOUNDRECORDER_SCR_MAX
}mmi_rp_app_soundrecorder_scr_enum;
/******************** Screen resource IDs - finish ********************/


/******************** Timer resource IDs - begin ********************/
typedef enum
{
    SNDREC_TIMER_FILELIST_SEEK = 35554 + 1, /* BASE_ID + 1 */
    MMI_RP_APP_SOUNDRECORDER_TIMER_MAX
}mmi_rp_app_soundrecorder_timer_enum;
/******************** Timer resource IDs - finish ********************/
/******************** Template resource IDs - Begin ********************/
/******************** Template resource IDs - End ********************/

/******************** Venus XML resource IDs - Begin ********************/
typedef enum 
{

    MMI_RP_APP_SOUNDRECORDER_VXML_LAYOUT_MAX
} mmi_rp_app_soundrecorder_vxml_layout_enum;
/******************** Venus XML resource IDs - End ********************/



/******************** MMI Cache IDs - Begin ********************/
typedef enum
{
    NVRAM_AUTO_VM_SETTING_VM_SUPPORT = 35554 + 1, /* BASE_ID + 1 */       /*         BYTE */ 
    MMI_RP_APP_SOUNDRECORDER_MMI_CACHE_MAX
} mmi_rp_app_soundrecorder_mmi_cache_enum;
/******************** MMI Cache IDs - End ********************/


/******************** Image resource IDs - begin ********************/
typedef enum
{
    IMG_ID_SNDREC_MAIN_ICON = 35554 + 1, /* BASE_ID + 1 */
    IMG_ID_SNDREC_BACKGROUND,
    IMG_ID_SNDREC_ANIMAL,
    IMG_ID_SNDREC_BUTTON_REC_UP,
    IMG_ID_SNDREC_BUTTON_REC_DN,
    IMG_ID_SNDREC_BUTTON_REC_P_UP,
    IMG_ID_SNDREC_BUTTON_REC_P_DN,
    IMG_ID_SNDREC_BUTTON_PLAY_UP,
    IMG_ID_SNDREC_BUTTON_PLAY_DN,
    IMG_ID_SNDREC_BUTTON_PLAY_P_UP,
    IMG_ID_SNDREC_BUTTON_PLAY_P_DN,
    IMG_ID_SNDREC_BUTTON_PREV_UP,
    IMG_ID_SNDREC_BUTTON_PREV_DN,
    IMG_ID_SNDREC_BUTTON_NEXT_UP,
    IMG_ID_SNDREC_BUTTON_NEXT_DN,
    IMG_ID_SNDREC_BUTTON_LIST_UP,
    IMG_ID_SNDREC_BUTTON_LIST_DN,
    IMG_ID_SNDREC_BUTTON_REC_DISABLE,
    IMG_ID_SNDREC_BUTTON_PLAY_DISABLE,
    IMG_ID_SNDREC_BUTTON_PREV_DISABLE,
    IMG_ID_SNDREC_BUTTON_NEXT_DISABLE,
    IMG_ID_SNDREC_BUTTON_LIST_DISABLE,
    IMG_ID_SNDREC_BUTTON_STOP_P_UP,
    IMG_ID_SNDREC_BUTTON_STOP_P_DOWN,
    MMI_RP_APP_SOUNDRECORDER_IMG_MAX
}mmi_rp_app_soundrecorder_img_enum;
/******************** Image resource IDs - finish ********************/


#endif /* _MMI_RP_APP_SOUNDRECORDER_DEF_H */
