/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_app_sim_me_lock_def.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   MTK resgenerator XML parser
 *
 *******************************************************************************/


#ifndef _MMI_RP_APP_SIM_ME_LOCK_DEF_H
#define _MMI_RP_APP_SIM_ME_LOCK_DEF_H




/******************** String resource IDs - begin ********************/
typedef enum
{
    STR_ID_CATEGORY_NP_LOCK = 30033 + 1, /* BASE_ID + 1 */
    STR_ID_CATEGORY_NSP_LOCK,
    STR_ID_CATEGORY_CP_LOCK,
    STR_ID_CATEGORY_SP_LOCK,
    STR_ID_CATEGORY_SIMP_LOCK,
    STR_ID_CATEGORY_NSP_SP_LOCK,
    STR_ID_CATEGORY_SIMP_CP_LOCK,
    STR_ID_SML_LOCK_MENU,
    STR_ID_SML_UNLOCK_MENU,
    STR_ID_SML_ADD_MENU,
    STR_ID_SML_REMOVE_MENU,
    STR_ID_SML_DEACTIVATE_MENU,
    STR_ID_SML_REBOOT_MSG,
    STR_ID_SML_QUREY_MSG,
    STR_ID_SML_BLOCK_MSG,
    STR_ID_SML_NO_EF_GID,
    STR_ID_SML_AUTOKEY_CONFIRM,
    STR_ID_LAST_RETRY_MSG,
    STR_ID_GENERAL_RETRY_MSG,
    STR_ID_UNLOCK_FIRST_MSG,
    STR_ID_EMPTY_CATEGORY_MSG,
    STR_ID_NO_RECORD_MSG,
    STR_ID_NO_DATA_MSG,
    STR_ID_SML_CAT_LOCKED,
    STR_ID_SML_CAT_UNLOCKED,
    STR_ID_SML_CAT_AUTOLOCKED,
    STR_ID_SML_CAT_DISABLED,
    STR_ID_SML_AUTOLOCKED,
    STR_ID_SML_FAIL_TO_AUTOLOCK,
    STR_ID_SML_NP_DATA,
    STR_ID_SML_NSP_DATA,
    STR_ID_SML_SP_DATA,
    STR_ID_SML_CP_DATA,
    STR_ID_SML_SIMP_DATA,
    STR_ID_SML_ASK_DELETE_CATEGORY,
    STR_ID_SML_ASK_DISABLE_CATEGORY,
    STR_ID_SML_INPUT_PASSWORD,
    STR_ID_SML_CONFIRM_PASSWORD,
    STR_ID_SML_DIFF_PASSWORD,
    STR_ID_SML_REMAIN_TRIALS,
    STR_ID_SML_INVALID_LENGTH,
    MMI_RP_APP_SIM_ME_LOCK_STR_MAX
}mmi_rp_app_sim_me_lock_str_enum;
/******************** String resource IDs - finish ********************/


/******************** Screen resource IDs - begin ********************/
typedef enum
{
    SCR_ID_SML_LOCK_MENU = 30033 + 1, /* BASE_ID + 1 */
    SCR_ID_SML_UNLOCK_MENU,
    SCR_ID_SML_ADD_MENU,
    SCR_ID_SML_REMOVE_MENU,
    SCR_ID_SML_DEACTIVATE_MENU,
    SCR_ID_SML_QUERY_POPUP,
    SCR_ID_SML_FILL_DATA,
    SCR_ID_SML_AUTOKEY_CONFIRM,
    SCR_ID_SML_REMOVE_CONFIRM,
    SCR_ID_SML_DEACTIVATE_CONFIRM,
    SCR_ID_SML_INPUT_KEY,
    SCR_ID_SML_CONFIRM_KEY,
    SCR_ID_SML_DUMMY,
    GRP_ID_SML_SIMS,
    GRP_ID_SML_MAIN,
    GRP_ID_SML_DATA,
    GRP_ID_SML_PSWD,
    MMI_RP_APP_SIM_ME_LOCK_SCR_MAX
}mmi_rp_app_sim_me_lock_scr_enum;
/******************** Screen resource IDs - finish ********************/


/******************** Timer resource IDs - begin ********************/
typedef enum
{
    SML_AUTOLOCK_IDLE_NOTIFY_TIMER = 30033 + 1, /* BASE_ID + 1 */
    MMI_RP_APP_SIM_ME_LOCK_TIMER_MAX
}mmi_rp_app_sim_me_lock_timer_enum;
/******************** Timer resource IDs - finish ********************/
/******************** Template resource IDs - Begin ********************/
/******************** Template resource IDs - End ********************/

/******************** Venus XML resource IDs - Begin ********************/
typedef enum 
{

    MMI_RP_APP_SIM_ME_LOCK_VXML_LAYOUT_MAX
} mmi_rp_app_sim_me_lock_vxml_layout_enum;
/******************** Venus XML resource IDs - End ********************/



#endif /* _MMI_RP_APP_SIM_ME_LOCK_DEF_H */
