/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_app_cca_def.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   MTK resgenerator XML parser
 *
 *******************************************************************************/


#ifndef _MMI_RP_APP_CCA_DEF_H
#define _MMI_RP_APP_CCA_DEF_H




/******************** String resource IDs - begin ********************/
typedef enum
{
    STR_ID_CCA_SETTINGS_MESSAGE = 48812 + 1, /* BASE_ID + 1 */
    STR_ID_CCA_PROGRESS_CONTENT,
    STR_ID_CCA_PREINFO_CONTENT,
    STR_ID_CCA_POSTINFO_TITLE,
    STR_ID_CCA_AUTH_CONTENT,
    STR_ID_CCA_CONFIGURED,
    STR_ID_CCA_INVALID_SETTING,
    STR_ID_CCA_SETTING_SKIPPED,
    STR_ID_CCA_CORRUPTED_SETTING,
    STR_ID_CCA_MISSING_DATA,
    STR_ID_CCA_INSTALL_SETTING,
    STR_ID_CCA_REPLACE_SETTING,
    STR_ID_CCA_SKIP_PROFILE,
    STR_ID_CCA_PROFILE_IN_USE,
    STR_ID_CCA_SKIP,
    STR_ID_CCA_ABORT_ASK,
    STR_ID_CCA_UPDATED,
    STR_ID_CCA_FAILED,
    STR_ID_CCA_PROFILE,
    STR_ID_CCA_NEW_SETTING,
    STR_ID_CCA_SETTING_INFO,
    STR_ID_CCA_PIN_RETRY,
    STR_ID_CCA_PIN_EMPTY,
    STR_ID_CCA_DATA_ACCOUNT_WITH_COLON,
    STR_ID_CCA_MMS,
    STR_ID_CCA_MMS_WITH_COLON,
    STR_ID_CCA_NOAPP,
    STR_ID_CCA_AUTH_FAILED,
    STR_ID_CCA_INSTALLING_RETRY,
    MMI_RP_APP_CCA_STR_MAX
}mmi_rp_app_cca_str_enum;
/******************** String resource IDs - finish ********************/


/******************** Screen resource IDs - begin ********************/
typedef enum
{
    SCR_ID_CCA_PRE_INFO = 48812 + 1, /* BASE_ID + 1 */
    SCR_ID_CCA_PROGRESS,
    SCR_ID_CCA_POST_INFO,
    SCR_ID_CCA_NEW_SETTING_CONF,
    SCR_ID_CCA_AUTH,
    GRP_ID_CCA,
    MMI_RP_APP_CCA_SCR_MAX
}mmi_rp_app_cca_scr_enum;
/******************** Screen resource IDs - finish ********************/


/******************** Timer resource IDs - begin ********************/
typedef enum
{
    TIMER_ID_CCA_NMGR_POPUP = 48812 + 1, /* BASE_ID + 1 */
    MMI_RP_APP_CCA_TIMER_MAX
}mmi_rp_app_cca_timer_enum;
/******************** Timer resource IDs - finish ********************/
/******************** Template resource IDs - Begin ********************/
/******************** Template resource IDs - End ********************/

/******************** Venus XML resource IDs - Begin ********************/
typedef enum 
{

    MMI_RP_APP_CCA_VXML_LAYOUT_MAX
} mmi_rp_app_cca_vxml_layout_enum;
/******************** Venus XML resource IDs - End ********************/



/******************** Image resource IDs - begin ********************/
typedef enum
{
    IMG_ID_CCA_MAIN_ICON = 48812 + 1, /* BASE_ID + 1 */
    IMG_ID_CCA_NEW_SETTING_IDLE,
    MMI_RP_APP_CCA_IMG_MAX
}mmi_rp_app_cca_img_enum;
/******************** Image resource IDs - finish ********************/


#endif /* _MMI_RP_APP_CCA_DEF_H */
