/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_srv_phb_def.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   MTK resgenerator XML parser
 *
 *******************************************************************************/


#ifndef _MMI_RP_SRV_PHB_DEF_H
#define _MMI_RP_SRV_PHB_DEF_H




/******************** String resource IDs - begin ********************/
typedef enum
{
    STR_ID_PHB_MOBILE_NUMBER = 32148 + 1, /* BASE_ID + 1 */
    STR_HOME_NUMBER,
    STR_OFFICE_NUMBER,
    STR_FAX_NUMBER,
    STR_EMERGENCY_NUMBER,
    MMI_RP_SRV_PHB_STR_MAX
}mmi_rp_srv_phb_str_enum;
/******************** String resource IDs - finish ********************/
/******************** Template resource IDs - Begin ********************/
/******************** Template resource IDs - End ********************/

/******************** Venus XML resource IDs - Begin ********************/
typedef enum 
{

    MMI_RP_SRV_PHB_VXML_LAYOUT_MAX
} mmi_rp_srv_phb_vxml_layout_enum;
/******************** Venus XML resource IDs - End ********************/



/******************** MMI Cache IDs - Begin ********************/
typedef enum
{
    NVRAM_PHB_SPEAK_NAME_ON_OFF = 32148 + 1, /* BASE_ID + 1 */   /*         BYTE */ 
    NVRAM_PHB_STARTUP_COPY_SIM,                                 /*         BYTE */ 
    NVRAM_PHB_STARTUP_COPY_SIM2,                                /*         BYTE */ 
    NVRAM_PHB_STARTUP_COPY_SIM3,                                /*         BYTE */ 
    NVRAM_PHB_STARTUP_COPY_SIM4,                                /*         BYTE */ 
    NVRAM_PHB_NAME_DISPLAY_TYPE,                                /*         BYTE */ 
    NVRAM_PHB_STORAGE_LOCATION,                                 /*        SHORT */ 
    NVRAM_PHB_NAME_LIST_FILTER,                                 /*        SHORT */ 
    NVRAM_PHB_VCARD_VERSION,                                    /*        SHORT */ 
    NVRAM_PHB_SAVE_CONTACT_NOTIFY,                              /*         BYTE */ 
    NVRAM_SSC_DISABLE_FLAG,                                     /*         BYTE */ 
    NVRAM_IDLE_DIALER_SEARCH_SETTING,                           /*         BYTE */ 
    NVRAM_SETTING_SPEED_DIAL,                                   /*         BYTE */ 
    MMI_RP_SRV_PHB_MMI_CACHE_MAX
} mmi_rp_srv_phb_mmi_cache_enum;
/******************** MMI Cache IDs - End ********************/


/******************** Image resource IDs - begin ********************/
typedef enum
{
    IMG_PHB_DEFAULT = 32148 + 1, /* BASE_ID + 1 */
    MMI_RP_SRV_PHB_IMG_MAX
}mmi_rp_srv_phb_img_enum;
/******************** Image resource IDs - finish ********************/


#endif /* _MMI_RP_SRV_PHB_DEF_H */
