/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_app_unifiedmessage_def.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   MTK resgenerator XML parser
 *
 *******************************************************************************/


#ifndef _MMI_RP_APP_UNIFIEDMESSAGE_DEF_H
#define _MMI_RP_APP_UNIFIEDMESSAGE_DEF_H




/******************** Menu resource IDs - begin ********************/
typedef enum
{
    MAIN_MENU_MESSAGES_MENUID = 47922 + 1, /* BASE_ID + 1 */
    MENU_ID_UM_WRITE_MSG,
    MENU_ID_UM_INBOX,
    MENU_ID_UM_DRAFT,
    MENU_ID_UM_UNSENT,
    MENU_ID_UM_SENT,
    MENU_ID_UM_DEL_ALL_OPT,
    MENU_ID_UM_MS_OPT,
    MENU_ID_UM_MS_DELETE_OPT,
    MENU_ID_UM_MULTI_OP_DELETE_PRE,
    MENU_ID_UM_CB_MAIN,
    MENU_ID_UM_TEMPLATE,
    MENU_ID_UM_SETTING,
    MENU_ID_UM_WRITE_MSG_SMS,
    MENU_ID_UM_WRITE_MSG_MMS,
    MENU_ID_UM_TEMPLATE_SMS,
    MENU_ID_UM_SETTING_SMS,
    MENU_ID_UM_SETTING_MMS,
    MENU_ID_UM_MULTI_OP_OPTION,
    MENU_ID_UM_MULTI_OP_DELETE,
    MENU_ID_UM_MULTI_OP_MARK_ALL,
    MENU_ID_UM_MULTI_OP_UNMARK_ALL,
    MENU_ID_UM_OPT,
    MMI_RP_APP_UNIFIEDMESSAGE_MENU_MAX
}mmi_rp_app_unifiedmessage_menu_enum;
/******************** Menu resource IDs - finish ********************/


/******************** String resource IDs - begin ********************/
typedef enum
{
    STR_UM_WRITE_MSG_ID = 47922 + 1, /* BASE_ID + 1 */
    STR_UM_SENT_ID,
    STR_UM_TEMPLATE_ID,
    STR_UM_SETTING_ID,
    STR_UM_MSG_ID,
    STR_UM_MSGS_ID,
    STR_UM_MSG_WITH_QUESTION_MARK_ID,
    STR_UM_MSGS_WITH_QUESTION_MARK_ID,
    STR_UM_UNREAD_MSG_NUMBER_ID,
    STR_UM_UNREAD_MSG,
    STR_UM_UNREAD_MSG_WITH_NUMBER,
    STR_UM_UNREAD_MSGS_WITH_NUMBER,
    STR_UM_SEND_FAILED_MSG,
    STR_UM_SEND_FAILED_MSG_NUMBER,
    STR_UM_SEND_FAILED_MSGS_NUMBER,
    STR_UM_SEND_FAILED_SAVE_SUCCESS_ID,
    STR_UM_EMPTY_SUBJECT_ID,
    STR_UM_EMPTY_CONTENT_ID,
    STR_UM_INCOMPLETE_ID,
    STR_UM_NOT_SUPPORT_ID,
    STR_UM_MOVE_MARKED_TO_ARCHIVE_ID,
    STR_UM_DELETE_MARKED_ID,
    STR_UM_MULTI_OP_PRESS_STAR,
    STR_UM_MULTI_OP_TOUCH_BOX,
    STR_UM_MULTI_OP_UNDELETED_WITH_MSG_ID,
    STR_UM_MULTI_OP_UNDELETED_WITH_MSGS_ID,
    STR_UM_MULTI_OP_UNMOVED_WITH_MSG_ID,
    STR_UM_MULTI_OP_UNMOVED_WITH_MSGS_ID,
    STR_UM_MULTI_OP_UNCOPIED_WITH_MSG_ID,
    STR_UM_MULTI_OP_UNCOPIED_WITH_MSGS_ID,
    STR_UM_MOVE_MARKED_TO_ARCHIVE_ID_PRE,
    STR_UM_DELETE_MARKED_ID_PRE,
    STR_UM_DELETE_SEVERAL_ID_PRE,
    STR_UM_QUESTION_MARK,
    STR_UM_EMPTY_MSG_ID,
    STR_UM_MARK_SEVERAL,
    STR_UM_CB,
    MMI_RP_APP_UNIFIEDMESSAGE_STR_MAX
}mmi_rp_app_unifiedmessage_str_enum;
/******************** String resource IDs - finish ********************/


/******************** Screen resource IDs - begin ********************/
typedef enum
{
    SCR_ID_UM_START = 47922 + 1, /* BASE_ID + 1 */
    SCR_ID_UM_MAIN,
    SCR_ID_UM_MAIN_MESSAGE,
    SCR_ID_UM_WRITE_MSG,
    SCR_ID_UM_DELETE_FOLDER,
    SCR_ID_UM_TEMPLATE,
    SCR_ID_UM_SETTING,
    SCR_ID_UM_PROCESSING,
    SCR_ID_UM_FOLDER,
    SCR_ID_UM_MULTI_OP,
    SCR_ID_UM_CONVERSATION_BOX,
    SCR_ID_UM_MS_CONVERSATION_BOX,
    SCR_ID_UM_THREAD_MSG,
    SCR_ID_UM_MS_THREAD_MSG,
    SCR_ID_UM_CONVERSATION_BOX_SETTING,
    SCR_ID_UM_PREFER_SIM_SETTING,
    MMI_RP_APP_UNIFIEDMESSAGE_SCR_MAX
}mmi_rp_app_unifiedmessage_scr_enum;
/******************** Screen resource IDs - finish ********************/


/******************** Timer resource IDs - begin ********************/
typedef enum
{
    MESSAGES_TTS_COUNT_DOWN_TIMER_ID = 47922 + 1, /* BASE_ID + 1 */
    UM_INPROGRESS_TIMER_ID,
    MMI_RP_APP_UNIFIEDMESSAGE_TIMER_MAX
}mmi_rp_app_unifiedmessage_timer_enum;
/******************** Timer resource IDs - finish ********************/


/******************** Events resource IDs - begin ********************/
typedef enum
{
    EVT_ID_MMI_UM_REFRESH = 47922 + 1, /* BASE_ID + 1 */
    EVT_ID_MMI_UM_ENTRY_MAIN_MSG,
    EVT_ID_MMI_UM_ENTRY_FOLDER,
    MMI_RP_APP_UNIFIEDMESSAGE_EVENT_MAX
}mmi_rp_app_unifiedmessage_event_enum;
/******************** Events resource IDs - begin ********************/
/******************** Template resource IDs - Begin ********************/
/******************** Template resource IDs - End ********************/

/******************** Venus XML resource IDs - Begin ********************/
typedef enum 
{

    MMI_RP_APP_UNIFIEDMESSAGE_VXML_LAYOUT_MAX
} mmi_rp_app_unifiedmessage_vxml_layout_enum;
/******************** Venus XML resource IDs - End ********************/



/******************** Image resource IDs - begin ********************/
typedef enum
{
    IMG_UM_UNREAD_ICON = 47922 + 1, /* BASE_ID + 1 */
    IMG_UM_MAIN_ID,
    IMG_UM_WRITE_MSG_ID,
    IMG_UM_INBOX_ID,
    IMG_UM_UNSENT_ID,
    IMG_UM_SENT_ID,
    IMG_UM_DRAFT_ID,
    IMG_UM_DELETE_FOLDER_ID,
    IMG_UM_TEMPLATE_ID,
    IMG_UM_SETTING_ID,
    IMG_UM_ENTRY_SCRN_CAPTION,
    MMI_RP_APP_UNIFIEDMESSAGE_IMG_MAX
}mmi_rp_app_unifiedmessage_img_enum;
/******************** Image resource IDs - finish ********************/


#endif /* _MMI_RP_APP_UNIFIEDMESSAGE_DEF_H */
