/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_app_npr_tts_def.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   MTK resgenerator XML parser
 *
 *******************************************************************************/


#ifndef _MMI_RP_APP_NPR_TTS_DEF_H
#define _MMI_RP_APP_NPR_TTS_DEF_H




/******************** Menu resource IDs - begin ********************/
typedef enum
{
    MENU_ID_TTS_SETTING = 32998 + 1, /* BASE_ID + 1 */
    MENU_ID_TTS_MENU_READ,
    MENU_ID_TTS_INCOMING_CALL_READ,
    MENU_ID_TTS_KEYPAD_READ,
    MENU_ID_TTS_ABOUT,
    MENU_ID_TTS_VOL_SET,
    MENU_ID_TTS_SMS_READ_SET,
    MENU_ID_TTS_SMS_RECV_READ,
    MENU_ID_TTS_SMS_AUTO_READ,
    MMI_RP_APP_NPR_TTS_MENU_MAX
}mmi_rp_app_npr_tts_menu_enum;
/******************** Menu resource IDs - finish ********************/


/******************** String resource IDs - begin ********************/
typedef enum
{
    STR_ID_NPR_TTS_MENU1 = 32998 + 1, /* BASE_ID + 1 */
    STR_ID_NPR_TTS_MENU2,
    STR_ID_NPR_TTS_ABOUT,
    STR_ID_NPR_TTS_ABOUT_INFO,
    STR_ID_NPR_TTS_VOL,
    STR_ID_NPR_TTS_SMS_NOTICE,
    STR_ID_TTS_SETTING_MENU_TEXT,
    STR_ID_TTS_MENU_READ,
    STR_ID_TTS_INCOMING_CALL_READ,
    STR_ID_TTS_KEYPAD_READ,
    STR_ID_TTS_TIME_READ_SET,
    STR_ID_TTS_VOICE_SEL,
    STR_ID_TTS_VOL_SET,
    STR_ID_TTS_ABOUT,
    STR_ID_TTS_TIME_READ_AUTO,
    STR_ID_TTS_TIME_READ_HAND,
    STR_ID_TTS_SMS_READ_SET,
    STR_ID_TTS_SMS_RECV_READ,
    STR_ID_TTS_SMS_AUTO_READ,
    STR_ID_TTS_TIME_READ_TIPS,
    STR_ID_TTS_ABOUT_INFO,
    STR_ID_TTS_FEMALE,
    STR_ID_TTS_GD,
    STR_ID_TTS_SC,
    STR_ID_TTS_DB,
    STR_ID_TTS_MALE,
    STR_ID_TTS_CHILDREN,
    STR_ID_NPR_INSERT_SIM_CARD,
    STR_ID_NPR_INVALID_SIM_CARD,
    STR_ID_NPR_NET_NOT_INITED,
    STR_ID_NPR_INSERT_T_CARD,
    STR_ID_NPR_TTS_SET_SIM,
    STR_ID_NPR_TTS_RESOURCES_DOWN,
    MMI_RP_APP_NPR_TTS_STR_MAX
}mmi_rp_app_npr_tts_str_enum;
/******************** String resource IDs - finish ********************/


/******************** Screen resource IDs - begin ********************/
typedef enum
{
    SCR_ID_TTS_SETTING_MIAN = 32998 + 1, /* BASE_ID + 1 */
    SCR_ID_TTS_ABOUT,
    SCR_ID_TTS_VOLUME_SET,
    SCR_ID_TTS_VOICE_SEL,
    SCR_ID_TTS_SMS_READ_SET,
    SCR_ID_TTS_TIME_READ_SET,
    MMI_RP_APP_NPR_TTS_SCR_MAX
}mmi_rp_app_npr_tts_scr_enum;
/******************** Screen resource IDs - finish ********************/
/******************** Template resource IDs - Begin ********************/
/******************** Template resource IDs - End ********************/

/******************** Venus XML resource IDs - Begin ********************/
typedef enum 
{

    MMI_RP_APP_NPR_TTS_VXML_LAYOUT_MAX
} mmi_rp_app_npr_tts_vxml_layout_enum;
/******************** Venus XML resource IDs - End ********************/



/******************** MMI Cache IDs - Begin ********************/
typedef enum
{
    NVRAM_NPR_TTS_FLAG = 32998 + 1, /* BASE_ID + 1 */           /*         BYTE */ 
    NVRAM_TTS_VOL_LEVEL,                                        /*         BYTE */ 
    NVRAM_TTS_VOICE_SEL,                                        /*         BYTE */ 
    MMI_RP_APP_NPR_TTS_MMI_CACHE_MAX
} mmi_rp_app_npr_tts_mmi_cache_enum;
/******************** MMI Cache IDs - End ********************/


/******************** Image resource IDs - begin ********************/
typedef enum
{
    IMG_ID_TTS_SETTING_MENU_ICON = 32998 + 1, /* BASE_ID + 1 */
    IMG_ID_NPR_TTS_MENU1,
    IMG_ID_NPR_TTS_MENU2,
    MMI_RP_APP_NPR_TTS_IMG_MAX
}mmi_rp_app_npr_tts_img_enum;
/******************** Image resource IDs - finish ********************/


#endif /* _MMI_RP_APP_NPR_TTS_DEF_H */
