xcopy /y plutommi\..\Plutommi\Framework\GDI\GDIRes\*.res %1\plutommi\..\Plutommi\Framework\GDI\GDIRes\
xcopy /y plutommi\..\Plutommi\Framework\GDI\GDIRes\*.txt %1\plutommi\..\Plutommi\Framework\GDI\GDIRes\
xcopy /y plutommi\..\Plutommi\Framework\GUI\GUI_Res\*.res %1\plutommi\..\Plutommi\Framework\GUI\GUI_Res\
xcopy /y plutommi\..\Plutommi\Framework\GUI\GUI_Res\*.txt %1\plutommi\..\Plutommi\Framework\GUI\GUI_Res\
xcopy /y plutommi\..\Plutommi\MMI\Resource\Res\*.res %1\plutommi\..\Plutommi\MMI\Resource\Res\
xcopy /y plutommi\..\Plutommi\MMI\Resource\Res\*.txt %1\plutommi\..\Plutommi\MMI\Resource\Res\
xcopy /y plutommi\..\custom\common\CharsetRes\*.res %1\plutommi\..\custom\common\CharsetRes\
xcopy /y plutommi\..\custom\common\CharsetRes\*.txt %1\plutommi\..\custom\common\CharsetRes\
xcopy /y plutommi\..\kjx\res\*.res %1\plutommi\..\kjx\res\
xcopy /y plutommi\..\kjx\res\*.txt %1\plutommi\..\kjx\res\
xcopy /y plutommi\..\mre\res\*.res %1\plutommi\..\mre\res\
xcopy /y plutommi\..\mre\res\*.txt %1\plutommi\..\mre\res\
xcopy /y plutommi\..\plutommi\Framework\InputMethod\res\*.res %1\plutommi\..\plutommi\Framework\InputMethod\res\
xcopy /y plutommi\..\plutommi\Framework\InputMethod\res\*.txt %1\plutommi\..\plutommi\Framework\InputMethod\res\
xcopy /y plutommi\..\vendor\alipay\res\*.res %1\plutommi\..\vendor\alipay\res\
xcopy /y plutommi\..\vendor\alipay\res\*.txt %1\plutommi\..\vendor\alipay\res\
xcopy /y plutommi\..\vendor\mobilevideo\adaption\MobileVideoRes\*.res %1\plutommi\..\vendor\mobilevideo\adaption\MobileVideoRes\
xcopy /y plutommi\..\vendor\mobilevideo\adaption\MobileVideoRes\*.txt %1\plutommi\..\vendor\mobilevideo\adaption\MobileVideoRes\
xcopy /y plutommi\..\vendor\nmc\adaption\nmc_res\*.res %1\plutommi\..\vendor\nmc\adaption\nmc_res\
xcopy /y plutommi\..\vendor\nmc\adaption\nmc_res\*.txt %1\plutommi\..\vendor\nmc\adaption\nmc_res\
xcopy /y plutommi\..\vendor\opera\browser\adaptation\res\*.res %1\plutommi\..\vendor\opera\browser\adaptation\res\
xcopy /y plutommi\..\vendor\opera\browser\adaptation\res\*.txt %1\plutommi\..\vendor\opera\browser\adaptation\res\
xcopy /y plutommi\..\vendor\pushmail\mail139\PushMailRes\*.res %1\plutommi\..\vendor\pushmail\mail139\PushMailRes\
xcopy /y plutommi\..\vendor\pushmail\mail139\PushMailRes\*.txt %1\plutommi\..\vendor\pushmail\mail139\PushMailRes\
xcopy /y plutommi\..\vendor\search_engine\GUOBI\winguo\res\*.res %1\plutommi\..\vendor\search_engine\GUOBI\winguo\res\
xcopy /y plutommi\..\vendor\search_engine\GUOBI\winguo\res\*.txt %1\plutommi\..\vendor\search_engine\GUOBI\winguo\res\
xcopy /y plutommi\..\venusmmi\app\Cosmos\SNS\Widget\res\*.res %1\plutommi\..\venusmmi\app\Cosmos\SNS\Widget\res\
xcopy /y plutommi\..\venusmmi\app\Cosmos\SNS\Widget\res\*.txt %1\plutommi\..\venusmmi\app\Cosmos\SNS\Widget\res\
xcopy /y plutommi\..\venusmmi\app\Cosmos\SNS\res\*.res %1\plutommi\..\venusmmi\app\Cosmos\SNS\res\
xcopy /y plutommi\..\venusmmi\app\Cosmos\SNS\res\*.txt %1\plutommi\..\venusmmi\app\Cosmos\SNS\res\
xcopy /y plutommi\..\venusmmi\app\Cosmos\WidgetGoogleSearch\res\*.res %1\plutommi\..\venusmmi\app\Cosmos\WidgetGoogleSearch\res\
xcopy /y plutommi\..\venusmmi\app\Cosmos\WidgetGoogleSearch\res\*.txt %1\plutommi\..\venusmmi\app\Cosmos\WidgetGoogleSearch\res\
xcopy /y plutommi\..\venusmmi\app\common\cp\res\*.res %1\plutommi\..\venusmmi\app\common\cp\res\
xcopy /y plutommi\..\venusmmi\app\common\cp\res\*.txt %1\plutommi\..\venusmmi\app\common\cp\res\
xcopy /y plutommi\..\venusmmi\app\common\wallpaper\res\*.res %1\plutommi\..\venusmmi\app\common\wallpaper\res\
xcopy /y plutommi\..\venusmmi\app\common\wallpaper\res\*.txt %1\plutommi\..\venusmmi\app\common\wallpaper\res\
xcopy /y plutommi\..\venusmmi\app\pluto_variation\ImageFlow\res\*.res %1\plutommi\..\venusmmi\app\pluto_variation\ImageFlow\res\
xcopy /y plutommi\..\venusmmi\app\pluto_variation\ImageFlow\res\*.txt %1\plutommi\..\venusmmi\app\pluto_variation\ImageFlow\res\
xcopy /y plutommi\..\venusmmi\app\pluto_variation\MediaWall\res\*.res %1\plutommi\..\venusmmi\app\pluto_variation\MediaWall\res\
xcopy /y plutommi\..\venusmmi\app\pluto_variation\MediaWall\res\*.txt %1\plutommi\..\venusmmi\app\pluto_variation\MediaWall\res\
xcopy /y plutommi\..\venusmmi\app\pluto_variation\MultiTouchTest\res\*.res %1\plutommi\..\venusmmi\app\pluto_variation\MultiTouchTest\res\
xcopy /y plutommi\..\venusmmi\app\pluto_variation\MultiTouchTest\res\*.txt %1\plutommi\..\venusmmi\app\pluto_variation\MultiTouchTest\res\
xcopy /y plutommi\..\venusmmi\app\pluto_variation\ShellApp\base\res\*.res %1\plutommi\..\venusmmi\app\pluto_variation\ShellApp\base\res\
xcopy /y plutommi\..\venusmmi\app\pluto_variation\ShellApp\base\res\*.txt %1\plutommi\..\venusmmi\app\pluto_variation\ShellApp\base\res\
xcopy /y plutommi\..\venusmmi\app\pluto_variation\ShellApp\panel\FavoriteContacts\res\*.res %1\plutommi\..\venusmmi\app\pluto_variation\ShellApp\panel\FavoriteContacts\res\
xcopy /y plutommi\..\venusmmi\app\pluto_variation\ShellApp\panel\FavoriteContacts\res\*.txt %1\plutommi\..\venusmmi\app\pluto_variation\ShellApp\panel\FavoriteContacts\res\
xcopy /y plutommi\..\venusmmi\app\pluto_variation\ShellApp\panel\HomeScreen\res\*.res %1\plutommi\..\venusmmi\app\pluto_variation\ShellApp\panel\HomeScreen\res\
xcopy /y plutommi\..\venusmmi\app\pluto_variation\ShellApp\panel\HomeScreen\res\*.txt %1\plutommi\..\venusmmi\app\pluto_variation\ShellApp\panel\HomeScreen\res\
xcopy /y plutommi\..\venusmmi\app\pluto_variation\ShellApp\panel\ImageViewer\res\*.res %1\plutommi\..\venusmmi\app\pluto_variation\ShellApp\panel\ImageViewer\res\
xcopy /y plutommi\..\venusmmi\app\pluto_variation\ShellApp\panel\ImageViewer\res\*.txt %1\plutommi\..\venusmmi\app\pluto_variation\ShellApp\panel\ImageViewer\res\
xcopy /y plutommi\..\venusmmi\app\pluto_variation\ShellApp\panel\MediaPlayer\*.res %1\plutommi\..\venusmmi\app\pluto_variation\ShellApp\panel\MediaPlayer\
xcopy /y plutommi\..\venusmmi\app\pluto_variation\ShellApp\panel\MediaPlayer\*.txt %1\plutommi\..\venusmmi\app\pluto_variation\ShellApp\panel\MediaPlayer\
xcopy /y plutommi\..\venusmmi\app\pluto_variation\ShellApp\panel\MsgViewer\res\*.res %1\plutommi\..\venusmmi\app\pluto_variation\ShellApp\panel\MsgViewer\res\
xcopy /y plutommi\..\venusmmi\app\pluto_variation\ShellApp\panel\MsgViewer\res\*.txt %1\plutommi\..\venusmmi\app\pluto_variation\ShellApp\panel\MsgViewer\res\
xcopy /y plutommi\..\venusmmi\app\pluto_variation\ShellApp\panel\RecentCalls\*.res %1\plutommi\..\venusmmi\app\pluto_variation\ShellApp\panel\RecentCalls\
xcopy /y plutommi\..\venusmmi\app\pluto_variation\ShellApp\panel\RecentCalls\*.txt %1\plutommi\..\venusmmi\app\pluto_variation\ShellApp\panel\RecentCalls\
xcopy /y plutommi\..\venusmmi\app\pluto_variation\ShellApp\panel\Settings\*.res %1\plutommi\..\venusmmi\app\pluto_variation\ShellApp\panel\Settings\
xcopy /y plutommi\..\venusmmi\app\pluto_variation\ShellApp\panel\Settings\*.txt %1\plutommi\..\venusmmi\app\pluto_variation\ShellApp\panel\Settings\
xcopy /y plutommi\..\venusmmi\visual\cp\res\*.res %1\plutommi\..\venusmmi\visual\cp\res\
xcopy /y plutommi\..\venusmmi\visual\cp\res\*.txt %1\plutommi\..\venusmmi\visual\cp\res\
xcopy /y plutommi\.\AppCore\Ucm\res\*.res %1\plutommi\.\AppCore\Ucm\res\
xcopy /y plutommi\.\AppCore\Ucm\res\*.txt %1\plutommi\.\AppCore\Ucm\res\
xcopy /y plutommi\.\CUI\BookmarkCui\res\*.res %1\plutommi\.\CUI\BookmarkCui\res\
xcopy /y plutommi\.\CUI\BookmarkCui\res\*.txt %1\plutommi\.\CUI\BookmarkCui\res\
xcopy /y plutommi\.\CUI\CameraCui\CameraCuiRes\*.res %1\plutommi\.\CUI\CameraCui\CameraCuiRes\
xcopy /y plutommi\.\CUI\CameraCui\CameraCuiRes\*.txt %1\plutommi\.\CUI\CameraCui\CameraCuiRes\
xcopy /y plutommi\.\CUI\DialerCui\res\*.res %1\plutommi\.\CUI\DialerCui\res\
xcopy /y plutommi\.\CUI\DialerCui\res\*.txt %1\plutommi\.\CUI\DialerCui\res\
xcopy /y plutommi\.\CUI\ImageClipCui\ImageClipCuiRes\*.res %1\plutommi\.\CUI\ImageClipCui\ImageClipCuiRes\
xcopy /y plutommi\.\CUI\ImageClipCui\ImageClipCuiRes\*.txt %1\plutommi\.\CUI\ImageClipCui\ImageClipCuiRes\
xcopy /y plutommi\.\CUI\ImageViewCui\res\*.res %1\plutommi\.\CUI\ImageViewCui\res\
xcopy /y plutommi\.\CUI\ImageViewCui\res\*.txt %1\plutommi\.\CUI\ImageViewCui\res\
xcopy /y plutommi\.\CUI\InlineCUI\InlineCui_Res\*.res %1\plutommi\.\CUI\InlineCUI\InlineCui_Res\
xcopy /y plutommi\.\CUI\InlineCUI\InlineCui_Res\*.txt %1\plutommi\.\CUI\InlineCUI\InlineCui_Res\
xcopy /y plutommi\.\CUI\PasswordCui\res\*.res %1\plutommi\.\CUI\PasswordCui\res\
xcopy /y plutommi\.\CUI\PasswordCui\res\*.txt %1\plutommi\.\CUI\PasswordCui\res\
xcopy /y plutommi\.\CUI\SecSetCui\SecSetCuiRes\*.res %1\plutommi\.\CUI\SecSetCui\SecSetCuiRes\
xcopy /y plutommi\.\CUI\SecSetCui\SecSetCuiRes\*.txt %1\plutommi\.\CUI\SecSetCui\SecSetCuiRes\
xcopy /y plutommi\.\CUI\SimSelCui\res\*.res %1\plutommi\.\CUI\SimSelCui\res\
xcopy /y plutommi\.\CUI\SimSelCui\res\*.txt %1\plutommi\.\CUI\SimSelCui\res\
xcopy /y plutommi\.\CUI\ToneSelectorCui\res\*.res %1\plutommi\.\CUI\ToneSelectorCui\res\
xcopy /y plutommi\.\CUI\ToneSelectorCui\res\*.txt %1\plutommi\.\CUI\ToneSelectorCui\res\
xcopy /y plutommi\.\CUI\UseDetailCui\res\*.res %1\plutommi\.\CUI\UseDetailCui\res\
xcopy /y plutommi\.\CUI\UseDetailCui\res\*.txt %1\plutommi\.\CUI\UseDetailCui\res\
xcopy /y plutommi\.\Framework\CSBrowser\CSBrowserRes\*.res %1\plutommi\.\Framework\CSBrowser\CSBrowserRes\
xcopy /y plutommi\.\Framework\CSBrowser\CSBrowserRes\*.txt %1\plutommi\.\Framework\CSBrowser\CSBrowserRes\
xcopy /y plutommi\.\Framework\CallbackManager\CallbackManagerRes\*.res %1\plutommi\.\Framework\CallbackManager\CallbackManagerRes\
xcopy /y plutommi\.\Framework\CallbackManager\CallbackManagerRes\*.txt %1\plutommi\.\Framework\CallbackManager\CallbackManagerRes\
xcopy /y plutommi\.\Framework\CommonScreens\CommonScreensRes\*.res %1\plutommi\.\Framework\CommonScreens\CommonScreensRes\
xcopy /y plutommi\.\Framework\CommonScreens\CommonScreensRes\*.txt %1\plutommi\.\Framework\CommonScreens\CommonScreensRes\
xcopy /y plutommi\.\Framework\MemManager\MemManagerRes\*.res %1\plutommi\.\Framework\MemManager\MemManagerRes\
xcopy /y plutommi\.\Framework\MemManager\MemManagerRes\*.txt %1\plutommi\.\Framework\MemManager\MemManagerRes\
xcopy /y plutommi\.\Framework\NVRAMManager\NVRAMManagerRes\*.res %1\plutommi\.\Framework\NVRAMManager\NVRAMManagerRes\
xcopy /y plutommi\.\Framework\NVRAMManager\NVRAMManagerRes\*.txt %1\plutommi\.\Framework\NVRAMManager\NVRAMManagerRes\
xcopy /y plutommi\.\Framework\Notification\NotificationRes\*.res %1\plutommi\.\Framework\Notification\NotificationRes\
xcopy /y plutommi\.\Framework\Notification\NotificationRes\*.txt %1\plutommi\.\Framework\Notification\NotificationRes\
xcopy /y plutommi\.\MMI\AppList\AppListRes\*.res %1\plutommi\.\MMI\AppList\AppListRes\
xcopy /y plutommi\.\MMI\AppList\AppListRes\*.txt %1\plutommi\.\MMI\AppList\AppListRes\
xcopy /y plutommi\.\MMI\Bootup\BootupRes\*.res %1\plutommi\.\MMI\Bootup\BootupRes\
xcopy /y plutommi\.\MMI\Bootup\BootupRes\*.txt %1\plutommi\.\MMI\Bootup\BootupRes\
xcopy /y plutommi\.\MMI\CallSetting\CallSettingRes\*.res %1\plutommi\.\MMI\CallSetting\CallSettingRes\
xcopy /y plutommi\.\MMI\CallSetting\CallSettingRes\*.txt %1\plutommi\.\MMI\CallSetting\CallSettingRes\
xcopy /y plutommi\.\MMI\IdleScreen\IdleScreenRes\*.res %1\plutommi\.\MMI\IdleScreen\IdleScreenRes\
xcopy /y plutommi\.\MMI\IdleScreen\IdleScreenRes\*.txt %1\plutommi\.\MMI\IdleScreen\IdleScreenRes\
xcopy /y plutommi\.\MMI\Idle\IdleRes\*.res %1\plutommi\.\MMI\Idle\IdleRes\
xcopy /y plutommi\.\MMI\Idle\IdleRes\*.txt %1\plutommi\.\MMI\Idle\IdleRes\
xcopy /y plutommi\.\MMI\MainMenu\MainMenuRes\*.res %1\plutommi\.\MMI\MainMenu\MainMenuRes\
xcopy /y plutommi\.\MMI\MainMenu\MainMenuRes\*.txt %1\plutommi\.\MMI\MainMenu\MainMenuRes\
xcopy /y plutommi\.\MMI\NWInfo\NWInfoRes\*.res %1\plutommi\.\MMI\NWInfo\NWInfoRes\
xcopy /y plutommi\.\MMI\NWInfo\NWInfoRes\*.txt %1\plutommi\.\MMI\NWInfo\NWInfoRes\
xcopy /y plutommi\.\MMI\ScrLocker\ScrLockerRes\*.res %1\plutommi\.\MMI\ScrLocker\ScrLockerRes\
xcopy /y plutommi\.\MMI\ScrLocker\ScrLockerRes\*.txt %1\plutommi\.\MMI\ScrLocker\ScrLockerRes\
xcopy /y plutommi\.\MMI\SecuritySetting\SecSetRes\*.res %1\plutommi\.\MMI\SecuritySetting\SecSetRes\
xcopy /y plutommi\.\MMI\SecuritySetting\SecSetRes\*.txt %1\plutommi\.\MMI\SecuritySetting\SecSetRes\
xcopy /y plutommi\.\MMI\Shutdown\ShutdownRes\*.res %1\plutommi\.\MMI\Shutdown\ShutdownRes\
xcopy /y plutommi\.\MMI\Shutdown\ShutdownRes\*.txt %1\plutommi\.\MMI\Shutdown\ShutdownRes\
xcopy /y plutommi\.\MMI\SimCtrl\SimCtrlRes\*.res %1\plutommi\.\MMI\SimCtrl\SimCtrlRes\
xcopy /y plutommi\.\MMI\SimCtrl\SimCtrlRes\*.txt %1\plutommi\.\MMI\SimCtrl\SimCtrlRes\
xcopy /y plutommi\.\MMI\SimSpace\SimSpaceRes\*.res %1\plutommi\.\MMI\SimSpace\SimSpaceRes\
xcopy /y plutommi\.\MMI\SimSpace\SimSpaceRes\*.txt %1\plutommi\.\MMI\SimSpace\SimSpaceRes\
xcopy /y plutommi\.\MMI\SupplementaryService\SsRes\*.res %1\plutommi\.\MMI\SupplementaryService\SsRes\
xcopy /y plutommi\.\MMI\SupplementaryService\SsRes\*.txt %1\plutommi\.\MMI\SupplementaryService\SsRes\
xcopy /y plutommi\.\MMI\UCM\UcmRes\*.res %1\plutommi\.\MMI\UCM\UcmRes\
xcopy /y plutommi\.\MMI\UCM\UcmRes\*.txt %1\plutommi\.\MMI\UCM\UcmRes\
xcopy /y plutommi\.\MMI\UnifiedMessage\UnifiedMessageRes\*.res %1\plutommi\.\MMI\UnifiedMessage\UnifiedMessageRes\
xcopy /y plutommi\.\MMI\UnifiedMessage\UnifiedMessageRes\*.txt %1\plutommi\.\MMI\UnifiedMessage\UnifiedMessageRes\
xcopy /y plutommi\.\Mmi\Ctm\CtmRes\*.res %1\plutommi\.\Mmi\Ctm\CtmRes\
xcopy /y plutommi\.\Mmi\Ctm\CtmRes\*.txt %1\plutommi\.\Mmi\Ctm\CtmRes\
xcopy /y plutommi\.\MtkApp\Connectivity\ConnectivityRes\*.res %1\plutommi\.\MtkApp\Connectivity\ConnectivityRes\
xcopy /y plutommi\.\MtkApp\Connectivity\ConnectivityRes\*.txt %1\plutommi\.\MtkApp\Connectivity\ConnectivityRes\
xcopy /y plutommi\.\MtkApp\Connectivity\ConnectivityRes\NFC\*.res %1\plutommi\.\MtkApp\Connectivity\ConnectivityRes\NFC\
xcopy /y plutommi\.\MtkApp\Connectivity\ConnectivityRes\NFC\*.txt %1\plutommi\.\MtkApp\Connectivity\ConnectivityRes\NFC\
xcopy /y plutommi\.\MtkApp\DCD\DCDRes\*.res %1\plutommi\.\MtkApp\DCD\DCDRes\
xcopy /y plutommi\.\MtkApp\DCD\DCDRes\*.txt %1\plutommi\.\MtkApp\DCD\DCDRes\
xcopy /y plutommi\.\MtkApp\DLAgent\DLAgentRes\*.res %1\plutommi\.\MtkApp\DLAgent\DLAgentRes\
xcopy /y plutommi\.\MtkApp\DLAgent\DLAgentRes\*.txt %1\plutommi\.\MtkApp\DLAgent\DLAgentRes\
xcopy /y plutommi\.\MtkApp\DTVPlayer\DTVPlayerRes\*.res %1\plutommi\.\MtkApp\DTVPlayer\DTVPlayerRes\
xcopy /y plutommi\.\MtkApp\DTVPlayer\DTVPlayerRes\*.txt %1\plutommi\.\MtkApp\DTVPlayer\DTVPlayerRes\
xcopy /y plutommi\.\MtkApp\EngineerMode\EngineerModeApp\EngineerModeAppRes\*.res %1\plutommi\.\MtkApp\EngineerMode\EngineerModeApp\EngineerModeAppRes\
xcopy /y plutommi\.\MtkApp\EngineerMode\EngineerModeApp\EngineerModeAppRes\*.txt %1\plutommi\.\MtkApp\EngineerMode\EngineerModeApp\EngineerModeAppRes\
xcopy /y plutommi\.\MtkApp\FactoryMode\FactoryModeRes\*.res %1\plutommi\.\MtkApp\FactoryMode\FactoryModeRes\
xcopy /y plutommi\.\MtkApp\FactoryMode\FactoryModeRes\*.txt %1\plutommi\.\MtkApp\FactoryMode\FactoryModeRes\
xcopy /y plutommi\.\MtkApp\FileMgr\FileMgrRes\*.res %1\plutommi\.\MtkApp\FileMgr\FileMgrRes\
xcopy /y plutommi\.\MtkApp\FileMgr\FileMgrRes\*.txt %1\plutommi\.\MtkApp\FileMgr\FileMgrRes\
xcopy /y plutommi\.\MtkApp\MOT\MOTRes\*.res %1\plutommi\.\MtkApp\MOT\MOTRes\
xcopy /y plutommi\.\MtkApp\MOT\MOTRes\*.txt %1\plutommi\.\MtkApp\MOT\MOTRes\
xcopy /y plutommi\.\MtkApp\MREAPP\MREAPPRes\*.res %1\plutommi\.\MtkApp\MREAPP\MREAPPRes\
xcopy /y plutommi\.\MtkApp\MREAPP\MREAPPRes\*.txt %1\plutommi\.\MtkApp\MREAPP\MREAPPRes\
xcopy /y plutommi\.\MtkApp\MobileTVPlayer\MobileTVPlayerRes\*.res %1\plutommi\.\MtkApp\MobileTVPlayer\MobileTVPlayerRes\
xcopy /y plutommi\.\MtkApp\MobileTVPlayer\MobileTVPlayerRes\*.txt %1\plutommi\.\MtkApp\MobileTVPlayer\MobileTVPlayerRes\
xcopy /y plutommi\.\MtkApp\RightsMgr\RightsMgrRes\*.res %1\plutommi\.\MtkApp\RightsMgr\RightsMgrRes\
xcopy /y plutommi\.\MtkApp\RightsMgr\RightsMgrRes\*.txt %1\plutommi\.\MtkApp\RightsMgr\RightsMgrRes\
xcopy /y plutommi\.\MtkApp\SearchWeb\SearchWebRes\*.res %1\plutommi\.\MtkApp\SearchWeb\SearchWebRes\
xcopy /y plutommi\.\MtkApp\SearchWeb\SearchWebRes\*.txt %1\plutommi\.\MtkApp\SearchWeb\SearchWebRes\
xcopy /y plutommi\.\MtkApp\Video\VideoRes\*.res %1\plutommi\.\MtkApp\Video\VideoRes\
xcopy /y plutommi\.\MtkApp\Video\VideoRes\*.txt %1\plutommi\.\MtkApp\Video\VideoRes\
xcopy /y plutommi\.\MtkApp\Video\VideoRes\vdoply\*.res %1\plutommi\.\MtkApp\Video\VideoRes\vdoply\
xcopy /y plutommi\.\MtkApp\Video\VideoRes\vdoply\*.txt %1\plutommi\.\MtkApp\Video\VideoRes\vdoply\
xcopy /y plutommi\.\Mtkapp\GPS\GPSRes\*.res %1\plutommi\.\Mtkapp\GPS\GPSRes\
xcopy /y plutommi\.\Mtkapp\GPS\GPSRes\*.txt %1\plutommi\.\Mtkapp\GPS\GPSRes\
xcopy /y plutommi\.\Service\AlarmSrv\Res\*.res %1\plutommi\.\Service\AlarmSrv\Res\
xcopy /y plutommi\.\Service\AlarmSrv\Res\*.txt %1\plutommi\.\Service\AlarmSrv\Res\
xcopy /y plutommi\.\Service\BootupSrv\BootupSrvRes\*.res %1\plutommi\.\Service\BootupSrv\BootupSrvRes\
xcopy /y plutommi\.\Service\BootupSrv\BootupSrvRes\*.txt %1\plutommi\.\Service\BootupSrv\BootupSrvRes\
xcopy /y plutommi\.\Service\BtcmSrv\res\*.res %1\plutommi\.\Service\BtcmSrv\res\
xcopy /y plutommi\.\Service\BtcmSrv\res\*.txt %1\plutommi\.\Service\BtcmSrv\res\
xcopy /y plutommi\.\Service\CallLogSrv\CallLogSrvRes\*.res %1\plutommi\.\Service\CallLogSrv\CallLogSrvRes\
xcopy /y plutommi\.\Service\CallLogSrv\CallLogSrvRes\*.txt %1\plutommi\.\Service\CallLogSrv\CallLogSrvRes\
xcopy /y plutommi\.\Service\CallSetSrv\*.res %1\plutommi\.\Service\CallSetSrv\
xcopy /y plutommi\.\Service\CallSetSrv\*.txt %1\plutommi\.\Service\CallSetSrv\
xcopy /y plutommi\.\Service\CbmSrv\res\*.res %1\plutommi\.\Service\CbmSrv\res\
xcopy /y plutommi\.\Service\CbmSrv\res\*.txt %1\plutommi\.\Service\CbmSrv\res\
xcopy /y plutommi\.\Service\CcaSrv\CcaSrvRes\*.res %1\plutommi\.\Service\CcaSrv\CcaSrvRes\
xcopy /y plutommi\.\Service\CcaSrv\CcaSrvRes\*.txt %1\plutommi\.\Service\CcaSrv\CcaSrvRes\
xcopy /y plutommi\.\Service\CharBatSrv\*.res %1\plutommi\.\Service\CharBatSrv\
xcopy /y plutommi\.\Service\CharBatSrv\*.txt %1\plutommi\.\Service\CharBatSrv\
xcopy /y plutommi\.\Service\CloudSrv\res\*.res %1\plutommi\.\Service\CloudSrv\res\
xcopy /y plutommi\.\Service\CloudSrv\res\*.txt %1\plutommi\.\Service\CloudSrv\res\
xcopy /y plutommi\.\Service\CphsSrv\*.res %1\plutommi\.\Service\CphsSrv\
xcopy /y plutommi\.\Service\CphsSrv\*.txt %1\plutommi\.\Service\CphsSrv\
xcopy /y plutommi\.\Service\CtmSrv\*.res %1\plutommi\.\Service\CtmSrv\
xcopy /y plutommi\.\Service\CtmSrv\*.txt %1\plutommi\.\Service\CtmSrv\
xcopy /y plutommi\.\Service\DLAgentSrv\res\*.res %1\plutommi\.\Service\DLAgentSrv\res\
xcopy /y plutommi\.\Service\DLAgentSrv\res\*.txt %1\plutommi\.\Service\DLAgentSrv\res\
xcopy /y plutommi\.\Service\DtcntSrv\DtcntSrvRes\*.res %1\plutommi\.\Service\DtcntSrv\DtcntSrvRes\
xcopy /y plutommi\.\Service\DtcntSrv\DtcntSrvRes\*.txt %1\plutommi\.\Service\DtcntSrv\DtcntSrvRes\
xcopy /y plutommi\.\Service\EonsSrv\res\*.res %1\plutommi\.\Service\EonsSrv\res\
xcopy /y plutommi\.\Service\EonsSrv\res\*.txt %1\plutommi\.\Service\EonsSrv\res\
xcopy /y plutommi\.\Service\FileMgrSrv\FileMgrSrvRes\*.res %1\plutommi\.\Service\FileMgrSrv\FileMgrSrvRes\
xcopy /y plutommi\.\Service\FileMgrSrv\FileMgrSrvRes\*.txt %1\plutommi\.\Service\FileMgrSrv\FileMgrSrvRes\
xcopy /y plutommi\.\Service\GpioSrv\*.res %1\plutommi\.\Service\GpioSrv\
xcopy /y plutommi\.\Service\GpioSrv\*.txt %1\plutommi\.\Service\GpioSrv\
xcopy /y plutommi\.\Service\Gsm3gCallSrv\*.res %1\plutommi\.\Service\Gsm3gCallSrv\
xcopy /y plutommi\.\Service\Gsm3gCallSrv\*.txt %1\plutommi\.\Service\Gsm3gCallSrv\
xcopy /y plutommi\.\Service\ImpsSrv\*.res %1\plutommi\.\Service\ImpsSrv\
xcopy /y plutommi\.\Service\ImpsSrv\*.txt %1\plutommi\.\Service\ImpsSrv\
xcopy /y plutommi\.\Service\MDI\MDIRes\*.res %1\plutommi\.\Service\MDI\MDIRes\
xcopy /y plutommi\.\Service\MDI\MDIRes\*.txt %1\plutommi\.\Service\MDI\MDIRes\
xcopy /y plutommi\.\Service\MREAppMgrSrv\MREAppMgrSrvRes\*.res %1\plutommi\.\Service\MREAppMgrSrv\MREAppMgrSrvRes\
xcopy /y plutommi\.\Service\MREAppMgrSrv\MREAppMgrSrvRes\*.txt %1\plutommi\.\Service\MREAppMgrSrv\MREAppMgrSrvRes\
xcopy /y plutommi\.\Service\MREPushSrv\*.res %1\plutommi\.\Service\MREPushSrv\
xcopy /y plutommi\.\Service\MREPushSrv\*.txt %1\plutommi\.\Service\MREPushSrv\
xcopy /y plutommi\.\Service\ModeSwitchSrv\res\*.res %1\plutommi\.\Service\ModeSwitchSrv\res\
xcopy /y plutommi\.\Service\ModeSwitchSrv\res\*.txt %1\plutommi\.\Service\ModeSwitchSrv\res\
xcopy /y plutommi\.\Service\MotSrv\*.res %1\plutommi\.\Service\MotSrv\
xcopy /y plutommi\.\Service\MotSrv\*.txt %1\plutommi\.\Service\MotSrv\
xcopy /y plutommi\.\Service\NativeAppFactorySrv\NativeAppFactorySrvRes\*.res %1\plutommi\.\Service\NativeAppFactorySrv\NativeAppFactorySrvRes\
xcopy /y plutommi\.\Service\NativeAppFactorySrv\NativeAppFactorySrvRes\*.txt %1\plutommi\.\Service\NativeAppFactorySrv\NativeAppFactorySrvRes\
xcopy /y plutommi\.\Service\NotificationSettingSrv\*.res %1\plutommi\.\Service\NotificationSettingSrv\
xcopy /y plutommi\.\Service\NotificationSettingSrv\*.txt %1\plutommi\.\Service\NotificationSettingSrv\
xcopy /y plutommi\.\Service\NwInfoSrv\NwInfoSrvRes\*.res %1\plutommi\.\Service\NwInfoSrv\NwInfoSrvRes\
xcopy /y plutommi\.\Service\NwInfoSrv\NwInfoSrvRes\*.txt %1\plutommi\.\Service\NwInfoSrv\NwInfoSrvRes\
xcopy /y plutommi\.\Service\NwNameSrv\res\*.res %1\plutommi\.\Service\NwNameSrv\res\
xcopy /y plutommi\.\Service\NwNameSrv\res\*.txt %1\plutommi\.\Service\NwNameSrv\res\
xcopy /y plutommi\.\Service\PhbSrv\PhbSrvRes\*.res %1\plutommi\.\Service\PhbSrv\PhbSrvRes\
xcopy /y plutommi\.\Service\PhbSrv\PhbSrvRes\*.txt %1\plutommi\.\Service\PhbSrv\PhbSrvRes\
xcopy /y plutommi\.\Service\PlstSlimSrv\res\*.res %1\plutommi\.\Service\PlstSlimSrv\res\
xcopy /y plutommi\.\Service\PlstSlimSrv\res\*.txt %1\plutommi\.\Service\PlstSlimSrv\res\
xcopy /y plutommi\.\Service\PlstSrv\res\*.res %1\plutommi\.\Service\PlstSrv\res\
xcopy /y plutommi\.\Service\PlstSrv\res\*.txt %1\plutommi\.\Service\PlstSrv\res\
xcopy /y plutommi\.\Service\PnSrv\*.res %1\plutommi\.\Service\PnSrv\
xcopy /y plutommi\.\Service\PnSrv\*.txt %1\plutommi\.\Service\PnSrv\
xcopy /y plutommi\.\Service\ProfilesSrv\ProfilesSrvRes\*.res %1\plutommi\.\Service\ProfilesSrv\ProfilesSrvRes\
xcopy /y plutommi\.\Service\ProfilesSrv\ProfilesSrvRes\*.txt %1\plutommi\.\Service\ProfilesSrv\ProfilesSrvRes\
xcopy /y plutommi\.\Service\PushSwitchSrv\PushSwitchSrvRes\*.res %1\plutommi\.\Service\PushSwitchSrv\PushSwitchSrvRes\
xcopy /y plutommi\.\Service\PushSwitchSrv\PushSwitchSrvRes\*.txt %1\plutommi\.\Service\PushSwitchSrv\PushSwitchSrvRes\
xcopy /y plutommi\.\Service\ReminderSrv\ReminderSrvRes\*.res %1\plutommi\.\Service\ReminderSrv\ReminderSrvRes\
xcopy /y plutommi\.\Service\ReminderSrv\ReminderSrvRes\*.txt %1\plutommi\.\Service\ReminderSrv\ReminderSrvRes\
xcopy /y plutommi\.\Service\RightsMgr\Res\*.res %1\plutommi\.\Service\RightsMgr\Res\
xcopy /y plutommi\.\Service\RightsMgr\Res\*.txt %1\plutommi\.\Service\RightsMgr\Res\
xcopy /y plutommi\.\Service\SafeModeSrv\res\*.res %1\plutommi\.\Service\SafeModeSrv\res\
xcopy /y plutommi\.\Service\SafeModeSrv\res\*.txt %1\plutommi\.\Service\SafeModeSrv\res\
xcopy /y plutommi\.\Service\SatSrv\*.res %1\plutommi\.\Service\SatSrv\
xcopy /y plutommi\.\Service\SatSrv\*.txt %1\plutommi\.\Service\SatSrv\
xcopy /y plutommi\.\Service\SecSetSrv\SecSetSrvRes\*.res %1\plutommi\.\Service\SecSetSrv\SecSetSrvRes\
xcopy /y plutommi\.\Service\SecSetSrv\SecSetSrvRes\*.txt %1\plutommi\.\Service\SecSetSrv\SecSetSrvRes\
xcopy /y plutommi\.\Service\SensorSrv\*.res %1\plutommi\.\Service\SensorSrv\
xcopy /y plutommi\.\Service\SensorSrv\*.txt %1\plutommi\.\Service\SensorSrv\
xcopy /y plutommi\.\Service\SettingSrv\res\*.res %1\plutommi\.\Service\SettingSrv\res\
xcopy /y plutommi\.\Service\SettingSrv\res\*.txt %1\plutommi\.\Service\SettingSrv\res\
xcopy /y plutommi\.\Service\ShutdownSrv\ShutdownSrvRes\*.res %1\plutommi\.\Service\ShutdownSrv\ShutdownSrvRes\
xcopy /y plutommi\.\Service\ShutdownSrv\ShutdownSrvRes\*.txt %1\plutommi\.\Service\ShutdownSrv\ShutdownSrvRes\
xcopy /y plutommi\.\Service\SimCtrlSrv\SimCtrlSrvRes\*.res %1\plutommi\.\Service\SimCtrlSrv\SimCtrlSrvRes\
xcopy /y plutommi\.\Service\SimCtrlSrv\SimCtrlSrvRes\*.txt %1\plutommi\.\Service\SimCtrlSrv\SimCtrlSrvRes\
xcopy /y plutommi\.\Service\SmsSrv\*.res %1\plutommi\.\Service\SmsSrv\
xcopy /y plutommi\.\Service\SmsSrv\*.txt %1\plutommi\.\Service\SmsSrv\
xcopy /y plutommi\.\Service\SnsSrv\*.res %1\plutommi\.\Service\SnsSrv\
xcopy /y plutommi\.\Service\SnsSrv\*.txt %1\plutommi\.\Service\SnsSrv\
xcopy /y plutommi\.\Service\SoundRecSrv\res\*.res %1\plutommi\.\Service\SoundRecSrv\res\
xcopy /y plutommi\.\Service\SoundRecSrv\res\*.txt %1\plutommi\.\Service\SoundRecSrv\res\
xcopy /y plutommi\.\Service\SsSrv\*.res %1\plutommi\.\Service\SsSrv\
xcopy /y plutommi\.\Service\SsSrv\*.txt %1\plutommi\.\Service\SsSrv\
xcopy /y plutommi\.\Service\SsoSrv\*.res %1\plutommi\.\Service\SsoSrv\
xcopy /y plutommi\.\Service\SsoSrv\*.txt %1\plutommi\.\Service\SsoSrv\
xcopy /y plutommi\.\Service\TetheringSrv\TetheringSrvRes\*.res %1\plutommi\.\Service\TetheringSrv\TetheringSrvRes\
xcopy /y plutommi\.\Service\TetheringSrv\TetheringSrvRes\*.txt %1\plutommi\.\Service\TetheringSrv\TetheringSrvRes\
xcopy /y plutommi\.\Service\TodoSrv\res\*.res %1\plutommi\.\Service\TodoSrv\res\
xcopy /y plutommi\.\Service\TodoSrv\res\*.txt %1\plutommi\.\Service\TodoSrv\res\
xcopy /y plutommi\.\Service\UPPSrv\UPPSrvRes\*.res %1\plutommi\.\Service\UPPSrv\UPPSrvRes\
xcopy /y plutommi\.\Service\UPPSrv\UPPSrvRes\*.txt %1\plutommi\.\Service\UPPSrv\UPPSrvRes\
xcopy /y plutommi\.\Service\UcmSrv\UcmSrvRes\*.res %1\plutommi\.\Service\UcmSrv\UcmSrvRes\
xcopy /y plutommi\.\Service\UcmSrv\UcmSrvRes\*.txt %1\plutommi\.\Service\UcmSrv\UcmSrvRes\
xcopy /y plutommi\.\Service\UmSrv\UmSrvRes\*.res %1\plutommi\.\Service\UmSrv\UmSrvRes\
xcopy /y plutommi\.\Service\UmSrv\UmSrvRes\*.txt %1\plutommi\.\Service\UmSrv\UmSrvRes\
xcopy /y plutommi\.\Service\UmmsSrv\MMSSrvRes\*.res %1\plutommi\.\Service\UmmsSrv\MMSSrvRes\
xcopy /y plutommi\.\Service\UmmsSrv\MMSSrvRes\*.txt %1\plutommi\.\Service\UmmsSrv\MMSSrvRes\
xcopy /y plutommi\.\Service\WapPushSrv\res\*.res %1\plutommi\.\Service\WapPushSrv\res\
xcopy /y plutommi\.\Service\WapPushSrv\res\*.txt %1\plutommi\.\Service\WapPushSrv\res\
xcopy /y plutommi\.\Service\WgtMgrSrv\WgtMgrSrvRes\*.res %1\plutommi\.\Service\WgtMgrSrv\WgtMgrSrvRes\
xcopy /y plutommi\.\Service\WgtMgrSrv\WgtMgrSrvRes\*.txt %1\plutommi\.\Service\WgtMgrSrv\WgtMgrSrvRes\
xcopy /y plutommi\.\VendorApp\AVK\AVKRes\*.res %1\plutommi\.\VendorApp\AVK\AVKRes\
xcopy /y plutommi\.\VendorApp\AVK\AVKRes\*.txt %1\plutommi\.\VendorApp\AVK\AVKRes\
xcopy /y plutommi\.\VendorApp\DevApp\DevAppRes\*.res %1\plutommi\.\VendorApp\DevApp\DevAppRes\
xcopy /y plutommi\.\VendorApp\DevApp\DevAppRes\*.txt %1\plutommi\.\VendorApp\DevApp\DevAppRes\
xcopy /y plutommi\.\cui\SsoCui\SSOCuiRes\*.res %1\plutommi\.\cui\SsoCui\SSOCuiRes\
xcopy /y plutommi\.\cui\SsoCui\SSOCuiRes\*.txt %1\plutommi\.\cui\SsoCui\SSOCuiRes\
xcopy /y plutommi\.\mmi\BrowserApp\PushInbox\PushInboxRes\*.res %1\plutommi\.\mmi\BrowserApp\PushInbox\PushInboxRes\
xcopy /y plutommi\.\mmi\BrowserApp\PushInbox\PushInboxRes\*.txt %1\plutommi\.\mmi\BrowserApp\PushInbox\PushInboxRes\
xcopy /y plutommi\.\mmi\BrowserApp\UPPApp\UPPAppRes\*.res %1\plutommi\.\mmi\BrowserApp\UPPApp\UPPAppRes\
xcopy /y plutommi\.\mmi\BrowserApp\UPPApp\UPPAppRes\*.txt %1\plutommi\.\mmi\BrowserApp\UPPApp\UPPAppRes\
xcopy /y plutommi\.\mmi\CallLog\CallLogRes\*.res %1\plutommi\.\mmi\CallLog\CallLogRes\
xcopy /y plutommi\.\mmi\CallLog\CallLogRes\*.txt %1\plutommi\.\mmi\CallLog\CallLogRes\
xcopy /y plutommi\.\mmi\Cbm\CbmRes\*.res %1\plutommi\.\mmi\Cbm\CbmRes\
xcopy /y plutommi\.\mmi\Cbm\CbmRes\*.txt %1\plutommi\.\mmi\Cbm\CbmRes\
xcopy /y plutommi\.\mmi\CertificateManager\CertificateManagerRes\*.res %1\plutommi\.\mmi\CertificateManager\CertificateManagerRes\
xcopy /y plutommi\.\mmi\CertificateManager\CertificateManagerRes\*.txt %1\plutommi\.\mmi\CertificateManager\CertificateManagerRes\
xcopy /y plutommi\.\mmi\ConnectManagement\ConnectManagementRes\*.res %1\plutommi\.\mmi\ConnectManagement\ConnectManagementRes\
xcopy /y plutommi\.\mmi\ConnectManagement\ConnectManagementRes\*.txt %1\plutommi\.\mmi\ConnectManagement\ConnectManagementRes\
xcopy /y plutommi\.\mmi\CustomerService\CustomerServiceRes\*.res %1\plutommi\.\mmi\CustomerService\CustomerServiceRes\
xcopy /y plutommi\.\mmi\CustomerService\CustomerServiceRes\*.txt %1\plutommi\.\mmi\CustomerService\CustomerServiceRes\
xcopy /y plutommi\.\mmi\DataAccount\DataAccountRes\*.res %1\plutommi\.\mmi\DataAccount\DataAccountRes\
xcopy /y plutommi\.\mmi\DataAccount\DataAccountRes\*.txt %1\plutommi\.\mmi\DataAccount\DataAccountRes\
xcopy /y plutommi\.\mmi\DateTime\Res\*.res %1\plutommi\.\mmi\DateTime\Res\
xcopy /y plutommi\.\mmi\DateTime\Res\*.txt %1\plutommi\.\mmi\DateTime\Res\
xcopy /y plutommi\.\mmi\Dialer\DialerRes\*.res %1\plutommi\.\mmi\Dialer\DialerRes\
xcopy /y plutommi\.\mmi\Dialer\DialerRes\*.txt %1\plutommi\.\mmi\Dialer\DialerRes\
xcopy /y plutommi\.\mmi\Dictionary\Dict_Res\*.res %1\plutommi\.\mmi\Dictionary\Dict_Res\
xcopy /y plutommi\.\mmi\Dictionary\Dict_Res\*.txt %1\plutommi\.\mmi\Dictionary\Dict_Res\
xcopy /y plutommi\.\mmi\Extra\ExtraRes\*.res %1\plutommi\.\mmi\Extra\ExtraRes\
xcopy /y plutommi\.\mmi\Extra\ExtraRes\*.txt %1\plutommi\.\mmi\Extra\ExtraRes\
xcopy /y plutommi\.\mmi\FunAndGames\FunAndGamesRes\*.res %1\plutommi\.\mmi\FunAndGames\FunAndGamesRes\
xcopy /y plutommi\.\mmi\FunAndGames\FunAndGamesRes\*.txt %1\plutommi\.\mmi\FunAndGames\FunAndGamesRes\
xcopy /y plutommi\.\mmi\IdleScreen\IdleScreenRes\*.res %1\plutommi\.\mmi\IdleScreen\IdleScreenRes\
xcopy /y plutommi\.\mmi\IdleScreen\IdleScreenRes\*.txt %1\plutommi\.\mmi\IdleScreen\IdleScreenRes\
xcopy /y plutommi\.\mmi\Messages\MessagesRes\*.res %1\plutommi\.\mmi\Messages\MessagesRes\
xcopy /y plutommi\.\mmi\Messages\MessagesRes\*.txt %1\plutommi\.\mmi\Messages\MessagesRes\
xcopy /y plutommi\.\mmi\MiscFramework\MiscFrameworkRes\*.res %1\plutommi\.\mmi\MiscFramework\MiscFrameworkRes\
xcopy /y plutommi\.\mmi\MiscFramework\MiscFrameworkRes\*.txt %1\plutommi\.\mmi\MiscFramework\MiscFrameworkRes\
xcopy /y plutommi\.\mmi\MobileService\MobileServiceRes\*.res %1\plutommi\.\mmi\MobileService\MobileServiceRes\
xcopy /y plutommi\.\mmi\MobileService\MobileServiceRes\*.txt %1\plutommi\.\mmi\MobileService\MobileServiceRes\
xcopy /y plutommi\.\mmi\NITZHandler\NITZRes\*.res %1\plutommi\.\mmi\NITZHandler\NITZRes\
xcopy /y plutommi\.\mmi\NITZHandler\NITZRes\*.txt %1\plutommi\.\mmi\NITZHandler\NITZRes\
xcopy /y plutommi\.\mmi\Organizer\HijriCalendar\HijriCalendar_res\*.res %1\plutommi\.\mmi\Organizer\HijriCalendar\HijriCalendar_res\
xcopy /y plutommi\.\mmi\Organizer\HijriCalendar\HijriCalendar_res\*.txt %1\plutommi\.\mmi\Organizer\HijriCalendar\HijriCalendar_res\
xcopy /y plutommi\.\mmi\Organizer\IndianCalendar\IndianCalendar_res\*.res %1\plutommi\.\mmi\Organizer\IndianCalendar\IndianCalendar_res\
xcopy /y plutommi\.\mmi\Organizer\IndianCalendar\IndianCalendar_res\*.txt %1\plutommi\.\mmi\Organizer\IndianCalendar\IndianCalendar_res\
xcopy /y plutommi\.\mmi\Organizer\OrganizerRes\*.res %1\plutommi\.\mmi\Organizer\OrganizerRes\
xcopy /y plutommi\.\mmi\Organizer\OrganizerRes\*.txt %1\plutommi\.\mmi\Organizer\OrganizerRes\
xcopy /y plutommi\.\mmi\Organizer\OrganizerRes\AlarmRes\*.res %1\plutommi\.\mmi\Organizer\OrganizerRes\AlarmRes\
xcopy /y plutommi\.\mmi\Organizer\OrganizerRes\AlarmRes\*.txt %1\plutommi\.\mmi\Organizer\OrganizerRes\AlarmRes\
xcopy /y plutommi\.\mmi\Organizer\OrganizerRes\WorldClock\*.res %1\plutommi\.\mmi\Organizer\OrganizerRes\WorldClock\
xcopy /y plutommi\.\mmi\Organizer\OrganizerRes\WorldClock\*.txt %1\plutommi\.\mmi\Organizer\OrganizerRes\WorldClock\
xcopy /y plutommi\.\mmi\Organizer\Reminder\Res\*.res %1\plutommi\.\mmi\Organizer\Reminder\Res\
xcopy /y plutommi\.\mmi\Organizer\Reminder\Res\*.txt %1\plutommi\.\mmi\Organizer\Reminder\Res\
xcopy /y plutommi\.\mmi\PROFILES\Profiles_Res\*.res %1\plutommi\.\mmi\PROFILES\Profiles_Res\
xcopy /y plutommi\.\mmi\PROFILES\Profiles_Res\*.txt %1\plutommi\.\mmi\PROFILES\Profiles_Res\
xcopy /y plutommi\.\mmi\PhoneBook\PhoneBookRes\*.res %1\plutommi\.\mmi\PhoneBook\PhoneBookRes\
xcopy /y plutommi\.\mmi\PhoneBook\PhoneBookRes\*.txt %1\plutommi\.\mmi\PhoneBook\PhoneBookRes\
xcopy /y plutommi\.\mmi\SAT\SATRes\*.res %1\plutommi\.\mmi\SAT\SATRes\
xcopy /y plutommi\.\mmi\SAT\SATRes\*.txt %1\plutommi\.\mmi\SAT\SATRes\
xcopy /y plutommi\.\mmi\SSOAPP\SSOAPPRes\*.res %1\plutommi\.\mmi\SSOAPP\SSOAPPRes\
xcopy /y plutommi\.\mmi\SSOAPP\SSOAPPRes\*.txt %1\plutommi\.\mmi\SSOAPP\SSOAPPRes\
xcopy /y plutommi\.\mmi\Setting\SettingRes\*.res %1\plutommi\.\mmi\Setting\SettingRes\
xcopy /y plutommi\.\mmi\Setting\SettingRes\*.txt %1\plutommi\.\mmi\Setting\SettingRes\
xcopy /y plutommi\.\mmi\Setting\SettingRes\PenCalibration\*.res %1\plutommi\.\mmi\Setting\SettingRes\PenCalibration\
xcopy /y plutommi\.\mmi\Setting\SettingRes\PenCalibration\*.txt %1\plutommi\.\mmi\Setting\SettingRes\PenCalibration\
xcopy /y plutommi\.\mmi\Setting\SettingRes\SoundEffect\*.res %1\plutommi\.\mmi\Setting\SettingRes\SoundEffect\
xcopy /y plutommi\.\mmi\Setting\SettingRes\SoundEffect\*.txt %1\plutommi\.\mmi\Setting\SettingRes\SoundEffect\
xcopy /y plutommi\.\mmi\Tethering\TetheringRes\*.res %1\plutommi\.\mmi\Tethering\TetheringRes\
xcopy /y plutommi\.\mmi\Tethering\TetheringRes\*.txt %1\plutommi\.\mmi\Tethering\TetheringRes\
xcopy /y plutommi\.\mmi\UDX\UDXRes\*.res %1\plutommi\.\mmi\UDX\UDXRes\
xcopy /y plutommi\.\mmi\UDX\UDXRes\*.txt %1\plutommi\.\mmi\UDX\UDXRes\
xcopy /y plutommi\.\mmi\UnifiedComposer\UnifiedComposerRes\*.res %1\plutommi\.\mmi\UnifiedComposer\UnifiedComposerRes\
xcopy /y plutommi\.\mmi\UnifiedComposer\UnifiedComposerRes\*.txt %1\plutommi\.\mmi\UnifiedComposer\UnifiedComposerRes\
xcopy /y plutommi\.\mmi\UnifiedMMS\MMSApp\MMSAppRes\*.res %1\plutommi\.\mmi\UnifiedMMS\MMSApp\MMSAppRes\
xcopy /y plutommi\.\mmi\UnifiedMMS\MMSApp\MMSAppRes\*.txt %1\plutommi\.\mmi\UnifiedMMS\MMSApp\MMSAppRes\
xcopy /y plutommi\.\mmi\ebookreader\ebookres\*.res %1\plutommi\.\mmi\ebookreader\ebookres\
xcopy /y plutommi\.\mmi\ebookreader\ebookres\*.txt %1\plutommi\.\mmi\ebookreader\ebookres\
xcopy /y plutommi\.\mmi\gpio\gpiores\*.res %1\plutommi\.\mmi\gpio\gpiores\
xcopy /y plutommi\.\mmi\gpio\gpiores\*.txt %1\plutommi\.\mmi\gpio\gpiores\
xcopy /y plutommi\.\mmi\inc\*.res %1\plutommi\.\mmi\inc\
xcopy /y plutommi\.\mmi\inc\*.txt %1\plutommi\.\mmi\inc\
xcopy /y plutommi\.\mmi\messages\messagesres\*.res %1\plutommi\.\mmi\messages\messagesres\
xcopy /y plutommi\.\mmi\messages\messagesres\*.txt %1\plutommi\.\mmi\messages\messagesres\
xcopy /y plutommi\.\mmi\npr\npr_tts\res\*.res %1\plutommi\.\mmi\npr\npr_tts\res\
xcopy /y plutommi\.\mmi\npr\npr_tts\res\*.txt %1\plutommi\.\mmi\npr\npr_tts\res\
xcopy /y plutommi\.\mmi\ucm\UcmRes\*.res %1\plutommi\.\mmi\ucm\UcmRes\
xcopy /y plutommi\.\mmi\ucm\UcmRes\*.txt %1\plutommi\.\mmi\ucm\UcmRes\
xcopy /y plutommi\.\mtkapp\AudioPlayer\AudioPlayerRes\*.res %1\plutommi\.\mtkapp\AudioPlayer\AudioPlayerRes\
xcopy /y plutommi\.\mtkapp\AudioPlayer\AudioPlayerRes\*.txt %1\plutommi\.\mtkapp\AudioPlayer\AudioPlayerRes\
xcopy /y plutommi\.\mtkapp\BGSound\BGSound_Res\*.res %1\plutommi\.\mtkapp\BGSound\BGSound_Res\
xcopy /y plutommi\.\mtkapp\BGSound\BGSound_Res\*.txt %1\plutommi\.\mtkapp\BGSound\BGSound_Res\
xcopy /y plutommi\.\mtkapp\Camcorder\CamcorderRes\*.res %1\plutommi\.\mtkapp\Camcorder\CamcorderRes\
xcopy /y plutommi\.\mtkapp\Camcorder\CamcorderRes\*.txt %1\plutommi\.\mtkapp\Camcorder\CamcorderRes\
xcopy /y plutommi\.\mtkapp\CentralConfigAgent\CentralConfigAgentRes\*.res %1\plutommi\.\mtkapp\CentralConfigAgent\CentralConfigAgentRes\
xcopy /y plutommi\.\mtkapp\CentralConfigAgent\CentralConfigAgentRes\*.txt %1\plutommi\.\mtkapp\CentralConfigAgent\CentralConfigAgentRes\
xcopy /y plutommi\.\mtkapp\Connectivity\ConnectivityRes\*.res %1\plutommi\.\mtkapp\Connectivity\ConnectivityRes\
xcopy /y plutommi\.\mtkapp\Connectivity\ConnectivityRes\*.txt %1\plutommi\.\mtkapp\Connectivity\ConnectivityRes\
xcopy /y plutommi\.\mtkapp\Connectivity\ConnectivityRes\Bluetooth\*.res %1\plutommi\.\mtkapp\Connectivity\ConnectivityRes\Bluetooth\
xcopy /y plutommi\.\mtkapp\Connectivity\ConnectivityRes\Bluetooth\*.txt %1\plutommi\.\mtkapp\Connectivity\ConnectivityRes\Bluetooth\
xcopy /y plutommi\.\mtkapp\Connectivity\ConnectivityRes\USB\*.res %1\plutommi\.\mtkapp\Connectivity\ConnectivityRes\USB\
xcopy /y plutommi\.\mtkapp\Connectivity\ConnectivityRes\USB\*.txt %1\plutommi\.\mtkapp\Connectivity\ConnectivityRes\USB\
xcopy /y plutommi\.\mtkapp\DataService\DataServiceRes\*.res %1\plutommi\.\mtkapp\DataService\DataServiceRes\
xcopy /y plutommi\.\mtkapp\DataService\DataServiceRes\*.txt %1\plutommi\.\mtkapp\DataService\DataServiceRes\
xcopy /y plutommi\.\mtkapp\ImageView\ImageViewRes\*.res %1\plutommi\.\mtkapp\ImageView\ImageViewRes\
xcopy /y plutommi\.\mtkapp\ImageView\ImageViewRes\*.txt %1\plutommi\.\mtkapp\ImageView\ImageViewRes\
xcopy /y plutommi\.\mtkapp\JavaAgency\JavaAgencyRes\*.res %1\plutommi\.\mtkapp\JavaAgency\JavaAgencyRes\
xcopy /y plutommi\.\mtkapp\JavaAgency\JavaAgencyRes\*.txt %1\plutommi\.\mtkapp\JavaAgency\JavaAgencyRes\
xcopy /y plutommi\.\mtkapp\MREAPP\MREAPPRes\*.res %1\plutommi\.\mtkapp\MREAPP\MREAPPRes\
xcopy /y plutommi\.\mtkapp\MREAPP\MREAPPRes\*.txt %1\plutommi\.\mtkapp\MREAPP\MREAPPRes\
xcopy /y plutommi\.\mtkapp\MSpace\MSpaceRes\*.res %1\plutommi\.\mtkapp\MSpace\MSpaceRes\
xcopy /y plutommi\.\mtkapp\MSpace\MSpaceRes\*.txt %1\plutommi\.\mtkapp\MSpace\MSpaceRes\
xcopy /y plutommi\.\mtkapp\MediaPlayer\MediaPlayerRes\*.res %1\plutommi\.\mtkapp\MediaPlayer\MediaPlayerRes\
xcopy /y plutommi\.\mtkapp\MediaPlayer\MediaPlayerRes\*.txt %1\plutommi\.\mtkapp\MediaPlayer\MediaPlayerRes\
xcopy /y plutommi\.\mtkapp\MyFavorite\MyFavoriteRes\*.res %1\plutommi\.\mtkapp\MyFavorite\MyFavoriteRes\
xcopy /y plutommi\.\mtkapp\MyFavorite\MyFavoriteRes\*.txt %1\plutommi\.\mtkapp\MyFavorite\MyFavoriteRes\
xcopy /y plutommi\.\mtkapp\PhotoEditor\PhotoEditorRes\*.res %1\plutommi\.\mtkapp\PhotoEditor\PhotoEditorRes\
xcopy /y plutommi\.\mtkapp\PhotoEditor\PhotoEditorRes\*.txt %1\plutommi\.\mtkapp\PhotoEditor\PhotoEditorRes\
xcopy /y plutommi\.\mtkapp\Pictbridge\PictBridgeRes\*.res %1\plutommi\.\mtkapp\Pictbridge\PictBridgeRes\
xcopy /y plutommi\.\mtkapp\Pictbridge\PictBridgeRes\*.txt %1\plutommi\.\mtkapp\Pictbridge\PictBridgeRes\
xcopy /y plutommi\.\mtkapp\PushSwitch\PushSwitchRes\*.res %1\plutommi\.\mtkapp\PushSwitch\PushSwitchRes\
xcopy /y plutommi\.\mtkapp\PushSwitch\PushSwitchRes\*.txt %1\plutommi\.\mtkapp\PushSwitch\PushSwitchRes\
xcopy /y plutommi\.\mtkapp\Sndrec\SndrecRes\*.res %1\plutommi\.\mtkapp\Sndrec\SndrecRes\
xcopy /y plutommi\.\mtkapp\Sndrec\SndrecRes\*.txt %1\plutommi\.\mtkapp\Sndrec\SndrecRes\
xcopy /y plutommi\.\mtkapp\SyncML\SyncMLRes\*.res %1\plutommi\.\mtkapp\SyncML\SyncMLRes\
xcopy /y plutommi\.\mtkapp\SyncML\SyncMLRes\*.txt %1\plutommi\.\mtkapp\SyncML\SyncMLRes\
xcopy /y plutommi\.\mtkapp\camera\camerares\*.res %1\plutommi\.\mtkapp\camera\camerares\
xcopy /y plutommi\.\mtkapp\camera\camerares\*.txt %1\plutommi\.\mtkapp\camera\camerares\
xcopy /y plutommi\.\mtkapp\sdk\sdkres\*.res %1\plutommi\.\mtkapp\sdk\sdkres\
xcopy /y plutommi\.\mtkapp\sdk\sdkres\*.txt %1\plutommi\.\mtkapp\sdk\sdkres\
xcopy /y plutommi\.\mtkapp\vObjects\vObjectRes\*.res %1\plutommi\.\mtkapp\vObjects\vObjectRes\
xcopy /y plutommi\.\mtkapp\vObjects\vObjectRes\*.txt %1\plutommi\.\mtkapp\vObjects\vObjectRes\
xcopy /y plutommi\.\service\AppMgrSrv\AppMgrSrvRes\*.res %1\plutommi\.\service\AppMgrSrv\AppMgrSrvRes\
xcopy /y plutommi\.\service\AppMgrSrv\AppMgrSrvRes\*.txt %1\plutommi\.\service\AppMgrSrv\AppMgrSrvRes\
xcopy /y plutommi\.\service\BrowserSrv\res\*.res %1\plutommi\.\service\BrowserSrv\res\
xcopy /y plutommi\.\service\BrowserSrv\res\*.txt %1\plutommi\.\service\BrowserSrv\res\
xcopy /y plutommi\.\service\CnmgrSrv\CnmgrSrvRes\*.res %1\plutommi\.\service\CnmgrSrv\CnmgrSrvRes\
xcopy /y plutommi\.\service\CnmgrSrv\CnmgrSrvRes\*.txt %1\plutommi\.\service\CnmgrSrv\CnmgrSrvRes\
xcopy /y plutommi\.\service\DmSRsrv\*.res %1\plutommi\.\service\DmSRsrv\
xcopy /y plutommi\.\service\DmSRsrv\*.txt %1\plutommi\.\service\DmSRsrv\
xcopy /y plutommi\.\service\DmSrv\DmSrvRes\*.res %1\plutommi\.\service\DmSrv\DmSrvRes\
xcopy /y plutommi\.\service\DmSrv\DmSrvRes\*.txt %1\plutommi\.\service\DmSrv\DmSrvRes\
xcopy /y plutommi\.\service\NetSetSrv\res\*.res %1\plutommi\.\service\NetSetSrv\res\
xcopy /y plutommi\.\service\NetSetSrv\res\*.txt %1\plutommi\.\service\NetSetSrv\res\
xcopy /y plutommi\.\service\datalocksrv\res\*.res %1\plutommi\.\service\datalocksrv\res\
xcopy /y plutommi\.\service\datalocksrv\res\*.txt %1\plutommi\.\service\datalocksrv\res\
xcopy /y plutommi\.\service\nitzsrv\res\*.res %1\plutommi\.\service\nitzsrv\res\
xcopy /y plutommi\.\service\nitzsrv\res\*.txt %1\plutommi\.\service\nitzsrv\res\
xcopy /y plutommi\.\service\settingsrv\res\*.res %1\plutommi\.\service\settingsrv\res\
xcopy /y plutommi\.\service\settingsrv\res\*.txt %1\plutommi\.\service\settingsrv\res\
xcopy /y plutommi\.\service\usbsrv\UsbSrvRes\*.res %1\plutommi\.\service\usbsrv\UsbSrvRes\
xcopy /y plutommi\.\service\usbsrv\UsbSrvRes\*.txt %1\plutommi\.\service\usbsrv\UsbSrvRes\
