/* Needed header files of the compile option in XML files, if you need others need to add here */
#include "mmi_features.h"

/* Need this line to tell parser that XML start, must after all #include. */
<?xml version="1.0" encoding="UTF-8"?>

/* APP tag, include your app name defined in MMIDataType.h */
<APP id="VAPP_SECSET" name="STR_ID_VAPP_SECSET_PHONE_AND_SIM_SETTING" type="venus">

    /* When you use any ID of other module, you need to add
       that header file here, so that Resgen can find the ID */
    <!--Include Area-->
    <INCLUDE file="GlobalResDef.h"/>

    <!-----------------------------------------------------String Resource Area----------------------------------------------------->
    /* String ID of you Application, we will get string from ref_list.txt for all languages */
    //<STRING id="STR_ID_VAPP_SECSET_CATEGORY_NAME"/>
    <STRING id="STR_ID_VAPP_SECSET_PHONE_AND_SIM"/>
    <STRING id="STR_ID_VAPP_SECSET_CHANGE_PASSWORD"/>
    <STRING id="STR_ID_VAPP_SECSET_PHONE_LOCK"/>
    <STRING id="STR_ID_VAPP_SECSET_TEMP_FAIL"/>
    <STRING id="STR_ID_VAPP_SECSET_INVALID_FORMAT"/>
    <STRING id="STR_ID_VAPP_SECSET_INVALID_LENGTH"/>
    <STRING id="STR_ID_VAPP_SECSET_POWER_OFF"/>
    //<STRING id="STR_ID_VAPP_SECSET_SIM_NOT_INSERTED"/>
#if (MMI_MAX_SIM_NUM >= 2)
    <STRING id="STR_ID_VAPP_SECSET_SELECT_SIM"/>
#endif
    //<STRING id="STR_ID_VAPP_SECSET_PHONE_SETTING"/>
    <STRING id="STR_ID_VAPP_SECSET_CHV1_LOCK"/>
    <STRING id="STR_ID_VAPP_SECSET_CHANGE_CHV1_PASSWORD"/>
    <STRING id="STR_ID_VAPP_SECSET_CHANGE_CHV2_PASSWORD"/>
    <STRING id="STR_ID_VAPP_SECSET_EMERGENCY"/>
    <STRING id="STR_ID_VAPP_SECSET_INPUT_PHONE_PASSWORD"/>
    <STRING id="STR_ID_VAPP_SECSET_WRONG_PHONE_PASSWORD"/>
    <STRING id="STR_ID_VAPP_SECSET_OLD_PHONE_PASSWORD"/>
    <STRING id="STR_ID_VAPP_SECSET_NEW_PHONE_PASSWORD"/>
    <STRING id="STR_ID_VAPP_SECSET_CONFIRM_NEW_PHONE_PASSWORD"/>
    <STRING id="STR_ID_VAPP_SECSET_DIFF_NEW_PHONE_PASSWORD"/>
    <STRING id="STR_ID_VAPP_SECSET_PHONE_PASSWORD_CHANGED"/>
    <STRING id="STR_ID_VAPP_SECSET_REMAINING_TRIALS_PROMPT"/>
    <STRING id="STR_ID_VAPP_SECSET_ENABLE_CHV1_PROMPT"/>
    <STRING id="STR_ID_VAPP_SECSET_CHV2_DISABLED"/>
    <STRING id="STR_ID_VAPP_SECSET_CONFIRM_NEW_CHV1"/>
    <STRING id="STR_ID_VAPP_SECSET_CONFIRM_NEW_CHV2"/>
    <STRING id="STR_ID_VAPP_SECSET_CHV1_NOT_MATCH"/> /* Also used by SSC */
    <STRING id="STR_ID_VAPP_SECSET_CHV2_NOT_MATCH"/>
    <STRING id="STR_ID_VAPP_SECSET_SIM_ERROR"/>
    <STRING id="STR_ID_VAPP_SECSET_INPUT_CHV1"/>
    <STRING id="STR_ID_VAPP_SECSET_WRONG_CHV1"/>
    <STRING id="STR_ID_VAPP_SECSET_INPUT_CHV2"/>
    <STRING id="STR_ID_VAPP_SECSET_WRONG_CHV2"/>
    <STRING id="STR_ID_VAPP_SECSET_INPUT_UBCHV1"/>
    <STRING id="STR_ID_VAPP_SECSET_WRONG_UBCHV1"/>
    <STRING id="STR_ID_VAPP_SECSET_INPUT_UBCHV2"/>
    <STRING id="STR_ID_VAPP_SECSET_WRONG_UBCHV2"/>
    <STRING id="STR_ID_VAPP_SECSET_OLD_CHV1"/>
    <STRING id="STR_ID_VAPP_SECSET_OLD_CHV2"/>
    <STRING id="STR_ID_VAPP_SECSET_NEW_CHV1"/>
    <STRING id="STR_ID_VAPP_SECSET_NEW_CHV2"/>
    <STRING id="STR_ID_VAPP_SECSET_CHV1_BLOCKED"/>
    <STRING id="STR_ID_VAPP_SECSET_CHV2_BLOCKED"/>
    <STRING id="STR_ID_VAPP_SECSET_CHV1_BLOCKED_REQ_UBCHV"/>
    <STRING id="STR_ID_VAPP_SECSET_CHV2_BLOCKED_REQ_UBCHV"/>
    <STRING id="STR_ID_VAPP_SECSET_SIM_BLOCKED"/>
    <STRING id="STR_ID_VAPP_SECSET_UBCHV1_BLOCKED"/>
    <STRING id="STR_ID_VAPP_SECSET_UBCHV2_BLOCKED"/>
    <STRING id="STR_ID_VAPP_SECSET_CHV1_CHANGED"/>
    <STRING id="STR_ID_VAPP_SECSET_CHV2_CHANGED"/>
    <STRING id="STR_ID_VAPP_SECSET_CHV1_UNBLOCKED"/>
    <STRING id="STR_ID_VAPP_SECSET_CHV2_UNBLOCKED"/>
#if (MMI_MAX_SIM_NUM >= 2)
    <STRING id="STR_ID_VAPP_SECSET_SIMX_INPUT_CHV1"/>
    <STRING id="STR_ID_VAPP_SECSET_SIMX_INPUT_CHV2"/>
    <STRING id="STR_ID_VAPP_SECSET_SIMX_INPUT_UBCHV1"/>
    <STRING id="STR_ID_VAPP_SECSET_SIMX_INPUT_UBCHV2"/>
    <STRING id="STR_ID_VAPP_SECSET_SIMX_OLD_CHV1"/>
    <STRING id="STR_ID_VAPP_SECSET_SIMX_OLD_CHV2"/>
    <STRING id="STR_ID_VAPP_SECSET_SIMX_NEW_CHV1"/>
    <STRING id="STR_ID_VAPP_SECSET_SIMX_NEW_CHV2"/>
    <STRING id="STR_ID_VAPP_SECSET_SIMX_CHV1_BLOCKED"/>
    <STRING id="STR_ID_VAPP_SECSET_SIMX_CHV2_BLOCKED"/>
    <STRING id="STR_ID_VAPP_SECSET_SIMX_CHV1_BLOCKED_REQ_UBCHV"/>
    <STRING id="STR_ID_VAPP_SECSET_SIMX_CHV2_BLOCKED_REQ_UBCHV"/>
    <STRING id="STR_ID_VAPP_SECSET_SIMX_BLOCKED"/>
    <STRING id="STR_ID_VAPP_SECSET_SIMX_UBCHV1_BLOCKED"/>
    <STRING id="STR_ID_VAPP_SECSET_SIMX_UBCHV2_BLOCKED"/>
    <STRING id="STR_ID_VAPP_SECSET_SIMX_CHV1_CHANGED"/>
    <STRING id="STR_ID_VAPP_SECSET_SIMX_CHV2_CHANGED"/>
    <STRING id="STR_ID_VAPP_SECSET_SIMX_CHV1_UNBLOCKED"/>
    <STRING id="STR_ID_VAPP_SECSET_SIMX_CHV2_UNBLOCKED"/>
#endif /* (MMI_MAX_SIM_NUM >= 2) */

    <!------------------------------------------------------Other Resource---------------------------------------------------------->
    <MEMORY base="300000"/>

    <RECEIVER id="EVT_ID_SRV_SIM_CTRL_AVAILABILITY_CHANGED" proc="vapp_secset_on_sim_availability_changed"/>

</APP>

