/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_app_mainmenu.c
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   MTK resgenerator XML parser
 *
 *******************************************************************************/
#include "CustDataProts.h"
#include "mmi_rp_app_mainmenu_def.h"

/* Application specified header files for using old res IDs */
#include "MMI_features.h"
#include "MMIDataType.h"    /* for resource base */

#include "CustResDef.h"         /* for image/audio path */
#include "GlobalMenuItems.h"    /* for menu resource */

#include "GlobalResDef.h"
#include "SettingResDef.h"
#include "Extraresdef.h"
#include "UcmResdef.h"
#include "GlobalMenuItems.h"
#include "CustMenuRes.h"
#include "mmi_rp_all_defs.h"


/*****************************************************************************
* FUNCTION
*  mmi_rp_app_mainmenu_populate
* DESCRIPTION
*  Automatically generated populate function for mmi_rp_app_mainmenu_populate
* PARAMETERS
*  void
* RETURNS
*  void
*****************************************************************************/
void mmi_rp_app_mainmenu_populate(void)
{
    /*----------------------------------------------------------------*/
    /* Local Variables                                                */
    /*----------------------------------------------------------------*/

    /*----------------------------------------------------------------*/
    /* Code Body                                                      */
    /*----------------------------------------------------------------*/

/******************** Menu resource IDs - begin ********************/
    ADD_APPLICATION_MENUITEM5((
        MAIN_MENU_FILE_MNGR_MENUID,
        IDLE_SCREEN_MENU_ID,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        MAIN_MENU_FILE_MNGR_TEXT,
        MAIN_MENU_FILEMNGR_ICON));

    ADD_APPLICATION_MENUITEM5((
        MAIN_MENU_PHONEBOOK_MENUID,
        IDLE_SCREEN_MENU_ID,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        MAIN_MENU_PHONEBOOK_TEXT,
        MAIN_MENU_PHONEBOOK_ICON));

    ADD_APPLICATION_MENUITEM5((
        MAIN_MENU_FUNANDGAMES_MENUID,
        IDLE_SCREEN_MENU_ID,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_APP_MAIN,
        MAIN_MENU_FUNANDGAMES_TEXT,
        MAIN_MENU_FUNANDGAMES_ICON));

    ADD_APPLICATION_MENUITEM5((
        MAIN_MENU_EXTRA_MENUID,
        0,
        1,
        EXTRA_CALCULATOR_MENU,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_APP_MAIN,
        MAIN_MENU_EXTRA_TEXT,
        MAIN_MENU_EXTRA_ICON));

    ADD_APPLICATION_MENUITEM5((
        MAIN_MENU_CALL_LOG,
        MAIN_MENU_CALL_CENTER,
        7,
        MENU_ID_CLOG_MISSED_CALL,
        MENU_ID_CLOG_DIALED_CALL,
        MENU_ID_CLOG_RECVED_CALL,
        MENU_ID_CLOG_ALL_CALL,
        MENU_ID_CLOG_CALL_TIME,
        MENU_ID_CLOG_CALL_COST,
        MENU_ID_CLOG_GPRS_COUNT,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_APP_MAIN,
        MAIN_MENU_CALL_LOG_TEXT,
        IMG_ID_CLOG_MAIN_ICON));

    ADD_APPLICATION_MENUITEM5((
        MAIN_MENU_MULTIMEDIA_MENUID,
        IDLE_SCREEN_MENU_ID,
        4,
        MENU_ID_CAMERA_APP,
        MENU_ID_IMGVIEW_APP,
        MENU_ID_MOT_APP,
        MENU_ID_SNDREC_MAIN,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_APP_MAIN,
        MAIN_MENU_MMEDIA_TEXT,
        MAIN_MENU_MULTIMEDIA_ICON));

    ADD_APPLICATION_MENUITEM5((
        MAIN_MENU_SERVICES_MENUID,
        IDLE_SCREEN_MENU_ID,
        19,
        MENU_ID_RMGR,
        MENU_ID_SAT1_ENTRY,
        MENU_ID_MRE_APP_CALCULATOR_SHORTCUT,
        MENU_ID_MRE_APP_HEALTH_SHORTCUT,
        MENU_ID_MRE_APP_STOPWATCH_SHORTCUT,
        MENU_ID_MRE_APP_CONVERTER_SHORTCUT,
        MENU_ID_MRE_APP_ZAKAT_SHORTCUT,
        MENU_ID_MRE_APP_EGYPTCODE_SHORTCUT,
        MENU_ID_MRE_APP_GIRLSLOT_SHORTCUT,
        MENU_ID_MRE_APP_GOLDMINER_SHORTCUT,
        MENU_ID_MRE_APP_HAPPYEGG_SHORTCUT,
        MENU_ID_MRE_APP_HAPPYWAR_SHORTCUT,
        MENU_ID_MRE_APP_KINGCOMBAT_SHORTCUT,
        MENU_ID_MRE_APP_MOTO_SHORTCUT,
        MENU_ID_MRE_APP_PARKOUR_SHORTCUT,
        MENU_ID_MRE_APP_TWITTER_SHORTCUT,
        MENU_ID_MRE_APP_GAMELOFT_LIVE_SHORTCUT,
        MENU_ID_MRE_APP_GMOBI_APPSTORE_SHORTCUT,
        MENU_ID_MRE_APP_MBOUNCE_APPSTORE_SHORTCUT,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_APP_MAIN,
        MAIN_MENU_SERVICES_TEXT,
        MAIN_MENU_SERVICES_ICON));

    ADD_APPLICATION_MENUITEM5((
        MAIN_MENU_ORGANIZER_MENUID,
        0,
        4,
        ORGANIZER_CALENDER_MENU,
        ORGANIZER_TODOLIST_MENU,
        ORGANIZER_ALARM_MENU,
        ORGANIZER_WORLDCLOCK_MENU,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_APP_MAIN,
        MAIN_MENU_ORGANIZER_TEXT,
        MAIN_MENU_ORGANIZER_ICON));

    ADD_APPLICATION_MENUITEM5((
        MAIN_MENU_SETTINGS_MENUID,
        IDLE_SCREEN_MENU_ID,
        7,
        MAIN_MENU_PROFILES_MENUID,
        MENU9102_INITIAL_SETUP,
        MENU_ID_NETSET_MAIN,
        MENU_ID_SECSET_MAIN_MENU,
        MENU_ID_CONNECTIVITY,
        MENU_ID_NSS_APP,
        MENU_SETTING_RESTORE,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_APP_MAIN,
        MAIN_MENU_SETTINGS_TEXT,
        MAIN_MENU_SETTINGS_ICON));

    ADD_APPLICATION_MENUITEM5((
        MAIN_MENU_SETTINGS_NO_SIM_MENUID,
        0,
        6,
        MENU9102_INITIAL_SETUP,
        MENU_ID_NETSET_MAIN,
        MENU_ID_SECSET_MAIN_MENU,
        MENU_ID_CONNECTIVITY,
        MENU_ID_NSS_APP,
        MENU_SETTING_RESTORE,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        MAIN_MENU_SETTINGS_TEXT,
        MAIN_MENU_SETTINGS_ICON));

    ADD_APPLICATION_MENUITEM5((
        MAIN_MENU_CALL_CENTER,
        IDLE_SCREEN_MENU_ID,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CALLSET_CALL_CENTER,
        MAIN_MENU_CALL_LOG_ICON));

    ADD_APPLICATION_MENUITEM5((
        MAIN_MENU_TOOLS_MENUID,
        IDLE_SCREEN_MENU_ID,
        5,
        ORGANIZER_CALENDER_MENU,
        ORGANIZER_TODOLIST_MENU,
        ORGANIZER_ALARM_MENU,
        ORGANIZER_WORLDCLOCK_MENU,
        EXTRA_CALCULATOR_MENU,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_APP_MAIN,
        MAIN_MENU_TOOLS_TEXT,
        MAIN_MENU_TOOLS_ICON));

    ADD_APPLICATION_MENUITEM5((
        IDLE_SCREEN_MENU_ID,
        0,
        9,
        MAIN_MENU_FILE_MNGR_MENUID,
        MAIN_MENU_PHONEBOOK_MENUID,
        MAIN_MENU_FUNANDGAMES_MENUID,
        MAIN_MENU_CALL_CENTER,
        MAIN_MENU_MESSAGES_MENUID,
        MAIN_MENU_MULTIMEDIA_MENUID,
        MAIN_MENU_SERVICES_MENUID,
        MAIN_MENU_SETTINGS_MENUID,
        MAIN_MENU_TOOLS_MENUID,
        SHOW,
        NONMOVEABLE,
        MATRIX_MENU,
        MAIN_MENU_MENU_TEXT,
        MAIN_MENU_PHONEBOOK_ICON));

/******************** Menu resource IDs - finish ********************/

/******************** Menu Hilite/Hint Handlers - begin ********************/
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MAIN_MENU_FILE_MNGR_MENUID, highlight_mainmenu_filemngr);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MAIN_MENU_PHONEBOOK_MENUID, highlight_mainmenu_phonebook);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MAIN_MENU_FUNANDGAMES_MENUID, highlight_mainmenu_funandgames);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MAIN_MENU_EXTRA_MENUID, highlight_mainmenu_extra);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MAIN_MENU_CALL_LOG, highlight_mainmenu_calllog);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MAIN_MENU_MULTIMEDIA_MENUID, highlight_mainmenu_multimedia);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MAIN_MENU_SERVICES_MENUID, highlight_mainmenu_services);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MAIN_MENU_ORGANIZER_MENUID, highlight_mainmenu_organizer);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MAIN_MENU_SETTINGS_MENUID, highlight_mainmenu_settings);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MAIN_MENU_SETTINGS_NO_SIM_MENUID, highlight_mainmenu_settings);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MAIN_MENU_CALL_CENTER, highlight_mainmenu_callcenter);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MAIN_MENU_TOOLS_MENUID, highlight_mainmenu_tools);
/******************** Menu Hilite/Hint Handlers - finish ********************/
}
