/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_app_unifiedcomposer.c
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   MTK resgenerator XML parser
 *
 *******************************************************************************/
#include "CustDataProts.h"
#include "mmi_rp_app_unifiedcomposer_def.h"

/* Application specified header files for using old res IDs */
#include "MMI_features.h"
#include "MMIDataType.h"    /* for resource base */

#include "CustResDef.h"         /* for image/audio path */
#include "GlobalMenuItems.h"    /* for menu resource */

#include "GlobalResDef.h"
#include "mmi_rp_srv_editor_def.h"


/*****************************************************************************
* FUNCTION
*  mmi_rp_app_unifiedcomposer_populate
* DESCRIPTION
*  Automatically generated populate function for mmi_rp_app_unifiedcomposer_populate
* PARAMETERS
*  void
* RETURNS
*  void
*****************************************************************************/
void mmi_rp_app_unifiedcomposer_populate(void)
{
    /*----------------------------------------------------------------*/
    /* Local Variables                                                */
    /*----------------------------------------------------------------*/

    /*----------------------------------------------------------------*/
    /* Code Body                                                      */
    /*----------------------------------------------------------------*/

/******************** Menu resource IDs - begin ********************/
    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_OPT,
        0,
        18,
        MENU_ID_UC_OPT_SEND,
        MENU_ID_UC_OPT_ADD_RECIPIENT,
        MENU_ID_EDITOR_OPT_INSERT_SYMBOL,
        MENU_ID_EDITOR_OPT_INPUT_METHOD,
        MENU_ID_EDITOR_OPT_INPUT_METHOD_OPTIONS,
        MENU_ID_UC_OPT_HEADER_OPTIONS,
        MENU_ID_UC_OPT_PICTURE_OPTIONS,
        MENU_ID_UC_OPT_SOUND_OPTIONS,
        MENU_ID_UC_OPT_VIDEO_OPTIONS,
        MENU_ID_UC_OPT_ATTACHMENT_OPTIONS,
        MENU_ID_UC_OPT_ADD_PICTURE,
        MENU_ID_UC_OPT_ADD_SOUND,
        MENU_ID_UC_OPT_ADD_VIDEO,
        MENU_ID_UC_OPT_PREVIEW,
        MENU_ID_UC_OPT_SLIDE_OPT,
        MENU_ID_UC_OPT_ADVANCED,
        MENU_ID_UC_OPT_SAVE_TO_DRAFT,
        MENU_ID_UC_OPT_SEND_OPT,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_OPTIONS,
        IMG_UC_ENTRY_SCRN_CAPTION_ID));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_OPT_SEND,
        MENU_ID_UC_OPT,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_SEND,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_OPT_ADD_RECIPIENT,
        MENU_ID_UC_OPT,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_UC_ADD_RECIPIENT_ID,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_OPT_HEADER_OPTIONS,
        MENU_ID_UC_OPT,
        3,
        MENU_ID_UC_OPT_HEADER_OPT_CC,
        MENU_ID_UC_OPT_HEADER_OPT_BCC,
        MENU_ID_UC_OPT_HEADER_OPT_SUBJECT,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_UC_HEADER_OPTIONS_ID,
        IMG_UC_ENTRY_SCRN_CAPTION_ID));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_OPT_HEADER_OPT_CC,
        MENU_ID_UC_OPT_HEADER_OPTIONS,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_UC_CC_ID,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_OPT_HEADER_OPT_BCC,
        MENU_ID_UC_OPT_HEADER_OPTIONS,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_UC_BCC_ID,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_OPT_HEADER_OPT_SUBJECT,
        MENU_ID_UC_OPT_HEADER_OPTIONS,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_SUBJECT,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_OPT_PICTURE_OPTIONS,
        MENU_ID_UC_OPT,
        1,
        MENU_ID_UC_OPT_PICTURE_OPT_IMAGE_REMOVE,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_UC_PICTURE_OPTIONS_ID,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_OPT_PICTURE_OPT_IMAGE_REMOVE,
        MENU_ID_UC_OPT_PICTURE_OPTIONS,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_UC_REMOVE_PICTURE_ID,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_OPT_SOUND_OPTIONS,
        MENU_ID_UC_OPT,
        1,
        MENU_ID_UC_OPT_AUDIO_OPT_AUDIO_REMOVE,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_UC_SOUND_OPTIONS_ID,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_OPT_AUDIO_OPT_AUDIO_REMOVE,
        MENU_ID_UC_OPT_SOUND_OPTIONS,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_UC_REMOVE_AUDIO_ID,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_OPT_VIDEO_OPTIONS,
        MENU_ID_UC_OPT,
        1,
        MENU_ID_UC_OPT_VIDEO_OPT_VIDEO_REMOVE,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_UC_VIDEO_OPTIONS_ID,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_OPT_VIDEO_OPT_VIDEO_REMOVE,
        MENU_ID_UC_OPT_VIDEO_OPTIONS,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_UC_REMOVE_VIDEO_ID,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_OPT_ATTACHMENT_OPTIONS,
        MENU_ID_UC_OPT,
        1,
        MENU_ID_UC_OPT_ATTACH_OPT_ATTACHMENT_REMOVE,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_UC_ATTACHMENT_OPTIONS_ID,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_OPT_ATTACH_OPT_ATTACHMENT_REMOVE,
        MENU_ID_UC_OPT_ATTACHMENT_OPTIONS,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_UC_REMOVE_ATTACHMENT_ID,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_OPT_ADD_PICTURE,
        MENU_ID_UC_OPT,
        1,
        MENU_ID_UC_OPT_INSERT_IMAGE,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_UC_ADD_PICTURE_ID,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_OPT_INSERT_IMAGE,
        MENU_ID_UC_OPT_ADD_PICTURE,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_UC_ADD_MY_PICTURES_ID,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_OPT_ADD_SOUND,
        MENU_ID_UC_OPT,
        1,
        MENU_ID_UC_OPT_INSERT_AUDIO,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_UC_ADD_SOUND_ID,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_OPT_INSERT_AUDIO,
        MENU_ID_UC_OPT_ADD_SOUND,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_UC_ADD_MY_SOUNDS_ID,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_OPT_ADD_VIDEO,
        MENU_ID_UC_OPT,
        1,
        MENU_ID_UC_OPT_INSERT_VIDEO,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_UC_ADD_VIDEO_ID,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_OPT_INSERT_VIDEO,
        MENU_ID_UC_OPT_ADD_VIDEO,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_UC_ADD_MY_VIDEOS_ID,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_OPT_PREVIEW,
        MENU_ID_UC_OPT,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_UC_PREVIEW_MMS_ID,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_OPT_SLIDE_OPT,
        MENU_ID_UC_OPT,
        6,
        MENU_ID_UC_OPT_SLIDE_OPT_INSERT,
        MENU_ID_UC_OPT_SLIDE_OPT_INSERT_BEFORE,
        MENU_ID_UC_OPT_SLIDE_OPT_TIMING,
        MENU_ID_UC_OPT_SLIDE_OPT_DELETE,
        MENU_ID_UC_OPT_SLIDE_OPT_NEXT,
        MENU_ID_UC_OPT_SLIDE_OPT_PREVIOUS,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_UC_SLIDE_OPTION_ID,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_OPT_SLIDE_OPT_INSERT,
        MENU_ID_UC_OPT_SLIDE_OPT,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_UC_ADD_NEW_SLIDE_AFTER_ID,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_OPT_SLIDE_OPT_INSERT_BEFORE,
        MENU_ID_UC_OPT_SLIDE_OPT,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_UC_ADD_NEW_SLIDE_BEFORE_ID,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_OPT_SLIDE_OPT_TIMING,
        MENU_ID_UC_OPT_SLIDE_OPT,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_UC_SLIDE_TIMING_ID,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_OPT_SLIDE_OPT_DELETE,
        MENU_ID_UC_OPT_SLIDE_OPT,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_UC_DELETE_SLIDE_ID,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_OPT_SLIDE_OPT_NEXT,
        MENU_ID_UC_OPT_SLIDE_OPT,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_UC_GO_TO_NEXT_SLIDE_ID,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_OPT_SLIDE_OPT_PREVIOUS,
        MENU_ID_UC_OPT_SLIDE_OPT,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_UC_GO_TO_PREVIOUS_SLIDE_ID,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_OPT_ADVANCED,
        MENU_ID_UC_OPT,
        2,
        MENU_ID_UC_OPT_INSERT_TEXT_TEMPLATE,
        MENU_ID_UC_OPT_INSERT_ATTACHMENT,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_UC_ADVANCED_ID,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_OPT_INSERT_TEXT_TEMPLATE,
        MENU_ID_UC_OPT_ADVANCED,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_UC_INSERT_TEXT_TEMPLATE_ID,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_OPT_INSERT_ATTACHMENT,
        MENU_ID_UC_OPT_ADVANCED,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_UC_INSERT_ATTACHMENT_ID,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_OPT_SAVE_TO_DRAFT,
        MENU_ID_UC_OPT,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_SAVE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_OPT_SEND_OPT,
        MENU_ID_UC_OPT,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_UC_SEND_OPTION_ID,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_EDITOR_OPTION,
        0,
        5,
        MENU_ID_UC_EDITOR_OPTION_DONE,
        MENU_ID_UC_EDITOR_OPTION_CANCEL,
        MENU_ID_EDITOR_OPT_INSERT_SYMBOL,
        MENU_ID_EDITOR_OPT_INPUT_METHOD,
        MENU_ID_EDITOR_OPT_INPUT_METHOD_OPTIONS,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_OPTIONS,
        IMG_GLOBAL_OPTIONS));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_EDITOR_OPTION_DONE,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_DONE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_EDITOR_OPTION_CANCEL,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_CANCEL,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_OPT_REMOVE,
        0,
        5,
        MENU_ID_UC_OPT_REMOVE_IMAGE,
        MENU_ID_UC_OPT_REMOVE_AUDIO,
        MENU_ID_UC_OPT_REMOVE_VIDEO,
        MENU_ID_UC_OPT_REMOVE_ATTACHMENT,
        MENU_ID_UC_OPT_DONE_SEND,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_REMOVE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_OPT_REMOVE_IMAGE,
        MENU_ID_UC_OPT_REMOVE,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_UC_REMOVE_PICTURE_ID,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_OPT_REMOVE_AUDIO,
        MENU_ID_UC_OPT_REMOVE,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_UC_REMOVE_AUDIO_ID,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_OPT_REMOVE_VIDEO,
        MENU_ID_UC_OPT_REMOVE,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_UC_REMOVE_VIDEO_ID,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_OPT_REMOVE_ATTACHMENT,
        MENU_ID_UC_OPT_REMOVE,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_UC_REMOVE_ATTACHMENT_ID,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_OPT_DONE_SEND,
        MENU_ID_UC_OPT_REMOVE,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_SEND,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_EXIT_OPT,
        0,
        2,
        MENU_ID_UC_EXIT_OPT_SAVE,
        MENU_ID_UC_EXIT_OPT_EXIT,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_OPTIONS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_EXIT_OPT_SAVE,
        MENU_ID_UC_EXIT_OPT,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_SAVE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_EXIT_OPT_EXIT,
        MENU_ID_UC_EXIT_OPT,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_EXIT,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_UC_OPT_MSG_TYPE_OPT,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_UC_MESSAGE_TYPE_ID,
        0));

/******************** Menu resource IDs - finish ********************/

/******************** Menu Hilite/Hint Handlers - begin ********************/
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_UC_OPT_SEND, mmi_uc_highlight_send);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_UC_OPT_PICTURE_OPTIONS, mmi_uc_highlight_opt_picture_options);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_UC_OPT_PICTURE_OPT_IMAGE_REMOVE, mmi_uc_highlight_remove_image);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_UC_OPT_SOUND_OPTIONS, mmi_uc_highlight_opt_sound_options);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_UC_OPT_AUDIO_OPT_AUDIO_REMOVE, mmi_uc_highlight_remove_audio);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_UC_OPT_VIDEO_OPTIONS, mmi_uc_highlight_opt_video_options);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_UC_OPT_VIDEO_OPT_VIDEO_REMOVE, mmi_uc_highlight_remove_video);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_UC_OPT_ATTACHMENT_OPTIONS, mmi_uc_highlight_opt_attachment_options);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_UC_OPT_ATTACH_OPT_ATTACHMENT_REMOVE, mmi_uc_highlight_remove_attachment);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_UC_OPT_ADD_PICTURE, mmi_uc_highlight_opt_add_picture);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_UC_OPT_INSERT_IMAGE, mmi_uc_highlight_insert_image);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_UC_OPT_ADD_SOUND, mmi_uc_highlight_opt_add_sound);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_UC_OPT_INSERT_AUDIO, mmi_uc_highlight_insert_audio);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_UC_OPT_ADD_VIDEO, mmi_uc_highlight_opt_add_video);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_UC_OPT_INSERT_VIDEO, mmi_uc_highlight_insert_video);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_UC_OPT_PREVIEW, mmi_uc_highlight_opt_preview);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_UC_OPT_SLIDE_OPT, mmi_uc_highlight_opt_slide_opt);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_UC_OPT_SLIDE_OPT_INSERT, mmi_uc_highlight_slide_opt_insert);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_UC_OPT_SLIDE_OPT_INSERT_BEFORE, mmi_uc_highlight_slide_opt_insert_before);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_UC_OPT_SLIDE_OPT_TIMING, mmi_uc_highlight_slide_opt_timing);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_UC_OPT_SLIDE_OPT_DELETE, mmi_uc_highlight_slide_opt_delete);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_UC_OPT_SLIDE_OPT_NEXT, mmi_uc_highlight_slide_opt_next);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_UC_OPT_SLIDE_OPT_PREVIOUS, mmi_uc_highlight_slide_opt_previous);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_UC_OPT_ADVANCED, mmi_uc_highlight_opt_advance_options);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_UC_OPT_INSERT_TEXT_TEMPLATE, mmi_uc_highlight_insert_text_template);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_UC_OPT_INSERT_ATTACHMENT, mmi_uc_highlight_insert_attachment);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_UC_OPT_SAVE_TO_DRAFT, mmi_uc_highlight_save_to_draft);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_UC_OPT_REMOVE, mmi_uc_highlight_opt_remove);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_UC_OPT_REMOVE_IMAGE, mmi_uc_highlight_remove_image);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_UC_OPT_REMOVE_AUDIO, mmi_uc_highlight_remove_audio);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_UC_OPT_REMOVE_VIDEO, mmi_uc_highlight_remove_video);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_UC_OPT_REMOVE_ATTACHMENT, mmi_uc_highlight_remove_attachment);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_UC_OPT_DONE_SEND, mmi_uc_highlight_done_opt_send);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_UC_EXIT_OPT_SAVE, mmi_uc_highlight_exit_opt_save);
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(MENU_ID_UC_EXIT_OPT_EXIT, mmi_uc_highlight_exit_opt_exit);
/******************** Menu Hilite/Hint Handlers - finish ********************/
}
