/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_app_filemanager.c
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   MTK resgenerator XML parser
 *
 *******************************************************************************/
#include "CustDataProts.h"
#include "mmi_rp_app_filemanager_def.h"

/* Application specified header files for using old res IDs */
#include "MMI_features.h"
#include "MMIDataType.h"    /* for resource base */

#include "CustResDef.h"         /* for image/audio path */
#include "GlobalMenuItems.h"    /* for menu resource */

#include "GlobalResDef.h"
#include "RightsMgrResDef.h"
#include "FileMgrServiceResDef.h"
#include "mmi_rp_app_rmgr_def.h"
#include "gdi_features.h"


/*****************************************************************************
* FUNCTION
*  mmi_rp_app_filemanager_populate
* DESCRIPTION
*  Automatically generated populate function for mmi_rp_app_filemanager_populate
* PARAMETERS
*  void
* RETURNS
*  void
*****************************************************************************/
void mmi_rp_app_filemanager_populate(void)
{
    /*----------------------------------------------------------------*/
    /* Local Variables                                                */
    /*----------------------------------------------------------------*/

    /*----------------------------------------------------------------*/
    /* Code Body                                                      */
    /*----------------------------------------------------------------*/

/******************** Menu resource IDs - begin ********************/
    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FMGR_DRIVE_OPTIONS,
        0,
        4,
        MENU_ID_FMGR_DRIVE_OPEN,
        MENU_ID_FMGR_FOLDER_CREATE,
        MENU_ID_FMGR_DRIVE_FORMAT,
        MENU_ID_FMGR_CARD_DETAIL,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_OPTIONS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FMGR_APP_DRIVE_OPTIONS,
        0,
        3,
        MENU_ID_FMGR_DRIVE_OPEN,
        MENU_ID_FMGR_DRIVE_SELECT_DONE,
        MENU_ID_FMGR_FOLDER_CREATE,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_OPTIONS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FMGR_DRIVE_OPEN,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_OPEN,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FMGR_DRIVE_FORMAT,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_FMGR_FORMAT,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FMGR_DRIVE_SELECT_DONE,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_SELECT,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FMGR_CARD_DETAIL,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_DETAILS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FMGR_FOLDER_OPTIONS,
        0,
        6,
        MENU_ID_FMGR_FOLDER_OPEN,
        MENU_ID_FMGR_FOLDER_CREATE,
        MENU_ID_FMGR_GEN_OPTION_RENAME,
        MENU_ID_FMGR_GEN_OPTION_DELETE,
        MENU_ID_FMGR_GEN_OPTION_SORT,
        MENU_ID_FMGR_GEN_OPTION_DETAIL,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_OPTIONS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FMGR_APP_FOLDER_OPTIONS,
        0,
        5,
        MENU_ID_FMGR_FOLDER_OPEN,
        MENU_ID_FMGR_FOLDER_SELECT_DONE,
        MENU_ID_FMGR_FOLDER_CREATE,
        MENU_ID_FMGR_GEN_OPTION_RENAME,
        MENU_ID_FMGR_GEN_OPTION_DELETE,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_OPTIONS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FMGR_FOLDER_OPEN,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_OPEN,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FMGR_FOLDER_CREATE,
        MENU_ID_FMGR_HYPERLINK_OPTIONS,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_FMGR_FOLDER_CREATE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FMGR_FOLDER_SELECT_DONE,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_SELECT,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FMGR_HYPERLINK_OPTIONS,
        0,
        2,
        MENU_ID_FMGR_HYPERLINK_APP_FUNC,
        MENU_ID_FMGR_FOLDER_CREATE,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_OPTIONS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FMGR_HYPERLINK_APP_FUNC,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_ERROR,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FMGR_TREE_OPTIONS,
        0,
        3,
        MENU_ID_FMGR_TREE_SELECT,
        MENU_ID_FMGR_TREE_OPEN,
        MENU_ID_FMGR_FOLDER_CREATE,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_OPTIONS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FMGR_TREE_SELECT,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_DONE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FMGR_TREE_OPEN,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_OPEN,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FMGR_GEN_TYPE_OPTIONS,
        0,
        10,
        MENU_ID_FMGR_GEN_OPTION_FORWARD_SEND,
        MENU_ID_FMGR_GEN_OPTION_FORWARD_USE,
        MENU_ID_FMGR_FOLDER_CREATE,
        MENU_ID_FMGR_GEN_OPTION_MORE_RITS,
        MENU_ID_FMGR_GEN_OPTION_RENAME,
        MENU_ID_FMGR_GEN_OPTION_DELETE,
        MENU_ID_FMGR_GEN_OPTION_SORT,
        MENU_ID_FMGR_GEN_OPTION_COPY,
        MENU_ID_FMGR_GEN_OPTION_MOVE,
        MENU_ID_FMGR_GEN_OPTION_DETAIL,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_OPTIONS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FMGR_GEN_OPTION_FORWARD_USE,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_FMGR_USE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FMGR_GEN_OPTION_FORWARD_SEND,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_SEND,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FMGR_GEN_OPTION_DETAIL,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_DETAILS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FMGR_GEN_OPTION_MORE_RITS,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_RMGR_MORE_RITS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FMGR_GEN_OPTION_RENAME,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_RENAME,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FMGR_GEN_OPTION_COPY,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_COPY,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FMGR_GEN_OPTION_MOVE,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_MOVE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FMGR_GEN_OPTION_DELETE,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_DELETE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FMGR_GEN_OPTION_SORT,
        0,
        4,
        MENU_ID_FMGR_SORT_BY_NAME,
        MENU_ID_FMGR_SORT_BY_TYPE,
        MENU_ID_FMGR_SORT_BY_TIME,
        MENU_ID_FMGR_SORT_BY_SIZE,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_SORT_BY,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FMGR_SORT_BY_NAME,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_FMGR_SORT_BY_NAME,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FMGR_SORT_BY_TYPE,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_FMGR_SORT_BY_TYPE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FMGR_SORT_BY_TIME,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_FMGR_SORT_BY_TIME,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FMGR_SORT_BY_SIZE,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_FMGR_SORT_BY_SIZE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FMGR_EDITOR_OPTION,
        0,
        2,
        MENU_ID_FMGR_EDITOR_DONE,
        MENU_ID_FMGR_EDITOR_INPUT_METHOD,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_OPTIONS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FMGR_EDITOR_DONE,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_DONE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_FMGR_EDITOR_INPUT_METHOD,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_INPUT_METHOD,
        0));

/******************** Menu resource IDs - finish ********************/

/******************** Menu Hilite/Hint Handlers - begin ********************/
    ADD_APPLICATION_MENUITEM_HINT_HANDLER(MENU_ID_FMGR_GEN_OPTION_SORT, mmi_fmgri_main_hint_sort);
/******************** Menu Hilite/Hint Handlers - finish ********************/
}
