/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_populate.c
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   MTK resgenerator XML parser
 *
 *******************************************************************************/

#include "CustDataProts.h"

/* Application specified header files for using old res IDs */


/*****************************************************************************
* FUNCTION
*  mmi_rp_populate_resources
* DESCRIPTION
*  Automatically generated populate function for mmi_rp_populate_resources
* PARAMETERS
*  void
* RETURNS
*  void
*****************************************************************************/
void mmi_rp_populate_resources(void)
{
    /*----------------------------------------------------------------*/
    /* Local Variables                                                */
    /*----------------------------------------------------------------*/

    /*----------------------------------------------------------------*/
    /* Code Body                                                      */
    /*----------------------------------------------------------------*/
    extern void mmi_rp_app_mre_populate(void);
    mmi_rp_app_mre_populate();

    extern void mmi_rp_app_bluetooth_populate(void);
    mmi_rp_app_bluetooth_populate();

    extern void mmi_rp_app_security_setting_populate(void);
    mmi_rp_app_security_setting_populate();

    extern void mmi_rp_app_camera_populate(void);
    mmi_rp_app_camera_populate();

    extern void mmi_rp_app_imageviewer_populate(void);
    mmi_rp_app_imageviewer_populate();

    extern void mmi_rp_app_soundrecorder_populate(void);
    mmi_rp_app_soundrecorder_populate();

    extern void mmi_rp_app_worldclock_populate(void);
    mmi_rp_app_worldclock_populate();

    extern void mmi_rp_app_callset_populate(void);
    mmi_rp_app_callset_populate();

    extern void mmi_rp_app_ss_populate(void);
    mmi_rp_app_ss_populate();

    extern void mmi_rp_app_unifiedcomposer_populate(void);
    mmi_rp_app_unifiedcomposer_populate();

    extern void mmi_rp_app_rmgr_populate(void);
    mmi_rp_app_rmgr_populate();

    extern void mmi_rp_app_dataaccount_populate(void);
    mmi_rp_app_dataaccount_populate();

    extern void mmi_rp_app_umms_mms_populate(void);
    mmi_rp_app_umms_mms_populate();

    extern void mmi_rp_app_mmi_wap_push_populate(void);
    mmi_rp_app_mmi_wap_push_populate();

    extern void mmi_rp_app_calllog_populate(void);
    mmi_rp_app_calllog_populate();

    extern void mmi_rp_app_profiles_populate(void);
    mmi_rp_app_profiles_populate();

    extern void mmi_rp_app_filemanager_populate(void);
    mmi_rp_app_filemanager_populate();

    extern void mmi_rp_srv_wallpaper_populate(void);
    mmi_rp_srv_wallpaper_populate();

    extern void mmi_rp_srv_spof_populate(void);
    mmi_rp_srv_spof_populate();

    extern void mmi_rp_srv_phnset_onoff_populate(void);
    mmi_rp_srv_phnset_onoff_populate();

    extern void mmi_rp_srv_flight_mode_populate(void);
    mmi_rp_srv_flight_mode_populate();

    extern void mmi_rp_app_phonesetting_new_populate(void);
    mmi_rp_app_phonesetting_new_populate();

    extern void mmi_rp_app_restore_populate(void);
    mmi_rp_app_restore_populate();

    extern void mmi_rp_app_netset_populate(void);
    mmi_rp_app_netset_populate();

    extern void mmi_rp_app_sat_populate(void);
    mmi_rp_app_sat_populate();

    extern void mmi_rp_app_shortcuts_populate(void);
    mmi_rp_app_shortcuts_populate();

    extern void mmi_rp_app_calculator_populate(void);
    mmi_rp_app_calculator_populate();

    extern void mmi_rp_app_cbs_populate(void);
    mmi_rp_app_cbs_populate();

    extern void mmi_rp_app_alarm_populate(void);
    mmi_rp_app_alarm_populate();

    extern void mmi_rp_app_nitz_populate(void);
    mmi_rp_app_nitz_populate();

    extern void mmi_rp_app_organizer_populate(void);
    mmi_rp_app_organizer_populate();

    extern void mmi_rp_app_calendar_populate(void);
    mmi_rp_app_calendar_populate();

    extern void mmi_rp_app_todolist_populate(void);
    mmi_rp_app_todolist_populate();

    extern void mmi_rp_srv_vobject_populate(void);
    mmi_rp_srv_vobject_populate();

    extern void mmi_rp_srv_vcalendar_populate(void);
    mmi_rp_srv_vcalendar_populate();

    extern void mmi_rp_srv_vcard_populate(void);
    mmi_rp_srv_vcard_populate();

    extern void mmi_rp_app_ucm_populate(void);
    mmi_rp_app_ucm_populate();

    extern void mmi_rp_app_sms_populate(void);
    mmi_rp_app_sms_populate();

    extern void mmi_rp_app_mot_populate(void);
    mmi_rp_app_mot_populate();

    extern void mmi_rp_app_unifiedmessage_populate(void);
    mmi_rp_app_unifiedmessage_populate();

    extern void mmi_rp_app_mainmenu_populate(void);
    mmi_rp_app_mainmenu_populate();

    extern void mmi_rp_app_nss_populate(void);
    mmi_rp_app_nss_populate();

    extern void mmi_rp_app_downloadagent_populate(void);
    mmi_rp_app_downloadagent_populate();

    extern void mmi_rp_app_phonebook_populate(void);
    mmi_rp_app_phonebook_populate();

    extern void mmi_rp_srv_editor_populate(void);
    mmi_rp_srv_editor_populate();

    extern void mmi_rp_app_engineermode1_populate(void);
    mmi_rp_app_engineermode1_populate();

    extern void mmi_rp_app_factorymode_populate(void);
    mmi_rp_app_factorymode_populate();

    extern void mmi_rp_app_connectivity_mainmenu_populate(void);
    mmi_rp_app_connectivity_mainmenu_populate();

    extern void mmi_rp_srv_mms_populate(void);
    mmi_rp_srv_mms_populate();

    extern void mmi_rp_app_gpio_populate(void);
    mmi_rp_app_gpio_populate();

    extern void mmi_rp_cui_dialer_populate(void);
    mmi_rp_cui_dialer_populate();

    extern void mmi_rp_cui_use_detail_populate(void);
    mmi_rp_cui_use_detail_populate();

    extern void mmi_rp_app_am_populate(void);
    mmi_rp_app_am_populate();

    extern void mmi_rp_app_gb_winguo_net_populate(void);
    mmi_rp_app_gb_winguo_net_populate();

    extern void mmi_rp_app_npr_tts_populate(void);
    mmi_rp_app_npr_tts_populate();

}
