/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_app_am.c
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   MTK resgenerator XML parser
 *
 *******************************************************************************/
#include "CustDataProts.h"
#include "mmi_rp_app_am_def.h"

/* Application specified header files for using old res IDs */
#include "MMI_features.h"
#include "MMIDataType.h"    /* for resource base */

#include "CustResDef.h"         /* for image/audio path */
#include "GlobalMenuItems.h"    /* for menu resource */

#include "GlobalResDef.h"
#include "mmi_rp_app_filemanager_def.h"
#include "GlobalResDef.h"
#include "mmi_rp_app_filemanager_def.h"


/*****************************************************************************
* FUNCTION
*  mmi_rp_app_am_populate
* DESCRIPTION
*  Automatically generated populate function for mmi_rp_app_am_populate
* PARAMETERS
*  void
* RETURNS
*  void
*****************************************************************************/
void mmi_rp_app_am_populate(void)
{
    /*----------------------------------------------------------------*/
    /* Local Variables                                                */
    /*----------------------------------------------------------------*/

    /*----------------------------------------------------------------*/
    /* Code Body                                                      */
    /*----------------------------------------------------------------*/

/******************** Menu resource IDs - begin ********************/
    ADD_APPLICATION_MENUITEM5((
        MENU_ID_AM_OPTION_DOWNLOAD,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_DOWNLOAD,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_AM_OPTION_OPEN,
        MENU_ID_AM_OPTIONS,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_OPEN,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_AM_OPTION_CREATE_SHORTCUT,
        MENU_ID_AM_OPTIONS,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_AM_OPTION_CREATE_SHORTCUT,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_AM_OPTION_DELETE_SHORTCUT,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_AM_OPTION_DELETE_SHORTCUT,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_AM_OPTION_DELETE,
        MENU_ID_AM_OPTIONS,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_DELETE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_AM_OPTION_DETAILS,
        MENU_ID_AM_OPTIONS,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_DETAILS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_AM_OPTION_UNINSTALL,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_AM_UNINSTALL,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_AM_OPTION_SETTINGS,
        MENU_ID_AM_OPTIONS,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_SETTINGS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_AM_OPTION_PSMGR,
        MENU_ID_AM_OPTIONS,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_AM_PSMGR_TXT_TITLE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_AM_OPTIONS,
        0,
        6,
        MENU_ID_AM_OPTION_OPEN,
        MENU_ID_AM_OPTION_CREATE_SHORTCUT,
        MENU_ID_AM_OPTION_DELETE,
        MENU_ID_AM_OPTION_DETAILS,
        MENU_ID_AM_OPTION_SETTINGS,
        MENU_ID_AM_OPTION_PSMGR,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_OPTIONS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_DLA_OPTION_MAIN,
        0,
        2,
        MENU_ID_DLA_OPTION_MAIN_DETAIL,
        MENU_ID_DLA_OPTION_MAIN_LIST,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_OPTIONS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_DLA_OPTION_MAIN_DETAIL,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_AM_DLA_OPTION_DOWNLOAD_STATUS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_DLA_OPTION_MAIN_LIST,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_AM_DLA_OPTION_DOWNLOAD_LIST,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_DLA_OPTION_LIST,
        0,
        5,
        MENU_ID_DLA_OPTION_LIST_DETAIL,
        MENU_ID_DLA_OPTION_LIST_RETRY,
        MENU_ID_DLA_OPTION_LIST_PAUSE,
        MENU_ID_DLA_OPTION_LIST_RESUME,
        MENU_ID_DLA_OPTION_LIST_REMOVE,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_OPTIONS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_DLA_OPTION_LIST_NONE,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_RENAME,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_DLA_OPTION_LIST_DETAIL,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_AM_DLA_OPTION_DOWNLOAD_STATUS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_DLA_OPTION_LIST_RETRY,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_AM_DLA_LIST_OPTION_RETRY,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_DLA_OPTION_LIST_PAUSE,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_PAUSE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_DLA_OPTION_LIST_RESUME,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_RESUME,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_DLA_OPTION_LIST_REMOVE,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_REMOVE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_AM_PSMGR_OPTION_BG_LIST,
        0,
        2,
        MENU_ID_AM_PSMGR_OPTION_BG_LIST_LAUNCH,
        MENU_ID_AM_PSMGR_OPTION_BG_LIST_EXIT,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_GLOBAL_OPTIONS,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_AM_PSMGR_OPTION_BG_LIST_LAUNCH,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_AM_PSMGR_TXT_OPTION_LAUNCH,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_AM_PSMGR_OPTION_BG_LIST_EXIT,
        0,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_EXIT,
        0));

/******************** Menu resource IDs - finish ********************/

/******************** Menu Hilite/Hint Handlers - begin ********************/
/******************** Menu Hilite/Hint Handlers - finish ********************/
}
