/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_app_calendar.c
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   MTK resgenerator XML parser
 *
 *******************************************************************************/
#include "CustDataProts.h"
#include "mmi_rp_app_calendar_def.h"

/* Application specified header files for using old res IDs */
#include "MMI_features.h"
#include "MMIDataType.h"    /* for resource base */

#include "CustResDef.h"         /* for image/audio path */
#include "GlobalMenuItems.h"    /* for menu resource */

#include "GlobalResDef.h"
#include "GlobalMenuItems.h"
#include "mmi_rp_app_mainmenu_def.h"
#include "OrganizerResDef.h"


/*****************************************************************************
* FUNCTION
*  mmi_rp_app_calendar_populate
* DESCRIPTION
*  Automatically generated populate function for mmi_rp_app_calendar_populate
* PARAMETERS
*  void
* RETURNS
*  void
*****************************************************************************/
void mmi_rp_app_calendar_populate(void)
{
    /*----------------------------------------------------------------*/
    /* Local Variables                                                */
    /*----------------------------------------------------------------*/

    /*----------------------------------------------------------------*/
    /* Code Body                                                      */
    /*----------------------------------------------------------------*/

/******************** Menu resource IDs - begin ********************/
    ADD_APPLICATION_MENUITEM5((
        ORGANIZER_CALENDER_MENU,
        MAIN_MENU_ORGANIZER_MENUID,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_APP_MAIN,
        ORGANIZER_MENU_CALENDER_STRINGID,
        ORGANIZER_MENU_CALENDER_IMAGEID));

    ADD_APPLICATION_MENUITEM5((
        MENU_GOTO_TASK_CAL,
        ORGANIZER_CALENDER_MONTHLY_OPTIONS_MENU,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_GLOBAL_VIEW,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLNDR_VIEW_ALL,
        ORGANIZER_CALENDER_MONTHLY_OPTIONS_MENU,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CLNDR_VIEW_ALL,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLNDR_ADD_TASK,
        ORGANIZER_CALENDER_MONTHLY_OPTIONS_MENU,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_CLNDR_ADD_TASK,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLNDR_JUMP_TO_DATE,
        ORGANIZER_CALENDER_MONTHLY_OPTIONS_MENU,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_CLNDR_JUMP_TO,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLNDR_GOTO_TODAY,
        ORGANIZER_CALENDER_MONTHLY_OPTIONS_MENU,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_CLNDR_GOTO_TODAY,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLNDR_MONTHLY_VIEW,
        ORGANIZER_CALENDER_WEEKLY_OPTIONS_MENU,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_CLNDR_MONTHLY_VIEW,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLNDR_FIRST_DAY_OF_WEEK,
        ORGANIZER_CALENDER_MONTHLY_OPTIONS_MENU,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CLNDR_FIRST_DAY_OF_WEEK,
        0));

    ADD_APPLICATION_MENUITEM5((
        ORGANIZER_CALENDER_MONTHLY_OPTIONS_MENU,
        0,
        8,
        MENU_GOTO_TASK_CAL,
        MENU_ID_CLNDR_VIEW_ALL,
        MENU_ID_CLNDR_ADD_TASK,
        MENU_ID_CLNDR_DELETE_EVENT,
        MENU_ID_CLNDR_JUMP_TO_DATE,
        MENU_ID_CLNDR_GOTO_TODAY,
        MENU_ID_CLNDR_WEEKLY_VIEW,
        MENU_ID_CLNDR_FIRST_DAY_OF_WEEK,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        ORGANIZER_MENU_CALENDER_STRINGID,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLNDR_WEEKLY_VIEW,
        ORGANIZER_CALENDER_MONTHLY_OPTIONS_MENU,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_CLNDR_WEEKLY_VIEW,
        0));

    ADD_APPLICATION_MENUITEM5((
        ORGANIZER_CALENDER_WEEKLY_OPTIONS_MENU,
        0,
        8,
        MENU_GOTO_TASK_CAL,
        MENU_ID_CLNDR_VIEW_ALL,
        MENU_ID_CLNDR_ADD_TASK,
        MENU_ID_CLNDR_DELETE_EVENT,
        MENU_ID_CLNDR_JUMP_TO_DATE,
        MENU_ID_CLNDR_GOTO_TODAY,
        MENU_ID_CLNDR_MONTHLY_VIEW,
        MENU_ID_CLNDR_FIRST_DAY_OF_WEEK,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        ORGANIZER_MENU_CALENDER_STRINGID,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLNDR_DELETE_EVENT,
        0,
        3,
        MENU_ID_CLNDR_DELETE_ALL,
        MENU_ID_CLNDR_DELETE_ALL_OVERDUE,
        MENU_ID_CLNDR_DELETE_SPEC_PERIOD,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_OPTION,
        STR_ID_CLNDR_DELETE_EVENT,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLNDR_DELETE_ALL,
        MENU_ID_CLNDR_DELETE_EVENT,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CLNDR_DELETE_ALL,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLNDR_DELETE_ALL_OVERDUE,
        MENU_ID_CLNDR_DELETE_EVENT,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CLNDR_DELETE_ALL_OVERDUE,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLNDR_DELETE_SPEC_PERIOD,
        MENU_ID_CLNDR_DELETE_EVENT,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CLNDR_DELETE_SPEC_PERIOD,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLNDR_EVENT_FILTER,
        0,
        5,
        MENU_ID_CLNDR_EVENT_ALL,
        MENU_ID_CLNDR_EVENT_LOCAL,
        MENU_ID_CLNDR_EVENT_FACEBOOK,
        MENU_ID_CLNDR_EVENT_KAIXIN,
        MENU_ID_CLNDR_EVENT_RENREN,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_APP_SUB,
        0,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLNDR_EVENT_ALL,
        MENU_ID_CLNDR_EVENT_FILTER,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CLNDR_EVENT_SELECT_ALL,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLNDR_EVENT_LOCAL,
        MENU_ID_CLNDR_EVENT_FILTER,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CLNDR_EVENT_LOCAL,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLNDR_EVENT_FACEBOOK,
        MENU_ID_CLNDR_EVENT_FILTER,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CLNDR_EVENT_FACEBOOK,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLNDR_EVENT_KAIXIN,
        MENU_ID_CLNDR_EVENT_FILTER,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CLNDR_EVENT_KAIXIN,
        0));

    ADD_APPLICATION_MENUITEM5((
        MENU_ID_CLNDR_EVENT_RENREN,
        MENU_ID_CLNDR_EVENT_FILTER,
        0,
        SHOW,
        NONMOVEABLE,
        MMI_RG_MENU_TYPE_ORIGINAL,
        STR_ID_CLNDR_EVENT_RENREN,
        0));

/******************** Menu resource IDs - finish ********************/

/******************** Menu Hilite/Hint Handlers - begin ********************/
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(ORGANIZER_CALENDER_MENU, HighlightClndrMenu);
/******************** Menu Hilite/Hint Handlers - finish ********************/
}
