/* Needed header files of the compile option in XML files, if you need others need to add here */
#include "mmi_features.h"
#include "custresdef.h"

#include "CustomCfg.h"

#ifdef FIRST_PASS
#include "BuildCfg.h"
#endif

#include "vfx_config.h"
#include "MMIDataType.h"

/* Need this line to tell parser that XML start, must after all #include. */
<?xml version="1.0" encoding="UTF-8"?>

/* APP tag, include your app name defined in MMIDataType.h */
<APP id="SRV_INPUT_METHOD">

    /* When you use any ID of other module, you need to add
       that header file here, so that Resgen can find the ID */
    <!--Include Area-->

    <!-----------------------------------------------------String Resource Area----------------------------------------------------->
    /* String ID of you Application, we will get string from ref_list.txt for all languages */

#ifdef __MMI_PREFER_INPUT_METHOD__
    <STRING id="STR_MENU_INPUT_METHOD"/>
#endif

    <STRING id="STR_INPUT_METHOD_MULTITAP_U_ABC"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_ABC"/>
#if defined(__MMI_T9_ENGLISH__)||defined(__MMI_ZI_PRC_ENGLISH__)||defined(__MMI_ITAP_ENGLISH__) || defined(__MMI_CSTAR_ENGLISH__)|| defined(__MMI_GB_ENGLISH__)
    <STRING id="STR_INPUT_METHOD_SMART_U_ABC"/>
#endif
#if defined(__MMI_T9_ENGLISH__)||defined(__MMI_ZI_PRC_ENGLISH__)||defined(__MMI_ITAP_ENGLISH__) || defined(__MMI_CSTAR_ENGLISH__)|| defined(__MMI_GB_ENGLISH__)
    <STRING id="STR_INPUT_METHOD_SMART_L_ABC"/>
#endif
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_ABC"/>
#endif

#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_ABC"/>
#endif

    <STRING id="STR_INPUT_METHOD_NUMERIC"/>
#if defined(__MMI_ZI_HK_CHINESE__) || defined(__MMI_T9_HK_CHINESE__)
#if defined(__MMI_ZI_STROKE_INPUT__) || defined(__MMI_T9_STROKE_INPUT__) 
    <STRING id="STR_INPUT_METHOD_HK_STROKE"/>
#endif
#endif
#if defined(__MMI_IME_TR_CHINESE__)
#if defined(__MMI_IME_MULTITAP_PHONETIC_INPUT__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_BPMF"/>
#endif
#endif
#if defined(__MMI_T9_TR_CHINESE__)||defined(__MMI_ZI_TR_CHINESE__)||defined(__MMI_ITAP_TR_CHINESE__) || defined(__MMI_CSTAR_TR_CHINESE__)
#if (defined(__MMI_T9_SMART_PHONETIC_INPUT__) && defined(__MMI_T9_AMB_BPMF_INPUT__))||defined(__MMI_ZI_SMART_PHONETIC_INPUT__)||defined(__MMI_ITAP_SMART_PHONETIC_INPUT__)
    <STRING id="STR_INPUT_METHOD_BPMF"/>
#endif
#endif
#if defined(__MMI_IME_STROKE_INPUT__)
    <STRING id="STR_INPUT_METHOD_TR_STROKE"/>
#endif
#if defined(__MMI_T9_SM_CHINESE__)||defined(__MMI_ZI_SM_CHINESE__)||defined(__MMI_ITAP_SM_CHINESE__)||defined(__MMI_CSTAR_SM_CHINESE__)||defined(__MMI_GB_SM_CHINESE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_PINYIN"/>
#endif
#if defined(__MMI_T9_SM_CHINESE__)||defined(__MMI_ZI_SM_CHINESE__)||defined(__MMI_ITAP_SM_CHINESE__)||defined(__MMI_CSTAR_SM_CHINESE__)||defined(__MMI_GB_SM_CHINESE__)
#if defined(__MMI_T9_SMART_PHONETIC_INPUT__)||defined(__MMI_ZI_SMART_PHONETIC_INPUT__)||defined(__MMI_ITAP_SMART_PHONETIC_INPUT__)||defined(__MMI_CSTAR_SMART_PHONETIC_INPUT__)||defined(__MMI_GB_SMART_PHONETIC_INPUT__)
    <STRING id="STR_INPUT_METHOD_PINYIN"/>
#endif
#endif
#if defined(__MMI_T9_STROKE_INPUT__) || defined(__MMI_ZI_STROKE_INPUT__) || defined(__MMI_CSTAR_STROKE_INPUT__)|| defined(__MMI_GB_STROKE_INPUT__)
    <STRING id="STR_INPUT_METHOD_SM_STROKE"/>
#endif

#if defined(__MMI_MULTITAP_KOREAN__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_KOREAN"/>
#endif

#if defined(__MMI_MULTITAP_SPANISH__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_SPANISH"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_SPANISH"/>

#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_SPANISH"/>
#endif
#endif

#if defined(__MMI_IME_SPANISH__)
    <STRING id="STR_INPUT_METHOD_SMART_U_SPANISH"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_SPANISH"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_SPANISH"/>
#endif
#endif

#if defined(__MMI_ZI_SA_SPANISH__)|| defined(__MMI_GB_SA_SPANISH__)
    <STRING id="STR_INPUT_METHOD_SMART_U_SA_SPANISH"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_SA_SPANISH"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_SA_SPANISH"/>    
#endif
#endif

#if defined(__MMI_MULTITAP_DANISH__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_DANISH"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_DANISH"/>
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_DANISH"/>
#endif
#endif

#if defined(__MMI_IME_DANISH__)
    <STRING id="STR_INPUT_METHOD_SMART_U_DANISH"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_DANISH"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_DANISH"/>
#endif
#endif

#if defined(__MMI_MULTITAP_POLISH__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_POLISH"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_POLISH"/>
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_POLISH"/>
#endif
#endif

#if defined(__MMI_IME_POLISH__)
    <STRING id="STR_INPUT_METHOD_SMART_U_POLISH"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_POLISH"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_POLISH"/>
#endif
#endif

#if defined(__MMI_MULTITAP_FRENCH__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_FRENCH"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_FRENCH"/>
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_FRENCH"/>
#endif
#endif

#if defined(__MMI_T9_FRENCH__) || defined(__MMI_ZI_CA_FRENCH__) || defined(__MMI_ZI_EU_FRENCH__) || defined(__MMI_CSTAR_FRENCH__)|| defined(__MMI_GB_FRENCH__)
    <STRING id="STR_INPUT_METHOD_SMART_U_FRENCH"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_FRENCH"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_FRENCH"/>
#endif
#endif

#if defined(__MMI_ZI_CA_FRENCH__)
    <STRING id="STR_INPUT_METHOD_SMART_U_CA_FRENCH"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_CA_FRENCH"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_CA_FRENCH"/>  
#endif
#endif

#if defined(__MMI_MULTITAP_GERMAN__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_GERMAN"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_GERMAN"/>
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_GERMAN"/>
#endif
#endif

#if defined(__MMI_IME_GERMAN__)
    <STRING id="STR_INPUT_METHOD_SMART_U_GERMAN"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_GERMAN"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_GERMAN"/>
#endif
#endif

#if defined(__MMI_MULTITAP_ITALIAN__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_ITALIAN"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_ITALIAN"/>
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_ITALIAN"/>
#endif
#endif

#if defined(__MMI_IME_ITALIAN__)
    <STRING id="STR_INPUT_METHOD_SMART_U_ITALIAN"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_ITALIAN"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_ITALIAN"/>
#endif
#endif

#if defined(__MMI_MULTITAP_RUSSIAN__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_RUSSIAN"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_RUSSIAN"/>
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_RUSSIAN"/>
#endif
#endif

#if defined ( __MMI_IME_RUSSIAN__)
    <STRING id="STR_INPUT_METHOD_SMART_U_RUSSIAN"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_RUSSIAN"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_RUSSIAN"/>
#endif
#endif

#if defined(__MMI_MULTITAP_BULGARIAN__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_BULGARIAN"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_BULGARIAN"/>
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_BULGARIAN"/>
#endif
#endif

#if defined ( __MMI_IME_BULGARIAN__)
    <STRING id="STR_INPUT_METHOD_SMART_U_BULGARIAN"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_BULGARIAN"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_BULGARIAN"/>
#endif
#endif

#if defined(__MMI_MULTITAP_UKRAINIAN__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_UKRAINIAN"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_UKRAINIAN"/>
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_UKRAINIAN"/>
#endif
#endif

#if defined ( __MMI_IME_UKRAINIAN__)
    <STRING id="STR_INPUT_METHOD_SMART_U_UKRAINIAN"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_UKRAINIAN"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_UKRAINIAN"/>
#endif
#endif

#if defined(__MMI_MULTITAP_TURKISH__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_TURKISH"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_TURKISH"/>
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_TURKISH"/>
#endif
#endif

#if defined(__MMI_IME_TURKISH__)
    <STRING id="STR_INPUT_METHOD_SMART_U_TURKISH"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_TURKISH"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_TURKISH"/>
#endif
#endif

#if defined(__MMI_MULTITAP_PORTUGUESE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_PORTUGUESE"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_PORTUGUESE"/>
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_PORTUGUESE"/>
#endif
#endif

#if defined(__MMI_IME_PORTUGUESE__)
    <STRING id="STR_INPUT_METHOD_SMART_U_PORTUGUESE"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_PORTUGUESE"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_PORTUGUESE"/>
#endif
#endif

#if defined(__MMI_ZI_SA_PORTUGUESE__)||defined(__MMI_GB_SA_PORTUGUESE__)
    <STRING id="STR_INPUT_METHOD_SMART_U_SA_PORTUGUESE"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_SA_PORTUGUESE"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_SA_PORTUGUESE"/>   
#endif
#endif

#if defined(__MMI_MULTITAP_INDONESIAN__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_INDONESIAN"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_INDONESIAN"/>
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_INDONESIAN"/>
#endif
#endif

#if defined(__MMI_IME_INDONESIAN__)
    <STRING id="STR_INPUT_METHOD_SMART_U_INDONESIAN"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_INDONESIAN"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_INDONESIAN"/>
#endif
#endif

#if defined(__MMI_MULTITAP_CZECH__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_CZECH"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_CZECH"/>
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_CZECH"/>
#endif
#endif

#if defined(__MMI_IME_CZECH__)
    <STRING id="STR_INPUT_METHOD_SMART_U_CZECH"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_CZECH"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_CZECH"/>
#endif
#endif

#if defined(__MMI_MULTITAP_MALAY__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_MALAY"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_MALAY"/>
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_MALAY"/>
#endif
#endif

#if defined(__MMI_IME_MALAY__)
    <STRING id="STR_INPUT_METHOD_SMART_U_MALAY"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_MALAY"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_MALAY"/>
#endif
#endif

#if defined(__MMI_MULTITAP_VIETNAMESE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_VIETNAMESE"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_VIETNAMESE"/>
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_VIETNAMESE"/>
#endif
#endif

#if defined(__MMI_IME_VIETNAMESE__)
    <STRING id="STR_INPUT_METHOD_SMART_U_VIETNAMESE"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_VIETNAMESE"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_VIETNAMESE"/>
#endif
#endif

#if defined (__MMI_MULTITAP_THAI__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_THAI"/>
#endif

#if defined(__MMI_IME_THAI__)
    <STRING id="STR_INPUT_METHOD_SMART_THAI"/>
#endif

#if  defined(__MMI_IME_HINGLISH__)
    <STRING id="STR_INPUT_METHOD_SMART_U_HINGLISH"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_HINGLISH"/>
#endif

#if defined(__MMI_ZI_HINDI__) || defined(__MMI_T9_HINDI__) || defined(__MMI_CSTAR_HINDI__)|| defined(__MMI_GB_HINDI__)
    <STRING id="STR_INPUT_METHOD_SMART_HINDI"/>
#endif

#if defined(__MMI_MULTITAP_ARABIC__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_ARABIC"/>
    <STRING id="STR_INPUT_METHOD_ARABIC_NUMERIC"/>
#endif

#if defined(__MMI_ZI_ARABIC__) || defined(__MMI_T9_ARABIC__) || defined(__MMI_CSTAR_ARABIC__)|| defined(__MMI_GB_ARABIC__)
    <STRING id="STR_INPUT_METHOD_SMART_ARABIC"/>
#endif

#if defined(__MMI_MULTITAP_PERSIAN__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_PERSIAN"/>
#endif

#if defined( __MMI_ZI_PERSIAN__ )|| defined(__MMI_CSTAR_PERSIAN__)|| defined(__MMI_T9_PERSIAN__)|| defined(__MMI_GB_PERSIAN__)
    <STRING id="STR_INPUT_METHOD_SMART_PERSIAN"/>
#endif

#if defined(__MMI_MULTITAP_URDU__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_URDU"/>
#endif

#if defined (__MMI_IME_URDU__)
    <STRING id="STR_INPUT_METHOD_SMART_URDU"/>
#endif

#if defined(__MMI_MULTITAP_HEBREW__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_HEBREW"/>
#endif

#if defined(__MMI_IME_HEBREW__)
    <STRING id="STR_INPUT_METHOD_SMART_HEBREW"/>
#endif

#if defined(__MMI_MULTITAP_HINDI__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_HINDI"/>
#endif

#if defined(__MMI_MULTITAP_FINNISH__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_FINNISH"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_FINNISH"/>
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_FINNISH"/>
#endif
#endif

#if defined(__MMI_IME_FINNISH__)
    <STRING id="STR_INPUT_METHOD_SMART_U_FINNISH"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_FINNISH"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_FINNISH"/>
#endif
#endif

#if defined(__MMI_MULTITAP_HUNGARIAN__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_HUNGARIAN"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_HUNGARIAN"/>
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_HUNGARIAN"/>
#endif
#endif

#if defined(__MMI_IME_HUNGARIAN__)
    <STRING id="STR_INPUT_METHOD_SMART_U_HUNGARIAN"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_HUNGARIAN"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_HUNGARIAN"/>
#endif
#endif

#if defined(__MMI_MULTITAP_SLOVAK__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_SLOVAK"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_SLOVAK"/>
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_SLOVAK"/>
#endif
#endif

#if defined(__MMI_IME_SLOVAKIAN__)
    <STRING id="STR_INPUT_METHOD_SMART_U_SLOVAK"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_SLOVAK"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_SLOVAK"/>
#endif
#endif

#if defined(__MMI_MULTITAP_DUTCH__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_DUTCH"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_DUTCH"/>
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_DUTCH"/>
#endif
#endif

#if defined(__MMI_IME_DUTCH__)
    <STRING id="STR_INPUT_METHOD_SMART_U_DUTCH"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_DUTCH"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_DUTCH"/>
#endif
#endif

#if defined(__MMI_MULTITAP_NORWEGIAN__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_NORWEGIAN"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_NORWEGIAN"/>
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_NORWEGIAN"/>
#endif
#endif

#if defined(__MMI_IME_NORWEGIAN__)
    <STRING id="STR_INPUT_METHOD_SMART_U_NORWEGIAN"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_NORWEGIAN"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_NORWEGIAN"/>
#endif
#endif

#if defined(__MMI_MULTITAP_SWEDISH__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_SWEDISH"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_SWEDISH"/>
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_SWEDISH"/>
#endif
#endif

#if defined(__MMI_IME_SWEDISH__)
    <STRING id="STR_INPUT_METHOD_SMART_U_SWEDISH"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_SWEDISH"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_SWEDISH"/>
#endif
#endif

#if defined(__MMI_MULTITAP_CROATIAN__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_CROATIAN"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_CROATIAN"/>
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_CROATIAN"/>
#endif
#endif

#if defined(__MMI_IME_CROATIAN__)
    <STRING id="STR_INPUT_METHOD_SMART_U_CROATIAN"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_CROATIAN"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_CROATIAN"/>
#endif
#endif

#if defined(__MMI_MULTITAP_ROMANIAN__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_ROMANIAN"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_ROMANIAN"/>
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_ROMANIAN"/>
#endif
#endif

#if defined(__MMI_IME_ROMANIAN__)
    <STRING id="STR_INPUT_METHOD_SMART_U_ROMANIAN"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_ROMANIAN"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_ROMANIAN"/>
#endif
#endif

#if defined(__MMI_MULTITAP_SLOVENIAN__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_SLOVENIAN"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_SLOVENIAN"/>
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_SLOVENIAN"/>
#endif
#endif

#if defined(__MMI_IME_SLOVENIAN__)
    <STRING id="STR_INPUT_METHOD_SMART_U_SLOVENIAN"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_SLOVENIAN"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_SLOVENIAN"/>
#endif
#endif

#if defined(__MMI_MULTITAP_GREEK__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_GREEK"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_GREEK"/>
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_GREEK"/>
#endif
#endif

#if defined(__MMI_IME_GREEK__)
    <STRING id="STR_INPUT_METHOD_SMART_U_GREEK"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_GREEK"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_GREEK"/>
#endif
#endif

#if defined(__MMI_MULTITAP_XHOSA__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_XHOSA"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_XHOSA"/>
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_XHOSA"/>
#endif
#endif

#if defined(__MMI_IME_XHOSA__)
    <STRING id="STR_INPUT_METHOD_SMART_U_XHOSA"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_XHOSA"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_XHOSA"/>
#endif
#endif

#if defined(__MMI_MULTITAP_SWAHILI__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_SWAHILI"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_SWAHILI"/>
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_SWAHILI"/>
#endif
#endif

#if defined(__MMI_IME_SWAHILI__)
    <STRING id="STR_INPUT_METHOD_SMART_U_SWAHILI"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_SWAHILI"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_SWAHILI"/>
#endif
#endif

#if defined(__MMI_MULTITAP_AFRIKAANS__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_AFRIKAANS"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_AFRIKAANS"/>
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_AFRIKAANS"/>
#endif
#endif

#if defined(__MMI_IME_AFRIKAANS__)    
    <STRING id="STR_INPUT_METHOD_SMART_U_AFRIKAANS"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_AFRIKAANS"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_AFRIKAANS"/>
#endif
#endif

#if defined(__MMI_MULTITAP_ZULU__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_ZULU"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_ZULU"/>
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_ZULU"/>
#endif
#endif

#if defined(__MMI_IME_ZULU__)
    <STRING id="STR_INPUT_METHOD_SMART_U_ZULU"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_ZULU"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_ZULU"/>
#endif
#endif

#if defined(__MMI_MULTITAP_LITHUANIAN__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_LITHUANIAN"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_LITHUANIAN"/>
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_LITHUANIAN"/>
#endif
#endif

#if defined(__MMI_IME_LITHUANIAN__)
    <STRING id="STR_INPUT_METHOD_SMART_U_LITHUANIAN"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_LITHUANIAN"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_LITHUANIAN"/>
#endif
#endif

#if defined(__MMI_MULTITAP_LATVIAN__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_LATVIAN"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_LATVIAN"/>
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_LATVIAN"/>
#endif
#endif

#if defined(__MMI_IME_LATVIAN__)
    <STRING id="STR_INPUT_METHOD_SMART_U_LATVIAN"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_LATVIAN"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_LATVIAN"/>
#endif
#endif

#if defined(__MMI_MULTITAP_ESTONIAN__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_ESTONIAN"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_ESTONIAN"/>
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_ESTONIAN"/>
#endif
#endif

#if defined(__MMI_IME_ESTONIAN__)
    <STRING id="STR_INPUT_METHOD_SMART_U_ESTONIAN"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_ESTONIAN"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_ESTONIAN"/>
#endif
#endif

#if defined(__MMI_MULTITAP_ALBANIAN__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_ALBANIAN"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_ALBANIAN"/>
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_ALBANIAN"/>
#endif
#endif

#if defined(__MMI_IME_ALBANIAN__)
    <STRING id="STR_INPUT_METHOD_SMART_U_ALBANIAN"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_ALBANIAN"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_ALBANIAN"/>
#endif
#endif

#if defined(__MMI_MULTITAP_ARMENIAN__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_ARMENIAN"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_ARMENIAN"/>
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_ARMENIAN"/>
#endif
#endif

#if defined(__MMI_IME_ARMENIAN__)
    <STRING id="STR_INPUT_METHOD_SMART_U_ARMENIAN"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_ARMENIAN"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_ARMENIAN"/>
#endif
#endif

#if defined(__MMI_MULTITAP_GEORGIAN__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_GEORGIAN"/>
#endif

#if defined(__MMI_IME_GEORGIAN__)
    <STRING id="STR_INPUT_METHOD_SMART_GEORGIAN"/>
#endif

#if defined(__MMI_MULTITAP_MOLDOVAN__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_MOLDOVAN"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_MOLDOVAN"/>
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_MOLDOVAN"/>
#endif
#endif

#if defined(__MMI_IME_MOLDOVAN__)
    <STRING id="STR_INPUT_METHOD_SMART_U_MOLDOVAN"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_MOLDOVAN"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_MOLDOVAN"/>
#endif
#endif

#if defined(__MMI_MULTITAP_AZERBAIJANI__)
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_AZERBAIJANI"/>
#endif
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_AZERBAIJANI"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_AZERBAIJANI"/>
#endif

#if defined(__MMI_IME_AZERBAIJANI__)
    <STRING id="STR_INPUT_METHOD_SMART_U_AZERBAIJANI"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_AZERBAIJANI"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_AZERBAIJANI"/>
#endif
#endif

#if defined(__MMI_MULTITAP_CATALAN__)
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_CATALAN"/>
#endif
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_CATALAN"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_CATALAN"/>
#endif

#if defined(__MMI_IME_CATALAN__)
    <STRING id="STR_INPUT_METHOD_SMART_U_CATALAN"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_CATALAN"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_CATALAN"/>
#endif
#endif

#if defined(__MMI_MULTITAP_KAZAKH__)
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_KAZAKH"/>
#endif
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_KAZAKH"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_KAZAKH"/>
#endif

#if defined(__MMI_IME_KAZAKH__)
    <STRING id="STR_INPUT_METHOD_SMART_U_KAZAKH"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_KAZAKH"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_KAZAKH"/>
#endif
#endif

#if defined(__MMI_MULTITAP_MACEDONIAN__)
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_MACEDONIAN"/>
#endif
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_MACEDONIAN"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_MACEDONIAN"/>
#endif

#if defined(__MMI_IME_MACEDONIAN__)
    <STRING id="STR_INPUT_METHOD_SMART_U_MACEDONIAN"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_MACEDONIAN"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_MACEDONIAN"/>
#endif
#endif

#if defined(__MMI_MULTITAP_HAUSA__)
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_HAUSA"/>
#endif
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_HAUSA"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_HAUSA"/>
#endif

#if defined(__MMI_IME_HAUSA__)
    <STRING id="STR_INPUT_METHOD_SMART_U_HAUSA"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_HAUSA"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_HAUSA"/>
#endif
#endif

#if defined(__MMI_MULTITAP_GALICIAN__)
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_GALICIAN"/>
#endif
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_GALICIAN"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_GALICIAN"/>
#endif

#if defined(__MMI_IME_GALICIAN__)
    <STRING id="STR_INPUT_METHOD_SMART_U_GALICIAN"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_GALICIAN"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_GALICIAN"/>
#endif
#endif

#if defined(__MMI_MULTITAP_BASQUE__)
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_BASQUE"/>
#endif
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_BASQUE"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_BASQUE"/>
#endif

#if defined(__MMI_IME_BASQUE__)
    <STRING id="STR_INPUT_METHOD_SMART_U_BASQUE"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_BASQUE"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_BASQUE"/>
#endif
#endif

#if defined(__MMI_MULTITAP_IGBO__)
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_IGBO"/>
#endif
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_IGBO"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_IGBO"/>
#endif

#if defined(__MMI_IME_IGBO__)
    <STRING id="STR_INPUT_METHOD_SMART_U_IGBO"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_IGBO"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_IGBO"/>
#endif
#endif

#if defined(__MMI_MULTITAP_FILIPINO__)
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_FILIPINO"/>
#endif
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_FILIPINO"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_FILIPINO"/>
#endif

#if defined(__MMI_IME_FILIPINO__)
    <STRING id="STR_INPUT_METHOD_SMART_U_FILIPINO"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_FILIPINO"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_FILIPINO"/>
#endif
#endif

#if defined(__MMI_MULTITAP_IRISH__)
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_IRISH"/>
#endif
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_IRISH"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_IRISH"/>
#endif

#if defined(__MMI_IME_IRISH__)
    <STRING id="STR_INPUT_METHOD_SMART_U_IRISH"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_IRISH"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_IRISH"/>
#endif
#endif

#if defined(__MMI_MULTITAP_SESOTHO__)
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_SESOTHO"/>
#endif
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_SESOTHO"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_SESOTHO"/>
#endif

#if defined(__MMI_T9_SESOTHO__)
    <STRING id="STR_INPUT_METHOD_SMART_U_SESOTHO"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_SESOTHO"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_SESOTHO"/>
#endif
#endif

#if defined(__MMI_MULTITAP_TAGALOG__)
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_TAGALOG"/>
#endif
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_TAGALOG"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_TAGALOG"/>
#endif

#if defined(__MMI_T9_TAGALOG__) || defined(__MMI_ZI_TAGALOG__)
    <STRING id="STR_INPUT_METHOD_SMART_U_TAGALOG"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_TAGALOG"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_TAGALOG"/>
#endif
#endif

#if defined(__MMI_MULTITAP_ICELANDIC__)
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_ICELANDIC"/>
#endif
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_ICELANDIC"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_ICELANDIC"/>
#endif

#if defined(__MMI_ZI_ICELANDIC__)||defined(__MMI_T9_ICELANDIC__)
    <STRING id="STR_INPUT_METHOD_SMART_U_ICELANDIC"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_ICELANDIC"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_ICELANDIC"/>
#endif
#endif

#if defined(__MMI_ZI_UK_ENGLISH__)
    <STRING id="STR_INPUT_METHOD_SMART_U_UK_ABC"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_UK_ABC"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_UK_ABC"/>    
#endif
#endif

#if defined(__MMI_MULTITAP_SERBIAN__)
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_SERBIAN"/>
#endif
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_SERBIAN"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_SERBIAN"/>
#endif

#if defined(__MMI_IME_SERBIAN__)
    <STRING id="STR_INPUT_METHOD_SMART_U_SERBIAN"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_SERBIAN"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_SERBIAN"/>
#endif
#endif

#if defined(__MMI_MULTITAP_YORUBA__)
#if defined(__MMI_MULTITAP_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_MULTITAP_FIRST_U_YORUBA"/>
#endif
    <STRING id="STR_INPUT_METHOD_MULTITAP_U_YORUBA"/>
    <STRING id="STR_INPUT_METHOD_MULTITAP_L_YORUBA"/>
#endif

#if defined(__MMI_IME_YORUBA__)
    <STRING id="STR_INPUT_METHOD_SMART_U_YORUBA"/>
    <STRING id="STR_INPUT_METHOD_SMART_L_YORUBA"/>
#if defined(__MMI_SMART_FIRST_UPPERCASE__)
    <STRING id="STR_INPUT_METHOD_SMART_FIRST_U_YORUBA"/>
#endif
#endif

#if defined(__MMI_MULTITAP_MARATHI__)  
    <STRING id="STR_INPUT_METHOD_MULTITAP_MARATHI"/>
#endif

#if defined(__MMI_IME_MARATHI__) 
    <STRING id="STR_INPUT_METHOD_SMART_MARATHI"/>
#endif

#if defined (__MMI_MULTITAP_TAMIL__) 
    <STRING id="STR_INPUT_METHOD_MULTITAP_TAMIL"/>
#endif

#if defined(__MMI_IME_TAMIL__) 
    <STRING id="STR_INPUT_METHOD_SMART_TAMIL"/>
#endif

#if defined (__MMI_MULTITAP_BENGALI__)  
    <STRING id="STR_INPUT_METHOD_MULTITAP_BENGALI"/>
#endif

#if defined(__MMI_IME_BENGALI__) 
    <STRING id="STR_INPUT_METHOD_SMART_BENGALI"/>
#endif

#if defined(__MMI_ZI_ASSAMESE__)|| defined(__MMI_T9_ASSAMESE__) || defined(__MMI_CSTAR_ASSAMESE__) 
    <STRING id="STR_INPUT_METHOD_SMART_ASSAMESE"/>
#endif

#if defined (__MMI_MULTITAP_ASSAMESE__)  
    <STRING id="STR_INPUT_METHOD_MULTITAP_ASSAMESE"/>
#endif

#if defined (__MMI_MULTITAP_PUNJABI__) 
    <STRING id="STR_INPUT_METHOD_MULTITAP_PUNJABI"/>
#endif

#if defined(__MMI_IME_PUNJABI__) 
    <STRING id="STR_INPUT_METHOD_SMART_PUNJABI"/>
#endif

#if defined (__MMI_MULTITAP_TELUGU__) 
    <STRING id="STR_INPUT_METHOD_MULTITAP_TELUGU"/>
#endif

#if defined (__MMI_MULTITAP_KANNADA__) 
    <STRING id="STR_INPUT_METHOD_MULTITAP_KANNADA"/>
#endif

#if defined(__MMI_IME_KANNADA__) 
    <STRING id="STR_INPUT_METHOD_SMART_KANNADA"/>
#endif

#if defined (__MMI_MULTITAP_MALAYALAM__) 
    <STRING id="STR_INPUT_METHOD_MULTITAP_MALAYALAM"/>
#endif

#if defined (__MMI_MULTITAP_LAO__) 
    <STRING id="STR_INPUT_METHOD_MULTITAP_LAO"/>
#endif

#if defined (__MMI_IME_LAO__) 
    <STRING id="STR_INPUT_METHOD_SMART_LAO"/>
#endif

#if defined (__MMI_MULTITAP_KHMER__) 
    <STRING id="STR_INPUT_METHOD_MULTITAP_KHMER"/>
#endif

#if defined (__MMI_MULTITAP_MYANMAR__) 
    <STRING id="STR_INPUT_METHOD_MULTITAP_MYANMAR"/>
#endif
#if defined (__MMI_IME_MYANMAR__) 
    <STRING id="STR_INPUT_METHOD_SMART_MYANMAR"/>
#endif
#if defined(__MMI_IME_MALAYALAM__) 
    <STRING id="STR_INPUT_METHOD_SMART_MALAYALAM"/>
#endif

#if defined(__MMI_IME_KHMER__) 
    <STRING id="STR_INPUT_METHOD_SMART_KHMER"/>
#endif

#if defined (__MMI_MULTITAP_GUJARATI__) 
    <STRING id="STR_INPUT_METHOD_MULTITAP_GUJARATI"/>
#endif

#if defined(__MMI_IME_GUJARATI__) 
    <STRING id="STR_INPUT_METHOD_SMART_GUJARATI"/>
#endif

#if defined (__MMI_MULTITAP_ORIYA__) 
    <STRING id="STR_INPUT_METHOD_MULTITAP_ORIYA"/>
#endif

#if defined(__MMI_IME_ORIYA__) 
    <STRING id="STR_INPUT_METHOD_SMART_ORIYA"/>
#endif

#if defined(__MMI_IME_TELUGU__) 
    <STRING id="STR_INPUT_METHOD_SMART_TELUGU"/>
#endif

#if defined(__MMI_PREFER_WRITING_LANG__) || defined(__MMI_MIXED_LANG_SUPPORT__)
    <STRING id="STR_ID_PHNSET_PREFERED_WRITING_LANG"/>
#if defined(__MMI_MIXED_LANG_SUPPORT__)
    <STRING id="STR_ID_PHNSET_PREFERED_WRITING_LANG_MAIN"/>
    <STRING id="STR_ID_PHNSET_PREFERED_WRITING_LANG_SUB"/>
#endif /* defined(__MMI_MIXED_LANG_SUPPORT__) */
#endif /* defined(__MMI_PREFER_WRITING_LANG__) */

    <!-----------------------------------------------------Image Resource Area------------------------------------------------------>
    #if defined(__MMI_IME_FTE_ENHANCE__)
    #if defined(__MMI_IME_CANDIDATE_GRID__)
    <IMAGE id = "MMI_IMUI_IMG_IME_CG_ARROWDOWN">CUST_IMG_PATH"\\\\MainLCD\\\\UIElement\\\\VK3\\\\ime\\\\new_cand_box\\\\Arrow_down.png"</IMAGE>;
    <IMAGE id = "MMI_IMUI_IMG_IME_CG_ARROWUP">CUST_IMG_PATH"\\\\MainLCD\\\\UIElement\\\\VK3\\\\ime\\\\new_cand_box\\\\Arrow_up.png"</IMAGE>;
    <IMAGE id = "MMI_IMUI_IMG_IME_CG_ARROWDOWNDIS">CUST_IMG_PATH"\\\\MainLCD\\\\UIElement\\\\VK3\\\\ime\\\\new_cand_box\\\\Arrow_down_disable.png"</IMAGE>;
    <IMAGE id = "MMI_IMUI_IMG_IME_CG_ARROWUPDIS">CUST_IMG_PATH"\\\\MainLCD\\\\UIElement\\\\VK3\\\\ime\\\\new_cand_box\\\\Arrow_up_disable.png"</IMAGE>;
    <IMAGE id = "MMI_IMUI_IMG_IME_CG_BACK">CUST_IMG_PATH"\\\\MainLCD\\\\UIElement\\\\VK3\\\\ime\\\\new_cand_box\\\\Back.png"</IMAGE>;
    <IMAGE id = "MMI_IMUI_IMG_IME_CG_BACKSPACE">CUST_IMG_PATH"\\\\MainLCD\\\\UIElement\\\\VK3\\\\ime\\\\new_cand_box\\\\delete.png"</IMAGE>;
    <IMAGE id = "MMI_IMUI_IMG_IME_CG_CAND_BG">CUST_IMG_PATH"\\\\MainLCD\\\\UIElement\\\\VK3\\\\ime\\\\new_cand_box\\\\candidate.9slice.png"</IMAGE>;
    <IMAGE id = "MMI_IMUI_IMG_IME_CG_CAND_BG_HL">CUST_IMG_PATH"\\\\\MainLCD\\\\UIElement\\\\VK3\\\\ime\\\\new_cand_box\\\\highlight_bkg.9slice.png"</IMAGE>;
    <IMAGE id = "MMI_IMUI_IMG_IME_CG_EXPAND">CUST_IMG_PATH"\\\\MainLCD\\\\UIElement\\\\VK3\\\\ime\\\\new_cand_box\\\\Expand_Candidate_box.png"</IMAGE>;
    <IMAGE id = "MMI_IMUI_IMG_IME_CG_BG">CUST_IMG_PATH"\\\\MainLCD\\\\UIElement\\\\VK3\\\\ime\\\\new_cand_box\\\\keyboard_background.9slice.png"</IMAGE>;
    <IMAGE id = "MMI_IMUI_IMG_IME_CG_BG_BLACK">CUST_IMG_PATH"\\\\MainLCD\\\\UIElement\\\\VK3\\\\function_bkg.9slice.png"</IMAGE>;
    #endif

    #if defined(__MMI_IME_SCROLLING_COMPOSITION__)
    <IMAGE id = "MMI_IMUI_IMG_IME_SC_BG">CUST_IMG_PATH"\\\\MainLCD\\\\UIElement\\\\VK3\\\\ime\\\\new_cand_box\\\\keyboard_background.9slice.png"</IMAGE>;
    <IMAGE id = "MMI_IMUI_IMG_IME_SC_CAND_BG">CUST_IMG_PATH"\\\\MainLCD\\\\UIElement\\\\VK3\\\\ime\\\\new_cand_box\\\\candidate.9slice.png"</IMAGE>;
    <IMAGE id = "MMI_IMUI_IMG_IME_SC_CAND_BG_HL">CUST_IMG_PATH"\\\\MainLCD\\\\UIElement\\\\VK3\\\\ime\\\\new_cand_box\\\\highlight_bkg.9slice.png"</IMAGE>;
    #endif
	
    #if !defined(__NO_HANDWRITING__)
    <IMAGE id = "MMI_IMUI_IMG_HANDWRITING_AREA">CUST_IMG_PATH"\\\\MainLCD\\\\UIElement\\\\VK3\\\\handwrite_bkg.9slice.png"</IMAGE>;    
    #endif
		#endif
    <!-----------------------------------------------------Theme Resource Area----------------------------------------------------->
#if defined(__COSMOS_MMI__)
<THEME>
    <IMAGE id = "VADP_IMG_IME_CAND_BG_SMALL"/>
    <IMAGE id = "VADP_IMG_IME_CAND_BG_MEDIUM"/>
    <IMAGE id = "VADP_IMG_IME_CAND_BG_LARGE"/>
    <IMAGE id = "VADP_IMG_IME_CAND_FOCUS_FRAME_SMALL"/>
    <IMAGE id = "VADP_IMG_IME_CAND_FOCUS_FRAME_MEDIUM"/>
    <IMAGE id = "VADP_IMG_IME_CAND_FOCUS_FRAME_LARGE"/>
    <IMAGE id = "VADP_IMG_IME_CAND_SEP_SMALL"/>
    <IMAGE id = "VADP_IMG_IME_CAND_SEP_MEDIUM"/>
    <IMAGE id = "VADP_IMG_IME_CAND_SEP_LARGE"/>
    <IMAGE id = "VADP_IMG_IME_CAND_LEFT_ARROW_NORMAL_SMALL"/>
    <IMAGE id = "VADP_IMG_IME_CAND_LEFT_ARROW_NORMAL_MEDIUM"/>
    <IMAGE id = "VADP_IMG_IME_CAND_LEFT_ARROW_NORMAL_LARGE"/>
    <IMAGE id = "VADP_IMG_IME_CAND_LEFT_ARROW_DOWN_SMALL"/>
    <IMAGE id = "VADP_IMG_IME_CAND_LEFT_ARROW_DOWN_MEDIUM"/>
    <IMAGE id = "VADP_IMG_IME_CAND_LEFT_ARROW_DOWN_LARGE"/>
    <IMAGE id = "VADP_IMG_IME_CAND_LEFT_ARROW_DISABLE_SMALL"/>
    <IMAGE id = "VADP_IMG_IME_CAND_LEFT_ARROW_DISABLE_MEDIUM"/>
    <IMAGE id = "VADP_IMG_IME_CAND_LEFT_ARROW_DISABLE_LARGE"/>
    <IMAGE id = "VADP_IMG_IME_CAND_RIGHT_ARROW_NORMAL_SMALL"/>
    <IMAGE id = "VADP_IMG_IME_CAND_RIGHT_ARROW_NORMAL_MEDIUM"/>
    <IMAGE id = "VADP_IMG_IME_CAND_RIGHT_ARROW_NORMAL_LARGE"/>
    <IMAGE id = "VADP_IMG_IME_CAND_RIGHT_ARROW_DOWN_SMALL"/>
    <IMAGE id = "VADP_IMG_IME_CAND_RIGHT_ARROW_DOWN_MEDIUM"/>
    <IMAGE id = "VADP_IMG_IME_CAND_RIGHT_ARROW_DOWN_LARGE"/>
    <IMAGE id = "VADP_IMG_IME_CAND_RIGHT_ARROW_DISABLE_SMALL"/>
    <IMAGE id = "VADP_IMG_IME_CAND_RIGHT_ARROW_DISABLE_MEDIUM"/>
    <IMAGE id = "VADP_IMG_IME_CAND_RIGHT_ARROW_DISABLE_LARGE"/>
    <IMAGE id = "VADP_IMG_IME_CAND_HIGHLIGHT_SMALL"/>
    <IMAGE id = "VADP_IMG_IME_CAND_HIGHLIGHT_MEDIUM"/>
    <IMAGE id = "VADP_IMG_IME_CAND_HIGHLIGHT_LARGE"/>
    <IMAGE id = "VADP_IMG_IME_CAND_DULL_HIGHLIGHT_SMALL"/>
    <IMAGE id = "VADP_IMG_IME_CAND_DULL_HIGHLIGHT_MEDIUM"/>
    <IMAGE id = "VADP_IMG_IME_CAND_DULL_HIGHLIGHT_LARGE"/>
    <IMAGE id = "VADP_IMG_IME_INPUT_BG_SMALL"/>
    <IMAGE id = "VADP_IMG_IME_INPUT_BG_MEDIUM"/>
    <IMAGE id = "VADP_IMG_IME_INPUT_BG_LARGE"/>
    <IMAGE id = "VADP_IMG_IME_CG_ARROWDOWN"/>
    <IMAGE id = "VADP_IMG_IME_CG_ARROWUP"/>
    <IMAGE id = "VADP_IMG_IME_CG_ARROWDOWNDIS"/>
    <IMAGE id = "VADP_IMG_IME_CG_ARROWUPDIS"/>
    <IMAGE id = "VADP_IMG_IME_CG_BACK"/>
    <IMAGE id = "VADP_IMG_IME_CG_BACKSPACE"/>
    <IMAGE id = "VADP_IMG_IME_CG_CAND_BG"/>
    <IMAGE id = "VADP_IMG_IME_CG_CAND_BG_HL"/>
    <IMAGE id = "VADP_IMG_IME_CG_EXPAND"/>                                              
    <IMAGE id = "VADP_IMG_IME_CG_BG"/>                                                                                      
    <IMAGE id = "VADP_IMG_IME_SC_BG"/>                                            
    <IMAGE id = "VADP_IMG_IME_SC_CAND_BG"/>                                            
    <IMAGE id = "VADP_IMG_IME_SC_CAND_BG_HL"/>                                           
    <IMAGE id = "VADP_IMG_IME_CAND_HW_BG"/>  

                                             
    <IMAGE id = "IMG_ID_DISABLE_BKG_9SLICE"/>     
    <IMAGE id = "IMG_ID_BALLOON_BKG_9SLICE"/>                                           
    <IMAGE id = "IMG_ID_BALLOON_BKG2_9SLICE"/>                                           
    <IMAGE id = "IMG_ID_CHARACTER_BKG_9SLICE"/>                                           
    <IMAGE id = "IMG_ID_FUNCTION_BKG_9SLICE"/>                                           
    <IMAGE id = "IMG_ID_HIGHLIGHT_BKG_9SLICE"/>                                           
    <IMAGE id = "IMG_ID_KEYBOARD_BACKGROUND_9SLICE"/>                                     
    <IMAGE id = "IMG_ID_POPUP_KEYBOARD_BACKGROUND_9SLICE"/>                                       
    <COLOR id = "VADP_COL_IME_HAND_WRITING_STROKE"/>
    <COLOR id = "VADP_COL_VK_HILIGHT"/>
    <COLOR id = "VADP_COL_VK_DISABLE"/>
</THEME>
#endif

<!-----------------------------------------------------Event Section------------------------------------------------------>

#if defined(__MMI_COSMOS_KEYPAD_SLIDER__) 
    <RECEIVER id="EVT_ID_GPIO_CLAM_OPEN" proc="mmi_imc_process_slider_event"/>
    <RECEIVER id="EVT_ID_GPIO_CLAM_CLOSE" proc="mmi_imc_process_slider_event"/>
#endif

</APP>


