#include "mmi_features.h"
#include "custresdef.h"

#if defined(__MMI_VUI_MAIN_MENU_SWITCH_EFFECT__)

#if defined(__MMI_VUI_3D_MAINMENU__) || defined(__COSMOS_MMI__) || defined(__MMI_VUI_LAUNCHER__) || defined(__MMI_VUI_LAUNCHER_KEY__)

<?xml version="1.0" encoding="UTF-8"?>

<APP id="VCP_PAGE_MENU_TRANSITION">

    <!-----------------------------------------------------Image Resource Area------------------------------------------------------>   
    #define ROOT_PATH RES_THEME_ROOT"\\\\Default\\\\Mainmenu_Icon\\\\"
    <IMAGE id="IMG_ID_VCP_PAGE_MENU_TRANSITION_TYPE_NORMAL">ROOT_PATH"MainMenu.png"</IMAGE>
    <IMAGE id="IMG_ID_VCP_PAGE_MENU_TRANSITION_TYPE_BALL">ROOT_PATH"MainMenu.png"</IMAGE>
    <IMAGE id="IMG_ID_VCP_PAGE_MENU_TRANSITION_TYPE_SPACE_BEAM">ROOT_PATH"MainMenu.png"</IMAGE>
    <IMAGE id="IMG_ID_VCP_PAGE_MENU_TRANSITION_TYPE_JUMP_UP">ROOT_PATH"MainMenu.png"</IMAGE>
    <IMAGE id="IMG_ID_VCP_PAGE_MENU_TRANSITION_TYPE_WAVE">ROOT_PATH"MainMenu.png"</IMAGE>
    <IMAGE id="IMG_ID_VCP_PAGE_MENU_TRANSITION_TYPE_TILT">ROOT_PATH"MainMenu.png"</IMAGE>
    <IMAGE id="IMG_ID_VCP_PAGE_MENU_TRANSITION_TYPE_ROLL">ROOT_PATH"MainMenu.png"</IMAGE>
    <IMAGE id="IMG_ID_VCP_PAGE_MENU_TRANSITION_TYPE_SLIDE_DOWN">ROOT_PATH"MainMenu.png"</IMAGE>
    <IMAGE id="IMG_ID_VCP_PAGE_MENU_TRANSITION_TYPE_SLIDE_UP">ROOT_PATH"MainMenu.png"</IMAGE>
    <IMAGE id="IMG_ID_VCP_PAGE_MENU_TRANSITION_TYPE_COLLECTION_MM">ROOT_PATH"MainMenu.png"</IMAGE>
    <IMAGE id="IMG_ID_VCP_PAGE_MENU_TRANSITION_TYPE_COLLECTION_TB">ROOT_PATH"MainMenu.png"</IMAGE>
    <IMAGE id="IMG_ID_VCP_PAGE_MENU_TRANSITION_TYPE_CYLINDER">ROOT_PATH"MainMenu.png"</IMAGE>
    <IMAGE id="IMG_ID_VCP_PAGE_MENU_TRANSITION_TYPE_TORNADO">ROOT_PATH"MainMenu.png"</IMAGE>
    <IMAGE id="IMG_ID_VCP_PAGE_MENU_TRANSITION_TYPE_CUBE">ROOT_PATH"MainMenu.png"</IMAGE>
    <IMAGE id="IMG_ID_VCP_PAGE_MENU_TRANSITION_TYPE_HEXAGONAL_PRISM">ROOT_PATH"MainMenu.png"</IMAGE>

    <!-----------------------------------------------------String Resource Area------------------------------------------------------>   
    <STRING id="STR_ID_VCP_PAGE_MENU_TRANSITION_TYPE_NORMAL">"Normal"</STRING>
    <STRING id="STR_ID_VCP_PAGE_MENU_TRANSITION_TYPE_BALL">"Ball"</STRING>
    <STRING id="STR_ID_VCP_PAGE_MENU_TRANSITION_TYPE_SPACE_BEAM">"Space beam"</STRING>
    <STRING id="STR_ID_VCP_PAGE_MENU_TRANSITION_TYPE_JUMP_UP">"Jump up"</STRING>
    <STRING id="STR_ID_VCP_PAGE_MENU_TRANSITION_TYPE_WAVE">"Wave"</STRING>
    <STRING id="STR_ID_VCP_PAGE_MENU_TRANSITION_TYPE_TILT">"Tilt"</STRING>
    <STRING id="STR_ID_VCP_PAGE_MENU_TRANSITION_TYPE_ROLL">"Roll"</STRING>
    <STRING id="STR_ID_VCP_PAGE_MENU_TRANSITION_TYPE_SLIDE_DOWN">"Slide down"</STRING>
    <STRING id="STR_ID_VCP_PAGE_MENU_TRANSITION_TYPE_SLIDE_UP">"Slide up"</STRING>
    <STRING id="STR_ID_VCP_PAGE_MENU_TRANSITION_TYPE_COLLECTION_MM">"Collection MM"</STRING>
    <STRING id="STR_ID_VCP_PAGE_MENU_TRANSITION_TYPE_COLLECTION_TB">"Collection TB"</STRING>
    <STRING id="STR_ID_VCP_PAGE_MENU_TRANSITION_TYPE_CYLINDER">"Cylinder"</STRING>
    <STRING id="STR_ID_VCP_PAGE_MENU_TRANSITION_TYPE_TORNADO">"Tornado"</STRING>
    <STRING id="STR_ID_VCP_PAGE_MENU_TRANSITION_TYPE_CUBE">"Cube"</STRING>
    <STRING id="STR_ID_VCP_PAGE_MENU_TRANSITION_TYPE_HEXAGONAL_PRISM">"Hexagonal prisme"</STRING>

</APP>

#endif

#endif // __MMI_VUI_MAIN_MENU_SWITCH_EFFECT__

