/* This file is automatically generated by mslt_parse_info.pl. Do not modify it. */

#ifndef __MSLT_TABLE_H__
#define __MSLT_TABLE_H__

#ifndef __MTK_TARGET__

#define MMI_MSLT_REGION_ID_NUM    151

typedef enum
{
    MMI_MSLT_REGION_TITLE,
    MMI_MSLT_REGION_LSK,
    MMI_MSLT_REGION_RSK,
    MMI_MSLT_REGION_CSK,
    MMI_MSLT_REGION_TEXT,
    MMI_MSLT_REGION_HINT,
    MMI_MSLT_REGION_ICONTEXT,
    MMI_MSLT_REGION_TWOSTATE,
    MMI_MSLT_REGION_TWOLINE,
    MMI_MSLT_REGION_TAB,
    MMI_MSLT_REGION_ICON_BAR_HINT,
    MMI_MSLT_REGION_IDLE_DAY,
    MMI_MSLT_REGION_POPUP,
    MMI_MSLT_REGION_POPUPCONFIRM,
    MMI_MSLT_REGION_UNLIM,
    MMI_MSLT_REGION_C009_1,
    MMI_MSLT_REGION_C230_1,
    MMI_MSLT_REGION_C017_1,
    MMI_MSLT_REGION_C018_1,
    MMI_MSLT_REGION_C019_1,
    MMI_MSLT_REGION_C032_1,
    MMI_MSLT_REGION_C033_1,
    MMI_MSLT_REGION_C033_2,
    MMI_MSLT_REGION_C057_1,
    MMI_MSLT_REGION_C061_1,
    MMI_MSLT_REGION_C069_1,
    MMI_MSLT_REGION_C072_1,
    MMI_MSLT_REGION_C073_1,
    MMI_MSLT_REGION_C085_1,
    MMI_MSLT_REGION_C085_2,
    MMI_MSLT_REGION_C086_1,
    MMI_MSLT_REGION_C088_1,
    MMI_MSLT_REGION_C089_1,
    MMI_MSLT_REGION_C090_1,
    MMI_MSLT_REGION_C090_2,
    MMI_MSLT_REGION_C090_3,
    MMI_MSLT_REGION_C111_1,
    MMI_MSLT_REGION_C112_1,
    MMI_MSLT_REGION_C113_1,
    MMI_MSLT_REGION_C113_2,
    MMI_MSLT_REGION_C113_3,
    MMI_MSLT_REGION_C120_1,
    MMI_MSLT_REGION_C122_1,
    MMI_MSLT_REGION_C122_2,
    MMI_MSLT_REGION_C122_3,
    MMI_MSLT_REGION_C125_1,
    MMI_MSLT_REGION_C125_2,
    MMI_MSLT_REGION_C128_1,
    MMI_MSLT_REGION_C129_1,
    MMI_MSLT_REGION_C130_1,
    MMI_MSLT_REGION_C144_1,
    MMI_MSLT_REGION_C145_1,
    MMI_MSLT_REGION_C150_1,
    MMI_MSLT_REGION_C154_1,
    MMI_MSLT_REGION_C154_2,
    MMI_MSLT_REGION_C165_1,
    MMI_MSLT_REGION_C205_1,
    MMI_MSLT_REGION_C211_1,
    MMI_MSLT_REGION_C211_2,
    MMI_MSLT_REGION_C213_1,
    MMI_MSLT_REGION_C222_1,
    MMI_MSLT_REGION_C229_1,
    MMI_MSLT_REGION_C261_1,
    MMI_MSLT_REGION_C261_2,
    MMI_MSLT_REGION_C264_1,
    MMI_MSLT_REGION_C265_1,
    MMI_MSLT_REGION_C265_2,
    MMI_MSLT_REGION_C265_3,
    MMI_MSLT_REGION_C267_1,
    MMI_MSLT_REGION_C267_2,
    MMI_MSLT_REGION_C280_1,
    MMI_MSLT_REGION_C311_1,
    MMI_MSLT_REGION_C312_1,
    MMI_MSLT_REGION_C354_1,
    MMI_MSLT_REGION_C354_2,
    MMI_MSLT_REGION_C384_1,
    MMI_MSLT_REGION_C384_2,
    MMI_MSLT_REGION_C402_1,
    MMI_MSLT_REGION_C402_2,
    MMI_MSLT_REGION_C403_1,
    MMI_MSLT_REGION_C412_1,
    MMI_MSLT_REGION_C412_2,
    MMI_MSLT_REGION_C420_1,
    MMI_MSLT_REGION_C420_2,
    MMI_MSLT_REGION_C420_3,
    MMI_MSLT_REGION_C425_1,
    MMI_MSLT_REGION_C425_2,
    MMI_MSLT_REGION_C426_1,
    MMI_MSLT_REGION_C426_2,
    MMI_MSLT_REGION_C427_1,
    MMI_MSLT_REGION_C427_2,
    MMI_MSLT_REGION_C427_3,
    MMI_MSLT_REGION_C428_1,
    MMI_MSLT_REGION_C429_1,
    MMI_MSLT_REGION_C429_2,
    MMI_MSLT_REGION_C429_3,
    MMI_MSLT_REGION_C430_1,
    MMI_MSLT_REGION_C433_1,
    MMI_MSLT_REGION_C435_1,
    MMI_MSLT_REGION_C620_1,
    MMI_MSLT_REGION_CEMS_1,
    MMI_MSLT_REGION_STEXT,
    MMI_MSLT_REGION_SICONTEXT,
    MMI_MSLT_REGION_STWOSTATE,
    MMI_MSLT_REGION_MATRIX,
    MMI_MSLT_REGION_LISTMAIN,
    MMI_MSLT_REGION_BDTITLE,
    MMI_MSLT_REGION_BDITEM,
    MMI_MSLT_REGION_PAGEITEM,
    MMI_MSLT_REGION_MEDPLY_LSK,
    MMI_MSLT_REGION_MEDPLY_RSK,
    MMI_MSLT_REGION_CAMCO_ITEM,
    MMI_MSLT_REGION_CAMCO_TITLE,
    MMI_MSLT_REGION_CAMCO_OPTION,
    MMI_MSLT_REGION_CAMCO_HINT,
    MMI_MSLT_REGION_IME_HINT,
    MMI_MSLT_REGION_IME_CAND,
    MMI_MSLT_REGION_DJITEM,
    MMI_MSLT_REGION_CAMERA_HINT,
    MMI_MSLT_REGION_CAMERA_TITLE,
    MMI_MSLT_REGION_CAMERA_SUB_HINT,
    MMI_MSLT_REGION_MTV_HINT,
    MMI_MSLT_REGION_SNDREC_TITLE,
    MMI_MSLT_REGION_SNDREC_STATE,
    MMI_MSLT_REGION_SNDREC_SK,
    MMI_MSLT_REGION_C409_1,
    MMI_MSLT_REGION_C409_2,
    MMI_MSLT_REGION_C407_1,
    MMI_MSLT_REGION_C407_2,
    MMI_MSLT_REGION_VDOEDT_PWIN_TXT,
    MMI_MSLT_REGION_VDOREC_OSD_HINT,
    MMI_MSLT_REGION_C627_1,
    MMI_MSLT_REGION_C627_2,
    MMI_MSLT_REGION_SUBICONTEXT,
    MMI_MSLT_REGION_PHOEDT_TITLE,
    MMI_MSLT_REGION_PHOEDT_SPIN,
    MMI_MSLT_REGION_PHOEDT_SK,
    MMI_MSLT_REGION_CALIBRIATION_WELCOME_TEXT,
    MMI_MSLT_REGION_CALIBRIATION_TOP_LEFT_TEXT,
    MMI_MSLT_REGION_CALIBRIATION_BOTTOM_RIGHT_TEXT,
    MMI_MSLT_REGION_CALIBRIATION_CENTER_TEXT,
    MMI_MSLT_REGION_CALIBRIATION_TEST_WELCOME_TEXT,
    MMI_MSLT_REGION_BARCODE_HINT,
    MMI_MSLT_REGION_BARCODE_HINT_BRACKET,
    MMI_MSLT_REGION_LK_TIPS,
    MMI_MSLT_REGION_C126_1,
    MMI_MSLT_REGION_CASCADE,
    MMI_MSLT_REGION_ICONBAR,
    MMI_MSLT_REGION_HS32_SHCT_LABEL_LARGE,
    MMI_MSLT_REGION_HS32_SHCT_LABEL_SMALL,
    MMI_MSLT_REGION_HS32_SHCT_CONTENT,
};

extern S32 mmi_mslt_title_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_lsk_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_rsk_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_csk_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_get_list_info(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_get_list_info(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_get_list_info(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_get_list_info(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_get_list_info(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_tab_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_icon_bar_hint_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_idle_day_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_popup_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_popupconfirm_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_dummy_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c009_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c230_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c017_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c018_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c019_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c032_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c033_1_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c033_2_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c057_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c061_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c069_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c072_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c073_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c085_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c085_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_button_title_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c088_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c089_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c090_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c090_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c090_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c111_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c112_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c113_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c113_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c113_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c120_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c122_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c122_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c122_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c125_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c125_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_button_title_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c129_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_button_title_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c144_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c145_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c150_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c154_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c154_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c165_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c205_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_fmgr_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c211_2_asm_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_fmgr_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c222_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_button_title_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c261_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c261_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c264_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c265_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c265_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c265_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c267_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c267_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c280_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c311_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c312_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c354_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c354_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c384_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c384_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c402_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c402_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c403_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c412_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c412_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c420_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c420_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c420_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c425_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c425_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c426_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c426_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c427_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c427_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c427_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c428_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c429_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c429_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c429_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c430_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c433_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c435_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c620_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_ems_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_get_list_info(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_get_list_info(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_get_list_info(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_get_mainmenu_info(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_get_mainmenu_info(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_get_mainmenu_info(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_get_mainmenu_info(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_get_mainmenu_info(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_medply_lsk_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_medply_rsk_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_get_camcorder_info(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_get_camcorder_info(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_get_camcorder_info(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_get_camcorder_info(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_ime_hint_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_ime_cand_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_get_djitem_info(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_camera_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_camera_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_camera_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_get_mtv_info(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_sndrec_title_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_sndrec_state_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_sndrec_sk_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c409_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c409_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c407_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c407_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_get_vdoedt_info(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_get_vdorec_info(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c627_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c627_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_subicontext_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_get_photo_editor_title(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_get_photo_editor_spin(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_get_photo_editor_sk(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_get_calibriation_info(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_get_calibriation_info(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_get_calibriation_info(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_get_calibriation_info(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_get_calibriation_info(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_barcodereader_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_barcodereader_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_langln_lk_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_c126_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_get_list_info(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_iconbar_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_op11_hs32_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_op11_hs32_query_function(S32, mmi_mslt_font_struct*);
extern S32 mmi_mslt_op11_hs32_query_function(S32, mmi_mslt_font_struct*);

static const mmi_mslt_query_func_tbl_strc g_mmi_mslt_query_func_ptrs[] =
{
    {MMI_MSLT_REGION_TITLE, "TITLE", mmi_mslt_title_query_function},
    {MMI_MSLT_REGION_LSK, "LSK", mmi_mslt_lsk_query_function},
    {MMI_MSLT_REGION_RSK, "RSK", mmi_mslt_rsk_query_function},
    {MMI_MSLT_REGION_CSK, "CSK", mmi_mslt_csk_query_function},
    {MMI_MSLT_REGION_TEXT, "TEXT", mmi_mslt_get_list_info},
    {MMI_MSLT_REGION_HINT, "HINT", mmi_mslt_get_list_info},
    {MMI_MSLT_REGION_ICONTEXT, "ICONTEXT", mmi_mslt_get_list_info},
    {MMI_MSLT_REGION_TWOSTATE, "TWOSTATE", mmi_mslt_get_list_info},
    {MMI_MSLT_REGION_TWOLINE, "TWOLINE", mmi_mslt_get_list_info},
    {MMI_MSLT_REGION_TAB, "TAB", mmi_mslt_tab_query_function},
    {MMI_MSLT_REGION_ICON_BAR_HINT, "ICON_BAR_HINT", mmi_mslt_icon_bar_hint_query_function},
    {MMI_MSLT_REGION_IDLE_DAY, "IDLE_DAY", mmi_mslt_idle_day_query_function},
    {MMI_MSLT_REGION_POPUP, "POPUP", mmi_mslt_popup_query_function},
    {MMI_MSLT_REGION_POPUPCONFIRM, "POPUPCONFIRM", mmi_mslt_popupconfirm_query_function},
    {MMI_MSLT_REGION_UNLIM, "UNLIM", mmi_mslt_dummy_query_function},
    {MMI_MSLT_REGION_C009_1, "C009_1", mmi_mslt_c009_query_function},
    {MMI_MSLT_REGION_C230_1, "C230_1", mmi_mslt_c230_query_function},
    {MMI_MSLT_REGION_C017_1, "C017_1", mmi_mslt_c017_query_function},
    {MMI_MSLT_REGION_C018_1, "C018_1", mmi_mslt_c018_query_function},
    {MMI_MSLT_REGION_C019_1, "C019_1", mmi_mslt_c019_query_function},
    {MMI_MSLT_REGION_C032_1, "C032_1", mmi_mslt_c032_query_function},
    {MMI_MSLT_REGION_C033_1, "C033_1", mmi_mslt_c033_1_query_function},
    {MMI_MSLT_REGION_C033_2, "C033_2", mmi_mslt_c033_2_query_function},
    {MMI_MSLT_REGION_C057_1, "C057_1", mmi_mslt_c057_query_function},
    {MMI_MSLT_REGION_C061_1, "C061_1", mmi_mslt_c061_query_function},
    {MMI_MSLT_REGION_C069_1, "C069_1", mmi_mslt_c069_query_function},
    {MMI_MSLT_REGION_C072_1, "C072_1", mmi_mslt_c072_query_function},
    {MMI_MSLT_REGION_C073_1, "C073_1", mmi_mslt_c073_query_function},
    {MMI_MSLT_REGION_C085_1, "C085_1", mmi_mslt_c085_query_function},
    {MMI_MSLT_REGION_C085_2, "C085_2", mmi_mslt_c085_query_function},
    {MMI_MSLT_REGION_C086_1, "C086_1", mmi_mslt_button_title_query_function},
    {MMI_MSLT_REGION_C088_1, "C088_1", mmi_mslt_c088_query_function},
    {MMI_MSLT_REGION_C089_1, "C089_1", mmi_mslt_c089_query_function},
    {MMI_MSLT_REGION_C090_1, "C090_1", mmi_mslt_c090_query_function},
    {MMI_MSLT_REGION_C090_2, "C090_2", mmi_mslt_c090_query_function},
    {MMI_MSLT_REGION_C090_3, "C090_3", mmi_mslt_c090_query_function},
    {MMI_MSLT_REGION_C111_1, "C111_1", mmi_mslt_c111_query_function},
    {MMI_MSLT_REGION_C112_1, "C112_1", mmi_mslt_c112_query_function},
    {MMI_MSLT_REGION_C113_1, "C113_1", mmi_mslt_c113_query_function},
    {MMI_MSLT_REGION_C113_2, "C113_2", mmi_mslt_c113_query_function},
    {MMI_MSLT_REGION_C113_3, "C113_3", mmi_mslt_c113_query_function},
    {MMI_MSLT_REGION_C120_1, "C120_1", mmi_mslt_c120_query_function},
    {MMI_MSLT_REGION_C122_1, "C122_1", mmi_mslt_c122_query_function},
    {MMI_MSLT_REGION_C122_2, "C122_2", mmi_mslt_c122_query_function},
    {MMI_MSLT_REGION_C122_3, "C122_3", mmi_mslt_c122_query_function},
    {MMI_MSLT_REGION_C125_1, "C125_1", mmi_mslt_c125_query_function},
    {MMI_MSLT_REGION_C125_2, "C125_2", mmi_mslt_c125_query_function},
    {MMI_MSLT_REGION_C128_1, "C128_1", mmi_mslt_button_title_query_function},
    {MMI_MSLT_REGION_C129_1, "C129_1", mmi_mslt_c129_query_function},
    {MMI_MSLT_REGION_C130_1, "C130_1", mmi_mslt_button_title_query_function},
    {MMI_MSLT_REGION_C144_1, "C144_1", mmi_mslt_c144_query_function},
    {MMI_MSLT_REGION_C145_1, "C145_1", mmi_mslt_c145_query_function},
    {MMI_MSLT_REGION_C150_1, "C150_1", mmi_mslt_c150_query_function},
    {MMI_MSLT_REGION_C154_1, "C154_1", mmi_mslt_c154_query_function},
    {MMI_MSLT_REGION_C154_2, "C154_2", mmi_mslt_c154_query_function},
    {MMI_MSLT_REGION_C165_1, "C165_1", mmi_mslt_c165_query_function},
    {MMI_MSLT_REGION_C205_1, "C205_1", mmi_mslt_c205_query_function},
    {MMI_MSLT_REGION_C211_1, "C211_1", mmi_mslt_fmgr_query_function},
    {MMI_MSLT_REGION_C211_2, "C211_2", mmi_mslt_c211_2_asm_query_function},
    {MMI_MSLT_REGION_C213_1, "C213_1", mmi_mslt_fmgr_query_function},
    {MMI_MSLT_REGION_C222_1, "C222_1", mmi_mslt_c222_query_function},
    {MMI_MSLT_REGION_C229_1, "C229_1", mmi_mslt_button_title_query_function},
    {MMI_MSLT_REGION_C261_1, "C261_1", mmi_mslt_c261_query_function},
    {MMI_MSLT_REGION_C261_2, "C261_2", mmi_mslt_c261_query_function},
    {MMI_MSLT_REGION_C264_1, "C264_1", mmi_mslt_c264_query_function},
    {MMI_MSLT_REGION_C265_1, "C265_1", mmi_mslt_c265_query_function},
    {MMI_MSLT_REGION_C265_2, "C265_2", mmi_mslt_c265_query_function},
    {MMI_MSLT_REGION_C265_3, "C265_3", mmi_mslt_c265_query_function},
    {MMI_MSLT_REGION_C267_1, "C267_1", mmi_mslt_c267_query_function},
    {MMI_MSLT_REGION_C267_2, "C267_2", mmi_mslt_c267_query_function},
    {MMI_MSLT_REGION_C280_1, "C280_1", mmi_mslt_c280_query_function},
    {MMI_MSLT_REGION_C311_1, "C311_1", mmi_mslt_c311_query_function},
    {MMI_MSLT_REGION_C312_1, "C312_1", mmi_mslt_c312_query_function},
    {MMI_MSLT_REGION_C354_1, "C354_1", mmi_mslt_c354_query_function},
    {MMI_MSLT_REGION_C354_2, "C354_2", mmi_mslt_c354_query_function},
    {MMI_MSLT_REGION_C384_1, "C384_1", mmi_mslt_c384_query_function},
    {MMI_MSLT_REGION_C384_2, "C384_2", mmi_mslt_c384_query_function},
    {MMI_MSLT_REGION_C402_1, "C402_1", mmi_mslt_c402_query_function},
    {MMI_MSLT_REGION_C402_2, "C402_2", mmi_mslt_c402_query_function},
    {MMI_MSLT_REGION_C403_1, "C403_1", mmi_mslt_c403_query_function},
    {MMI_MSLT_REGION_C412_1, "C412_1", mmi_mslt_c412_query_function},
    {MMI_MSLT_REGION_C412_2, "C412_2", mmi_mslt_c412_query_function},
    {MMI_MSLT_REGION_C420_1, "C420_1", mmi_mslt_c420_query_function},
    {MMI_MSLT_REGION_C420_2, "C420_2", mmi_mslt_c420_query_function},
    {MMI_MSLT_REGION_C420_3, "C420_3", mmi_mslt_c420_query_function},
    {MMI_MSLT_REGION_C425_1, "C425_1", mmi_mslt_c425_query_function},
    {MMI_MSLT_REGION_C425_2, "C425_2", mmi_mslt_c425_query_function},
    {MMI_MSLT_REGION_C426_1, "C426_1", mmi_mslt_c426_query_function},
    {MMI_MSLT_REGION_C426_2, "C426_2", mmi_mslt_c426_query_function},
    {MMI_MSLT_REGION_C427_1, "C427_1", mmi_mslt_c427_query_function},
    {MMI_MSLT_REGION_C427_2, "C427_2", mmi_mslt_c427_query_function},
    {MMI_MSLT_REGION_C427_3, "C427_3", mmi_mslt_c427_query_function},
    {MMI_MSLT_REGION_C428_1, "C428_1", mmi_mslt_c428_query_function},
    {MMI_MSLT_REGION_C429_1, "C429_1", mmi_mslt_c429_query_function},
    {MMI_MSLT_REGION_C429_2, "C429_2", mmi_mslt_c429_query_function},
    {MMI_MSLT_REGION_C429_3, "C429_3", mmi_mslt_c429_query_function},
    {MMI_MSLT_REGION_C430_1, "C430_1", mmi_mslt_c430_query_function},
    {MMI_MSLT_REGION_C433_1, "C433_1", mmi_mslt_c433_query_function},
    {MMI_MSLT_REGION_C435_1, "C435_1", mmi_mslt_c435_query_function},
    {MMI_MSLT_REGION_C620_1, "C620_1", mmi_mslt_c620_query_function},
    {MMI_MSLT_REGION_CEMS_1, "CEMS_1", mmi_mslt_ems_query_function},
    {MMI_MSLT_REGION_STEXT, "STEXT", mmi_mslt_get_list_info},
    {MMI_MSLT_REGION_SICONTEXT, "SICONTEXT", mmi_mslt_get_list_info},
    {MMI_MSLT_REGION_STWOSTATE, "STWOSTATE", mmi_mslt_get_list_info},
    {MMI_MSLT_REGION_MATRIX, "MATRIX", mmi_mslt_get_mainmenu_info},
    {MMI_MSLT_REGION_LISTMAIN, "LISTMAIN", mmi_mslt_get_mainmenu_info},
    {MMI_MSLT_REGION_BDTITLE, "BDTITLE", mmi_mslt_get_mainmenu_info},
    {MMI_MSLT_REGION_BDITEM, "BDITEM", mmi_mslt_get_mainmenu_info},
    {MMI_MSLT_REGION_PAGEITEM, "PAGEITEM", mmi_mslt_get_mainmenu_info},
    {MMI_MSLT_REGION_MEDPLY_LSK, "MEDPLY_LSK", mmi_mslt_medply_lsk_query_function},
    {MMI_MSLT_REGION_MEDPLY_RSK, "MEDPLY_RSK", mmi_mslt_medply_rsk_query_function},
    {MMI_MSLT_REGION_CAMCO_ITEM, "CAMCO_ITEM", mmi_mslt_get_camcorder_info},
    {MMI_MSLT_REGION_CAMCO_TITLE, "CAMCO_TITLE", mmi_mslt_get_camcorder_info},
    {MMI_MSLT_REGION_CAMCO_OPTION, "CAMCO_OPTION", mmi_mslt_get_camcorder_info},
    {MMI_MSLT_REGION_CAMCO_HINT, "CAMCO_HINT", mmi_mslt_get_camcorder_info},
    {MMI_MSLT_REGION_IME_HINT, "IME_HINT", mmi_mslt_ime_hint_query_function},
    {MMI_MSLT_REGION_IME_CAND, "IME_CAND", mmi_mslt_ime_cand_query_function},
    {MMI_MSLT_REGION_DJITEM, "DJITEM", mmi_mslt_get_djitem_info},
    {MMI_MSLT_REGION_CAMERA_HINT, "CAMERA_HINT", mmi_mslt_camera_query_function},
    {MMI_MSLT_REGION_CAMERA_TITLE, "CAMERA_TITLE", mmi_mslt_camera_query_function},
    {MMI_MSLT_REGION_CAMERA_SUB_HINT, "CAMERA_SUB_HINT", mmi_mslt_camera_query_function},
    {MMI_MSLT_REGION_MTV_HINT, "MTV_HINT", mmi_mslt_get_mtv_info},
    {MMI_MSLT_REGION_SNDREC_TITLE, "SNDREC_TITLE", mmi_mslt_sndrec_title_query_function},
    {MMI_MSLT_REGION_SNDREC_STATE, "SNDREC_STATE", mmi_mslt_sndrec_state_query_function},
    {MMI_MSLT_REGION_SNDREC_SK, "SNDREC_SK", mmi_mslt_sndrec_sk_query_function},
    {MMI_MSLT_REGION_C409_1, "C409_1", mmi_mslt_c409_query_function},
    {MMI_MSLT_REGION_C409_2, "C409_2", mmi_mslt_c409_query_function},
    {MMI_MSLT_REGION_C407_1, "C407_1", mmi_mslt_c407_query_function},
    {MMI_MSLT_REGION_C407_2, "C407_2", mmi_mslt_c407_query_function},
    {MMI_MSLT_REGION_VDOEDT_PWIN_TXT, "VDOEDT_PWIN_TXT", mmi_mslt_get_vdoedt_info},
    {MMI_MSLT_REGION_VDOREC_OSD_HINT, "VDOREC_OSD_HINT", mmi_mslt_get_vdorec_info},
    {MMI_MSLT_REGION_C627_1, "C627_1", mmi_mslt_c627_query_function},
    {MMI_MSLT_REGION_C627_2, "C627_2", mmi_mslt_c627_query_function},
    {MMI_MSLT_REGION_SUBICONTEXT, "SUBICONTEXT", mmi_mslt_subicontext_query_function},
    {MMI_MSLT_REGION_PHOEDT_TITLE, "PHOEDT_TITLE", mmi_mslt_get_photo_editor_title},
    {MMI_MSLT_REGION_PHOEDT_SPIN, "PHOEDT_SPIN", mmi_mslt_get_photo_editor_spin},
    {MMI_MSLT_REGION_PHOEDT_SK, "PHOEDT_SK", mmi_mslt_get_photo_editor_sk},
    {MMI_MSLT_REGION_CALIBRIATION_WELCOME_TEXT, "CALIBRIATION_WELCOME_TEXT", mmi_mslt_get_calibriation_info},
    {MMI_MSLT_REGION_CALIBRIATION_TOP_LEFT_TEXT, "CALIBRIATION_TOP_LEFT_TEXT", mmi_mslt_get_calibriation_info},
    {MMI_MSLT_REGION_CALIBRIATION_BOTTOM_RIGHT_TEXT, "CALIBRIATION_BOTTOM_RIGHT_TEXT", mmi_mslt_get_calibriation_info},
    {MMI_MSLT_REGION_CALIBRIATION_CENTER_TEXT, "CALIBRIATION_CENTER_TEXT", mmi_mslt_get_calibriation_info},
    {MMI_MSLT_REGION_CALIBRIATION_TEST_WELCOME_TEXT, "CALIBRIATION_TEST_WELCOME_TEXT", mmi_mslt_get_calibriation_info},
    {MMI_MSLT_REGION_BARCODE_HINT, "BARCODE_HINT", mmi_mslt_barcodereader_query_function},
    {MMI_MSLT_REGION_BARCODE_HINT_BRACKET, "BARCODE_HINT_BRACKET", mmi_mslt_barcodereader_query_function},
    {MMI_MSLT_REGION_LK_TIPS, "LK_TIPS", mmi_langln_lk_query_function},
    {MMI_MSLT_REGION_C126_1, "C126_1", mmi_mslt_c126_query_function},
    {MMI_MSLT_REGION_CASCADE, "CASCADE", mmi_mslt_get_list_info},
    {MMI_MSLT_REGION_ICONBAR, "ICONBAR", mmi_mslt_iconbar_query_function},
    {MMI_MSLT_REGION_HS32_SHCT_LABEL_LARGE, "HS32_SHCT_LABEL_LARGE", mmi_mslt_op11_hs32_query_function},
    {MMI_MSLT_REGION_HS32_SHCT_LABEL_SMALL, "HS32_SHCT_LABEL_SMALL", mmi_mslt_op11_hs32_query_function},
    {MMI_MSLT_REGION_HS32_SHCT_CONTENT, "HS32_SHCT_CONTENT", mmi_mslt_op11_hs32_query_function},
};

#endif /* __MTK_TARGET__ */

#endif /* __MSLT_TABLE_H__ */
