#include "CustomCfg.h"
#ifdef FIRST_PASS
#include "BuildCfg.h"
#endif
#include "MMI_features.h"
#include "MMIDataType.h"
#include "lcd_sw_inc.h"
#include "MMI_features_camcorder.h"
#include "custresdef.h"

#if defined(__VAPP_CAMCO__)

<?xml version="1.0" encoding="UTF-8"?>

<APP id="VCUI_CAMCO" name="STR_ID_VCUI_CAMCORDER" type="venus">   
    <MEMORY heap= "VAPP_CAMCO_UI_MEM" extra_base="base(SRV_MDI_VDOREC)" fg="CAMCO_PREVIEW_LAYER_SIZE + CAMCO_OSD_OVERLAY_PALETTE_SIZE + max(total(SRV_MDI_CAMERA_STANDARD), fg(SRV_MDI_VDOREC))" inc="vapp_camco_gprot.h,vfx_sys_config.h"/> 
</APP>

<APP id="VCUI_STANDARD_CAMERA" name="STR_ID_VCUI_CAMERA" type="venus">   
    <MEMORY heap= "VAPP_CAMCO_UI_MEM" fg="CAMCO_PREVIEW_LAYER_SIZE + CAMCO_OSD_OVERLAY_PALETTE_SIZE + total(SRV_MDI_CAMERA_ONLY_CAP_LCD)" inc="vapp_camco_gprot.h,vfx_sys_config.h"/> 
</APP>

<APP id="VCUI_STANDARD_RECORDER" name="STR_ID_VCUI_RECORDER" type="venus">   
    <MEMORY heap= "VAPP_CAMCO_UI_MEM" extra_base="base(SRV_MDI_VDOREC_CIF)" fg="CAMCO_PREVIEW_LAYER_SIZE + CAMCO_OSD_OVERLAY_PALETTE_SIZE  + fg(SRV_MDI_VDOREC_CIF)" inc="vapp_camco_gprot.h,vfx_sys_config.h"/> 
</APP>

<APP id="VCUI_SLIM_CAMERA" name="STR_ID_VCUI_SLIM_CAMERA" type="venus">   
    <MEMORY heap= "VAPP_CAMCO_UI_MEM" fg="CAMCO_PREVIEW_LAYER_SIZE + CAMCO_OSD_OVERLAY_PALETTE_SIZE  + total(SRV_MDI_CAMERA_CAP_VGA_BELOW)" inc="vapp_camco_gprot.h,vfx_sys_config.h"/> 
</APP>

<APP id="VAPP_CAMCO"  package_name="native.mtk.camcorder" name="STR_ID_VAPP_CAMCO_APP_NAME" img = "MAIN_MENU_CAMCO_ICON" launch = "vapp_camco_launch" package_proc = "vapp_camco_package_proc" type="venus">


    <INCLUDE file = "PopulateRes.h"/>
    <INCLUDE file = "ImageViewerResDef.h"/>
    <INCLUDE file = "CustResDef.h"/>
#ifdef __VENUS_3D_UI_ENGINE__
    <MEMORY heap= "VAPP_CAMCO_UI_MEM" extra_base="max(base(SRV_MDI_VDOREC), base(SRV_MDI_VDOPLY_PREVIEW))" fg="MMI_CAMCO_APP_MEM_SIZE + max(max(max(total(SRV_MDI_CAMERA_STANDARD), total(SRV_MDI_CAMERA_CAP_HDR)), fg(SRV_MDI_VDOREC)), fg(SRV_MDI_VDOPLY_PREVIEW))" inc="vapp_camco_gprot.h,vfx_sys_config.h" vrt_mem_factor="2.8f"/>
#else    
    <MEMORY heap= "VAPP_CAMCO_UI_MEM" extra_base="max(base(SRV_MDI_VDOREC), base(SRV_MDI_VDOPLY_PREVIEW))" fg="MMI_CAMCO_APP_MEM_SIZE + max(max(max(total(SRV_MDI_CAMERA_STANDARD), total(SRV_MDI_CAMERA_CAP_HDR)), fg(SRV_MDI_VDOREC)), fg(SRV_MDI_VDOPLY_PREVIEW))" inc="vapp_camco_gprot.h,vfx_sys_config.h" />
#endif

    <STRING id="STR_ID_VAPP_CAMCO_EV"/>
    <STRING id="STR_ID_VAPP_CAMCO_EVP4"/>
    <STRING id="STR_ID_VAPP_CAMCO_EVP3"/>
    <STRING id="STR_ID_VAPP_CAMCO_EVP2"/>
    <STRING id="STR_ID_VAPP_CAMCO_EVP1"/>
    <STRING id="STR_ID_VAPP_CAMCO_EVZ0"/>   
    <STRING id="STR_ID_VAPP_CAMCO_EVN1"/>
    <STRING id="STR_ID_VAPP_CAMCO_EVN2"/>
    <STRING id="STR_ID_VAPP_CAMCO_EVN3"/>
    <STRING id="STR_ID_VAPP_CAMCO_EVN4"/>
    
    <STRING id="STR_ID_VAPP_CAMCO_CAPMODE"/>
    <STRING id="STR_ID_VAPP_CAMCO_CAPMODE_NORMAL"/>
    <STRING id="STR_ID_VAPP_CAMCO_CAPMODE_BEST_SHOT"/>
    <STRING id="STR_ID_VAPP_CAMCO_CAPMODE_CONT_SHOT"/>
    <STRING id="STR_ID_VAPP_CAMCO_CAPMODE_BURST_SHOT_SEL"/>
    <STRING id="STR_ID_VAPP_CAMCO_CAPMODE_EV_BRACKET_SEL"/>
    <STRING id="STR_ID_VAPP_CAMCO_CAPMODE_HDR_SHOT"/>    
    <STRING id="STR_ID_VAPP_CAMCO_CAPMODE_ASD_SHOT"/>        
    <STRING id="STR_ID_VAPP_CAMCO_CAPMODE_ZSD_SHOT"/>            
    <STRING id="STR_ID_VAPP_CAMCO_CAPMODE_ADD_FRAME"/>
    <STRING id="STR_ID_VAPP_CAMCO_CAPMODE_SMILE_SHOT"/>
    <STRING id="STR_ID_VAPP_CAMCO_CAPMODE_LCE_SHOT"/>    
    
    <STRING id="STR_ID_VAPP_CAMCO_SCENEMODE"/>
    <STRING id="STR_ID_VAPP_CAMCO_SCENEMODE_AUTO"/>
    <STRING id="STR_ID_VAPP_CAMCO_SCENEMODE_PORTRAIT"/>
    <STRING id="STR_ID_VAPP_CAMCO_SCENEMODE_LANDSCAPE"/>
    <STRING id="STR_ID_VAPP_CAMCO_SCENEMODE_NIGHT"/>
    <STRING id="STR_ID_VAPP_CAMCO_SCENEMODE_SPORT"/>
    <STRING id="STR_ID_VAPP_CAMCO_SCENEMODE_DOCUMENT"/>
    <STRING id="STR_ID_VAPP_CAMCO_SCENEMODE_ANTI_SHAKE"/>
    
    <STRING id="STR_ID_VAPP_CAMCO_CAPSIZE"/>
    <STRING id="STR_ID_VAPP_CAMCO_CAPSIZE_WALLPAPER"/>
#if defined(__MMI_MAINLCD_240X400__)
    <STRING id="STR_ID_VAPP_CAMCO_CAPSIZE_HLCD">"400x240"</STRING>
#elif defined(__MMI_MAINLCD_320X480__)
    <STRING id="STR_ID_VAPP_CAMCO_CAPSIZE_HLCD">"480x320"</STRING>
#elif defined(__MMI_MAINLCD_480X800__)
    <STRING id="STR_ID_VAPP_CAMCO_CAPSIZE_HLCD">"800x480"</STRING>    
#else
    <STRING id="STR_ID_VAPP_CAMCO_CAPSIZE_HLCD">"320x240"</STRING>
#endif
    <STRING id="STR_ID_VAPP_CAMCO_CAPSIZE_VGA"/>
    <STRING id="STR_ID_VAPP_CAMCO_CAPSIZE_1MP"/>
    <STRING id="STR_ID_VAPP_CAMCO_CAPSIZE_1MP_EX"/>    
    <STRING id="STR_ID_VAPP_CAMCO_CAPSIZE_2MP"/>
    <STRING id="STR_ID_VAPP_CAMCO_CAPSIZE_2MP_EX"/>    
    <STRING id="STR_ID_VAPP_CAMCO_CAPSIZE_3MP"/>
    <STRING id="STR_ID_VAPP_CAMCO_CAPSIZE_3MP_EX"/>    
    <STRING id="STR_ID_VAPP_CAMCO_CAPSIZE_4MP"/>
    <STRING id="STR_ID_VAPP_CAMCO_CAPSIZE_4MP_EX"/>    
    <STRING id="STR_ID_VAPP_CAMCO_CAPSIZE_5MP"/>
    <STRING id="STR_ID_VAPP_CAMCO_CAPSIZE_5MP_EX"/>    
    
    <STRING id="STR_ID_VAPP_CAMCO_FLASH"/>
    <STRING id="STR_ID_VAPP_CAMCO_FLASH_AUTO"/>
    <STRING id="STR_ID_VAPP_CAMCO_FLASH_FORCE_ON"/>
    <STRING id="STR_ID_VAPP_CAMCO_FLASH_RED_EYE"/>
    <STRING id="STR_ID_VAPP_CAMCO_HIGHLIGHT"/>
    
    <STRING id="STR_ID_VAPP_CAMCO_AFRANGE"/>
    <STRING id="STR_ID_VAPP_CAMCO_AFRANGE_AUTO"/>
    <STRING id="STR_ID_VAPP_CAMCO_AFRANGE_MACRO"/>
    <STRING id="STR_ID_VAPP_CAMCO_AFRANGE_INFINITE"/>
    
    <STRING id="STR_ID_VAPP_CAMCO_SELFTIMER"/>
    <STRING id="STR_ID_VAPP_CAMCO_SELFTIMER_5S"/>
    <STRING id="STR_ID_VAPP_CAMCO_SELFTIMER_10S"/>
    <STRING id="STR_ID_VAPP_CAMCO_SELFTIMER_15S"/>
        
    <STRING id="STR_ID_VAPP_CAMCO_AUXILIARY"/>    
    
    <STRING id="STR_ID_VAPP_CAMCO_ISO"/>
    <STRING id="STR_ID_VAPP_CAMCO_ISO_AUTO"/>
    <STRING id="STR_ID_VAPP_CAMCO_ISO_100"/>
    <STRING id="STR_ID_VAPP_CAMCO_ISO_200"/>
    <STRING id="STR_ID_VAPP_CAMCO_ISO_400"/>
    <STRING id="STR_ID_VAPP_CAMCO_ISO_800"/>
    <STRING id="STR_ID_VAPP_CAMCO_ISO_1600"/>
    
    <STRING id="STR_ID_VAPP_CAMCO_WB"/>
    <STRING id="STR_ID_VAPP_CAMCO_WB_AUTO"/>
    <STRING id="STR_ID_VAPP_CAMCO_WB_DAYLIGHT"/>
    <STRING id="STR_ID_VAPP_CAMCO_WB_TUNGSTEN"/>
    <STRING id="STR_ID_VAPP_CAMCO_WB_FLUORESCENT"/>
    <STRING id="STR_ID_VAPP_CAMCO_WB_CLOUDY"/>
    <STRING id="STR_ID_VAPP_CAMCO_WB_INCANDESCENT"/>
    
    <STRING id="STR_ID_VAPP_CAMCO_EFFECT"/>
    <STRING id="STR_ID_VAPP_CAMCO_EFFECT_GRAYSCALE"/>
    <STRING id="STR_ID_VAPP_CAMCO_EFFECT_SEPIA"/>
    <STRING id="STR_ID_VAPP_CAMCO_EFFECT_SEPIA_GREEN"/>
    <STRING id="STR_ID_VAPP_CAMCO_EFFECT_SEPIA_BLUE"/>
    <STRING id="STR_ID_VAPP_CAMCO_EFFECT_COLOR_INVERT"/>
    <STRING id="STR_ID_VAPP_CAMCO_EFFECT_GRAY_INVERT"/>
    <STRING id="STR_ID_VAPP_CAMCO_EFFECT_BLACKBOARD"/>
    <STRING id="STR_ID_VAPP_CAMCO_EFFECT_WHITEBOARD"/>
    <STRING id="STR_ID_VAPP_CAMCO_EFFECT_COPPER_CARVING"/>
    <STRING id="STR_ID_VAPP_CAMCO_EFFECT_BLUE_CARVING"/>
    <STRING id="STR_ID_VAPP_CAMCO_EFFECT_EMBOSSMENT"/>
    <STRING id="STR_ID_VAPP_CAMCO_EFFECT_CONTRAST"/>
    <STRING id="STR_ID_VAPP_CAMCO_EFFECT_JEAN"/>
    <STRING id="STR_ID_VAPP_CAMCO_EFFECT_SKETCH"/>
    <STRING id="STR_ID_VAPP_CAMCO_EFFECT_OIL"/>
    <STRING id="STR_ID_VAPP_CAMCO_EFFECT_LOMO"/>
    <STRING id="STR_ID_VAPP_CAMCO_EFFECT_COLOR_RED"/>
    <STRING id="STR_ID_VAPP_CAMCO_EFFECT_COLOR_YELLOW"/>
    <STRING id="STR_ID_VAPP_CAMCO_EFFECT_COLOR_GREEN"/>
    <STRING id="STR_ID_VAPP_CAMCO_EFFECT_COLOR_BLUE"/>
    
    <STRING id="STR_ID_VAPP_CAMCO_CAPQTY"/>
    <STRING id="STR_ID_VAPP_CAMCO_CAPQTY_FINE"/>
    <STRING id="STR_ID_VAPP_CAMCO_CAPQTY_GOOD"/>
    <STRING id="STR_ID_VAPP_CAMCO_CAPQTY_NORMAL"/>
    <STRING id="STR_ID_VAPP_CAMCO_CAPQTY_LOW"/>
    
    <STRING id="STR_ID_VAPP_CAMCO_AFZONE"/>
    <STRING id="STR_ID_VAPP_CAMCO_AFZONE_SINGLE"/>
    <STRING id="STR_ID_VAPP_CAMCO_AFZONE_MULTI"/>
    <STRING id="STR_ID_VAPP_CAMCO_AFZONE_CONTINUE"/>
    
    <STRING id="STR_ID_VAPP_CAMCO_AEMETER"/>
    <STRING id="STR_ID_VAPP_CAMCO_AEMETER_AUTO"/>
    <STRING id="STR_ID_VAPP_CAMCO_AEMETER_SPOT"/>
    <STRING id="STR_ID_VAPP_CAMCO_AEMETER_CENTER_WEIGHT"/>
    <STRING id="STR_ID_VAPP_CAMCO_AEMETER_AVERAGE"/>
    
    <STRING id="STR_ID_VAPP_CAMCO_SHARPNESS"/>
    
    <STRING id="STR_ID_VAPP_CAMCO_CONTRAST"/>
    
    <STRING id="STR_ID_VAPP_CAMCO_SATURATION"/>
    
    <STRING id="STR_ID_VAPP_CAMCO_ENHANCE"/>
    <STRING id="STR_ID_VAPP_CAMCO_REDUCE"/>

    <STRING id="STR_ID_VAPP_CAMCO_SHUTTERSOUND"/>
    <STRING id="STR_ID_VAPP_CAMCO_SHUTTERSOUND_SOUND_1"/>
    <STRING id="STR_ID_VAPP_CAMCO_SHUTTERSOUND_SOUND_2"/>
    <STRING id="STR_ID_VAPP_CAMCO_SHUTTERSOUND_SOUND_3"/>
    
    <STRING id="STR_ID_VAPP_CAMCO_BANDING"/>
    <STRING id="STR_ID_VAPP_CAMCO_BANDING_50HZ"/>
    <STRING id="STR_ID_VAPP_CAMCO_BANDING_60HZ"/>
    
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE"/>
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_SQCIF"/>
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_QQVGA"/>   
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_QCIF"/>
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_QVGA"/>
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_CIF"/>  
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_WQVGA"/>
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_CIF2"/>
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_HVGA"/>
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_NHD"/>     
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_VGA"/>
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_4CIF"/>    
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_D1"/>
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_D12"/>
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_WVGA"/>                                      
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_SVGA"/>
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_WVGA2"/>
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_FWVGA"/>    
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_XGA"/>
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_720P"/>
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_4VGA"/>
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_SXGA"/>
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_16CIF"/>
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_4SVGA"/>
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_FHD"/>

    <STRING id="STR_ID_VAPP_CAMCO_TIME_LAPSE"/>

    <STRING id="STR_ID_VAPP_CAMCO_TIME_LAPSE_PERIOD"/>

    <STRING id="STR_ID_VAPP_CAMCO_LIMIT"/>
    <STRING id="STR_ID_VAPP_CAMCO_LIMIT_NO_LIMIT"/>
    <STRING id="STR_ID_VAPP_CAMCO_LIMIT_TIME_15S"/>
    <STRING id="STR_ID_VAPP_CAMCO_LIMIT_TIME_30S"/>
    <STRING id="STR_ID_VAPP_CAMCO_LIMIT_TIME_60S"/>
    <STRING id="STR_ID_VAPP_CAMCO_LIMIT_TIME_300S"/>
    <STRING id="STR_ID_VAPP_CAMCO_LIMIT_TIME_600S"/>
    <STRING id="STR_ID_VAPP_CAMCO_LIMIT_SIZE_95K"/>
    <STRING id="STR_ID_VAPP_CAMCO_LIMIT_SIZE_195K"/>
    <STRING id="STR_ID_VAPP_CAMCO_LIMIT_SIZE_295K"/>
    
    <STRING id="STR_ID_VAPP_CAMCO_VISQTY"/>
    <STRING id="STR_ID_VAPP_CAMCO_VISQTY_FINE"/>
    <STRING id="STR_ID_VAPP_CAMCO_VISQTY_GOOD"/>
    <STRING id="STR_ID_VAPP_CAMCO_VISQTY_NORMAL"/>
    <STRING id="STR_ID_VAPP_CAMCO_VISQTY_LOW"/>    
    
    <STRING id="STR_ID_VAPP_CAMCO_AFMODE"/>
    <STRING id="STR_ID_VAPP_CAMCO_AFMODE_SINGLE"/>
    <STRING id="STR_ID_VAPP_CAMCO_AFMODE_CONT"/>
    
    <STRING id="STR_ID_VAPP_CAMCO_RECAUD"/>
    <STRING id="STR_ID_VAPP_CAMCO_RECAUD_ON"/>
    
    <STRING id="STR_ID_VAPP_CAMCO_VISCODEC"/>
    <STRING id="STR_ID_VAPP_CAMCO_VISCODEC_MP4"/>
    <STRING id="STR_ID_VAPP_CAMCO_VISCODEC_3GP"/>
    <STRING id="STR_ID_VAPP_CAMCO_VISCODEC_MJPG"/>
    <STRING id="STR_ID_VAPP_CAMCO_VISCODEC_H264"/>    

    <STRING id="STR_ID_VAPP_CAMCO_DEFAULT"/>
    <STRING id="STR_ID_VAPP_CAMCO_DEFAULT_COMFIRM"/>
    
    <STRING id="STR_ID_VAPP_CAMCO_DELETE_QUERY"/>

    <STRING id="STR_ID_VAPP_CAMCO_CREATE_FOLDER_FAILED"/>
    <STRING id="STR_ID_VAPP_CAMCO_PREVIEW_FAILED"/>
    <STRING id="STR_ID_VAPP_CAMCO_DISK_FULL"/>
    <STRING id="STR_ID_VAPP_CAMCO_CAPTURE_FAILED"/>
    <STRING id="STR_ID_VAPP_CAMCO_PAUSE_FAILED"/>
    <STRING id="STR_ID_VAPP_CAMCO_CAMERA_NOT_READY"/>
    <STRING id="STR_ID_VAPP_CAMCO_CONTINUE"/>
    <STRING id="STR_ID_VAPP_CAMCO_COUNTDOWN"/>
    <STRING id="STR_ID_VAPP_CAMCO_STITCHING"/>
    <STRING id="STR_ID_VAPP_CAMCO_CAPTURING"/>    
    <STRING id="STR_ID_VAPP_CAMCO_BURST_CAPTURING"/>        

    <STRING id="STR_ID_VAPP_CAMCO_NOTIFY_ADDFRAME_IS_ACTIVE"/>

    <STRING id="STR_ID_VAPP_CAMCO_NOTIFY_WRITE_PROTECT"/>
    <STRING id="STR_ID_VAPP_CAMCO_NOTIFY_HW_NOT_READY"/>
    <STRING id="STR_ID_VAPP_CAMCO_NOTIFY_STORAGE_NOT_READY"/>
    <STRING id="STR_ID_VAPP_CAMCO_NOTIFY_ERROR"/>
    <STRING id="STR_ID_VAPP_CAMCO_NOTIFY_REACH_TIME_LIMIT"/>
    <STRING id="STR_ID_VAPP_CAMCO_NOTIFY_REACH_SIZE_LIMIT"/>
    <STRING id="STR_ID_VAPP_CAMCO_NOTIFY_STORAGE_TOO_SLOW"/>
    <STRING id="STR_ID_VAPP_CAMCO_NOTIFY_CHANGE_LOW_RECSIZE"/>
    <STRING id="STR_ID_VAPP_CAMCO_NOTIFY_CHANGE_NORMAL_CAPTURE"/>
    <STRING id="STR_ID_VAPP_CAMCO_MEM_CARD_REMOVE"/>
    <STRING id="STR_ID_VAPP_CAMCO_MEM_CARD_INSERT"/>
    <STRING id="STR_ID_VAPP_CAMCO_FACE_DETECTION"/>
    <STRING id="STR_ID_VAPP_CAMCO_NOTIFY_BT_IS_WORKING"/>
    <STRING id="STR_ID_VAPP_CAMCO_NOTIFY_PICT_IS_WORKING"/>


    #define CAMCO_OSD_PATH    RES_IMG_ROOT"\\\\Camcorder\\\\"
    
    <THEME>
        <IMAGE id="MAIN_MENU_CAMCO_ICON" desc="Main menu camcorder icon">RES_IMG_ROOT"\\\\"__MMI_MAINMENU_ICON_DEFAULT_PATH__"\\\\Camera.png"</IMAGE>
    </THEME>
    <IMAGE id="MAIN_MENU_CAMCO_ENTER_ICON">RES_IMG_ROOT"\\\\Mainmenu_Icon\\\\Camera.png"</IMAGE>     
    <IMAGE id="IMG_ID_VAPP_CAMCO_LEFT_BAR_ICON">CAMCO_OSD_PATH"bg_bar_l.9slice.png"</IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CAMCO_RIGHT_BAR_ICON">CAMCO_OSD_PATH"bg_bar_r.9slice.png"</IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CAMCO_V_LEFT_BAR_ICON">CAMCO_OSD_PATH"bg_bar_v_l.9slice.png"</IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CAMCO_V_RIGHT_BAR_ICON">CAMCO_OSD_PATH"bg_bar_v_r.9slice.png"</IMAGE>     
    <IMAGE id="IMG_ID_VAPP_CAMCO_SETTING_NAME_ICON">CAMCO_OSD_PATH"bg_item_name.9slice.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_RESET_ICON">CAMCO_OSD_PATH"btn_menu.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_RECORD_PAUSE_ICON">CAMCO_OSD_PATH"btn_pause.png"</IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CAMCO_RECORD_RESUME_ICON">CAMCO_OSD_PATH"btn_play.png"</IMAGE>     
    <IMAGE id="IMG_ID_VAPP_CAMCO_RECORD_REC_ICON">CAMCO_OSD_PATH"btn_rec.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_RECORD_REC_IND_ICON">CAMCO_OSD_PATH"icon_rec.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_RECORD_PAUSE_IND_ICON">CAMCO_OSD_PATH"icon_pause.png"</IMAGE>      
    <IMAGE id="IMG_ID_VAPP_CAMCO_SAVE_ICON">CAMCO_OSD_PATH"btn_save.png"</IMAGE>      
    <IMAGE id="IMG_ID_VAPP_CAMCO_CAPTURE_ICON">CAMCO_OSD_PATH"btn_shoot.png"</IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CAMCO_RECORD_STOP_ICON">CAMCO_OSD_PATH"btn_stop.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_SETTING_SPLITER_ICON">CAMCO_OSD_PATH"splitter.png"</IMAGE>    
    <IMAGE id="IMG_ID_VAPP_CAMCO_AD_SETTING_BG_ICON">CAMCO_OSD_PATH"bg_adv_setting.png"</IMAGE>    
#ifdef __MMI_CAMCO_FEATURE_ADD_FRAME_COLOR_IDX_1__
    <IMAGE id="IMG_ID_VAPP_CAMCO_ADD_FRAME_COLOR_IDX_1">CAMCO_OSD_PATH"Frame\\\\CAM_frame_01.gif"</IMAGE>
#endif
#ifdef __MMI_CAMCO_FEATURE_ADD_FRAME_COLOR_IDX_2__
    <IMAGE id="IMG_ID_VAPP_CAMCO_ADD_FRAME_COLOR_IDX_2">CAMCO_OSD_PATH"Frame\\\\CAM_frame_02.gif"</IMAGE>
#endif
#ifdef __MMI_CAMCO_FEATURE_ADD_FRAME_COLOR_IDX_3__
    <IMAGE id="IMG_ID_VAPP_CAMCO_ADD_FRAME_COLOR_IDX_3">CAMCO_OSD_PATH"Frame\\\\CAM_frame_03.gif"</IMAGE>
#endif
#ifdef __MMI_CAMCO_FEATURE_ADD_FRAME_COLOR_IDX_4__
    <IMAGE id="IMG_ID_VAPP_CAMCO_ADD_FRAME_COLOR_IDX_4">CAMCO_OSD_PATH"Frame\\\\CAM_frame_04.gif"</IMAGE>
#endif
#ifdef __MMI_CAMCO_FEATURE_ADD_FRAME_COLOR_IDX_5__
    <IMAGE id="IMG_ID_VAPP_CAMCO_ADD_FRAME_COLOR_IDX_5">CAMCO_OSD_PATH"Frame\\\\CAM_frame_05.gif"</IMAGE>
#endif
#ifdef __MMI_CAMCO_FEATURE_ADD_FRAME_COLOR_IDX_6__
    <IMAGE id="IMG_ID_VAPP_CAMCO_ADD_FRAME_COLOR_IDX_6">CAMCO_OSD_PATH"Frame\\\\CAM_frame_06.gif"</IMAGE>
#endif
#ifdef __MMI_CAMCO_FEATURE_ADD_FRAME_COLOR_IDX_7__
    <IMAGE id="IMG_ID_VAPP_CAMCO_ADD_FRAME_COLOR_IDX_7">CAMCO_OSD_PATH"Frame\\\\CAM_frame_07.gif"</IMAGE>
#endif
#ifdef __MMI_CAMCO_FEATURE_ADD_FRAME_COLOR_IDX_8__
    <IMAGE id="IMG_ID_VAPP_CAMCO_ADD_FRAME_COLOR_IDX_8">CAMCO_OSD_PATH"Frame\\\\CAM_frame_08.gif"</IMAGE>
#endif
#ifdef __MMI_CAMCO_FEATURE_ADD_FRAME_COLOR_IDX_9__
    <IMAGE id="IMG_ID_VAPP_CAMCO_ADD_FRAME_COLOR_IDX_9">CAMCO_OSD_PATH"Frame\\\\CAM_frame_09.gif"</IMAGE>
#endif
#ifdef __MMI_CAMCO_FEATURE_ADD_FRAME_COLOR_IDX_10__
    <IMAGE id="IMG_ID_VAPP_CAMCO_ADD_FRAME_COLOR_IDX_10">CAMCO_OSD_PATH"Frame\\\\CAM_frame_10.gif"</IMAGE>
#endif

    <IMAGE id="IMG_ID_VAPP_CAMCO_RECT_AF_NORMAL1_ICON">CAMCO_OSD_PATH"focus_sb_1.png"</IMAGE>    
    <IMAGE id="IMG_ID_VAPP_CAMCO_RECT_AF_NORMAL2_ICON">CAMCO_OSD_PATH"focus_sb_2.png"</IMAGE>    
    <IMAGE id="IMG_ID_VAPP_CAMCO_RECT_AF_NORMAL3_ICON">CAMCO_OSD_PATH"focus_sb_3.png"</IMAGE>    
    <IMAGE id="IMG_ID_VAPP_CAMCO_RECT_AF_NORMAL4_ICON">CAMCO_OSD_PATH"focus_sb_4.png"</IMAGE>    

    <IMAGE id="IMG_ID_VAPP_CAMCO_RECT_AF_SUCCESS1_ICON">CAMCO_OSD_PATH"focus_1.png"</IMAGE>    
    <IMAGE id="IMG_ID_VAPP_CAMCO_RECT_AF_SUCCESS2_ICON">CAMCO_OSD_PATH"focus_2.png"</IMAGE>    
    <IMAGE id="IMG_ID_VAPP_CAMCO_RECT_AF_SUCCESS3_ICON">CAMCO_OSD_PATH"focus_3.png"</IMAGE>    
    <IMAGE id="IMG_ID_VAPP_CAMCO_RECT_AF_SUCCESS4_ICON">CAMCO_OSD_PATH"focus_4.png"</IMAGE>    

    <IMAGE id="IMG_ID_VAPP_CAMCO_RECT_AF_FAIL1_ICON">CAMCO_OSD_PATH"focus_sf_1.png"</IMAGE>    
    <IMAGE id="IMG_ID_VAPP_CAMCO_RECT_AF_FAIL2_ICON">CAMCO_OSD_PATH"focus_sf_2.png"</IMAGE>    
    <IMAGE id="IMG_ID_VAPP_CAMCO_RECT_AF_FAIL3_ICON">CAMCO_OSD_PATH"focus_sf_3.png"</IMAGE>    
    <IMAGE id="IMG_ID_VAPP_CAMCO_RECT_AF_FAIL4_ICON">CAMCO_OSD_PATH"focus_sf_4.png"</IMAGE>  

    <IMAGE id="IMG_ID_VAPP_CAMCO_RECT_FD_SUCCESS1_ICON">CAMCO_OSD_PATH"focus_1.png"</IMAGE>    
    <IMAGE id="IMG_ID_VAPP_CAMCO_RECT_FD_SUCCESS2_ICON">CAMCO_OSD_PATH"focus_2.png"</IMAGE>    
    <IMAGE id="IMG_ID_VAPP_CAMCO_RECT_FD_SUCCESS3_ICON">CAMCO_OSD_PATH"focus_3.png"</IMAGE>    
    <IMAGE id="IMG_ID_VAPP_CAMCO_RECT_FD_SUCCESS4_ICON">CAMCO_OSD_PATH"focus_4.png"</IMAGE>    
    
    <IMAGE id="IMG_ID_VAPP_CAMCO_RECT_SD_SUCCESS1_ICON">CAMCO_OSD_PATH"focus_sm_1.png"</IMAGE>    
    <IMAGE id="IMG_ID_VAPP_CAMCO_RECT_SD_SUCCESS2_ICON">CAMCO_OSD_PATH"focus_sm_2.png"</IMAGE>    
    <IMAGE id="IMG_ID_VAPP_CAMCO_RECT_SD_SUCCESS3_ICON">CAMCO_OSD_PATH"focus_sm_3.png"</IMAGE>    
    <IMAGE id="IMG_ID_VAPP_CAMCO_RECT_SD_SUCCESS4_ICON">CAMCO_OSD_PATH"focus_sm_4.png"</IMAGE>    
           
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_IND_ICON">CAMCO_OSD_PATH"indicator_1.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_MENU_IND_ICON">CAMCO_OSD_PATH"indicator_2.png"</IMAGE>      
    <IMAGE id="IMG_ID_VAPP_CAMCO_UNCHECK_ICON">RES_THEME_ROOT"\\\\Theme1\\\\Components\\\\ListMenu\\\\CheckBox_Off.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_CHECK_ICON">RES_THEME_ROOT"\\\\Theme1\\\\Components\\\\ListMenu\\\\CheckBox_On.png"</IMAGE>      
    <IMAGE id="IMG_ID_VAPP_CAMCO_GALLERY_ICON">CAMCO_OSD_PATH"last_shot_frame.png"</IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_BASE_ICON">CAMCO_OSD_PATH"setting_wheel.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_SWITCHER_BAR_U">CAMCO_OSD_PATH"switcher_rec.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_SWITCHER_BAR_D">CAMCO_OSD_PATH"switcher_cam.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_SWITCHER_REC">CAMCO_OSD_PATH"switcher_rec_icon.png"</IMAGE>    
    <IMAGE id="IMG_ID_VAPP_CAMCO_SWITCHER_CAM">CAMCO_OSD_PATH"switcher_cam_icon.png"</IMAGE>    
    <IMAGE id="IMG_ID_VAPP_CAMCO_ZOOM_IND_ICON">CAMCO_OSD_PATH"zoom_ball.png"</IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CAMCO_ZOOM_IN_ICON">CAMCO_OSD_PATH"zoom_in.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_ZOOM_OUT_ICON">CAMCO_OSD_PATH"zoom_out.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_ZOOM_BAR_ICON">CAMCO_OSD_PATH"zoom_track.png"</IMAGE>

    <IMAGE id="IMG_ID_VAPP_CAMCO_SETTING_AD_SETTING_ICON">CAMCO_OSD_PATH"Icon_Left_Bar\\\\normal\\\\advanced_setting.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_SETTING_AD_SETTING_HILITE_ICON">CAMCO_OSD_PATH"On_Wheel\\\\high_light\\\\advanced_setting.png"</IMAGE>    
    <IMAGE id="IMG_ID_VAPP_CAMCO_SETTING_CAPMODE_ICON">CAMCO_OSD_PATH"Icon_Left_Bar\\\\normal\\\\capture_mode.png"</IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CAMCO_SETTING_CAPMODE_HILITE_ICON">CAMCO_OSD_PATH"On_Wheel\\\\high_light\\\\capture_mode.png"</IMAGE>   
    <IMAGE id="IMG_ID_VAPP_CAMCO_SETTING_EV_ICON">CAMCO_OSD_PATH"Icon_Left_Bar\\\\normal\\\\EV.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_SETTING_EV_HILITE_ICON">CAMCO_OSD_PATH"On_Wheel\\\\high_light\\\\ev.png"</IMAGE>          
    <IMAGE id="IMG_ID_VAPP_CAMCO_SETTING_FLASH_ICON">CAMCO_OSD_PATH"Icon_Left_Bar\\\\normal\\\\flash.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_SETTING_FLASH_HILITE_ICON">CAMCO_OSD_PATH"On_Wheel\\\\high_light\\\\flash.png"</IMAGE>      
    <IMAGE id="IMG_ID_VAPP_CAMCO_SETTING_IMG_PTY_ICON">CAMCO_OSD_PATH"Icon_Left_Bar\\\\normal\\\\image_property.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_SETTING_IMG_PTY_HILITE_ICON">CAMCO_OSD_PATH"On_Wheel\\\\high_light\\\\image_property.png"</IMAGE>      
    <IMAGE id="IMG_ID_VAPP_CAMCO_SETTING_SCN_ICON">CAMCO_OSD_PATH"Icon_Left_Bar\\\\normal\\\\scene_mode.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_SETTING_SCN_HILITE_ICON">CAMCO_OSD_PATH"On_Wheel\\\\high_light\\\\scene_mode.png"</IMAGE>    
    <IMAGE id="IMG_ID_VAPP_CAMCO_SETTING_FRAME_SELECT_ICON">CAMCO_OSD_PATH"Icon_Left_Bar\\\\normal\\\\select_frame.png"</IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CAMCO_SETTING_FRAME_HILITE_SELECT_ICON">CAMCO_OSD_PATH"On_Wheel\\\\high_light\\\\select_frame.png"</IMAGE>     
    <IMAGE id="IMG_ID_VAPP_CAMCO_SETTING_TIMER_ICON">CAMCO_OSD_PATH"Icon_Left_Bar\\\\normal\\\\self_timer.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_SETTING_TIMER_HILITE_ICON">CAMCO_OSD_PATH"On_Wheel\\\\high_light\\\\self_timer.png"</IMAGE>    
    <IMAGE id="IMG_ID_VAPP_CAMCO_SETTING_WB_ICON">CAMCO_OSD_PATH"Icon_Left_Bar\\\\normal\\\\WB.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_SETTING_WB_HILITE_ICON">CAMCO_OSD_PATH"On_Wheel\\\\high_light\\\\wb.png"</IMAGE>       
    
    <IMAGE id="IMG_ID_VAPP_CAMCO_SWITCH_SENSOR">CAMCO_OSD_PATH"Icon_Right_Bar\\\\switch_cam.png"</IMAGE>
    
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_AD_AE_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Advanced_Setting\\\\AE.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_AD_AF_MODE_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Advanced_Setting\\\\AF.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_AD_AF_RANGE_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Advanced_Setting\\\\AF_Range.png"</IMAGE>      
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_AD_AF_ZONE_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Advanced_Setting\\\\AF_Zone.png"</IMAGE>    
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_AD_BANDING_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Advanced_Setting\\\\anti_flicker.png"</IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_AD_AUXILIARY_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Advanced_Setting\\\\auxiliary.png"</IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_AD_ISO_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Advanced_Setting\\\\ISO.png"</IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_AD_QTY_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Advanced_Setting\\\\quality.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_AD_CONTRAST_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Advanced_Setting\\\\Contrast.png"</IMAGE>            
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_AD_SATURATION_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Advanced_Setting\\\\Saturation.png"</IMAGE>            
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_AD_SHARPNESS_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Advanced_Setting\\\\Sharpness.png"</IMAGE>                
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_AD_CAP_AUD_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Advanced_Setting\\\\shutter_sound.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_AD_CAPSIZE_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Advanced_Setting\\\\size.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_AD_STORAGE_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Advanced_Setting\\\\storage.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_AD_TIME_LAPSE_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Advanced_Setting\\\\time_lapse.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_AD_TIME_LAPSE_PERIOD_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Advanced_Setting\\\\time_lapse.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_AD_LIMIT_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Advanced_Setting\\\\limit.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_AD_RESTORE_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Advanced_Setting\\\\to_default.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_AD_HIGHLIGHT_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Advanced_Setting\\\\highlight.png"</IMAGE>    
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_AD_REC_AUD_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Advanced_Setting\\\\rec_sound.png"</IMAGE>    
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_AD_VIS_CODEC_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Advanced_Setting\\\\rec_codec.png"</IMAGE>        
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_AD_RECSIZE_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Advanced_Setting\\\\rec_size.png"</IMAGE>            
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_AD_EFFECT_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Advanced_Setting\\\\image_effect.png"</IMAGE> 

    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_CAPMODE_ADDFRAME_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Capture_Mode\\\\add_frame.png"</IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_CAPMODE_BEST_SHOT_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Capture_Mode\\\\best_shot.png"</IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_CAPMODE_BURST_SHOT_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Capture_Mode\\\\burst_shot.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_CAPMODE_CONT_SHOT_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Capture_Mode\\\\continue_shot.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_CAPMODE_EVB_SHOT_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Capture_Mode\\\\EV.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_CAPMODE_LCE_SHOT_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Capture_Mode\\\\LCE.png"</IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_CAPMODE_NORMAL_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Capture_Mode\\\\normal_mode.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_CAPMODE_HDR_SHOT_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Capture_Mode\\\\HDR.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_CAPMODE_ASD_SHOT_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Capture_Mode\\\\asd.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_CAPMODE_ZSD_SHOT_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Capture_Mode\\\\zsd.png"</IMAGE>      
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_CAPMODE_SMILE_DETECT_SHOT_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Capture_Mode\\\\smile_shot.png"</IMAGE>

    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_ADDFRAME_FRAME1_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Frame\\\\F1.png"</IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_ADDFRAME_FRAME2_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Frame\\\\F2.png"</IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_ADDFRAME_FRAME3_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Frame\\\\F3.png"</IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_ADDFRAME_FRAME4_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Frame\\\\F4.png"</IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_ADDFRAME_FRAME5_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Frame\\\\F5.png"</IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_ADDFRAME_FRAME6_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Frame\\\\F6.png"</IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_ADDFRAME_FRAME7_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Frame\\\\F7.png"</IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_ADDFRAME_FRAME8_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Frame\\\\F8.png"</IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_ADDFRAME_FRAME9_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Frame\\\\F9.png"</IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_ADDFRAME_FRAME10_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Frame\\\\F10.png"</IMAGE> 
    
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_EFFECT1_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Effect\\\\E1.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_EFFECT10_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Effect\\\\E10.png"</IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_EFFECT11_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Effect\\\\E11.png"</IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_EFFECT12_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Effect\\\\E12.png"</IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_EFFECT13_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Effect\\\\E13.png"</IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_EFFECT14_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Effect\\\\E14.png"</IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_EFFECT15_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Effect\\\\E15.png"</IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_EFFECT16_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Effect\\\\E16.png"</IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_EFFECT2_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Effect\\\\E2.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_EFFECT3_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Effect\\\\E3.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_EFFECT4_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Effect\\\\E4.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_EFFECT5_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Effect\\\\E5.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_EFFECT6_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Effect\\\\E6.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_EFFECT7_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Effect\\\\E7.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_EFFECT8_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Effect\\\\E8.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_EFFECT9_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Effect\\\\E9.png"</IMAGE>  
    
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_FLASH_AUTO_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Flash\\\\flash_auto.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_FLASH_FORCE_ON_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Flash\\\\flash_force_on.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_FLASH_OFF_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Flash\\\\flash_off.png"</IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_FLASH_REDEYE_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Flash\\\\flash_red_eye.png"</IMAGE> 
    
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_EV_N4_ICON">CAMCO_OSD_PATH"On_Wheel\\\\EV\\\\EV_m2.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_EV_N3_ICON">CAMCO_OSD_PATH"On_Wheel\\\\EV\\\\EV_m1_5.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_EV_N2_ICON">CAMCO_OSD_PATH"On_Wheel\\\\EV\\\\EV_m1.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_EV_N1_ICON">CAMCO_OSD_PATH"On_Wheel\\\\EV\\\\EV_m0_5.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_EV_0_ICON">CAMCO_OSD_PATH"On_Wheel\\\\EV\\\\EV_p0.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_EV_P1_ICON">CAMCO_OSD_PATH"On_Wheel\\\\EV\\\\EV_p0_5.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_EV_P2_ICON">CAMCO_OSD_PATH"On_Wheel\\\\EV\\\\EV_p1.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_EV_P3_ICON">CAMCO_OSD_PATH"On_Wheel\\\\EV\\\\EV_p1_5.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_EV_P4_ICON">CAMCO_OSD_PATH"On_Wheel\\\\EV\\\\EV_p2.png"</IMAGE>
    
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_SCN_MODE_ANTI_SHAKE_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Scene_Mode\\\\mode_antishake.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_SCN_MODE_AUTO_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Scene_Mode\\\\mode_auto.png"</IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_SCN_MODE_NIGHT_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Scene_Mode\\\\mode_night.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_SCN_MODE_PORTRAIT_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Scene_Mode\\\\mode_portrait.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_SCN_MODE_SPORT_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Scene_Mode\\\\mode_sport.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_SCN_MODE_TEXT_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Scene_Mode\\\\mode_text.png"</IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_SCN_MODE_VIEW_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Scene_Mode\\\\mode_view.png"</IMAGE> 

    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_TIMER_15_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Self_Timer\\\\timer_15s.png"</IMAGE>     
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_TIMER_10_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Self_Timer\\\\timer_10s.png"</IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_TIMER_5_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Self_Timer\\\\timer_5s.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_TIMER_OFF_ICON">CAMCO_OSD_PATH"On_Wheel\\\\Self_Timer\\\\timer_off.png"</IMAGE> 
    
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_WB_NORMAL_ICON">CAMCO_OSD_PATH"On_Wheel\\\\WB\\\\AWB.png"</IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_WB_CLOUDY_ICON">CAMCO_OSD_PATH"On_Wheel\\\\WB\\\\cloudy.png"</IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_WB_DAYLIGHT_ICON">CAMCO_OSD_PATH"On_Wheel\\\\WB\\\\daylight.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_WB_FLOURESCENT_ICON">CAMCO_OSD_PATH"On_Wheel\\\\WB\\\\fluorescent.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_WB_INCADESCENT_ICON">CAMCO_OSD_PATH"On_Wheel\\\\WB\\\\incandescent.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_WHEEL_WB_TUNGSTEN_ICON">CAMCO_OSD_PATH"On_Wheel\\\\WB\\\\tungsten.png"</IMAGE>  
     
    
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_AF_INFINTE_ICON">CAMCO_OSD_PATH"Status_Icon\\\\AF\\\\AF_infi.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_AF_MACRO_ICON">CAMCO_OSD_PATH"Status_Icon\\\\AF\\\\AF_marco.png"</IMAGE>  
    
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_CAPMODE_ADDFRAME_ICON">CAMCO_OSD_PATH"Status_Icon\\\\CaptureMode\\\\add_frame.png"</IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_CAPMODE_BEST_SHOT_ICON">CAMCO_OSD_PATH"Status_Icon\\\\CaptureMode\\\\best_shot.png"</IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_CAPMODE_BURST_SHOT_ICON">CAMCO_OSD_PATH"Status_Icon\\\\CaptureMode\\\\burst_shot.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_CAPMODE_CONT_SHOT_ICON">CAMCO_OSD_PATH"Status_Icon\\\\CaptureMode\\\\continue_shot.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_CAPMODE_EVBSHOT_ICON">CAMCO_OSD_PATH"Status_Icon\\\\CaptureMode\\\\ev.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_CAPMODE_LCE_SHOT_ICON">CAMCO_OSD_PATH"Status_Icon\\\\CaptureMode\\\\lce.png"</IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_CAPMODE_NORMAL_SHOT_ICON">CAMCO_OSD_PATH"Status_Icon\\\\CaptureMode\\\\normal_mode.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_CAPMODE_SMILE_DETECT_ICON">CAMCO_OSD_PATH"Status_Icon\\\\CaptureMode\\\\smile_shot.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_CAPMODE_HDR_SHOT_ICON">CAMCO_OSD_PATH"Status_Icon\\\\CaptureMode\\\\hdr.png"</IMAGE>        
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_CAPMODE_ZSD_SHOT_ICON">CAMCO_OSD_PATH"Status_Icon\\\\CaptureMode\\\\zsd.png"</IMAGE>        
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_CAPMODE_ASD_SHOT_ICON">CAMCO_OSD_PATH"Status_Icon\\\\CaptureMode\\\\asd.png"</IMAGE>        
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_CAPMODE_ASD_SHOT_AUTO_MODE_ICON">CAMCO_OSD_PATH"Status_Icon\\\\SceneMode\\\\mode_auto.png"</IMAGE>       
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_CAPMODE_ASD_SHOT_BACKLIGHT_MODE_ICON">CAMCO_OSD_PATH"Status_Icon\\\\SceneMode\\\\mode_backlight.png"</IMAGE>   
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_CAPMODE_ASD_SHOT_BACKLIGHT_PORTRAIT_MODE_ICON">CAMCO_OSD_PATH"Status_Icon\\\\SceneMode\\\\mode_backlight_portrait.png"</IMAGE>   
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_CAPMODE_ASD_SHOT_LANDSCAPE_MODE_ICON">CAMCO_OSD_PATH"Status_Icon\\\\SceneMode\\\\mode_landscape.png"</IMAGE>   
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_CAPMODE_ASD_SHOT_NIGHT_MODE_ICON">CAMCO_OSD_PATH"Status_Icon\\\\SceneMode\\\\mode_night.png"</IMAGE>   
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_CAPMODE_ASD_SHOT_NIGHT_PORTRAIT_MODE_ICON">CAMCO_OSD_PATH"Status_Icon\\\\SceneMode\\\\mode_night_portrait.png"</IMAGE>   
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_CAPMODE_ASD_SHOT_PORTRAIT_MODE_ICON">CAMCO_OSD_PATH"Status_Icon\\\\SceneMode\\\\mode_portrait.png"</IMAGE>   

    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_EV_0_ICON">CAMCO_OSD_PATH"Status_Icon\\\\EV\\\\ev_p0.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_EV_N1_ICON">CAMCO_OSD_PATH"Status_Icon\\\\EV\\\\ev_n05.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_EV_N2_ICON">CAMCO_OSD_PATH"Status_Icon\\\\EV\\\\ev_n1.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_EV_N3_ICON">CAMCO_OSD_PATH"Status_Icon\\\\EV\\\\ev_n15.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_EV_N4_ICON">CAMCO_OSD_PATH"Status_Icon\\\\EV\\\\ev_n2.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_EV_P1_ICON">CAMCO_OSD_PATH"Status_Icon\\\\EV\\\\ev_p05.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_EV_P2_ICON">CAMCO_OSD_PATH"Status_Icon\\\\EV\\\\ev_p1.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_EV_P3_ICON">CAMCO_OSD_PATH"Status_Icon\\\\EV\\\\ev_p15.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_EV_P4_ICON">CAMCO_OSD_PATH"Status_Icon\\\\EV\\\\ev_p2.png"</IMAGE>  
    
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_FLASH_AUTO_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Flash\\\\flash_auto.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_FLASH_FORCE_ON_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Flash\\\\flash_on.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_FLASH_OFF_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Flash\\\\flash_off.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_FLASH_REDEYE_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Flash\\\\flash_redeye.png"</IMAGE>
    
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_ISO_100_ICON">CAMCO_OSD_PATH"Status_Icon\\\\ISO\\\\iso_100.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_ISO_200_ICON">CAMCO_OSD_PATH"Status_Icon\\\\ISO\\\\iso_200.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_ISO_400_ICON">CAMCO_OSD_PATH"Status_Icon\\\\ISO\\\\iso_400.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_ISO_800_ICON">CAMCO_OSD_PATH"Status_Icon\\\\ISO\\\\iso_800.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_ISO_1600_ICON">CAMCO_OSD_PATH"Status_Icon\\\\ISO\\\\iso_1600.png"</IMAGE>

    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_TIME_LAPSE_ON_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Time_Lapse\\\\time_lapse.png"</IMAGE>

    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_LIMIT_15S_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Limit\\\\15sec.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_LIMIT_30S_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Limit\\\\30sec.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_LIMIT_60S_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Limit\\\\60sec.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_LIMIT_300S_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Limit\\\\300sec.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_LIMIT_600S_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Limit\\\\600sec.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_LIMIT_95K_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Limit\\\\95kb.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_LIMIT_195K_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Limit\\\\195kb.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_LIMIT_295K_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Limit\\\\295kb.png"</IMAGE>

    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_SCN_MODE_ANTI_ICON">CAMCO_OSD_PATH"Status_Icon\\\\SceneMode\\\\mode_anti_shake.png"</IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_SCN_MODE_NIGHT_ICON">CAMCO_OSD_PATH"Status_Icon\\\\SceneMode\\\\mode_night.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_SCN_MODE_PORTRAIT_ICON">CAMCO_OSD_PATH"Status_Icon\\\\SceneMode\\\\mode_portrait.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_SCN_MODE_SPORT_ICON">CAMCO_OSD_PATH"Status_Icon\\\\SceneMode\\\\mode_sport.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_SCN_MODE_TEXT_ICON">CAMCO_OSD_PATH"Status_Icon\\\\SceneMode\\\\mode_text.png"</IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_SCN_MODE_VIEW_ICON">CAMCO_OSD_PATH"Status_Icon\\\\SceneMode\\\\mode_landscape.png"</IMAGE> 
    
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_CAPSIZE_1M_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Size_Photo\\\\1m.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_CAPSIZE_2M_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Size_Photo\\\\2m.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_CAPSIZE_3M_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Size_Photo\\\\3m.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_CAPSIZE_4M_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Size_Photo\\\\4m.png"</IMAGE>      
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_CAPSIZE_5M_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Size_Photo\\\\5m.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_CAPSIZE_WP_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Size_Photo\\\\wp.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_CAPSIZE_VGA_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Size_Photo\\\\vga.png"</IMAGE> 
#if defined(__MMI_MAINLCD_240X400__)
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_CAPSIZE_HLCD_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Size_Photo\\\\wqvga.png"</IMAGE>
#elif defined(__MMI_MAINLCD_320X480__)
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_CAPSIZE_HLCD_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Size_Photo\\\\hvga.png"</IMAGE>
#elif defined(__MMI_MAINLCD_480X800__)
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_CAPSIZE_HLCD_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Size_Photo\\\\wvga.png"</IMAGE>
#else
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_CAPSIZE_HLCD_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Size_Photo\\\\qvga.png"</IMAGE>
#endif           

    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_RECSIZE_SQCIF_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Size_Rec\\\\sqcif.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_RECSIZE_QQVGA_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Size_Rec\\\\qqvga.png"</IMAGE>    
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_RECSIZE_QCIF_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Size_Rec\\\\qcif.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_RECSIZE_QVGA_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Size_Rec\\\\qvga.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_RECSIZE_CIF_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Size_Rec\\\\cif.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_RECSIZE_WQVGA_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Size_Rec\\\\wqvga.png"</IMAGE>         
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_RECSIZE_CIF2_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Size_Rec\\\\cif2.png"</IMAGE>     
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_RECSIZE_HVGA_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Size_Rec\\\\hvga.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_RECSIZE_NHD_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Size_Rec\\\\nhd.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_RECSIZE_VGA_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Size_Rec\\\\vga.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_RECSIZE_4CIF_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Size_Rec\\\\4cif.png"</IMAGE>    
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_RECSIZE_D1_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Size_Rec\\\\d1.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_RECSIZE_D12_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Size_Rec\\\\d12.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_RECSIZE_WVGA_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Size_Rec\\\\wvga.png"</IMAGE>                          
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_RECSIZE_SVGA_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Size_Rec\\\\svga.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_RECSIZE_WVGA2_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Size_Rec\\\\wvga2.png"</IMAGE>  
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_RECSIZE_FWVGA_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Size_Rec\\\\fwvga.png"</IMAGE>      
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_RECSIZE_XGA_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Size_Rec\\\\xga.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_RECSIZE_720P_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Size_Rec\\\\720p.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_RECSIZE_4VGA_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Size_Rec\\\\4vga.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_RECSIZE_SXGA_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Size_Rec\\\\sxga.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_RECSIZE_16CIF_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Size_Rec\\\\16CIF.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_RECSIZE_4SVGA_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Size_Rec\\\\4svga.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_RECSIZE_FHD_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Size_Rec\\\\fhd.png"</IMAGE>

    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_TIMER_15S_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Timer\\\\timer_15s.png"</IMAGE>     
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_TIMER_10S_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Timer\\\\timer_10s.png"</IMAGE> 
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_TIMER_5S_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Timer\\\\timer_5s.png"</IMAGE>  

    <IMAGE id="IMG_ID_VAPP_CAMCO_MULTI_SHOT_INDICATOR_ICON">CAMCO_OSD_PATH"pana_focus.png"</IMAGE>        

    <CACHEDATA type="short" id="NVRAM_CAM_FILENAME_SEQ_NO" restore_flag="TRUE">
        <DEFAULT_VALUE> [0xFF, 0xFF] </DEFAULT_VALUE>
        <DESCRIPTION> CameraApp </DESCRIPTION>
    </CACHEDATA>    

    <CACHEDATA type="short" id="NVRAM_VDOREC_FILENAME_SEQ_NO">
        <DEFAULT_VALUE> [0xFF, 0xFF] </DEFAULT_VALUE>
        <DESCRIPTION> Short Cache </DESCRIPTION>
    </CACHEDATA>   

    <SCREEN id="SCR_ID_VAPP_CAMCO_APP"/>
    <SCREEN id="SCR_ID_VAPP_CAMCO_EXT_APP"/>
    <SCREEN id="SCR_GROUP_ID_VAPP_CAMCO_APP"/>
    <SCREEN id="SCR_GROUP_ID_VAPP_CAMCO_PARTIAL_APP"/>
    <SCREEN id="SCR_GROUP_ID_VAPP_CAMCO_INT_APP"/>    
    <SCREEN id="SCR_GROUP_ID_VAPP_CAMCO_EXT_APP"/>   
    
    <RECEIVER id="EVT_ID_PRE_KEY_EVT_ROUTING" proc="vapp_camco_pre_key_hdlr"/>

    <AUDIO id="AUD_ID_VAPP_CAMCO_COUNTDOWN">CUST_ADO_PATH"\\\\Camcorder\\\\count.wav"</AUDIO>
#if defined(MT6225) || defined(MT6253) || defined(MT6253T) || defined(MT6235) || defined(MT6235B)
    <AUDIO id="AUD_ID_VAPP_CAMCO_CAPTURE_1">CUST_ADO_PATH"\\\\Camcorder\\\\pic_.wav"</AUDIO>
#else
    <AUDIO id="AUD_ID_VAPP_CAMCO_CAPTURE_1">CUST_ADO_PATH"\\\\Camcorder\\\\pic.wav"</AUDIO>
#endif
    <AUDIO id="AUD_ID_VAPP_CAMCO_CAPTURE_2">CUST_ADO_PATH"\\\\Camcorder\\\\pic1.wav"</AUDIO>
    <AUDIO id="AUD_ID_VAPP_CAMCO_CAPTURE_3">CUST_ADO_PATH"\\\\Camcorder\\\\pic2.wav"</AUDIO>

</APP>

#endif

