#include "mmi_features.h"
#include "custresdef.h"

<?xml version="1.0" encoding="UTF-8"?>

<APP id="VCUI_SSO_SETTING" name="STR_ID_SSO_SETTINGS" type="venus">
    <MEMORY extra_base="10240" heap="153600"/>
    
    <STRING id="STR_ID_VCUI_SSO_TITLE"/>
    <STRING id="STR_ID_VCUI_SSO_CONTACTS"/>
    <STRING id="STR_ID_VCUI_SSO_BACKUP_TO"/>
    <STRING id="STR_ID_VCUI_SSO_RESTORE_FROM"/>
    <STRING id="STR_ID_VCUI_SSO_BACKUP_POP"/>
    <STRING id="STR_ID_VCUI_SSO_RESTORE_POP"/>
    <STRING id="STR_ID_VCUI_SSO_PHB_INSUFFICIENT_STORAGE"/>
    <STRING id="STR_ID_VCUI_SSO_SMS_INSUFFICIENT_STORAGE"/>
    <STRING id="STR_ID_VCUI_SSO_TOOLBAR_BACKUP"/>
    <STRING id="STR_ID_VCUI_SSO_TOOLBAR_RESTORE"/>
    <STRING id="STR_ID_VCUI_SSO_PHB_AND_SMS_RESTORE_ERR"/>
    <STRING id="STR_ID_VCUI_SSO_PHB_RESTORE_ERR"/>
    <STRING id="STR_ID_VCUI_SSO_SMS_RESTORE_ERR"/>
    <STRING id="STR_ID_VCUI_SSO_PHB_AND_SMS_BACKUP_ERR"/>
    <STRING id="STR_ID_VCUI_SSO_PHB_BACKUP_ERR"/>
    <STRING id="STR_ID_VCUI_SSO_SMS_BACKUP_ERR"/>
    <STRING id="STR_ID_VCUI_SSO_BACKUP_PHB_POP"/>
    <STRING id="STR_ID_VCUI_SSO_RESTORE_PHB_POP"/>
    <STRING id="STR_ID_VCUI_SSO_BACKUP_SMS_POP"/>
    <STRING id="STR_ID_VCUI_SSO_RESTORE_SMS_POP"/>
    <STRING id="STR_ID_VCUI_SSO_RESTORE_PHB_SMS_POP"/>
    <STRING id="STR_ID_VCUI_SSO_BACKUP_PHB_SMS_POP"/>
    <STRING id="STR_ID_VCUI_SSO_YAHOO_SERVICE"/>
    <STRING id="STR_ID_VCUI_SSO_SMS_BACKUP_ERR"/>
    <STRING id="STR_ID_VCUI_SSO_PHB_AND_SMS_BACKUP_ERR"/>
</APP>