#include "mmi_features.h"
#include "custresdef.h"

<?xml version="1.0" encoding="UTF-8"?>

<APP id="VAPP_CONTACT"
    package_name="native.mtk.contact"
    name="STR_ID_VAPP_CONTACT"
    img="IMG_ID_VAPP_CONTACT"
    launch="vapp_contact_launch" type="venus">

    <INCLUDE file="GlobalResDef.h"/>
    <INCLUDE file="Mmi_rp_srv_venus_component_tool_bar_def.h"/>
    <INCLUDE file="Mmi_rp_vcui_fmgr_def.h"/>
    <INCLUDE file="FileMgrServiceResDef.h"/>

    <!--Memory config ------------------------------------------------------------------------------------>

#ifndef __LOW_COST_SUPPORT_COMMON__
#ifdef __MMI_SNS_CONTACTS__
    <MEMORY heap="500*1024" extra_base="VAPP_SNS_PROFILE_EXTRA_BASE_SIZE" cui="VCUI_CONTACT_LIST + VCUI_CONTACT_VIEW" fg="VAPP_SNS_HAPPENINGS_CACHE_FG_SIZE" inc="vapp_sns_mem_def.h"/>
#else
    <MEMORY heap="500*1024" cui="VCUI_CONTACT_LIST + VCUI_CONTACT_VIEW"/>
#endif
#else
#ifdef __MMI_SNS_CONTACTS__
    <MEMORY heap="400*1024" extra_base="VAPP_SNS_PROFILE_EXTRA_BASE_SIZE" cui="VCUI_CONTACT_VIEW" fg="VAPP_SNS_HAPPENINGS_CACHE_FG_SIZE" inc="vapp_sns_mem_def.h"/>
#else
#ifdef __MMI_SMS_COMPOSER__
    <MEMORY heap="400*1024"
#ifdef __MMI_CONTACT_SLIM__
    extra_base = " 50 * 1024"
#endif
    cui= "max(VCUI_CONTACT_VIEW, VCUI_SMS_COMPOSER)"/>
#else
    <MEMORY heap="400*1024"  cui="VCUI_CONTACT_VIEW"/>
#endif
#endif
#endif

#ifdef __MMI_SNS_CONTACTS__
    <APPCONCURRENT concurrent ="VAPP_CONTACT, VAPP_SNS_PLUGIN"/>
#endif

    <!--Event config ------------------------------------------------------------------------------------>

    <SENDER id="EVT_ID_VAPP_PHB_APP_ENTER" hfile="vapp_phb_gprot.h"/>

    <RECEIVER id="EVT_ID_GPIO_BEFORE_LCD_SLEEP_IN"        proc="vapp_phb_processing_hdlr"/>
    <RECEIVER id="EVT_ID_GPIO_AFTER_LCD_SLEEP_IN"         proc="vapp_phb_processing_hdlr"/>

#ifdef __DM_LAWMO_SUPPORT__
    <RECEIVER id="EVT_ID_SRV_DM_LAWMO_LOCK_IND"           proc="vapp_phb_processing_hdlr"/>
    <RECEIVER id="EVT_ID_SRV_DM_LAWMO_WIPE_IND"           proc="vapp_phb_processing_hdlr"/>
#endif

#if defined(__SIM_HOT_SWAP_SUPPORT__) || defined(__SIM_RECOVERY_ENHANCEMENT__)
    <RECEIVER id="EVT_ID_SRV_SIM_CTRL_EVENT_DETECTED"     proc="vapp_phb_processing_hdlr"/>
#endif

    <!--String ID----------------------------------------------------------------------------------------->

    <!--Contacts field-->

    <STRING id="VAPP_PHB_STR_UNNAMED"/>
    <STRING id="VAPP_PHB_STR_FIRST_NAME"/>
    <STRING id="VAPP_PHB_STR_LAST_NAME"/>
    <STRING id="VAPP_PHB_STR_NAME"/>
    <STRING id="VAPP_PHB_STR_NICKNAME"/>
    <STRING id="VAPP_PHB_STR_NUMBER"/>
    <STRING id="VAPP_PHB_STR_EMAIL"/>
    <STRING id="VAPP_PHB_STR_TITLE"/>
    <STRING id="VAPP_PHB_STR_COMPANY"/>
    <STRING id="VAPP_PHB_STR_RING"/>
    <STRING id="VAPP_PHB_STR_URL"/>
    <STRING id="VAPP_PHB_STR_NOTE"/>
    <STRING id="VAPP_PHB_STR_ADDRESS"/>
    <STRING id="VAPP_PHB_STR_BDAY"/>
    <STRING id="VAPP_PHB_STR_MOBILE"/>
    <STRING id="VAPP_PHB_STR_HOME"/>
    <STRING id="VAPP_PHB_STR_WORK"/>
    <STRING id="VAPP_PHB_STR_FAX"/>
    <STRING id="VAPP_PHB_STR_POBOX"/>
    <STRING id="VAPP_PHB_STR_EXTENSION"/>
    <STRING id="VAPP_PHB_STR_STREET"/>
    <STRING id="VAPP_PHB_STR_CITY"/>
    <STRING id="VAPP_PHB_STR_STATE"/>
    <STRING id="VAPP_PHB_STR_POSTALCODE"/>
    <STRING id="VAPP_PHB_STR_COUNTRY"/>
    <STRING id="VAPP_PHB_STR_STORAGE"/>

    <!--Contacts-->

    <STRING id="VAPP_PHB_STR_CONTACTS"/>
    <STRING id="VAPP_PHB_STR_CONTACTS_APPEND"/>
    <STRING id="VAPP_PHB_STR_CONTACT"/>
    <STRING id="VAPP_PHB_STR_CONTACT_APPEND"/>
    <STRING id="VAPP_PHB_STR_CONTACT_EMPTY"/>
    <STRING id="STR_ID_VAPP_PHB_PROCESSING"/>

    <!--Storage-->

    //<STRING id="VAPP_PHB_STR_SIM"/>
    <STRING id="VAPP_PHB_STR_PHONE"/>
    <STRING id="STR_ID_VAPP_PHB_STORAGE_IS_UNAVAILABLE"/>
    <STRING id="STR_ID_VAPP_PHB_STORAGE_IS_FULL"/>
    <STRING id="STR_ID_VAPP_PHB_STORAGE_IS_EMPTY"/>
    //<STRING id="STR_ID_VAPP_PHB_SELECT_STORAGE"/>

    <!--Action-->

    <STRING id="VAPP_PHB_STR_ADD_CONTACT"/>
    <STRING id="VAPP_PHB_STR_CALL"/>
    <STRING id="STR_ID_VAPP_PHB_CALL_TO"/>
    //<STRING id="VAPP_PHB_STR_SEND_MSG"/>
    <STRING id="STR_ID_VAPP_PHB_MESSAGE_TO"/>
    <STRING id="VAPP_PHB_STR_SEND_EMAIL"/>
    <STRING id="VAPP_PHB_STR_NOTIFY_ME"/>
    <STRING id="VAPP_PHB_STR_BLOCK_NUMBER"/>
    <STRING id="VAPP_PHB_STR_UNBLOCK_NUMBER"/>
    <STRING id="STR_ID_VAPP_PHB_COPY"/>
    <STRING id="STR_ID_VAPP_PHB_DELETE_THE_CONTACT"/>
    <STRING id="STR_ID_VAPP_PHB_DELETE_SELECTED"/>
    <STRING id="STR_ID_VAPP_PHB_SHARE_CONTACT"/>
    <STRING id="STR_ID_VAPP_PHB_SHARE_MY_CARD"/>
    <STRING id="STR_ID_VAPP_PHB_SHARE_WITH_SMS"/>
    <STRING id="STR_ID_VAPP_PHB_SHARE_WITH_MMS"/>
    <STRING id="STR_ID_VAPP_PHB_SHARE_WITH_EMAIL"/>
    <STRING id="STR_ID_VAPP_PHB_SHARE_WITH_BLUETOOTH"/>
    //<STRING id="STR_ID_VAPP_PHB_EDIT_BEFORE_CALL"/>
    <STRING id="STR_ID_VAPP_PHB_VIDEO_CALL"/>
    <STRING id="STR_ID_VAPP_PHB_NO_COPY_WITH_W"/>
    <STRING id="STR_ID_VAPP_PHB_NO_COPY_WITH_Q"/>
    <STRING id="STR_ID_VAPP_PHB_SELECT_SIM"/>

    <!--Sub app-->

    <STRING id="VAPP_PHB_STR_PROFILE"/>
    <STRING id="VAPP_PHB_STR_CLOG"/>
    <STRING id="VAPP_PHB_STR_MSG"/>
    <STRING id="VAPP_PHB_STR_LOCAL"/>
    <STRING id="VAPP_PHB_STR_SNS"/>
    <STRING id="VAPP_PHB_STR_SHARE"/>
    <STRING id="VAPP_PHB_STR_MESSAGE"/>
    <STRING id="VAPP_PHB_STR_MYCARD"/>
    <STRING id="VAPP_PHB_STR_DIAL"/>
    <STRING id="VAPP_PHB_STR_CLOGS"/>

    <!--Groups-->

    <STRING id="VAPP_PHB_STR_GROUPS"/>
    <STRING id="VAPP_PHB_STR_GROUP_EMPTY"/>
    <STRING id="VAPP_PHB_STR_ADD_GROUP"/>
    <STRING id="VAPP_PHB_STR_EDIT_GROUP"/>
    <STRING id="VAPP_PHB_STR_GROUP_NAME"/>    
    <STRING id="VAPP_PHB_STR_GROUP_RINGTONE"/>
    <STRING id="VAPP_PHB_STR_EDIT_MEMBER"/>
    <STRING id="VAPP_PHB_STR_ADD_MEMBER"/>
    //<STRING id="VAPP_PHB_STR_GROUP_NO_MEMBER"/>
    <STRING id="VAPP_PHB_STR_EDIT_GROUP_MEMBER"/>
    <STRING id="VAPP_PHB_STR_ADD_GROUP_MEMBER"/>
    <STRING id="VAPP_PHB_STR_REMOVE_GROUP_MEMBER"/>
    <STRING id="VAPP_PHB_STR_MOVE_GROUP_MEMBER"/>
    <STRING id="VAPP_PHB_STR_CREATE_NEW_GROUP"/>
    <STRING id="STR_ID_VAPP_PHB_GROUPS"/>
    <STRING id="STR_ID_VAPP_PHB_GROUP"/>
    <STRING id="STR_ID_VAPP_PHB_NO_MEMBERS"/>
    <STRING id="STR_ID_VAPP_PHB_SELECT_GROUP"/>
    <STRING id="STR_ID_VAPP_PHB_GROUP_NAME_EMPTY"/>
    <STRING id="STR_ID_VAPP_PHB_GROUP_NAME_DUPLICATED"/>

    <!--SNS-->

    <STRING id="STR_ID_VAPP_PHB_LINK"/>
    <STRING id="STR_ID_VAPP_PHB_UNLINK"/>
    <STRING id="STR_ID_VAPP_PHB_SELECT_CONTACT"/>
    <STRING id="STR_ID_VAPP_PHB_SELECT_ACCOUNT"/>
    <STRING id="STR_ID_VAPP_PHB_CHOOSE_TO_UNLINK"/>
    <STRING id="STR_ID_VAPP_PHB_NO_SNS_ACCOUNT_CONFIRM"/>

    <!--Setting-->

    <STRING id="STR_ID_VAPP_PHB_RESTORE_DELETING"/>
    <STRING id="STR_ID_VAPP_PHB_RESTORE_CHOOSE_ACTION"/>
    <STRING id="STR_ID_VAPP_PHB_BACKUPING"/>
    <STRING id="STR_ID_VAPP_PHB_IMPORTING"/>
    <STRING id="STR_ID_VAPP_PHB_EXPORTING"/>
    <STRING id="STR_ID_VAPP_PHB_SPEED_DIAL_SELECT_ACTION"/>
    <STRING id="STR_ID_VAPP_PHB_RESTORE_TITLE"/>
    <STRING id="STR_ID_VAPP_PHB_IMPORT_FROM"/>
    <STRING id="STR_ID_VAPP_PHB_EXPORT_TO"/>
    <STRING id="STR_ID_VAPP_PHB_SETING_EXTRA"/>
    <STRING id="STR_ID_VAPP_PHB_SETTING_SYNC"/>
    <STRING id="STR_ID_VAPP_PHB_SETTING_IMPORT"/>
    <STRING id="STR_ID_VAPP_PHB_SETTING_EXPORT"/>
#if defined(__MMI_MULTI_VCARD__) || defined(__VCARD_CLOUD_SUPPORT__)
    <STRING id="STR_ID_VAPP_PHB_SETTING_RESTORE"/>
    <STRING id="STR_ID_VAPP_PHB_SETTING_BACKUP"/>
#endif    
    <STRING id="STR_ID_VAPP_PHB_SETTING_SAVE_NOTIFY"/>
    <STRING id="STR_ID_VAPP_PHB_SPEED_DIAL_LIST"/>
#ifdef __MMI_PHB_SPEED_DIAL__
    <STRING id="STR_ID_VAPP_PHB_SETTING_SPEED_DIAL"/>
#endif
    <STRING id="STR_ID_VAPP_PHB_SETTING_NAME_DISPLAY_FIRST_NAME_LAST"/>
    <STRING id="STR_ID_VAPP_PHB_SETTING_NAME_DISPLAY_FIRST_NAME_FIRST"/>
    <STRING id="STR_ID_VAPP_PHB_SETTING_NAME_DISPLAY"/>
    <STRING id="STR_ID_VAPP_PHB_SETTING_STORAGE"/>
    <STRING id="STR_ID_VAPP_PHB_SETTING"/>
    <STRING id="STR_ID_VAPP_PHB_FND_MULTI_DELETE_TITLE"/>
    <STRING id="STR_ID_VAPP_PHB_FDN_EDIT_TITLE"/>    
    <STRING id="STR_ID_VAPP_PHB_FDN_ADD_TITLE"/>   
    <STRING id="STR_ID_VAPP_PHB_FND_LIST_TITLE"/>
    <STRING id="STR_ID_VAPP_PHB_FND_ON_OFF"/>
    <STRING id="STR_ID_VAPP_PHB_SETTING_SPEED_NO_SET"/>
    <STRING id="STR_ID_VAPP_PHB_SETTING_PROCESSING"/>
    <STRING id="STR_ID_VAPP_PHB_SPEED_SELECT_FROM_CONTACT"/>
    <STRING id="STR_ID_VAPP_PHB_NO_FILE_TO_RESTORE"/>
    <STRING id="STR_ID_VAPP_PHB_SELECT_TO_RESTORE"/>
    <STRING id="STR_ID_VAPP_PHB_FND_TITLE"/>
    <STRING id="STR_ID_VAPP_PHB_FND_SIM_SELECT"/>
    <STRING id="STR_ID_VAPP_PHB_INSERT_MEMORY_CARD"/>
    <STRING id="STR_ID_VAPP_PHB_BACKUP_FULL"/>
    //<STRING id="STR_ID_VAPP_PHB_FDN_FULL"/>
    <STRING id="STR_ID_VAPP_PHB_VCARD_SAVE"/>
    <STRING id="STR_ID_VAPP_PHB_VCARD_SAVING"/>
    <STRING id="STR_ID_VAPP_PHB_PLEASE_INPUT_NUMBER"/>
    <STRING id="STR_ID_VAPP_PHB_INVALID_NUMBER"/>
    <STRING id="STR_ID_VAPP_PHB_SUCCESS"/>
    <STRING id="STR_ID_VAPP_PHB_TOTAL"/>

    <!-- Cloud Service backup restore-->

    <STRING id="STR_ID_VAPP_PHB_BACKUP_TO"/>
    <STRING id="STR_ID_VAPP_PHB_RESTORE_FROM"/>
    <STRING id="STR_ID_VAPP_PHB_CLOUD_YAHOO_SERVICE"/>
    <STRING id="STR_ID_VAPP_PHB_MEMORY_CARD"/>
    <STRING id="STR_ID_VAPP_PHB_CLOUD_RELOGIN"/>
    <STRING id="STR_ID_VAPP_PHB_CLOUD_BACKUPING"/>
    <STRING id="STR_ID_VAPP_PHB_CLOUD_RESTORING"/>
    <STRING id="STR_ID_VAPP_PHB_CLOUD_NO_CONTACT_BACKUP"/>
    <STRING id="STR_ID_VAPP_PHB_CLOUD_NO_CONTACT_RESTORE"/>

    <!--Cui editor-->

    <STRING id="VAPP_PHB_STR_ADD_NEW_CONTACT"/>
    <STRING id="VAPP_PHB_STR_EDIT_CONTACT"/>
    <STRING id="VAPP_PHB_STR_ADD_NAME"/>
    //<STRING id="VAPP_PHB_STR_SAVE_A_NUMBER"/>
    //<STRING id="VAPP_PHB_STR_SAVE_A_EMAIL"/>
    <STRING id="VAPP_PHB_STR_CREATE_NEW_CONTACT"/>
    <STRING id="VAPP_PHB_STR_ADD_TO_EXISTING_CONTACT"/>
    <STRING id="VAPP_PHB_STR_NO_MORE_NUMBER"/>
    <STRING id="VAPP_PHB_STR_NO_MORE_EMAIL"/>
    <STRING id="VAPP_PHB_STR_ADD_ADDRESS"/>
    <STRING id="VAPP_PHB_STR_OTHER_INFO"/>
    <STRING id="VAPP_PHB_STR_CONTACT_SETTING"/>
    <STRING id="VAPP_PHB_STR_GROUP"/>
    <STRING id="VAPP_PHB_STR_NO_GROUP"/>
    <STRING id="VAPP_PHB_STR_SELECT_NUM_TYPE"/>
    <STRING id="VAPP_PHB_STR_DEFAULT_NUM_TYPE"/>
    <STRING id="VAPP_PHB_STR_CUSTOM_NUM_TYPE"/>
    <STRING id="VAPP_PHB_STR_SELECT_EMAIL_TYPE"/>
    <STRING id="VAPP_PHB_STR_DEFAULT_EMAIL_TYPE"/>
    <STRING id="VAPP_PHB_STR_CUSTOM_EMAIL_TYPE"/>
    <STRING id="STR_ID_VAPP_PHB_SET_PHOTO"/>
    <STRING id="STR_ID_VAPP_PHB_SELECT_FROM_GALLERY"/>
    <STRING id="STR_ID_VAPP_PHB_TAKE_A_PHOTO"/>
    <STRING id="STR_ID_VAPP_PHB_REMOVE_PHOTO"/>
    <STRING id="STR_ID_VAPP_PHB_INFO_MISSED"/>
    <STRING id="STR_ID_VAPP_PHB_INFO_MISSED_CONTINUE"/>
    <STRING id="STR_ID_VAPP_PHB_ADD_NUMBER_TYPE"/>
    <STRING id="STR_ID_VAPP_PHB_ADD_EMAIL_TYPE"/>
    <STRING id="STR_ID_VAPP_PHB_NUMBER_TYPE_WARNING"/>
    <STRING id="STR_ID_VAPP_PHB_EMAIL_TYPE_WARNING"/>
    //<STRING id="STR_ID_VAPP_PHB_ADDRESS_WARNING"/>
    <STRING id="STR_ID_VAPP_PHB_NAME_WARNING"/>
    <STRING id="STR_ID_VAPP_PHB_SELECT_RINGTONE"/>
    <STRING id="STR_ID_VAPP_PHB_DELETE_THE_TYPE"/>
    <STRING id="STR_ID_VAPP_PHB_TYPE_NAME"/>
    <STRING id="STR_ID_VAPP_PHB_NAME_MODIFIED"/>
    <STRING id="STR_ID_VAPP_PHB_ADN_FORBID"/>
    <STRING id="STR_ID_VAPP_PHB_NUMBER_TOO_LONG"/>    
    <STRING id="STR_ID_VAPP_PHB_DUPLICATE_TYPE"/>

    <!--Cui list-->

   // <STRING id="VAPP_PHB_STR_ALL_CONTACTS"/>
    <STRING id="STR_ID_VAPP_PHB_SELECT_A_CONTACT"/>

    <!--Common-->

    <STRING id="VAPP_PHB_STR_COMMA"/>
    <STRING id="VAPP_PHB_STR_COLON"/>
    <STRING id="STR_ID_VAPP_PHB_QUESTION"/>
    <STRING id="STR_ID_VAPP_PHB_LEFT_PARENTHESES"/>
    <STRING id="STR_ID_VAPP_PHB_RIGHT_PARENTHESES"/>
    <STRING id="VAPP_PHB_STR_DEFAULT"/>
    <STRING id="STR_ID_VAPP_PHB_TO"/>
    <STRING id="STR_ID_VAPP_PHB_TO_LOW"/>
    //<STRING id="STR_ID_VAPP_PHB_FROM"/>
    <STRING id="STR_ID_VAPP_PHB_FROM_LOW"/>
    <STRING id="STR_ID_VAPP_PHB_COPYING"/>
    <STRING id="STR_ID_VAPP_PHB_DELETING"/>
    <STRING id="STR_ID_VAPP_PHB_MAX_NUM_REACH"/>
    <STRING id="STR_ID_VAPP_PHB_MOVE_TO"/>

    <!--Vcard-->

    <STRING id="STR_ID_VAPP_VCARD"/>
    <STRING id="STR_ID_VAPP_CONTACT"/>
    <STRING id="STR_ID_VAPP_PHB_VCARD_DETAILS"/>

    <!--Others-->

    <STRING id="STR_ID_VAPP_PHB_NO_CONTACT"/>
    <STRING id="STR_ID_VAPP_PHB_INVALID_LOCATION"/>
    <STRING id="STR_ID_VAPP_PHB_SLIM_EDIT_PHOTO_POPUP"/>

    <!--Image ID----------------------------------------------------------------------------------------->

    <THEME>
        <IMAGE id="IMG_ID_VAPP_CONTACT" desc="IMG_ID_VAPP_CONTACT">RES_IMG_ROOT"\\\\"__MMI_MAINMENU_ICON_DEFAULT_PATH__"\\\\Contact.png"</IMAGE>
        <IMAGE id="VAPP_PHB_IMG_DEFAULT_CONTACT" desc="VAPP_PHB_IMG_DEFAULT_CONTACT"></IMAGE>
        <IMAGE id="IMG_ID_VAPP_PHB_MORE_ACTION" desc="IMG_ID_VAPP_PHB_MORE_ACTION"></IMAGE>
        <IMAGE id="IMG_ID_VAPP_PHB_BLOCK_NUMBER" desc="IMG_ID_VAPP_PHB_BLOCK_NUMBER"></IMAGE>
#ifdef __MMI_MULTI_VCARD__
        <IMAGE id="VAPP_PHB_VCARD_LEFT_ARROW" desc="VAPP_PHB_VCARD_LEFT_ARROW"></IMAGE>
        <IMAGE id="VAPP_PHB_VCARD_RIGHT_ARROW" desc="VAPP_PHB_VCARD_RIGHT_ARROW"></IMAGE>
#endif
        //<IMAGE id="VAPP_PHB_VCARD_TITLE_BG" desc="VAPP_PHB_VCARD_TITLE_BG"></IMAGE>
    </THEME>

    #define ROOT_PATH RES_IMG_ROOT"\\\\Contact\\\\"
    <IMAGE id="VAPP_PHB_IMG_TAB_CLOG">          ROOT_PATH"TabIcon\\\\CallLog.png" </IMAGE>
    <IMAGE id="VAPP_PHB_IMG_TAB_CONTACT">       ROOT_PATH"TabIcon\\\\Contact.png" </IMAGE>
    <IMAGE id="VAPP_PHB_IMG_TAB_DIALPAD">       ROOT_PATH"TabIcon\\\\Dialpad.png" </IMAGE>
    <IMAGE id="VAPP_PHB_IMG_TAB_MESSAGE">       ROOT_PATH"TabIcon\\\\Message.png" </IMAGE>
    <IMAGE id="VAPP_PHB_IMG_TAB_PROFILE">       ROOT_PATH"TabIcon\\\\Profile.png" </IMAGE>
#ifdef __MMI_PHB_CALLER_GROUP__ 
    <IMAGE id="VAPP_PHB_IMG_TAB_GROUP">         ROOT_PATH"TabIcon\\\\GroupContact.png" </IMAGE>
#endif
#ifdef __MMI_SNS_CONTACTS__
    <IMAGE id="VAPP_PHB_IMG_TAB_LOCAL">         RES_IMG_ROOT"\\\\SNS\\\\TabIcon\\\\Local.png" </IMAGE>
    <IMAGE id="VAPP_PHB_IMG_TAB_SNS">           RES_IMG_ROOT"\\\\SNS\\\\TabIcon\\\\SNS.png" </IMAGE>
#endif /* __MMI_SNS_CONTACTS__ */

    <IMAGE id="VAPP_PHB_IMG_CMD_ADD_CONTACT">   ROOT_PATH"ToolbarIcon\\\\Add_Contact.png" </IMAGE>
#ifdef __MMI_PHB_CALLER_GROUP__     
    <IMAGE id="VAPP_PHB_IMG_CMD_ADD_GROUP">     ROOT_PATH"ToolbarIcon\\\\Add_Group.png" </IMAGE>
    <IMAGE id="VAPP_PHB_IMG_CMD_ADD_MEMBER">    ROOT_PATH"ToolbarIcon\\\\Add_Member.png" </IMAGE>
#endif
#if !defined (__MMI_CONTACT_SLIM__)
    <IMAGE id="VAPP_PHB_IMG_CMD_CARD">          ROOT_PATH"ToolbarIcon\\\\Card.png" </IMAGE>
#endif
#ifdef __MMI_PHB_CALLER_GROUP__ 
    <IMAGE id="VAPP_PHB_IMG_CMD_DELETE_GROUP">  ROOT_PATH"ToolbarIcon\\\\Delete_Group.png" </IMAGE>
    <IMAGE id="VAPP_PHB_IMG_CMD_EDIT_GROUP">    ROOT_PATH"ToolbarIcon\\\\Edit_Group.png" </IMAGE>
    <IMAGE id="VAPP_PHB_IMG_CMD_EDIT_MEMBER">   ROOT_PATH"ToolbarIcon\\\\Edit_Member.png" </IMAGE>
    <IMAGE id="VAPP_PHB_IMG_CMD_GROUP">         ROOT_PATH"ToolbarIcon\\\\Group.png" </IMAGE>
#endif
#if !defined (__MMI_CONTACT_SLIM__)
    <IMAGE id="VAPP_PHB_IMG_CMD_MESSAGE">       ROOT_PATH"ToolbarIcon\\\\Message.png" </IMAGE>
#endif
#ifdef __MMI_SNS_CONTACTS__
    <IMAGE id="VAPP_PHB_IMG_CMD_LINK">          RES_IMG_ROOT"\\\\SNS\\\\ToolbarIcon\\\\Link.png" </IMAGE>
    <IMAGE id="VAPP_PHB_IMG_CMD_UNLINK">        RES_IMG_ROOT"\\\\SNS\\\\ToolbarIcon\\\\Unlink.png" </IMAGE>
#endif /* __MMI_SNS_CONTACTS__ */

    <IMAGE id="IMG_ID_VAPP_PHB_PHONE"> RES_IMG_ROOT"\\\\Common\\\\ListIcon\\\\System.png" </IMAGE>
    <IMAGE id="IMG_ID_VAPP_PHB_LIST_DELETE_CMD">   RES_IMG_ROOT"\\\\Common\\\\Button\\\\Delete.png" </IMAGE>
    <IMAGE id="IMG_ID_FMGR_LIST_ICON_FILE_TYPE_VCARD"> RES_IMG_ROOT"\\\\Message\\\\ListIcon\\\\Vcard_File.png" </IMAGE>

    <MENU id="MENU_ID_VAPP_VCARD_OPTION" type="OPTION" str="STR_GLOBAL_OPTIONS">
        <MENUITEM_ID>MENU_ID_VAPP_VCARD_OPEN</MENUITEM_ID>
    </MENU>
    <MENUITEM id="MENU_ID_VAPP_VCARD_OPEN" str="STR_GLOBAL_OPEN"/>

    <FILE_TYPES>
    #if defined(__COSMOS_MMI__)
        <FILE_TYPE type_id="FMGR_TYPE_VCF" extension="VCF" small_icon="IMG_ID_FMGR_LIST_ICON_FILE_TYPE_VCARD" large_icon="IMG_ID_FMGR_LIST_ICON_FILE_TYPE_VCARD" option="MENU_ID_VAPP_VCARD_OPTION"/>
#ifdef __MMI_MULTI_VCARD__
        <FILE_OPTION_HDLR option="MENU_ID_VAPP_VCARD_OPEN" handler="vapp_phb_vcard_view_from_fmgr"/>
#endif
    #endif
    </FILE_TYPES>

</APP>

