#include "mmi_features.h"
#include "custresdef.h"
#include "custom_mmi_default_value.h"
#include "../../../venusmmi/app/Cosmos/setting/res/vapp_setting_memory.h"

<?xml version="1.0" encoding="UTF-8"?>

<APP id="VAPP_SETTING"
     package_name="native.mtk.setting"
     name="STR_ID_APP_SETTINGS"
     img="IMG_ID_APP_SETTING_TITLE"
     launch="vapp_setting_launch" type="venus">
    <MEMORY cui=SETTINGS_MAX_COMMON_UI_MEMORY
        heap="VAPP_SETTINGS_MAX_HEAP" 
        extra_base= VAPP_SETTINGS_MAX_EXTRA_BASE
        fg = VAPP_SETTINGS_MAX_FG_MEMORY
        vrt_mem_factor="2.0"
        inc="../../../venusmmi/app/Cosmos/setting/res/vapp_setting_memory.h,CloudSrvGprot.h"/>  

    <APPCONCURRENT concurrent="VAPP_SETTING, SRV_VENUS_THEME"/>

    <STRING id = "STR_ID_APP_SETTINGS"/>  

    // Main menu
    // Caption
    <STRING id = "STR_ID_VAPP_SETTING_PERSONAL_CAPTION"/>
    <STRING id = "STR_ID_VAPP_SETTING_SYSTEM_CAPTION"/>
    <STRING id = "STR_ID_VAPP_SETTING_APPLICATIONS_CAPTION"/>

	// Menu
    <STRING id = "STR_ID_VAPP_SETTING_MULTI_SIM_SETTING"/>  
    <STRING id = "STR_ID_VAPP_SETTING_NETWORK_CONNECTIVITY"/>
    <STRING id = "STR_ID_VAPP_SETTING_SOUND_SETTING"/>
	//<STRING id = "STR_ID_VAPP_SETTING_IMEV3_SETTING"/>
    <STRING id = "STR_ID_VAPP_SETTING_CALL_SETTING"/>    
    //<STRING id = "STR_ID_VAPP_SETTING_CONTACT_SETTING"/>
    <STRING id = "STR_ID_VAPP_SETTING_MESSAGE_SETTING"/>    
    <STRING id = "STR_ID_VAPP_SETTING_DISPLAY_SETTING"/>
    <STRING id = "STR_ID_VAPP_SETTING_SECURITY_SETTING"/>
    <STRING id = "STR_ID_VAPP_SETTING_DATE_TIME_SETTING"/>    
    <STRING id = "STR_ID_VAPP_SETTING_LANGUAGE_INPUT"/>
    //<STRING id = "STR_ID_VAPP_SETTING_USAGE"/>    
    <STRING id = "STR_ID_VAPP_SETTING_FACTORY_RESTORE"/>   
    <STRING id = "STR_ID_VAPP_SETTING_THEME"/>
    <STRING id = "STR_ID_VAPP_SETTING_ADVANCED_SETTING"/>    
    //<STRING id = "STR_ID_VAPP_SETTING_SERVICE_UPDATE"/> 


    <IMAGE id = "IMG_ID_VAPP_SETTING_DUAL_SIM_SETTING">RES_IMG_ROOT"\\\\Settings\\\\sim.png"</IMAGE>;
    <IMAGE id = "IMG_ID_VAPP_SETTING_NETWORK_CONNECTIVITY">RES_IMG_ROOT"\\\\Settings\\\\network.png"</IMAGE>;
    <IMAGE id = "IMG_ID_VAPP_SETTING_SOUND_SETTING">RES_IMG_ROOT"\\\\Settings\\\\profile.png"</IMAGE>;
    <IMAGE id = "IMG_ID_VAPP_SETTING_CALL_SETTING">RES_IMG_ROOT"\\\\Settings\\\\call.png"</IMAGE>;
    <IMAGE id = "IMG_ID_VAPP_SETTING_CONTACT_SETTING">RES_IMG_ROOT"\\\\Settings\\\\contact.png"</IMAGE>;
    <IMAGE id = "IMG_ID_VAPP_SETTING_MESSAGE_SETTING">RES_IMG_ROOT"\\\\Settings\\\\message.png"</IMAGE>;
#if defined(__SOCIAL_NETWORK_SUPPORT__) || defined(__MMI_SSO__)
    <IMAGE id = "IMG_ID_VAPP_SETTING_SNS_SETTING">RES_IMG_ROOT"\\\\Settings\\\\sns.png"</IMAGE>;  
#endif
    <IMAGE id = "IMG_ID_VAPP_SETTING_DISPLAY_SETTING">RES_IMG_ROOT"\\\\Settings\\\\display.png"</IMAGE>;
#if !defined(__LOW_COST_SUPPORT_COMMON__)
    <IMAGE id = "IMG_ID_VAPP_SETTING_SCHEDULE_POWER">RES_IMG_ROOT"\\\\Settings\\\\power.png"</IMAGE>;
#endif // #if !defined(__LOW_COST_SUPPORT_COMMON__)
    <IMAGE id = "IMG_ID_VAPP_SETTING_SECURITY_SETTING">RES_IMG_ROOT"\\\\Settings\\\\security.png"</IMAGE>;
    <IMAGE id = "IMG_ID_VAPP_SETTING_DATE_TIME_SETTING">RES_IMG_ROOT"\\\\Settings\\\\date.png"</IMAGE>;
    <IMAGE id = "IMG_ID_VAPP_SETTING_LANGUAGE_INPUT">RES_IMG_ROOT"\\\\Settings\\\\language.png"</IMAGE>;
   // <IMAGE id = "IMG_ID_VAPP_SETTING_PEN_CALIBRATION">RES_IMG_ROOT"\\\\Settings\\\\PenCalibration.png"</IMAGE>;
    <IMAGE id = "IMG_ID_VAPP_SETTING_USAGE">RES_IMG_ROOT"\\\\Settings\\\\sim.png"</IMAGE>;
  //  <IMAGE id = "IMG_ID_VAPP_SETTING_FACTORY_RESTORE">RES_IMG_ROOT"\\\\Settings\\\\RestoreFactory.png"</IMAGE>;
#ifdef __MMI_SETTING_THEME_SETTINGS__    
    <IMAGE id = "IMG_ID_VAPP_SETTING_THEME">RES_IMG_ROOT"\\\\Settings\\\\Theme.png"</IMAGE>;
#else
    <IMAGE id = "IMG_ID_VAPP_SETTING_WALLPAPER">RES_IMG_ROOT"\\\\Settings\\\\Wallpaper.png"</IMAGE>;  
#endif       
    <IMAGE id = "IMG_ID_VAPP_SETTING_ADVANCED_SETTING">RES_IMG_ROOT"\\\\Settings\\\\AdvancedSetting.png"</IMAGE>;

    // Dual SIM setting
    
    #ifdef __MMI_UART_SETTING__
        <STRING id = "STR_ID_VAPP_SETTING_UART_SETTING"/>
    #else
    <STRING id = "STR_ID_VAPP_SETTING_SET_PRIMARY_CARD"/>
    #endif //__MMI_UART_SETTING__
    //<STRING id = "STR_ID_VAPP_SETTING_SET_PRIMARY_CARD_SIM1"/>
    //<STRING id = "STR_ID_VAPP_SETTING_SET_PRIMARY_CARD_SIM2"/>
   // #ifdef __MMI_UART_SETTING__    
       // <STRING id = "STR_ID_VAPP_SETTING_SET_PRIMARY_CARD_SIM3"/>
       // <STRING id = "STR_ID_VAPP_SETTING_SET_PRIMARY_CARD_SIM4"/>
    //#endif //__MMI_UART_SETTING__
    <STRING id = "STR_ID_VAPP_SETTING_DISPLAY_BOOT_UP_MODE"/>
    <STRING id = "STR_ID_VAPP_SETTING_SIM_NAME"/>
    <STRING id = "STR_ID_VAPP_SETTING_EDIT_SIM_NAME"/>    
    <STRING id = "STR_ID_VAPP_SETTING_SIM_NAME_LEFT_BRACKET"/>
    <STRING id = "STR_ID_VAPP_SETTING_SIM_NAME_RIGHT_BRACKET"/>    

    // Date time setting
    <STRING id = "STR_ID_VAPP_SETTING_HOME_CITY"/>
    <STRING id = "STR_ID_VAPP_SETTING_DATE_SETTINGS"/>
    <STRING id = "STR_ID_VAPP_SETTING_TIME_SETTINGS"/>
    <STRING id = "STR_ID_VAPP_SETTING_DATE_FORMAT"/>
    <STRING id = "STR_ID_VAPP_SETTING_DATE_SEPERATOR"/>
    <STRING id = "STR_ID_VAPP_SETTING_24_HOUR_TIME"/>
    <STRING id = "STR_ID_VAPP_SETTING_DAYLIGHT_SAVING_TIME"/>
    
    
    <STRING id = "STR_ID_VAPP_SETTING_FORMAT_DD_MM_YYYY"/>
    <STRING id = "STR_ID_VAPP_SETTING_FORMAT_MM_DD_YYYY"/>
    <STRING id = "STR_ID_VAPP_SETTING_FORMAT_YYYY_MM_DD"/>
    <STRING id = "STR_ID_VAPP_SETTING_SEPERATOR_DOT"/>
    <STRING id = "STR_ID_VAPP_SETTING_SEPERATOR_COLON"/>
    <STRING id = "STR_ID_VAPP_SETTING_SEPERATOR_SLOPE"/>
    <STRING id = "STR_ID_VAPP_SETTING_SEPERATOR_LINE"/>
    // Flight mode
    <STRING id = "STR_ID_VAPP_SETTING_FLIGHT_MODE"/>

    // For dual SIM network setting
    #if 0
    <STRING id = "STR_ID_VAPP_SETTING_SIM1_SWITCH"/>
    <STRING id = "STR_ID_VAPP_SETTING_SIM1_SWITCH_HINT"/>
    <STRING id = "STR_ID_VAPP_SETTING_SIM2_SWITCH"/>
    <STRING id = "STR_ID_VAPP_SETTING_SIM2_SWITCH_HINT"/>   
    #endif
#if (defined(__SIM_HOT_SWAP_SUPPORT__) || defined(__SIM_RECOVERY_ENHANCEMENT__))
    <RECEIVER id="EVT_ID_SRV_SIM_CTRL_EVENT_DETECTED" proc="vapp_sim_hot_swap_recovery_srv_proc"/>
#endif
    

    // NFC
#ifdef __NFC_SUPPORT__
    <STRING id = "STR_ID_VAPP_NFC_SWITCH"/>
    <STRING id = "STR_ID_VAPP_NFC_SWITCH_ON_FAIL"/>
    <STRING id = "STR_ID_VAPP_NFC_SWITCH_OFF_FAIL"/>
    
    <CACHEDATA type="byte" id="NVRAM_EF_NFC_SETTING_LID" restore_flag="TRUE">
        <DEFAULT_VALUE> [0x01] </DEFAULT_VALUE>
        <DESCRIPTION> nfc setting </DESCRIPTION>
    </CACHEDATA>
#endif // __NFC_SUPPORT__

    // Network setting group caption
    <STRING id = "STR_ID_VAPP_SETTING_CONNECTIVITY_SETTINGS"/>
    <STRING id = "STR_ID_VAPP_SETTING_CELLULAR_NETWORK_SETTINGS"/>

    // CTA query screen
    <STRING id = "STR_ID_VAPP_SETTING_NO_MOBILE_NETWORK"/>
    <STRING id = "STR_ID_VAPP_SETTING_CHOOSE_SIM"/>

    // CTA manual network selection query screen
    <STRING id = "STR_ID_VAPP_SETTING_SET_SIM1_NETWORK"/>

    // Display setting
    <STRING id = "STR_ID_VAPP_SETTING_WALLPAPER_SETTING"/>
    <STRING id = "STR_ID_VAPP_SETTING_WALLPAPER_HOME_SCREEN"/>    
    <STRING id = "STR_ID_VAPP_SETTING_WALLPAPER_LOCK_SCREEN"/>  
#if 0    
    <STRING id = "STR_ID_VAPP_SETTING_WALLPAPER_MAIN_MENU"/>   
#endif    
    <STRING id = "STR_ID_VAPP_SETTING_WALLPAPER_SYSTEM"/>
    <STRING id = "STR_ID_VAPP_SETTING_WALLPAPER_GALLERY"/>
    <STRING id = "STR_ID_VAPP_SETTING_WALLPAPER_PICTURE"/>
    <STRING id = "STR_ID_VAPP_SETTING_WALLPAPER_VIDEO"/>
    //<STRING id = "STR_ID_VAPP_SETTING_WALLPAPER_SYSTEM_PICTURE"/>
    <STRING id = "STR_ID_VAPP_SETTING_WALLPAPER_SYSTEM_VIDEO"/>
    //<STRING id = "STR_ID_VAPP_SETTING_WALLPAPER_GALLERY_PICTURE"/>
    //<STRING id = "STR_ID_VAPP_SETTING_WALLPAPER_GALLERY_VIDEO"/>
    //<STRING id = "STR_ID_VAPP_SETTING_WALLPAPER_CAMERA"/>
    <STRING id = "STR_ID_VAPP_SETTING_WALLPAPER_LIVE"/>
    <STRING id = "STR_ID_VAPP_SETTING_WALLPAPER_STATIC"/>
    <STRING id = "STR_ID_VAPP_SETTING_WALLPAPER_SET_SUCCESSFULLY"/>
    <STRING id = "STR_ID_VAPP_SETTING_WALLPAPER_FILE_TOO_LARGE"/>
    //<STRING id = "STR_ID_SETTING_BRIGHTNESS"/>
    <STRING id = "STR_ID_VAPP_WALLPAPER_SETTING_CONFIRM"/>
    <STRING id = "STR_ID_VAPP_WALLPAPER_SETTING_CONTINUE"/>

    <EVENT id="EVT_ID_VAPP_WALLPAPER_SETTING_EXIT" type="SENDER"/>

	// Power On/Off animation
    <STRING id = "STR_ID_VAPP_SETTING_PWR_ON_VIDEO"/>
    <STRING id = "STR_ID_VAPP_SETTING_PWR_OFF_VIDEO"/>
    <STRING id = "STR_ID_VAPP_SETTING_PWR_ON_VIDEO_TOO_LONG"/>
    <STRING id = "STR_ID_VAPP_SETTING_PWR_OFF_VIDEO_TOO_LONG"/>
    
    #define ROOT_PATH RES_IMG_ROOT"\\\\Wallpaper\\\\WP_Live\\\\thumbnail\\\\"
    <IMAGE id="IMG_ID_VAPP_LIVE_WALLPAPER_CONTENT_PROVIDER_THUMB_1">ROOT_PATH"wp_thumb_static_1.jpg"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_LIVE_WALLPAPER_CONTENT_PROVIDER_THUMB_2">ROOT_PATH"wp_thumb_static_2.jpg"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_LIVE_WALLPAPER_CONTENT_PROVIDER_THUMB_3">ROOT_PATH"wp_thumb_static_3.jpg"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_LIVE_WALLPAPER_CONTENT_PROVIDER_THUMB_4">ROOT_PATH"wp_thumb_static_4.jpg"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_LIVE_WALLPAPER_CONTENT_PROVIDER_THUMB_5">ROOT_PATH"wp_thumb_static_5.jpg"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_LIVE_WALLPAPER_CONTENT_PROVIDER_THUMB_6">ROOT_PATH"wp_thumb_static_6.jpg"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_LIVE_WALLPAPER_CONTENT_PROVIDER_THUMB_7">ROOT_PATH"wp_thumb_static_7.jpg"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_LIVE_WALLPAPER_CONTENT_PROVIDER_THUMB_8">ROOT_PATH"wp_thumb_static_8.jpg"</IMAGE>    
    // Wallpaper in theme
    <THEME>
        <IMAGE id = "IMG_ID_APP_SETTING_TITLE" desc = "Main menu setting icon">CUST_IMG_PATH_ROOT"\\\\MainLCD\\\\Default\\\\"__MMI_MAINMENU_ICON_DEFAULT_PATH__"\\\\Setting.png"</IMAGE>
	    <IMAGE id = "IMG_ID_THEME_WALLPAPER_0" desc = "Home screen wallpaper in theme"/>
	    <IMAGE id = "IMG_ID_THEME_WALLPAPER_THUMB_0" desc = "Home screen wallpaper thumbnail in theme"/>	    
    </THEME>


    

#ifdef __MMI_VUI_HOMESCREEN_VIDEO_WALLPAPER__
    // Video ID
    <CACHEDATA type="byte" id="NVRAM_SETTING_PWR_ON_VIDEO" restore_flag="TRUE">
        <DEFAULT_VALUE> [0x00] </DEFAULT_VALUE>
        <DESCRIPTION> Video setting Pwr on screen </DESCRIPTION>
    </CACHEDATA>
    
    <CACHEDATA type="byte" id="NVRAM_SETTING_PWR_OFF_VIDEO" restore_flag="TRUE">
        <DEFAULT_VALUE> [0x00] </DEFAULT_VALUE>
        <DESCRIPTION> Video setting Pwr off screen </DESCRIPTION>
    </CACHEDATA>
#endif    
    // Wallpaper resource type
   
#ifdef __MMI_VUI_HOMESCREEN_VIDEO_WALLPAPER__
     <CACHEDATA type="byte" id="NVRAM_SETTING_PWR_ON_VIDEO_RES_TYPE" restore_flag="TRUE">
        <DEFAULT_VALUE> [0x00] </DEFAULT_VALUE>
        <DESCRIPTION> Pwr on screen Video resource type </DESCRIPTION>
    </CACHEDATA>

    <CACHEDATA type="byte" id="NVRAM_SETTING_PWR_OFF_VIDEO_RES_TYPE" restore_flag="TRUE">
        <DEFAULT_VALUE> [0x00] </DEFAULT_VALUE>
        <DESCRIPTION> Pwr off screen Video resource type </DESCRIPTION>
    </CACHEDATA>
#endif

#if 0
    <CACHEDATA type="byte" id="NVRAM_SETTING_MENU_WALLPAPER_RES_TYPE" restore_flag="TRUE">
        <DEFAULT_VALUE> [0x00] </DEFAULT_VALUE>
        <DESCRIPTION> Main menu Wallpaper resource type </DESCRIPTION>
    </CACHEDATA>

    <CACHEDATA type="byte" id="NVRAM_SETTING_MENU_WALLPAPER" restore_flag="TRUE">
        <DEFAULT_VALUE> [0x00] </DEFAULT_VALUE>
        <DESCRIPTION> Main menu wallpaper setting </DESCRIPTION>
    </CACHEDATA>    
#endif    

    // Schedule power on/off
#if !defined(__LOW_COST_SUPPORT_COMMON__)
    <STRING id = "STR_ID_VAPP_SETTING_SCHEDULE_POWER_ON_OFF"/>    
    <STRING id = "STR_ID_VAPP_SETTING_SCHEDULE1"/> 
    <STRING id = "STR_ID_VAPP_SETTING_SCHEDULE2"/> 
    <STRING id = "STR_ID_VAPP_SETTING_SCHEDULE3"/> 
    <STRING id = "STR_ID_VAPP_SETTING_SCHEDULE4"/> 
    <STRING id = "STR_ID_VAPP_SETTING_SCHEDULE_POWER_SET_TIME"/>
    <STRING id = "STR_ID_VAPP_SETTING_SCHEDULE_POWER_ON"/>   
    <STRING id = "STR_ID_VAPP_SETTING_SCHEDULE_POWER_OFF"/>   
    <STRING id = "STR_ID_VAPP_SETTING_SCHEDULE_POWER_HINT"/>   
    <STRING id = "STR_ID_VAPP_SETTING_SCHEDULE_POWER_OFF_CONFIRM"/>   
    <STRING id = "STR_ID_VAPP_SETTING_SCHEDULE_POWER_SHUT_DOWN_NOW"/>
    <STRING id = "STR_ID_VAPP_SETTING_EDIT_SCHEDULE_POWER_ON"/>
    <STRING id = "STR_ID_VAPP_SETTING_EDIT_SCHEDULE_POWER_OFF"/>    
    <STRING id = "STR_ID_VAPP_SETTING_SCHEDULE_POWER_CONFLICT"/>   

    <TIMER id = "MMI_ALARM_ALERT_NOTIFYDURATION_TIMER"/>

    <RECEIVER id="EVT_ID_SRV_REMINDER_NOTIFY" proc="vapp_schedule_power_reminder_srv_proc"/>
#endif // #if !defined(__LOW_COST_SUPPORT_COMMON__)
    // Language
    <STRING id = "STR_ID_VAPP_SETTING_LANGUAGE"/>
    <STRING id = "STR_ID_VAPP_SETTING_LANGUAGE_STOP_APP_CONFIRM"/>
    <STRING id = "STR_ID_VAPP_SETTING_LANGUAGE_SWITCHING"/>
    <STRING id = "STR_ID_VAPP_SETTING_SUCCESSFUL"/>
    <STRING id = "STR_ID_VAPP_SETTING_FAILURE"/> 

    <EVENT id="EVT_ID_VAPP_LANGUAGE_CHANGED" type="SENDER"/>
    // Pen calibration
    <IMAGE id = "IMG_ID_VAPP_SETTING_PEN_CALIBRATION_TARGET">RES_IMG_ROOT"\\\\Settings\\\\PenCalibration"</IMAGE>;

    // Restore
    <STRING id = "STR_ID_VAPP_SETTING_RESTORE"/>
    <STRING id = "STR_ID_VAPP_SETTING_RESTORE_CONFIRM"/>    

    // Connection management
#ifdef __MMI_CBM_CONNECTION_MANAGER__
    <STRING id = "STR_ID_VAPP_SETTING_CNMGR_CONNECTION_MANAGEMENT"/>
    <STRING id = "STR_ID_VAPP_SETTING_CNMGR_SETTING_HINT"/>
    <STRING id = "STR_ID_VAPP_SETTING_CNMGR_NO_CONNECTION"/>
    <STRING id = "STR_ID_VAPP_SETTING_CNMGR_DISCONNECT_ALL"/>
    <STRING id = "STR_ID_VAPP_SETTING_CNMGR_DISCONNECT"/>
    <STRING id = "STR_ID_VAPP_SETTING_CNMGR_DISCONEECT_ALL_CONFIRM"/>
    <STRING id = "STR_ID_VAPP_SETTING_CNMGR_DISCONEECT_CONFIRM"/>
    <STRING id = "STR_ID_VAPP_SETTING_CNMGR_APN"/>
    <STRING id = "STR_ID_VAPP_SETTING_CNMGR_NUMBER"/>
    <STRING id = "STR_ID_VAPP_SETTING_CNMGR_TYPE"/>
    <STRING id = "STR_ID_VAPP_SETTING_CNMGR_CONNECTION_STATUS"/>
    <STRING id = "STR_ID_VAPP_SETTING_CNMGR_CONNECTION_TIME"/>
    <STRING id = "STR_ID_VAPP_SETTING_CNMGR_ALL_DATA_SIZE"/>
    <STRING id = "STR_ID_VAPP_SETTING_CNMGR_RECV_DATA_SIZE"/>
    <STRING id = "STR_ID_VAPP_SETTING_CNMGR_SENT_DATA_SIZE"/>
    <STRING id = "STR_ID_VAPP_SETTING_CNMGR_UPLOAD_RATE"/>
    <STRING id = "STR_ID_VAPP_SETTING_CNMGR_DOWNLOAD_RATE"/>
    <STRING id = "STR_ID_VAPP_SETTING_CNMGR_TYPE_CSD"/>
    <STRING id = "STR_ID_VAPP_SETTING_CNMGR_TYPE_DIALUP"/>
    <STRING id = "STR_ID_VAPP_SETTING_CNMGR_NO_TRANSFER"/>
    <STRING id = "STR_ID_VAPP_SETTING_CNMGR_TRANSFERRING"/>
    <STRING id = "STR_ID_VAPP_SETTING_CNMGR_DISCONNECTED"/>
    <STRING id = "STR_ID_VAPP_SETTING_CNMGR_DISCONNECTING"/>
#endif /* __MMI_CBM_CONNECTION_MANAGER__ */

#ifdef __NTPD_SUPPORT__
    // NTP
    <STRING id = "STR_ID_NTP_APP"/>
    <IMAGE  id = "IMG_ID_NTP_ICON"/>
    <STRING id = "STR_ID_VAPP_SETTING_NTP_TIME_AUTO_UPDATE"/>
    <STRING id = "STR_ID_VAPP_SETTING_NTP_ATOMIC_CLOCK"/>
    <STRING id = "STR_ID_VAPP_SETTING_NTP_SYSTEM_TIME"/>
    <STRING id = "STR_ID_VAPP_SETTING_NTP_SYNC_SYSTEM_TIME"/>
    <STRING id = "STR_ID_VAPP_SETTING_NTP_FAIL_INFO"/>
    <STRING id = "STR_ID_VAPP_SETTING_NTP_FAIL_INFO_SLIM"/>
    <STRING id = "STR_ID_VAPP_SETTING_NTP_PRESS_TO_UPDATE"/>
    <STRING id = "STR_ID_VAPP_SETTING_NTP_SYNCING_BACKGROUND"/>

    #define ROOT_PATH RES_IMG_ROOT"\\\\Contact\\\\\ToolbarIcon\\\\"
    <IMAGE id="IMG_ID_VAPP_NTP_TOOLBAR_SYNC">ROOT_PATH"Sync.png"</IMAGE>
    #define ROOT_PATH RES_THEME_ROOT"\\\\Theme1\\\\NTP\\\\"
    <IMAGE id="IMG_ID_VAPP_NTP_TAB_BG">ROOT_PATH"Background.9slice.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_NTP_PAGE_BG">ROOT_PATH"BG.9slice.png"</IMAGE>
#endif

#ifdef __LCD_COLOR_ENGINE_SUPPORT__
   // picture quality
    <STRING id = "STR_ID_VAPP_SETTING_PICTURE_QUALITY"/>
    <CACHEDATA type="byte" id="NVRAM_PICTURE_QUALITY_SETTING_LID" restore_flag="TRUE">
        <DEFAULT_VALUE> [0x01] </DEFAULT_VALUE>
        <DESCRIPTION> picture quality setting </DESCRIPTION>
    </CACHEDATA>
#endif   

#ifdef MOTION_SENSOR_SUPPORT
    // string
    <STRING id = "STR_ID_VAPP_SETTING_MOTION"/>
    <STRING id = "STR_ID_VAPP_SETTING_MOTION_SENSOR"/>
    <STRING id = "STR_ID_VAPP_SETTING_MOTION_ORIENTATION"/>
    <STRING id = "STR_ID_VAPP_SETTING_MOTION_FLIP_TO_MUTE_CALL"/>
    <STRING id = "STR_ID_VAPP_SETTING_MOTION_FLIP_TO_MUTE_ALARM"/>
    <STRING id = "STR_ID_VAPP_SETTING_MOTION_TAP_TAP_TO_RECORD"/>
    <STRING id = "STR_ID_VAPP_SETTING_MOTION_AUTO_SWITCH_DISPLAY_ORIENTATION"/>
    <STRING id = "STR_ID_VAPP_SETTING_MOTION_FLIP_PHONE_TO_MUTE_INCOMING_CALL"/>
    <STRING id = "STR_ID_VAPP_SETTING_MOTION_FLIP_PHONE_TO_MUTE_ALARM"/>
    <STRING id = "STR_ID_VAPP_SETTING_MOTION_START_TO_RECORD_SECRETLY_INCALL"/>

    // image
    <IMAGE  id = "IMG_ID_VAPP_SETTING_MOTION">RES_IMG_ROOT"\\\\Settings\\\\motion.png"</IMAGE>
#endif

    // NITZ
    <STRING id = "STR_ID_VAPP_SETTING_NITZ"/>
    <STRING id = "STR_ID_VAPP_SETTING_NITZ_ALWAYS_ASK"/>
    <STRING id = "STR_ID_VAPP_SETTING_NITZ_UPDATE_HINT"/>
    <STRING id = "STR_ID_VAPP_SETTING_NITZ_UPDATE_TEXT_PREVIEW"/>
    <STRING id = "STR_ID_VAPP_SETTING_NITZ_UPDATE_NCENTER_MAIN"/>
    
    <RECEIVER id="EVT_ID_SRV_NITZ_UPDATE_REQ" proc="vapp_nitz_update_hdlr"/>
    
    <CACHEDATA type="byte" id="NVRAM_SETTING_AUTOUPDATE_DT_TIME" restore_flag="TRUE" restore_id="@RESTORE_DEFAULT_AUTOUPDATE_TIME">
        <DEFAULT_VALUE> [FACTORY_RESTORE_DEFAULT_AUTOUPDATE_TIME_VALUE] </DEFAULT_VALUE>
        <DESCRIPTION> auto update date and time state </DESCRIPTION>
    </CACHEDATA>

    <CACHEDATA type="byte" id="RESTORE_DEFAULT_AUTOUPDATE_TIME">
        <DEFAULT_VALUE> [FACTORY_RESTORE_DEFAULT_AUTOUPDATE_TIME_VALUE] </DEFAULT_VALUE>
        <DESCRIPTION> Byte Cache </DESCRIPTION>
    </CACHEDATA>     

    <RECEIVER id="EVT_ID_SRV_MODE_SWITCH_FINISH_NOTIFY" proc="vapp_flight_mode_switch_finish_hdlr"/>    

    // Data lock
#ifdef __MMI_DATA_LOCK__
    <STRING id = "STR_ID_VAPP_SETTING_DATA_LOCK"/>
    <STRING id = "STR_ID_VAPP_SETTING_NETWORK_ROAMING"/>
#endif
#ifdef __MMI_PUSH_TURN_ON_OFF_SWITCH__
    <STRING id = "STR_ID_VAPP_SETTING_PUSH_LOCK"/>
    <STRING id = "STR_ID_VAPP_SETTING_PUSH_LOCK_QUERY"/>
    <RECEIVER id="EVT_ID_SRV_PUSH_SWITCH_NOTIFY" proc="vapp_push_switch_notify_hdlr"/>  
#endif
#if defined(__MONITOR_PAGE_DURING_TRANSFER__) //&& !defined(__LOW_COST_SUPPORT_COMMON__)
    <STRING id = "STR_ID_VAPP_SETTING_PCH_SETTING"/>
    <STRING id = "STR_ID_VAPP_SETTING_PCH_DATA_PREFER_CONFIRM"/>
    <STRING id = "STR_ID_VAPP_SETTING_PCH_DATA_PREFER"/>
    <STRING id = "STR_ID_VAPP_SETTING_PCH_CALL_PREFER"/>
#endif //#if defined(__MONITOR_PAGE_DURING_TRANSFER__) //&& !defined(__LOW_COST_SUPPORT_COMMON__)

#if defined(__MMI_VUI_HOMESCREEN_VIDEO_WALLPAPER__)
    #if !defined(__LOW_COST_SUPPORT_COMMON__)
    <STRING id = "STR_ID_SYS_VDO_NAME_01"/>
    <STRING id = "STR_ID_SYS_VDO_NAME_02"/>

    <IMAGE id="IMG_ID_SYS_VIDEO_THUMB_01">RES_IMG_ROOT"\\\\Wallpaper\\\\Wp_Vdo\\\\thumbnail\\\\wp_vdo_thumb_01.png"</IMAGE>
    <IMAGE id="IMG_ID_SYS_VIDEO_THUMB_02">RES_IMG_ROOT"\\\\Wallpaper\\\\Wp_Vdo\\\\thumbnail\\\\wp_vdo_thumb_02.png"</IMAGE>
    
    <MEDIA id="VDO_ID_SYS_MP4_01">RES_IMG_ROOT"\\\\Wallpaper\\\\Wp_Vdo\\\\wp_vdo_01.mp4"</MEDIA>
    <MEDIA id="VDO_ID_SYS_MP4_02">RES_IMG_ROOT"\\\\Wallpaper\\\\Wp_Vdo\\\\wp_vdo_02.mp4"</MEDIA>
    #endif
    <MEDIA id="VDO_ID_SYS_INVALID_VID"></MEDIA>
#endif

#if defined(__GSM_RAT__) && defined(__UMTS_RAT__)	
#if defined(__MMI_EM_NW_SERVICE_MODE_SELECTION__)
	  <STRING id="STR_ID_NETSET_SERVICE_SELECTION"/>
	  <STRING id="STR_ID_NETSET_ITEM_GSM"/>
	  <STRING id="STR_ID_NETSET_ITEM_WCDMA"/>
		<STRING id="STR_ID_NETSET_ITEM_TDSCDMA"/>
		<STRING id="STR_ID_NETSET_ITEM_ALL"/>
	
		<SCREEN id = "GRP_ID_NETSET_SERVICE_SELECTION"/>
		<SCREEN id = "SCR_ID_NETSET_SERVICE_SELECTION"/>
		<SCREEN id = "SCR_ID_NETSET_SET_RAT_PROGRESS"/>
		<SCREEN id = "SCR_ID_NETSET_RAT_QUERY"/>

#endif    
#endif    

#if defined(__MMI_EM_NW_GPRS_CONN__) && defined(__MMI_GPRS_FEATURES__)
	<SCREEN id = "SCR_ID_NETSET_SET_GPRS_PROGRESS"/>	

	<STRING id="STR_ID_NETSET_GPRS_CONNECTION"/>
	<STRING id="STR_ID_NETSET_GPRS_CONNECTION_ALWAYS"/>
	<STRING id="STR_ID_NETSET_GPRS_CONNECTION_WHENNEEDED"/>
	
	<MENUITEM id="MENU_ID_NETSET_GPRS_CONNECTION" str="STR_ID_NETSET_GPRS_CONNECTION"/>
#endif

</APP>
