#include "mmi_features.h"
#include "custresdef.h"
#include "custom_mmi_default_value.h"

<?xml version="1.0" encoding="UTF-8"?>

<APP id="VCUI_MOBILE_NW_SETTING"
     name="STR_ID_VAPP_MOBILE_NW_SETTING"
     type="venus">
    <MEMORY heap="400*1024"/> 
    <STRING id = "STR_ID_VAPP_MOBILE_NW_SETTING"/>  

    // Mobile network setting title & sub title
    <STRING id = "STR_ID_VAPP_SETTING_MOBILE_NETWORK_SETTING_TITLE"/>
#ifdef __OP01_3G__
    <STRING id = "STR_ID_VAPP_SETTING_MOBILE_NETWORK_SETTING_HINT_OP01_3G"/>
#else
    <STRING id = "STR_ID_VAPP_SETTING_MOBILE_NETWORK_SETTING_HINT"/>  
#endif
    
    // For  SIM network setting
    <STRING id = "STR_ID_VAPP_SETTING_SIM_NETWORK_OPERATOR"/>

    // GPRS connection settings
#if defined(__MMI_GPRS_FEATURES__) && !defined(__MMI_EM_NW_GPRS_CONN__)
    <STRING id = "STR_ID_VAPP_SETTING_SIM_GPRS_CONNECTION"/>
    <STRING id = "STR_ID_VAPP_SETTING_GPRS_CONNECTION_WHEN_NEEDED"/>
    <STRING id = "STR_ID_VAPP_SETTING_GPRS_CONNECTION_ALWAYS_CONNECT"/>
#endif /* defined(__MMI_GPRS_FEATURES__) && !defined(__MMI_EM_NW_GPRS_CONN__) */
    //#endif
    
    // HSPA switch
    <STRING id = "STR_ID_VAPP_SETTING_HSPA_SWITCH"/>
    <STRING id = "STR_ID_VAPP_SETTING_HSPA_SWITCH_FAILED"/>

    // Network selection settings
    <STRING id = "STR_ID_VAPP_SETTING_AUTO_SELECT"/>    
    <STRING id = "STR_ID_VAPP_SETTING_AUTO_SELECT_NETWORK"/>
    <STRING id = "STR_ID_VAPP_SETTING_NETWORK_SERVICE_MODE"/>
    <STRING id = "STR_ID_VAPP_SETTING_GSM_WCDMA_AUTO"/>
    
    <STRING id = "STR_ID_VAPP_SETTING_AUTO_SELECTION_PAGE_HINT"/>
    <STRING id = "STR_ID_VAPP_SETTING_MANUAL_REFRESH_HINT"/>
    <STRING id = "STR_ID_VAPP_SETTING_AVAILABLE_NETWORK"/>
    <STRING id = "STR_ID_VAPP_SETTING_SEARCHING_AVAILABLE_NETWORKS"/>
    <STRING id = "STR_ID_VAPP_SETTING_CONNECTING"/>
    <STRING id = "STR_ID_VAPP_SETTING_FAILED_TO_CONNECT"/>
    <STRING id = "STR_ID_VAPP_SETTING_SWITCH_SELECTION_MODE_FAILED"/>
    <STRING id = "STR_ID_VAPP_SETTING_SWITCH_SERVICE_MODE_FAILED"/>
    <STRING id = "STR_ID_VAPP_SETTING_RETRY"/>

    <IMAGE id = "IMG_ID_VAPP_SETTING_HOME_PLMN">RES_IMG_ROOT"\\\\Network\\\\Home.png"</IMAGE>; 
    <IMAGE id = "IMG_ID_VAPP_SETTING_HOME_PLMN_SELECTED">RES_IMG_ROOT"\\\\Network\\\\Home_S.png"</IMAGE>; 
    <IMAGE id = "IMG_ID_VAPP_SETTING_UNKNOWN_PLMN">RES_IMG_ROOT"\\\\Network\\\\Doubt.png"</IMAGE>;
    <IMAGE id = "IMG_ID_VAPP_SETTING_UNKNOWN_PLMN_SELECTED">RES_IMG_ROOT"\\\\Network\\\\Doubt_S.png"</IMAGE>;
    <IMAGE id = "IMG_ID_VAPP_SETTING_FORBIDDEN_PLMN">RES_IMG_ROOT"\\\\Network\\\\Forbid.png"</IMAGE>;
    <IMAGE id = "IMG_ID_VAPP_SETTING_FORBIDDEN_PLMN_SELECTED">RES_IMG_ROOT"\\\\Network\\\\Forbid_S.png"</IMAGE>;

    // preferred network setting 
#if !defined(__LOW_COST_SUPPORT_COMMON__)
    <STRING id = "STR_ID_VAPP_SETTING_PREFERRED_NETWORK"/>
    <STRING id = "STR_ID_VAPP_SETTING_PREFERRED_NETWORK_HINT"/>

    <STRING id = "STR_ID_VAPP_SETTING_NO_PREFERRED_NETWORK"/>
    <STRING id = "STR_ID_VAPP_SETTING_CHANGE_PRIORITY"/>
    <STRING id = "STR_ID_VAPP_SETTING_ADD_FROM_PREDEFINED_LIST"/>
    <STRING id = "STR_ID_VAPP_SETTING_CREATE_NEW_NETWORK"/>
    <STRING id = "STR_ID_VAPP_SETTING_DELETE_NETWORKS"/>
    <STRING id = "STR_ID_VAPP_SETTING_DELETE_CONFIRM"/>
    <STRING id = "STR_ID_VAPP_SETTING_DELETING"/>
    <STRING id = "STR_ID_VAPP_SETTING_ADDING"/>
    <STRING id = "STR_ID_VAPP_SETTING_CANNOT_ADD_MORE_NETWORK"/>
    <STRING id = "STR_ID_VAPP_SETTING_INVALID_MCCMNC"/>
    <IMAGE id="IMG_ID_VAPP_SETTING_CHANGE_PRIORITY">RES_IMG_ROOT"\\\\Settings\\\\ToolbarIcon\\\\ChangePriority.png"</IMAGE>
#endif //#if !defined(__LOW_COST_SUPPORT_COMMON__)

</APP>
