#include "custresdef.h"

<?xml version="1.0" encoding="UTF-8"?>

<APP id="VCUI_PEN_CALIBRATION" name="STR_ID_VAPP_PEN_CALIBRATION" type="venus">
    <MEMORY base="1024*100" />
    <STRING id = "STR_ID_VAPP_PEN_CALIBRATION"/>
    <STRING id = "STR_ID_VAPP_PEN_CALIBRATION_WELCOME_STRING"/>
    <STRING id = "STR_ID_VAPP_PEN_CALIBRATION_POINT1_STRING"/>
    <STRING id = "STR_ID_VAPP_PEN_CALIBRATION_POINT2_STRING"/>
    <STRING id = "STR_ID_VAPP_PEN_CALIBRATION_POINT3_STRING"/>
    <STRING id = "STR_ID_VAPP_PEN_CALIBRATION_SUCCESS_INFO"/>
    <STRING id= "STR_ID_VAPP_DL_CALI_DATA_INVALID"/>
</APP>