#include "CustomCfg.h"
#ifdef FIRST_PASS
#include "BuildCfg.h"
#endif
#include "MMI_features.h"
#include "MMIDataType.h"
#include "lcd_sw_inc.h"
#include "MMI_features_camcorder.h"
#include "custresdef.h"

#if defined(__VAPP_CAMCO_EXPRESS__)

<?xml version="1.0" encoding="UTF-8"?>

<APP id="VCUI_STANDARD_CAMERA" name="STR_ID_VCUI_CAMERA" type="venus">
    <MEMORY heap= "VAPP_CAMCO_UI_MEM" fg="CAMCO_PREVIEW_LAYER_SIZE + total(SRV_MDI_CAMERA_ONLY_CAP_LCD)" inc="vapp_camco_express_gprot.h,vfx_sys_config.h"/>
</APP>

<APP id="VCUI_STANDARD_RECORDER" name="STR_ID_VCUI_RECORDER" type="venus">
    <MEMORY heap= "VAPP_CAMCO_UI_MEM" extra_base="base(SRV_MDI_VDOREC_CIF)" fg="CAMCO_PREVIEW_LAYER_SIZE + fg(SRV_MDI_VDOREC_CIF)" inc="vapp_camco_express_gprot.h,vfx_sys_config.h"/>
</APP>

<APP id="VCUI_SLIM_CAMERA" name="STR_ID_VCUI_SLIM_CAMERA" type="venus">
    <MEMORY heap= "VAPP_CAMCO_UI_MEM" fg="CAMCO_PREVIEW_LAYER_SIZE  + total(SRV_MDI_CAMERA_CAP_VGA_BELOW)" inc="vapp_camco_express_gprot.h,vfx_sys_config.h"/>
</APP>

<APP id="VAPP_CAMCO_D"  package_name="native.mtk.camcorder_dummy" name="STR_ID_VAPP_CAMCO_APP_NAME2" img = "MAIN_MENU_CAMCO_ICON2"  hidden_in_mainmenu="true" type="venus">
    <MEMORY heap= "VAPP_CAMCO_UI_MEM" fg="MMI_CAMCO_APP_MEM_SIZE + max(max(total(SRV_MDI_CAMERA_STANDARD), fg(SRV_MDI_VDOREC)), fg(SRV_MDI_VDOPLY_PREVIEW))" inc="vapp_camco_express_gprot.h,vfx_sys_config.h"/>

    #define CAMCO_OSD_PATH    RES_IMG_ROOT"\\\\Camcorder\\\\"

    <IMAGE id="MAIN_MENU_CAMCO_ICON2">RES_IMG_ROOT"\\\\Mainmenu_Icon\\\\Camera.png"</IMAGE>

</APP>

<APP id="VAPP_CAMCO"  package_name="native.mtk.camcorder" name="STR_ID_VAPP_CAMCO_APP_NAME" img = "MAIN_MENU_CAMCO_ICON" launch = "vapp_camco_launch" package_proc = "vapp_camco_package_proc" type="venus">


    <INCLUDE file = "PopulateRes.h"/>
    <INCLUDE file = "ImageViewerResDef.h"/>
    <INCLUDE file = "CustResDef.h"/>

    <MEMORY heap= "VAPP_CAMCO_UI_MEM" extra_base="max(base(SRV_MDI_VDOREC), base(SRV_MDI_VDOPLY_PREVIEW))" fg="MMI_CAMCO_APP_MEM_SIZE + max(max(total(SRV_MDI_CAMERA_STANDARD), fg(SRV_MDI_VDOREC)), fg(SRV_MDI_VDOPLY_PREVIEW))" inc="vapp_camco_express_gprot.h,vfx_sys_config.h" vrt_mem_factor="1.0f"/>

    <STRING id="STR_ID_VAPP_CAMCO_CAPMODE_ASD_SHOT"/>
    <STRING id="STR_ID_VAPP_CAMCO_CAPMODE_ZSD_SHOT"/>
    <STRING id="STR_ID_VAPP_CAMCO_CAPMODE_SMILE_SHOT"/>

    <STRING id="STR_ID_VAPP_CAMCO_SCENEMODE"/>
    <STRING id="STR_ID_VAPP_CAMCO_SCENEMODE_AUTO"/>
    <STRING id="STR_ID_VAPP_CAMCO_SCENEMODE_PORTRAIT"/>
    <STRING id="STR_ID_VAPP_CAMCO_SCENEMODE_LANDSCAPE"/>
    <STRING id="STR_ID_VAPP_CAMCO_SCENEMODE_NIGHT"/>
    <STRING id="STR_ID_VAPP_CAMCO_SCENEMODE_SPORT"/>
    <STRING id="STR_ID_VAPP_CAMCO_SCENEMODE_DOCUMENT"/>
    <STRING id="STR_ID_VAPP_CAMCO_SCENEMODE_ANTI_SHAKE"/>

    <STRING id="STR_ID_VAPP_CAMCO_CAPSIZE"/>
    <STRING id="STR_ID_VAPP_CAMCO_CAPSIZE_WALLPAPER"/>
    <STRING id="STR_ID_VAPP_CAMCO_CAPSIZE_VGA"/>
    <STRING id="STR_ID_VAPP_CAMCO_CAPSIZE_1MP"/>
    <STRING id="STR_ID_VAPP_CAMCO_CAPSIZE_2MP"/>
    <STRING id="STR_ID_VAPP_CAMCO_CAPSIZE_3MP"/>
    <STRING id="STR_ID_VAPP_CAMCO_CAPSIZE_4MP"/>
    <STRING id="STR_ID_VAPP_CAMCO_CAPSIZE_5MP"/>

    <STRING id="STR_ID_VAPP_CAMCO_FLASH"/>
    <STRING id="STR_ID_VAPP_CAMCO_FLASH_AUTO"/>
    <STRING id="STR_ID_VAPP_CAMCO_FLASH_FORCE_ON"/>
    <STRING id="STR_ID_VAPP_CAMCO_FLASH_RED_EYE"/>

    <STRING id="STR_ID_VAPP_CAMCO_SELFTIMER"/>
    <STRING id="STR_ID_VAPP_CAMCO_SELFTIMER_5S"/>
    <STRING id="STR_ID_VAPP_CAMCO_SELFTIMER_10S"/>

    <STRING id="STR_ID_VAPP_CAMCO_ISO"/>
    <STRING id="STR_ID_VAPP_CAMCO_ISO_AUTO"/>
    <STRING id="STR_ID_VAPP_CAMCO_ISO_100"/>
    <STRING id="STR_ID_VAPP_CAMCO_ISO_200"/>
    <STRING id="STR_ID_VAPP_CAMCO_ISO_400"/>
    <STRING id="STR_ID_VAPP_CAMCO_ISO_800"/>
    <STRING id="STR_ID_VAPP_CAMCO_ISO_1600"/>

    <STRING id="STR_ID_VAPP_CAMCO_WB"/>
    <STRING id="STR_ID_VAPP_CAMCO_WB_AUTO"/>
    <STRING id="STR_ID_VAPP_CAMCO_WB_DAYLIGHT"/>
    <STRING id="STR_ID_VAPP_CAMCO_WB_TUNGSTEN"/>
    <STRING id="STR_ID_VAPP_CAMCO_WB_FLUORESCENT"/>
    <STRING id="STR_ID_VAPP_CAMCO_WB_CLOUDY"/>
    <STRING id="STR_ID_VAPP_CAMCO_WB_INCANDESCENT"/>

    <STRING id="STR_ID_VAPP_CAMCO_EFFECT"/>
    <STRING id="STR_ID_VAPP_CAMCO_EFFECT_GRAYSCALE"/>
    <STRING id="STR_ID_VAPP_CAMCO_EFFECT_SEPIA"/>
    <STRING id="STR_ID_VAPP_CAMCO_EFFECT_SEPIA_GREEN"/>
    <STRING id="STR_ID_VAPP_CAMCO_EFFECT_SEPIA_BLUE"/>
    <STRING id="STR_ID_VAPP_CAMCO_EFFECT_COLOR_INVERT"/>
    <STRING id="STR_ID_VAPP_CAMCO_EFFECT_GRAY_INVERT"/>
    <STRING id="STR_ID_VAPP_CAMCO_EFFECT_BLACKBOARD"/>
    <STRING id="STR_ID_VAPP_CAMCO_EFFECT_WHITEBOARD"/>
    <STRING id="STR_ID_VAPP_CAMCO_EFFECT_COPPER_CARVING"/>
    <STRING id="STR_ID_VAPP_CAMCO_EFFECT_BLUE_CARVING"/>
    <STRING id="STR_ID_VAPP_CAMCO_EFFECT_EMBOSSMENT"/>
    <STRING id="STR_ID_VAPP_CAMCO_EFFECT_CONTRAST"/>
    <STRING id="STR_ID_VAPP_CAMCO_EFFECT_JEAN"/>
    <STRING id="STR_ID_VAPP_CAMCO_EFFECT_SKETCH"/>
    <STRING id="STR_ID_VAPP_CAMCO_EFFECT_OIL"/>
    <STRING id="STR_ID_VAPP_CAMCO_EFFECT_LOMO"/>
    <STRING id="STR_ID_VAPP_CAMCO_EFFECT_COLOR_RED"/>
    <STRING id="STR_ID_VAPP_CAMCO_EFFECT_COLOR_YELLOW"/>
    <STRING id="STR_ID_VAPP_CAMCO_EFFECT_COLOR_GREEN"/>
    <STRING id="STR_ID_VAPP_CAMCO_EFFECT_COLOR_BLUE"/>

    <STRING id="STR_ID_VAPP_CAMCO_CAPQTY"/>
    <STRING id="STR_ID_VAPP_CAMCO_CAPQTY_FINE"/>
    <STRING id="STR_ID_VAPP_CAMCO_CAPQTY_GOOD"/>
    <STRING id="STR_ID_VAPP_CAMCO_CAPQTY_NORMAL"/>
    <STRING id="STR_ID_VAPP_CAMCO_CAPQTY_LOW"/>

    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE"/>
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_SQCIF"/>
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_QQVGA"/>
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_QCIF"/>
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_QVGA"/>
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_CIF"/>
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_WQVGA"/>
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_CIF2"/>
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_HVGA"/>
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_NHD"/>
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_VGA"/>
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_4CIF"/>
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_D1"/>
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_D12"/>
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_WVGA"/>
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_SVGA"/>
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_WVGA2"/>
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_FWVGA"/>
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_XGA"/>
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_720P"/>
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_4VGA"/>
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_SXGA"/>
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_16CIF"/>
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_4SVGA"/>
    <STRING id="STR_ID_VAPP_CAMCO_RECSIZE_FHD"/>

    <STRING id="STR_ID_VAPP_CAMCO_TIME_LAPSE"/>

    <STRING id="STR_ID_VAPP_CAMCO_TIME_LAPSE_PERIOD"/>

    <STRING id="STR_ID_VAPP_CAMCO_LIMIT"/>
    <STRING id="STR_ID_VAPP_CAMCO_LIMIT_NO_LIMIT"/>
    <STRING id="STR_ID_VAPP_CAMCO_LIMIT_TIME_15S"/>
    <STRING id="STR_ID_VAPP_CAMCO_LIMIT_TIME_30S"/>
    <STRING id="STR_ID_VAPP_CAMCO_LIMIT_TIME_60S"/>
    <STRING id="STR_ID_VAPP_CAMCO_LIMIT_TIME_300S"/>
    <STRING id="STR_ID_VAPP_CAMCO_LIMIT_TIME_600S"/>
    <STRING id="STR_ID_VAPP_CAMCO_LIMIT_SIZE_95K"/>
    <STRING id="STR_ID_VAPP_CAMCO_LIMIT_SIZE_195K"/>
    <STRING id="STR_ID_VAPP_CAMCO_LIMIT_SIZE_295K"/>

    <STRING id="STR_ID_VAPP_CAMCO_VISQTY"/>
    <STRING id="STR_ID_VAPP_CAMCO_VISQTY_FINE"/>
    <STRING id="STR_ID_VAPP_CAMCO_VISQTY_GOOD"/>
    <STRING id="STR_ID_VAPP_CAMCO_VISQTY_NORMAL"/>
    <STRING id="STR_ID_VAPP_CAMCO_VISQTY_LOW"/>

    <STRING id="STR_ID_VAPP_CAMCO_VISCODEC"/>
    <STRING id="STR_ID_VAPP_CAMCO_VISCODEC_MP4"/>
    <STRING id="STR_ID_VAPP_CAMCO_VISCODEC_3GP"/>
    <STRING id="STR_ID_VAPP_CAMCO_VISCODEC_MJPG"/>
    <STRING id="STR_ID_VAPP_CAMCO_VISCODEC_H264"/>

    <STRING id="STR_ID_VAPP_CAMCO_EV"/>

    <STRING id="STR_ID_VAPP_CAMCO_CREATE_FOLDER_FAILED"/>
    <STRING id="STR_ID_VAPP_CAMCO_PREVIEW_FAILED"/>
    <STRING id="STR_ID_VAPP_CAMCO_DISK_FULL"/>
    <STRING id="STR_ID_VAPP_CAMCO_CAPTURE_FAILED"/>
    <STRING id="STR_ID_VAPP_CAMCO_PAUSE_FAILED"/>
    <STRING id="STR_ID_VAPP_CAMCO_CAMERA_NOT_READY"/>
    <STRING id="STR_ID_VAPP_CAMCO_PROCESSING"/>

    <STRING id="STR_ID_VAPP_CAMCO_NOTIFY_HW_NOT_READY"/>
    <STRING id="STR_ID_VAPP_CAMCO_NOTIFY_STORAGE_NOT_READY"/>
    <STRING id="STR_ID_VAPP_CAMCO_NOTIFY_ERROR"/>
    <STRING id="STR_ID_VAPP_CAMCO_NOTIFY_REACH_TIME_LIMIT"/>
    <STRING id="STR_ID_VAPP_CAMCO_NOTIFY_REACH_SIZE_LIMIT"/>

    #define CAMCO_OSD_PATH    RES_IMG_ROOT"\\\\Camcorder\\\\"

    <THEME>
        <IMAGE id="MAIN_MENU_CAMCO_ICON">RES_IMG_ROOT"\\\\"__MMI_MAINMENU_ICON_DEFAULT_PATH__"\\\\Camera.png"</IMAGE>
    </THEME>
    <IMAGE id="IMG_ID_VAPP_CAMCO_RIGHT_BAR_ICON">CAMCO_OSD_PATH"bg_bar_r.9slice.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_V_RIGHT_BAR_ICON">CAMCO_OSD_PATH"bg_bar_v_r.9slice.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_SWITCH_SENSOR">CAMCO_OSD_PATH"switch_cam.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_RECORD_PAUSE_ICON">CAMCO_OSD_PATH"btn_pause.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_RECORD_RESUME_ICON">CAMCO_OSD_PATH"btn_play.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_RECORD_REC_ICON">CAMCO_OSD_PATH"btn_rec.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_RECORD_REC_IND_ICON">CAMCO_OSD_PATH"icon_rec.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_RECORD_PAUSE_IND_ICON">CAMCO_OSD_PATH"icon_pause.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_CAPTURE_ICON">CAMCO_OSD_PATH"btn_shoot.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_RECORD_STOP_ICON">CAMCO_OSD_PATH"btn_stop.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_BTN_BG1_ICON">CAMCO_OSD_PATH"btn_bg01.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_BTN_BG2_ICON">CAMCO_OSD_PATH"btn_bg02.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_SETTING_BG_ICON">CAMCO_OSD_PATH"ItemBG.9slice.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_GALLERY_ICON">CAMCO_OSD_PATH"last_shot_frame.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_SWITCHER_BAR_U">CAMCO_OSD_PATH"switcher_rec.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_SWITCHER_BAR_D">CAMCO_OSD_PATH"switcher_cam.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_SWITCHER_REC">CAMCO_OSD_PATH"switcher_rec_icon.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_SWITCHER_CAM">CAMCO_OSD_PATH"switcher_cam_icon.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_ZOOM_IND_ICON">CAMCO_OSD_PATH"zoom_ball.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_ZOOM_IN_ICON">CAMCO_OSD_PATH"zoom_in.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_ZOOM_OUT_ICON">CAMCO_OSD_PATH"zoom_out.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_ZOOM_BAR_ICON">CAMCO_OSD_PATH"zoom_track.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_AD_SETTING_ICON">CAMCO_OSD_PATH"Setting.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_AD_SETTING_SHADOW_ICON">CAMCO_OSD_PATH"Shadow.9slice.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_SETTING_IND_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Flash\\\\flash_H.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_AD_SETTING_IND_ICON">CAMCO_OSD_PATH"arrow.png"</IMAGE>

    // rect icon
    <IMAGE id="IMG_ID_VAPP_CAMCO_RECT_AF_NORMAL1_ICON">CAMCO_OSD_PATH"focus_sb_1.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_RECT_AF_NORMAL2_ICON">CAMCO_OSD_PATH"focus_sb_2.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_RECT_AF_NORMAL3_ICON">CAMCO_OSD_PATH"focus_sb_3.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_RECT_AF_NORMAL4_ICON">CAMCO_OSD_PATH"focus_sb_4.png"</IMAGE>

    <IMAGE id="IMG_ID_VAPP_CAMCO_RECT_AF_SUCCESS1_ICON">CAMCO_OSD_PATH"focus_1.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_RECT_AF_SUCCESS2_ICON">CAMCO_OSD_PATH"focus_2.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_RECT_AF_SUCCESS3_ICON">CAMCO_OSD_PATH"focus_3.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_RECT_AF_SUCCESS4_ICON">CAMCO_OSD_PATH"focus_4.png"</IMAGE>

    <IMAGE id="IMG_ID_VAPP_CAMCO_RECT_AF_FAIL1_ICON">CAMCO_OSD_PATH"focus_sf_1.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_RECT_AF_FAIL2_ICON">CAMCO_OSD_PATH"focus_sf_2.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_RECT_AF_FAIL3_ICON">CAMCO_OSD_PATH"focus_sf_3.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_RECT_AF_FAIL4_ICON">CAMCO_OSD_PATH"focus_sf_4.png"</IMAGE>

    <IMAGE id="IMG_ID_VAPP_CAMCO_RECT_FD_SUCCESS1_ICON">CAMCO_OSD_PATH"focus_1.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_RECT_FD_SUCCESS2_ICON">CAMCO_OSD_PATH"focus_2.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_RECT_FD_SUCCESS3_ICON">CAMCO_OSD_PATH"focus_3.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_RECT_FD_SUCCESS4_ICON">CAMCO_OSD_PATH"focus_4.png"</IMAGE>

    <IMAGE id="IMG_ID_VAPP_CAMCO_RECT_SD_SUCCESS1_ICON">CAMCO_OSD_PATH"focus_sm_1.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_RECT_SD_SUCCESS2_ICON">CAMCO_OSD_PATH"focus_sm_2.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_RECT_SD_SUCCESS3_ICON">CAMCO_OSD_PATH"focus_sm_3.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_RECT_SD_SUCCESS4_ICON">CAMCO_OSD_PATH"focus_sm_4.png"</IMAGE>

    // menu icon
    <IMAGE id="IMG_ID_VAPP_CAMCO_FLASH_AUTO_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Flash\\\\flash_auto.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_FLASH_FORCE_ON_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Flash\\\\flash_on.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_FLASH_OFF_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Flash\\\\flash_off.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_FLASH_REDEYE_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Flash\\\\flash_redeye.png"</IMAGE>

    <IMAGE id="IMG_ID_VAPP_CAMCO_EFFECT1_ICON">CAMCO_OSD_PATH"Filter\\\\Normal.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_EFFECT2_ICON">CAMCO_OSD_PATH"Filter\\\\Graystyle.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_EFFECT3_ICON">CAMCO_OSD_PATH"Filter\\\\Sepia.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_EFFECT4_ICON">CAMCO_OSD_PATH"Filter\\\\ColorInvert.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_EFFECT5_ICON">CAMCO_OSD_PATH"Filter\\\\Sketch.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_EFFECT6_ICON">CAMCO_OSD_PATH"Filter\\\\OilPaint.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_EFFECT7_ICON">CAMCO_OSD_PATH"Filter\\\\Lomo.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_EFFECT8_ICON">CAMCO_OSD_PATH"Filter\\\\Color_Red.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_EFFECT9_ICON">CAMCO_OSD_PATH"Filter\\\\Color_Yellow.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_EFFECT10_ICON">CAMCO_OSD_PATH"Filter\\\\Color_Green.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_EFFECT11_ICON">CAMCO_OSD_PATH"Filter\\\\Color_Bule.png"</IMAGE>

    <IMAGE id="IMG_ID_VAPP_CAMCO_EV_PLUS_ICON">RES_THEME_ROOT"\\\Default\\\Settings\\\ListIcon\\\Brightness_MAX.png"</IMAGE>

    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_AF_MACRO_ICON">CAMCO_OSD_PATH"AF_marco.png"</IMAGE>

    // status icon
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_CAPMODE_ASD_ICON">CAMCO_OSD_PATH"Status_Icon\\\\CaptureMode\\\\asd.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_CAPMODE_SD_ICON">CAMCO_OSD_PATH"Status_Icon\\\\CaptureMode\\\\smile_shot.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_CAPMODE_ZSD_ICON">CAMCO_OSD_PATH"Status_Icon\\\\CaptureMode\\\\zsd.png"</IMAGE>

    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_CAPMODE_ASD_SHOT_AUTO_MODE_ICON">CAMCO_OSD_PATH"Status_Icon\\\\SceneMode\\\\mode_auto.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_CAPMODE_ASD_SHOT_BACKLIGHT_MODE_ICON">CAMCO_OSD_PATH"Status_Icon\\\\SceneMode\\\\mode_backlight.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_CAPMODE_ASD_SHOT_BACKLIGHT_PORTRAIT_MODE_ICON">CAMCO_OSD_PATH"Status_Icon\\\\SceneMode\\\\mode_backlight_portrait.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_CAPMODE_ASD_SHOT_LANDSCAPE_MODE_ICON">CAMCO_OSD_PATH"Status_Icon\\\\SceneMode\\\\mode_landscape.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_CAPMODE_ASD_SHOT_NIGHT_MODE_ICON">CAMCO_OSD_PATH"Status_Icon\\\\SceneMode\\\\mode_night.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_CAPMODE_ASD_SHOT_NIGHT_PORTRAIT_MODE_ICON">CAMCO_OSD_PATH"Status_Icon\\\\SceneMode\\\\mode_night_portrait.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_CAPMODE_ASD_SHOT_PORTRAIT_MODE_ICON">CAMCO_OSD_PATH"Status_Icon\\\\SceneMode\\\\mode_portrait.png"</IMAGE>

    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_SCN_MODE_ANTI_ICON">CAMCO_OSD_PATH"Status_Icon\\\\SceneMode\\\\mode_anti_shake.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_SCN_MODE_NIGHT_ICON">CAMCO_OSD_PATH"Status_Icon\\\\SceneMode\\\\mode_night.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_SCN_MODE_PORTRAIT_ICON">CAMCO_OSD_PATH"Status_Icon\\\\SceneMode\\\\mode_portrait.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_SCN_MODE_SPORT_ICON">CAMCO_OSD_PATH"Status_Icon\\\\SceneMode\\\\mode_sport.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_SCN_MODE_TEXT_ICON">CAMCO_OSD_PATH"Status_Icon\\\\SceneMode\\\\mode_text.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_SCN_MODE_VIEW_ICON">CAMCO_OSD_PATH"Status_Icon\\\\SceneMode\\\\mode_landscape.png"</IMAGE>

    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_TIMER_10S_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Timer\\\\timer_10s.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_TIMER_5S_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Timer\\\\timer_5s.png"</IMAGE>

    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_TIME_LAPSE_ON_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Time_Lapse\\\\time_lapse.png"</IMAGE>

    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_LIMIT_15S_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Limit\\\\15sec.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_LIMIT_30S_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Limit\\\\30sec.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_LIMIT_60S_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Limit\\\\60sec.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_LIMIT_300S_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Limit\\\\300sec.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_LIMIT_600S_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Limit\\\\600sec.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_LIMIT_95K_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Limit\\\\95kb.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_LIMIT_195K_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Limit\\\\195kb.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_CAMCO_STATUS_LIMIT_295K_ICON">CAMCO_OSD_PATH"Status_Icon\\\\Limit\\\\295kb.png"</IMAGE>

    <CACHEDATA type="short" id="NVRAM_CAM_FILENAME_SEQ_NO" restore_flag="TRUE">
        <DEFAULT_VALUE> [0xFF, 0xFF] </DEFAULT_VALUE>
        <DESCRIPTION> CameraApp </DESCRIPTION>
    </CACHEDATA>

    <CACHEDATA type="short" id="NVRAM_VDOREC_FILENAME_SEQ_NO">
        <DEFAULT_VALUE> [0xFF, 0xFF] </DEFAULT_VALUE>
        <DESCRIPTION> Short Cache </DESCRIPTION>
    </CACHEDATA>

    <RECEIVER id="EVT_ID_PRE_KEY_EVT_ROUTING" proc="vapp_camco_pre_key_hdlr"/>

    <AUDIO id="AUD_ID_VAPP_CAMCO_COUNTDOWN">CUST_ADO_PATH"\\\\Camcorder\\\\count.wav"</AUDIO>
    <AUDIO id="AUD_ID_VAPP_CAMCO_CAPTURE_1">CUST_ADO_PATH"\\\\Camcorder\\\\pic.wav"</AUDIO>

</APP>

#endif

