/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2008
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES. ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *  Vapp_email_prot.h
 *
 * Project:
 * --------
 *  COSMOS Email Prot
 *
 * Description:
 * ------------
 *  
 *
 * Author:
 * -------
 * -------
 *
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/
#ifndef VAPP_EMAIL_PROT_H
#define VAPP_EMAIL_PROT_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "MMI_features.h"
#include "mmi_rp_srv_venus_component_list_menu_def.h"
#include "mmi_rp_vapp_email_def.h"
#include "GlobalResDef.h"
#include "MMI_inet_app_trc.h"

#ifdef __cplusplus
}
#endif

#include "vapp_email_gprot.h"

#define VAPP_EMAIL_MAX_CONT_LEN                     MMI_EMAIL_MAX_CONT_LEN
#define VAPP_EMAIL_MAX_SUBJ_LEN                     MMI_EMAIL_MAX_SUBJ_LEN

// TODO: should be dependent on SRV's value
#define VAPP_EMAIL_MIN_VLIAD_ACCT_ID                (1)

#define VAPP_EMAIL_POP3_PORT_NUMBER                 (110)
#define VAPP_EMAIL_POP3_SECURITY_PORT_NUMBER        (995)

#define VAPP_EMAIL_IMAP_PORT_NUMBER                 (143)
#define VAPP_EMAIL_IMAP_SECURITY_PORT_NUMBER        (993)

#define VAPP_EMAIL_SMTP_PORT_NUMBER                 (25)
#define VAPP_EMAIL_SMTP_SECURITY_PORT_NUMBER        (465)

enum VappEmailFuncBarEnum
{
    FUNCBAR_PREV = 0,
    FUNCBAR_NEXT,
    FUNCBAR_TEST,
    FUNCBAR_FINISH,
    FUNCBAR_SAVE,
    FUNCBAR_OK,
    FUNCBAR_EMOTION,
    FUNCBAR_INSERT,
};

// this buffer used to store the content from other apps
// and used in background sending for MRE
extern WCHAR g_content[VAPP_EMAIL_MAX_CONT_LEN + 1];


// email_acct_setting.cpp
#define VEMAIL_TRC_ACCT_SET_ID(a) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_ACCT_SET_ID, __LINE__, a)
#define VEMAIL_TRC_ACCT_INIT_DATA(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_ACCT_INIT_DATA, __LINE__, r)
#define VEMAIL_TRC_DEL_ACCT(a,r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_DEL_ACCT, __LINE__, a,r)
#define VEMAIL_TRC_SAVE_ACCT(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_SAVE_ACCT, __LINE__, r)

// email_setting.cpp
#define VEMAIL_TRC_GET_DRIVE_NAME(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_GET_DRIVE_NAME, __LINE__, r)
#define VEMAIL_TRC_EDIT_ACCT_BGN(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_EDIT_ACCT_BGN, __LINE__, r)
#define VEMAIL_TRC_CREATE_ACCT_SCR(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_CREATE_ACCT_SCR, __LINE__, r)
#define VEMAIL_TRC_DRIVE_COUNT(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_DRIVE_COUNT, __LINE__, r)
#define VEMAIL_TRC_SWITCH_STOR(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_SWITCH_STOR, __LINE__, r)
#define VEMAIL_TRC_SET_DFT_ACCT(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_SET_DFT_ACCT, __LINE__, r)
#define VEMAIL_TRC_GET_DFT_ACCT(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_GET_DFT_ACCT, __LINE__, r)

// email_acct_wizard.cpp
#define VEMAIL_TRC_ACCT_SAVE_INIT_MISC_FAIL() \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_ACCT_SAVE_INIT_MISC_FAIL, __LINE__)
#define VEMAIL_TRC_ACCT_SAVE_PROC(R) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_ACCT_SAVE_PROC, __LINE__, R)
#define VEMAIL_TRC_ACCT_SAVE_PROC_DEL_ACCT(R) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_ACCT_SAVE_PROC_DEL_ACCT, __LINE__, R)
#define VEMAIL_TRC_ACCT_SAVE_PROC_TEST_NWK(R) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_ACCT_SAVE_PROC_TEST_NWK, __LINE__, R)
#define VEMAIL_TRC_ACCT_SAVE_CANCEL() \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_ACCT_SAVE_CANCEL, __LINE__)
#define VEMAIL_TRC_ACCT_SAVE_TEST_NWK_CANCEL() \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_ACCT_SAVE_TEST_NWK_CANCEL, __LINE__)
#define VEMAIL_TRC_ACCT_SAVE_TEST_NWK_RESUTL(R, M, N) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_ACCT_SAVE_TEST_NWK_RESUTL, __LINE__, R, M, N)
#define VEMAIL_TRC_ACCT_TEMPLATE_NUM(N) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_ACCT_TEMPLATE_NUM, __LINE__, N)
#define VEMAIL_TRC_ACCT_TEMPLATE_CHOOSE_IDEX(I) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_ACCT_TEMPLATE_CHOOSE_IDEX, __LINE__, I)

// email_acct.cpp
#define VEMAIL_TRC_ACCT_NUM(r,c) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_ACCT_NUM, __LINE__, r,c)
#define VEMAIL_TRC_ACCT_CREATE(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_ACCT_CREATE, __LINE__, r)
#define VEMAIL_TRC_ACCT_OPEN(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_ACCT_OPEN, __LINE__, r)
#define VEMAIL_TRC_ACCT_READ(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_ACCT_READ, __LINE__, r)
#define VEMAIL_TRC_AUTO_CHK(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_AUTO_CHK, __LINE__, r)
#define VEMAIL_TRC_ACCT_PERMISSION(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_ACCT_PERMISSION, __LINE__, r)
#define VEMAIL_TRC_ACCT_EDIT(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_ACCT_EDIT, __LINE__, r)
#define VEMAIL_TRC_ACCT_SAVE(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_ACCT_SAVE, __LINE__, r)
#define VEMAIL_TRC_SIG_CREATE(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_SIG_CREATE, __LINE__, r)
#define VEMAIL_TRC_SIG_DELETE(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_SIG_DELETE, __LINE__, r)
#define VEMAIL_TRC_AUTO_CHK_CREATE(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_AUTO_CHK_CREATE, __LINE__, r)
#define VEMAIL_TRC_AUTO_CHK_DELETE(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_AUTO_CHK_DELETE, __LINE__, r)
#define VEMAIL_TRC_AUTO_CHK_ADD(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_AUTO_CHK_ADD, __LINE__, r)
#define VEMAIL_TRC_AUTO_CHK_SET(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_AUTO_CHK_SET, __LINE__, r)
#define VEMAIL_TRC_AUTO_CHK_STOP(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_AUTO_CHK_STOP, __LINE__, r)
#define VEMAIL_TRC_GLB_SET_OPEN(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_GLB_SET_OPEN, __LINE__, r)
#define VEMAIL_TRC_GLB_SET_READ(r,a,s) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_GLB_SET_READ, __LINE__, r,a,s)
#define VEMAIL_TRC_GLB_SET_WRITE(r,a,s) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_GLB_SET_WRITE, __LINE__, r,a,s)
#define VEMAIL_TRC_ACCT_CBM_REGISTER_FAIL(RES) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_ACCT_CBM_REGISTER_FAIL, __LINE__, RES)
#define VEMAIL_TRC_DTCNT_IS_VALID(VALID) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_DTCNT_IS_VALID, __LINE__, VALID)
// email_composer.cpp
#define VEMAIL_TRC_COMP_ACCT_LIST_ID(a) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_ACCT_LIST_ID, __LINE__, a)
#define VEMAIL_TRC_COMP_GET_ACCT_CNT(c) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_GET_ACCT_CNT, __LINE__, c)
#define VEMAIL_TRC_COMP_SLCT_ACCT_ID(i) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_SLCT_ACCT_ID, __LINE__, i)
#define VEMAIL_TRC_COMP_SET_SUBJ(p, f) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_SET_SUBJ, __LINE__, p, f)
#define VEMAIL_TRC_COMP_SET_CONT(p, f) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_SET_CONT, __LINE__, p, f)
#define VEMAIL_TRC_COMP_SET_ADDR(ap, af, np, nf, t) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_SET_ADDR, __LINE__, ap, af, np, nf, t)
#define VEMAIL_TRC_COMP_INST_ADDR_INDEX(i) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_INST_ADDR_INDEX, __LINE__, i)
#define VEMAIL_TRC_COMP_INST_ATTCH_INDEX(i) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_INST_ATTCH_INDEX, __LINE__, i)
#define VEMAIL_TRC_COMP_ADDR_TOTAL(i) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_ADDR_TOTAL, __LINE__, i)
#define VEMAIL_TRC_COMP_ATTCH_TOTAL(i) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_ATTCH_TOTAL, __LINE__, i)
#define VEMAIL_TRC_COMP_SET_ATTCH(p,f,d) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_SET_ATTCH, __LINE__, p, f, d)
#define VEMAIL_TRC_COMP_GET_FILE_SIZE(r,s) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_GET_FILE_SIZE, __LINE__, r, s)
#define VEMAIL_TRC_COMP_SIG_GET_STATUS(r,a,s) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_SIG_GET_STATUS, __LINE__, r, a, s)
#define VEMAIL_TRC_COMP_SIG_GET_SIG(r,a) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_SIG_GET_SIG, __LINE__, r,a)
#define VEMAIL_TRC_COMP_SIG_GET_PATH(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_SIG_GET_PATH, __LINE__, r)
#define VEMAIL_TRC_COMP_MSG_CREATE(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_MSG_CREATE, __LINE__, r)
#define VEMAIL_TRC_COMP_MSG_OPEN(r,m) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_MSG_OPEN, __LINE__, r,m)
#define VEMAIL_TRC_COMP_MSG_EDIT(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_MSG_EDIT, __LINE__, r)
#define VEMAIL_TRC_COMP_MSG_MOVE(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_MSG_MOVE, __LINE__, r)
#define VEMAIL_TRC_COMP_MSG_SET_NEW(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_MSG_SET_NEW, __LINE__, r)
#define VEMAIL_TRC_COMP_MSG_GET_SUBJ(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_MSG_GET_SUBJ, __LINE__, r)
#define VEMAIL_TRC_COMP_MSG_GET_CONT(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_MSG_GET_CONT, __LINE__, r)
#define VEMAIL_TRC_COMP_MSG_GET_SENDER(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_MSG_GET_SENDER, __LINE__, r)
#define VEMAIL_TRC_COMP_MSG_GET_BASIC(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_MSG_GET_BASIC, __LINE__, r)
#define VEMAIL_TRC_COMP_MSG_GET_PERMISSION(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_MSG_GET_PERMISSION, __LINE__, r)
#define VEMAIL_TRC_COMP_MSG_GET_RECIPIENT(r, c) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_MSG_GET_RECIPIENT, __LINE__, r,c)
#define VEMAIL_TRC_COMP_MSG_GET_ATTCH(r, c) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_MSG_GET_ATTCH, __LINE__, r,c)
#define VEMAIL_TRC_COMP_MSG_BASIC_ADDR_ATTCH(t, c, b, a) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_MSG_BASIC_ADDR_ATTCH, __LINE__, t, c, b, a)
#define VEMAIL_TRC_COMP_MSG_UPDATE_SUBJ(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_MSG_UPDATE_SUBJ, __LINE__, r)
#define VEMAIL_TRC_COMP_MSG_UPDATE_CONT(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_MSG_UPDATE_CONT, __LINE__, r)
#define VEMAIL_TRC_COMP_MSG_UPDATE_RECIPIENT(r, t, n)\
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_MSG_UPDATE_RECIPIENT, __LINE__, r, t, n)
#define VEMAIL_TRC_COMP_MSG_UPDATE_ATTCH(r,n) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_MSG_UPDATE_ATTCH, __LINE__, r, n)
#define VEMAIL_TRC_COMP_MSG_UPDATE_BASIC_INFO(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_MSG_UPDATE_BASIC_INFO, __LINE__, r)
#define VEMAIL_TRC_COMP_MSG_SAVE(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_MSG_SAVE, __LINE__, r)
#define VEMAIL_TRC_COMP_MSG_SAVE_NEW(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_MSG_SAVE_NEW, __LINE__, r)
#define VEMAIL_TRC_COMP_MSG_SEND() \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_MSG_SEND, __LINE__)
#define VEMAIL_TRC_COMP_MSG_SAVE_PROC(r1, r2, e1, e2) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_MSG_SAVE_PROC, __LINE__, r1, r2, e1, e2)
#define VEMAIL_TRC_COMP_ACCT_CREATE(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_ACCT_CREATE, __LINE__, r)
#define VEMAIL_TRC_COMP_ACCT_OPEN(r,a) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_ACCT_OPEN, __LINE__, r,a)
#define VEMAIL_TRC_COMP_ACCT_READ(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_ACCT_READ, __LINE__, r)
#define VEMAIL_TRC_COMP_ACCT_GET_FLDR_ID(res) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_ACCT_GET_FLDR_ID, __LINE__, res)
#define VEMAIL_TRC_COMP_UPDATE_REPLY_TO(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_UPDATE_REPLY_TO, __LINE__, r)
#define VEMAIL_TRC_COMP_UPDATE_SENDER(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_UPDATE_SENDER, __LINE__, r)
#define VEMAIL_TRC_COMP_UC_LAUNCH(addrN, attchN, s, c) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_UC_LAUNCH, __LINE__, addrN, attchN, s, c)
#define VEMAIL_TRC_COMP_UC_QUERY_ADDR(i, g, a) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_UC_QUERY_ADDR, __LINE__, i, g, a)
#define VEMAIL_TRC_COMP_UC_QUERY_ATTCH(n, p, s) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_UC_QUERY_ATTCH, __LINE__, n, p, s)
#define VEMAIL_TRC_COMP_UC_QUERY_TITLE(m, s) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_UC_QUERY_TITLE, __LINE__, m, s)
#define VEMAIL_TRC_COMP_UC_QUERY_SHOW_CC(s) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_UC_QUERY_SHOW_CC, __LINE__, s)
#define VEMAIL_TRC_COMP_UC_QUERY_DOMAIN_CNT(c) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_UC_QUERY_DOMAIN_CNT, __LINE__, c)
#define VEMAIL_TRC_COMP_UC_QUERY_DOMAIN(i, d) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_UC_QUERY_DOMAIN, __LINE__, i, d)
#define VEMAIL_TRC_COMP_UC_CALL_EMAIL_SAVE() \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_UC_CALL_EMAIL_SAVE, __LINE__)
#define VEMAIL_TRC_COMP_UC_CALL_EMAIL_SEND() \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_UC_CALL_EMAIL_SEND, __LINE__)
#define VEMAIL_TRC_COMP_DRM() \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_DRM, __LINE__)
#define VEMAIL_TRC_COMP_DRM_FWD(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_DRM_FWD, __LINE__, r)
#define VEMAIL_TRC_COMP_TOTAL_SIZE(s) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_TOTAL_SIZE, __LINE__, s)
#define VEMAIL_TRC_COMP_INTERNAL_ADD_ATTCH(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_INTERNAL_ADD_ATTCH, __LINE__, r)
#define VEMAIL_TRC_COMP_INTERNAL_DEL_ATTCH(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_INTERNAL_DEL_ATTCH, __LINE__, r)
#define VEMAIL_TRC_COMP_CHK_ATTCH(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_CHK_ATTCH, __LINE__, r)
#define VEMAIL_TRC_COMP_ATTCH_COPY(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_ATTCH_COPY, __LINE__, r)
#define VEMAIL_TRC_COMP_ATTCH_DEL(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_ATTCH_DEL, __LINE__, r)
#define VEMAIL_TRC_COMP_SAVE_SEND_MODE(s) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_SAVE_SEND_MODE, __LINE__, s)
#define VEMAIL_TRC_COMP_FROM_UC_ADDR(t, c, b) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_FROM_UC_ADDR, __LINE__, t, c, b)
#define VEMAIL_TRC_COMP_FROM_UC_ATTCH(c) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_FROM_UC_ATTCH, __LINE__, c)
#define VEMAIL_TRC_COMP_SYS_INIT(r) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_SYS_INIT, __LINE__, r)
#define VEMAIL_TRC_COMP_RECENT_DOMAIN_READ(RES) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_RECENT_DOMAIN_READ, __LINE__, RES)
#define VEMAIL_TRC_COMP_RECENT_DOMAIN_WRITE(RES) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_COMP_RECENT_DOMAIN_WRITE, __LINE__, RES)

#define VEMAIL_TRC_MAIN_SEND_CHK_ATTCH(RES) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_MAIN_SEND_CHK_ATTCH, __LINE__, RES)
#define VEMAIL_TRC_MAIN_SEND_CONT(CONT) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_MAIN_SEND_CONT, __LINE__, CONT)
#define VEMAIL_TRC_MAIN_SEND_CHK_ADDR(RES) \
    MMI_TRACE(MMI_INET_TRC_G9_EMAIL, TRC_VEMAIL_MAIN_SEND_CHK_ADDR, __LINE__, RES)

// Email SWLA logging
#ifdef __MTK_TARGET__
//#define __MAUI_SOFTWARE_LA__
#endif

#if defined(__MAUI_SOFTWARE_LA__)

#ifdef __cplusplus
extern "C"
{
#endif
#include "SST_sla.h"
#ifdef __cplusplus
}
#endif

#define VAPP_EMAIL_SWLA_START(_symbol_)\
        SLA_CustomLogging(##_symbol_##, SA_start)
#define VAPP_EMAIL_SWLA_STOP(_symbol_)\
        SLA_CustomLogging(##_symbol_##, SA_stop)
#define VAPP_EMAIL_SWLA_LABEL(_symbol_)\
        SLA_CustomLogging(##_symbol_##, SA_label)
#else
#define VAPP_EMAIL_SWLA_START(_symbol_)
#define VAPP_EMAIL_SWLA_STOP(_symbol_)
#define VAPP_EMAIL_SWLA_LABEL(_symbol_)
#endif

#endif
