/**********************************************************************************
*Filename:     kjx_timer.h
*
*Description:  定时器ID定义
*
*Author:        xiebiao
*
*Datetime:    2016-09-18
*
***********************************************************************************/
KJX_TIMER_ID_START,
KJX_TIMER_ID_NOTIFY_ERROR,
KJX_TIMER_ID_DOG,

KJX_TIMER_ID_MISC,
KJX_TIMER_ID_SENSOR,
KJX_TIMER_ID_BOSCH_GENSOR_READ,

KJX_TIMER_ID_READ_NV,
KJX_TIMER_ID_GET_DATABASE,
KJX_TIMER_ID_GET_ICCID,
KJX_TIMER_ID_CELL_REQ,
KJX_TIMER_ID_NBR_CELL_REQ,

KJX_TIMER_ID_LED_RED,
KJX_TIMER_ID_LED_BLUE,
KJX_TIMER_ID_LED_GREEN,
KJX_TIMER_ID_LED_YELLOW,

KJX_TIMER_ID_GPS_DATA,
KJX_TIMER_ID_GPS_SUSPEND,
KJX_TIMER_ID_GPS_RESUME,
KJX_TIMER_ID_GPS_CLOSE,
KJX_TIMER_ID_GPS_OPEN,
KJX_TIMER_ID_GPS_CHECK,
KJX_TIMER_ID_GPS_RESET,
KJX_TIMER_ID_GPS_RESET_TIMEROUT,
KJX_TIMER_ID_GPS_UPDATE_STATE,
KJX_TIMER_ID_GPS_AGPS_STATE,
KJX_TIMER_ID_AGPS_START,
KJX_TIMER_ID_AGPS_HD_CMD_DELAY,
KJX_TIMER_ID_AGPS_HD_CMD_WAIT_TIMEROUT,

KJX_TIMER_ID_OBD_WEB,
KJX_TIMER_ID_OBD_PLAY,
KJX_TIMER_ID_OBD_TIMEOUT,
KJX_TIMER_ID_OBD_START,
KJX_TIMER_ID_OBD_SEND,

KJX_TIMER_ID_INFRARED,
KJX_TIMER_ID_INFRARED_PLAY,

KJX_TIMER_ID_SET_TIMEZONE,
KJX_TIMER_ID_SET_MAINLCD,

KJX_TIMER_ID_SOS_HAND,
KJX_TIMER_ID_SOS_CALL,
KJX_TIMER_ID_GET_ADDRESS,
KJX_TIMER_ID_KEY_SOS,

KJX_TIMER_ID_HEART,
KJX_TIMER_ID_HEART_BEAT,
KJX_TIMER_ID_HEART_TOTAL,
KJX_TIMER_ID_HEART_STOP,

KJX_TIMER_ID_SHOW_TIME,
KJX_TIMER_ID_SHOW_VER,
KJX_TIMER_ID_SHOW_IMEI,

KJX_TIMER_ID_STEPS,
KJX_TIMER_ID_STEPS_START1,
KJX_TIMER_ID_STEPS_START2,

KJX_TIMER_ID_PLAY_AUDIO,
KJX_TIMER_ID_PLAY_TTS,
KJX_TIMER_ID_PLAY_TTS_AFTER,

KJX_TIMER_ID_RFID_CHECK,
KJX_TIMER_ID_RFID_KEY_HANDLER,
KJX_TIMER_ID_RFID_CLOSE,
KJX_TIMER_ID_RFID_MAIN,
KJX_TIMER_ID_RFID_EINT_INIT,
KJX_TIMER_ID_RFID_TEST_TIME,

KJX_TIMER_ID_EARPHONE_TEST_DELAY,
KJX_TIMER_ID_EARPHONE_PLUG_NOTIFY,
KJX_TIMER_ID_REDRAW_IDLESCREEN,

KJX_TIMER_ID_FACTORY_TEST,
KJX_TIMER_ID_KEY_ENTRY_TEST,
KJX_TIMER_ID_CUSTOM_CMD_SEND,
KJX_TIMER_ID_BATTERY,
KJX_TIMER_ID_QUERY_BATTERY_VOLTAGE,
KJX_TIMER_ID_REJECT_CALL,

KJX_TIMER_ID_LOGIN_AGAIN,
KJX_TIMER_ID_IS_CONNET,
KJX_TIMER_ID_SOCKET_START,
KJX_TIMER_ID_SOCKET_CONNECT,
KJX_TIMER_ID_SOCKET_NOTIFY_OVERTIME,
KJX_TIMER_ID_SOCKET_RECEIVE_DELAY,
KJX_TIMER_ID_SEND_POSITION_TRIGGER,
KJX_TIMER_ID_SEND_POSITION_TRIGGER_RFID,
KJX_TIMER_ID_SEND_PHONE_NUM,

KJX_TIMER_RESET,
KJX_TIMER_RESET_SHOW,

KJX_TIMER_ID_FIND_DEVICE,

KJX_TIMER_ID_IMEI_CHECK_ERROR,
KJX_TIMER_ID_RESEND_LANGUAGE_SET,
KJX_TIMER_ID_END_KEY_DELAY,
KJX_TIMER_ID_POWER_OFF_DELAY,

KJX_TIMER_ID_SMS_SENDER_DELAY,
KJX_TIMER_ID_GET_WEATHER,
KJX_TIMER_ID_SHOW_TOUR_IMG_TIMEROUT,
KJX_TIMER_ID_FENCE_ALARM_TIMEROUT,

KJX_TIMER_ID_SENSOR_INIT,
KJX_TIMER_ID_SENSOR_CHECK_SHAKE,
KJX_TIMER_ID_SENSOR_CHECK_STEP,

KJX_TIMER_ID_DJ_WORK_CHECK,
KJX_TIMER_ID_DJ_KEY_CHECK,

KJX_TIMER_ID_END,
