#ifndef _SQLITE3_TRC_GEN_H_
#define _SQLITE3_TRC_GEN_H_

// SQL_SQLITE_ROW_MSG
#define SQL_SQLITE_ROW_MSG_size ""
#define SQL_SQLITE_ROW_MSG SQL_SQLITE_ROW_MSG__enum,SQL_SQLITE_ROW_MSG_size

// SQL_SQLITE_DONE_MSG
#define SQL_SQLITE_DONE_MSG_size ""
#define SQL_SQLITE_DONE_MSG SQL_SQLITE_DONE_MSG__enum,SQL_SQLITE_DONE_MSG_size

// SQL_SQLITE_OK_MSG
#define SQL_SQLITE_OK_MSG_size ""
#define SQL_SQLITE_OK_MSG SQL_SQLITE_OK_MSG__enum,SQL_SQLITE_OK_MSG_size

// SQL_SQLITE_ERROR_MSG
#define SQL_SQLITE_ERROR_MSG_size ""
#define SQL_SQLITE_ERROR_MSG SQL_SQLITE_ERROR_MSG__enum,SQL_SQLITE_ERROR_MSG_size

// SQL_SQLITE_PERM_MSG
#define SQL_SQLITE_PERM_MSG_size ""
#define SQL_SQLITE_PERM_MSG SQL_SQLITE_PERM_MSG__enum,SQL_SQLITE_PERM_MSG_size

// SQL_SQLITE_ABORT_MSG
#define SQL_SQLITE_ABORT_MSG_size ""
#define SQL_SQLITE_ABORT_MSG SQL_SQLITE_ABORT_MSG__enum,SQL_SQLITE_ABORT_MSG_size

// SQL_SQLITE_BUSY_MSG
#define SQL_SQLITE_BUSY_MSG_size ""
#define SQL_SQLITE_BUSY_MSG SQL_SQLITE_BUSY_MSG__enum,SQL_SQLITE_BUSY_MSG_size

// SQL_SQLITE_LOCKED_MSG
#define SQL_SQLITE_LOCKED_MSG_size ""
#define SQL_SQLITE_LOCKED_MSG SQL_SQLITE_LOCKED_MSG__enum,SQL_SQLITE_LOCKED_MSG_size

// SQL_SQLITE_NOMEM_MSG
#define SQL_SQLITE_NOMEM_MSG_size ""
#define SQL_SQLITE_NOMEM_MSG SQL_SQLITE_NOMEM_MSG__enum,SQL_SQLITE_NOMEM_MSG_size

// SQL_SQLITE_READONLY_MSG
#define SQL_SQLITE_READONLY_MSG_size ""
#define SQL_SQLITE_READONLY_MSG SQL_SQLITE_READONLY_MSG__enum,SQL_SQLITE_READONLY_MSG_size

// SQL_SQLITE_INTERRUPT_MSG
#define SQL_SQLITE_INTERRUPT_MSG_size ""
#define SQL_SQLITE_INTERRUPT_MSG SQL_SQLITE_INTERRUPT_MSG__enum,SQL_SQLITE_INTERRUPT_MSG_size

// SQL_SQLITE_IOERR_MSG
#define SQL_SQLITE_IOERR_MSG_size ""
#define SQL_SQLITE_IOERR_MSG SQL_SQLITE_IOERR_MSG__enum,SQL_SQLITE_IOERR_MSG_size

// SQL_SQLITE_CORRUPT_MSG
#define SQL_SQLITE_CORRUPT_MSG_size ""
#define SQL_SQLITE_CORRUPT_MSG SQL_SQLITE_CORRUPT_MSG__enum,SQL_SQLITE_CORRUPT_MSG_size

// SQL_SQLITE_FULL_MSG
#define SQL_SQLITE_FULL_MSG_size ""
#define SQL_SQLITE_FULL_MSG SQL_SQLITE_FULL_MSG__enum,SQL_SQLITE_FULL_MSG_size

// SQL_SQLITE_CANTOPEN_MSG
#define SQL_SQLITE_CANTOPEN_MSG_size ""
#define SQL_SQLITE_CANTOPEN_MSG SQL_SQLITE_CANTOPEN_MSG__enum,SQL_SQLITE_CANTOPEN_MSG_size

// SQL_SQLITE_EMPTY_MSG
#define SQL_SQLITE_EMPTY_MSG_size ""
#define SQL_SQLITE_EMPTY_MSG SQL_SQLITE_EMPTY_MSG__enum,SQL_SQLITE_EMPTY_MSG_size

// SQL_SQLITE_SCHEMA_MSG
#define SQL_SQLITE_SCHEMA_MSG_size ""
#define SQL_SQLITE_SCHEMA_MSG SQL_SQLITE_SCHEMA_MSG__enum,SQL_SQLITE_SCHEMA_MSG_size

// SQL_SQLITE_TOOBIG_MSG
#define SQL_SQLITE_TOOBIG_MSG_size ""
#define SQL_SQLITE_TOOBIG_MSG SQL_SQLITE_TOOBIG_MSG__enum,SQL_SQLITE_TOOBIG_MSG_size

// SQL_SQLITE_CONSTRAINT_MSG
#define SQL_SQLITE_CONSTRAINT_MSG_size ""
#define SQL_SQLITE_CONSTRAINT_MSG SQL_SQLITE_CONSTRAINT_MSG__enum,SQL_SQLITE_CONSTRAINT_MSG_size

// SQL_SQLITE_MISMATCH_MSG
#define SQL_SQLITE_MISMATCH_MSG_size ""
#define SQL_SQLITE_MISMATCH_MSG SQL_SQLITE_MISMATCH_MSG__enum,SQL_SQLITE_MISMATCH_MSG_size

// SQL_SQLITE_MISUSE_MSG
#define SQL_SQLITE_MISUSE_MSG_size ""
#define SQL_SQLITE_MISUSE_MSG SQL_SQLITE_MISUSE_MSG__enum,SQL_SQLITE_MISUSE_MSG_size

// SQL_SQLITE_NOLFS_MSG
#define SQL_SQLITE_NOLFS_MSG_size ""
#define SQL_SQLITE_NOLFS_MSG SQL_SQLITE_NOLFS_MSG__enum,SQL_SQLITE_NOLFS_MSG_size

// SQL_SQLITE_AUTH_MSG
#define SQL_SQLITE_AUTH_MSG_size ""
#define SQL_SQLITE_AUTH_MSG SQL_SQLITE_AUTH_MSG__enum,SQL_SQLITE_AUTH_MSG_size

// SQL_SQLITE_FORMAT_MSG
#define SQL_SQLITE_FORMAT_MSG_size ""
#define SQL_SQLITE_FORMAT_MSG SQL_SQLITE_FORMAT_MSG__enum,SQL_SQLITE_FORMAT_MSG_size

// SQL_SQLITE_RANGE_MSG
#define SQL_SQLITE_RANGE_MSG_size ""
#define SQL_SQLITE_RANGE_MSG SQL_SQLITE_RANGE_MSG__enum,SQL_SQLITE_RANGE_MSG_size

// SQL_SQLITE_NOTADB_MSG
#define SQL_SQLITE_NOTADB_MSG_size ""
#define SQL_SQLITE_NOTADB_MSG SQL_SQLITE_NOTADB_MSG__enum,SQL_SQLITE_NOTADB_MSG_size

// SQL_UNKNOW_ERROR_MSG
#define SQL_UNKNOW_ERROR_MSG_size ""
#define SQL_UNKNOW_ERROR_MSG SQL_UNKNOW_ERROR_MSG__enum,SQL_UNKNOW_ERROR_MSG_size

// SQL_MEMINFO_PREPARE_MSG
#define SQL_MEMINFO_PREPARE_MSG_size "ddddd"
#define SQL_MEMINFO_PREPARE_MSG SQL_MEMINFO_PREPARE_MSG__enum,SQL_MEMINFO_PREPARE_MSG_size

// SQL_MEMINFO_PREPAREV2_MSG
#define SQL_MEMINFO_PREPAREV2_MSG_size "ddddd"
#define SQL_MEMINFO_PREPAREV2_MSG SQL_MEMINFO_PREPAREV2_MSG__enum,SQL_MEMINFO_PREPAREV2_MSG_size

// SQL_MEMINFO_PREPARE16_MSG
#define SQL_MEMINFO_PREPARE16_MSG_size "ddddd"
#define SQL_MEMINFO_PREPARE16_MSG SQL_MEMINFO_PREPARE16_MSG__enum,SQL_MEMINFO_PREPARE16_MSG_size

// SQL_MEMINFO_PREPARE16V2_MSG
#define SQL_MEMINFO_PREPARE16V2_MSG_size "ddddd"
#define SQL_MEMINFO_PREPARE16V2_MSG SQL_MEMINFO_PREPARE16V2_MSG__enum,SQL_MEMINFO_PREPARE16V2_MSG_size

// SQL_MEMINFO_FINALIZE_MSG
#define SQL_MEMINFO_FINALIZE_MSG_size "ddddd"
#define SQL_MEMINFO_FINALIZE_MSG SQL_MEMINFO_FINALIZE_MSG__enum,SQL_MEMINFO_FINALIZE_MSG_size

// SQL_MEMINFO_RESET_MSG
#define SQL_MEMINFO_RESET_MSG_size "ddddd"
#define SQL_MEMINFO_RESET_MSG SQL_MEMINFO_RESET_MSG__enum,SQL_MEMINFO_RESET_MSG_size

// SQL_MEMINFO_CLEAR_BINDINGS_MSG
#define SQL_MEMINFO_CLEAR_BINDINGS_MSG_size "ddddd"
#define SQL_MEMINFO_CLEAR_BINDINGS_MSG SQL_MEMINFO_CLEAR_BINDINGS_MSG__enum,SQL_MEMINFO_CLEAR_BINDINGS_MSG_size

// SQL_MEMINFO_ERRMSG_MSG
#define SQL_MEMINFO_ERRMSG_MSG_size "ddddd"
#define SQL_MEMINFO_ERRMSG_MSG SQL_MEMINFO_ERRMSG_MSG__enum,SQL_MEMINFO_ERRMSG_MSG_size

// SQL_MEMINFO_STEP_MSG
#define SQL_MEMINFO_STEP_MSG_size "ddddd"
#define SQL_MEMINFO_STEP_MSG SQL_MEMINFO_STEP_MSG__enum,SQL_MEMINFO_STEP_MSG_size

// SQL_MEMINFO_OPEN_MSG
#define SQL_MEMINFO_OPEN_MSG_size "ddddd"
#define SQL_MEMINFO_OPEN_MSG SQL_MEMINFO_OPEN_MSG__enum,SQL_MEMINFO_OPEN_MSG_size

// SQL_MEMINFO_OPENV2_MSG
#define SQL_MEMINFO_OPENV2_MSG_size "ddddd"
#define SQL_MEMINFO_OPENV2_MSG SQL_MEMINFO_OPENV2_MSG__enum,SQL_MEMINFO_OPENV2_MSG_size

// SQL_MEMINFO_OPEN16_MSG
#define SQL_MEMINFO_OPEN16_MSG_size "ddddd"
#define SQL_MEMINFO_OPEN16_MSG SQL_MEMINFO_OPEN16_MSG__enum,SQL_MEMINFO_OPEN16_MSG_size

// SQL_MEMINFO_CLOSE_MSG
#define SQL_MEMINFO_CLOSE_MSG_size "ddddd"
#define SQL_MEMINFO_CLOSE_MSG SQL_MEMINFO_CLOSE_MSG__enum,SQL_MEMINFO_CLOSE_MSG_size

// SQL_OUTOFMEM_MSG
#define SQL_OUTOFMEM_MSG_size "dddd"
#define SQL_OUTOFMEM_MSG SQL_OUTOFMEM_MSG__enum,SQL_OUTOFMEM_MSG_size

// SQL_GETSHAREFILE_OUTOFMEM_MSG
#define SQL_GETSHAREFILE_OUTOFMEM_MSG_size ""
#define SQL_GETSHAREFILE_OUTOFMEM_MSG SQL_GETSHAREFILE_OUTOFMEM_MSG__enum,SQL_GETSHAREFILE_OUTOFMEM_MSG_size

// SQL_GETSHAREFILE_OPENFILE_MSG
#define SQL_GETSHAREFILE_OPENFILE_MSG_size "d"
#define SQL_GETSHAREFILE_OPENFILE_MSG SQL_GETSHAREFILE_OPENFILE_MSG__enum,SQL_GETSHAREFILE_OPENFILE_MSG_size

// SQL_DUMPERRORCODE_MSG
#define SQL_DUMPERRORCODE_MSG_size "d"
#define SQL_DUMPERRORCODE_MSG SQL_DUMPERRORCODE_MSG__enum,SQL_DUMPERRORCODE_MSG_size

// SQL_NOMUTEX_MSG
#define SQL_NOMUTEX_MSG_size ""
#define SQL_NOMUTEX_MSG SQL_NOMUTEX_MSG__enum,SQL_NOMUTEX_MSG_size

// SQL_WRONG_ENTER_INSTANCE_MSG
#define SQL_WRONG_ENTER_INSTANCE_MSG_size ""
#define SQL_WRONG_ENTER_INSTANCE_MSG SQL_WRONG_ENTER_INSTANCE_MSG__enum,SQL_WRONG_ENTER_INSTANCE_MSG_size

// SQL_DBLEAK_MSG
#define SQL_DBLEAK_MSG_size "d"
#define SQL_DBLEAK_MSG SQL_DBLEAK_MSG__enum,SQL_DBLEAK_MSG_size

// SQL_STATEMENTLEAK_MSG
#define SQL_STATEMENTLEAK_MSG_size "d"
#define SQL_STATEMENTLEAK_MSG SQL_STATEMENTLEAK_MSG__enum,SQL_STATEMENTLEAK_MSG_size

// SQL_MEMLEAK_MSG
#define SQL_MEMLEAK_MSG_size "d"
#define SQL_MEMLEAK_MSG SQL_MEMLEAK_MSG__enum,SQL_MEMLEAK_MSG_size

// SQL_NOSHARESPACE_MSG
#define SQL_NOSHARESPACE_MSG_size ""
#define SQL_NOSHARESPACE_MSG SQL_NOSHARESPACE_MSG__enum,SQL_NOSHARESPACE_MSG_size

// SQL_CANNOTSHARE_MSG
#define SQL_CANNOTSHARE_MSG_size ""
#define SQL_CANNOTSHARE_MSG SQL_CANNOTSHARE_MSG__enum,SQL_CANNOTSHARE_MSG_size

// SQL_DBRDONLY_MSG
#define SQL_DBRDONLY_MSG_size ""
#define SQL_DBRDONLY_MSG SQL_DBRDONLY_MSG__enum,SQL_DBRDONLY_MSG_size

// SQL_SHAREOOM_MSG
#define SQL_SHAREOOM_MSG_size ""
#define SQL_SHAREOOM_MSG SQL_SHAREOOM_MSG__enum,SQL_SHAREOOM_MSG_size

// SQL_OPENFILE_MSG
#define SQL_OPENFILE_MSG_size "d"
#define SQL_OPENFILE_MSG SQL_OPENFILE_MSG__enum,SQL_OPENFILE_MSG_size

// SQL_SEEKHINT_MSG
#define SQL_SEEKHINT_MSG_size "d"
#define SQL_SEEKHINT_MSG SQL_SEEKHINT_MSG__enum,SQL_SEEKHINT_MSG_size

// SQL_SEEKERROR_MSG
#define SQL_SEEKERROR_MSG_size "d"
#define SQL_SEEKERROR_MSG SQL_SEEKERROR_MSG__enum,SQL_SEEKERROR_MSG_size

// SQL_READERROR_MSG
#define SQL_READERROR_MSG_size "d"
#define SQL_READERROR_MSG SQL_READERROR_MSG__enum,SQL_READERROR_MSG_size

// SQL_WRITEERROR_MSG
#define SQL_WRITEERROR_MSG_size "d"
#define SQL_WRITEERROR_MSG SQL_WRITEERROR_MSG__enum,SQL_WRITEERROR_MSG_size

// SQL_TRUNCATEERROR_MSG
#define SQL_TRUNCATEERROR_MSG_size "d"
#define SQL_TRUNCATEERROR_MSG SQL_TRUNCATEERROR_MSG__enum,SQL_TRUNCATEERROR_MSG_size

// SQL_COMMITERROR_MSG
#define SQL_COMMITERROR_MSG_size "d"
#define SQL_COMMITERROR_MSG SQL_COMMITERROR_MSG__enum,SQL_COMMITERROR_MSG_size

// SQL_GETFILESIZEERROR_MSG
#define SQL_GETFILESIZEERROR_MSG_size "d"
#define SQL_GETFILESIZEERROR_MSG SQL_GETFILESIZEERROR_MSG__enum,SQL_GETFILESIZEERROR_MSG_size

// SQL_LOCKERROR_MSG
#define SQL_LOCKERROR_MSG_size "ddd"
#define SQL_LOCKERROR_MSG SQL_LOCKERROR_MSG__enum,SQL_LOCKERROR_MSG_size


#endif // SQLITE3_TRC_GEN.H
