#include "mmi_features.h"
#include "custresdef.h"

<?xml version="1.0" encoding="UTF-8"?>

<APP id="APP_VENUS_HS_TODO">

#ifdef __MMI_VUI_HOMESCREEN_TODO__

    <!--Include Area-->
    <!-----------------------------------------------------String Resource Area----------------------------------------------------->
    <STRING id="VAPP_HS_STR_WG_TODO">"Todo"</STRING>
    <STRING id="VAPP_HS_STR_WG_TODO_NO_EVENTS">"No events"</STRING>

    <!-----------------------------------------------------Image Resource Area------------------------------------------------------>
	#define ROOT_PATH   CUST_IMG_PATH"\\\\MainLCD\\\\VUI\\\\HomeScreen\\\\"
	#define WIDGET_PATH ROOT_PATH"Widget\\\\"
	
    #define TODO_WIDGET_PATH         WIDGET_PATH"Todo\\\\"
    #define TODO_WIDGET_LOADING_PATH TODO_WIDGET_PATH"Loading\\\\"


    <IMAGE id="VAPP_HS_IMG_WG_ICON_TODO">WIDGET_PATH"Widgeticon_Todo.png"</IMAGE>
    
    <IMAGE id="VAPP_HS_IMG_WG_TODO_BG">TODO_WIDGET_PATH"Todo_BG.png"</IMAGE>
    <IMAGE id="VAPP_HS_IMG_WG_TODO_CAL_BG">TODO_WIDGET_PATH"Todo_Calendar_BG.png"</IMAGE>
    <IMAGE id="VAPP_HS_IMG_WG_TODO_NUM0">TODO_WIDGET_PATH"Todo_0.png"</IMAGE>
    <IMAGE id="VAPP_HS_IMG_WG_TODO_NUM1">TODO_WIDGET_PATH"Todo_1.png"</IMAGE>
    <IMAGE id="VAPP_HS_IMG_WG_TODO_NUM2">TODO_WIDGET_PATH"Todo_2.png"</IMAGE>
    <IMAGE id="VAPP_HS_IMG_WG_TODO_NUM3">TODO_WIDGET_PATH"Todo_3.png"</IMAGE>
    <IMAGE id="VAPP_HS_IMG_WG_TODO_NUM4">TODO_WIDGET_PATH"Todo_4.png"</IMAGE>
    <IMAGE id="VAPP_HS_IMG_WG_TODO_NUM5">TODO_WIDGET_PATH"Todo_5.png"</IMAGE>
    <IMAGE id="VAPP_HS_IMG_WG_TODO_NUM6">TODO_WIDGET_PATH"Todo_6.png"</IMAGE>
    <IMAGE id="VAPP_HS_IMG_WG_TODO_NUM7">TODO_WIDGET_PATH"Todo_7.png"</IMAGE>
    <IMAGE id="VAPP_HS_IMG_WG_TODO_NUM8">TODO_WIDGET_PATH"Todo_8.png"</IMAGE>
    <IMAGE id="VAPP_HS_IMG_WG_TODO_NUM9">TODO_WIDGET_PATH"Todo_9.png"</IMAGE>
    
    <IMAGE id="VAPP_HS_IMG_WG_TODO_MONTH1">TODO_WIDGET_PATH"Todo_Jan.png"</IMAGE>
	<IMAGE id="VAPP_HS_IMG_WG_TODO_MONTH2">TODO_WIDGET_PATH"Todo_Feb.png"</IMAGE>
	<IMAGE id="VAPP_HS_IMG_WG_TODO_MONTH3">TODO_WIDGET_PATH"Todo_Mar.png"</IMAGE>
	<IMAGE id="VAPP_HS_IMG_WG_TODO_MONTH4">TODO_WIDGET_PATH"Todo_Apr.png"</IMAGE>
	<IMAGE id="VAPP_HS_IMG_WG_TODO_MONTH5">TODO_WIDGET_PATH"Todo_May.png"</IMAGE>
	<IMAGE id="VAPP_HS_IMG_WG_TODO_MONTH6">TODO_WIDGET_PATH"Todo_Jun.png"</IMAGE>
	<IMAGE id="VAPP_HS_IMG_WG_TODO_MONTH7">TODO_WIDGET_PATH"Todo_Jul.png"</IMAGE>
	<IMAGE id="VAPP_HS_IMG_WG_TODO_MONTH8">TODO_WIDGET_PATH"Todo_Aug.png"</IMAGE>
	<IMAGE id="VAPP_HS_IMG_WG_TODO_MONTH9">TODO_WIDGET_PATH"Todo_Sep.png"</IMAGE>
	<IMAGE id="VAPP_HS_IMG_WG_TODO_MONTH10">TODO_WIDGET_PATH"Todo_Oct.png"</IMAGE>
	<IMAGE id="VAPP_HS_IMG_WG_TODO_MONTH11">TODO_WIDGET_PATH"Todo_Nov.png"</IMAGE>
	<IMAGE id="VAPP_HS_IMG_WG_TODO_MONTH12">TODO_WIDGET_PATH"Todo_Dec.png"</IMAGE>

	<IMAGE id="VAPP_HS_IMG_WG_TODO_LOADING_BG">TODO_WIDGET_PATH"LOAD_BG.png"</IMAGE>
	<IMAGE id="VAPP_HS_IMG_WG_TODO_LOADING0">TODO_WIDGET_LOADING_PATH"0.png"</IMAGE>	
	<IMAGE id="VAPP_HS_IMG_WG_TODO_LOADING1">TODO_WIDGET_LOADING_PATH"1.png"</IMAGE>
	<IMAGE id="VAPP_HS_IMG_WG_TODO_LOADING2">TODO_WIDGET_LOADING_PATH"2.png"</IMAGE>
	<IMAGE id="VAPP_HS_IMG_WG_TODO_LOADING3">TODO_WIDGET_LOADING_PATH"3.png"</IMAGE>
	<IMAGE id="VAPP_HS_IMG_WG_TODO_LOADING4">TODO_WIDGET_LOADING_PATH"4.png"</IMAGE>
	<IMAGE id="VAPP_HS_IMG_WG_TODO_LOADING5">TODO_WIDGET_LOADING_PATH"5.png"</IMAGE>
	<IMAGE id="VAPP_HS_IMG_WG_TODO_LOADING6">TODO_WIDGET_LOADING_PATH"6.png"</IMAGE>
	<IMAGE id="VAPP_HS_IMG_WG_TODO_LOADING7">TODO_WIDGET_LOADING_PATH"7.png"</IMAGE>
	<IMAGE id="VAPP_HS_IMG_WG_TODO_LOADING_TOTAL">TODO_WIDGET_LOADING_PATH"7.png"</IMAGE>

#endif /* __MMI_VUI_HOMESCREEN_TODO__ */

</APP>

