#include "CustDataRes.h"
#include "ResCompressConfig.h"

#ifndef __MMI_RESOURCE_IMAGE_THIRD_ROM__
#ifdef __MMI_RESOURCE_LZMA_IMAGE_GROUP_COMPRESS__

#include "CustResDef.h"
#include "CustImgGroupDataHW.h"
const unsigned short  mtk_CurrMaxGroupsNum = 85;

const CUSTOM_IMAGE	mtk_nCustGroupNames[]={
    (U8*)&image_group_0,
    (U8*)&image_group_1,
    (U8*)&image_group_2,
    (U8*)&image_group_3,
    (U8*)&image_group_4,
    (U8*)&image_group_5,
    (U8*)&image_group_6,
    (U8*)&image_group_7,
    (U8*)&image_group_8,
    (U8*)&image_group_9,
    (U8*)&image_group_10,
    (U8*)&image_group_11,
    (U8*)&image_group_12,
    (U8*)&image_group_13,
    (U8*)&image_group_14,
    (U8*)&image_group_15,
    (U8*)&image_group_16,
    (U8*)&image_group_17,
    (U8*)&image_group_18,
    (U8*)&image_group_19,
    (U8*)&image_group_20,
    (U8*)&image_group_21,
    (U8*)&image_group_22,
    (U8*)&image_group_23,
    (U8*)&image_group_24,
    (U8*)&image_group_25,
    (U8*)&image_group_26,
    (U8*)&image_group_27,
    (U8*)&image_group_28,
    (U8*)&image_group_29,
    (U8*)&image_group_30,
    (U8*)&image_group_31,
    (U8*)&image_group_32,
    (U8*)&image_group_33,
    (U8*)&image_group_34,
    (U8*)&image_group_35,
    (U8*)&image_group_36,
    (U8*)&image_group_37,
    (U8*)&image_group_38,
    (U8*)&image_group_39,
    (U8*)&image_group_40,
    (U8*)&image_group_41,
    (U8*)&image_group_42,
    (U8*)&image_group_43,
    (U8*)&image_group_44,
    (U8*)&image_group_45,
    (U8*)&image_group_46,
    (U8*)&image_group_47,
    (U8*)&image_group_48,
    (U8*)&image_group_49,
    (U8*)&image_group_50,
    (U8*)&image_group_51,
    (U8*)&image_group_52,
    (U8*)&image_group_53,
    (U8*)&image_group_54,
    (U8*)&image_group_55,
    (U8*)&image_group_56,
    (U8*)&image_group_57,
    (U8*)&image_group_58,
    (U8*)&image_group_59,
    (U8*)&image_group_60,
    (U8*)&image_group_61,
    (U8*)&image_group_62,
    (U8*)&image_group_63,
    (U8*)&image_group_64,
    (U8*)&image_group_65,
    (U8*)&image_group_66,
    (U8*)&image_group_67,
    (U8*)&image_group_68,
    (U8*)&image_group_69,
    (U8*)&image_group_70,
    (U8*)&image_group_71,
    (U8*)&image_group_72,
    (U8*)&image_group_73,
    (U8*)&image_group_74,
    (U8*)&image_group_75,
    (U8*)&image_group_76,
    (U8*)&image_group_77,
    (U8*)&image_group_78,
    (U8*)&image_group_79,
    (U8*)&image_group_80,
    (U8*)&image_group_81,
    (U8*)&image_group_82,
    (U8*)&image_group_83,
    (U8*)&image_group_84
};

#ifdef __MMI_RESOURCE_UT_SIMPLE_CACHE_SUPPORT__
const CUSTOM_IMAGE	mtk_nCustGroupCacheNames[]={
    (U8*)&cache_image_group_0,
    (U8*)&cache_image_group_1,
    (U8*)&cache_image_group_2,
    (U8*)&cache_image_group_3,
    (U8*)&cache_image_group_4,
    (U8*)&cache_image_group_5,
    (U8*)&cache_image_group_6,
    (U8*)&cache_image_group_7,
    (U8*)&cache_image_group_8,
    (U8*)&cache_image_group_9,
    (U8*)&cache_image_group_10,
    (U8*)&cache_image_group_11,
    (U8*)&cache_image_group_12,
    (U8*)&cache_image_group_13,
    (U8*)&cache_image_group_14,
    (U8*)&cache_image_group_15,
    (U8*)&cache_image_group_16,
    (U8*)&cache_image_group_17,
    (U8*)&cache_image_group_18,
    (U8*)&cache_image_group_19,
    (U8*)&cache_image_group_20,
    (U8*)&cache_image_group_21,
    (U8*)&cache_image_group_22,
    (U8*)&cache_image_group_23,
    (U8*)&cache_image_group_24,
    (U8*)&cache_image_group_25,
    (U8*)&cache_image_group_26,
    (U8*)&cache_image_group_27,
    (U8*)&cache_image_group_28,
    (U8*)&cache_image_group_29,
    (U8*)&cache_image_group_30,
    (U8*)&cache_image_group_31,
    (U8*)&cache_image_group_32,
    (U8*)&cache_image_group_33,
    (U8*)&cache_image_group_34,
    (U8*)&cache_image_group_35,
    (U8*)&cache_image_group_36,
    (U8*)&cache_image_group_37,
    (U8*)&cache_image_group_38,
    (U8*)&cache_image_group_39,
    (U8*)&cache_image_group_40,
    (U8*)&cache_image_group_41,
    (U8*)&cache_image_group_42,
    (U8*)&cache_image_group_43,
    (U8*)&cache_image_group_44,
    (U8*)&cache_image_group_45,
    (U8*)&cache_image_group_46,
    (U8*)&cache_image_group_47,
    (U8*)&cache_image_group_48,
    (U8*)&cache_image_group_49,
    (U8*)&cache_image_group_50,
    (U8*)&cache_image_group_51,
    (U8*)&cache_image_group_52,
    (U8*)&cache_image_group_53,
    (U8*)&cache_image_group_54,
    (U8*)&cache_image_group_55,
    (U8*)&cache_image_group_56,
    (U8*)&cache_image_group_57,
    (U8*)&cache_image_group_58,
    (U8*)&cache_image_group_59,
    (U8*)&cache_image_group_60,
    (U8*)&cache_image_group_61,
    (U8*)&cache_image_group_62,
    (U8*)&cache_image_group_63,
    (U8*)&cache_image_group_64,
    (U8*)&cache_image_group_65,
    (U8*)&cache_image_group_66,
    (U8*)&cache_image_group_67,
    (U8*)&cache_image_group_68,
    (U8*)&cache_image_group_69,
    (U8*)&cache_image_group_70,
    (U8*)&cache_image_group_71,
    (U8*)&cache_image_group_72,
    (U8*)&cache_image_group_73,
    (U8*)&cache_image_group_74,
    (U8*)&cache_image_group_75,
    (U8*)&cache_image_group_76,
    (U8*)&cache_image_group_77,
    (U8*)&cache_image_group_78,
    (U8*)&cache_image_group_79,
    (U8*)&cache_image_group_80,
    (U8*)&cache_image_group_81,
    (U8*)&cache_image_group_82,
    (U8*)&cache_image_group_83,
    (U8*)&cache_image_group_84
};

#endif //__MMI_RESOURCE_UT_SIMPLE_CACHE_SUPPORT__


#endif  //__MMI_RESOURCE_LZMA_IMAGE_GROUP_COMPRESS__


#endif  // __MMI_RESOURCE_IMAGE_THIRD_ROM__
