/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_menu_misc_data.c
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   MTK resgenerator XML parser
 *
 *******************************************************************************/
#include "MMIDataType.h"
#include "CustMenuRes.h"
#include "mmi_rp_menu_misc_def.h"

/* Application specified header files for MainMenu/Image IDs declared elsewhere. */

/* Count of all main menu IDs */
const U32 mmi_rg_menu_mainmenuid_total = 13;

/* Array of Image IDs for main menu IDs */
/* 1) Main menu ID */
/* 2) List image ID */
/* 3) Matrix image ID */
/* 4) Page image ID */
/* 5) Venus1 image ID */
/* 6) Venus2 image ID */
/* 7) Matrix highlight image ID */
/* 8) Matrix controlled area image ID */
/* 9) Venus1 highlight image ID */
/* 10) Title image ID */
const mmi_rg_menu_mainmenu_img_id_struct mmi_rg_menu_mainmenu_img_id_array[] = {
    { 48512, 0, 48525, 0, 0, 0, 48541, 0, 0, 48574},
    { 48513, 0, 48514, 0, 0, 0, 48530, 0, 0, 48562},
    { 48514, 0, 48516, 0, 0, 0, 48532, 0, 0, 48564},
    { 48515, 0, 48526, 0, 0, 0, 48542, 0, 0, 48575},
    { 48516, 0, 48523, 0, 0, 0, 48539, 0, 0, 48572},
    { 48517, 0, 48524, 0, 0, 0, 48540, 0, 0, 48573},
    { 48518, 0, 48520, 0, 0, 0, 48537, 0, 0, 48571},
    { 48519, 0, 48517, 0, 0, 0, 48533, 0, 0, 48566},
    { 48520, 0, 48518, 0, 0, 0, 48534, 0, 0, 48567},
    { 48523, 0, 48527, 0, 0, 0, 48543, 0, 0, 0},
    { 48522, 0, 48523, 0, 0, 0, 48539, 0, 0, 48572},
    { 47923, 0, 48515, 0, 0, 0, 48531, 0, 0, 48563},
    { 40270, 0, 48522, 0, 0, 0, 48538, 0, 0, 48568},
};

/* Default menu ID associated parent with menu IDs */
/* Pair of 'parent menu ID', 'default menu ID' */
const mmi_rg_menu_default_struct mmi_rg_menu_default_menu_array[] = {
    {44916, 44906},
};

/* Arrays of menu IDs for Group IDs */
const U16 menu_group_editor[] = {26131, 26132, 26133, 0xFFFF};
const U16 menu_group_editor_cui_options[] = {26135, 26136, 0xFFFF};

/* Menu group array associated with Group ID enum */
const U16 *mmi_rg_menu_group[] = {
    menu_group_editor,
    menu_group_editor_cui_options,
    NULL
};

/* Application's notify handlers */
const mmi_rg_notify_hdlr_struct mmi_frm_const_notify_handler_table[] = {
   {0, NULL}
};
