/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_file_type_table.c
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   MTK resgenerator XML parser
 *
 *******************************************************************************/
#define _MMI_RP_FILE_TYPE_DEF_C

#include "MMIDataType.h"
#include "CustMenuRes.h"
#include "mmi_rp_file_type_def.h"
#include "filemgrsrvgprot.h"
#include "mmi_rp_all_defs.h"

#include "GlobalResDef.h"	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
#include "FileMgrServiceResDef.h"	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
#include "ImageViewerResDef.h"	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
#include "ABRepeaterResDef.h"	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
#include "VdoPlyResDef.h"	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
#include "CatScreenBrowserResDef.h"	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
#include "mmi_rp_app_profiles_def.h"	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
#include "mmi_rp_app_font_manager_def.h"	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
#include "mmi_rp_app_imageviewer_def.h"	/* .\mtkapp\ImageView\ImageViewRes\imgview.res */
#include "mmi_rp_app_soundrecorder_def.h"	/* .\mtkapp\Sndrec\SndrecRes\Sndrec.res */

typedef struct {
    U16            file_type;
    const char     *extension;
    const WCHAR    *extension_ucs2;
} filetypes_extension_struct;

typedef struct {
    U16            file_type;
    mmi_img_id     small_icon;
    mmi_img_id     large_icon;
} filetypes_icons_struct;

typedef struct {
    U16            file_type;
    mmi_menu_id    option;
    mmi_menu_id    send_option;
    mmi_menu_id    use_option;
} filetypes_option_struct;

typedef struct {
    U16            group_type;
    U16            begin_id;
    U16            end_id;
} filetypes_group_range_struct;

typedef void (*filetypes_option_enabler_func_ptr)(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);
typedef void (*filetypes_option_handler_func_ptr)(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);
typedef void (*filetypes_option_hint_func_ptr)(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo, WCHAR* hint_buffer, S32 hint_buffer_size);

typedef struct {
    mmi_menu_id    option;
    filetypes_option_handler_func_ptr handler;
    filetypes_option_enabler_func_ptr enabler;
} filetypes_opt_hdlr_struct;

typedef struct {
    mmi_menu_id    option;
    filetypes_option_hint_func_ptr hint_hdlr;
} filetypes_opt_hint_struct;

const filetypes_extension_struct g_filetypes_extension_table[] = 
{
    {FMGR_TYPE_BMP, "BMP", L"BMP"}
    ,{FMGR_TYPE_JPG, "JPG", L"JPG"}
    ,{FMGR_TYPE_JPEG, "JPEG\0", L"JPEG"}
    ,{FMGR_TYPE_GIF, "GIF", L"GIF"}
    ,{FMGR_TYPE_PNG, "PNG", L"PNG"}
    ,{FMGR_TYPE_WBMP, "WBMP\0", L"WBMP"}
    ,{FMGR_TYPE_WBM, "WBM", L"WBM"}
    ,{FMGR_TYPE_EMS, "EMS", L"EMS"}
    ,{FMGR_TYPE_ANM, "ANM", L"ANM"}
    ,{FMGR_TYPE_IMY, "IMY", L"IMY"}
    ,{FMGR_TYPE_MID, "MID", L"MID"}
    ,{FMGR_TYPE_MIDI, "MIDI\0", L"MIDI"}
    ,{FMGR_TYPE_WAV, "WAV", L"WAV"}
    ,{FMGR_TYPE_AMR, "AMR", L"AMR"}
    ,{FMGR_TYPE_AAC, "AAC", L"AAC"}
    ,{FMGR_TYPE_DAF, "MP3", L"MP3"}
    ,{FMGR_TYPE_VM, "VM\0", L"VM"}
    ,{FMGR_TYPE_3GP, "3GP", L"3GP"}
    ,{FMGR_TYPE_MP4, "MP4", L"MP4"}
    ,{FMGR_TYPE_3G2, "3G2", L"3G2"}
    ,{FMGR_TYPE_AVI, "AVI", L"AVI"}
    ,{FMGR_TYPE_MKV, "MKV", L"MKV"}
    ,{FMGR_TYPE_WEBM, "WEBM\0", L"WEBM"}
    ,{FMGR_TYPE_MOT, "MOT", L"MOT"}
    ,{FMGR_TYPE_KMV, "KMV", L"KMV"}
    ,{FMGR_TYPE_QKMV, "QKMV\0", L"QKMV"}
    ,{FMGR_TYPE_MRE_TXT, "TXT", L"TXT"}
    ,{FMGR_TYPE_VCF, "VCF", L"VCF"}
    ,{FMGR_TYPE_VCS, "VCS", L"VCS"}
    ,{FMGR_TYPE_LRC, "LRC", L"LRC"}
    ,{FMGR_TYPE_DCF, "DCF", L"DCF"}
    ,{FMGR_TYPE_DM, "DM\0", L"DM"}
    ,{FMGR_TYPE_VXP, "VXP", L"VXP"}
    ,{FMGR_TYPE_VPP, "VPP", L"VPP"}
};
const S32 g_filetypes_extension_table_size = sizeof(g_filetypes_extension_table) / sizeof(filetypes_extension_struct);

const filetypes_icons_struct g_filetypes_icons_table[] = 
{
    {FMGR_TYPE_UNKNOWN, IMG_ID_FMGR_ICON_FILE_TYPE_UNKNOWN, IMG_ID_FMGR_FILE_TYPE_UNKNOWN}	/* .\MtkApp\FileMgr\FileMgrRes\000_FileMgr.res */
    ,{FMGR_TYPE_FOLDER, IMG_ID_FMGR_ICON_FILE_TYPE_FOLDER, IMG_ID_FMGR_FILE_TYPE_FOLDER}	/* .\MtkApp\FileMgr\FileMgrRes\000_FileMgr.res */
    ,{FMGR_TYPE_BMP, 0, IMG_ID_FMGR_FILE_TYPE_BMP}	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
    ,{FMGR_TYPE_JPG, 0, IMG_ID_FMGR_FILE_TYPE_JPG}	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
    ,{FMGR_TYPE_JPEG, 0, IMG_ID_FMGR_FILE_TYPE_JPG}	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
    ,{FMGR_TYPE_GIF, 0, IMG_ID_FMGR_FILE_TYPE_GIF}	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
    ,{FMGR_TYPE_PNG, 0, IMG_ID_FMGR_FILE_TYPE_PNG}	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
    ,{FMGR_TYPE_WBMP, 0, IMG_ID_FMGR_FILE_TYPE_WBMP}	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
    ,{FMGR_TYPE_WBM, 0, IMG_ID_FMGR_FILE_TYPE_WBMP}	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
    ,{FMGR_TYPE_EMS, 0, IMG_ID_FMGR_FILE_TYPE_EMS}	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
    ,{FMGR_TYPE_ANM, 0, IMG_ID_FMGR_FILE_TYPE_ANM}	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
    ,{FMGR_TYPE_IMY, 0, IMG_ID_FMGR_FILE_TYPE_IMY}	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
    ,{FMGR_TYPE_MID, 0, IMG_ID_FMGR_FILE_TYPE_MID}	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
    ,{FMGR_TYPE_MIDI, 0, IMG_ID_FMGR_FILE_TYPE_MID}	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
    ,{FMGR_TYPE_WAV, 0, IMG_ID_FMGR_FILE_TYPE_WAV}	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
    ,{FMGR_TYPE_AMR, 0, IMG_ID_FMGR_FILE_TYPE_AMR}	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
    ,{FMGR_TYPE_AAC, 0, IMG_ID_FMGR_FILE_TYPE_AAC}	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
    ,{FMGR_TYPE_DAF, 0, IMG_ID_FMGR_FILE_TYPE_DAF}	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
    ,{FMGR_TYPE_VM, 0, IMG_ID_FMGR_FILE_TYPE_VM}	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
    ,{FMGR_TYPE_3GP, 0, IMG_ID_FMGR_FILE_TYPE_MP4}	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
    ,{FMGR_TYPE_MP4, 0, IMG_ID_FMGR_FILE_TYPE_MP4}	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
    ,{FMGR_TYPE_3G2, 0, IMG_ID_FMGR_FILE_TYPE_MP4}	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
    ,{FMGR_TYPE_AVI, 0, IMG_ID_FMGR_FILE_TYPE_AVI}	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
    ,{FMGR_TYPE_MKV, 0, IMG_ID_FMGR_FILE_TYPE_MP4}	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
    ,{FMGR_TYPE_WEBM, 0, IMG_ID_FMGR_FILE_TYPE_MP4}	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
    ,{FMGR_TYPE_MOT, 0, IMG_ID_FMGR_FILE_TYPE_MP4}	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
    ,{FMGR_TYPE_KMV, 0, IMG_ID_FMGR_FILE_TYPE_MP4}	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
    ,{FMGR_TYPE_QKMV, 0, IMG_ID_FMGR_FILE_TYPE_MP4}	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
    ,{FMGR_TYPE_VCF, IMG_ID_FMGR_ICON_FILE_TYPE_VCF, IMG_ID_FMGR_FILE_TYPE_VCF}	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
    ,{FMGR_TYPE_VCS, IMG_ID_FMGR_ICON_FILE_TYPE_VCS, IMG_ID_FMGR_FILE_TYPE_VCS}	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
    ,{FMGR_TYPE_VXP, IMAGE_MRE_SMALL_ICON, IMAGE_MRE_LARGE_ICON}	/* ..\mre\res\mre.res */
    ,{FMGR_TYPE_VPP, IMAGE_MRE_SMALL_ICON, IMAGE_MRE_LARGE_ICON}	/* ..\mre\res\mre.res */

    ,{FMGR_GROUP_IMAGE, IMG_ID_FMGR_ICON_FILE_TYPE_IMG, 0}	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
    ,{FMGR_GROUP_AUDIO, IMG_ID_FMGR_ICON_FILE_TYPE_AUD, 0}	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
    ,{FMGR_GROUP_VIDEO, IMG_ID_FMGR_ICON_FILE_TYPE_VDO, 0}	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
};
const S32 g_filetypes_icons_table_size = sizeof(g_filetypes_icons_table) / sizeof(filetypes_icons_struct);

const filetypes_option_struct g_filetypes_option_table[] = 
{
    {FMGR_TYPE_UNKNOWN, MENU_ID_FMGR_GEN_TYPE_OPTIONS, MENU_ID_FMGR_GEN_SEND_OPTION, 0}	/* .\MtkApp\FileMgr\FileMgrRes\000_FileMgr.res */
    ,{FMGR_TYPE_FOLDER, MENU_ID_FMGR_FOLDER_OPTIONS, 0, 0}	/* .\MtkApp\FileMgr\FileMgrRes\000_FileMgr.res */
    ,{FMGR_TYPE_VCF, 0, MENU_ID_FMGR_VCARD_FWD_SEND_OPTION, MENU_ID_FMGR_VCARD_FWD_USE_OPTION}	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
    ,{FMGR_TYPE_VCS, 0, MENU_ID_FMGR_VCAL_FWD_SEND_OPTION, MENU_ID_FMGR_VCAL_FWD_USE_OPTION}	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
    ,{FMGR_TYPE_VXP, MENU_ID_FMGR_MRE_TYPE_OPTIONS, 0, 0}	/* ..\mre\res\mre.res */
    ,{FMGR_TYPE_VPP, MENU_ID_FMGR_MRE_TYPE_OPTIONS, 0, 0}	/* ..\mre\res\mre.res */

    ,{FMGR_GROUP_IMAGE, MENU_ID_FMGR_IMG_TYPE_OPTIONS, MENU_ID_FMGR_IMG_FWD_SEND_OPTION, MENU_ID_FMGR_IMG_FWD_USE_OPTION}	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
    ,{FMGR_GROUP_AUDIO, MENU_ID_FMGR_AUD_TYPE_OPTIONS, MENU_ID_FMGR_AUD_FWD_SEND_OPTION, MENU_ID_FMGR_AUD_FWD_USE_OPTION}	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
    ,{FMGR_GROUP_VIDEO, MENU_ID_FMGR_VID_TYPE_OPTIONS, MENU_ID_FMGR_VID_FWD_SEND_OPTION, MENU_ID_FMGR_VID_FWD_USE_OPTION}	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
};
const S32 g_filetypes_option_table_size = sizeof(g_filetypes_option_table) / sizeof(filetypes_option_struct);

const filetypes_group_range_struct g_filetypes_group_range_table[] = 
{
    {FMGR_GROUP_COMMON, FMGR_TYPE_UNKNOWN, FMGR_TYPE_HYPER_LINK}	/* .\MtkApp\FileMgr\FileMgrRes\000_FileMgr.res */
    ,{FMGR_GROUP_IMAGE, FMGR_TYPE_BMP, FMGR_TYPE_ANM}	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
    ,{FMGR_GROUP_AUDIO, FMGR_TYPE_IMY, FMGR_TYPE_VM}	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
    ,{FMGR_GROUP_VIDEO, FMGR_TYPE_3GP, FMGR_TYPE_QKMV}	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
    ,{FMGR_GROUP_MRE_TXT, FMGR_TYPE_MRE_TXT, FMGR_TYPE_MRE_TXT}	/* .\Service\FileMgrSrv\FileMgrSrvRes\FileTypes.res */
};
const S32 g_filetypes_group_range_table_size = sizeof(g_filetypes_group_range_table) / sizeof(filetypes_group_range_struct);


extern void mmi_imgview_file_type_handler(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);
extern void mmi_imgview_view_handler(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);
extern void mmi_umms_fmgr_to_mms_hdlr(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);
extern void mmi_fmgr_vxp_option_hdlr(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);
extern void mmi_fmgr_vxp_option_hdlr(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);
extern void mmi_fmgr_to_power_on_display_hdlr(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);
extern void mmi_fmgr_to_power_off_display_hdlr(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);
extern void mmi_prof_app_filemgr_option_hdlr(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);
extern void mmi_prof_app_filemgr_option_hdlr(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);
extern void mmi_prof_app_filemgr_option_hdlr(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);
extern void mmi_prof_app_filemgr_option_hdlr(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);
extern void mmi_prof_app_filemgr_option_hdlr(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);
extern void mmi_ems_fmgr_send_by_ems_hdlr(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);
extern void mmi_vcal_fmgr_use_handler(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);
extern void mmi_vcal_fmgr_use_handler(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);
extern void mmi_vobj_fmgr_use_handler(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);
extern void mmi_fmgr_to_wallpaper_hdlr(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);

extern void mmi_fmgr_general_option_enabler(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);
extern void mmi_fmgr_general_option_enabler(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);
extern void mmi_fmgr_general_option_enabler(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);
extern void mmi_fmgr_general_option_enabler(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);
extern void mmi_fmgr_option_audio_enabler_ex(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);
extern void mmi_fmgr_option_image_enabler_ex(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);
extern void mmi_imgview_file_type_enabler(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);
extern void mmi_imgview_view_enabler(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);
extern void mmi_fmgr_option_imgviewer_enabler(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);
extern void mmi_fmgr_empty_option_imgviewer_enabler(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);
extern void mmi_umms_fmgr_forward_mms_enabler(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);
extern void mmi_fmgr_vxp_option_enabler(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);
extern void mmi_fmgr_vxp_option_enabler(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);
extern void mmi_phnset_display_use_as_enabler(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);
extern void mmi_phnset_display_use_as_enabler(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);
extern void mmi_prof_app_filemgr_option_enabler(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);
extern void mmi_prof_app_filemgr_option_enabler(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);
extern void mmi_prof_app_filemgr_option_enabler(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);
extern void mmi_prof_app_filemgr_option_enabler(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);
extern void mmi_prof_app_filemgr_option_enabler(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);
extern void mmi_ems_fmgr_send_by_ems_enabler(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);
extern void mmi_sndrec_option_enabler(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);
extern void mmi_vcal_fmgr_use_enabler(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);
extern void mmi_vcal_fmgr_use_enabler(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);
extern void mmi_vobj_fmgr_use_enabler(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);
extern void mmi_phnset_display_use_as_enabler(mmi_menu_id item_id, const WCHAR* filepath, const srv_fmgr_fileinfo_struct* fileinfo);

const filetypes_opt_hdlr_struct g_filetypes_opt_hdlr_table[] = 
{
    {MENU_ID_FMGR_FOLDER_OPTIONS, NULL, mmi_fmgr_general_option_enabler}	/* .\MtkApp\FileMgr\FileMgrRes\000_FileMgr.res */
    ,{MENU_ID_FMGR_GEN_OPTION_FORWARD_SEND, NULL, mmi_fmgr_general_option_enabler}	/* .\MtkApp\FileMgr\FileMgrRes\000_FileMgr.res */
    ,{MENU_ID_FMGR_GEN_OPTION_FORWARD_USE, NULL, mmi_fmgr_general_option_enabler}	/* .\MtkApp\FileMgr\FileMgrRes\000_FileMgr.res */
    ,{MENU_ID_FMGR_GEN_OPTION_MORE_RITS, NULL, mmi_fmgr_general_option_enabler}	/* .\MtkApp\FileMgr\FileMgrRes\000_FileMgr.res */
    ,{MENU_ID_FMGR_AUD_TYPE_OPTIONS, NULL, mmi_fmgr_option_audio_enabler_ex}	/* .\MtkApp\FileMgr\FileMgrRes\000_FileMgr.res */
    ,{MENU_ID_FMGR_IMG_TYPE_OPTIONS, NULL, mmi_fmgr_option_image_enabler_ex}	/* .\MtkApp\FileMgr\FileMgrRes\000_FileMgr.res */
    ,{MENU_ID_IMGVIEW_OPTION_IMG_INFORMATION, mmi_imgview_file_type_handler, mmi_imgview_file_type_enabler}	/* .\mtkapp\ImageView\ImageViewRes\imgview.res */
    ,{MENU_ID_IMGVIEW_OPTION_IMG_VIEW, mmi_imgview_view_handler, mmi_imgview_view_enabler}	/* .\mtkapp\ImageView\ImageViewRes\imgview.res */
    ,{MENU_ID_IMGVIEW_FILE_OPTION, NULL, mmi_fmgr_option_imgviewer_enabler}	/* .\mtkapp\ImageView\ImageViewRes\imgview.res */
    ,{MENU_ID_IMGVIEW_EMPTY_FOLDER_OPTION, NULL, mmi_fmgr_empty_option_imgviewer_enabler}	/* .\mtkapp\ImageView\ImageViewRes\imgview.res */
    ,{MENU_ID_FMGR_FWD_MMS, mmi_umms_fmgr_to_mms_hdlr, mmi_umms_fmgr_forward_mms_enabler}	/* .\Service\UmmsSrv\MMSSrvRes\MMSSrv.res */
    ,{MENU_ID_FMGR_MRE_FILE_OPEN, mmi_fmgr_vxp_option_hdlr, mmi_fmgr_vxp_option_enabler}	/* ..\mre\res\mre.res */
    ,{MENU_ID_FMGR_MRE_OPTION_INSTALL, mmi_fmgr_vxp_option_hdlr, mmi_fmgr_vxp_option_enabler}	/* ..\mre\res\mre.res */
    ,{MENU_ID_FMGR_FWD_POWER_ON, mmi_fmgr_to_power_on_display_hdlr, mmi_phnset_display_use_as_enabler}	/* .\mmi\Setting\SettingRes\PowerOnOffDisplay.res */
    ,{MENU_ID_FMGR_FWD_POWER_OFF, mmi_fmgr_to_power_off_display_hdlr, mmi_phnset_display_use_as_enabler}	/* .\mmi\Setting\SettingRes\PowerOnOffDisplay.res */
    ,{MENU_ID_PROF_USE_AS_RINGTONE, mmi_prof_app_filemgr_option_hdlr, mmi_prof_app_filemgr_option_enabler}	/* .\mmi\PROFILES\Profiles_Res\Profiles.res */
    ,{MENU_ID_PROF_USE_AS_SIM1_RINGTONE, mmi_prof_app_filemgr_option_hdlr, mmi_prof_app_filemgr_option_enabler}	/* .\mmi\PROFILES\Profiles_Res\Profiles.res */
    ,{MENU_ID_PROF_USE_AS_SIM2_RINGTONE, mmi_prof_app_filemgr_option_hdlr, mmi_prof_app_filemgr_option_enabler}	/* .\mmi\PROFILES\Profiles_Res\Profiles.res */
    ,{MENU_ID_PROF_USE_AS_SIM3_RINGTONE, mmi_prof_app_filemgr_option_hdlr, mmi_prof_app_filemgr_option_enabler}	/* .\mmi\PROFILES\Profiles_Res\Profiles.res */
    ,{MENU_ID_PROF_USE_AS_SIM4_RINGTONE, mmi_prof_app_filemgr_option_hdlr, mmi_prof_app_filemgr_option_enabler}	/* .\mmi\PROFILES\Profiles_Res\Profiles.res */
    ,{MENU_ID_SMS_FMGR_FWD_EMS, mmi_ems_fmgr_send_by_ems_hdlr, mmi_ems_fmgr_send_by_ems_enabler}	/* .\mmi\messages\messagesres\SmsAppRes.res */
    ,{MENU_ID_SNDREC_REC_OPTION, NULL, mmi_sndrec_option_enabler}	/* .\mtkapp\Sndrec\SndrecRes\Sndrec.res */
    ,{MENU_VCLNDR_USE_AS_EVENT, mmi_vcal_fmgr_use_handler, mmi_vcal_fmgr_use_enabler}	/* .\mtkapp\vObjects\vObjectRes\vCalendar.res */
    ,{MENU_VCLNDR_USE_AS_TASK, mmi_vcal_fmgr_use_handler, mmi_vcal_fmgr_use_enabler}	/* .\mtkapp\vObjects\vObjectRes\vCalendar.res */
    ,{MENU_ID_VOBJ_FMGR_SEND_SMS, mmi_vobj_fmgr_use_handler, mmi_vobj_fmgr_use_enabler}	/* .\mtkapp\vObjects\vObjectRes\vObjects.res */
    ,{MENU_ID_FMGR_FWD_WALLPAPER, mmi_fmgr_to_wallpaper_hdlr, mmi_phnset_display_use_as_enabler}	/* .\mmi\Setting\SettingRes\Wallpaper.res */
};
const S32 g_filetypes_opt_hdlr_table_size = sizeof(g_filetypes_opt_hdlr_table) / sizeof(filetypes_opt_hdlr_struct);


const filetypes_opt_hint_struct g_filetypes_opt_hint_table[] = 
{
    {0, NULL}
};
const S32 g_filetypes_opt_hint_table_size = sizeof(g_filetypes_opt_hint_table) / sizeof(filetypes_opt_hint_struct);

