#include "mmi_features.h"
#include "custresdef.h"

<?xml version="1.0" encoding="UTF-8"?>

<APP id="VAPP_FMGR" name="STR_ID_VAPP_FMGR_APP_MAINMENU" package_proc="vapp_fmgr_proc" package_name="native.mtk.fmgr" img="IMG_ID_VAPP_FMGR_MAINMENU_ICN" launch="vapp_fmgr_launch" type="venus">
    <INCLUDE file="GlobalResDef.h"/>
    <INCLUDE file="Mmi_rp_srv_venus_component_tool_bar_def.h"/>
    <INCLUDE file="Mmi_rp_vcui_fmgr_def.h"/>
#ifdef __MMI_OPP_SUPPORT__
    <MEMORY extra_base="$(VAPP_FMGR_IMAGE_DETAIL_THUMB_MEMORY_SIZE)+$(SRV_FMGR_FOLDER_FILELIST_MEM_SIZE)" cui="max(VCUI_FMGR, VCUI_BT_SEND_PREPARE)" heap="VAPP_FMGR_HEAP_SIZE" inc="FileMgrSrvGProt.h,vapp_fmgr_gprot.h"/>
#else
    <MEMORY extra_base="$(VAPP_FMGR_IMAGE_DETAIL_THUMB_MEMORY_SIZE)+$(SRV_FMGR_FOLDER_FILELIST_MEM_SIZE)" cui="VCUI_FMGR" heap="VAPP_FMGR_HEAP_SIZE" inc="FileMgrSrvGProt.h,vapp_fmgr_gprot.h"/>
#endif    

<!-- 
**************************************** Image section ****************************************
-->
    <IMAGE id="IMG_ID_VAPP_FMGR_TAB_CARD_ICN">RES_IMG_ROOT"\\\\FMGR\\\\TabIcon\\\\MemoryCard.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_FMGR_TAB_PHONE_ICN">RES_IMG_ROOT"\\\\FMGR\\\\TabIcon\\\\Phone.png"</IMAGE>
#if !defined(__MMI_ULTRA_SLIM_FILE_MANAGER__)
    <IMAGE id="IMG_ID_VAPP_FMGR_OPTION_OPEN">RES_IMG_ROOT"\\\\FMGR\\\\ToolbarIcon\\\\Open.png"</IMAGE>
#endif /* #if !defined(__MMI_ULTRA_SLIM_FILE_MANAGER__) */
    <IMAGE id="IMG_ID_VAPP_FMGR_STORAGE_REPORT">RES_IMG_ROOT"\\\\FMGR\\\\ToolbarIcon\\\\Storage_Report.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_FMGR_SHARE_BY_BT">RES_IMG_ROOT"\\\\FMGR\\\\ToolbarIcon\\\\BT.png"</IMAGE>
#if !defined(__MMI_ULTRA_SLIM_FILE_MANAGER__)
    <IMAGE id="IMG_ID_VAPP_FMGR_DETAIL_INFO">RES_IMG_ROOT"\\\\Common\\\\Button\\\\Details.png"</IMAGE>
#endif /* #if !defined(__MMI_ULTRA_SLIM_FILE_MANAGER__) */
    <IMAGE id="IMG_ID_VAPP_FMGR_TYPE_DEF_FOLDER">RES_IMG_ROOT"\\\\FMGR\\\\ListIcon\\\\System_Folder.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_FMGR_TYPE_USER_FOLDER">RES_IMG_ROOT"\\\\FMGR\\\\ListIcon\\\\User_Defined_Folder.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_FMGR_TYPE_UNKNOWN">RES_IMG_ROOT"\\\\FMGR\\\\ListIcon\\\\UnknownFile.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_FMGR_STORAGE_REPORT_BAR_BG">RES_IMG_ROOT"\\\\FMGR\\\\Space_BG.9slice.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_FMGR_STORAGE_REPORT_BAR_HIGH">RES_IMG_ROOT"\\\\FMGR\\\\Space_03.9slice.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_FMGR_STORAGE_REPORT_BAR_MID">RES_IMG_ROOT"\\\\FMGR\\\\Space_02.9slice.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_FMGR_STORAGE_REPORT_BAR_LOW">RES_IMG_ROOT"\\\\FMGR\\\\Space_01.9slice.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_FMGR_AUD_PREV_PLAY_D">RES_IMG_ROOT"\\\\Profile\\\\Button_Play_D.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_FMGR_AUD_PREV_PLAY_N">RES_IMG_ROOT"\\\\Profile\\\\Button_Play_N.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_FMGR_AUD_PREV_PLAY_P">RES_IMG_ROOT"\\\\Profile\\\\Button_Play_P.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_FMGR_AUD_PREV_STOP_D">RES_IMG_ROOT"\\\\Profile\\\\Button_Stop_D.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_FMGR_AUD_PREV_STOP_N">RES_IMG_ROOT"\\\\Profile\\\\Button_Stop_N.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_FMGR_AUD_PREV_STOP_P">RES_IMG_ROOT"\\\\Profile\\\\Button_Stop_P.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_FMGR_SELECT_N">RES_IMG_ROOT"\\\\FMGR\\\\Select_N.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_FMGR_SELECT_P">RES_IMG_ROOT"\\\\FMGR\\\\Select_P.png"</IMAGE>
    <THEME>
        <IMAGE id="IMG_ID_VAPP_FMGR_MAINMENU_ICN" desc="Main menu file manager icon">RES_IMG_ROOT"\\\\"__MMI_MAINMENU_ICON_DEFAULT_PATH__"\\\\FMGR.png"</IMAGE>
        <IMAGE id="IMG_ID_VAPP_FMGR_BACK_N" desc="Normal case of back button icon shown near parent folder" />
        <IMAGE id="IMG_ID_VAPP_FMGR_BACK_P" desc="Press case of back button icon shown near parent folder" />
#if !defined(__MMI_ULTRA_SLIM_FILE_MANAGER__)
        <IMAGE id="IMG_ID_VAPP_FMGR_RENAME_ICON_N"  desc="Normal case of edit button icon shown near file name in detail page" />
        <IMAGE id="IMG_ID_VAPP_FMGR_RENAME_ICON_P" desc="Press case of edit button icon shown near file name in detail page" />
#endif /* #if !defined(__MMI_ULTRA_SLIM_FILE_MANAGER__) */
        <IMAGE id="IMG_ID_VAPP_FMGR_PARENT_FOLDER_BG" desc="Background of parent folder" />

        <COLOR id="CLR_ID_VAPP_FMGR_TITLE_MAIN_TXT" desc="The color of parent folder main text" />
        <COLOR id="CLR_ID_VAPP_FMGR_TITLE_SUB_TXT" desc="The color of parent folder sub text" />
    </THEME>
<!-- 
**************************************** String Id ****************************************
-->

    <STRING id="STR_ID_VAPP_FMGR_MYPICTURE"/>
    <STRING id="STR_ID_VAPP_FMGR_MYVIDEO"/>
    <STRING id="STR_ID_VAPP_FMGR_MYSHOOTING"/>
    <STRING id="STR_ID_VAPP_FMGR_MYMUSIC"/>
    <STRING id="STR_ID_VAPP_FMGR_MYEBOOK"/>
    <STRING id="STR_ID_VAPP_FMGR_MYRECEIVED"/>
    <STRING id="STR_ID_VAPP_FMGR_MYAPPLICATION"/>
    <STRING id="STR_ID_VAPP_FMGR_MYRECORD"/>
    <STRING id="STR_ID_VAPP_FMGR_MYRINGTONE"/>
    <STRING id="STR_ID_VAPP_FMGR_MYDOCUMENT"/>
    <STRING id="STR_ID_VAPP_FMGR_HEADER_SYSTEM"/>
    <STRING id="STR_ID_VAPP_FMGR_HEADER_USERDEFINE"/>
    <STRING id="STR_ID_VAPP_FMGR_STORAGE_REPORT"/>
    /*<STRING id="STR_ID_VAPP_FMGR_PORTABLE_DISK"/>*/
    <STRING id="STR_ID_VAPP_FMGR_TOTAL"/>
    <STRING id="STR_ID_VAPP_FMGR_FREE"/>
    
    <STRING id="STR_ID_VAPP_FMGR_OPTION_NEW_FOLDER"/>
    <STRING id="STR_ID_VAPP_FMGR_OPTION_DELETE"/>
    <STRING id="STR_ID_VAPP_FMGR_OPTION_DELETE_ALL"/>    
    <STRING id="STR_ID_VAPP_FMGR_OPTION_MOVE"/>
    <STRING id="STR_ID_VAPP_FMGR_OPTION_COPY"/>
    <STRING id="STR_ID_VAPP_FMGR_OPTION_MOVE_TO"/>
    <STRING id="STR_ID_VAPP_FMGR_OPTION_COPY_TO"/>
#if defined( __FS_SORT_SUPPORT__) && !defined(__MMI_ULTRA_SLIM_FILE_MANAGER__)
    <STRING id="STR_ID_VAPP_FMGR_SORT_BY_NAME"/>
    <STRING id="STR_ID_VAPP_FMGR_SORT_BY_TYPE"/>
    <STRING id="STR_ID_VAPP_FMGR_SORT_BY_TIME"/>
    <STRING id="STR_ID_VAPP_FMGR_SORT_BY_SIZE"/>
#endif /*#if defined( __FS_SORT_SUPPORT__) && !defined(__MMI_ULTRA_SLIM_FILE_MANAGER__)*/
    <STRING id="STR_ID_VAPP_FMGR_OPTION_FORMAT"/>
#if defined(__MMI_VECTOR_FONT_MEMORY_CARD_SUPPORT__) || defined(__MMI_FE_VECTOR_FONT_ON_FILE_SYSTEM__) || defined(__MMI_IME_MEMORY_CARD_SUPPORT__) || defined(__MMI_HANDWRITING_MEMORY_CARD_SUPPORT__)
    <STRING id="STR_ID_VAPP_FMGR_FORMAT_REBOOT_HINT"/>
#endif
    <STRING id="STR_ID_VAPP_FMGR_FILE"/>
    <STRING id="STR_ID_VAPP_FMGR_FILES"/>
    <STRING id="STR_ID_VAPP_FMGR_FOLDER"/>
    <STRING id="STR_ID_VAPP_FMGR_FOLDERS"/>
    <STRING id="STR_ID_VAPP_FMGR_DAF"/>
    <STRING id="STR_ID_VAPP_FMGR_NO_DATA"/>
    <STRING id="STR_ID_VAPP_FMGR_NAME_NEW_FOLDER"/>
    <STRING id="STR_ID_VAPP_FMGR_APP_MAINMENU"/>
    <STRING id="STR_ID_VAPP_FMGR_APP_TITLE"/>
    <STRING id="STR_ID_VAPP_FMGR_FOLDER_SELECTOR_TITLE"/>
    <STRING id="STR_ID_VAPP_FMGR_FILE_SELECTOR_TITLE"/>

    <STRING id="STR_ID_VAPP_FMGR_FORMATING"/>

    <STRING id="STR_ID_VAPP_FMGR_DETAIL_NAME"/>
    <STRING id="STR_ID_VAPP_FMGR_DETAIL_TYPE"/>
    <STRING id="STR_ID_VAPP_FMGR_DETAIL_SIZE"/>
    <STRING id="STR_ID_VAPP_FMGR_DETAIL_CREATED_TIME"/>
    <STRING id="STR_ID_VAPP_FMGR_DETAIL_MODIFIED_TIME"/>
    <STRING id="STR_ID_VAPP_FMGR_DETAIL_COPYRIGHT"/>
    <STRING id="STR_ID_VAPP_FMGR_DETAIL_PROTECTED"/>
    <STRING id="STR_ID_VAPP_FMGR_DETAIL_NOT_PROTECTED"/>
    <STRING id="STR_ID_VAPP_FMGR_DETAIL_DOWNLOAD_LICENSE"/>
    <STRING id="STR_ID_VAPP_FMGR_DETAIL_IMG_WIDTH"/>
    <STRING id="STR_ID_VAPP_FMGR_DETAIL_IMG_HEIGHT"/>
    <STRING id="STR_ID_VAPP_FMGR_DETAIL_IMG_PREVIEW"/>
    <STRING id="STR_ID_VAPP_FMGR_DETAIL_AUD_DURATION"/>
    <STRING id="STR_ID_VAPP_FMGR_DETAIL_AUD_BITRATE"/>
    /* <STRING id="STR_ID_VAPP_FMGR_DETAIL_AUD_BIT"/> */
    <STRING id="STR_ID_VAPP_FMGR_DETAIL_AUD_SAMPLE_RATE"/>
    <STRING id="STR_ID_VAPP_FMGR_DETAIL_VDO_WIDTH"/>
    <STRING id="STR_ID_VAPP_FMGR_DETAIL_VDO_HEIGHT"/>
    <STRING id="STR_ID_VAPP_FMGR_DETAIL_VDO_DURATION"/>
    <STRING id="STR_ID_VAPP_FMGR_DETAIL_BK_URL"/>
    /* <STRING id="STR_ID_VAPP_FMGR_DETAIL_JAVA_MIDLET_NAME"/> */
    /* <STRING id="STR_ID_VAPP_FMGR_DETAIL_JAVA_MIDLET_VENDOR"/> */
    <STRING id="STR_ID_VAPP_FMGR_DEATIL_EXTRA_INFO"/>
    <STRING id="STR_ID_VAPP_FMGR_FILE_LIST_IS_DIRTY"/>
    <STRING id="STR_ID_VAPP_FMGR_DRM_AND_PATH_OVER_LEN_FAIL"/>
    <STRING id="STR_ID_VAPP_FMGR_MORE_THAN_BT_LIMIT_CONTINUE"/>
    <STRING id="STR_ID_VAPP_FMGR_SHARE_BY_MMS"/>
    <STRING id="STR_ID_VAPP_FMGR_SHARE_BY_BLUETOOTH"/>
    <STRING id="STR_ID_VAPP_FMGR_SHARE_BY_EMAIL"/>
    <STRING id="STR_ID_VAPP_FMGR_DETAIL_FILE_TITLE"/>
    <STRING id="STR_ID_VAPP_FMGR_DETAIL_FOLDER_TITLE"/>
    <STRING id="STR_ID_VAPP_FMGR_FAILED_TO_COPY"/>
    <STRING id="STR_ID_VAPP_FMGR_FAILED_TO_MOVE"/>
    <STRING id="STR_ID_VAPP_FMGR_FAILED_TO_DELETE"/>
    <STRING id="STR_ID_VAPP_FMGR_FAILED_TO_FORMAT"/>
    <STRING id="STR_ID_VAPP_FMGR_NO_AVAILABLE_STORAGE"/>

    <STRING id="STR_ID_VAPP_FMGR_DELETE_THE_FILE_Q"/>
    <STRING id="STR_ID_VAPP_FMGR_DELETE_SELECT_FILES_Q"/>
/* For media picker */
    <STRING id="STR_ID_VAPP_FMGR_MEDIA_PICKER_BEYOND_LIMIT_Q"/>
<!-- 
**************************************** Menu Id ****************************************
-->

    <MENUSET id="MENU_ID_FMGR_GEN_OPTION_SET">
        <MENUITEM_ID>MENU_ID_FMGR_OPTION_NEW_FOLDER</MENUITEM_ID>
#if defined( __FS_SORT_SUPPORT__) && !defined(__MMI_ULTRA_SLIM_FILE_MANAGER__)
        <MENUITEM_ID>MENU_ID_FMGR_OPTION_SORT</MENUITEM_ID>
#endif /*#if defined( __FS_SORT_SUPPORT__) && !defined(__MMI_ULTRA_SLIM_FILE_MANAGER__)*/
        <MENUITEM_ID>MENU_ID_FMGR_OPTION_DELETE</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_FMGR_OPTION_SHARE</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_FMGR_OPTION_MOVE</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_FMGR_OPTION_COPY</MENUITEM_ID>
    </MENUSET>

    <MENUSET id="MENU_ID_FMGR_SINGLE_GEN_OPTION_SET">
#if !defined(__MMI_ULTRA_SLIM_FILE_MANAGER__)
        <MENUITEM_ID>MENU_ID_FMGR_OPTION_OPEN</MENUITEM_ID>
#endif /*#if !defined(__MMI_ULTRA_SLIM_FILE_MANAGER__) */
        <MENUITEM_ID>MENU_ID_FMGR_OPTION_SHARE_SINGLE</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_FMGR_OPTION_DELETE_SINGLE</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_FMGR_OPTION_MOVE_TO</MENUITEM_ID>        
        <MENUITEM_ID>MENU_ID_FMGR_OPTION_COPY_TO</MENUITEM_ID>      
    </MENUSET>
    
    <MENU id="MENU_ID_FMGR_GEN_OPTIONS" type="OPTION" str="STR_GLOBAL_OPTIONS">
        <MENUSET_ID>MENU_ID_FMGR_GEN_OPTION_SET</MENUSET_ID>        
    </MENU>

    <MENU id="MENU_ID_FMGR_SINGLE_GEN_OPTIONS" type="OPTION" str="STR_GLOBAL_OPTIONS">
        <MENUSET_ID>MENU_ID_FMGR_SINGLE_GEN_OPTION_SET</MENUSET_ID>        
    </MENU>
#if !defined(__MMI_ULTRA_SLIM_FILE_MANAGER__)
    <MENUITEM id="MENU_ID_FMGR_OPTION_OPEN" str="STR_GLOBAL_OPEN" img="IMG_ID_VAPP_FMGR_OPTION_OPEN"/>
#endif /* #if !defined(__MMI_ULTRA_SLIM_FILE_MANAGER__) */
    <MENUITEM id="MENU_ID_FMGR_OPTION_NEW_FOLDER" str="STR_ID_VAPP_FMGR_OPTION_NEW_FOLDER" img="VCP_IMG_TOOL_BAR_COMMON_ITEM_NEW_FOLDER"/>
    <MENUITEM id="MENU_ID_FMGR_OPTION_SHARE" str="STR_GLOBAL_SHARE" img="IMG_ID_VAPP_FMGR_SHARE_BY_BT"/>
    <MENUITEM id="MENU_ID_FMGR_OPTION_SHARE_SINGLE" str="STR_GLOBAL_SHARE" img="VCP_IMG_TOOL_BAR_COMMON_ITEM_SHARE"/>    
    <MENUITEM id="MENU_ID_FMGR_OPTION_DELETE" str="STR_ID_VAPP_FMGR_OPTION_DELETE" img="VCP_IMG_TOOL_BAR_COMMON_ITEM_DELETE"/>
    <MENUITEM id="MENU_ID_FMGR_OPTION_DELETE_SINGLE" str="STR_ID_VAPP_FMGR_OPTION_DELETE" img="VCP_IMG_TOOL_BAR_COMMON_ITEM_DELETE"/>
    <MENUITEM id="MENU_ID_FMGR_OPTION_COPY" str="STR_ID_VAPP_FMGR_OPTION_COPY" img="VCP_IMG_TOOL_BAR_COMMON_ITEM_COPY"/>
    <MENUITEM id="MENU_ID_FMGR_OPTION_MOVE" str="STR_ID_VAPP_FMGR_OPTION_MOVE" img="VCP_IMG_TOOL_BAR_COMMON_ITEM_MOVE"/>
    <MENUITEM id="MENU_ID_FMGR_OPTION_COPY_TO" str="STR_ID_VAPP_FMGR_OPTION_COPY_TO" img="VCP_IMG_TOOL_BAR_COMMON_ITEM_COPY"/>
    <MENUITEM id="MENU_ID_FMGR_OPTION_MOVE_TO" str="STR_ID_VAPP_FMGR_OPTION_MOVE_TO" img="VCP_IMG_TOOL_BAR_COMMON_ITEM_MOVE"/>

    <MENU id="MENU_ID_FMGR_OPTION_DRV" type="OPTION" str="STR_GLOBAL_OPTIONS">
        <MENUITEM_ID>MENU_ID_FMGR_STORAGE_REPORT</MENUITEM_ID>
        /*<MENUITEM_ID>MENU_ID_FMGR_PORTABLE_DISK</MENUITEM_ID>*/
        </MENU>
        
    <MENUITEM id="MENU_ID_FMGR_STORAGE_REPORT" str="STR_ID_VAPP_FMGR_STORAGE_REPORT" img="IMG_ID_VAPP_FMGR_STORAGE_REPORT"/>
    /*<MENUITEM id="MENU_ID_FMGR_PORTABLE_DISK" str="STR_ID_VAPP_FMGR_PORTABLE_DISK"/>*/

    <MENU id="MENU_ID_FMGR_OPTION_FOLDER_SELECTOR_CUI" type="OPTION" str="STR_GLOBAL_OPTIONS">
        <MENUITEM_ID>MENU_ID_FMGR_OPTION_NEW_FOLDER</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_FMGR_CANCEL</MENUITEM_ID>
        </MENU>

/* For media picker */
    <MENU id="MENU_ID_FMGR_OPTION_MEDIA_PICKER_CUI" type="OPTION" str="STR_GLOBAL_OPTIONS">
        <MENUITEM_ID>MENU_ID_FMGR_OPTION_SELECT</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_FMGR_CANCEL</MENUITEM_ID>
        </MENU>

    <MENUITEM id="MENU_ID_FMGR_OPTION_SELECT" str="STR_GLOBAL_SELECT" img="VCP_IMG_TOOL_BAR_COMMON_ITEM_ADD"/>

    <MENU id="MENU_ID_FMGR_OPTION_STORAGE_REPORT" type="OPTION" str="STR_GLOBAL_OPTIONS">
        <MENUITEM_ID>MENU_ID_FMGR_OPTION_RENAME_DRIVE</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_FMGR_OPTION_FORMAT_PHONE</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_FMGR_OPTION_FORMAT_CARD</MENUITEM_ID>
        </MENU>
        
    <MENUITEM id="MENU_ID_FMGR_OPTION_RENAME" str="STR_GLOBAL_RENAME" img="VCP_IMG_TOOL_BAR_COMMON_ITEM_EDIT"/>
    <MENUITEM id="MENU_ID_FMGR_OPTION_RENAME_DRIVE" str="STR_GLOBAL_RENAME" img="VCP_IMG_TOOL_BAR_COMMON_ITEM_EDIT"/>
    <MENUITEM id="MENU_ID_FMGR_OPTION_FORMAT_PHONE" str="STR_ID_VAPP_FMGR_OPTION_FORMAT" img="VCP_IMG_TOOL_BAR_COMMON_ITEM_FORMAT"/>
    <MENUITEM id="MENU_ID_FMGR_OPTION_FORMAT_CARD" str="STR_ID_VAPP_FMGR_OPTION_FORMAT" img="VCP_IMG_TOOL_BAR_COMMON_ITEM_FORMAT"/>
#if defined( __FS_SORT_SUPPORT__) && !defined(__MMI_ULTRA_SLIM_FILE_MANAGER__)
    <MENU id="MENU_ID_FMGR_OPTION_SORT" type="OPTION" str="STR_GLOBAL_SORT" img="VCP_IMG_TOOL_BAR_COMMON_ITEM_SORT">
        <MENUITEM_ID>MENU_ID_FMGR_SORT_NAME</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_FMGR_SORT_TYPE</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_FMGR_SORT_TIME</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_FMGR_SORT_SIZE</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_FMGR_CANCEL</MENUITEM_ID>
        </MENU>
    <MENUITEM id="MENU_ID_FMGR_SORT_NAME" str="STR_ID_VAPP_FMGR_SORT_BY_NAME"/>
    <MENUITEM id="MENU_ID_FMGR_SORT_TYPE" str="STR_ID_VAPP_FMGR_SORT_BY_TYPE"/>
    <MENUITEM id="MENU_ID_FMGR_SORT_TIME" str="STR_ID_VAPP_FMGR_SORT_BY_TIME"/>
    <MENUITEM id="MENU_ID_FMGR_SORT_SIZE" str="STR_ID_VAPP_FMGR_SORT_BY_SIZE"/>    
#endif /*#if defined( __FS_SORT_SUPPORT__) && !defined(__MMI_ULTRA_SLIM_FILE_MANAGER__)*/

    <MENU id="MENU_ID_FMGR_OPTION_MULTI_SELECT" type="OPTION" str="STR_GLOBAL_OPTIONS">
        <MENUITEM_ID>MENU_ID_FMGR_OPTION_SELECT_ALL</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_FMGR_OPTION_UNSELECT_ALL</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_FMGR_OPTION_SHARE</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_FMGR_OPTION_DELETE</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_FMGR_OPTION_COPY</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_FMGR_OPTION_MOVE</MENUITEM_ID>
/* For media picker */
        <MENUITEM_ID>MENU_ID_FMGR_OPTION_ADD</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_FMGR_CANCEL</MENUITEM_ID>       
    </MENU>

    <MENUITEM id="MENU_ID_FMGR_OPTION_SELECT_ALL" str="STR_GLOBAL_MARK_ALL" img="VCP_IMG_TOOL_BAR_COMMON_ITEM_SELECT_ALL"/>
    <MENUITEM id="MENU_ID_FMGR_OPTION_UNSELECT_ALL" str="STR_GLOBAL_UNMARK_ALL" img="VCP_IMG_TOOL_BAR_COMMON_ITEM_UNSELECT_ALL"/>
    
/* For media picker */
    <MENUITEM id="MENU_ID_FMGR_OPTION_ADD" str="STR_GLOBAL_ADD" img="VCP_IMG_TOOL_BAR_COMMON_ITEM_OK"/>
    <MENUITEM id="MENU_ID_FMGR_CANCEL" str="STR_GLOBAL_CANCEL" img="VCP_IMG_TOOL_BAR_COMMON_ITEM_CANCEL"/>

    <MENUITEM id="MENU_ID_FILE_TYPE_UNKNOWN_LAUNCH" str="STR_GLOBAL_OPEN"/>
    <MENUITEM id="MENU_ID_FILE_TYPE_SHARE_AS_MMS" str="STR_ID_VAPP_FMGR_SHARE_BY_MMS"/>
    <MENUITEM id="MENU_ID_FILE_TYPE_SHARE_AS_EMAIL" str="STR_ID_VAPP_FMGR_SHARE_BY_EMAIL"/>
    <MENUITEM id="MENU_ID_FILE_TYPE_SHARE_AS_BT" str="STR_ID_VAPP_FMGR_SHARE_BY_BLUETOOTH"/>
    
    <MENUSET id="MENU_ID_FILE_TYPE_UNKNOWN_SHARE_SET">
        <MENUITEM_ID>MENU_ID_FILE_TYPE_SHARE_AS_MMS</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_FILE_TYPE_SHARE_AS_EMAIL</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_FILE_TYPE_SHARE_AS_BT</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_FMGR_CANCEL</MENUITEM_ID>
    </MENUSET>

    <MENU id="MENU_ID_FILE_TYPE_UNKNOWN_OPTION" type="OPTION" str="STR_GLOBAL_OPTIONS">
        <MENUITEM_ID>MENU_ID_FILE_TYPE_UNKNOWN_LAUNCH</MENUITEM_ID>
        <MENUSET_ID>MENU_ID_FILE_TYPE_UNKNOWN_SHARE_SET</MENUSET_ID>       
    </MENU>
<!-- 
**************************************** Callback Manager Receiver ****************************************
-->

    <RECEIVER id="EVT_ID_SRV_FMGR_NOTIFICATION_DEV_PLUG_IN" proc="vapp_fmgr_notify_hdlr"/>
    <RECEIVER id="EVT_ID_SRV_FMGR_NOTIFICATION_DEV_PLUG_OUT" proc="vapp_fmgr_notify_hdlr"/>
    <RECEIVER id="EVT_ID_SRV_FMGR_NOTIFICATION_DEV_SOFT_MOUNT" proc="vapp_fmgr_notify_hdlr"/>
    <RECEIVER id="EVT_ID_SRV_FMGR_NOTIFICATION_ADV_ACTION" proc="vapp_fmgr_notify_hdlr"/>

    <RECEIVER id="EVT_ID_SRV_FMGRI_CARD_PLUG_IN"                 proc="vapp_fmgr_notify_hdlr" />
    <RECEIVER id="EVT_ID_SRV_FMGRI_CARD_PLUG_OUT"                proc="vapp_fmgr_notify_hdlr" />

    <RECEIVER id="EVT_ID_USB_ENTER_MS_MODE" proc="vapp_fmgr_notify_hdlr"/>
#ifdef __DM_LAWMO_SUPPORT__
    <RECEIVER id="EVT_ID_SRV_DM_LAWMO_WIPE_EX_IND" proc="vapp_fmgr_notify_hdlr"/>
#endif
<!-- 
**************************************** File Type ****************************************
-->
<FILE_TYPES>
#if defined(__COSMOS_MMI__)
    <FILE_GROUP_TYPE type_id="FMGR_GROUP_COMMON">
        <FILE_TYPE type_id="FMGR_TYPE_UNKNOWN" small_icon="IMG_ID_VAPP_FMGR_TYPE_UNKNOWN" large_icon="IMG_ID_VAPP_FMGR_TYPE_UNKNOWN"/>
        <FILE_TYPE type_id="FMGR_TYPE_FOLDER" small_icon="IMG_ID_VAPP_FMGR_TYPE_USER_FOLDER" large_icon="IMG_ID_VAPP_FMGR_TYPE_USER_FOLDER"/>
        #if defined(__DRM_V02__)
        <FILE_TYPE type_id="FMGR_TYPE_ODF" extension="ODF" small_icon="IMG_GLOBAL_L3" large_icon="IMG_GLOBAL_L3"/>
        #endif
        <FILE_TYPE type_id="FMGR_TYPE_HYPER_LINK" small_icon="IMG_GLOBAL_L2" large_icon="IMG_GLOBAL_L2"/>

        <FILE_OPTION_HDLR option="MENU_ID_FILE_TYPE_UNKNOWN_LAUNCH" handler="vapp_file_type_unknown_launch"/>
    
    </FILE_GROUP_TYPE>
#endif
</FILE_TYPES>
</APP>

