/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
/**
 *	Copyright Notice
 *	?2002 - 2003, Pixtel Communications, Inc., 1489 43rd Ave. W.,
 *	Vancouver, B.C. V6M 4K8 Canada. All Rights Reserved.
 *  (It is illegal to remove this copyright notice from this software or any
 *  portion of it)
 */

/**************************************************************

	FILENAME	: Res_.c

  	PURPOSE		: Populate Resource for 

	REMARKS		: nil

	AUTHOR		: Yogesh

	DATE		: August-11-2003

**************************************************************/
#include "MMI_features.h"
#include "CustomCfg.h"

#if defined(__PLUTO_MMI_PACKAGE__)
#include "mmi_rp_app_mainmenu_def.h"
#endif

#ifdef FIRST_PASS
#include "BuildCfg.h"
#endif

#include "InfoNumResDef.h"

//micha0601, NOTE, checkin all main trunk branches
#include "ServiceDefs.h"

#ifdef DEVELOPER_BUILD_FIRST_PASS
#include "PopulateRes.h"
#if defined (__MMI_BROWSER_2__) && !defined(__COSMOS_MMI_PACKAGE__)
#include "mmi_rp_app_browser_def.h"
#endif /* __MMI_BROWSER_2__ */
/**************************************************************

	FUNCTION NAME		: PopulateSATRes

  	PURPOSE				: Populates the respurces for SAT

	INPUT PARAMETERS	: nil

	OUTPUT PARAMETERS	: nil

	RETURNS				: nil

	REMARKS				: nil

**************************************************************/

void PopulateSATRes(void)
{
    /* SERVICES_WAP_MENU_ID use different highlight handler in Operator Version  */
#if (!defined(__MMI_OP01_MENU_9MATRIX__) && !defined(__MMI_OP01_MENU_12MATRIX__) && !defined(__MMI_OP02_MAINMENU_12MATRIX__) && !defined(__MMI_OP02_MAINMENU_9MATRIX__))
#ifdef BROWSER_SUPPORT
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(SERVICES_WAP_MENU_ID, WapHiliteHandler);
#endif
#endif /* __MMI_OP01_MENU_9MATRIX__ */

#if defined(__MMI_OP02_MAINMENU_12MATRIX__) || defined(__MMI_OP02_MAINMENU_9MATRIX__) || defined(__MMI_OP01_MENU_9MATRIX__) || defined(__MMI_OP01_MENU_12MATRIX__)
#ifdef BROWSER_SUPPORT
    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(SERVICES_WAP_MENU_ID,highlight_mainmenu_monwap);
#endif /* BROWSER_SUPPORT */
#endif /* __MMI_OP02_MAINMENU_12MATRIX__ && __MMI_OP02_MAINMENU_9MATRIX__ */

    ADD_APPLICATION_MENUITEM_HILITE_HANDLER(SERVICES_DATA_CONNECT_MENU_ID, DataConnectGSMHiliteHandler);

	/* Services Resources to be put in separate file*/
	ADD_APPLICATION_STRING2(SERVICES_TITLE_STRING_ID,"Services","Title for Services Menu");

#ifdef BROWSER_SUPPORT
#ifdef OPERA_BROWSER
	ADD_APPLICATION_STRING2(SERVICES_OPERA_STRING_ID,"Opera","Opera Menu Item String");
#else
	ADD_APPLICATION_STRING2(SERVICES_WAP_STRING_ID,"Internet service","WAP Menu Item String");
#endif

#if defined (__MMI_BROWSER_2__) && !defined(__COSMOS_MMI_PACKAGE__)
#if defined(__MMI_OP01_MENU_9MATRIX__) || defined(__MMI_OP01_MENU_12MATRIX__) || defined(__MMI_OP02_0100__)
	ADD_APPLICATION_MENUITEM2((SERVICES_WAP_MENU_ID,IDLE_SCREEN_MENU_ID,
#else
	ADD_APPLICATION_MENUITEM2((SERVICES_WAP_MENU_ID, MAIN_MENU_SERVICES_MENUID,
#endif
#ifdef __MMI_OP12_BRW_SEARCH_MENU__
			MENU_ID_BRW_SEARCH_WEB,
#endif /* __MMI_OP12_BRW_SEARCH_MENU__ */ 
#ifdef __MMI_DOWNLOAD_AGENT_MULTI_DL__
			MENU_ID_BRW_REN_PAGE_DOWNLOADS,
#endif /* __MMI_DOWNLOAD_AGENT_MULTI_DL__ */ 
			MENU_ID_BRW_HOMEPAGE,
#ifdef __MMI_VBOOKMARK__
			MENU_ID_BRW_BOOKMARKS,
#endif /*__MMI_VBOOKMARK__*/
			MENU_ID_BRW_ENTER_ADDRESS,
#ifdef OBIGO_Q05A
			MENU_ID_BRW_OPEN_FILE,
#endif /* OBIGO_Q05A */
#ifdef __MMI_BRW_ADVANCED_APP_FEATURES__
			MENU_ID_BRW_LAST_WEB_ADDR,
#endif /* __MMI_BRW_ADVANCED_APP_FEATURES__ */
#ifndef __MMI_BRW_RECENT_PAGES_SLIM__
			MENU_ID_BRW_RECENT_PAGES,
#endif
#ifdef __MMI_WAP_OFFLINE_PAGES_SUPPORT__
			MENU_ID_BRW_STORED_PAGES,
#endif /* __MMI_WAP_OFFLINE_PAGES_SUPPORT__ */
			MENU_ID_BRW_SETTINGS,
			MENU_ITEM_END,
#if defined(__MMI_OP01_MENU_9MATRIX__) || defined(__MMI_OP01_MENU_12MATRIX__) || defined(__MMI_OP02_0100__)
			SHOW,MOVEABLEWITHINPARENT|INSERTABLE,1,MAIN_MENU_MONWAP_TEXT, MAIN_MENU_MONWAP_ICON));
#else
			SHOW,NONMOVEABLE|SHORTCUTABLE,DISP_LIST,SERVICES_WAP_STRING_ID,SERVICES_WAP_IMAGE_ID));
#endif
#elif defined (OPERA_BROWSER) && defined(__PLUTO_MMI_PACKAGE__)
#if defined(__MMI_OP01_MENU_9MATRIX__) || defined(__MMI_OP01_MENU_12MATRIX__) || defined(__MMI_OP02_0100__)
	ADD_APPLICATION_MENUITEM((SERVICES_WAP_MENU_ID,IDLE_SCREEN_MENU_ID,0,SHOW,MOVEABLEWITHINPARENT|INSERTABLE,1,
								MAIN_MENU_MONWAP_TEXT, MAIN_MENU_MONWAP_ICON));
#else /* __MMI_OP01_MENU_9MATRIX__ || __MMI_OP02_0100__ */
	ADD_APPLICATION_MENUITEM((SERVICES_WAP_MENU_ID,MAIN_MENU_SERVICES_MENUID,0,SHOW,NONMOVEABLE|SHORTCUTABLE,DISP_LIST,
								SERVICES_OPERA_STRING_ID,SERVICES_OPERA_IMAGE_ID));
#endif /* __MMI_OP01_MENU_9MATRIX__ || __MMI_OP02_0100__ */
#elif defined(__PLUTO_MMI_PACKAGE__)
#if defined(__MMI_OP01_MENU_9MATRIX__) || defined(__MMI_OP01_MENU_12MATRIX__) || defined(__MMI_OP02_0100__)
	ADD_APPLICATION_MENUITEM((SERVICES_WAP_MENU_ID,IDLE_SCREEN_MENU_ID,0,SHOW,MOVEABLEWITHINPARENT|INSERTABLE,1,
								MAIN_MENU_MONWAP_TEXT, MAIN_MENU_MONWAP_ICON));
#else /* __MMI_OP01_MENU_9MATRIX__ || __MMI_OP02_0100__ */
	ADD_APPLICATION_MENUITEM((SERVICES_WAP_MENU_ID,MAIN_MENU_SERVICES_MENUID,0,SHOW,NONMOVEABLE|SHORTCUTABLE,DISP_LIST,
								SERVICES_WAP_STRING_ID,SERVICES_WAP_IMAGE_ID));
#endif /* __MMI_OP01_MENU_9MATRIX__ || __MMI_OP02_0100__ */
#endif
#endif 

//	ADD_APPLICATION_IMAGE2(SERVICES_TITLE_IMAGE_ID,CUST_IMG_PATH"\\\\MainLCD\\\\TitleBar\\\\TB_SV.PNG","Title Icon for Services Menu");
#ifdef OPERA_BROWSER
	ADD_APPLICATION_IMAGE2(SERVICES_OPERA_IMAGE_ID,CUST_IMG_PATH"\\\\MainLCD\\\\Opera\\\\SB_opera.bmp","Opera Menu Item Icon");
#else
    #ifdef __MMI_BRW_IMG_RES_SLIM__
	ADD_APPLICATION_IMAGE2(SERVICES_WAP_IMAGE_ID,CUST_IMG_PATH"\\\\MainLCD\\\\WAP\\\\SB_WAP.bmp","WAP Menu Item Icon");
    #else
	ADD_APPLICATION_IMAGE2(SERVICES_WAP_IMAGE_ID,CUST_IMG_PATH"\\\\MainLCD\\\\WAP\\\\SB_WAP.png","WAP Menu Item Icon");
    #endif
#endif

#ifdef __MMI_MERGE_SAT_TO_MAINMENU__			//slim
	ADD_APPLICATION_STRING2(SERVICES_NOT_PROVIDED_STRING_ID,"SIM Not Support!","String displayed when no service avaliable.");
#endif /* __MMI_MERGE_SAT_TO_MAINMENU__ */		//slim

}

#endif


