/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 *   gui_virtual_keyboard.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Virtual keyboard - UI component
 *
 * Author:
 * -------
 * -------
 *
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/

/*
 * This file contains internal UI component API, and is intended to be used by category screen module only. 
 * It's not recommended to be included in application code directly. 
 * For application developers, please include category screen header files instead (e.g., wgui_categories.h).
*/

#ifndef __GUI_VIRTUAL_KEYBOARD_LANGUAGE_TYPE_H__
#define __GUI_VIRTUAL_KEYBOARD_LANGUAGE_TYPE_H__

/***************************************************************************** 
* Define
*****************************************************************************/
/***************************************************************************** 
* Typedef 
*****************************************************************************/
#if defined(__MMI_TOUCH_SCREEN__)

/*****************************************************************************
 * Following code is for VK V1
 ****************************************************************************/

/* <group dom_virtual_keyboard_enum>
 * Supported languages 
 * MMI_virtual_keyboard_language_map[] and gui_dead_key_symbol_table[] should be changed
 * accrording to gui_virtual_keyboard_language_enum.
 */
#ifndef __MMI_UI_VIRTUAL_KEYBOARD_DEFAULT_VERSION_3__

typedef enum
{
    GUI_VIRTUAL_KEYBOARD_ENGLISH = 0,
    GUI_VIRTUAL_KEYBOARD_ENGLISH_UPPERCASE,
    GUI_VIRTUAL_KEYBOARD_SYMBOL,
    GUI_VIRTUAL_KEYBOARD_TRAY,
    GUI_VIRTUAL_KEYBOARD_NUMBER,
    GUI_VIRTUAL_KEYBOARD_SYMBOL_FOR_NUM, /* new vk */
    GUI_VIRTUAL_KEYBOARD_NUMBER_AND_SYMBOL, /* new vk */
    GUI_VIRTUAL_KEYBOARD_LANG_NUMBER, /* new vk (for alphanumeric input with language vk) */
    GUI_VIRTUAL_KEYBOARD_PHONE_NUMBER,
    GUI_VIRTUAL_KEYBOARD_PHONE_NUMBER_WILDCHAR,
    GUI_VIRTUAL_KEYBOARD_EMPTY_TRAY,
    GUI_VIRTUAL_KEYBOARD_NUMBER_TRAY,
    GUI_VIRTUAL_KEYBOARD_NUMBER_DOT_TRAY,
    /* new vk */
    GUI_VIRTUAL_KEYBOARD_ALPHANUMERIC_SYMBOL_PAGE_1,
    GUI_VIRTUAL_KEYBOARD_ALPHANUMERIC_SYMBOL_PAGE_2,
    GUI_VIRTUAL_KEYBOARD_ALPHANUMERIC_SYMBOL_PAGE_3,
    GUI_VIRTUAL_KEYBOARD_ALPHANUMERIC_SYMBOL_PAGE_4,
    /* Chinese */
    GUI_VIRTUAL_KEYBOARD_PINYIN,
    GUI_VIRTUAL_KEYBOARD_BOPOMO,
    GUI_VIRTUAL_KEYBOARD_NUMBER_AND_CH_SYMBOL, /* new vk */
    GUI_VIRTUAL_KEYBOARD_CHINESE_SYMBOL,
    GUI_VIRTUAL_KEYBOARD_TR_STROKE,
    GUI_VIRTUAL_KEYBOARD_SM_STROKE,
    /* new vk */
    GUI_VIRTUAL_KEYBOARD_ALPHANUMERIC_CH_SYMBOL_PAGE_1,
    GUI_VIRTUAL_KEYBOARD_ALPHANUMERIC_CH_SYMBOL_PAGE_2,
    GUI_VIRTUAL_KEYBOARD_ALPHANUMERIC_CH_SYMBOL_PAGE_3,
    GUI_VIRTUAL_KEYBOARD_ALPHANUMERIC_CH_SYMBOL_PAGE_4,
    /* Asia-pacific */
    GUI_VIRTUAL_KEYBOARD_THAI,
    GUI_VIRTUAL_KEYBOARD_THAI_LOWERCASE,
     GUI_VIRTUAL_KEYBOARD_THAI_NUMERIC,
    GUI_VIRTUAL_KEYBOARD_THAI_SYMBOL,
    GUI_VIRTUAL_KEYBOARD_INDONESIAN,
    GUI_VIRTUAL_KEYBOARD_INDONESIAN_UPPERCASE,
    GUI_VIRTUAL_KEYBOARD_MALAY,
    GUI_VIRTUAL_KEYBOARD_MALAY_UPPERCASE,
    GUI_VIRTUAL_KEYBOARD_VIETNAMESE,
    GUI_VIRTUAL_KEYBOARD_VIETNAMESE_UPPERCASE,
    /* Hindi */
    GUI_VIRTUAL_KEYBOARD_HINDI,
    GUI_VIRTUAL_KEYBOARD_HINDI_LOWERCASE,
    GUI_VIRTUAL_KEYBOARD_HINDI_UPPERCASE,
    GUI_VIRTUAL_KEYBOARD_HINDI_CONS_MATRAS1,
    GUI_VIRTUAL_KEYBOARD_HINDI_CONS_MATRAS2,
    GUI_VIRTUAL_KEYBOARD_HINDI_CONS_INDEPEDENTVOWELS1,
    GUI_VIRTUAL_KEYBOARD_HINDI_CONS_INDEPEDENTVOWELS2,
    GUI_VIRTUAL_KEYBOARD_HINDI_SYMBOLS,
    GUI_VIRTUAL_KEYBOARD_TAMIL_CONS_MATRAS1,
    GUI_VIRTUAL_KEYBOARD_TAMIL_CONS_INDEPEDENTVOWELS1,
    GUI_VIRTUAL_KEYBOARD_TAMIL_SYMBOLS,
    GUI_VIRTUAL_KEYBOARD_BENGALI,
    GUI_VIRTUAL_KEYBOARD_BENGALI_LOWERCASE,
    GUI_VIRTUAL_KEYBOARD_BENGALI_CONS_MATRAS1,
    GUI_VIRTUAL_KEYBOARD_BENGALI_CONS_MATRAS2,
    GUI_VIRTUAL_KEYBOARD_BENGALI_CONS_INDEPEDENTVOWELS1,
    GUI_VIRTUAL_KEYBOARD_BENGALI_CONS_INDEPEDENTVOWELS2,
    GUI_VIRTUAL_KEYBOARD_BENGALI_SYMBOLS,
    GUI_VIRTUAL_KEYBOARD_ASSAMESE_CONS_MATRAS1,
    GUI_VIRTUAL_KEYBOARD_ASSAMESE_CONS_MATRAS2,
    GUI_VIRTUAL_KEYBOARD_ASSAMESE_CONS_INDEPEDENTVOWELS1,
    GUI_VIRTUAL_KEYBOARD_ASSAMESE_CONS_INDEPEDENTVOWELS2,
    GUI_VIRTUAL_KEYBOARD_ASSAMESE_SYMBOLS,    
    GUI_VIRTUAL_KEYBOARD_PUNJABI_CONS_MATRAS1,
    GUI_VIRTUAL_KEYBOARD_PUNJABI_CONS_MATRAS2,
    GUI_VIRTUAL_KEYBOARD_PUNJABI_CONS_INDEPEDENTVOWELS1,
    GUI_VIRTUAL_KEYBOARD_PUNJABI_CONS_INDEPEDENTVOWELS2,
    GUI_VIRTUAL_KEYBOARD_PUNJABI_SYMBOLS,
    GUI_VIRTUAL_KEYBOARD_MARATHI_CONS_MATRAS1,
    GUI_VIRTUAL_KEYBOARD_MARATHI_CONS_MATRAS2,
    GUI_VIRTUAL_KEYBOARD_MARATHI_CONS_INDEPEDENTVOWELS1,
    GUI_VIRTUAL_KEYBOARD_MARATHI_CONS_INDEPEDENTVOWELS2,
    GUI_VIRTUAL_KEYBOARD_MARATHI_SYMBOLS,
    GUI_VIRTUAL_KEYBOARD_GUJARATI_CONS_MATRAS1,
    GUI_VIRTUAL_KEYBOARD_GUJARATI_CONS_MATRAS2,
    GUI_VIRTUAL_KEYBOARD_GUJARATI_CONS_INDEPEDENTVOWELS1,
    GUI_VIRTUAL_KEYBOARD_GUJARATI_CONS_INDEPEDENTVOWELS2,
    GUI_VIRTUAL_KEYBOARD_GUJARATI_SYMBOLS,
    GUI_VIRTUAL_KEYBOARD_KANNADA_CONS_MATRAS1,
    GUI_VIRTUAL_KEYBOARD_KANNADA_CONS_MATRAS2,
    GUI_VIRTUAL_KEYBOARD_KANNADA_CONS_INDEPEDENTVOWELS1,
    GUI_VIRTUAL_KEYBOARD_KANNADA_CONS_INDEPEDENTVOWELS2,
    GUI_VIRTUAL_KEYBOARD_KANNADA_SYMBOLS,
    GUI_VIRTUAL_KEYBOARD_ORIYA_CONS_MATRAS1,
    GUI_VIRTUAL_KEYBOARD_ORIYA_CONS_MATRAS2,
    GUI_VIRTUAL_KEYBOARD_ORIYA_CONS_INDEPEDENTVOWELS1,
    GUI_VIRTUAL_KEYBOARD_ORIYA_CONS_INDEPEDENTVOWELS2,
    GUI_VIRTUAL_KEYBOARD_ORIYA_SYMBOLS,
    GUI_VIRTUAL_KEYBOARD_MALAYALAM_CONS_MATRAS1,
    GUI_VIRTUAL_KEYBOARD_MALAYALAM_CONS_MATRAS2,
    GUI_VIRTUAL_KEYBOARD_MALAYALAM_CONS_INDEPEDENTVOWELS1,
    GUI_VIRTUAL_KEYBOARD_MALAYALAM_CONS_INDEPEDENTVOWELS2,
    GUI_VIRTUAL_KEYBOARD_MALAYALAM_SYMBOLS,
    GUI_VIRTUAL_KEYBOARD_TELUGU_CONS_MATRAS1,
    GUI_VIRTUAL_KEYBOARD_TELUGU_CONS_MATRAS2,
    GUI_VIRTUAL_KEYBOARD_TELUGU_CONS_INDEPEDENTVOWELS1,
    GUI_VIRTUAL_KEYBOARD_TELUGU_CONS_INDEPEDENTVOWELS2,
    GUI_VIRTUAL_KEYBOARD_TELUGU_SYMBOLS,
    /* Arabic */
    GUI_VIRTUAL_KEYBOARD_ARABIC,
    GUI_VIRTUAL_KEYBOARD_ARABIC_LOWERCASE,
    GUI_VIRTUAL_KEYBOARD_ARABIC_SYMBOLS,
    GUI_VIRTUAL_KEYBOARD_ARABIC_NUMERIC,
    /* Urdu */
    GUI_VIRTUAL_KEYBOARD_URDU,
	GUI_VIRTUAL_KEYBOARD_URDU_UPPERCASE,
    GUI_VIRTUAL_KEYBOARD_URDU_SYMBOLS,
    GUI_VIRTUAL_KEYBOARD_URDU_NUMERIC,
    /* Europe */
    GUI_VIRTUAL_KEYBOARD_SPANISH,
    GUI_VIRTUAL_KEYBOARD_SPANISH_SYMBOL,
    GUI_VIRTUAL_KEYBOARD_SPANISH_UPPERCASE,
    GUI_VIRTUAL_KEYBOARD_FRENCH,
    GUI_VIRTUAL_KEYBOARD_FRENCH_UPPERCASE,
    GUI_VIRTUAL_KEYBOARD_GERMAN,
    GUI_VIRTUAL_KEYBOARD_GERMAN_UPPERCASE,
    GUI_VIRTUAL_KEYBOARD_SA_PORTUGUESE,
    GUI_VIRTUAL_KEYBOARD_SA_PORTUGUESE_UPPERCASE,
    GUI_VIRTUAL_KEYBOARD_CA_FRENCH,
    GUI_VIRTUAL_KEYBOARD_CA_FRENCH_UPPERCASE,
    GUI_VIRTUAL_KEYBOARD_SA_SPANISH,
    GUI_VIRTUAL_KEYBOARD_SA_SPANISH_UPPERCASE,
    GUI_VIRTUAL_KEYBOARD_HK_CHINESE,
    GUI_VIRTUAL_KEYBOARD_HK_CHINESE_UPPERCASE,
    GUI_VIRTUAL_KEYBOARD_UK_ENGLISH,
    GUI_VIRTUAL_KEYBOARD_UK_ENGLISH_UPPERCASE,
    GUI_VIRTUAL_KEYBOARD_ICELANDIC,
    GUI_VIRTUAL_KEYBOARD_ICELANDIC_UPPERCASE,
    GUI_VIRTUAL_KEYBOARD_SERBIAN,
    GUI_VIRTUAL_KEYBOARD_SERBIAN_UPPERCASE,
    GUI_VIRTUAL_KEYBOARD_AZERBAIJANI,
    GUI_VIRTUAL_KEYBOARD_AZERBAIJANI_UPPERCASE,
    GUI_VIRTUAL_KEYBOARD_CATALAN,
    GUI_VIRTUAL_KEYBOARD_CATALAN_UPPERCASE,
    GUI_VIRTUAL_KEYBOARD_HAUSA,
    GUI_VIRTUAL_KEYBOARD_HAUSA_UPPERCASE,
    GUI_VIRTUAL_KEYBOARD_GALICIAN,
    GUI_VIRTUAL_KEYBOARD_GALICIAN_UPPERCASE,
    GUI_VIRTUAL_KEYBOARD_BASQUE,
    GUI_VIRTUAL_KEYBOARD_BASQUE_UPPERCASE,
    GUI_VIRTUAL_KEYBOARD_IGBO,
    GUI_VIRTUAL_KEYBOARD_IGBO_UPPERCASE,
    GUI_VIRTUAL_KEYBOARD_FILIPINO,
    GUI_VIRTUAL_KEYBOARD_FILIPINO_UPPERCASE,
    GUI_VIRTUAL_KEYBOARD_IRISH,
    GUI_VIRTUAL_KEYBOARD_IRISH_UPPERCASE,
    GUI_VIRTUAL_KEYBOARD_ALBANIAN,
    GUI_VIRTUAL_KEYBOARD_ALBANIAN_UPPERCASE,
    GUI_VIRTUAL_KEYBOARD_KAZAKH,
    GUI_VIRTUAL_KEYBOARD_KAZAKH_UPPERCASE,
    GUI_VIRTUAL_KEYBOARD_MACEDONIAN,
    GUI_VIRTUAL_KEYBOARD_MACEDONIAN_UPPERCASE,
    GUI_VIRTUAL_KEYBOARD_SESOTHO,
    GUI_VIRTUAL_KEYBOARD_SESOTHO_UPPERCASE,
    GUI_VIRTUAL_KEYBOARD_TAGALOG,
    GUI_VIRTUAL_KEYBOARD_TAGALOG_UPPERCASE,
    GUI_VIRTUAL_KEYBOARD_YORUBA,
    GUI_VIRTUAL_KEYBOARD_YORUBA_UPPERCASE,
    GUI_VIRTUAL_KEYBOARD_ITALIAN,
    GUI_VIRTUAL_KEYBOARD_ITALIAN_UPPERCASE,
    GUI_VIRTUAL_KEYBOARD_RUSSIAN,
    GUI_VIRTUAL_KEYBOARD_RUSSIAN_UPPERCASE,
    GUI_VIRTUAL_KEYBOARD_TURKISH,
    GUI_VIRTUAL_KEYBOARD_TURKISH_UPPERCASE,
    GUI_VIRTUAL_KEYBOARD_PORTUGUESE,
    GUI_VIRTUAL_KEYBOARD_PORTUGUESE_UPPERCASE,
    GUI_VIRTUAL_KEYBOARD_EUROPEAN_SYMBOLS,
    GUI_VIRTUAL_KEYBOARD_CZECH,
    GUI_VIRTUAL_KEYBOARD_CZECH_UPPERCASE,
    GUI_VIRTUAL_KEYBOARD_KOREAN,

    GUI_VIRTUAL_KEYBOARD_HEBREW,

     GUI_VIRTUAL_KEYBOARD_FARSI,
     GUI_VIRTUAL_KEYBOARD_FARSI_SYMBOL,

     GUI_VIRTUAL_KEYBOARD_GREEK,
     GUI_VIRTUAL_KEYBOARD_GREEK_UPPERCASE,

     GUI_VIRTUAL_KEYBOARD_BULGARIAN,
     GUI_VIRTUAL_KEYBOARD_BULGARIAN_UPPERCASE,

     GUI_VIRTUAL_KEYBOARD_DANISH,
     GUI_VIRTUAL_KEYBOARD_DANISH_UPPERCASE,

     GUI_VIRTUAL_KEYBOARD_NORWEGIAN,
     GUI_VIRTUAL_KEYBOARD_NORWEGIAN_UPPERCASE,

     GUI_VIRTUAL_KEYBOARD_SLOVAK,
     GUI_VIRTUAL_KEYBOARD_SLOVAK_UPPERCASE,

     GUI_VIRTUAL_KEYBOARD_HUNGARIAN,
     GUI_VIRTUAL_KEYBOARD_HUNGARIAN_UPPERCASE,

     GUI_VIRTUAL_KEYBOARD_FINNISH,
     GUI_VIRTUAL_KEYBOARD_FINNISH_UPPERCASE,

     GUI_VIRTUAL_KEYBOARD_SWEDISH,
     GUI_VIRTUAL_KEYBOARD_SWEDISH_UPPERCASE,

     GUI_VIRTUAL_KEYBOARD_CROATIAN,
     GUI_VIRTUAL_KEYBOARD_CROATIAN_UPPERCASE,

     GUI_VIRTUAL_KEYBOARD_SLOVENIAN,
     GUI_VIRTUAL_KEYBOARD_SLOVENIAN_UPPERCASE,

     GUI_VIRTUAL_KEYBOARD_DUTCH,
     GUI_VIRTUAL_KEYBOARD_DUTCH_UPPERCASE,

     GUI_VIRTUAL_KEYBOARD_POLISH,
     GUI_VIRTUAL_KEYBOARD_POLISH_UPPERCASE = GUI_VIRTUAL_KEYBOARD_POLISH,

     GUI_VIRTUAL_KEYBOARD_ROMANIAN,
     GUI_VIRTUAL_KEYBOARD_ROMANIAN_UPPERCASE,

     GUI_VIRTUAL_KEYBOARD_MOLDOVAN,
     GUI_VIRTUAL_KEYBOARD_MOLDOVAN_UPPERCASE,

    GUI_VIRTUAL_KEYBOARD_UKRAINIAN,
    GUI_VIRTUAL_KEYBOARD_UKRAINIAN_UPPERCASE,
    
    GUI_VIRTUAL_KEYBOARD_LATVIAN,
    GUI_VIRTUAL_KEYBOARD_LATVIAN_UPPERCASE,
    
    GUI_VIRTUAL_KEYBOARD_ESTONIAN,
    GUI_VIRTUAL_KEYBOARD_ESTONIAN_UPPERCASE,
    
    GUI_VIRTUAL_KEYBOARD_ARMENIAN,
    GUI_VIRTUAL_KEYBOARD_ARMENIAN_UPPERCASE,
    
    GUI_VIRTUAL_KEYBOARD_LITHUANIAN,
    GUI_VIRTUAL_KEYBOARD_LITHUANIAN_UPPERCASE,

    /*Asian*/
	/*Myanmar*/
	GUI_VIRTUAL_KEYBOARD_MYANMAR,
	GUI_VIRTUAL_KEYBOARD_MYANMAR_UPPERCASE,
	/*Khmer*/
	GUI_VIRTUAL_KEYBOARD_KHMER,
	GUI_VIRTUAL_KEYBOARD_KHMER_UPPERCASE,

    GUI_VIRTUAL_KEYBOARD_GEORGIAN,
    GUI_VIRTUAL_KEYBOARD_INTERNET, /* new function */
    GUI_VIRTUAL_KEYBOARD_INTERNET_UPPERCASE,
    GUI_VIRTUAL_KEYBOARD_NUM_AND_HALFWIDTH_SYMBOL, /* new function */
    GUI_VIRTUAL_KEYBOARD_INTERNET_SYM_PAGE_ONE,
    GUI_VIRTUAL_KEYBOARD_INTERNET_SYM_PAGE_TWO,
    GUI_VIRTUAL_KEYBOARD_INTERNET_SYM_PAGE_THREE,
    GUI_VIRTUAL_KEYBOARD_KEYPAD_NUMERIC,
    GUI_VIRTUAL_KEYBOARD_SIM_NUMERIC,
    GUI_VIRTUAL_KEYBOARD_TEXT_PHONE_NUMBER,
    GUI_VIRTUAL_KEYBOARD_TEXT_PHONE_NUMBER_WILDCHAR,
    GUI_VIRTUAL_KEYBOARD_DIALER_DUAL_SIM,
	GUI_VIRTUAL_KEYBOARD_VIDEO_DIALER_DUAL_SIM,
	GUI_VIRTUAL_KEYBOARD_VIDEO_DIALER_SINGLE_SIM,
    GUI_VIRTUAL_KEYBOARD_DIALER_SINGLE_SIM,
	GUI_VIRTUAL_KEYBOARD_DIALER_NORMAL_CALL,
	GUI_VIRTUAL_KEYBOARD_DIALER_EMERGENCY_CALL,
    GUI_VIRTUAL_KEYBOARD_MAX_LANG
} gui_virtual_keyboard_language_enum;

/* <group dom_virtual_keyboard_enum>
 *  Pen events */
typedef enum
{
    GUI_VKBD_PEN_NONE = 0x00010000,
    GUI_VKBD_PEN_DISPLAY_AREA,
    GUI_VKBD_PEN_CHAR_I,
    GUI_VKBD_PEN_HIDE,
    GUI_VKBD_PEN_SHOW,
    GUI_VKBD_PEN_CAPSLOCK,
    GUI_VKBD_PEN_SPACE,
    GUI_VKBD_PEN_BAKSPACE,
    GUI_VKBD_PEN_SYMBPICKER,
    GUI_VKBD_PEN_BRACKET,
    GUI_VKBD_PEN_NEWLINE,
    GUI_VKBD_PEN_EUROSYMB,
    GUI_VKBD_PEN_DEAD_KEY,
    GUI_VKBD_PEN_DISPLAY_CALLBACK,
    GUI_VKBD_PEN_NUM_AND_SYM, /* new function */
    GUI_VKBD_PEN_CHANGE_MODE, /* new function */
    GUI_VKBD_PEN_HANDWRITING, /* new function */
    GUI_VKBD_PEN_DOT_COM, /* new function */
    GUI_VKBD_PEN_DOT_ORG, /* new function */
    GUI_VKBD_PEN_DOT_NET, /* new function */
    GUI_VKBD_PEN_DOT_GOV, /* new function */
    GUI_VKBD_PEN_DOT_EDU, /* new function */
    GUI_VKBD_PEN_DOT_MIL, /* new function */
    GUI_VKBD_PEN_BACK_TO_LANG, /* new function */
    GUI_VKBD_PEN_ZI_STROKE_1, /* new function */
    GUI_VKBD_PEN_ZI_STROKE_2, /* new function */
    GUI_VKBD_PEN_ZI_STROKE_3, /* new function */
    GUI_VKBD_PEN_ZI_STROKE_4, /* new function */
    GUI_VKBD_PEN_ZI_STROKE_5, /* new function */
    GUI_VKBD_PEN_ZI_STROKE_6, /* new function */
    GUI_VKBD_PEN_ZI_STROKE_7, /* new function */
    GUI_VKBD_PEN_ZI_STROKE_8, /* new function */
    GUI_VKBD_PEN_ZI_STROKE_9, /* new function */
    GUI_VKBD_PEN_ZI_STROKE_DEPART, /* new function */    
    GUI_VKBD_PEN_ALPHANUMERIC_KEY_0, /* new function for alphanumeric keypad */
    GUI_VKBD_PEN_ALPHANUMERIC_KEY_1, /* new function for alphanumeric keypad */
    GUI_VKBD_PEN_ALPHANUMERIC_KEY_2, /* new function for alphanumeric keypad */
    GUI_VKBD_PEN_ALPHANUMERIC_KEY_3, /* new function for alphanumeric keypad */
    GUI_VKBD_PEN_ALPHANUMERIC_KEY_4, /* new function for alphanumeric keypad */
    GUI_VKBD_PEN_ALPHANUMERIC_KEY_5, /* new function for alphanumeric keypad */
    GUI_VKBD_PEN_ALPHANUMERIC_KEY_6, /* new function for alphanumeric keypad */
    GUI_VKBD_PEN_ALPHANUMERIC_KEY_7, /* new function for alphanumeric keypad */
    GUI_VKBD_PEN_ALPHANUMERIC_KEY_8, /* new function for alphanumeric keypad */
    GUI_VKBD_PEN_ALPHANUMERIC_KEY_9, /* new function for alphanumeric keypad */
    GUI_VKBD_PEN_ALPHANUMERIC_KEY_STAR, /* new function for alphanumeric keypad */
    GUI_VKBD_PEN_ALPHANUMERIC_KEY_POUND, /* new function for alphanumeric keypad */
    GUI_VKBD_PEN_ALPHANUMERIC_KEY_DELETE, /* new function for alphanumeric keypad */
    GUI_VKBD_PEN_ALPHANUMERIC_KEY_CAPS_LOCK, /* new function for alphanumeric keypad */
    GUI_VKBD_PEN_ALPHANUMERIC_KEY_NUM, /* new function for alphanumeric keypad */
    GUI_VKBD_PEN_ALPHANUMERIC_KEY_HANDWRITING, /* new function for alphanumeric keypad */
    GUI_VKBD_PEN_ALPHANUMERIC_KEY_HIDE, /* new function for alphanumeric keypad */
    GUI_VKBD_PEN_ALPHANUMERIC_KEY_SPACE,  /* new function for alphanumeric keypad */
    GUI_VKBD_PEN_ALPHANUMERIC_KEY_BACK_TO_LANG,  /* new function for alphanumeric keypad */
    GUI_VKBD_PEN_ALPHANUMERIC_SYM_PREV_PAGE,  /* new function for alphanumeric keypad */
    GUI_VKBD_PEN_ALPHANUMERIC_SYM_NEXT_PAGE,   /* new function for alphanumeric keypad */
    GUI_VKBD_PEN_ALPHANUMERIC_SYM_LOCK,   /* new function for alphanumeric keypad */
    GUI_VKBD_PEN_ALPHANUMERIC_SYMBPICKER,   /* new function for alphanumeric keypad */
    GUI_VKBD_PEN_ALPHANUMERIC_CHANGE_MODE,   /* new function for alphanumeric keypad */
    GUI_VKBD_PEN_ALPHANUMERIC_NEWLINE,   /* new function for alphanumeric keypad */    
    GUI_VKBD_PEN_ALPHANUMERIC_EMOTION_1,   /* new function for alphanumeric keypad */    
    GUI_VKBD_PEN_ALPHANUMERIC_EMOTION_2,   /* new function for alphanumeric keypad */    
    GUI_VKBD_PEN_ALPHANUMERIC_EMOTION_3,   /* new function for alphanumeric keypad */    
    GUI_VKBD_PEN_ALPHANUMERIC_EMOTION_4,   /* new function for alphanumeric keypad */    
    GUI_VKBD_PEN_ALPHANUMERIC_EMOTION_5,   /* new function for alphanumeric keypad */    
    GUI_VKBD_PEN_ALPHANUMERIC_EMOTION_6,   /* new function for alphanumeric keypad */    
    GUI_VKBD_PEN_ALPHANUMERIC_EMOTION_7,   /* new function for alphanumeric keypad */    
    GUI_VKBD_PEN_ALPHANUMERIC_EMOTION_8,   /* new function for alphanumeric keypad */    
    GUI_VKBD_PEN_ALPHANUMERIC_EMOTION_9,   /* new function for alphanumeric keypad */    
    GUI_VKBD_PEN_ALPHANUMERIC_EMOTION_10,   /* new function for alphanumeric keypad */    
    GUI_VKBD_PEN_ALPHANUMERIC_EMOTION_11,   /* new function for alphanumeric keypad */    
    GUI_VKBD_PEN_ALPHANUMERIC_DOT_COM, /* new function */
    GUI_VKBD_PEN_INDIC_SLIDE1_CAPSLOCK_ON,
    GUI_VKBD_PEN_INDIC_SLIDE1_CAPSLOCK_OFF,
    GUI_VKBD_PEN_INDIC_SLIDE2_CAPSLOCK_ON,
    GUI_VKBD_PEN_INDIC_SLIDE2_CAPSLOCK_OFF,
    GUI_VKBD_PEN_INDIC_SYMBPICKER,
    GUI_VKBD_PEN_INDIC_SLIDE1,
    GUI_VKBD_PEN_INDIC_SLIDE2,
    GUI_VKBD_PEN_ZHUYIN_B_P, /* for Zhuyin B & P */
    GUI_VKBD_PEN_ZHUYIN_M_F, /* for Zhuyin M & F */
    GUI_VKBD_PEN_ZHUYIN_D_T, /* for Zhuyin D & T */
    GUI_VKBD_PEN_ZHUYIN_N_L, /* for Zhuyin N & L */
    GUI_VKBD_PEN_ZHUYIN_G_J, /* for Zhuyin G & J */
    GUI_VKBD_PEN_ZHUYIN_K_Q, /* for Zhuyin K & Q */
    GUI_VKBD_PEN_ZHUYIN_H_X, /* for Zhuyin H & X */
    GUI_VKBD_PEN_ZHUYIN_ZH_CH, /* for Zhuyin ZH & CH */
    GUI_VKBD_PEN_ZHUYIN_SH, /* for Zhuyin SH */
    GUI_VKBD_PEN_ZHUYIN_R, /* for Zhuyin R */
    GUI_VKBD_PEN_ZHUYIN_Z, /* for Zhuyin Z */
    GUI_VKBD_PEN_ZHUYIN_C, /* for Zhuyin C */
    GUI_VKBD_PEN_ZHUYIN_S, /* for Zhuyin S */
    GUI_VKBD_PEN_ZHUYIN_I, /* for Zhuyin I */
    GUI_VKBD_PEN_ZHUYIN_U, /* for Zhuyin U */
    GUI_VKBD_PEN_ZHUYIN_IU, /* for Zhuyin IU */    
    GUI_VKBD_PEN_ZHUYIN_A_O, /* for Zhuyin A & O */
    GUI_VKBD_PEN_ZHUYIN_E, /* for Zhuyin E */
    GUI_VKBD_PEN_ZHUYIN_EH, /* for Zhuyin EH */
    GUI_VKBD_PEN_ZHUYIN_AI_EI, /* for Zhuyin AI & EI */
    GUI_VKBD_PEN_ZHUYIN_AU, /* for Zhuyin AU */
    GUI_VKBD_PEN_ZHUYIN_OU, /* for Zhuyin OU */
    GUI_VKBD_PEN_ZHUYIN_AN_EN, /* for Zhuyin AI & EI */
    GUI_VKBD_PEN_ZHUYIN_ANG, /* for Zhuyin AU */
    GUI_VKBD_PEN_ZHUYIN_ENG, /* for Zhuyin OU */
    GUI_VKBD_PEN_ZHUYIN_ER, /* for Zhuyin ER */
    GUI_VKBD_PEN_ZHUYIN_TONE, /* for Zhuyin tone */
    GUI_VKBD_PEN_STROKE_1, /* new function */
    GUI_VKBD_PEN_STROKE_2, /* new function */
    GUI_VKBD_PEN_STROKE_3, /* new function */
    GUI_VKBD_PEN_STROKE_4, /* new function */
    GUI_VKBD_PEN_STROKE_5, /* new function */
    GUI_VKBD_PEN_STROKE_DEPART, /* new function */   
    GUI_VKBD_PEN_ZHUYIN_TONE_3,
    GUI_VKBD_PEN_ZHUYIN_TONE_4,
    GUI_VKBD_PEN_ZHUYIN_TONE_2_5,
    GUI_VKBD_PEN_ZHUYIN_COMMA_DOT,
    /* Dialer Events for vk */
    GUI_VKBD_PEN_ALPHANUMERIC_DIALER_KEY_0, 
    GUI_VKBD_PEN_ALPHANUMERIC_DIALER_KEY_1,  
	GUI_VKBD_PEN_ALPHANUMERIC_DIALER_KEY_2,  
	GUI_VKBD_PEN_ALPHANUMERIC_DIALER_KEY_3,  
	GUI_VKBD_PEN_ALPHANUMERIC_DIALER_KEY_4,  
	GUI_VKBD_PEN_ALPHANUMERIC_DIALER_KEY_5,  
	GUI_VKBD_PEN_ALPHANUMERIC_DIALER_KEY_6,  
	GUI_VKBD_PEN_ALPHANUMERIC_DIALER_KEY_7,  
	GUI_VKBD_PEN_ALPHANUMERIC_DIALER_KEY_8,  
	GUI_VKBD_PEN_ALPHANUMERIC_DIALER_KEY_9,  
	GUI_VKBD_PEN_ALPHANUMERIC_DIALER_KEY_STAR,
	GUI_VKBD_PEN_ALPHANUMERIC_DIALER_KEY_POUND,
	GUI_VKBD_PEN_ALPHANUMERIC_KEY_VIDEO_CALL,
	GUI_VKBD_PEN_ALPHANUMERIC_DIALER_KEY_CALL1,
	GUI_VKBD_PEN_ALPHANUMERIC_DIALER_KEY_CALL2,
	GUI_VKBD_PEN_ALPHANUMERIC_DIALER_KEY_N_CALL,
	GUI_VKBD_PEN_ALPHANUMERIC_DIALER_KEY_E_CALL,

    GUI_VKBD_PEN_MAX
} gui_virtual_keyboard_pen_enum;

#else

#define MMI_VK_TYPE_ROTATION            0x00000001
/* <group dom_virtual_keyboard_macros> */
#define MMI_VK_TYPE_NOT_ROTATION    0x00000002
/* <group dom_virtual_keyboard_macros> */
#define MMI_VK_TYPE_QWERTY              0x00000004
/* <group dom_virtual_keyboard_macros> */
#define MMI_VK_TYPE_ALPHANUMERIC   0x00000008
/* <group dom_virtual_keyboard_macros> */
#define MMI_VK_TYPE_HW 0x00000010

typedef enum
    {
        //for old version
            GUI_VIRTUAL_KEYBOARD_ENGLISH ,
            GUI_VIRTUAL_KEYBOARD_ENGLISH_UPPERCASE = GUI_VIRTUAL_KEYBOARD_ENGLISH,
            GUI_VIRTUAL_KEYBOARD_SYMBOL,
            GUI_VIRTUAL_KEYBOARD_TRAY,
            GUI_VIRTUAL_KEYBOARD_EMPTY_TRAY,
            GUI_VIRTUAL_KEYBOARD_NUMBER,
            GUI_VIRTUAL_KEYBOARD_SIM_NUMERIC = GUI_VIRTUAL_KEYBOARD_NUMBER,
            GUI_VIRTUAL_KEYBOARD_SYMBOL_FOR_NUM = GUI_VIRTUAL_KEYBOARD_NUMBER, /* new vk */
            GUI_VIRTUAL_KEYBOARD_NUMBER_AND_SYMBOL = GUI_VIRTUAL_KEYBOARD_NUMBER, /* new vk */
            GUI_VIRTUAL_KEYBOARD_LANG_NUMBER = GUI_VIRTUAL_KEYBOARD_NUMBER, /* new vk (for alphanumeric input with language vk) */
            GUI_VIRTUAL_KEYBOARD_PHONE_NUMBER = GUI_VIRTUAL_KEYBOARD_NUMBER,
            GUI_VIRTUAL_KEYBOARD_PHONE_NUMBER_WILDCHAR = GUI_VIRTUAL_KEYBOARD_NUMBER,
            GUI_VIRTUAL_KEYBOARD_NUMBER_TRAY = GUI_VIRTUAL_KEYBOARD_NUMBER,
            GUI_VIRTUAL_KEYBOARD_NUMBER_DOT_TRAY = GUI_VIRTUAL_KEYBOARD_NUMBER,
            GUI_VIRTUAL_KEYBOARD_KEYPAD_NUMERIC = GUI_VIRTUAL_KEYBOARD_NUMBER,
            GUI_VIRTUAL_KEYBOARD_TEXT_PHONE_NUMBER = GUI_VIRTUAL_KEYBOARD_NUMBER ,
            GUI_VIRTUAL_KEYBOARD_TEXT_PHONE_NUMBER_WILDCHAR = GUI_VIRTUAL_KEYBOARD_NUMBER,
            /* new vk */
            GUI_VIRTUAL_KEYBOARD_ALPHANUMERIC_SYMBOL_PAGE_1,
            GUI_VIRTUAL_KEYBOARD_ALPHANUMERIC_SYMBOL_PAGE_2,
            GUI_VIRTUAL_KEYBOARD_ALPHANUMERIC_SYMBOL_PAGE_3,
            GUI_VIRTUAL_KEYBOARD_ALPHANUMERIC_SYMBOL_PAGE_4,
            /* Chinese */
            GUI_VIRTUAL_KEYBOARD_PINYIN,
            GUI_VIRTUAL_KEYBOARD_BOPOMO,
            GUI_VIRTUAL_KEYBOARD_NUMBER_AND_CH_SYMBOL, /* new vk */
            GUI_VIRTUAL_KEYBOARD_CHINESE_SYMBOL,
            GUI_VIRTUAL_KEYBOARD_TR_STROKE,
            GUI_VIRTUAL_KEYBOARD_SM_STROKE = GUI_VIRTUAL_KEYBOARD_TR_STROKE,
            /* new vk */
            GUI_VIRTUAL_KEYBOARD_ALPHANUMERIC_CH_SYMBOL_PAGE_1,
            GUI_VIRTUAL_KEYBOARD_ALPHANUMERIC_CH_SYMBOL_PAGE_2,
            GUI_VIRTUAL_KEYBOARD_ALPHANUMERIC_CH_SYMBOL_PAGE_3,
            GUI_VIRTUAL_KEYBOARD_ALPHANUMERIC_CH_SYMBOL_PAGE_4,
            /* Asia-pacific */
            GUI_VIRTUAL_KEYBOARD_THAI,
            GUI_VIRTUAL_KEYBOARD_THAI_LOWERCASE,
             GUI_VIRTUAL_KEYBOARD_THAI_NUMERIC,
            GUI_VIRTUAL_KEYBOARD_THAI_SYMBOL,
            GUI_VIRTUAL_KEYBOARD_INDONESIAN,
            GUI_VIRTUAL_KEYBOARD_INDONESIAN_UPPERCASE = GUI_VIRTUAL_KEYBOARD_INDONESIAN,
            GUI_VIRTUAL_KEYBOARD_MALAY,
            GUI_VIRTUAL_KEYBOARD_MALAY_UPPERCASE = GUI_VIRTUAL_KEYBOARD_MALAY,
            GUI_VIRTUAL_KEYBOARD_VIETNAMESE,
            GUI_VIRTUAL_KEYBOARD_VIETNAMESE_UPPERCASE = GUI_VIRTUAL_KEYBOARD_VIETNAMESE,
            /* Hindi */
            GUI_VIRTUAL_KEYBOARD_HINDI,
            GUI_VIRTUAL_KEYBOARD_HINDI_LOWERCASE,
            GUI_VIRTUAL_KEYBOARD_HINDI_UPPERCASE,
            GUI_VIRTUAL_KEYBOARD_HINDI_CONS_MATRAS1 = GUI_VIRTUAL_KEYBOARD_HINDI,
            GUI_VIRTUAL_KEYBOARD_HINDI_CONS_MATRAS2 = GUI_VIRTUAL_KEYBOARD_HINDI,
            GUI_VIRTUAL_KEYBOARD_HINDI_CONS_INDEPEDENTVOWELS1 = GUI_VIRTUAL_KEYBOARD_HINDI_UPPERCASE + 1,
            GUI_VIRTUAL_KEYBOARD_HINDI_CONS_INDEPEDENTVOWELS2,
            GUI_VIRTUAL_KEYBOARD_HINDI_SYMBOLS,
			GUI_VIRTUAL_KEYBOARD_TAMIL,
			GUI_VIRTUAL_KEYBOARD_TAMIL_UPPERCASE,
            GUI_VIRTUAL_KEYBOARD_TAMIL_CONS_MATRAS1 = GUI_VIRTUAL_KEYBOARD_TAMIL,
            GUI_VIRTUAL_KEYBOARD_TAMIL_CONS_INDEPEDENTVOWELS1 = GUI_VIRTUAL_KEYBOARD_TAMIL,
            GUI_VIRTUAL_KEYBOARD_TAMIL_SYMBOLS = GUI_VIRTUAL_KEYBOARD_TAMIL_UPPERCASE + 1,

			/*Myanmar*/
			GUI_VIRTUAL_KEYBOARD_MYANMAR,
			GUI_VIRTUAL_KEYBOARD_MYANMAR_UPPERCASE,

			/*Khmer*/

			GUI_VIRTUAL_KEYBOARD_KHMER,
			GUI_VIRTUAL_KEYBOARD_KHMER_UPPERCASE,

			/*Punjabi*/
			GUI_VIRTUAL_KEYBOARD_PUNJABI,
			GUI_VIRTUAL_KEYBOARD_PUNJABI_UPPERCASE,

			GUI_VIRTUAL_KEYBOARD_SWAHILI,
			GUI_VIRTUAL_KEYBOARD_SWAHILI_UPPERCASE ,
            GUI_VIRTUAL_KEYBOARD_BENGALI,
            GUI_VIRTUAL_KEYBOARD_BENGALI_LOWERCASE,
            GUI_VIRTUAL_KEYBOARD_BENGALI_CONS_MATRAS1 = GUI_VIRTUAL_KEYBOARD_BENGALI,
            GUI_VIRTUAL_KEYBOARD_BENGALI_CONS_MATRAS2 = GUI_VIRTUAL_KEYBOARD_BENGALI,
            GUI_VIRTUAL_KEYBOARD_BENGALI_CONS_INDEPEDENTVOWELS1 = GUI_VIRTUAL_KEYBOARD_BENGALI,
            GUI_VIRTUAL_KEYBOARD_BENGALI_CONS_INDEPEDENTVOWELS2 = GUI_VIRTUAL_KEYBOARD_BENGALI,
            GUI_VIRTUAL_KEYBOARD_BENGALI_SYMBOLS = GUI_VIRTUAL_KEYBOARD_BENGALI_LOWERCASE + 1,
			GUI_VIRTUAL_KEYBOARD_ASSAMESE,
			GUI_VIRTUAL_KEYBOARD_ASSAMESE_LOWERCASE,
			GUI_VIRTUAL_KEYBOARD_ASSAMESE_UPPERCASE,
            GUI_VIRTUAL_KEYBOARD_ASSAMESE_CONS_MATRAS1 = GUI_VIRTUAL_KEYBOARD_ASSAMESE,
            GUI_VIRTUAL_KEYBOARD_ASSAMESE_CONS_MATRAS2 = GUI_VIRTUAL_KEYBOARD_ASSAMESE,
            GUI_VIRTUAL_KEYBOARD_ASSAMESE_CONS_INDEPEDENTVOWELS1 = GUI_VIRTUAL_KEYBOARD_ASSAMESE_UPPERCASE + 1,
            GUI_VIRTUAL_KEYBOARD_ASSAMESE_CONS_INDEPEDENTVOWELS2,
            GUI_VIRTUAL_KEYBOARD_ASSAMESE_SYMBOLS,    
            GUI_VIRTUAL_KEYBOARD_PUNJABI_CONS_MATRAS1 = GUI_VIRTUAL_KEYBOARD_PUNJABI,
            GUI_VIRTUAL_KEYBOARD_PUNJABI_CONS_MATRAS2 = GUI_VIRTUAL_KEYBOARD_PUNJABI,
            GUI_VIRTUAL_KEYBOARD_PUNJABI_CONS_INDEPEDENTVOWELS1 = GUI_VIRTUAL_KEYBOARD_ASSAMESE_SYMBOLS + 1,
            GUI_VIRTUAL_KEYBOARD_PUNJABI_CONS_INDEPEDENTVOWELS2,
            GUI_VIRTUAL_KEYBOARD_PUNJABI_SYMBOLS,
			GUI_VIRTUAL_KEYBOARD_GUJARATI,
			GUI_VIRTUAL_KEYBOARD_GUJARATI_LOWERCASE,
			GUI_VIRTUAL_KEYBOARD_GUJARATI_UPPERCASE,
            GUI_VIRTUAL_KEYBOARD_GUJARATI_CONS_MATRAS1 = GUI_VIRTUAL_KEYBOARD_GUJARATI,
            GUI_VIRTUAL_KEYBOARD_GUJARATI_CONS_MATRAS2 = GUI_VIRTUAL_KEYBOARD_GUJARATI,
            GUI_VIRTUAL_KEYBOARD_GUJARATI_CONS_INDEPEDENTVOWELS1 = GUI_VIRTUAL_KEYBOARD_GUJARATI_UPPERCASE + 1,
            GUI_VIRTUAL_KEYBOARD_GUJARATI_CONS_INDEPEDENTVOWELS2,
            GUI_VIRTUAL_KEYBOARD_GUJARATI_SYMBOLS,
			GUI_VIRTUAL_KEYBOARD_KANNADA,
			GUI_VIRTUAL_KEYBOARD_KANNADA_LOWERCASE,
			GUI_VIRTUAL_KEYBOARD_KANNADA_UPPERCASE,
            GUI_VIRTUAL_KEYBOARD_KANNADA_CONS_MATRAS1 = GUI_VIRTUAL_KEYBOARD_KANNADA,
            GUI_VIRTUAL_KEYBOARD_KANNADA_CONS_MATRAS2 = GUI_VIRTUAL_KEYBOARD_KANNADA,
            GUI_VIRTUAL_KEYBOARD_KANNADA_CONS_INDEPEDENTVOWELS1 = GUI_VIRTUAL_KEYBOARD_KANNADA_UPPERCASE + 1,
            GUI_VIRTUAL_KEYBOARD_KANNADA_CONS_INDEPEDENTVOWELS2,
            GUI_VIRTUAL_KEYBOARD_KANNADA_SYMBOLS,
            GUI_VIRTUAL_KEYBOARD_ORIYA_CONS_MATRAS1,
            GUI_VIRTUAL_KEYBOARD_ORIYA_CONS_MATRAS2,
            GUI_VIRTUAL_KEYBOARD_ORIYA_CONS_INDEPEDENTVOWELS1,
            GUI_VIRTUAL_KEYBOARD_ORIYA_CONS_INDEPEDENTVOWELS2,
            GUI_VIRTUAL_KEYBOARD_ORIYA_SYMBOLS,
			GUI_VIRTUAL_KEYBOARD_MALAYALAM,
			GUI_VIRTUAL_KEYBOARD_MALAYALAM_LOWERCASE,
			GUI_VIRTUAL_KEYBOARD_MALAYALAM_UPPERCASE,
            GUI_VIRTUAL_KEYBOARD_MALAYALAM_CONS_MATRAS1 = GUI_VIRTUAL_KEYBOARD_MALAYALAM,
            GUI_VIRTUAL_KEYBOARD_MALAYALAM_CONS_MATRAS2 = GUI_VIRTUAL_KEYBOARD_MALAYALAM,
            GUI_VIRTUAL_KEYBOARD_MALAYALAM_CONS_INDEPEDENTVOWELS1 = GUI_VIRTUAL_KEYBOARD_MALAYALAM_UPPERCASE + 1 ,
            GUI_VIRTUAL_KEYBOARD_MALAYALAM_CONS_INDEPEDENTVOWELS2,
            GUI_VIRTUAL_KEYBOARD_MALAYALAM_SYMBOLS,
			GUI_VIRTUAL_KEYBOARD_TELUGU,
			GUI_VIRTUAL_KEYBOARD_TELUGU_UPPERCASE,
            GUI_VIRTUAL_KEYBOARD_TELUGU_CONS_MATRAS1 = GUI_VIRTUAL_KEYBOARD_TELUGU,
            GUI_VIRTUAL_KEYBOARD_TELUGU_CONS_MATRAS2 = GUI_VIRTUAL_KEYBOARD_TELUGU,
            GUI_VIRTUAL_KEYBOARD_TELUGU_CONS_INDEPEDENTVOWELS1 = GUI_VIRTUAL_KEYBOARD_TELUGU_UPPERCASE + 1,
            GUI_VIRTUAL_KEYBOARD_TELUGU_CONS_INDEPEDENTVOWELS2,
            GUI_VIRTUAL_KEYBOARD_TELUGU_SYMBOLS,
            /* Arabic */
            GUI_VIRTUAL_KEYBOARD_ARABIC,
            GUI_VIRTUAL_KEYBOARD_ARABIC_LOWERCASE = GUI_VIRTUAL_KEYBOARD_ARABIC,
            GUI_VIRTUAL_KEYBOARD_ARABIC_SYMBOLS,
            GUI_VIRTUAL_KEYBOARD_ARABIC_NUMERIC,
            /* Urdu */
            GUI_VIRTUAL_KEYBOARD_URDU,
			GUI_VIRTUAL_KEYBOARD_URDU_UPPERCASE,
            GUI_VIRTUAL_KEYBOARD_URDU_SYMBOLS,
            GUI_VIRTUAL_KEYBOARD_URDU_NUMERIC,
            /* Europe */
            GUI_VIRTUAL_KEYBOARD_SPANISH,
            GUI_VIRTUAL_KEYBOARD_SPANISH_UPPERCASE = GUI_VIRTUAL_KEYBOARD_SPANISH,
            GUI_VIRTUAL_KEYBOARD_SA_SPANISH = GUI_VIRTUAL_KEYBOARD_SPANISH,
            GUI_VIRTUAL_KEYBOARD_SA_SPANISH_UPPERCASE = GUI_VIRTUAL_KEYBOARD_SA_SPANISH,
            GUI_VIRTUAL_KEYBOARD_SPANISH_SYMBOL,
            GUI_VIRTUAL_KEYBOARD_FRENCH,
            GUI_VIRTUAL_KEYBOARD_FRENCH_UPPERCASE = GUI_VIRTUAL_KEYBOARD_FRENCH,
            GUI_VIRTUAL_KEYBOARD_GERMAN,
            GUI_VIRTUAL_KEYBOARD_GERMAN_UPPERCASE = GUI_VIRTUAL_KEYBOARD_GERMAN,
            GUI_VIRTUAL_KEYBOARD_SA_PORTUGUESE,
            GUI_VIRTUAL_KEYBOARD_SA_PORTUGUESE_UPPERCASE = GUI_VIRTUAL_KEYBOARD_SA_PORTUGUESE,
            GUI_VIRTUAL_KEYBOARD_CA_FRENCH,
            GUI_VIRTUAL_KEYBOARD_CA_FRENCH_UPPERCASE = GUI_VIRTUAL_KEYBOARD_CA_FRENCH,
            GUI_VIRTUAL_KEYBOARD_HK_CHINESE,
            GUI_VIRTUAL_KEYBOARD_HK_CHINESE_UPPERCASE,
            GUI_VIRTUAL_KEYBOARD_UK_ENGLISH,
            GUI_VIRTUAL_KEYBOARD_UK_ENGLISH_UPPERCASE,
            GUI_VIRTUAL_KEYBOARD_ICELANDIC,
            GUI_VIRTUAL_KEYBOARD_ICELANDIC_UPPERCASE = GUI_VIRTUAL_KEYBOARD_ICELANDIC,
            GUI_VIRTUAL_KEYBOARD_SERBIAN,
            GUI_VIRTUAL_KEYBOARD_SERBIAN_UPPERCASE = GUI_VIRTUAL_KEYBOARD_SERBIAN,
            GUI_VIRTUAL_KEYBOARD_AZERBAIJANI,
			GUI_VIRTUAL_KEYBOARD_AZERBAIJANI_LOWERCASE = GUI_VIRTUAL_KEYBOARD_AZERBAIJANI,
            GUI_VIRTUAL_KEYBOARD_AZERBAIJANI_UPPERCASE = GUI_VIRTUAL_KEYBOARD_AZERBAIJANI,
            GUI_VIRTUAL_KEYBOARD_CATALAN,
            GUI_VIRTUAL_KEYBOARD_CATALAN_UPPERCASE = GUI_VIRTUAL_KEYBOARD_CATALAN,
            GUI_VIRTUAL_KEYBOARD_HAUSA,
            GUI_VIRTUAL_KEYBOARD_HAUSA_UPPERCASE = GUI_VIRTUAL_KEYBOARD_HAUSA,
            GUI_VIRTUAL_KEYBOARD_GALICIAN,
            GUI_VIRTUAL_KEYBOARD_GALICIAN_UPPERCASE = GUI_VIRTUAL_KEYBOARD_GALICIAN,
            GUI_VIRTUAL_KEYBOARD_BASQUE,
            GUI_VIRTUAL_KEYBOARD_BASQUE_UPPERCASE = GUI_VIRTUAL_KEYBOARD_BASQUE,
            GUI_VIRTUAL_KEYBOARD_IGBO,
            GUI_VIRTUAL_KEYBOARD_IGBO_UPPERCASE = GUI_VIRTUAL_KEYBOARD_IGBO,
            GUI_VIRTUAL_KEYBOARD_FILIPINO,
            GUI_VIRTUAL_KEYBOARD_FILIPINO_UPPERCASE = GUI_VIRTUAL_KEYBOARD_FILIPINO,
            GUI_VIRTUAL_KEYBOARD_IRISH,
            GUI_VIRTUAL_KEYBOARD_IRISH_UPPERCASE,
            GUI_VIRTUAL_KEYBOARD_ALBANIAN,
            GUI_VIRTUAL_KEYBOARD_ALBANIAN_UPPERCASE,
            GUI_VIRTUAL_KEYBOARD_KAZAKH,
            GUI_VIRTUAL_KEYBOARD_KAZAKH_UPPERCASE,
            GUI_VIRTUAL_KEYBOARD_MACEDONIAN,
            GUI_VIRTUAL_KEYBOARD_MACEDONIAN_UPPERCASE,
            GUI_VIRTUAL_KEYBOARD_SESOTHO,
            GUI_VIRTUAL_KEYBOARD_SESOTHO_UPPERCASE,
            GUI_VIRTUAL_KEYBOARD_TAGALOG,
            GUI_VIRTUAL_KEYBOARD_TAGALOG_UPPERCASE = GUI_VIRTUAL_KEYBOARD_TAGALOG,
            GUI_VIRTUAL_KEYBOARD_YORUBA,
            GUI_VIRTUAL_KEYBOARD_YORUBA_UPPERCASE = GUI_VIRTUAL_KEYBOARD_YORUBA,
            GUI_VIRTUAL_KEYBOARD_ITALIAN,
            GUI_VIRTUAL_KEYBOARD_ITALIAN_UPPERCASE = GUI_VIRTUAL_KEYBOARD_ITALIAN,
            GUI_VIRTUAL_KEYBOARD_RUSSIAN,
            GUI_VIRTUAL_KEYBOARD_RUSSIAN_UPPERCASE = GUI_VIRTUAL_KEYBOARD_RUSSIAN,
            GUI_VIRTUAL_KEYBOARD_TURKISH,
            GUI_VIRTUAL_KEYBOARD_TURKISH_UPPERCASE = GUI_VIRTUAL_KEYBOARD_TURKISH,
            GUI_VIRTUAL_KEYBOARD_PORTUGUESE,
            GUI_VIRTUAL_KEYBOARD_PORTUGUESE_UPPERCASE = GUI_VIRTUAL_KEYBOARD_PORTUGUESE,
            GUI_VIRTUAL_KEYBOARD_EUROPEAN_SYMBOLS,
            GUI_VIRTUAL_KEYBOARD_CZECH,
            GUI_VIRTUAL_KEYBOARD_CZECH_UPPERCASE = GUI_VIRTUAL_KEYBOARD_CZECH,
            GUI_VIRTUAL_KEYBOARD_KOREAN,
            
            GUI_VIRTUAL_KEYBOARD_HEBREW,
            
             GUI_VIRTUAL_KEYBOARD_FARSI,
             GUI_VIRTUAL_KEYBOARD_FARSI_SYMBOL,
            
             GUI_VIRTUAL_KEYBOARD_GREEK,
             GUI_VIRTUAL_KEYBOARD_GREEK_UPPERCASE = GUI_VIRTUAL_KEYBOARD_GREEK,
            
             GUI_VIRTUAL_KEYBOARD_BULGARIAN,
             GUI_VIRTUAL_KEYBOARD_BULGARIAN_UPPERCASE = GUI_VIRTUAL_KEYBOARD_BULGARIAN,

			 GUI_VIRTUAL_KEYBOARD_LAO,
			 GUI_VIRTUAL_KEYBOARD_LAO_UPPERCASE,
            
             GUI_VIRTUAL_KEYBOARD_DANISH,
             GUI_VIRTUAL_KEYBOARD_DANISH_UPPERCASE = GUI_VIRTUAL_KEYBOARD_DANISH,
            
             GUI_VIRTUAL_KEYBOARD_NORWEGIAN,
             GUI_VIRTUAL_KEYBOARD_NORWEGIAN_UPPERCASE = GUI_VIRTUAL_KEYBOARD_NORWEGIAN,
            
             GUI_VIRTUAL_KEYBOARD_SLOVAK,
             GUI_VIRTUAL_KEYBOARD_SLOVAK_UPPERCASE,
            
             GUI_VIRTUAL_KEYBOARD_HUNGARIAN,
             GUI_VIRTUAL_KEYBOARD_HUNGARIAN_UPPERCASE = GUI_VIRTUAL_KEYBOARD_HUNGARIAN,
            
             GUI_VIRTUAL_KEYBOARD_AFRIKAAN,
             GUI_VIRTUAL_KEYBOARD_AFRIKAAN_UPPERCASE = GUI_VIRTUAL_KEYBOARD_AFRIKAAN,

             GUI_VIRTUAL_KEYBOARD_FINNISH,
             GUI_VIRTUAL_KEYBOARD_FINNISH_UPPERCASE = GUI_VIRTUAL_KEYBOARD_FINNISH,
            
             GUI_VIRTUAL_KEYBOARD_SWEDISH,
             GUI_VIRTUAL_KEYBOARD_SWEDISH_UPPERCASE = GUI_VIRTUAL_KEYBOARD_SWEDISH,
            
             GUI_VIRTUAL_KEYBOARD_CROATIAN,
             GUI_VIRTUAL_KEYBOARD_CROATIAN_UPPERCASE = GUI_VIRTUAL_KEYBOARD_CROATIAN,
            
             GUI_VIRTUAL_KEYBOARD_SLOVENIAN,
             GUI_VIRTUAL_KEYBOARD_SLOVENIAN_UPPERCASE = GUI_VIRTUAL_KEYBOARD_SLOVENIAN,
            
             GUI_VIRTUAL_KEYBOARD_DUTCH,
             GUI_VIRTUAL_KEYBOARD_DUTCH_UPPERCASE = GUI_VIRTUAL_KEYBOARD_DUTCH,
            
             GUI_VIRTUAL_KEYBOARD_POLISH,
             GUI_VIRTUAL_KEYBOARD_POLISH_UPPERCASE = GUI_VIRTUAL_KEYBOARD_POLISH,
            
             GUI_VIRTUAL_KEYBOARD_ROMANIAN,
             GUI_VIRTUAL_KEYBOARD_ROMANIAN_UPPERCASE = GUI_VIRTUAL_KEYBOARD_ROMANIAN,

			GUI_VIRTUAL_KEYBOARD_MOLDOVAN,
			GUI_VIRTUAL_KEYBOARD_MOLDOVAN_UPPERCASE = GUI_VIRTUAL_KEYBOARD_MOLDOVAN,
			 
            
            GUI_VIRTUAL_KEYBOARD_UKRAINIAN,
            GUI_VIRTUAL_KEYBOARD_UKRAINIAN_UPPERCASE = GUI_VIRTUAL_KEYBOARD_UKRAINIAN,
            
            GUI_VIRTUAL_KEYBOARD_LATVIAN,
            GUI_VIRTUAL_KEYBOARD_LATVIAN_UPPERCASE = GUI_VIRTUAL_KEYBOARD_LATVIAN,
            
            GUI_VIRTUAL_KEYBOARD_ESTONIAN,
            GUI_VIRTUAL_KEYBOARD_ESTONIAN_UPPERCASE = GUI_VIRTUAL_KEYBOARD_ESTONIAN,
            
            GUI_VIRTUAL_KEYBOARD_ARMENIAN,
            GUI_VIRTUAL_KEYBOARD_ARMENIAN_UPPERCASE,
            
            GUI_VIRTUAL_KEYBOARD_LITHUANIAN,
            GUI_VIRTUAL_KEYBOARD_LITHUANIAN_UPPERCASE = GUI_VIRTUAL_KEYBOARD_LITHUANIAN,
                
            GUI_VIRTUAL_KEYBOARD_GEORGIAN,
            GUI_VIRTUAL_KEYBOARD_INTERNET, /* new function */
            GUI_VIRTUAL_KEYBOARD_INTERNET_UPPERCASE,
            GUI_VIRTUAL_KEYBOARD_NUM_AND_HALFWIDTH_SYMBOL, /* new function */
            GUI_VIRTUAL_KEYBOARD_INTERNET_SYM_PAGE_ONE,
            GUI_VIRTUAL_KEYBOARD_INTERNET_SYM_PAGE_TWO,
            GUI_VIRTUAL_KEYBOARD_INTERNET_SYM_PAGE_THREE,
            GUI_VIRTUAL_KEYBOARD_EN_DIALER,
            GUI_VIRTUAL_KEYBOARD_DIALER_DUAL_SIM = GUI_VIRTUAL_KEYBOARD_EN_DIALER,
            GUI_VIRTUAL_KEYBOARD_DIALER_SINGLE_SIM = GUI_VIRTUAL_KEYBOARD_EN_DIALER,
            GUI_VIRTUAL_KEYBOARD_DIALER_NORMAL_CALL = GUI_VIRTUAL_KEYBOARD_EN_DIALER,
            GUI_VIRTUAL_KEYBOARD_DIALER_EMERGENCY_CALL = GUI_VIRTUAL_KEYBOARD_EN_DIALER,
			GUI_VIRTUAL_KEYBOARD_MARATHI,
			GUI_VIRTUAL_KEYBOARD_MARATHI_UPPERCASE,
            GUI_VIRTUAL_KEYBOARD_MARATHI_CONS_MATRAS1 = GUI_VIRTUAL_KEYBOARD_MARATHI,
            GUI_VIRTUAL_KEYBOARD_MARATHI_CONS_MATRAS2 = GUI_VIRTUAL_KEYBOARD_MARATHI,
            GUI_VIRTUAL_KEYBOARD_MARATHI_CONS_INDEPEDENTVOWELS1 = GUI_VIRTUAL_KEYBOARD_MARATHI_UPPERCASE+1,
            GUI_VIRTUAL_KEYBOARD_MARATHI_CONS_INDEPEDENTVOWELS2,
            GUI_VIRTUAL_KEYBOARD_MARATHI_SYMBOLS,


        //bellowing is for VKv3
        /* English */
        GUI_VIRTUAL_KEYBOARD_EN = GUI_VIRTUAL_KEYBOARD_ENGLISH,
        GUI_VIRTUAL_KEYBOARD_EN_US = GUI_VIRTUAL_KEYBOARD_ENGLISH_UPPERCASE,
        GUI_VIRTUAL_KEYBOARD_EN_US_PHONE = GUI_VIRTUAL_KEYBOARD_PHONE_NUMBER,
        GUI_VIRTUAL_KEYBOARD_EN_US_SYMBOL = GUI_VIRTUAL_KEYBOARD_SYMBOL_FOR_NUM, 
        GUI_VIRTUAL_KEYBOARD_EN_PHONE = GUI_VIRTUAL_KEYBOARD_PHONE_NUMBER,

		/* Chinese */
        GUI_VIRTUAL_KEYBOARD_ZH_CN = GUI_VIRTUAL_KEYBOARD_PINYIN,
        GUI_VIRTUAL_KEYBOARD_ZH_TW = GUI_VIRTUAL_KEYBOARD_BOPOMO,
        GUI_VIRTUAL_KEYBOARD_ZH_STROKE = GUI_VIRTUAL_KEYBOARD_TR_STROKE,
        GUI_VIRTUAL_KEYBOARD_ZH_TW_STROKE = GUI_VIRTUAL_KEYBOARD_TR_STROKE,
        GUI_VIRTUAL_KEYBOARD_ZH_CN_STROKE = GUI_VIRTUAL_KEYBOARD_TR_STROKE,

		/* Thai*/
        GUI_VIRTUAL_KEYBOARD_TH = GUI_VIRTUAL_KEYBOARD_THAI,
        GUI_VIRTUAL_KEYBOARD_TH_TH = GUI_VIRTUAL_KEYBOARD_THAI,
        GUI_VIRTUAL_KEYBOARD_TH_SHIFT = GUI_VIRTUAL_KEYBOARD_THAI_LOWERCASE,
        GUI_VIRTUAL_KEYBOARD_TH_TH_SHIFT = GUI_VIRTUAL_KEYBOARD_THAI_LOWERCASE,
        
        /* Vietnamese */
        GUI_VIRTUAL_KEYBOARD_VI = GUI_VIRTUAL_KEYBOARD_VIETNAMESE,
        GUI_VIRTUAL_KEYBOARD_VI_VN = GUI_VIRTUAL_KEYBOARD_VIETNAMESE,
        
        /* Hindi */
        GUI_VIRTUAL_KEYBOARD_HI = GUI_VIRTUAL_KEYBOARD_HINDI,
        GUI_VIRTUAL_KEYBOARD_HI_IN = GUI_VIRTUAL_KEYBOARD_HINDI,
        GUI_VIRTUAL_KEYBOARD_HI_IN_SHIFT = GUI_VIRTUAL_KEYBOARD_HINDI_UPPERCASE,

		/* Assamese */
		GUI_VIRTUAL_KEYBOARD_AS = GUI_VIRTUAL_KEYBOARD_ASSAMESE,
		GUI_VIRTUAL_KEYBOARD_AS_IN = GUI_VIRTUAL_KEYBOARD_ASSAMESE,
		GUI_VIRTUAL_KEYBOARD_AS_IN_SHIFT = GUI_VIRTUAL_KEYBOARD_ASSAMESE_UPPERCASE,

		/*Kannada*/
		GUI_VIRTUAL_KEYBOARD_KN = GUI_VIRTUAL_KEYBOARD_KANNADA,
		GUI_VIRTUAL_KEYBOARD_KN_IN = GUI_VIRTUAL_KEYBOARD_KANNADA,
		GUI_VIRTUAL_KEYBOARD_KN_IN_SHIFT = GUI_VIRTUAL_KEYBOARD_KANNADA_UPPERCASE,

		/*Malyalam*/
		GUI_VIRTUAL_KEYBOARD_ML = GUI_VIRTUAL_KEYBOARD_MALAYALAM,
		GUI_VIRTUAL_KEYBOARD_ML_IN = GUI_VIRTUAL_KEYBOARD_MALAYALAM,
		GUI_VIRTUAL_KEYBOARD_ML_IN_SHIFT = GUI_VIRTUAL_KEYBOARD_MALAYALAM_UPPERCASE,

		/*Marathi*/

        GUI_VIRTUAL_KEYBOARD_MR = GUI_VIRTUAL_KEYBOARD_MARATHI,
        GUI_VIRTUAL_KEYBOARD_MR_IN = GUI_VIRTUAL_KEYBOARD_MARATHI,
        GUI_VIRTUAL_KEYBOARD_MR_IN_SHIFT = GUI_VIRTUAL_KEYBOARD_MARATHI_UPPERCASE,

		/*Bengali*/
        GUI_VIRTUAL_KEYBOARD_BE_IN = GUI_VIRTUAL_KEYBOARD_BENGALI,
        GUI_VIRTUAL_KEYBOARD_BE_IN_SHIFT = GUI_VIRTUAL_KEYBOARD_BENGALI_LOWERCASE,

		/*Punjabi*/
		
        GUI_VIRTUAL_KEYBOARD_PA = GUI_VIRTUAL_KEYBOARD_PUNJABI,
        GUI_VIRTUAL_KEYBOARD_PA_IN = GUI_VIRTUAL_KEYBOARD_PUNJABI,
        GUI_VIRTUAL_KEYBOARD_PA_IN_SHIFT = GUI_VIRTUAL_KEYBOARD_PUNJABI_UPPERCASE,

		/*Telugu*/

        GUI_VIRTUAL_KEYBOARD_TE = GUI_VIRTUAL_KEYBOARD_TELUGU,
        GUI_VIRTUAL_KEYBOARD_TE_IN = GUI_VIRTUAL_KEYBOARD_TELUGU,
        GUI_VIRTUAL_KEYBOARD_TE_IN_SHIFT = GUI_VIRTUAL_KEYBOARD_TELUGU_UPPERCASE,

		/*Tamil*/

        GUI_VIRTUAL_KEYBOARD_TA = GUI_VIRTUAL_KEYBOARD_TAMIL,
        GUI_VIRTUAL_KEYBOARD_TA_IN = GUI_VIRTUAL_KEYBOARD_TAMIL,
        GUI_VIRTUAL_KEYBOARD_TA_IN_SHIFT = GUI_VIRTUAL_KEYBOARD_TAMIL_UPPERCASE,

		/*Gujarati*/
		
        GUI_VIRTUAL_KEYBOARD_GU = GUI_VIRTUAL_KEYBOARD_GUJARATI,
        GUI_VIRTUAL_KEYBOARD_GU_IN = GUI_VIRTUAL_KEYBOARD_GUJARATI,
        GUI_VIRTUAL_KEYBOARD_GU_IN_SHIFT = GUI_VIRTUAL_KEYBOARD_GUJARATI_UPPERCASE,


		/*Myanmar*/
		GUI_VIRTUAL_KEYBOARD_MY = GUI_VIRTUAL_KEYBOARD_MYANMAR,
		GUI_VIRTUAL_KEYBOARD_MY_IN = GUI_VIRTUAL_KEYBOARD_MYANMAR,
		GUI_VIRTUAL_KEYBOARD_MY_IN_SHIFT = GUI_VIRTUAL_KEYBOARD_MYANMAR_UPPERCASE,

		/*Khmer*/
		GUI_VIRTUAL_KEYBOARD_KM = GUI_VIRTUAL_KEYBOARD_KHMER,
		GUI_VIRTUAL_KEYBOARD_KM_IN = GUI_VIRTUAL_KEYBOARD_KHMER,
		GUI_VIRTUAL_KEYBOARD_KM_IN_SHIFT = GUI_VIRTUAL_KEYBOARD_KHMER_UPPERCASE,

		/* arabic */
        GUI_VIRTUAL_KEYBOARD_AR = GUI_VIRTUAL_KEYBOARD_ARABIC,
        GUI_VIRTUAL_KEYBOARD_AR_SA = GUI_VIRTUAL_KEYBOARD_ARABIC,
        
		/*Persian*/
		GUI_VIRTUAL_KEYBOARD_PS = GUI_VIRTUAL_KEYBOARD_ARABIC,
		GUI_VIRTUAL_KEYBOARD_PS_IR = GUI_VIRTUAL_KEYBOARD_FARSI,

		/* Urdu */

        GUI_VIRTUAL_KEYBOARD_UR = GUI_VIRTUAL_KEYBOARD_URDU,
        GUI_VIRTUAL_KEYBOARD_UR_PK = GUI_VIRTUAL_KEYBOARD_URDU,
        GUI_VIRTUAL_KEYBOARD_UR_PK_SHIFT = GUI_VIRTUAL_KEYBOARD_URDU_UPPERCASE,

		/* Spanish */
        GUI_VIRTUAL_KEYBOARD_ES = GUI_VIRTUAL_KEYBOARD_SPANISH,
        GUI_VIRTUAL_KEYBOARD_ES_SA = GUI_VIRTUAL_KEYBOARD_SPANISH,
        GUI_VIRTUAL_KEYBOARD_ES_ES = GUI_VIRTUAL_KEYBOARD_SPANISH,

		/*Norwegian*/

        GUI_VIRTUAL_KEYBOARD_NB = GUI_VIRTUAL_KEYBOARD_NORWEGIAN,
        GUI_VIRTUAL_KEYBOARD_NB_NO = GUI_VIRTUAL_KEYBOARD_NORWEGIAN,

		/*Polish*/

        GUI_VIRTUAL_KEYBOARD_PL = GUI_VIRTUAL_KEYBOARD_POLISH,
        GUI_VIRTUAL_KEYBOARD_PL_PL = GUI_VIRTUAL_KEYBOARD_POLISH, 

		/*Igbo*/

        GUI_VIRTUAL_KEYBOARD_IG = GUI_VIRTUAL_KEYBOARD_IGBO,
        GUI_VIRTUAL_KEYBOARD_IG_NG = GUI_VIRTUAL_KEYBOARD_IGBO, 

		/*Yoruba*/

        GUI_VIRTUAL_KEYBOARD_YO = GUI_VIRTUAL_KEYBOARD_YORUBA,
        GUI_VIRTUAL_KEYBOARD_YO_YO = GUI_VIRTUAL_KEYBOARD_YORUBA, 

		/*Hausa*/

        GUI_VIRTUAL_KEYBOARD_HA = GUI_VIRTUAL_KEYBOARD_HAUSA,
        GUI_VIRTUAL_KEYBOARD_HA_HA = GUI_VIRTUAL_KEYBOARD_HAUSA,

		/* Franch */
        GUI_VIRTUAL_KEYBOARD_FR = GUI_VIRTUAL_KEYBOARD_FRENCH,
        GUI_VIRTUAL_KEYBOARD_FR_FR = GUI_VIRTUAL_KEYBOARD_FRENCH,
		GUI_VIRTUAL_KEYBOARD_FR_CA = GUI_VIRTUAL_KEYBOARD_FRENCH,
		
		/* German */
        GUI_VIRTUAL_KEYBOARD_DE = GUI_VIRTUAL_KEYBOARD_GERMAN,
		GUI_VIRTUAL_KEYBOARD_DE_DE = GUI_VIRTUAL_KEYBOARD_GERMAN,
		
		/* Itanian */
        GUI_VIRTUAL_KEYBOARD_IT = GUI_VIRTUAL_KEYBOARD_ITALIAN,
        GUI_VIRTUAL_KEYBOARD_IT_IT = GUI_VIRTUAL_KEYBOARD_ITALIAN,

		/* Russian */
        GUI_VIRTUAL_KEYBOARD_RU = GUI_VIRTUAL_KEYBOARD_RUSSIAN,
        GUI_VIRTUAL_KEYBOARD_RU_RU = GUI_VIRTUAL_KEYBOARD_RUSSIAN,

		/*Ukranian*/
        GUI_VIRTUAL_KEYBOARD_UK = GUI_VIRTUAL_KEYBOARD_UKRAINIAN,
        GUI_VIRTUAL_KEYBOARD_UK_UA = GUI_VIRTUAL_KEYBOARD_UKRAINIAN,

		/* Turkish */
        GUI_VIRTUAL_KEYBOARD_TR = GUI_VIRTUAL_KEYBOARD_TURKISH,
        GUI_VIRTUAL_KEYBOARD_TR_TR = GUI_VIRTUAL_KEYBOARD_TURKISH,

		/* Portuguese */
        GUI_VIRTUAL_KEYBOARD_PT = GUI_VIRTUAL_KEYBOARD_PORTUGUESE,
        GUI_VIRTUAL_KEYBOARD_PT_PT = GUI_VIRTUAL_KEYBOARD_PORTUGUESE,
        GUI_VIRTUAL_KEYBOARD_PT_BZ = GUI_VIRTUAL_KEYBOARD_PORTUGUESE,

		/*Azerbaijani*/
		GUI_VIRTUAL_KEYBOARD_AZ = GUI_VIRTUAL_KEYBOARD_AZERBAIJANI,
		GUI_VIRTUAL_KEYBOARD_AZ_AZ = GUI_VIRTUAL_KEYBOARD_AZERBAIJANI,

		/*Galician*/
		GUI_VIRTUAL_KEYBOARD_GL = GUI_VIRTUAL_KEYBOARD_GALICIAN,
		GUI_VIRTUAL_KEYBOARD_GL_ES = GUI_VIRTUAL_KEYBOARD_GALICIAN,

		/*Basque*/

		GUI_VIRTUAL_KEYBOARD_EU = GUI_VIRTUAL_KEYBOARD_BASQUE,
		GUI_VIRTUAL_KEYBOARD_EU_ES = GUI_VIRTUAL_KEYBOARD_BASQUE,

		/*Bulgarian*/
		GUI_VIRTUAL_KEYBOARD_BG = GUI_VIRTUAL_KEYBOARD_BULGARIAN,
		GUI_VIRTUAL_KEYBOARD_BG_BG = GUI_VIRTUAL_KEYBOARD_BULGARIAN,

		/*Finnish*/

		GUI_VIRTUAL_KEYBOARD_FI = GUI_VIRTUAL_KEYBOARD_FINNISH,
		GUI_VIRTUAL_KEYBOARD_FI_FI = GUI_VIRTUAL_KEYBOARD_FINNISH,

		/*Lao*/

		GUI_VIRTUAL_KEYBOARD_LO = GUI_VIRTUAL_KEYBOARD_LAO,
		GUI_VIRTUAL_KEYBOARD_LO_IN = GUI_VIRTUAL_KEYBOARD_LAO,
		GUI_VIRTUAL_KEYBOARD_LO_IN_SHIFT = GUI_VIRTUAL_KEYBOARD_LAO_UPPERCASE,

		/*Estonian*/

		GUI_VIRTUAL_KEYBOARD_ET = GUI_VIRTUAL_KEYBOARD_ESTONIAN,
		GUI_VIRTUAL_KEYBOARD_ET_EE = GUI_VIRTUAL_KEYBOARD_ESTONIAN,

		/*Georgian*/
		GUI_VIRTUAL_KEYBOARD_KA_GE = GUI_VIRTUAL_KEYBOARD_GEORGIAN,

		/*Serbian*/
		GUI_VIRTUAL_KEYBOARD_SR = GUI_VIRTUAL_KEYBOARD_SERBIAN,
		GUI_VIRTUAL_KEYBOARD_SR_SR = GUI_VIRTUAL_KEYBOARD_SERBIAN,
		
		/*Tagalog*/

		GUI_VIRTUAL_KEYBOARD_TL = GUI_VIRTUAL_KEYBOARD_TAGALOG,
		GUI_VIRTUAL_KEYBOARD_TL_TL = GUI_VIRTUAL_KEYBOARD_TAGALOG,

		/*Icelandic*/

		GUI_VIRTUAL_KEYBOARD_IS = GUI_VIRTUAL_KEYBOARD_ICELANDIC,
		GUI_VIRTUAL_KEYBOARD_IS_IS = GUI_VIRTUAL_KEYBOARD_ICELANDIC,

		/*Latvian*/

		GUI_VIRTUAL_KEYBOARD_LV = GUI_VIRTUAL_KEYBOARD_LATVIAN,
		GUI_VIRTUAL_KEYBOARD_LV_LV = GUI_VIRTUAL_KEYBOARD_LATVIAN,

		/*Armenian*/
		
		GUI_VIRTUAL_KEYBOARD_HY = GUI_VIRTUAL_KEYBOARD_ARMENIAN,
		GUI_VIRTUAL_KEYBOARD_HY_AM = GUI_VIRTUAL_KEYBOARD_ARMENIAN,
		GUI_VIRTUAL_KEYBOARD_HY_AM_SHIFT = GUI_VIRTUAL_KEYBOARD_ARMENIAN_UPPERCASE,

		/* Romanian */
        //GUI_VIRTUAL_KEYBOARD_RO_RO = GUI_VIRTUAL_KEYBOARD_DIALER_SINGLE_SIM + 1,
        GUI_VIRTUAL_KEYBOARD_RO_RO = GUI_VIRTUAL_KEYBOARD_ROMANIAN,

		/*MOLDOVAN*/
		GUI_VIRTUAL_KEYBOARD_MO = GUI_VIRTUAL_KEYBOARD_MOLDOVAN,
		GUI_VIRTUAL_KEYBOARD_MO_MD = GUI_VIRTUAL_KEYBOARD_MOLDOVAN,

		/*Catalan*/
		
		GUI_VIRTUAL_KEYBOARD_CA = GUI_VIRTUAL_KEYBOARD_CATALAN,
		GUI_VIRTUAL_KEYBOARD_CA_CA = GUI_VIRTUAL_KEYBOARD_CATALAN,

		/*Slovenian*/

		GUI_VIRTUAL_KEYBOARD_SL = GUI_VIRTUAL_KEYBOARD_SLOVENIAN,
		GUI_VIRTUAL_KEYBOARD_SL_SI = GUI_VIRTUAL_KEYBOARD_SLOVENIAN,

		
		/*Lithunian*/

		GUI_VIRTUAL_KEYBOARD_LT = GUI_VIRTUAL_KEYBOARD_LITHUANIAN,
		GUI_VIRTUAL_KEYBOARD_LT_LT = GUI_VIRTUAL_KEYBOARD_LITHUANIAN,


		/* Indonesian */
        GUI_VIRTUAL_KEYBOARD_ID_ID = GUI_VIRTUAL_KEYBOARD_INDONESIAN,

		/* Malay */
        GUI_VIRTUAL_KEYBOARD_MS_MY = GUI_VIRTUAL_KEYBOARD_MALAY,

		/* Hungarian */
        GUI_VIRTUAL_KEYBOARD_HU_HU = GUI_VIRTUAL_KEYBOARD_HUNGARIAN,
        
		/*Afrikaan*/
        GUI_VIRTUAL_KEYBOARD_AF_NA = GUI_VIRTUAL_KEYBOARD_AFRIKAAN ,

		/* Czech */
		GUI_VIRTUAL_KEYBOARD_CS_CZ = GUI_VIRTUAL_KEYBOARD_CZECH,
		
		/* Greek */
		GUI_VIRTUAL_KEYBOARD_EL_GR = GUI_VIRTUAL_KEYBOARD_GREEK,
		
		/* Dutch */
		GUI_VIRTUAL_KEYBOARD_NL_NL = GUI_VIRTUAL_KEYBOARD_DUTCH,

		/*Hebrew*/
		GUI_VIRTUAL_KEYBOARD_HE_IL  = GUI_VIRTUAL_KEYBOARD_HEBREW,

		/*filipino*/
		GUI_VIRTUAL_KEYBOARD_FIL = GUI_VIRTUAL_KEYBOARD_FILIPINO,
		GUI_VIRTUAL_KEYBOARD_FIL_PH = GUI_VIRTUAL_KEYBOARD_FILIPINO,

		/*Swedish*/
		GUI_VIRTUAL_KEYBOARD_SV = GUI_VIRTUAL_KEYBOARD_SWEDISH,
		GUI_VIRTUAL_KEYBOARD_SV_SE = GUI_VIRTUAL_KEYBOARD_SWEDISH,

		/*Danish*/
		GUI_VIRTUAL_KEYBOARD_DA = GUI_VIRTUAL_KEYBOARD_DANISH,
		GUI_VIRTUAL_KEYBOARD_DA_DK = GUI_VIRTUAL_KEYBOARD_DANISH,

		/*Croation*/
		GUI_VIRTUAL_KEYBOARD_HR = GUI_VIRTUAL_KEYBOARD_CROATIAN,
		GUI_VIRTUAL_KEYBOARD_HR_HR = GUI_VIRTUAL_KEYBOARD_CROATIAN,

        GUI_VIRTUAL_KEYBOARD_SYMBOL_PAGE_BASE = 210,
        GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_1 = GUI_VIRTUAL_KEYBOARD_SYMBOL_PAGE_BASE + 0,
        GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_2,
        GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_3,
	GUI_VIRTUAL_KEYBOARD_EN_PHONE_SYMBOL,
	GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_CUSTOM_1,
	GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_CUSTOM_2,
	GUI_VIRTUAL_KEYBOARD_EN_123SYM_1,
	GUI_VIRTUAL_KEYBOARD_EN_123SYM_2,
	    
            
        GUI_VIRTUAL_KEYBOARD_AR_SA_SYMBOL_1 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_1,
        GUI_VIRTUAL_KEYBOARD_AR_SA_SYMBOL_2 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_2,
        GUI_VIRTUAL_KEYBOARD_AR_SA_SYMBOL_3 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_3,
        
        GUI_VIRTUAL_KEYBOARD_EN_US_SYMBOL_1 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_1,
        GUI_VIRTUAL_KEYBOARD_EN_US_SYMBOL_2 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_2,
        GUI_VIRTUAL_KEYBOARD_EN_US_SYMBOL_3 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_3,

        GUI_VIRTUAL_KEYBOARD_ZH_SYMBOL_1 = GUI_VIRTUAL_KEYBOARD_EN_123SYM_2 + 1,
        GUI_VIRTUAL_KEYBOARD_ZH_SYMBOL_2,
        GUI_VIRTUAL_KEYBOARD_ZH_SYMBOL_3,

    	GUI_VIRTUAL_KEYBOARD_ZH_CN_SYMBOL_1 = GUI_VIRTUAL_KEYBOARD_ZH_SYMBOL_1,
    	GUI_VIRTUAL_KEYBOARD_ZH_CN_SYMBOL_2 = GUI_VIRTUAL_KEYBOARD_ZH_SYMBOL_2,
    	GUI_VIRTUAL_KEYBOARD_ZH_CN_SYMBOL_3 = GUI_VIRTUAL_KEYBOARD_ZH_SYMBOL_3,
        
    	GUI_VIRTUAL_KEYBOARD_ZH_TW_SYMBOL_1 = GUI_VIRTUAL_KEYBOARD_ZH_SYMBOL_1,
    	GUI_VIRTUAL_KEYBOARD_ZH_TW_SYMBOL_2 = GUI_VIRTUAL_KEYBOARD_ZH_SYMBOL_2,
    	GUI_VIRTUAL_KEYBOARD_ZH_TW_SYMBOL_3 = GUI_VIRTUAL_KEYBOARD_ZH_SYMBOL_3,
	
        
        GUI_VIRTUAL_KEYBOARD_PT_PT_SYMBOL_1 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_1,
        GUI_VIRTUAL_KEYBOARD_PT_PT_SYMBOL_2 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_2,
        GUI_VIRTUAL_KEYBOARD_PT_PT_SYMBOL_3 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_3,
        
        GUI_VIRTUAL_KEYBOARD_PT_BZ_SYMBOL_1 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_1,
        GUI_VIRTUAL_KEYBOARD_PT_BZ_SYMBOL_2 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_2,
        GUI_VIRTUAL_KEYBOARD_PT_BZ_SYMBOL_3 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_3,
        
        GUI_VIRTUAL_KEYBOARD_ID_ID_SYMBOL_1 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_1,
        GUI_VIRTUAL_KEYBOARD_ID_ID_SYMBOL_2 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_2,
        GUI_VIRTUAL_KEYBOARD_ID_ID_SYMBOL_3 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_3,
        GUI_VIRTUAL_KEYBOARD_ID_ID_PHONE = GUI_VIRTUAL_KEYBOARD_EN_PHONE,
        
        GUI_VIRTUAL_KEYBOARD_ES_ES_SYMBOL_1 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_1,
        GUI_VIRTUAL_KEYBOARD_ES_ES_SYMBOL_2 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_2,
        GUI_VIRTUAL_KEYBOARD_ES_ES_SYMBOL_3 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_3,
        
        GUI_VIRTUAL_KEYBOARD_ES_SA_SYMBOL_1 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_1,
        GUI_VIRTUAL_KEYBOARD_ES_SA_SYMBOL_2 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_2,
        GUI_VIRTUAL_KEYBOARD_ES_SA_SYMBOL_3 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_3,
        
        GUI_VIRTUAL_KEYBOARD_VI_VN_SYMBOL_1 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_1,
        GUI_VIRTUAL_KEYBOARD_VI_VN_SYMBOL_2 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_2,
        GUI_VIRTUAL_KEYBOARD_VI_VN_SYMBOL_3 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_3,
          
        GUI_VIRTUAL_KEYBOARD_RU_RU_SYMBOL_1 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_1,
        GUI_VIRTUAL_KEYBOARD_RU_RU_SYMBOL_2 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_2,
        GUI_VIRTUAL_KEYBOARD_RU_RU_SYMBOL_3 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_3,
        
        GUI_VIRTUAL_KEYBOARD_TH_TH_SYMBOL_1 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_1,
        GUI_VIRTUAL_KEYBOARD_TH_TH_SYMBOL_2 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_2,
        GUI_VIRTUAL_KEYBOARD_TH_TH_SYMBOL_3 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_3,
        
        GUI_VIRTUAL_KEYBOARD_HI_IN_SYMBOL_1 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_1,
        GUI_VIRTUAL_KEYBOARD_HI_IN_SYMBOL_2 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_2,
        GUI_VIRTUAL_KEYBOARD_HI_IN_SYMBOL_3 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_3,
        
        GUI_VIRTUAL_KEYBOARD_TR_TR_SYMBOL_1 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_1,
        GUI_VIRTUAL_KEYBOARD_TR_TR_SYMBOL_2 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_2,
        GUI_VIRTUAL_KEYBOARD_TR_TR_SYMBOL_3 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_3,

        GUI_VIRTUAL_KEYBOARD_MS_MY_SYMBOL_1 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_1,
        GUI_VIRTUAL_KEYBOARD_MS_MY_SYMBOL_2 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_2,
        GUI_VIRTUAL_KEYBOARD_MS_MY_SYMBOL_3 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_3,
        GUI_VIRTUAL_KEYBOARD_MS_MY_PHONE = GUI_VIRTUAL_KEYBOARD_EN_PHONE,
        
        GUI_VIRTUAL_KEYBOARD_BE_IN_SYMBOL_1 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_1,
        GUI_VIRTUAL_KEYBOARD_BE_IN_SYMBOL_2 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_2,
        GUI_VIRTUAL_KEYBOARD_BE_IN_SYMBOL_3 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_3,
        GUI_VIRTUAL_KEYBOARD_BE_IN_PHONE = GUI_VIRTUAL_KEYBOARD_EN_PHONE,
        
        GUI_VIRTUAL_KEYBOARD_RO_RO_SYMBOL_1 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_1,
        GUI_VIRTUAL_KEYBOARD_RO_RO_SYMBOL_2 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_2,
        GUI_VIRTUAL_KEYBOARD_RO_RO_SYMBOL_3 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_3,
        GUI_VIRTUAL_KEYBOARD_RO_RO_PHONE = GUI_VIRTUAL_KEYBOARD_EN_PHONE,
        
        
        GUI_VIRTUAL_KEYBOARD_FR_CA_SYMBOL_1 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_1,
        GUI_VIRTUAL_KEYBOARD_FR_CA_SYMBOL_2 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_2,
        GUI_VIRTUAL_KEYBOARD_FR_CA_SYMBOL_3 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_3,
        
        GUI_VIRTUAL_KEYBOARD_DE_DE_SYMBOL_1 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_1,
        GUI_VIRTUAL_KEYBOARD_DE_DE_SYMBOL_2 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_2,
        GUI_VIRTUAL_KEYBOARD_DE_DE_SYMBOL_3 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_3,

        GUI_VIRTUAL_KEYBOARD_IT_IT_SYMBOL_1 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_1,
        GUI_VIRTUAL_KEYBOARD_IT_IT_SYMBOL_2 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_2,
        GUI_VIRTUAL_KEYBOARD_IT_IT_SYMBOL_3 = GUI_VIRTUAL_KEYBOARD_EN_SYMBOL_3,
    
	

        GUI_VIRTUAL_KEYBOARD_MAX_LANG = 255
    } gui_virtual_keyboard_language_enum;

typedef enum
    {
        GUI_VKBD_PEN_NONE = 0x00010000,

        GUI_VKBD_PEN_DISPLAY_AREA,
        GUI_VKBD_PEN_CHAR_I,
        GUI_VKBD_PEN_HIDE,
        GUI_VKBD_PEN_SHOW,
        GUI_VKBD_PEN_CAPSLOCK,
        GUI_VKBD_PEN_SPACE,
        GUI_VKBD_PEN_BAKSPACE,
        GUI_VKBD_PEN_SYMBPICKER,
        GUI_VKBD_PEN_BRACKET,
        GUI_VKBD_PEN_NEWLINE,
        GUI_VKBD_PEN_EUROSYMB,
        GUI_VKBD_PEN_DEAD_KEY,
        GUI_VKBD_PEN_DISPLAY_CALLBACK,
        GUI_VKBD_PEN_NUM_AND_SYM, /* new function */
        GUI_VKBD_PEN_CHANGE_MODE, /* new function */
        GUI_VKBD_PEN_HANDWRITING, /* new function */
        GUI_VKBD_PEN_DOT_COM, /* new function */
        GUI_VKBD_PEN_DOT_ORG, /* new function */
        GUI_VKBD_PEN_DOT_NET, /* new function */
        GUI_VKBD_PEN_DOT_GOV, /* new function */
        GUI_VKBD_PEN_DOT_EDU, /* new function */
        GUI_VKBD_PEN_DOT_MIL, /* new function */
        GUI_VKBD_PEN_BACK_TO_LANG, /* new function */
        GUI_VKBD_PEN_ZI_STROKE_1, /* new function */
        GUI_VKBD_PEN_ZI_STROKE_2, /* new function */
        GUI_VKBD_PEN_ZI_STROKE_3, /* new function */
        GUI_VKBD_PEN_ZI_STROKE_4, /* new function */
        GUI_VKBD_PEN_ZI_STROKE_5, /* new function */
        GUI_VKBD_PEN_ZI_STROKE_6, /* new function */
        GUI_VKBD_PEN_ZI_STROKE_7, /* new function */
        GUI_VKBD_PEN_ZI_STROKE_8, /* new function */
        GUI_VKBD_PEN_ZI_STROKE_9, /* new function */
        GUI_VKBD_PEN_ZI_STROKE_DEPART, /* new function */    
        GUI_VKBD_PEN_ALPHANUMERIC_KEY_0, /* new function for alphanumeric keypad */
        GUI_VKBD_PEN_ALPHANUMERIC_KEY_1, /* new function for alphanumeric keypad */
        GUI_VKBD_PEN_ALPHANUMERIC_KEY_2, /* new function for alphanumeric keypad */
        GUI_VKBD_PEN_ALPHANUMERIC_KEY_3, /* new function for alphanumeric keypad */
        GUI_VKBD_PEN_ALPHANUMERIC_KEY_4, /* new function for alphanumeric keypad */
        GUI_VKBD_PEN_ALPHANUMERIC_KEY_5, /* new function for alphanumeric keypad */
        GUI_VKBD_PEN_ALPHANUMERIC_KEY_6, /* new function for alphanumeric keypad */
        GUI_VKBD_PEN_ALPHANUMERIC_KEY_7, /* new function for alphanumeric keypad */
        GUI_VKBD_PEN_ALPHANUMERIC_KEY_8, /* new function for alphanumeric keypad */
        GUI_VKBD_PEN_ALPHANUMERIC_KEY_9, /* new function for alphanumeric keypad */
        GUI_VKBD_PEN_ALPHANUMERIC_KEY_STAR, /* new function for alphanumeric keypad */
        GUI_VKBD_PEN_ALPHANUMERIC_KEY_POUND, /* new function for alphanumeric keypad */
        GUI_VKBD_PEN_ALPHANUMERIC_KEY_DELETE, /* new function for alphanumeric keypad */
        GUI_VKBD_PEN_ALPHANUMERIC_KEY_CAPS_LOCK, /* new function for alphanumeric keypad */
        GUI_VKBD_PEN_ALPHANUMERIC_KEY_NUM, /* new function for alphanumeric keypad */
        GUI_VKBD_PEN_ALPHANUMERIC_KEY_HANDWRITING, /* new function for alphanumeric keypad */
        GUI_VKBD_PEN_ALPHANUMERIC_KEY_HIDE, /* new function for alphanumeric keypad */
        GUI_VKBD_PEN_ALPHANUMERIC_KEY_SPACE,  /* new function for alphanumeric keypad */
        GUI_VKBD_PEN_ALPHANUMERIC_KEY_BACK_TO_LANG,  /* new function for alphanumeric keypad */
        GUI_VKBD_PEN_ALPHANUMERIC_SYM_PREV_PAGE,  /* new function for alphanumeric keypad */
        GUI_VKBD_PEN_ALPHANUMERIC_SYM_NEXT_PAGE,   /* new function for alphanumeric keypad */
        GUI_VKBD_PEN_ALPHANUMERIC_SYM_LOCK,   /* new function for alphanumeric keypad */
        GUI_VKBD_PEN_ALPHANUMERIC_SYMBPICKER,   /* new function for alphanumeric keypad */
        GUI_VKBD_PEN_ALPHANUMERIC_CHANGE_MODE,   /* new function for alphanumeric keypad */
        GUI_VKBD_PEN_ALPHANUMERIC_NEWLINE,   /* new function for alphanumeric keypad */    
        GUI_VKBD_PEN_ALPHANUMERIC_EMOTION_1,   /* new function for alphanumeric keypad */    
        GUI_VKBD_PEN_ALPHANUMERIC_EMOTION_2,   /* new function for alphanumeric keypad */    
        GUI_VKBD_PEN_ALPHANUMERIC_EMOTION_3,   /* new function for alphanumeric keypad */    
        GUI_VKBD_PEN_ALPHANUMERIC_EMOTION_4,   /* new function for alphanumeric keypad */    
        GUI_VKBD_PEN_ALPHANUMERIC_EMOTION_5,   /* new function for alphanumeric keypad */    
        GUI_VKBD_PEN_ALPHANUMERIC_EMOTION_6,   /* new function for alphanumeric keypad */    
        GUI_VKBD_PEN_ALPHANUMERIC_EMOTION_7,   /* new function for alphanumeric keypad */    
        GUI_VKBD_PEN_ALPHANUMERIC_EMOTION_8,   /* new function for alphanumeric keypad */    
        GUI_VKBD_PEN_ALPHANUMERIC_EMOTION_9,   /* new function for alphanumeric keypad */    
        GUI_VKBD_PEN_ALPHANUMERIC_EMOTION_10,   /* new function for alphanumeric keypad */    
        GUI_VKBD_PEN_ALPHANUMERIC_EMOTION_11,   /* new function for alphanumeric keypad */    
        GUI_VKBD_PEN_ALPHANUMERIC_DOT_COM, /* new function */
        GUI_VKBD_PEN_INDIC_SLIDE1_CAPSLOCK_ON,
        GUI_VKBD_PEN_INDIC_SLIDE1_CAPSLOCK_OFF,
        GUI_VKBD_PEN_INDIC_SLIDE2_CAPSLOCK_ON,
        GUI_VKBD_PEN_INDIC_SLIDE2_CAPSLOCK_OFF,
        GUI_VKBD_PEN_INDIC_SYMBPICKER,
        GUI_VKBD_PEN_INDIC_SLIDE1,
        GUI_VKBD_PEN_INDIC_SLIDE2,
        GUI_VKBD_PEN_ZHUYIN_B_P, /* for Zhuyin B & P */
        GUI_VKBD_PEN_ZHUYIN_M_F, /* for Zhuyin M & F */
        GUI_VKBD_PEN_ZHUYIN_D_T, /* for Zhuyin D & T */
        GUI_VKBD_PEN_ZHUYIN_N_L, /* for Zhuyin N & L */
        GUI_VKBD_PEN_ZHUYIN_G_J, /* for Zhuyin G & J */
        GUI_VKBD_PEN_ZHUYIN_K_Q, /* for Zhuyin K & Q */
        GUI_VKBD_PEN_ZHUYIN_H_X, /* for Zhuyin H & X */
        GUI_VKBD_PEN_ZHUYIN_ZH_CH, /* for Zhuyin ZH & CH */
        GUI_VKBD_PEN_ZHUYIN_SH, /* for Zhuyin SH */
        GUI_VKBD_PEN_ZHUYIN_R, /* for Zhuyin R */
        GUI_VKBD_PEN_ZHUYIN_Z, /* for Zhuyin Z */
        GUI_VKBD_PEN_ZHUYIN_C, /* for Zhuyin C */
        GUI_VKBD_PEN_ZHUYIN_S, /* for Zhuyin S */
        GUI_VKBD_PEN_ZHUYIN_I, /* for Zhuyin I */
        GUI_VKBD_PEN_ZHUYIN_U, /* for Zhuyin U */
        GUI_VKBD_PEN_ZHUYIN_IU, /* for Zhuyin IU */    
        GUI_VKBD_PEN_ZHUYIN_A_O, /* for Zhuyin A & O */
        GUI_VKBD_PEN_ZHUYIN_E, /* for Zhuyin E */
        GUI_VKBD_PEN_ZHUYIN_EH, /* for Zhuyin EH */
        GUI_VKBD_PEN_ZHUYIN_AI_EI, /* for Zhuyin AI & EI */
        GUI_VKBD_PEN_ZHUYIN_AU, /* for Zhuyin AU */
        GUI_VKBD_PEN_ZHUYIN_OU, /* for Zhuyin OU */
        GUI_VKBD_PEN_ZHUYIN_AN_EN, /* for Zhuyin AI & EI */
        GUI_VKBD_PEN_ZHUYIN_ANG, /* for Zhuyin AU */
        GUI_VKBD_PEN_ZHUYIN_ENG, /* for Zhuyin OU */
        GUI_VKBD_PEN_ZHUYIN_ER, /* for Zhuyin ER */
        GUI_VKBD_PEN_ZHUYIN_TONE, /* for Zhuyin tone */
        GUI_VKBD_PEN_STROKE_1, /* new function */
        GUI_VKBD_PEN_STROKE_2, /* new function */
        GUI_VKBD_PEN_STROKE_3, /* new function */
        GUI_VKBD_PEN_STROKE_4, /* new function */
        GUI_VKBD_PEN_STROKE_5, /* new function */
        GUI_VKBD_PEN_STROKE_DEPART, /* new function */   
        GUI_VKBD_PEN_ZHUYIN_TONE_2_5,
        GUI_VKBD_PEN_ZHUYIN_TONE_3,
        GUI_VKBD_PEN_ZHUYIN_TONE_4,
        GUI_VKBD_PEN_ZHUYIN_COMMA_DOT = GUI_VKBD_PEN_ZHUYIN_TONE_4 + 2,
        /* Dialer Events for vk */
        GUI_VKBD_PEN_ALPHANUMERIC_DIALER_KEY_0, 
        GUI_VKBD_PEN_ALPHANUMERIC_DIALER_KEY_1,  
        GUI_VKBD_PEN_ALPHANUMERIC_DIALER_KEY_2,  
        GUI_VKBD_PEN_ALPHANUMERIC_DIALER_KEY_3,  
        GUI_VKBD_PEN_ALPHANUMERIC_DIALER_KEY_4,  
        GUI_VKBD_PEN_ALPHANUMERIC_DIALER_KEY_5,  
        GUI_VKBD_PEN_ALPHANUMERIC_DIALER_KEY_6,  
        GUI_VKBD_PEN_ALPHANUMERIC_DIALER_KEY_7,  
        GUI_VKBD_PEN_ALPHANUMERIC_DIALER_KEY_8,  
        GUI_VKBD_PEN_ALPHANUMERIC_DIALER_KEY_9,  
        GUI_VKBD_PEN_ALPHANUMERIC_DIALER_KEY_STAR,
        GUI_VKBD_PEN_ALPHANUMERIC_DIALER_KEY_POUND,
        GUI_VKBD_PEN_ALPHANUMERIC_KEY_VIDEO_CALL,
        GUI_VKBD_PEN_ALPHANUMERIC_DIALER_KEY_CALL1,
        GUI_VKBD_PEN_ALPHANUMERIC_DIALER_KEY_CALL2,
		GUI_VKBD_PEN_ALPHANUMERIC_DIALER_KEY_N_CALL,
		GUI_VKBD_PEN_ALPHANUMERIC_DIALER_KEY_E_CALL,

//for bihua
        GUI_VKBD_PEN_V3_KEY_BIHUA_1 = GUI_VKBD_PEN_STROKE_1,
        GUI_VKBD_PEN_V3_KEY_BIHUA_2 = GUI_VKBD_PEN_STROKE_2,
        GUI_VKBD_PEN_V3_KEY_BIHUA_3 = GUI_VKBD_PEN_STROKE_3,
        GUI_VKBD_PEN_V3_KEY_BIHUA_4 = GUI_VKBD_PEN_STROKE_4,
        GUI_VKBD_PEN_V3_KEY_BIHUA_5 = GUI_VKBD_PEN_STROKE_5,
        GUI_VKBD_PEN_V3_KEY_BIHUA_ALL = GUI_VKBD_PEN_STROKE_DEPART,


//event for vkv3
        GUI_VKBD_PEN_V3_CHAR_I_CHAR = GUI_VKBD_PEN_CHAR_I, //WHEN KEYCODE IS UNICODE, ON OTHER SIDE, KEY CODE IS LESS THAN OX00010000
        GUI_VKBD_PEN_V3_HIDE = GUI_VKBD_PEN_HIDE,  //KEY CODE = -5
        GUI_VKBD_PEN_V3_SHIFT = GUI_VKBD_PEN_CAPSLOCK, //KEY CODE = -2
        GUI_VKBD_PEN_V3_SPACE = GUI_VKBD_PEN_SPACE,     //KEY CODE = 32
        GUI_VKBD_PEN_V3_DELETE = GUI_VKBD_PEN_BAKSPACE,    //KEY CODE = 8
        GUI_VKBD_PEN_V3_SYMBPICKER = GUI_VKBD_PEN_SYMBPICKER,    //KEY CODE = -1
        GUI_VKBD_PEN_V3_ENTER = GUI_VKBD_PEN_NEWLINE,     //KEY CODE = 13
        GUI_VKBD_PEN_V3_DOT_COM = GUI_VKBD_PEN_DOT_COM,   //KEY CODE = -11
        GUI_VKBD_PEN_V3_CHANGE_MODE = GUI_VKBD_PEN_CHANGE_MODE,   //KEY CODE = -3

// for zhuyin
        GUI_VKBD_PEN_V3_KEY_ZHUNYIN_TONE_1 = GUI_VKBD_PEN_ZHUYIN_TONE,
        GUI_VKBD_PEN_V3_KEY_ZHUNYIN_TONE_2 = GUI_VKBD_PEN_ZHUYIN_TONE_2_5,
        GUI_VKBD_PEN_V3_KEY_ZHUNYIN_TONE_3 = GUI_VKBD_PEN_ZHUYIN_TONE_3,
        GUI_VKBD_PEN_V3_KEY_ZHUNYIN_TONE_4 = GUI_VKBD_PEN_ZHUYIN_TONE_4,
        GUI_VKBD_PEN_V3_KEY_ZHUNYIN_TONE_5 = GUI_VKBD_PEN_ZHUYIN_TONE_4 + 1,

        GUI_VKBD_PEN_V3_KEY_BPMF_0 = 0x00100000,  ///TODO:  how to mapping those event on 0~9 key
        GUI_VKBD_PEN_V3_KEY_BPMF_1,
        GUI_VKBD_PEN_V3_KEY_BPMF_2,
        GUI_VKBD_PEN_V3_KEY_BPMF_3,
        GUI_VKBD_PEN_V3_KEY_BPMF_4,
        GUI_VKBD_PEN_V3_KEY_BPMF_5,
        GUI_VKBD_PEN_V3_KEY_BPMF_6,
        GUI_VKBD_PEN_V3_KEY_BPMF_7,
        GUI_VKBD_PEN_V3_KEY_BPMF_8,
        GUI_VKBD_PEN_V3_KEY_BPMF_9,
        GUI_VKBD_PEN_V3_KEY_BPMF_10,

        GUI_VKBD_PEN_V3_CHANGE_MODE_BETWEEN_SMART_MULTITAP,
        GUI_VKBD_PEN_V3_CHAR_I_STRING,   //WHEN KEY CODE EQUAL TO ZERO
        GUI_VKBD_PEN_V3_SYMBOLE_SWITCH,    //KEY CODE = -6
        GUI_VKBD_PEN_V3_SYMBOL_FULL_HALF,  //KEY CODE = -7
        GUI_VKBD_PEN_V3_SYMBOL_PAGE1,  //KEY CODE = -8
        GUI_VKBD_PEN_V3_SYMBOL_PAGE2,  //KEY CODE = -9
        GUI_VKBD_PEN_V3_SYMBOL_PAGE3,  //KEY CODE = -10
        GUI_VKBD_PEN_V3_MOVE_LEFT, //KEY CODE = -12
        GUI_VKBD_PEN_V3_MOVE_RIGHT,    //KEY CODE = -13
        GUI_VKBD_PEN_V3_HANDWRITING_SWITCH,    //KEY CODE = -37
        GUI_VKBD_PEN_V3_CHANGE_MODE_BETWEEN_SMART_AND_MULTITAP, //KEY CODE = -100
        GUI_VKBD_PEN_DEFAULT_VALUE,
        GUI_VKBD_PEN_V3_SHIFT_UP_TO_LOW,  //KEY CODE = -101
        GUI_VKBD_PEN_V3_SHIFT_LOW_TO_UP,  //KEY CODE = -102
        GUI_VKBD_PEN_V3_CUSTOM_SYMBOLE_SWITCH, // KEY CODE = -30
        GUI_VKBD_PEN_V3_CUSTOM_SYMBOL_PAGE1,    // KEY_CODE = -31
        GUI_VKBD_PEN_V3_CUSTOM_SYMBOL_PAGE2,    //KEY CODE = 32
        GUI_VKBD_PEN_V3_DOT_NET,
        GUI_VKBD_PEN_V3_DOT_EDU,
        GUI_VKBD_PEN_V3_DOT_ORG,
        GUI_VKBD_PEN_V3_123SYM,
        GUI_VKBD_PEN_V3_123SYM_PAGE1,
        GUI_VKBD_PEN_V3_123SYM_PAGE2,
        GUI_VKBD_PEN_V3_123SYM_SWITCH,
        
        GUI_VKBD_PEN_MAX
        } gui_virtual_keyboard_pen_enum;
#endif

#if defined(__MMI_UI_VIRTUAL_KEYBOARD_DEFAULT_VERSION_2__)
/*****************************************************************************
 * Following code is for VK V2
 ****************************************************************************/
/* <group dom_virtual_keyboard_macros>
 *  vk type attribute */
#define MMI_VK_TYPE_ROTATION            0x00000001
/* <group dom_virtual_keyboard_macros> */
#define MMI_VK_TYPE_NOT_ROTATION    0x00000002
/* <group dom_virtual_keyboard_macros> */
#define MMI_VK_TYPE_QWERTY              0x00000004
/* <group dom_virtual_keyboard_macros> */
#define MMI_VK_TYPE_ALPHANUMERIC   0x00000008


#if defined (__MMI_INDIC_VK__)
/* <group dom_virtual_keyboard_struct> */
typedef struct
{
    gui_virtual_keyboard_language_enum cons_matra1;
    gui_virtual_keyboard_language_enum cons_matra2;
    gui_virtual_keyboard_language_enum cons_independentvowel1;
    gui_virtual_keyboard_language_enum cons_independentvowel2;
    gui_virtual_keyboard_language_enum symbols;
} gui_vk_indic_toggle_struct;

/* <group dom_virtual_keyboard_enum> */
typedef enum
{

    GUI_VIRTUAL_KEYBOARD_LANGUAGE_ID_NONE
#if defined (__MMI_INDIC_VK_HINDI__)
    ,GUI_VIRTUAL_KEYBOARD_LANGUAGE_ID_HINDI
#endif 
#if defined (__MMI_INDIC_VK_TAMIL__)
    ,GUI_VIRTUAL_KEYBOARD_LANGUAGE_ID_TAMIL
#endif 
#if defined (__MMI_INDIC_VK_BENGALI__)
    ,GUI_VIRTUAL_KEYBOARD_LANGUAGE_ID_BENGALI
#endif 
#if defined (__MMI_INDIC_VK_ASSAMESE__)
    ,GUI_VIRTUAL_KEYBOARD_LANGUAGE_ID_ASSAMESE
#endif 
#if defined (__MMI_INDIC_VK_PUNJABI__)
    ,GUI_VIRTUAL_KEYBOARD_LANGUAGE_ID_PUNJABI
#endif 
#if defined (__MMI_INDIC_VK_MARATHI__)
    ,GUI_VIRTUAL_KEYBOARD_LANGUAGE_ID_MARATHI
#endif 
#if defined (__MMI_INDIC_VK_GUJARATI__)
    , GUI_VIRTUAL_KEYBOARD_LANGUAGE_ID_GUJARATI
#endif 
#if defined (__MMI_INDIC_VK_KANNADA__)
    , GUI_VIRTUAL_KEYBOARD_LANGUAGE_ID_KANNADA
#endif 
#if defined (__MMI_INDIC_VK_ORIYA__)
        , GUI_VIRTUAL_KEYBOARD_LANGUAGE_ID_ORIYA
#endif 
#if defined (__MMI_INDIC_VK_MALAYALAM__)
        , GUI_VIRTUAL_KEYBOARD_LANGUAGE_ID_MALAYALAM
#endif 
#if defined (__MMI_INDIC_VK_TELUGU__)
        , GUI_VIRTUAL_KEYBOARD_LANGUAGE_ID_TELUGU
#endif 
} gui_virtual_keyboard_indic_enum;
extern const gui_vk_indic_toggle_struct gui_vk_indic_toggle_table[];

#endif /* defined (__MMI_INDIC_VK__) */ 
#endif /* __MMI_UI_VIRTUAL_KEYBOARD_DEFAULT_VERSION_2__ */

#endif /* __MMI_TOUCH_SCREEN__ */

#endif /* __GUI_VIRTUAL_KEYBOARD_LANGUAGE_TYPE_H__ */

