#include "MMI_features.h"
#include "MMIDataType.h"
#include "CustResDef.h"
#include "CustDataProts.h"

<?xml version="1.0" encoding="UTF-8"?>
<APP id="APP_MEDIAWALL">

#ifdef __MMI_VUI_MEDIAWALL__
    
    #define ROOT_PATH CUST_IMG_PATH"\\\\MainLCD\\\\MediaWall\\\\"
    <IMAGE id="VAPP_MEDIAWALL_IMG_SOFTKEY_LSK">ROOT_PATH"IVEX_WV_FULL_SK_OPTION.png"</IMAGE>
    <IMAGE id="VAPP_MEDIAWALL_IMG_SOFTKEY_LSK_INSET">ROOT_PATH"IVEX_WV_SK_OPTION.png"</IMAGE>
    <IMAGE id="VAPP_MEDIAWALL_IMG_SOFTKEY_RSK">ROOT_PATH"IVEX_WV_FULL_SK_BACK.png"</IMAGE>
    <IMAGE id="VAPP_MEDIAWALL_IMG_SOFTKEY_RSK_INSET">ROOT_PATH"IVEX_WV_SK_BACK.png"</IMAGE>
    <IMAGE id="VAPP_MEDIAWALL_IMG_DEFAULT_ICON">ROOT_PATH"IVEX_WV_DEFAULT.png"</IMAGE>
    <IMAGE id="VAPP_MEDIAWALL_IMG_UNSUPPORT_ICON">ROOT_PATH"IVEX_WV_UNKNOW.png"</IMAGE>
    <IMAGE id="VAPP_MEDIAWALL_IMG_DRM_LOCKED_ICON">ROOT_PATH"IVEX_WV_LOCK.png"</IMAGE>
    <IMAGE id="VAPP_MEDIAWALL_IMG_BUT_HIGHLIGHT">ROOT_PATH"IVEX_WV_HIGHLIGHT.png"</IMAGE>
    <IMAGE id="VAPP_MEDIAWALL_IMG_PORTRAIT_ROTATE">ROOT_PATH"IVEX_WV_ROTATE.png"</IMAGE>
    <IMAGE id="VAPP_MEDIAWALL_IMG_LANDSCAPE_ROTATE">ROOT_PATH"IVEX_WV_ROTATE_02.png"</IMAGE>

    <IMAGE id="VAPP_MEDIAWALL_IMG_TITLE_SHADOW">ROOT_PATH"IVEX_WV_TITLE_SHADOW.9slice.png"</IMAGE>
    <IMAGE id="VAPP_MEDIAWALL_IMG_SOFTKEYBAR_BG">ROOT_PATH"IVEX_WV_SK_BG.9slice.png"</IMAGE> 
    <IMAGE id="VAPP_MEDIAWALL_IMG_SOFTKEYBAR_SHADOW">ROOT_PATH"IVEX_WV_SK_SHADOW.9slice.png"</IMAGE>
    <IMAGE id="VAPP_MEDIAWALL_IMG_STATUSBAR_BG">ROOT_PATH"IVEX_WV_STATUS_BG.9slice.png"</IMAGE>
    <IMAGE id="VAPP_MEDIAWALL_IMG_MENU_SHADOW_LEFT">ROOT_PATH"IVEX_FADEOUT_LEFT.9slice.png"</IMAGE>
    <IMAGE id="VAPP_MEDIAWALL_IMG_MENU_SHADOW_RIGHT">ROOT_PATH"IVEX_FADEOUT_RIGHT.9slice.png"</IMAGE>
    <IMAGE id="VAPP_MEDIAWALL_IMG_TITLE">ROOT_PATH"IVEX_WV_TITLE_BG.9slice.png"</IMAGE>
#endif

</APP>
