/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 * ArabicShapingEngine.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   This file is header file for ArabicShapingEngine
 *
 * Author:
 * -------
 * -------
 *
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/

#include "MMI_features.h"

/* RHR */
#include "MMIDataType.h"
#include "kal_general_types.h"
    

#ifdef __MMI_ARSHAPING_ENGINE__

#define UNICODE_ARABIC(ch)        (U16)((ch) - 0x620)
#define UNICODE_ARABIC_FORM_B(ch)        (U16)((ch) - 0xFE70)
#define UNICODE_ARABIC_FORM_A(ch)        (U16)((ch) - 0xFB50)
#define UI_ARABIC_CHARACTER_RANGE(ch)      ((((U16)(ch) > 0x620)&&((U16)(ch) < 0x6FF))?(1) : (0) )

typedef enum
{
    ARABIC_NON_JOIN,
    ARABIC_TRANSPARENT,
    ARABIC_DUAL_JOIN,
    ARABIC_RIGHT_JOIN,
    ARABIC_LEFT_JOIN,
    ARABIC_JOIN_CAUSING,
    ARABIC_JOIN_CLASS_MAX
} ARABIC_JOIN_TYPE_ENUM;

extern const ARABIC_JOIN_TYPE_ENUM g_arabic_base_char_array[];
extern const ARABIC_JOIN_TYPE_ENUM g_arabic_form_A_char_array[];
extern const ARABIC_JOIN_TYPE_ENUM g_arabic_form_B_char_array[];

#define UI_ARABIC_FORM_A_RANGE(ch)      ((((U16)(ch) >= 0xFB50)&&((U16)(ch) <= 0xFDFD))?(1) : (0) )
#define UI_ARABIC_FORM_B_RANGE(ch)      ((((U16)(ch) >= 0xFE70)&&((U16)(ch) <= 0xFEFF))?(1) : (0) )
#define ARABIC_LIGATURE_LENGTH	5
#define LANGUAGE_FOR_LIGATURE	0
#define NOT_SUPPORTED 0
#define  WHETHER_JOIN_CHARACTER(ch)  (UI_ARABIC_CHARACTER_RANGE(ch) &&  g_arabic_base_char_array[UNICODE_ARABIC(ch)]) || (UI_ARABIC_FORM_B_RANGE(ch) &&  g_arabic_form_B_char_array[UNICODE_ARABIC_FORM_B(ch)])|| (UI_ARABIC_FORM_A_RANGE(ch) &&  g_arabic_form_A_char_array[UNICODE_ARABIC_FORM_A(ch)])

#ifndef NULL
#define NULL  0
#endif

typedef struct
{
    U16 nominalForm;
    U16 preForm;
    U16 postForm;
    U16 middleForm;
} ARABIC_SHAPE_TABLE;

typedef enum
{
    /* Nominal glyph Forms */
    N_HAMZA = 0x0621,
    N_MADDA_ON_ALEF = 0x622,
    N_HAMZA_ON_ALEF = 0x623,
    N_HAMZA_ON_WOW = 0x624,
    N_HAMZA_UNDER_ALEF = 0x625,
    N_HAMZA_ON_YEH = 0x626,
    N_ALEF = 0x627,
    N_BEH = 0x628,
    N_TEH_MARBUTA = 0x629,
    N_TEH = 0x62A,
    N_THEH = 0x62B,
    N_JEEM = 0x62C,
    N_HAH = 0x62D,
    N_KHAH = 0x62E,
    N_DAL = 0x62F,
    N_THAL = 0x630,
    N_REH = 0x631,
    N_ZAIN = 0x632,
    N_SEEN = 0x633,
    N_SHEEN = 0x634,
    N_SAD = 0x635,
    N_DAD = 0x636,
    N_TAH = 0x637,
    N_ZAH = 0x638,
    N_AIN = 0x639,
    N_GHAIN = 0x63A,
    N_TATWEEL = 0x640,
    N_FEH = 0x641,
    N_QAF = 0x642,
    N_KAF = 0x643,
    N_LAM = 0x644,
    N_MEEM = 0x645,
    N_NOON = 0x646,
    N_HEH = 0x647,
    N_WAW = 0x648,
    N_ALEF_MAKSURA = 0x649,
    /* PMT START PERSIAN */
    N_YEH = 0x64A,
    //PMT START URDU
    /* PMT START DIGIT */
    N_ARABIC_D_ZERO = 0x660,
    N_ARABIC_D_ONE = 0x661,
    N_ARABIC_D_TWO = 0x662,
    N_ARABIC_D_THREE = 0x663,
    N_ARABIC_D_FOUR = 0x664,
    N_ARABIC_D_FIVE = 0x665,
    N_ARABIC_D_SIX = 0x666,
    N_ARABIC_D_SEVEN = 0x667,
    N_ARABIC_D_EIGHT = 0x668,
    N_ARABIC_D_NINE = 0x669,
    /* PMT END DIGIT */
    //PMT END URDU

    N_PEH = 0x67E,
    N_TCHEH = 0x686,
    N_JEH = 0x698,
    N_KHEHEH = 0x6A9,
    N_GAF = 0x6AF,
    N_FARSIYEH = 0x6CC,

    /* PMT START URDU */
    N_TTEH = 0x0679,
    N_DDAL = 0x0688,
    N_RREH = 0x0691,
    N_NOON_GHUNNA = 0x06BA,
    N_HEH_DOCHASHMEE = 0x06BE,
    N_HEH_GOAL = 0x06C1,
    N_HEH_GOAL_WITH_HAMZA_ABOVE = 0x06C2,
    N_HEH_MARBUTA_GOAL = 0x06C3,
    N_YEH_BARREE = 0x06D2,
    N_YEH_BARREE_WITH_HAMZA_ABOVE = 0x06D3,

    /* PMT START EXTENDED DIGIT */
    N_ARABIC_EXD_ZERO = 0x6F0,
    N_ARABIC_EXD_ONE = 0x6F1,
    N_ARABIC_EXD_TWO = 0x6F2,
    N_ARABIC_EXD_THREE = 0x6F3,
    N_ARABIC_EXD_FOUR = 0x6F4,
    N_ARABIC_EXD_FIVE = 0x6F5,
    N_ARABIC_EXD_SIX = 0x6F6,
    N_ARABIC_EXD_SEVEN = 0x6F7,
    N_ARABIC_EXD_EIGHT = 0x6F8,
    N_ARABIC_EXD_NINE = 0x6F9,
    /* PMT END EXTENDED DIGIT */


    N_HAMZA_ON_YEH_WITH_ALEF = 0xFBEA,
    N_HAMZA_ON_YEH_WITH_WAW = 0xFBEE,
    N_HAMZA_ON_YEH_WITH_JEEM = 0xFC00,
    N_HAMZA_ON_YEH_WITH_HAH = 0xFC01,
    N_HAMZA_ON_YEH_WITH_MEEM = 0xFC02,
    N_HAMZA_ON_YEH_WITH_ALEF_MAKSURA = 0xFC03,
    N_HAMZA_ON_YEH_WITH_YEH = 0xFC04,
    N_HAMZA_ON_YEH_WITH_REH = 0xFC64,
    N_HAMZA_ON_YEH_WITH_ZAIN = 0xFC65,
    N_HAMZA_ON_YEH_WITH_NOON = 0xFC67,

    N_BEH_WITH_JEEM = 0xFC05,
    N_BEH_WITH_HAH = 0xFC06,
    N_BEH_WITH_KHAH = 0xFC07,
    N_BEH_WITH_MEEM = 0xFC08,
    N_BEH_WITH_ALEF_MAKSURA = 0xFC09,
    N_BEH_WITH_YEH = 0xFC0A,
    N_BEH_WITH_REH = 0xFC6A,
    N_BEH_WITH_ZAIN = 0xFC6B,
    N_BEH_WITH_NOON = 0xFC6D,

    N_TEH_WITH_JEEM = 0xFC0B,
    N_TEH_WITH_HAH = 0xFC0C,
    N_TEH_WITH_KHAH = 0xFC0D,
    N_TEH_WITH_MEEM = 0xFC0E,
    N_TEH_WITH_ALEF_MAKSURA = 0xFC0F,
    N_TEH_WITH_YEH = 0xFC10,
    N_TEH_WITH_REH = 0xFC70,
    N_TEH_WITH_ZAIN = 0xFC71,
    N_TEH_WITH_NOON = 0xFC73,

    N_THEH_WITH_JEEM = 0xFC11,
    N_THEH_WITH_MEEM = 0xFC12,
    N_THEH_WITH_ALEF_MAKSURA = 0xFC13,
    N_THEH_WITH_YEH = 0xFC14,
    N_THEH_WITH_REH = 0xFC76,
    N_THEH_WITH_ZAIN = 0xFC77,
    N_THEH_WITH_NOON = 0xFC79,

    N_JEEM_WITH_HAH = 0xFC15,
    N_JEEM_WITH_MEEM = 0xFC16,
    N_JEEM_WITH_ALEF_MAKSURA = 0xFD01,
    N_JEEM_WITH_YEH = 0xFD02,

    N_HAH_WITH_JEEM = 0xFC17,
    N_HAH_WITH_MEEM = 0xFC18,
    N_HAH_WITH_ALEF_MAKSURA = 0xFCFF,
    N_HAH_WITH_YEH = 0xFD00,

    N_KHAH_WITH_JEEM = 0xFC19,
    N_KHAH_WITH_HAH = 0xFC1A,
    N_KHAH_WITH_MEEM = 0xFC1B,
    N_KHAH_WITH_ALEF_MAKSURA = 0xFD03,
    N_KHAH_WITH_YEH = 0xFD04,

    N_SEEN_WITH_JEEM = 0xFC1C,
    N_SEEN_WITH_HAH = 0xFC1D,
    N_SEEN_WITH_KHAH = 0xFC1E,
    N_SEEN_WITH_MEEM = 0xFC1F,
    N_SEEN_WITH_ALEF_MAKSURA = 0xFCFB,
    N_SEEN_WITH_YEH = 0xFCFB,
    N_SEEN_WITH_REH = 0xFD0E,

    N_SHEEN_WITH_JEEM = 0xFD09,
    N_SHEEN_WITH_HAH = 0xFD0A,
    N_SHEEN_WITH_KHAH = 0xFD0B,
    N_SHEEN_WITH_MEEM = 0xFD0C,
    N_SHEEN_WITH_REH = 0xFD0D,
    N_SHEEN_WITH_HEH = 0xFCEA,
    N_SHEEN_WITH_ALEF_MAKSURA = 0xFCFD,
    N_SHEEN_WITH_YEH = 0xFCFE,

    N_SAD_WITH_HAH = 0xFC20,
    N_SAD_WITH_MEEM = 0xFC21,
    N_SAD_WITH_ALEF_MAKSURA = 0xFD05,
    N_SAD_WITH_YEH = 0xFD06,
    N_SAD_WITH_REH = 0xFD0F,
    N_SAD_WITH_LAM_WITH_AIN_WITH_MEEM = 0xFDF5,
    N_SAD_WITH_LAM_WITH_ALEF_MAKSURA = 0xFDF9,

    N_DAD_WITH_JEEM = 0xFC22,
    N_DAD_WITH_HAH = 0xFC23,
    N_DAD_WITH_KHAH = 0xFC24,
    N_DAD_WITH_MEEM = 0xFC25,
    N_DAD_WITH_ALEF_MAKSURA = 0xFD07,
    N_DAD_WITH_YEH = 0xFD08,
    N_DAD_WITH_REH = 0xFD10,

    N_TAH_WITH_HAH = 0xFC26,
    N_TAH_WITH_MEEM = 0xFC27,

    N_ZAH_WITH_MEEM = 0xFC28,

    N_AIN_WITH_JEEM = 0xFC29,
    N_AIN_WITH_MEEM = 0xFC2A,
    N_AIN_WITH_ALEF_MAKSURA = 0xFCF7,
    N_AIN_WITH_YEH = 0xFCF8,
    N_AIN_WITH_LAM_WITH_YEH_WITH_HEH = 0xFDF7,

    N_GHAIN_WITH_JEEM = 0xFC2B,
    N_GHAIN_WITH_MEEM = 0xFC2C,
    N_GHAIN_WITH_ALEF_MAKSURA = 0xFCF9,
    N_GHAIN_WITH_YEH = 0xFCFA,

    N_FEH_WITH_JEEM = 0xFC2D,
    N_FEH_WITH_HAH = 0xFC2E,
    N_FEH_WITH_KHAH = 0xFC2F,
    N_FEH_WITH_MEEM = 0xFC30,
    N_FEH_WITH_ALEF_MAKSURA = 0xFC31,
    N_FEH_WITH_YEH = 0xFC32,

    N_QAF_WITH_HAH = 0xFC33,
    N_QAF_WITH_MEEM = 0xFC34,
    N_QAF_WITH_ALEF_MAKSURA = 0xFC35,
    N_QAF_WITH_YEH = 0xFC36,

    N_KAF_WITH_ALEF = 0xFC37,
    N_KAF_WITH_JEEM = 0xFC38,
    N_KAF_WITH_HAH = 0xFC39,
    N_KAF_WITH_KHAH = 0xFC3A,
    N_KAF_WITH_LAM = 0xFC3B,
    N_KAF_WITH_MEEM = 0xFC3C,
    N_KAF_WITH_ALEF_MAKSURA = 0xFC3D,
    N_KAF_WITH_YEH = 0xFC3E,

    N_LAM_WITH_JEEM = 0xFC3F,
    N_LAM_WITH_HAH = 0xFC40,
    N_LAM_WITH_KHAH = 0xFC41,
    N_LAM_WITH_MEEM = 0xFC42,
    N_LAM_WITH_ALEF_MAKSURA = 0xFC43,
    N_LAM_WITH_YEH = 0xFC44,

    N_MEEM_WITH_JEEM = 0xFC45,
    N_MEEM_WITH_HAH = 0xFC46,
    N_MEEM_WITH_KHAH = 0xFC47,
    N_MEEM_WITH_MEEM = 0xFC48,
    N_MEEM_WITH_ALEF_MAKSURA = 0xFC49,
    N_MEEM_WITH_YEH = 0xFC4A,
    N_MEEM_WITH_ALEF = 0xFC88,
    N_MEEM_WITH_HAH_WITH_MEEM_WITH_DAL = 0xFDF4,

    N_NOON_WITH_JEEM = 0xFC4B,
    N_NOON_WITH_HAH = 0xFC4C,
    N_NOON_WITH_KHAH = 0xFC4D,
    N_NOON_WITH_MEEM = 0xFC4E,
    N_NOON_WITH_ALEF_MAKSURA = 0xFC4F,
    N_NOON_WITH_YEH = 0xFC50,
    N_NOON_WITH_REH = 0xFC8A,
    N_NOON_WITH_ZAIN = 0xFC8B,
    N_NOON_WITH_NOON = 0xFC8D,

    N_HEH_WITH_JEEM = 0xFC51,
    N_HEH_WITH_MEEM = 0xFC52,
    N_HEH_WITH_ALEF_MAKSURA = 0xFC53,
    N_HEH_WITH_YEH = 0xFC54,

    N_YEH_WITH_JEEM = 0xFC55,
    N_YEH_WITH_HAH = 0xFC56,
    N_YEH_WITH_KHAH = 0xFC57,
    N_YEH_WITH_MEEM = 0xFC58,
    N_YEH_WITH_ALEF_MAKSURA = 0xFC59,
    N_YEH_WITH_YEH = 0xFC5A,
    N_YEH_WITH_REH = 0xFC91,
    N_YEH_WITH_ZAIN = 0xFC92,
    N_YEH_WITH_NOON = 0xFC94,

    N_TAH_WITH_ALEF_MAKSURA = 0xFCF5,
    N_TAH_WITH_YEH = 0xFCF6,

    N_SAD_WITH_LAM_WITH_YEH_BARREE = 0xFDF0,
    N_ALEF_WITH_LAM_WITH_LAM_WITH_HEH = 0xFDF2,
    N_ALEF_WITH_KAF_WITH_BEH_WITH_REH = 0xFDF3,

    N_REH_WITH_SEEN_WITH_WAW_WITH_LAM = 0xFDF6,
    N_WAW_WITH_SEEN_WITH_LAM_WITH_MEEM = 0xFDF8,
    N_JALLAJALLALOUHOU = 0xFDFB,
    N_REH_WITH_FARSIYEH_WITH_ALEF_WITH_LAM = 0xFDFC,
    N_BISMILLAH_AR_RAHMAN_AR_RAHEEM = 0xFDFD,
/* PMT END URDU */
    /* Ligatures */
    N_MADDA_ON_LAMALEF = 0xFEF5,
    N_HAMZA_ON_LAMALEF = 0xFEF7,
    N_HAMZA_UNDER_LAMALEF = 0xFEF9,
    N_LAMALEF = 0xFEFB
        /* PMT END PERSIAN */
} NOMINAL_CHARACTERS_ENUM;

typedef enum
{
    /* left joining Form */
    L_MADDA_ON_ALEF = 0xFE81,
    L_HAMZA_ON_ALEF = 0xFE83,
    L_HAMZA_ON_WOW = 0xFE85,
    L_HAMZA_UNDER_ALEF = 0xFE87,
    L_HAMZA_ON_YEH = 0xFE8B,
    L_ALEF = 0xFE8D,
    L_BEH = 0xFE91,
    L_TEH_MARBUTA = 0xFE93,
    L_TEH = 0xFE97,
    L_THEH = 0xFE9B,
    L_JEEM = 0xFE9F,
    L_HAH = 0xFEA3,
    L_KHAH = 0xFEA7,
    L_DAL = 0xFEA9,
    L_THAL = 0xFEAB,
    L_REH = 0xFEAD,
    L_ZAIN = 0xFEAF,
    L_SEEN = 0xFEB3,
    L_SHEEN = 0xFEB7,
    L_SAD = 0xFEBB,
    L_DAD = 0xFEBF,
    L_TAH = 0xFEC3,
    L_ZAH = 0xFEC7,
    L_AIN = 0xFECB,
    L_GHAIN = 0xFECF,
    /* L_TATWEEL=0x640, same for all forms. */
    L_FEH = 0xFED3,
    L_QAF = 0xFED7,
    L_KAF = 0xFEDB,
    L_LAM = 0xFEDF,
    L_MEEM = 0xFEE3,
    L_NOON = 0xFEE7,
    L_HEH = 0xFEEB,
    L_WAW = 0xFEED,
    L_ALEF_MAKSURA = 0xFEEF,
    /* PMT START PERSIAN */
    L_YEH = 0xFEF3,
    L_PEH = 0xFB58,
    L_TCHEH = 0xFB7C,
    L_JEH = 0xFB8A,
    L_KHEHEH = 0xFB90,
    L_GAF = 0xFB94,
    L_FARSIYEH = 0xFBFE,

    /* PMT START URDU */
    L_TTEH = 0xFB68,
    L_DDAL = 0xFB88,
    L_RREH = 0xFB8C,
    L_NOON_GHUNNA = 0xFB9E,
    L_HEH_DOCHASHMEE = 0xFBAC,
    L_HEH_GOAL = 0xFBA8,
    L_YEH_BARREE = 0xFBAE,
    L_YEH_BARREE_WITH_HAMZA_ABOVE = 0xFBB0,

    L_HAMZA_ON_YEH_WITH_ALEF = 0xFBEA,
    L_HAMZA_ON_YEH_WITH_WAW = 0xFBEE,
    L_HAMZA_ON_YEH_WITH_JEEM = 0xFC97,
    L_HAMZA_ON_YEH_WITH_HAH = 0xFC98,
    L_HAMZA_ON_YEH_WITH_MEEM = 0xFC9A,
    L_HAMZA_ON_YEH_WITH_ALEF_MAKSURA = 0xFC03,
    L_HAMZA_ON_YEH_WITH_YEH = 0xFC04,
    L_HAMZA_ON_YEH_WITH_REH = 0xFC64,
    L_HAMZA_ON_YEH_WITH_ZAIN = 0xFC65,
    L_HAMZA_ON_YEH_WITH_NOON = 0xFC67,
    L_HAMZA_ON_YEH_WITH_KHAH = 0xFC99,
    L_HAMZA_ON_YEH_WITH_HEH = 0xFC9B,

    L_BEH_WITH_JEEM = 0xFC9C,
    L_BEH_WITH_HAH = 0xFC9D,
    L_BEH_WITH_KHAH = 0xFC9E,
    L_BEH_WITH_MEEM = 0xFC9F,
    L_BEH_WITH_ALEF_MAKSURA = 0xFC09,
    L_BEH_WITH_YEH = 0xFC0A,
    L_BEH_WITH_REH = 0xFC6A,
    L_BEH_WITH_ZAIN = 0xFC6B,
    L_BEH_WITH_NOON = 0xFC6D,
    L_BEH_WITH_HEH = 0xFCA0,

    L_TEH_WITH_JEEM = 0xFCA1,
    L_TEH_WITH_HAH = 0xFCA2,
    L_TEH_WITH_KHAH = 0xFCA3,
    L_TEH_WITH_MEEM = 0xFCA4,
    L_TEH_WITH_ALEF_MAKSURA = 0xFC0F,
    L_TEH_WITH_YEH = 0xFC10,
    L_TEH_WITH_REH = 0xFC70,
    L_TEH_WITH_ZAIN = 0xFC71,
    L_TEH_WITH_NOON = 0xFC73,
    L_TEH_WITH_HEH = 0xFCA5,
    L_TEH_WITH_JEEM_WITH_MEEM = 0xFD50,
    L_TEH_WITH_HAH_WITH_JEEM = 0xFD52,
    L_TEH_WITH_HAH_WITH_MEEM = 0xFD53,
    L_TEH_WITH_KHAH_WITH_MEEM = 0xFD54,
    L_TEH_WITH_MEEM_WITH_JEEM = 0xFD55,
    L_TEH_WITH_MEEM_WITH_HAH = 0xFD56,
    L_TEH_WITH_MEEM_WITH_KHAH = 0xFD57,

    L_THEH_WITH_JEEM = 0xFC11,
    L_THEH_WITH_MEEM = 0xFCA6,
    L_THEH_WITH_ALEF_MAKSURA = 0xFC13,
    L_THEH_WITH_YEH = 0xFC14,
    L_THEH_WITH_REH = 0xFC76,
    L_THEH_WITH_ZAIN = 0xFC77,
    L_THEH_WITH_NOON = 0xFC79,

    L_JEEM_WITH_HAH = 0xFCA7,
    L_JEEM_WITH_MEEM = 0xFCA8,
    L_JEEM_WITH_MEEM_WITH_HAH = 0xFD59,

    L_HAH_WITH_JEEM = 0xFCA9,
    L_HAH_WITH_MEEM = 0xFCAA,

    L_KHAH_WITH_JEEM = 0xFCAB,
    L_KHAH_WITH_HAH = 0xFC1A,
    L_KHAH_WITH_MEEM = 0xFCAC,

    L_SEEN_WITH_JEEM = 0xFCAD,
    L_SEEN_WITH_HAH = 0xFCAE,
    L_SEEN_WITH_KHAH = 0xFCAF,
    L_SEEN_WITH_MEEM = 0xFCB0,
    L_SEEN_WITH_ALEF_MAKSURA = 0xFCFB,
    L_SEEN_WITH_YEH = 0xFCFB,
    L_SEEN_WITH_HEH = 0xFD31,
    L_SEEN_WITH_HAH_WITH_JEEM = 0xFD5C,
    L_SEEN_WITH_JEEM_WITH_HAH = 0xFD5D,
    L_SEEN_WITH_MEEM_WITH_HAH = 0xFD60,
    L_SEEN_WITH_MEEM_WITH_JEEM = 0xFD61,
    L_SEEN_WITH_MEEM_WITH_MEEM = 0xFD63,

    L_SHEEN_WITH_MEEM = 0xFD30,
    L_SHEEN_WITH_ALEF_MAKSURA = 0xFCFD,
    L_SHEEN_WITH_YEH = 0xFCFE,
    L_SHEEN_WITH_JEEM = 0xFD2D,
    L_SHEEN_WITH_HAH = 0xFD2E,
    L_SHEEN_WITH_KHAH = 0xFD2F,
    L_SHEEN_WITH_HEH = 0xFD32,
    L_SHEEN_WITH_HAH_WITH_MEEM = 0xFD68,
    L_SHEEN_WITH_MEEM_WITH_KHAH = 0xFD6B,
    L_SHEEN_WITH_MEEM_WITH_MEEM = 0xFD6D,

    L_SAD_WITH_HAH = 0xFCB1,
    L_SAD_WITH_MEEM = 0xFCB3,
    L_SAD_WITH_KHAH = 0xFCB2,
    L_SAD_WITH_HAH_WITH_HAH = 0xFD65,
    L_SAD_WITH_MEEM_WITH_MEEM = 0xFDC5,

    L_DAD_WITH_JEEM = 0xFCB4,
    L_DAD_WITH_HAH = 0xFCB5,
    L_DAD_WITH_KHAH = 0xFCB6,
    L_DAD_WITH_MEEM = 0xFCB7,
    L_DAD_WITH_KHAH_WITH_MEEM = 0xFD70,

    L_TAH_WITH_HAH = 0xFCB8,
    L_TAH_WITH_MEEM = 0xFD33,
    L_TAH_WITH_ALEF_MAKSURA = 0xFCF5,
    L_TAH_WITH_YEH = 0xFCF6,
    L_TAH_WITH_MEEM_WITH_HAH = 0xFD72,
    L_TAH_WITH_MEEM_WITH_MEEM = 0xFD73,

    L_ZAH_WITH_MEEM = 0xFCB9,

    L_AIN_WITH_JEEM = 0xFCBA,
    L_AIN_WITH_MEEM = 0xFCBB,
    L_AIN_WITH_ALEF_MAKSURA = 0xFCF7,
    L_AIN_WITH_YEH = 0xFCF8,
    L_AIN_WITH_MEEM_WITH_MEEM = 0xFD77,
    L_AIN_WITH_JEEM_WITH_MEEM = 0xFDC4,

    L_GHAIN_WITH_JEEM = 0xFCBC,
    L_GHAIN_WITH_MEEM = 0xFCBD,
    L_GHAIN_WITH_ALEF_MAKSURA = 0xFCF9,
    L_GHAIN_WITH_YEH = 0xFCFA,

    L_FEH_WITH_JEEM = 0xFCBE,
    L_FEH_WITH_HAH = 0xFCBF,
    L_FEH_WITH_KHAH = 0xFCC0,
    L_FEH_WITH_MEEM = 0xFCC1,
    L_FEH_WITH_ALEF_MAKSURA = 0xFC31,
    L_FEH_WITH_YEH = 0xFC32,
    L_FEH_WITH_KHAH_WITH_MEEM = 0xFD7D,

    L_QAF_WITH_HAH = 0xFCC2,
    L_QAF_WITH_MEEM = 0xFCC3,
    L_QAF_WITH_ALEF_MAKSURA = 0xFC35,
    L_QAF_WITH_YEH = 0xFC36,
    L_QAF_WITH_MEEM_WITH_HAH = 0xFDB4,

    L_KAF_WITH_ALEF = 0xFC37,
    L_KAF_WITH_JEEM = 0xFCC4,
    L_KAF_WITH_HAH = 0xFCC5,
    L_KAF_WITH_KHAH = 0xFCC6,
    L_KAF_WITH_LAM = 0xFCC7,
    L_KAF_WITH_MEEM = 0xFCC8,
    L_KAF_WITH_ALEF_MAKSURA = 0xFC3D,
    L_KAF_WITH_YEH = 0xFC3E,
    L_KAF_WITH_MEEM_WITH_MEEM = 0xFDC3,

    L_LAM_WITH_JEEM = 0xFCC9,
    L_LAM_WITH_HAH = 0xFCCA,
    L_LAM_WITH_KHAH = 0xFCCB,
    L_LAM_WITH_MEEM = 0xFCCC,
    L_LAM_WITH_ALEF_MAKSURA = 0xFC43,
    L_LAM_WITH_YEH = 0xFC44,
    L_LAM_WITH_HEH = 0xFCCD,
    L_LAM_WITH_JEEM_WITH_JEEM = 0xFD83,
    L_LAM_WITH_KHAH_WITH_MEEM = 0xFD86,
    L_LAM_WITH_MEEM_WITH_HAH = 0xFD88,
    L_LAM_WITH_JEEM_WITH_MEEM = 0xFDBA,
    L_LAM_WITH_HAH_WITH_MEEM = 0xFDB5,

    L_MEEM_WITH_JEEM = 0xFCCE,
    L_MEEM_WITH_HAH = 0xFCCF,
    L_MEEM_WITH_KHAH = 0xFCD0,
    L_MEEM_WITH_MEEM = 0xFCD1,
    L_MEEM_WITH_ALEF_MAKSURA = 0xFC49,
    L_MEEM_WITH_YEH = 0xFC4A,
    L_MEEM_WITH_ALEF = 0xFC88,
    L_MEEM_WITH_HAH_WITH_JEEM = 0xFD89,
    L_MEEM_WITH_HAH_WITH_MEEM = 0xFD8A,
    L_MEEM_WITH_JEEM_WITH_HAH = 0xFD8C,
    L_MEEM_WITH_JEEM_WITH_MEEM = 0xFD8D,
    L_MEEM_WITH_KHAH_WITH_JEEM = 0xFD8E,
    L_MEEM_WITH_KHAH_WITH_MEEM = 0xFD8F,
    L_MEEM_WITH_JEEM_WITH_KHAH = 0xFD92,

    L_NOON_WITH_JEEM = 0xFCD2,
    L_NOON_WITH_HAH = 0xFCD3,
    L_NOON_WITH_KHAH = 0xFCD4,
    L_NOON_WITH_MEEM = 0xFCD5,
    L_NOON_WITH_ALEF_MAKSURA = 0xFC4F,
    L_NOON_WITH_YEH = 0xFC50,
    L_NOON_WITH_REH = 0xFC8A,
    L_NOON_WITH_ZAIN = 0xFC8B,
    L_NOON_WITH_NOON = 0xFC8D,
    L_NOON_WITH_HEH = 0xFCD6,
    L_NOON_WITH_HAH_WITH_MEEM = 0xFD95,
    L_NOON_WITH_JEEM_WITH_MEEM = 0xFD98,
    L_NOON_WITH_JEEM_WITH_HAH = 0xFDB8,

    L_HEH_WITH_JEEM = 0xFCD7,
    L_HEH_WITH_MEEM = 0xFCD8,
    L_HEH_WITH_ALEF_MAKSURA = 0xFC53,
    L_HEH_WITH_YEH = 0xFC54,
    L_HEH_WITH_MEEM_WITH_JEEM = 0xFD93,
    L_HEH_WITH_MEEM_WITH_MEEM = 0xFD94,

    L_YEH_WITH_JEEM = 0xFCDA,
    L_YEH_WITH_HAH = 0xFCDB,
    L_YEH_WITH_KHAH = 0xFCDC,
    L_YEH_WITH_MEEM = 0xFCDD,
    L_YEH_WITH_ALEF_MAKSURA = 0xFC59,
    L_YEH_WITH_YEH = 0xFC5A,
    L_YEH_WITH_REH = 0xFC91,
    L_YEH_WITH_ZAIN = 0xFC92,
    L_YEH_WITH_NOON = 0xFC94,
    L_YEH_WITH_HEH = 0xFCDE,
    L_YEH_WITH_MEEM_WITH_MEEM = 0xFD9D,

    L_KHEHEH_WITH_YEH_BARREE = 0xFDFF,
    /* PMT END URDU */
    /* Ligatures */
    L_MADDA_ON_LAMALEF = 0xFEF5,
    L_HAMZA_ON_LAMALEF = 0xFEF7,
    L_HAMZA_UNDER_LAMALEF = 0xFEF9,
    L_LAMALEF = 0xFEFB
        /* PMT END PERSIAN */
} LEFT_JOINING_CHARACTERS_ENUM;

typedef enum
{
    /* Right joining Form */
    R_MADDA_ON_ALEF = 0xFE82,
    R_HAMZA_ON_ALEF = 0xFE84,
    R_HAMZA_ON_WOW = 0xFE86,
    R_HAMZA_UNDER_ALEF = 0xFE88,
    R_HAMZA_ON_YEH = 0xFE8A,
    R_ALEF = 0xFE8E,
    R_BEH = 0xFE90,
    R_TEH_MARBUTA = 0xFE94,
    R_TEH = 0xFE96,
    R_THEH = 0xFE9A,
    R_JEEM = 0xFE9E,
    R_HAH = 0xFEA2,
    R_KHAH = 0xFEA6,
    R_DAL = 0xFEAA,
    R_THAL = 0xFEAC,
    R_REH = 0xFEAE,
    R_ZAIN = 0xFEB0,
    R_SEEN = 0xFEB2,
    R_SHEEN = 0xFEB6,
    R_SAD = 0xFEBA,
    R_DAD = 0xFEBE,
    R_TAH = 0xFEC2,
    R_ZAH = 0xFEC6,
    R_AIN = 0xFECA,
    R_GHAIN = 0xFECE,
    /* R_TATWEEL=0x640, same for all forms. */
    R_FEH = 0xFED2,
    R_QAF = 0xFED6,
    R_KAF = 0xFEDA,
    R_LAM = 0xFEDE,
    R_MEEM = 0xFEE2,
    R_NOON = 0xFEE6,
    R_HEH = 0xFEEA,
    R_WAW = 0xFEEE,
    R_ALEF_MAKSURA = 0xFEF0,
    /* PMT START PERSIAN */
    R_YEH = 0xFEF2,
    R_PEH = 0xFB57,
    R_TCHEH = 0xFB7B,
    R_JEH = 0xFB8B,
    R_KHEHEH = 0xFB8F,
    R_GAF = 0xFB93,
    R_FARSIYEH = 0xFBFD,

    /* PMT START URDU */
    R_TTEH = 0xFB67,
    R_DDAL = 0xFB89,
    R_RREH = 0xFB8D,
    R_NOON_GHUNNA = 0xFB9F,
    R_HEH_DOCHASHMEE = 0xFBAB,
    R_HEH_GOAL = 0xFBA7,
    R_YEH_BARREE = 0xFBAF,
    R_YEH_BARREE_WITH_HAMZA_ABOVE = 0xFBB1,

    R_HAMZA_ON_YEH_WITH_ALEF = 0xFBEB,
    R_HAMZA_ON_YEH_WITH_WAW = 0xFBEF,
    R_HAMZA_ON_YEH_WITH_JEEM = 0xFC00,
    R_HAMZA_ON_YEH_WITH_HAH = 0xFC01,
    R_HAMZA_ON_YEH_WITH_MEEM = 0xFC66,
    R_HAMZA_ON_YEH_WITH_ALEF_MAKSURA = 0xFC68,
    R_HAMZA_ON_YEH_WITH_YEH = 0xFC69,
    R_HAMZA_ON_YEH_WITH_REH = 0xFC64,
    R_HAMZA_ON_YEH_WITH_ZAIN = 0xFC65,
    R_HAMZA_ON_YEH_WITH_NOON = 0xFC67,

    R_BEH_WITH_JEEM = 0xFC05,
    R_BEH_WITH_HAH = 0xFC06,
    R_BEH_WITH_KHAH = 0xFC07,
    R_BEH_WITH_MEEM = 0xFC6C,
    R_BEH_WITH_ALEF_MAKSURA = 0xFC6E,
    R_BEH_WITH_YEH = 0xFC6F,
    R_BEH_WITH_REH = 0xFC6A,
    R_BEH_WITH_ZAIN = 0xFC6B,
    R_BEH_WITH_NOON = 0xFC6D,
    R_BEH_WITH_KHAH_WITH_YEH = 0xFD9E,
    R_BEH_WITH_HAH_WITH_YEH = 0xFDC2,

    R_TEH_WITH_JEEM = 0xFC0B,
    R_TEH_WITH_HAH = 0xFC0C,
    R_TEH_WITH_KHAH = 0xFC0D,
    R_TEH_WITH_MEEM = 0xFC72,
    R_TEH_WITH_ALEF_MAKSURA = 0xFC74,
    R_TEH_WITH_YEH = 0xFC75,
    R_TEH_WITH_REH = 0xFC70,
    R_TEH_WITH_ZAIN = 0xFC71,
    R_TEH_WITH_NOON = 0xFC73,
    R_TEH_WITH_HAH_WITH_JEEM = 0xFD51,
    R_TEH_WITH_JEEM_WITH_YEH = 0xFD9F,
    R_TEH_WITH_JEEM_WITH_ALEF_MAKSURA = 0xFDA0,
    R_TEH_WITH_KHAH_WITH_YEH = 0xFDA1,
    R_TEH_WITH_KHAH_WITH_ALEF_MAKSURA = 0xFDA2,
    R_TEH_WITH_MEEM_WITH_YEH = 0xFDA3,
    R_TEH_WITH_MEEM_WITH_ALEF_MAKSURA = 0xFDA4,

    R_THEH_WITH_JEEM = 0xFC11,
    R_THEH_WITH_MEEM = 0xFC12,
    R_THEH_WITH_ALEF_MAKSURA = 0xFC13,
    R_THEH_WITH_YEH = 0xFC14,
    R_THEH_WITH_REH = 0xFC76,
    R_THEH_WITH_ZAIN = 0xFC77,
    R_THEH_WITH_NOON = 0xFC79,

    R_JEEM_WITH_HAH = 0xFC15,
    R_JEEM_WITH_MEEM = 0xFC16,
    R_JEEM_WITH_ALEF_MAKSURA = 0xFD1D,
    R_JEEM_WITH_YEH = 0xFD1E,
    R_JEEM_WITH_MEEM_WITH_HAH = 0xFD58,
    R_JEEM_WITH_MEEM_WITH_YEH = 0xFDA5,
    R_JEEM_WITH_HAH_WITH_ALEF_MAKSURA = 0xFDA6,
    R_JEEM_WITH_MEEM_WITH_ALEF_MAKSURA = 0xFDA7,
    R_JEEM_WITH_HAH_WITH_YEH = 0xFDBE,

    R_HAH_WITH_JEEM = 0xFC17,
    R_HAH_WITH_MEEM = 0xFC18,
    R_HAH_WITH_ALEF_MAKSURA = 0xFD1B,
    R_HAH_WITH_YEH = 0xFD1C,
    R_HAH_WITH_MEEM_WITH_YEH = 0xFD5A,
    R_HAH_WITH_MEEM_WITH_ALEF_MAKSURA = 0xFD5B,
    R_HAH_WITH_JEEM_WITH_YEH = 0xFDBF,

    R_KHAH_WITH_JEEM = 0xFC19,
    R_KHAH_WITH_HAH = 0xFC1A,
    R_KHAH_WITH_MEEM = 0xFC1B,
    R_KHAH_WITH_ALEF_MAKSURA = 0xFD1F,
    R_KHAH_WITH_YEH = 0xFD20,

    R_SEEN_WITH_JEEM = 0xFC1C,
    R_SEEN_WITH_HAH = 0xFC1D,
    R_SEEN_WITH_KHAH = 0xFC1E,
    R_SEEN_WITH_MEEM = 0xFC1F,
    R_SEEN_WITH_ALEF_MAKSURA = 0xFD17,
    R_SEEN_WITH_YEH = 0xFD18,
    R_SEEN_WITH_REH = 0xFD2A,
    R_SEEN_WITH_JEEM_WITH_ALEF_MAKSURA = 0xFD5E,
    R_SEEN_WITH_MEEM_WITH_HAH = 0xFD5F,
    R_SEEN_WITH_MEEM_WITH_MEEM = 0xFD62,
    R_SEEN_WITH_KHAH_WITH_ALEF_MAKSURA = 0xFDA8,
    R_SEEN_WITH_KHAH_WITH_YEH = 0xFDC6,

    R_SHEEN_WITH_HEH = 0xFCEA,
    R_SHEEN_WITH_ALEF_MAKSURA = 0xFD19,
    R_SHEEN_WITH_YEH = 0xFD20,
    R_SHEEN_WITH_JEEM = 0xFD25,
    R_SHEEN_WITH_HAH = 0xFD26,
    R_SHEEN_WITH_KHAH = 0xFD27,
    R_SHEEN_WITH_MEEM = 0xFD28,
    R_SHEEN_WITH_REH = 0xFD29,
    R_SHEEN_WITH_HAH_WITH_MEEM = 0xFD67,
    R_SHEEN_WITH_JEEM_WITH_YEH = 0xFD69,
    R_SHEEN_WITH_MEEM_WITH_KHAH = 0xFD6A,
    R_SHEEN_WITH_MEEM_WITH_MEEM = 0xFD6C,
    R_SHEEN_WITH_HAH_WITH_YEH = 0xFDAA,

    R_SAD_WITH_HAH = 0xFC20,
    R_SAD_WITH_MEEM = 0xFC21,
    R_SAD_WITH_ALEF_MAKSURA = 0xFD21,
    R_SAD_WITH_YEH = 0xFD22,
    R_SAD_WITH_REH = 0xFD2B,
    R_SAD_WITH_HAH_WITH_HAH = 0xFD64,
    R_SAD_WITH_MEEM_WITH_MEEM = 0xFD66,
    R_SAD_WITH_HAH_WITH_YEH = 0xFDA9,

    R_DAD_WITH_JEEM = 0xFC22,
    R_DAD_WITH_HAH = 0xFC23,
    R_DAD_WITH_KHAH = 0xFC24,
    R_DAD_WITH_MEEM = 0xFC25,
    R_DAD_WITH_ALEF_MAKSURA = 0xFD23,
    R_DAD_WITH_YEH = 0xFD24,
    R_DAD_WITH_REH = 0xFD2C,
    R_DAD_WITH_HAH_WITH_ALEF_MAKSURA = 0xFD6E,
    R_DAD_WITH_KHAH_WITH_MEEM = 0xFD6F,
    R_DAD_WITH_HAH_WITH_YEH = 0xFDAB,

    R_TAH_WITH_HAH = 0xFC26,
    R_TAH_WITH_MEEM = 0xFC27,
    R_TAH_WITH_ALEF_MAKSURA = 0xFD11,
    R_TAH_WITH_YEH = 0xFD12,
    R_TAH_WITH_MEEM_WITH_HAH = 0xFD71,
    R_TAH_WITH_MEEM_WITH_YEH = 0xFD74,

    R_ZAH_WITH_MEEM = 0xFC28,

    R_AIN_WITH_JEEM = 0xFC29,
    R_AIN_WITH_MEEM = 0xFC2A,
    R_AIN_WITH_ALEF_MAKSURA = 0xFD13,
    R_AIN_WITH_YEH = 0xFD14,
    R_AIN_WITH_JEEM_WITH_MEEM = 0xFD75,
    R_AIN_WITH_MEEM_WITH_MEEM = 0xFD76,
    R_AIN_WITH_MEEM_WITH_ALEF_MAKSURA = 0xFD78,
    R_AIN_WITH_MEEM_WITH_YEH = 0xFDB6,

    R_GHAIN_WITH_JEEM = 0xFC2B,
    R_GHAIN_WITH_MEEM = 0xFC2C,
    R_GHAIN_WITH_ALEF_MAKSURA = 0xFD15,
    R_GHAIN_WITH_YEH = 0xFD16,
    R_GHAIN_WITH_MEEM_WITH_MEEM = 0xFD79,
    R_GHAIN_WITH_MEEM_WITH_YEH = 0xFD7A,
    R_GHAIN_WITH_MEEM_WITH_ALEF_MAKSURA = 0xFD7B,

    R_FEH_WITH_JEEM = 0xFC2D,
    R_FEH_WITH_HAH = 0xFC2E,
    R_FEH_WITH_KHAH = 0xFC2F,
    R_FEH_WITH_MEEM = 0xFC30,
    R_FEH_WITH_ALEF_MAKSURA = 0xFC7C,
    R_FEH_WITH_YEH = 0xFC7D,
    R_FEH_WITH_KHAH_WITH_MEEM = 0xFD7C,
    R_FEH_WITH_MEEM_WITH_YEH = 0xFDC1,

    R_QAF_WITH_HAH = 0xFC33,
    R_QAF_WITH_MEEM = 0xFC34,
    R_QAF_WITH_ALEF_MAKSURA = 0xFC7E,
    R_QAF_WITH_YEH = 0xFC7F,
    R_QAF_WITH_MEEM_WITH_HAH = 0xFD7E,
    R_QAF_WITH_MEEM_WITH_MEEM = 0xFD7F,
    R_QAF_WITH_MEEM_WITH_YEH = 0xFDB2,

    R_KAF_WITH_ALEF = 0xFC80,
    R_KAF_WITH_JEEM = 0xFC38,
    R_KAF_WITH_HAH = 0xFC39,
    R_KAF_WITH_KHAH = 0xFC3A,
    R_KAF_WITH_LAM = 0xFC81,
    R_KAF_WITH_MEEM = 0xFC82,
    R_KAF_WITH_ALEF_MAKSURA = 0xFC83,
    R_KAF_WITH_YEH = 0xFC84,
    R_KAF_WITH_MEEM_WITH_YEH = 0xFCB7,
    R_KAF_WITH_MEEM_WITH_MEEM = 0xFCBB,

    R_LAM_WITH_JEEM = 0xFC3F,
    R_LAM_WITH_HAH = 0xFC40,
    R_LAM_WITH_KHAH = 0xFC41,
    R_LAM_WITH_MEEM = 0xFC85,
    R_LAM_WITH_ALEF_MAKSURA = 0xFC86,
    R_LAM_WITH_YEH = 0xFC87,
    R_LAM_WITH_HAH_WITH_MEEM = 0xFD80,
    R_LAM_WITH_HAH_WITH_YEH = 0xFD81,
    R_LAM_WITH_HAH_WITH_ALEF_MAKSURA = 0xFD82,
    R_LAM_WITH_JEEM_WITH_JEEM = 0xFD84,
    R_LAM_WITH_KHAH_WITH_MEEM = 0xFD85,
    R_LAM_WITH_MEEM_WITH_HAH = 0xFD87,
    R_LAM_WITH_JEEM_WITH_YEH = 0xFDAC,
    R_LAM_WITH_MEEM_WITH_YEH = 0xFDAD,
    R_LAM_WITH_JEEM_WITH_MEEM = 0xFDBC,

    R_MEEM_WITH_JEEM = 0xFC45,
    R_MEEM_WITH_HAH = 0xFC46,
    R_MEEM_WITH_KHAH = 0xFC47,
    R_MEEM_WITH_MEEM = 0xFC89,
    R_MEEM_WITH_ALEF_MAKSURA = 0xFC49,
    R_MEEM_WITH_YEH = 0xFC4A,
    R_MEEM_WITH_ALEF = 0xFC88,
    R_MEEM_WITH_HAH_WITH_YEH = 0xFD8B,
    R_MEEM_WITH_MEEM_WITH_YEH = 0xFDB1,
    R_MEEM_WITH_KHAH_WITH_YEH = 0xFDB9,
    R_MEEM_WITH_JEEM_WITH_YEH = 0xFDC0,

    R_NOON_WITH_JEEM = 0xFC4B,
    R_NOON_WITH_HAH = 0xFC4C,
    R_NOON_WITH_KHAH = 0xFC4D,
    R_NOON_WITH_MEEM = 0xFC8C,
    R_NOON_WITH_ALEF_MAKSURA = 0xFC8E,
    R_NOON_WITH_YEH = 0xFC8F,
    R_NOON_WITH_REH = 0xFC8A,
    R_NOON_WITH_ZAIN = 0xFC8B,
    R_NOON_WITH_NOON = 0xFC8D,
    R_NOON_WITH_HAH_WITH_ALEF_MAKSURA = 0xFD96,
    R_NOON_WITH_JEEM_WITH_MEEM = 0xFD97,
    R_NOON_WITH_JEEM_WITH_ALEF_MAKSURA = 0xFD99,
    R_NOON_WITH_MEEM_WITH_YEH = 0xFD9A,
    R_NOON_WITH_MEEM_WITH_ALEF_MAKSURA = 0xFD9B,
    R_NOON_WITH_HAH_WITH_YEH = 0xFDB3,
    R_NOON_WITH_JEEM_WITH_HAH = 0xFDBD,
    R_NOON_WITH_JEEM_WITH_YEH = 0xFDC7,

    R_HEH_WITH_JEEM = 0xFC51,
    R_HEH_WITH_MEEM = 0xFC52,
    R_HEH_WITH_ALEF_MAKSURA = 0xFC53,
    R_HEH_WITH_YEH = 0xFC54,

    R_YEH_WITH_JEEM = 0xFC55,
    R_YEH_WITH_HAH = 0xFC56,
    R_YEH_WITH_KHAH = 0xFC57,
    R_YEH_WITH_MEEM = 0xFC93,
    R_YEH_WITH_ALEF_MAKSURA = 0xFC95,
    R_YEH_WITH_YEH = 0xFC96,
    R_YEH_WITH_REH = 0xFC91,
    R_YEH_WITH_ZAIN = 0xFC92,
    R_YEH_WITH_NOON = 0xFC94,
    R_YEH_WITH_MEEM_WITH_MEEM = 0xFD9C,
    R_YEH_WITH_HAH_WITH_YEH = 0xFDAE,
    R_YEH_WITH_JEEM_WITH_YEH = 0xFDAF,
    R_YEH_WITH_MEEM_WITH_YEH = 0xFDB0,
    /* PMT END URDU */
    /* Ligatures */
    R_MADDA_ON_LAMALEF = 0xFEF6,
    R_HAMZA_ON_LAMALEF = 0xFEF8,
    R_HAMZA_UNDER_LAMALEF = 0xFEFA,
    R_LAMALEF = 0xFEFC
        /* PMT END PERSIAN */
} RIGHT_JOINING_CHARACTERS_ENUM;

typedef enum
{
    /* Middle joining Form */
    M_MADDA_ON_ALEF = 0xFE82,
    M_HAMZA_ON_ALEF = 0xFE84,
    M_HAMZA_ON_WOW = 0xFE86,
    M_HAMZA_UNDER_ALEF = 0xFE88,
    M_HAMZA_ON_YEH = 0xFE8C,
    M_ALEF = 0xFE8E,
    M_BEH = 0xFE92,
    M_TEH_MARBUTA = 0xFE94,
    M_TEH = 0xFE98,
    M_THEH = 0xFE9C,
    M_JEEM = 0xFEA0,
    M_HAH = 0xFEA4,
    M_KHAH = 0xFEA8,
    M_DAL = 0xFEAA,
    M_THAL = 0xFEAC,
    M_REH = 0xFEAE,
    M_ZAIN = 0xFEB0,
    M_SEEN = 0xFEB4,
    M_SHEEN = 0xFEB8,
    M_SAD = 0xFEBC,
    M_DAD = 0xFEC0,
    M_TAH = 0xFEC4,
    M_ZAH = 0xFEC8,
    M_AIN = 0xFECC,
    M_GHAIN = 0xFED0,
    /* M_TATWEEL=0x640, same for all forms. */
    M_FEH = 0xFED4,
    M_QAF = 0xFED8,
    M_KAF = 0xFEDC,
    M_LAM = 0xFEE0,
    M_MEEM = 0xFEE4,
    M_NOON = 0xFEE8,
    M_HEH = 0xFEEC,
    M_WAW = 0xFEEE,
    M_ALEF_MAKSURA = 0xFEF0,
    /* PMT START PERSIAN */
    M_YEH = 0xFEF4,
    M_PEH = 0xFB59,
    M_TCHEH = 0xFB7D,
    M_JEH = 0xFB8B,
    M_KHEHEH = 0xFB91,
    M_GAF = 0xFB95,
    M_FARSIYEH = 0xFBFF,

    /* PMT START URDU */
    M_TTEH = 0xFB69,
    M_DDAL = 0xFB89,
    M_RREH = 0xFB8D,
    M_NOON_GHUNNA = 0xFB9F,
    M_HEH_DOCHASHMEE = 0xFBAD,
    M_HEH_GOAL = 0xFBA9,
    M_YEH_BARREE = 0xFBAF,
    M_YEH_BARREE_WITH_HAMZA_ABOVE = 0xFBB1,

    M_HAMZA_ON_YEH_WITH_ALEF = 0xFBEB,
    M_HAMZA_ON_YEH_WITH_WAW = 0xFBEF,
    M_HAMZA_ON_YEH_WITH_JEEM = 0xFC00,
    M_HAMZA_ON_YEH_WITH_HAH = 0xFC01,
    M_HAMZA_ON_YEH_WITH_MEEM = 0xFCDF,
    M_HAMZA_ON_YEH_WITH_ALEF_MAKSURA = 0xFC68,
    M_HAMZA_ON_YEH_WITH_YEH = 0xFC69,
    M_HAMZA_ON_YEH_WITH_REH = 0xFC64,
    M_HAMZA_ON_YEH_WITH_ZAIN = 0xFC65,
    M_HAMZA_ON_YEH_WITH_NOON = 0xFC67,
    M_HAMZA_ON_YEH_WITH_HEH = 0xFCE0,

    M_BEH_WITH_JEEM = 0xFC05,
    M_BEH_WITH_HAH = 0xFC06,
    M_BEH_WITH_KHAH = 0xFC07,
    M_BEH_WITH_MEEM = 0xFCE1,
    M_BEH_WITH_ALEF_MAKSURA = 0xFC6E,
    M_BEH_WITH_YEH = 0xFC6F,
    M_BEH_WITH_REH = 0xFC6A,
    M_BEH_WITH_ZAIN = 0xFC6B,
    M_BEH_WITH_NOON = 0xFC6D,
    M_BEH_WITH_HEH = 0xFCE2,

    M_TEH_WITH_JEEM = 0xFC0B,
    M_TEH_WITH_HAH = 0xFC0C,
    M_TEH_WITH_KHAH = 0xFC0D,
    M_TEH_WITH_MEEM = 0xFCE3,
    M_TEH_WITH_ALEF_MAKSURA = 0xFC74,
    M_TEH_WITH_YEH = 0xFC75,
    M_TEH_WITH_REH = 0xFC70,
    M_TEH_WITH_ZAIN = 0xFC71,
    M_TEH_WITH_NOON = 0xFC73,
    M_TEH_WITH_HEH = 0xFCE4,

    M_THEH_WITH_JEEM = 0xFC11,
    M_THEH_WITH_MEEM = 0xFCE5,
    M_THEH_WITH_ALEF_MAKSURA = 0xFC13,
    M_THEH_WITH_YEH = 0xFC14,
    M_THEH_WITH_REH = 0xFC76,
    M_THEH_WITH_ZAIN = 0xFC77,
    M_THEH_WITH_NOON = 0xFC79,
    M_THEH_WITH_HEH = 0xFCE6,

    M_JEEM_WITH_HAH = 0xFC15,
    M_JEEM_WITH_MEEM = 0xFC16,

    M_HAH_WITH_JEEM = 0xFC17,
    M_HAH_WITH_MEEM = 0xFC18,

    M_KHAH_WITH_JEEM = 0xFC19,
    M_KHAH_WITH_HAH = 0xFC1A,
    M_KHAH_WITH_MEEM = 0xFC1B,

    M_SEEN_WITH_JEEM = 0xFD34,
    M_SEEN_WITH_HAH = 0xFD35,
    M_SEEN_WITH_KHAH = 0xFD36,
    M_SEEN_WITH_MEEM = 0xFCE7,
    M_SEEN_WITH_HEH = 0xFCE8,
    M_SEEN_WITH_ALEF_MAKSURA = 0xFCFB,
    M_SEEN_WITH_YEH = 0xFCFB,

    M_SHEEN_WITH_MEEM = 0xFCE9,
    M_SHEEN_WITH_HEH = 0xFCEA,
    M_SHEEN_WITH_ALEF_MAKSURA = 0xFCFD,
    M_SHEEN_WITH_YEH = 0xFCFE,
    M_SHEEN_WITH_JEEM = 0xFD37,
    M_SHEEN_WITH_HAH = 0xFD38,
    M_SHEEN_WITH_KHAH = 0xFD39,

    M_SAD_WITH_HAH = 0xFC20,
    M_SAD_WITH_MEEM = 0xFC21,

    M_DAD_WITH_JEEM = 0xFC22,
    M_DAD_WITH_HAH = 0xFC23,
    M_DAD_WITH_KHAH = 0xFC24,
    M_DAD_WITH_MEEM = 0xFC25,

    M_TAH_WITH_HAH = 0xFC26,
    M_TAH_WITH_MEEM = 0xFD3A,

    M_ZAH_WITH_MEEM = 0xFD3B,

    M_AIN_WITH_JEEM = 0xFC29,
    M_AIN_WITH_MEEM = 0xFC2A,
    M_AIN_WITH_ALEF_MAKSURA = 0xFCF7,
    M_AIN_WITH_YEH = 0xFCF8,

    M_GHAIN_WITH_JEEM = 0xFC2B,
    M_GHAIN_WITH_MEEM = 0xFC2C,
    M_GHAIN_WITH_ALEF_MAKSURA = 0xFCF9,
    M_GHAIN_WITH_YEH = 0xFCFA,

    M_FEH_WITH_JEEM = 0xFC2D,
    M_FEH_WITH_HAH = 0xFC2E,
    M_FEH_WITH_KHAH = 0xFC2F,
    M_FEH_WITH_MEEM = 0xFC30,
    M_FEH_WITH_ALEF_MAKSURA = 0xFC7C,
    M_FEH_WITH_YEH = 0xFC7D,

    M_QAF_WITH_HAH = 0xFC33,
    M_QAF_WITH_MEEM = 0xFC34,
    M_QAF_WITH_ALEF_MAKSURA = 0xFC7E,
    M_QAF_WITH_YEH = 0xFC7F,

    M_KAF_WITH_ALEF = 0xFC80,
    M_KAF_WITH_JEEM = 0xFC38,
    M_KAF_WITH_HAH = 0xFC39,
    M_KAF_WITH_KHAH = 0xFC3A,
    M_KAF_WITH_LAM = 0xFCEB,
    M_KAF_WITH_MEEM = 0xFCEC,
    M_KAF_WITH_ALEF_MAKSURA = 0xFC83,
    M_KAF_WITH_YEH = 0xFC84,

    M_LAM_WITH_JEEM = 0xFC3F,
    M_LAM_WITH_HAH = 0xFC40,
    M_LAM_WITH_KHAH = 0xFC41,
    M_LAM_WITH_MEEM = 0xFCED,
    M_LAM_WITH_ALEF_MAKSURA = 0xFC86,
    M_LAM_WITH_YEH = 0xFC87,

    M_MEEM_WITH_JEEM = 0xFC45,
    M_MEEM_WITH_HAH = 0xFC46,
    M_MEEM_WITH_KHAH = 0xFC47,
    M_MEEM_WITH_MEEM = 0xFC89,
    M_MEEM_WITH_ALEF_MAKSURA = 0xFC49,
    M_MEEM_WITH_YEH = 0xFC4A,
    M_MEEM_WITH_ALEF = 0xFC88,

    M_NOON_WITH_JEEM = 0xFC4B,
    M_NOON_WITH_HAH = 0xFC4C,
    M_NOON_WITH_KHAH = 0xFC4D,
    M_NOON_WITH_MEEM = 0xFCEE,
    M_NOON_WITH_ALEF_MAKSURA = 0xFC8E,
    M_NOON_WITH_YEH = 0xFC8F,
    M_NOON_WITH_REH = 0xFC8A,
    M_NOON_WITH_ZAIN = 0xFC8B,
    M_NOON_WITH_NOON = 0xFC8D,
    M_NOON_WITH_HEH = 0xFCEF,

    M_HEH_WITH_JEEM = 0xFC51,
    M_HEH_WITH_MEEM = 0xFC52,
    M_HEH_WITH_ALEF_MAKSURA = 0xFC53,
    M_HEH_WITH_YEH = 0xFC54,

    M_YEH_WITH_JEEM = 0xFC55,
    M_YEH_WITH_HAH = 0xFC56,
    M_YEH_WITH_KHAH = 0xFC57,
    M_YEH_WITH_MEEM = 0xFCF0,
    M_YEH_WITH_ALEF_MAKSURA = 0xFC95,
    M_YEH_WITH_YEH = 0xFC96,
    M_YEH_WITH_REH = 0xFC91,
    M_YEH_WITH_ZAIN = 0xFC92,
    M_YEH_WITH_NOON = 0xFC94,
    M_YEH_WITH_HEH = 0xFCF1,

    M_TAH_WITH_ALEF_MAKSURA = 0xFCF5,
    M_TAH_WITH_YEH = 0xFCF6,
    /* PMT END URDU */
    /* Ligatures */
    M_MADDA_ON_LAMALEF = 0xFEF6,
    M_HAMZA_ON_LAMALEF = 0xFEF8,
    M_HAMZA_UNDER_LAMALEF = 0xFEFA,
    M_LAMALEF = 0xFEFC
        /* PMT END PERSIAN */
} MIDDLE_JOINING_CHARACTERS_ENUM;

typedef enum
{
    /* Nominal glyph Forms */
    N_HAMZA_FORM_B = 0xFE80,
    N_MADDA_ON_ALEF_FORM_B = 0xFE81,
    N_HAMZA_ON_ALEF_FORM_B = 0xFE83,
    N_HAMZA_ON_WOW_FORM_B = 0xFE85,
    N_HAMZA_UNDER_ALEF_FORM_B = 0xFE87,
    N_HAMZA_ON_YEH_FORM_B = 0xFE89,
    N_ALEF_FORM_B = 0xFE8D,
    N_BEH_FORM_B = 0xFE8F,
    N_TEH_MARBUTA_FORM_B = 0xFE93,
    N_TEH_FORM_B = 0xFE95,
    N_THEH_FORM_B = 0xFE99,
    N_JEEM_FORM_B = 0xFE9D,
    N_HAH_FORM_B = 0xFEA1,
    N_KHAH_FORM_B = 0xFEA5,
    N_DAL_FORM_B = 0xFEA9,
    N_THAL_FORM_B = 0xFEAB,
    N_REH_FORM_B = 0xFEAD,
    N_ZAIN_FORM_B = 0xFEAF,
    N_SEEN_FORM_B = 0xFEB1,
    N_SHEEN_FORM_B = 0xFEB5,
    N_SAD_FORM_B = 0xFEB9,
    N_DAD_FORM_B = 0xFEBD,
    N_TAH_FORM_B = 0xFEC1,
    N_ZAH_FORM_B = 0xFEC5,
    N_AIN_FORM_B = 0xFEC9,
    N_GHAIN_FORM_B = 0xFECD,    
    N_FEH_FORM_B = 0xFED1,
    N_QAF_FORM_B = 0xFED5,
    N_KAF_FORM_B = 0xFED9,
    N_LAM_FORM_B = 0xFEDD,
    N_MEEM_FORM_B = 0xFEE1,
    N_NOON_FORM_B = 0xFEE5,
    N_HEH_FORM_B = 0xFEE9,
    N_WAW_FORM_B = 0xFEED,
    N_ALEF_MAKSURA_FORM_B = 0xFEEF,
    N_YEH_FORM_B = 0xFEF1
} NOMINAL_CHARACTERS_FORM_B_ENUM;

typedef enum
{
    /* Nominal glyph Forms */
    N_PEH_FORM_A = 0xFB56,
    N_TCHEH_FORM_A = 0xFB7A,
    N_JEH_FORM_A = 0xFB8A,
    N_KHEHEH_FORM_A = 0xFB8E,
    N_GAF_FORM_A = 0xFB92,
    N_FARSIYEH_FORM_A = 0xFBFC,

    /* PMT START URDU */
    N_TTEH_FORM_A = 0xFB66,
    N_DDAL_FORM_A = 0xFB88,
    N_RREH_FORM_A = 0xFB8C,
    N_NOON_GHUNNA_FORM_A = 0xFB9E,
    N_HEH_DOCHASHMEE_FORM_A = 0xFBAA,
    N_HEH_GOAL_FORM_A = 0xFBA6,
    N_YEH_BARREE_FORM_A = 0xFBAE,
    N_YEH_BARREE_WITH_HAMZA_ABOVE_FORM_A = 0xFBB0
        /* PMT END URDU */
} NOMINAL_CHARACTERS_FORM_A_ENUM;

typedef struct _ligature_glyph_info
{    
    U8 nInputLen;               /* no. of input unicode values */
    U8 nOutputLen;              /* no, of output values */
    U8 language_for_ligature;
    U16 Input_glyph[ARABIC_LIGATURE_LENGTH];     /* no. of input glyph used to make conjunct */
    U16 Output_glyph[ARABIC_LIGATURE_LENGTH];    /* no. of output glyph that has to be rendered */
} LIGATURE_INFO_TABLE;

typedef struct _arabic_main_table
{
    const LIGATURE_INFO_TABLE *glyphinfo;  /* pointer to individual table */
    U16 nsize;                          /* size of individual character's array */
    U8 maxInputGlyphSize;               /* max input of glyph it can handle */
} ARABIC_MAIN_TABLE;
extern BOOL WhetherRightJoinCausingChar(U16 pre_char, U16 pre2_char);
extern BOOL WhetherLeftJoinCausingChar(U16 post_char, U16 post2_char);
extern ARABIC_JOIN_TYPE_ENUM ArabicGetJoinType(U16 ch);

extern void ArabicShapeEngine(U8 , PU16 , PU16 );
extern S32 arabic_ligature_rules(U8, PU16, PU16, PU16, PU16, PU16, MMI_BOOL);
extern void ArabicShapeEngine2(U8, PU16, PU16, PU16, PU16);
extern MMI_BOOL arabic_shape_rules(U16 length, PU16 text_buffer);
#endif /* __MMI_ARSHAPING_ENGINE__ */ 


