#ifndef __VAPP_MSG_NCENTER_GPROT_H_
#define __VAPP_MSG_NCENTER_GPROT_H_

typedef enum
{
    VAPP_MSG_NCENTER_MESSAGE_CELL_BEGIN,
    VAPP_MSG_NCENTER_UNREAD_CELL,
    VAPP_MSG_NCENTER_UNSEND_CELL,    
    VAPP_MSG_NCENTER_FULL_SMS_SIM1_CELL,
    
#if (MMI_MAX_SIM_NUM >= 2)
    VAPP_MSG_NCENTER_FULL_SMS_SIM2_CELL,
#endif /* MMI_MAX_SIM_NUM >= 2 */

#if (MMI_MAX_SIM_NUM >= 3)
    VAPP_MSG_NCENTER_FULL_SMS_SIM3_CELL,
#endif /* MMI_MAX_SIM_NUM >= 3 */

#if (MMI_MAX_SIM_NUM >= 4)
    VAPP_MSG_NCENTER_FULL_SMS_SIM4_CELL,
#endif /* MMI_MAX_SIM_NUM >= 4 */

    VAPP_MSG_NCENTER_FULL_SMS_PHONE_CELL,
#ifdef __MMI_SMS_TCARD_STORAGE_SUPPORT__
    VAPP_MSG_NCENTER_FULL_SMS_CARD_CELL,
#endif /* __MMI_SMS_TCARD_STORAGE_SUPPORT__ */

#ifdef __MMI_MMS_IN_UM__
    VAPP_MSG_NCENTER_FULL_MMS_PHONE_CELL,
    VAPP_MSG_NCENTER_FULL_MMS_CARD_CELL,
#endif /* __MMI_MMS_IN_UM__ */

#ifdef __MMI_PROV_IN_UM__
    VAPP_MSG_NCENTER_FULL_PRO_CELL,
#endif /* __MMI_PROV_IN_UM__ */
    VAPP_MSG_NCENTER_MESSAGE_CELL_END,
    
    VAPP_MSG_NCENTER_WAP_PUSH_CELL_BEGIN,
    VAPP_MSG_NCENTER_WAP_PUSH_CELL,
    VAPP_MSG_NCENTER_WAP_PUSH_CELL_END,

	VAPP_MSG_NCENTER_SMS_WAITING_CELL_BEGIN = 50,
	VAPP_MSG_NCENTER_SMS_WAITING_CELL_END = 74,

    VAPP_MSG_NCENTER_CCA_CELL_BEGIN,
    VAPP_MSG_NCENTER_CCA_CELL,
    VAPP_MSG_NCENTER_CCA_CELL_END,

	VAPP_MSG_NCENTER_SIZE
} VappMsgNCenterCellMenu;

#endif
