#ifdef __COSMOS_MMI_PACKAGE__ 
#include "mmi_features.h"
#include "custresdef.h"

<?xml version="1.0" encoding="UTF-8"?>

#ifndef __CERTMAN_SUPPORT__
<APP id="VAPP_CERTMAN"></APP>
#else
<APP id="VAPP_CERTMAN" name="STR_ID_VAPP_CERTMAN" type="venus">

#ifdef __CERTMAN_SUPPORT__

    <MEMORY base="358400" />
    
    <!--------------------------------------Include Area-------------------------------------->
    <INCLUDE file="GlobalResDef.h,GlobalMenuItems.h" />
    <INCLUDE file="SettingResDef.h" />
    
    <!-----------------------------------------------------String Resource Area----------------------------------------------------->
    <STRING id="STR_ID_CERTIFICATE_MANAGER"/>
    <STRING id="STR_ID_VAPP_CERTMAN_CERTIFICATE_LABEL"/>
    <STRING id="STR_ID_VAPP_CERTMAN_CERTIFICATE_INFO"/>
    <STRING id="STR_ID_VAPP_CERTMAN_FILE_CONTAINS"/>
    <STRING id="STR_ID_VAPP_CERTMAN_CERT_SERIAL_NO"/>
    <STRING id="STR_ID_VAPP_CERTMAN_CERT_VERSION"/>
    <STRING id="STR_ID_VAPP_CERTMAN_CERT_ISSUER"/>
    <STRING id="STR_ID_VAPP_CERTMAN_CERT_VALID_FROM"/>
    <STRING id="STR_ID_VAPP_CERTMAN_CERT_VALID_UPTO"/>
    <STRING id="STR_ID_VAPP_CERTMAN_CERT_FINGER_PRINT"/>
    <STRING id="STR_ID_VAPP_CERTMAN_CERT_TYPE"/>    
    <STRING id="STR_ID_VAPP_CERTMAN_CERTTYPE_X509"/>
    <STRING id="STR_ID_VAPP_CERTMAN_KP_ALL"/>
    <STRING id="STR_ID_VAPP_CERTMAN_KP_SERVER_AUTH"/>
    <STRING id="STR_ID_VAPP_CERTMAN_KP_CLIENT_AUTH"/>
    <STRING id="STR_ID_VAPP_CERTMAN_KP_CODE_SIGNING"/>
    <STRING id="STR_ID_VAPP_CERTMAN_KP_EMAIL_PROTECTION"/>
    <STRING id="STR_ID_VAPP_CERTMAN_KP_IPSEC_ENDSYSTEM"/>
    <STRING id="STR_ID_VAPP_CERTMAN_KP_IPSEC_TUNNEL"/>
    <STRING id="STR_ID_VAPP_CERTMAN_KP_IPSEC_USER"/>
    <STRING id="STR_ID_VAPP_CERTMAN_KP_TIME_STAMPING"/>
    <STRING id="STR_ID_VAPP_CERTMAN_KP_OCSP_SIGNING"/>
    <STRING id="STR_ID_VAPP_CERTMAN_CERTIFICATE_KEY_USAGE"/>
    <STRING id="STR_ID_VAPP_CERTMAN_AUTHORITY_CERTS"/>
    <STRING id="STR_ID_VAPP_CERTMAN_USER_CERT"/>
    <STRING id="STR_ID_VAPP_CERTMAN_PERSONAL_CERTIFICATE"/>
    <STRING id="STR_ID_VAPP_CERTMAN_CERTIFICATE_DETAILS"/>
    
    <STRING id="STR_ID_VAPP_CERTMAN_WARN_DELETE_CERT"/>
    <STRING id="STR_ID_VAPP_CERTMAN_NO_CERT"/>
    <STRING id="STR_ID_VAPP_CERTMAN_PASSWD_DONT_MATCH"/>
    <STRING id="STR_ID_VAPP_CERTMAN_INSTALLATION_FAILED"/>
    <STRING id="STR_ID_VAPP_CERTMAN_CERT_INSTALLED"/>
    <STRING id="STR_ID_VAPP_CERTMAN_CERT_EXISTS"/>
    <STRING id="STR_ID_VAPP_CERTMAN_WARN_INVALID_CERT"/>
    <STRING id="STR_ID_VAPP_CERTMAN_WARN_ACCEPT_CERT"/>
    <STRING id="STR_ID_VAPP_CERTMAN_USE_PERSONAL_CERT"/>
    <STRING id="STR_ID_VAPP_CERTMAN_CERTIFICATES"/>
    <STRING id="STR_ID_VAPP_CERTMAN_INPUT_PASSWORD"/>
    <STRING id="STR_ID_VAPP_CERTMAN_INPUT_PASS_AGAIN"/>
    <STRING id="STR_ID_VAPP_CERTMAN_INCORRECT_PASSWORD"/>
    <STRING id="STR_ID_VAPP_CERTMAN_NO_CERTS"/>
    <STRING id="STR_ID_VAPP_CERTMAN_WARN_VALIDITY"/>
    <STRING id="STR_ID_VAPP_CERTMAN_ACCEPT_CERT"/>
    <STRING id="STR_ID_VAPP_CERTMAN_ACCEPT_CERT_THIS_TIME"/>
    <STRING id="STR_ID_VAPP_CERTMAN_WARN_INSTALL"/>
    <STRING id="STR_ID_VAPP_CERTMAN_CERTIFICATE_PRIVATE_KEY_PROTECTION"/>
    <STRING id="STR_ID_VAPP_CERTMAN_PASS_ABRV"/>
    <STRING id="STR_ID_VAPP_CERTMAN_CERTIFICATE_CONFIRM_PWD"/>
    <STRING id="STR_ID_VAPP_CERTMAN_MISMATCHED"/>
    <STRING id="STR_ID_VAPP_CERTMAN_PERSONAL_CERTS"/>

    <STRING id="STR_ID_VAPP_CERTMAN_MEMORY_FULL"/>
    <STRING id="STR_ID_VAPP_CERTMAN_INVALID_CONTEXT"/>
    <STRING id="STR_ID_VAPP_CERTMAN_INVALID_ENCODING"/>
    <STRING id="STR_ID_VAPP_CERTMAN_NEED_PASSWORD"/>
    <STRING id="STR_ID_VAPP_CERTMAN_INVALID_JOB"/>
    <STRING id="STR_ID_VAPP_CERTMAN_INVALID_CERT_ID"/>

    <STRING id="STR_ID_VAPP_CERTMAN_LABEL_EXISTS"/>
    <STRING id="STR_ID_VAPP_CERTMAN_INVALID_LABEL"/>
    <STRING id="STR_ID_VAPP_CERTMAN_INVALID_CERT_GROUP"/>
    <STRING id="STR_ID_VAPP_CERTMAN_INVALID_KEY_PURPOSE"/>
    <STRING id="STR_ID_VAPP_CERTMAN_CERTIFICATE_NOT_FOUND"/>
    <STRING id="STR_ID_VAPP_CERTMAN_INVALID_INPUT"/>
    <STRING id="STR_ID_VAPP_CERTMAN_TOO_MANY_CERT"/>
    <STRING id="STR_ID_VAPP_CERTMAN_READ_ONLY"/>
    <STRING id="STR_ID_VAPP_CERTMAN_CORRUPTED_FILE"/>
    <STRING id="STR_ID_VAPP_CERTMAN_CERT_IN_USE"/>
    <STRING id="STR_ID_VAPP_CERTMAN_FILE_NOT_FOUND"/>
    <STRING id="STR_ID_VAPP_CERTMAN_MAX_LIMIT"/>
    <STRING id="STR_ID_VAPP_CERTMAN_WARN_ACCEPT_ALWAYS"/>
    <STRING id="STR_ID_VAPP_CERTMAN_CONFIRM"/>
    <STRING id="STR_ID_VAPP_CERTMAN_CERT_PASSWORD"/>
    <STRING id="STR_ID_VAPP_CERTMAN_ALGORITHM"/>
    <STRING id="STR_ID_VAPP_CERTMAN_NEXT"/>    
    <STRING id="STR_ID_VAPP_CERTMAN_PREV"/>
    <STRING id="STR_ID_VAPP_CERTMAN_EXPIRED"/>
    <STRING id="STR_ID_VAPP_CERTMAN_CONTINUE"/>  
    <STRING id="STR_ID_VAPP_CERTMAN_CERTIFICATE_PRIV_KEY_CONFIRMATION"/>  
    <STRING id="STR_ID_VAPP_CERTMAN_COLON"/>

    <!------------------------------------------------------Menu Resource Area------------------------------------------------------>

    <MENUITEM id="MENU_CERTIFICATE_MANAGER" str="STR_ID_CERTIFICATE_MANAGER"/>

    <!------------------------------------------------------FMGR options------------------------------------------------------>

    <MENUITEM id="MENU_FMGR_CER_OPTION_INSTALL" str="STR_GLOBAL_INSTALL"/>
    <FILE_TYPES>
        <FILE_OPTION_HDLR option="MENU_FMGR_CER_OPTION_INSTALL" handler="vapp_certman_install_handler"/>
            <FILE_GROUP_TYPE type_id="FMGR_GROUP_CERT" small_icon="IMG_ID_CERTMAN_FILE_TYPE" large_icon="IMG_ID_CERTMAN_FILE_TYPE" option="MENU_ID_FMGR_CERT_TYPE_OPTIONS">
                <FILE_TYPE type_id="FMGR_TYPE_P12" extension="P12" large_icon="IMG_ID_CERTMAN_FILE_TYPE"/>
                <FILE_TYPE type_id="FMGR_TYPE_CER" extension="CER" large_icon="IMG_ID_CERTMAN_FILE_TYPE"/>
                <FILE_TYPE type_id="FMGR_TYPE_PFX" extension="PFX" large_icon="IMG_ID_CERTMAN_FILE_TYPE"/>
                <FILE_TYPE type_id="FMGR_TYPE_DER" extension="DER" large_icon="IMG_ID_CERTMAN_FILE_TYPE"/>
                <FILE_TYPE type_id="FMGR_TYPE_PEM" extension="PEM" large_icon="IMG_ID_CERTMAN_FILE_TYPE"/>
                <FILE_TYPE type_id="FMGR_TYPE_P7B" extension="P7B" large_icon="IMG_ID_CERTMAN_FILE_TYPE"/>
                <FILE_TYPE type_id="FMGR_TYPE_CRT" extension="CRT" large_icon="IMG_ID_CERTMAN_FILE_TYPE"/>
                <FILE_TYPE type_id="FMGR_TYPE_SPC" extension="SPC" large_icon="IMG_ID_CERTMAN_FILE_TYPE"/>
            </FILE_GROUP_TYPE>
    </FILE_TYPES>
    
    <MENU id="MENU_ID_FMGR_CERT_TYPE_OPTIONS" type="OPTION" str="STR_GLOBAL_OPTIONS">
        <MENUITEM_ID>MENU_FMGR_CER_OPTION_INSTALL</MENUITEM_ID>     
    </MENU>

    <!-----------------------------------------------------Image Resource Area------------------------------------------------------>
    
    <IMAGE id="IMG_ID_CERTMAN_AUTH_CERT">RES_IMG_ROOT"\\\\CMGR\\\\TAB\\\\CM_AUTH.png"</IMAGE>
    <IMAGE id="IMG_ID_CERTMAN_USER_CERT">RES_IMG_ROOT"\\\\CMGR\\\\TAB\\\\CM_USER.png"</IMAGE>
    <IMAGE id="IMG_ID_CERTMAN_KEY_USAGE">RES_IMG_ROOT"\\\\CMGR\\\\TOOLBAR\\\\CM_KEY_USAGE.png"</IMAGE>
    <IMAGE id="IMG_ID_CERTMAN_READ_ONLY">RES_IMG_ROOT"\\\\CMGR\\\\LIST\\\\CM_READ_ONLY.png"</IMAGE>
    <IMAGE id="IMG_ID_CERTMAN_FILE_TYPE">RES_IMG_ROOT"\\\\FMGR\\\\ListIcon\\\\CERT.png"</IMAGE>
    
    
#endif /* __CERTMAN_SUPPORT__ */

</APP>

#endif
#endif /* __COSMOS_MMI_PACKAGE__  */