#ifndef _FMR_TRC_GEN_H_
#define _FMR_TRC_GEN_H_

// FM_INFO_FM_COMMON_POWER_ON
#define FM_INFO_FM_COMMON_POWER_ON_size NULL
#define FM_INFO_FM_COMMON_POWER_ON FM_INFO_FM_COMMON_POWER_ON__enum,FM_INFO_FM_COMMON_POWER_ON_size

// FM_INFO_FM_POWER_ON_RST
#define FM_INFO_FM_POWER_ON_RST_size NULL
#define FM_INFO_FM_POWER_ON_RST FM_INFO_FM_POWER_ON_RST__enum,FM_INFO_FM_POWER_ON_RST_size

// FM_INFO_FM_POWER_OFF
#define FM_INFO_FM_POWER_OFF_size NULL
#define FM_INFO_FM_POWER_OFF FM_INFO_FM_POWER_OFF__enum,FM_INFO_FM_POWER_OFF_size

// FM_INFO_FM_CHIP_ID
#define FM_INFO_FM_CHIP_ID_size "d"
#define FM_INFO_FM_CHIP_ID FM_INFO_FM_CHIP_ID__enum,FM_INFO_FM_CHIP_ID_size

// FM_INFO_FM_SET_FREQ
#define FM_INFO_FM_SET_FREQ_size "d"
#define FM_INFO_FM_SET_FREQ FM_INFO_FM_SET_FREQ__enum,FM_INFO_FM_SET_FREQ_size

// FM_INFO_FM_IS_VALID_STOP
#define FM_INFO_FM_IS_VALID_STOP_size "ƒd"
#define FM_INFO_FM_IS_VALID_STOP FM_INFO_FM_IS_VALID_STOP__enum,FM_INFO_FM_IS_VALID_STOP_size

// FM_INFO_FM_HW_SEARCH_S
#define FM_INFO_FM_HW_SEARCH_S_size "„d"
#define FM_INFO_FM_HW_SEARCH_S FM_INFO_FM_HW_SEARCH_S__enum,FM_INFO_FM_HW_SEARCH_S_size

// FM_INFO_FM_HW_SEARCH_E
#define FM_INFO_FM_HW_SEARCH_E_size "d"
#define FM_INFO_FM_HW_SEARCH_E FM_INFO_FM_HW_SEARCH_E__enum,FM_INFO_FM_HW_SEARCH_E_size

// FM_INFO_FM_PAMD_LVL
#define FM_INFO_FM_PAMD_LVL_size "‚d"
#define FM_INFO_FM_PAMD_LVL FM_INFO_FM_PAMD_LVL__enum,FM_INFO_FM_PAMD_LVL_size

// FM_INFO_FM_RSSI_LVL
#define FM_INFO_FM_RSSI_LVL_size "‚d"
#define FM_INFO_FM_RSSI_LVL FM_INFO_FM_RSSI_LVL__enum,FM_INFO_FM_RSSI_LVL_size

// FM_INFO_FM_MR
#define FM_INFO_FM_MR_size "d"
#define FM_INFO_FM_MR FM_INFO_FM_MR__enum,FM_INFO_FM_MR_size

// FM_INFO_FM_ITEM_INFO
#define FM_INFO_FM_ITEM_INFO_size "ƒd"
#define FM_INFO_FM_ITEM_INFO FM_INFO_FM_ITEM_INFO__enum,FM_INFO_FM_ITEM_INFO_size

// FM_INFO_SeekEliminate
#define FM_INFO_SeekEliminate_size "ƒd"
#define FM_INFO_SeekEliminate FM_INFO_SeekEliminate__enum,FM_INFO_SeekEliminate_size

// FM_INFO_SortTuneRssi
#define FM_INFO_SortTuneRssi_size "‚d"
#define FM_INFO_SortTuneRssi FM_INFO_SortTuneRssi__enum,FM_INFO_SortTuneRssi_size

// FM_INFO_EMPTY_NO
#define FM_INFO_EMPTY_NO_size "d"
#define FM_INFO_EMPTY_NO FM_INFO_EMPTY_NO__enum,FM_INFO_EMPTY_NO_size

// FM_INFO_READ_DATA
#define FM_INFO_READ_DATA_size "‚d"
#define FM_INFO_READ_DATA FM_INFO_READ_DATA__enum,FM_INFO_READ_DATA_size

// FM_INFO_TuneTimes
#define FM_INFO_TuneTimes_size NULL
#define FM_INFO_TuneTimes FM_INFO_TuneTimes__enum,FM_INFO_TuneTimes_size

// FM_INFO_GetSoundTrack
#define FM_INFO_GetSoundTrack_size "d"
#define FM_INFO_GetSoundTrack FM_INFO_GetSoundTrack__enum,FM_INFO_GetSoundTrack_size

// FM_INFO_GetRSSITH
#define FM_INFO_GetRSSITH_size "‚d"
#define FM_INFO_GetRSSITH FM_INFO_GetRSSITH__enum,FM_INFO_GetRSSITH_size

// FM_INFO_HEX2DB
#define FM_INFO_HEX2DB_size "‚d"
#define FM_INFO_HEX2DB FM_INFO_HEX2DB__enum,FM_INFO_HEX2DB_size

// FM_INFO_DB2HEX
#define FM_INFO_DB2HEX_size "‚d"
#define FM_INFO_DB2HEX FM_INFO_DB2HEX__enum,FM_INFO_DB2HEX_size

// FM_INFO_FM_CQI
#define FM_INFO_FM_CQI_size "ƒd"
#define FM_INFO_FM_CQI FM_INFO_FM_CQI__enum,FM_INFO_FM_CQI_size

// FM_INFO_ROM_VERSION
#define FM_INFO_ROM_VERSION_size "‚d"
#define FM_INFO_ROM_VERSION FM_INFO_ROM_VERSION__enum,FM_INFO_ROM_VERSION_size

// FM_INFO_PATCH_VERSION
#define FM_INFO_PATCH_VERSION_size "d"
#define FM_INFO_PATCH_VERSION FM_INFO_PATCH_VERSION__enum,FM_INFO_PATCH_VERSION_size

// FM_INFO_SCAN_CQI
#define FM_INFO_SCAN_CQI_size "ƒd"
#define FM_INFO_SCAN_CQI FM_INFO_SCAN_CQI__enum,FM_INFO_SCAN_CQI_size

// FM_INFO_SOFT_MUTE_TUNE_CQI
#define FM_INFO_SOFT_MUTE_TUNE_CQI_size "‰d"
#define FM_INFO_SOFT_MUTE_TUNE_CQI FM_INFO_SOFT_MUTE_TUNE_CQI__enum,FM_INFO_SOFT_MUTE_TUNE_CQI_size

// FM_INFO_DENSENSE_CHANNEL
#define FM_INFO_DENSENSE_CHANNEL_size "‚d"
#define FM_INFO_DENSENSE_CHANNEL FM_INFO_DENSENSE_CHANNEL__enum,FM_INFO_DENSENSE_CHANNEL_size

// FM_INFO_NOISE_FLOOR
#define FM_INFO_NOISE_FLOOR_size "‚d"
#define FM_INFO_NOISE_FLOOR FM_INFO_NOISE_FLOOR__enum,FM_INFO_NOISE_FLOOR_size

// FM_INFO_NOISE_FLOOR_DETECT
#define FM_INFO_NOISE_FLOOR_DETECT_size "‚d"
#define FM_INFO_NOISE_FLOOR_DETECT FM_INFO_NOISE_FLOOR_DETECT__enum,FM_INFO_NOISE_FLOOR_DETECT_size

// FM_INFO_SCAN_CHANNEL_NUM
#define FM_INFO_SCAN_CHANNEL_NUM_size "‚d"
#define FM_INFO_SCAN_CHANNEL_NUM FM_INFO_SCAN_CHANNEL_NUM__enum,FM_INFO_SCAN_CHANNEL_NUM_size

// FM_I2SIN_CheckDataValid_TIMEOUT
#define FM_I2SIN_CheckDataValid_TIMEOUT_size NULL
#define FM_I2SIN_CheckDataValid_TIMEOUT FM_I2SIN_CheckDataValid_TIMEOUT__enum,FM_I2SIN_CheckDataValid_TIMEOUT_size

// FM_I2SIN_CheckDataValid_ERROR
#define FM_I2SIN_CheckDataValid_ERROR_size NULL
#define FM_I2SIN_CheckDataValid_ERROR FM_I2SIN_CheckDataValid_ERROR__enum,FM_I2SIN_CheckDataValid_ERROR_size

// FM_INFO_SFI_VOLTAGE_UNKNOWN
#define FM_INFO_SFI_VOLTAGE_UNKNOWN_size NULL
#define FM_INFO_SFI_VOLTAGE_UNKNOWN FM_INFO_SFI_VOLTAGE_UNKNOWN__enum,FM_INFO_SFI_VOLTAGE_UNKNOWN_size

// FM_INFO_SFI_CLK_NOT104Mor78M
#define FM_INFO_SFI_CLK_NOT104Mor78M_size NULL
#define FM_INFO_SFI_CLK_NOT104Mor78M FM_INFO_SFI_CLK_NOT104Mor78M__enum,FM_INFO_SFI_CLK_NOT104Mor78M_size

// FM_API_ENTRANCE
#define FM_API_ENTRANCE_size "d"
#define FM_API_ENTRANCE FM_API_ENTRANCE__enum,FM_API_ENTRANCE_size

// FM_API_EXIT
#define FM_API_EXIT_size "d"
#define FM_API_EXIT FM_API_EXIT__enum,FM_API_EXIT_size

// FMDRV_API_ENTRANCE
#define FMDRV_API_ENTRANCE_size "d"
#define FMDRV_API_ENTRANCE FMDRV_API_ENTRANCE__enum,FMDRV_API_ENTRANCE_size

// FMDRV_API_EXIT
#define FMDRV_API_EXIT_size "d"
#define FMDRV_API_EXIT FMDRV_API_EXIT__enum,FMDRV_API_EXIT_size

// FM_ON_SEQUENCE_CMD
#define FM_ON_SEQUENCE_CMD_size "d"
#define FM_ON_SEQUENCE_CMD FM_ON_SEQUENCE_CMD__enum,FM_ON_SEQUENCE_CMD_size

// FM_OFF_SEQUENCE_CMD
#define FM_OFF_SEQUENCE_CMD_size "d"
#define FM_OFF_SEQUENCE_CMD FM_OFF_SEQUENCE_CMD__enum,FM_OFF_SEQUENCE_CMD_size

// FM_ON_POLLING_TIMES
#define FM_ON_POLLING_TIMES_size "d"
#define FM_ON_POLLING_TIMES FM_ON_POLLING_TIMES__enum,FM_ON_POLLING_TIMES_size

// FM_READ_DATA
#define FM_READ_DATA_size "‚d"
#define FM_READ_DATA FM_READ_DATA__enum,FM_READ_DATA_size

// FM_WRITE_DATA
#define FM_WRITE_DATA_size "‚d"
#define FM_WRITE_DATA FM_WRITE_DATA__enum,FM_WRITE_DATA_size

// FM_SET_OutputDevice
#define FM_SET_OutputDevice_size "d"
#define FM_SET_OutputDevice FM_SET_OutputDevice__enum,FM_SET_OutputDevice_size

// FM_SET_OutputVolume
#define FM_SET_OutputVolume_size "‚d"
#define FM_SET_OutputVolume FM_SET_OutputVolume__enum,FM_SET_OutputVolume_size

// FM_SET_ANTENNAY_TYPE
#define FM_SET_ANTENNAY_TYPE_size "d"
#define FM_SET_ANTENNAY_TYPE FM_SET_ANTENNAY_TYPE__enum,FM_SET_ANTENNAY_TYPE_size

// FM_GET_ANTENNAY_TYPE
#define FM_GET_ANTENNAY_TYPE_size "d"
#define FM_GET_ANTENNAY_TYPE FM_GET_ANTENNAY_TYPE__enum,FM_GET_ANTENNAY_TYPE_size

// FM_RDS_INTR_ONOFF
#define FM_RDS_INTR_ONOFF_size "d"
#define FM_RDS_INTR_ONOFF FM_RDS_INTR_ONOFF__enum,FM_RDS_INTR_ONOFF_size

// FM_INTR_VALUE
#define FM_INTR_VALUE_size "d"
#define FM_INTR_VALUE FM_INTR_VALUE__enum,FM_INTR_VALUE_size

// FM_MUTE_ONOFF
#define FM_MUTE_ONOFF_size "d"
#define FM_MUTE_ONOFF FM_MUTE_ONOFF__enum,FM_MUTE_ONOFF_size

// FM_SOFTE_MUTE_ONOFF
#define FM_SOFTE_MUTE_ONOFF_size "d"
#define FM_SOFTE_MUTE_ONOFF FM_SOFTE_MUTE_ONOFF__enum,FM_SOFTE_MUTE_ONOFF_size

// FM_DELAYMS
#define FM_DELAYMS_size "d"
#define FM_DELAYMS FM_DELAYMS__enum,FM_DELAYMS_size

// FM_INFO_FM_RDS_EINT
#define FM_INFO_FM_RDS_EINT_size NULL
#define FM_INFO_FM_RDS_EINT FM_INFO_FM_RDS_EINT__enum,FM_INFO_FM_RDS_EINT_size

// FM_INFO_FM_RDS_CLR
#define FM_INFO_FM_RDS_CLR_size NULL
#define FM_INFO_FM_RDS_CLR FM_INFO_FM_RDS_CLR__enum,FM_INFO_FM_RDS_CLR_size

// FM_INFO_FM_RDS_EVENT
#define FM_INFO_FM_RDS_EVENT_size "‚d"
#define FM_INFO_FM_RDS_EVENT FM_INFO_FM_RDS_EVENT__enum,FM_INFO_FM_RDS_EVENT_size

// FM_INFO_FM_RDS_BLER_ERR
#define FM_INFO_FM_RDS_BLER_ERR_size "‚d"
#define FM_INFO_FM_RDS_BLER_ERR FM_INFO_FM_RDS_BLER_ERR__enum,FM_INFO_FM_RDS_BLER_ERR_size

// FM_INFO_FM_RDS_BLK_RST
#define FM_INFO_FM_RDS_BLK_RST_size "d"
#define FM_INFO_FM_RDS_BLK_RST FM_INFO_FM_RDS_BLK_RST__enum,FM_INFO_FM_RDS_BLK_RST_size

// FM_INFO_FM_RDS_BLOCK_DATA
#define FM_INFO_FM_RDS_BLOCK_DATA_size "…d"
#define FM_INFO_FM_RDS_BLOCK_DATA FM_INFO_FM_RDS_BLOCK_DATA__enum,FM_INFO_FM_RDS_BLOCK_DATA_size

// FM_INFO_FM_RDS_GROUP
#define FM_INFO_FM_RDS_GROUP_size "‚d"
#define FM_INFO_FM_RDS_GROUP FM_INFO_FM_RDS_GROUP__enum,FM_INFO_FM_RDS_GROUP_size

// FM_INFO_FM_RDS_PS_TBL
#define FM_INFO_FM_RDS_PS_TBL_size "d"
#define FM_INFO_FM_RDS_PS_TBL FM_INFO_FM_RDS_PS_TBL__enum,FM_INFO_FM_RDS_PS_TBL_size

// FM_INFO_FM_RDS_PS_DATA
#define FM_INFO_FM_RDS_PS_DATA_size "‚d"
#define FM_INFO_FM_RDS_PS_DATA FM_INFO_FM_RDS_PS_DATA__enum,FM_INFO_FM_RDS_PS_DATA_size

// FM_INFO_FM_RDS_PS_BUFF0
#define FM_INFO_FM_RDS_PS_BUFF0_size NULL
#define FM_INFO_FM_RDS_PS_BUFF0 FM_INFO_FM_RDS_PS_BUFF0__enum,FM_INFO_FM_RDS_PS_BUFF0_size

// FM_INFO_FM_RDS_PS_BUFF1
#define FM_INFO_FM_RDS_PS_BUFF1_size NULL
#define FM_INFO_FM_RDS_PS_BUFF1 FM_INFO_FM_RDS_PS_BUFF1__enum,FM_INFO_FM_RDS_PS_BUFF1_size

// FM_INFO_FM_RDS_PS_BUFF_FULL
#define FM_INFO_FM_RDS_PS_BUFF_FULL_size "‰d"
#define FM_INFO_FM_RDS_PS_BUFF_FULL FM_INFO_FM_RDS_PS_BUFF_FULL__enum,FM_INFO_FM_RDS_PS_BUFF_FULL_size

// FM_INFO_FM_RDS_PS_CANNCEL
#define FM_INFO_FM_RDS_PS_CANNCEL_size NULL
#define FM_INFO_FM_RDS_PS_CANNCEL FM_INFO_FM_RDS_PS_CANNCEL__enum,FM_INFO_FM_RDS_PS_CANNCEL_size

// FM_INFO_FM_RDS_RT_TBL
#define FM_INFO_FM_RDS_RT_TBL_size "d"
#define FM_INFO_FM_RDS_RT_TBL FM_INFO_FM_RDS_RT_TBL__enum,FM_INFO_FM_RDS_RT_TBL_size

// FM_INFO_FM_RDS_RT_DATA
#define FM_INFO_FM_RDS_RT_DATA_size "ƒd"
#define FM_INFO_FM_RDS_RT_DATA FM_INFO_FM_RDS_RT_DATA__enum,FM_INFO_FM_RDS_RT_DATA_size

// FM_INFO_FM_RDS_RT_BUFF1
#define FM_INFO_FM_RDS_RT_BUFF1_size "d"
#define FM_INFO_FM_RDS_RT_BUFF1 FM_INFO_FM_RDS_RT_BUFF1__enum,FM_INFO_FM_RDS_RT_BUFF1_size

// FM_INFO_FM_RDS_RT_BUFF2
#define FM_INFO_FM_RDS_RT_BUFF2_size "d"
#define FM_INFO_FM_RDS_RT_BUFF2 FM_INFO_FM_RDS_RT_BUFF2__enum,FM_INFO_FM_RDS_RT_BUFF2_size

// FM_INFO_FM_RDS_RT_LEN
#define FM_INFO_FM_RDS_RT_LEN_size "ƒd"
#define FM_INFO_FM_RDS_RT_LEN FM_INFO_FM_RDS_RT_LEN__enum,FM_INFO_FM_RDS_RT_LEN_size

// FM_INFO_FM_RDS_AF_SET
#define FM_INFO_FM_RDS_AF_SET_size "‚d"
#define FM_INFO_FM_RDS_AF_SET FM_INFO_FM_RDS_AF_SET__enum,FM_INFO_FM_RDS_AF_SET_size

// FM_INFO_FM_RDS_AF_PAMD
#define FM_INFO_FM_RDS_AF_PAMD_size "ƒd"
#define FM_INFO_FM_RDS_AF_PAMD FM_INFO_FM_RDS_AF_PAMD__enum,FM_INFO_FM_RDS_AF_PAMD_size

// FM_INFO_FM_RDS_AF_SWITCH
#define FM_INFO_FM_RDS_AF_SWITCH_size "d"
#define FM_INFO_FM_RDS_AF_SWITCH FM_INFO_FM_RDS_AF_SWITCH__enum,FM_INFO_FM_RDS_AF_SWITCH_size

// FM_INFO_FM_RDS_AF_BUFF_FULL
#define FM_INFO_FM_RDS_AF_BUFF_FULL_size "‰d"
#define FM_INFO_FM_RDS_AF_BUFF_FULL FM_INFO_FM_RDS_AF_BUFF_FULL__enum,FM_INFO_FM_RDS_AF_BUFF_FULL_size

// FM_INFO_FM_RDS_PS_STATUS
#define FM_INFO_FM_RDS_PS_STATUS_size "ƒd"
#define FM_INFO_FM_RDS_PS_STATUS FM_INFO_FM_RDS_PS_STATUS__enum,FM_INFO_FM_RDS_PS_STATUS_size

// FM_INFO_FM_RDS_PS1_STATUS
#define FM_INFO_FM_RDS_PS1_STATUS_size "ˆd"
#define FM_INFO_FM_RDS_PS1_STATUS FM_INFO_FM_RDS_PS1_STATUS__enum,FM_INFO_FM_RDS_PS1_STATUS_size

// FM_INFO_FM_RDS_PS2_STATUS
#define FM_INFO_FM_RDS_PS2_STATUS_size "ˆd"
#define FM_INFO_FM_RDS_PS2_STATUS FM_INFO_FM_RDS_PS2_STATUS__enum,FM_INFO_FM_RDS_PS2_STATUS_size

// FM_INFO_FM_RDS_GET_PS_NAME
#define FM_INFO_FM_RDS_GET_PS_NAME_size "ˆd"
#define FM_INFO_FM_RDS_GET_PS_NAME FM_INFO_FM_RDS_GET_PS_NAME__enum,FM_INFO_FM_RDS_GET_PS_NAME_size

// FM_INFO_FM_RDS_BLOCK_CNT
#define FM_INFO_FM_RDS_BLOCK_CNT_size "‚d"
#define FM_INFO_FM_RDS_BLOCK_CNT FM_INFO_FM_RDS_BLOCK_CNT__enum,FM_INFO_FM_RDS_BLOCK_CNT_size

// FM_INFO_FM_RDS_EVENT_STATUS
#define FM_INFO_FM_RDS_EVENT_STATUS_size "‚d"
#define FM_INFO_FM_RDS_EVENT_STATUS FM_INFO_FM_RDS_EVENT_STATUS__enum,FM_INFO_FM_RDS_EVENT_STATUS_size

// FM_INFO_FM_RDS_EVENT_INFO
#define FM_INFO_FM_RDS_EVENT_INFO_size "d"
#define FM_INFO_FM_RDS_EVENT_INFO FM_INFO_FM_RDS_EVENT_INFO__enum,FM_INFO_FM_RDS_EVENT_INFO_size


#endif // FMR_TRC_GEN.H
