#ifndef _GDI_TRC_GEN_H_
#define _GDI_TRC_GEN_H_

// GDI_TRC_PRINT_LR_VALUE
#define GDI_TRC_PRINT_LR_VALUE_size "d"
#define GDI_TRC_PRINT_LR_VALUE GDI_TRC_PRINT_LR_VALUE__enum,GDI_TRC_PRINT_LR_VALUE_size

// GDI_TRC_1
#define GDI_TRC_1_size "âd"
#define GDI_TRC_1 GDI_TRC_1__enum,GDI_TRC_1_size

// GDI_TRC_2
#define GDI_TRC_2_size "âd"
#define GDI_TRC_2 GDI_TRC_2__enum,GDI_TRC_2_size

// GDI_TRC_3
#define GDI_TRC_3_size "Éd"
#define GDI_TRC_3 GDI_TRC_3__enum,GDI_TRC_3_size

// GDI_TRC_5
#define GDI_TRC_5_size "Üd"
#define GDI_TRC_5 GDI_TRC_5__enum,GDI_TRC_5_size

// GDI_TRC_6
#define GDI_TRC_6_size "Üd"
#define GDI_TRC_6 GDI_TRC_6__enum,GDI_TRC_6_size

// GDI_TRC_7
#define GDI_TRC_7_size "àd"
#define GDI_TRC_7 GDI_TRC_7__enum,GDI_TRC_7_size

// GDI_TRC_8
#define GDI_TRC_8_size "àd"
#define GDI_TRC_8 GDI_TRC_8__enum,GDI_TRC_8_size

// GDI_TRC_9
#define GDI_TRC_9_size "Ñd"
#define GDI_TRC_9 GDI_TRC_9__enum,GDI_TRC_9_size

// GDI_TRC_10
#define GDI_TRC_10_size "Ñd"
#define GDI_TRC_10 GDI_TRC_10__enum,GDI_TRC_10_size

// GDI_TRC_11
#define GDI_TRC_11_size "Üd"
#define GDI_TRC_11 GDI_TRC_11__enum,GDI_TRC_11_size

// GDI_TRC_12
#define GDI_TRC_12_size "Öd"
#define GDI_TRC_12 GDI_TRC_12__enum,GDI_TRC_12_size

// GDI_TRC_13
#define GDI_TRC_13_size "ád"
#define GDI_TRC_13 GDI_TRC_13__enum,GDI_TRC_13_size

// GDI_TRC_14
#define GDI_TRC_14_size "âd"
#define GDI_TRC_14 GDI_TRC_14__enum,GDI_TRC_14_size

// GDI_TRC_15
#define GDI_TRC_15_size "d"
#define GDI_TRC_15 GDI_TRC_15__enum,GDI_TRC_15_size

// GDI_TRC_16
#define GDI_TRC_16_size "d"
#define GDI_TRC_16 GDI_TRC_16__enum,GDI_TRC_16_size

// GDI_TRC_17
#define GDI_TRC_17_size NULL
#define GDI_TRC_17 GDI_TRC_17__enum,GDI_TRC_17_size

// GDI_TRC_18
#define GDI_TRC_18_size "d"
#define GDI_TRC_18 GDI_TRC_18__enum,GDI_TRC_18_size

// GDI_TRC_19
#define GDI_TRC_19_size NULL
#define GDI_TRC_19 GDI_TRC_19__enum,GDI_TRC_19_size

// GDI_TRC_20
#define GDI_TRC_20_size "d"
#define GDI_TRC_20 GDI_TRC_20__enum,GDI_TRC_20_size

// GDI_TRC_21
#define GDI_TRC_21_size "d"
#define GDI_TRC_21 GDI_TRC_21__enum,GDI_TRC_21_size

// GDI_TRC_22
#define GDI_TRC_22_size NULL
#define GDI_TRC_22 GDI_TRC_22__enum,GDI_TRC_22_size

// GDI_TRC_23
#define GDI_TRC_23_size "d"
#define GDI_TRC_23 GDI_TRC_23__enum,GDI_TRC_23_size

// GDI_TRC_24
#define GDI_TRC_24_size NULL
#define GDI_TRC_24 GDI_TRC_24__enum,GDI_TRC_24_size

// GDI_TRC_25
#define GDI_TRC_25_size "åd"
#define GDI_TRC_25 GDI_TRC_25__enum,GDI_TRC_25_size

// GDI_TRC_26
#define GDI_TRC_26_size NULL
#define GDI_TRC_26 GDI_TRC_26__enum,GDI_TRC_26_size

// GDI_TRC_30
#define GDI_TRC_30_size "Çd"
#define GDI_TRC_30 GDI_TRC_30__enum,GDI_TRC_30_size

// GDI_TRC_31
#define GDI_TRC_31_size "Çd"
#define GDI_TRC_31 GDI_TRC_31__enum,GDI_TRC_31_size

// GDI_TRC_32
#define GDI_TRC_32_size "Çd"
#define GDI_TRC_32 GDI_TRC_32__enum,GDI_TRC_32_size

// GDI_TRC_33
#define GDI_TRC_33_size "Çd"
#define GDI_TRC_33 GDI_TRC_33__enum,GDI_TRC_33_size

// GDI_TRC_34
#define GDI_TRC_34_size "Çd"
#define GDI_TRC_34 GDI_TRC_34__enum,GDI_TRC_34_size

// GDI_TRC_35
#define GDI_TRC_35_size "Çd"
#define GDI_TRC_35 GDI_TRC_35__enum,GDI_TRC_35_size

// GDI_TRC_36
#define GDI_TRC_36_size "Çd"
#define GDI_TRC_36 GDI_TRC_36__enum,GDI_TRC_36_size

// GDI_TRC_37
#define GDI_TRC_37_size "Çd"
#define GDI_TRC_37 GDI_TRC_37__enum,GDI_TRC_37_size

// GDI_TRC_38
#define GDI_TRC_38_size "Çd"
#define GDI_TRC_38 GDI_TRC_38__enum,GDI_TRC_38_size

// GDI_TRC_39
#define GDI_TRC_39_size "Çd"
#define GDI_TRC_39 GDI_TRC_39__enum,GDI_TRC_39_size

// GDI_TRC_40
#define GDI_TRC_40_size "Çd"
#define GDI_TRC_40 GDI_TRC_40__enum,GDI_TRC_40_size

// GDI_TRC_41
#define GDI_TRC_41_size NULL
#define GDI_TRC_41 GDI_TRC_41__enum,GDI_TRC_41_size

// GDI_TRC_42
#define GDI_TRC_42_size "d"
#define GDI_TRC_42 GDI_TRC_42__enum,GDI_TRC_42_size

// GDI_TRC_43
#define GDI_TRC_43_size NULL
#define GDI_TRC_43 GDI_TRC_43__enum,GDI_TRC_43_size

// GDI_TRC_44
#define GDI_TRC_44_size NULL
#define GDI_TRC_44 GDI_TRC_44__enum,GDI_TRC_44_size

// GDI_TRC_45
#define GDI_TRC_45_size "Ñd"
#define GDI_TRC_45 GDI_TRC_45__enum,GDI_TRC_45_size

// GDI_TRC_46
#define GDI_TRC_46_size "Éd"
#define GDI_TRC_46 GDI_TRC_46__enum,GDI_TRC_46_size

// GDI_TRC_47
#define GDI_TRC_47_size "Çd"
#define GDI_TRC_47 GDI_TRC_47__enum,GDI_TRC_47_size

// GDI_TRC_48
#define GDI_TRC_48_size "d"
#define GDI_TRC_48 GDI_TRC_48__enum,GDI_TRC_48_size

// GDI_TRC_49
#define GDI_TRC_49_size NULL
#define GDI_TRC_49 GDI_TRC_49__enum,GDI_TRC_49_size

// GDI_TRC_50
#define GDI_TRC_50_size NULL
#define GDI_TRC_50 GDI_TRC_50__enum,GDI_TRC_50_size

// GDI_TRC_51
#define GDI_TRC_51_size "Üd"
#define GDI_TRC_51 GDI_TRC_51__enum,GDI_TRC_51_size

// GDI_TRC_52
#define GDI_TRC_52_size NULL
#define GDI_TRC_52 GDI_TRC_52__enum,GDI_TRC_52_size

// GDI_TRC_53
#define GDI_TRC_53_size "d"
#define GDI_TRC_53 GDI_TRC_53__enum,GDI_TRC_53_size

// GDI_TRC_54
#define GDI_TRC_54_size NULL
#define GDI_TRC_54 GDI_TRC_54__enum,GDI_TRC_54_size

// GDI_TRC_55
#define GDI_TRC_55_size NULL
#define GDI_TRC_55 GDI_TRC_55__enum,GDI_TRC_55_size

// GDI_TRC_56
#define GDI_TRC_56_size "Ñd"
#define GDI_TRC_56 GDI_TRC_56__enum,GDI_TRC_56_size

// GDI_SVG_TRC_SVG_RAISE_ERROR
#define GDI_SVG_TRC_SVG_RAISE_ERROR_size "d"
#define GDI_SVG_TRC_SVG_RAISE_ERROR GDI_SVG_TRC_SVG_RAISE_ERROR__enum,GDI_SVG_TRC_SVG_RAISE_ERROR_size

// GDI_SVG_TRC_PARSER_ELEMENT
#define GDI_SVG_TRC_PARSER_ELEMENT_size "d"
#define GDI_SVG_TRC_PARSER_ELEMENT GDI_SVG_TRC_PARSER_ELEMENT__enum,GDI_SVG_TRC_PARSER_ELEMENT_size

// GDI_SVG_TRC_PARSER_ELEMENT_UNKNOWN
#define GDI_SVG_TRC_PARSER_ELEMENT_UNKNOWN_size NULL
#define GDI_SVG_TRC_PARSER_ELEMENT_UNKNOWN GDI_SVG_TRC_PARSER_ELEMENT_UNKNOWN__enum,GDI_SVG_TRC_PARSER_ELEMENT_UNKNOWN_size

// GDI_SVG_TRC_PARSER_ELEMENT_UNKNOWN_INDEX
#define GDI_SVG_TRC_PARSER_ELEMENT_UNKNOWN_INDEX_size "d"
#define GDI_SVG_TRC_PARSER_ELEMENT_UNKNOWN_INDEX GDI_SVG_TRC_PARSER_ELEMENT_UNKNOWN_INDEX__enum,GDI_SVG_TRC_PARSER_ELEMENT_UNKNOWN_INDEX_size

// GDI_SVG_TRC_STACK_OVERFLOW
#define GDI_SVG_TRC_STACK_OVERFLOW_size NULL
#define GDI_SVG_TRC_STACK_OVERFLOW GDI_SVG_TRC_STACK_OVERFLOW__enum,GDI_SVG_TRC_STACK_OVERFLOW_size

// GDI_MEM_ALLOC_START
#define GDI_MEM_ALLOC_START_size "dsd"
#define GDI_MEM_ALLOC_START GDI_MEM_ALLOC_START__enum,GDI_MEM_ALLOC_START_size

// GDI_MEM_ALLOC_END
#define GDI_MEM_ALLOC_END_size "d"
#define GDI_MEM_ALLOC_END GDI_MEM_ALLOC_END__enum,GDI_MEM_ALLOC_END_size

// GDI_MEM_ALLOC_FAIL
#define GDI_MEM_ALLOC_FAIL_size NULL
#define GDI_MEM_ALLOC_FAIL GDI_MEM_ALLOC_FAIL__enum,GDI_MEM_ALLOC_FAIL_size

// GDI_MEM_FREE
#define GDI_MEM_FREE_size "dsd"
#define GDI_MEM_FREE GDI_MEM_FREE__enum,GDI_MEM_FREE_size

// GDI_GIF_ENTER
#define GDI_GIF_ENTER_size "ád"
#define GDI_GIF_ENTER GDI_GIF_ENTER__enum,GDI_GIF_ENTER_size

// GDI_GIF_START
#define GDI_GIF_START_size "Éd"
#define GDI_GIF_START GDI_GIF_START__enum,GDI_GIF_START_size

// GDI_GIF_LEAVE
#define GDI_GIF_LEAVE_size "d"
#define GDI_GIF_LEAVE GDI_GIF_LEAVE__enum,GDI_GIF_LEAVE_size

// GDI_GIF_HW_TIMEOUT
#define GDI_GIF_HW_TIMEOUT_size NULL
#define GDI_GIF_HW_TIMEOUT GDI_GIF_HW_TIMEOUT__enum,GDI_GIF_HW_TIMEOUT_size

// GDI_GIF_HW_MSG
#define GDI_GIF_HW_MSG_size "Éd"
#define GDI_GIF_HW_MSG GDI_GIF_HW_MSG__enum,GDI_GIF_HW_MSG_size

// GDI_GIF_DECODE_FAIL
#define GDI_GIF_DECODE_FAIL_size "àd"
#define GDI_GIF_DECODE_FAIL GDI_GIF_DECODE_FAIL__enum,GDI_GIF_DECODE_FAIL_size

// GDI_JPG_ENTER
#define GDI_JPG_ENTER_size "ád"
#define GDI_JPG_ENTER GDI_JPG_ENTER__enum,GDI_JPG_ENTER_size

// GDI_JPG_START
#define GDI_JPG_START_size "Çd"
#define GDI_JPG_START GDI_JPG_START__enum,GDI_JPG_START_size

// GDI_JPG_LEAVE
#define GDI_JPG_LEAVE_size "d"
#define GDI_JPG_LEAVE GDI_JPG_LEAVE__enum,GDI_JPG_LEAVE_size

// GDI_JPG_CALLBACK
#define GDI_JPG_CALLBACK_size "Çd"
#define GDI_JPG_CALLBACK GDI_JPG_CALLBACK__enum,GDI_JPG_CALLBACK_size

// GDI_JPG_TIMEOUT
#define GDI_JPG_TIMEOUT_size "d"
#define GDI_JPG_TIMEOUT GDI_JPG_TIMEOUT__enum,GDI_JPG_TIMEOUT_size

// GDI_JPG_HW_MSG
#define GDI_JPG_HW_MSG_size "d"
#define GDI_JPG_HW_MSG GDI_JPG_HW_MSG__enum,GDI_JPG_HW_MSG_size

// GDI_JPG_DECODE_FAIL
#define GDI_JPG_DECODE_FAIL_size "àd"
#define GDI_JPG_DECODE_FAIL GDI_JPG_DECODE_FAIL__enum,GDI_JPG_DECODE_FAIL_size

// GDI_PNG_ENTER
#define GDI_PNG_ENTER_size "àd"
#define GDI_PNG_ENTER GDI_PNG_ENTER__enum,GDI_PNG_ENTER_size

// GDI_PNG_START
#define GDI_PNG_START_size "Çd"
#define GDI_PNG_START GDI_PNG_START__enum,GDI_PNG_START_size

// GDI_PNG_LEAVE
#define GDI_PNG_LEAVE_size "d"
#define GDI_PNG_LEAVE GDI_PNG_LEAVE__enum,GDI_PNG_LEAVE_size

// GDI_PNG_HW_TIMEOUT
#define GDI_PNG_HW_TIMEOUT_size NULL
#define GDI_PNG_HW_TIMEOUT GDI_PNG_HW_TIMEOUT__enum,GDI_PNG_HW_TIMEOUT_size

// GDI_PNG_HW_MSG
#define GDI_PNG_HW_MSG_size "Çd"
#define GDI_PNG_HW_MSG GDI_PNG_HW_MSG__enum,GDI_PNG_HW_MSG_size

// GDI_PNG_DECODE_FAIL
#define GDI_PNG_DECODE_FAIL_size "àd"
#define GDI_PNG_DECODE_FAIL GDI_PNG_DECODE_FAIL__enum,GDI_PNG_DECODE_FAIL_size

// GDI_ABM_LAYER_PUSH
#define GDI_ABM_LAYER_PUSH_size "sÇd"
#define GDI_ABM_LAYER_PUSH GDI_ABM_LAYER_PUSH__enum,GDI_ABM_LAYER_PUSH_size

// GDI_ABM_LAYER_POP
#define GDI_ABM_LAYER_POP_size "sÇd"
#define GDI_ABM_LAYER_POP GDI_ABM_LAYER_POP__enum,GDI_ABM_LAYER_POP_size

// GDI_LAYER_PUSH
#define GDI_LAYER_PUSH_size "sÇd"
#define GDI_LAYER_PUSH GDI_LAYER_PUSH__enum,GDI_LAYER_PUSH_size

// GDI_LAYER_POP
#define GDI_LAYER_POP_size "sÇd"
#define GDI_LAYER_POP GDI_LAYER_POP__enum,GDI_LAYER_POP_size

// GDI_CLIP_PUSH
#define GDI_CLIP_PUSH_size "sÇd"
#define GDI_CLIP_PUSH GDI_CLIP_PUSH__enum,GDI_CLIP_PUSH_size

// GDI_CLIP_POP
#define GDI_CLIP_POP_size "sÇd"
#define GDI_CLIP_POP GDI_CLIP_POP__enum,GDI_CLIP_POP_size

// GDI_FRAME_BUFFER_LOCK
#define GDI_FRAME_BUFFER_LOCK_size "sÇd"
#define GDI_FRAME_BUFFER_LOCK GDI_FRAME_BUFFER_LOCK__enum,GDI_FRAME_BUFFER_LOCK_size

// GDI_FRAME_BUFFER_UNLOCK
#define GDI_FRAME_BUFFER_UNLOCK_size "sÇd"
#define GDI_FRAME_BUFFER_UNLOCK GDI_FRAME_BUFFER_UNLOCK__enum,GDI_FRAME_BUFFER_UNLOCK_size

// GDI_ENCODE_BUFFER_ENTER
#define GDI_ENCODE_BUFFER_ENTER_size "Éd"
#define GDI_ENCODE_BUFFER_ENTER GDI_ENCODE_BUFFER_ENTER__enum,GDI_ENCODE_BUFFER_ENTER_size

// GDI_ENCODE_BUFFER_FS_OPEN_ERROR
#define GDI_ENCODE_BUFFER_FS_OPEN_ERROR_size "d"
#define GDI_ENCODE_BUFFER_FS_OPEN_ERROR GDI_ENCODE_BUFFER_FS_OPEN_ERROR__enum,GDI_ENCODE_BUFFER_FS_OPEN_ERROR_size

// GDI_ENCODE_BUFFER_FS_WRITE_ERROR
#define GDI_ENCODE_BUFFER_FS_WRITE_ERROR_size "d"
#define GDI_ENCODE_BUFFER_FS_WRITE_ERROR GDI_ENCODE_BUFFER_FS_WRITE_ERROR__enum,GDI_ENCODE_BUFFER_FS_WRITE_ERROR_size

// GDI_ENCODE_BUFFER_LEAVE
#define GDI_ENCODE_BUFFER_LEAVE_size "Éd"
#define GDI_ENCODE_BUFFER_LEAVE GDI_ENCODE_BUFFER_LEAVE__enum,GDI_ENCODE_BUFFER_LEAVE_size

// GDI_ENCODE_MEM_ENTER
#define GDI_ENCODE_MEM_ENTER_size "Üd"
#define GDI_ENCODE_MEM_ENTER GDI_ENCODE_MEM_ENTER__enum,GDI_ENCODE_MEM_ENTER_size

// GDI_ENCODE_MEM_LEAVE
#define GDI_ENCODE_MEM_LEAVE_size "Éd"
#define GDI_ENCODE_MEM_LEAVE GDI_ENCODE_MEM_LEAVE__enum,GDI_ENCODE_MEM_LEAVE_size

// GDI_ENCODE_MEM_START
#define GDI_ENCODE_MEM_START_size "d"
#define GDI_ENCODE_MEM_START GDI_ENCODE_MEM_START__enum,GDI_ENCODE_MEM_START_size

// GDI_G2D_LT_ENTER
#define GDI_G2D_LT_ENTER_size "âd"
#define GDI_G2D_LT_ENTER GDI_G2D_LT_ENTER__enum,GDI_G2D_LT_ENTER_size

// GDI_G2D_LT_START
#define GDI_G2D_LT_START_size "d"
#define GDI_G2D_LT_START GDI_G2D_LT_START__enum,GDI_G2D_LT_START_size

// GDI_G2D_LT_LEAVE
#define GDI_G2D_LT_LEAVE_size "Éd"
#define GDI_G2D_LT_LEAVE GDI_G2D_LT_LEAVE__enum,GDI_G2D_LT_LEAVE_size

// GDI_G2D_LT_HW_FAIL_FORCE_TO_SW
#define GDI_G2D_LT_HW_FAIL_FORCE_TO_SW_size "Çd"
#define GDI_G2D_LT_HW_FAIL_FORCE_TO_SW GDI_G2D_LT_HW_FAIL_FORCE_TO_SW__enum,GDI_G2D_LT_HW_FAIL_FORCE_TO_SW_size

// GDI_G2D_TILT_FONT_ENTER
#define GDI_G2D_TILT_FONT_ENTER_size "Üd"
#define GDI_G2D_TILT_FONT_ENTER GDI_G2D_TILT_FONT_ENTER__enum,GDI_G2D_TILT_FONT_ENTER_size

// GDI_G2D_TILT_FONT_GET_HANDLE
#define GDI_G2D_TILT_FONT_GET_HANDLE_size "d"
#define GDI_G2D_TILT_FONT_GET_HANDLE GDI_G2D_TILT_FONT_GET_HANDLE__enum,GDI_G2D_TILT_FONT_GET_HANDLE_size

// GDI_G2D_TILT_FONT_LEAVE
#define GDI_G2D_TILT_FONT_LEAVE_size "d"
#define GDI_G2D_TILT_FONT_LEAVE GDI_G2D_TILT_FONT_LEAVE__enum,GDI_G2D_TILT_FONT_LEAVE_size

// GDI_G2D_AA_FONT_ENTER
#define GDI_G2D_AA_FONT_ENTER_size "Üd"
#define GDI_G2D_AA_FONT_ENTER GDI_G2D_AA_FONT_ENTER__enum,GDI_G2D_AA_FONT_ENTER_size

// GDI_G2D_AA_FONT_GET_HANDLE
#define GDI_G2D_AA_FONT_GET_HANDLE_size "d"
#define GDI_G2D_AA_FONT_GET_HANDLE GDI_G2D_AA_FONT_GET_HANDLE__enum,GDI_G2D_AA_FONT_GET_HANDLE_size

// GDI_G2D_AA_FONT_LEAVE
#define GDI_G2D_AA_FONT_LEAVE_size "d"
#define GDI_G2D_AA_FONT_LEAVE GDI_G2D_AA_FONT_LEAVE__enum,GDI_G2D_AA_FONT_LEAVE_size

// GDI_TRC_LCD_FREEZE
#define GDI_TRC_LCD_FREEZE_size "Çd"
#define GDI_TRC_LCD_FREEZE GDI_TRC_LCD_FREEZE__enum,GDI_TRC_LCD_FREEZE_size

// GDI_TRC_LCD_HIGH_PRIORITY_FREEZE
#define GDI_TRC_LCD_HIGH_PRIORITY_FREEZE_size "Çd"
#define GDI_TRC_LCD_HIGH_PRIORITY_FREEZE GDI_TRC_LCD_HIGH_PRIORITY_FREEZE__enum,GDI_TRC_LCD_HIGH_PRIORITY_FREEZE_size

// GDI_TRC_LCD_SET_HW_UPDATE
#define GDI_TRC_LCD_SET_HW_UPDATE_size "Éd"
#define GDI_TRC_LCD_SET_HW_UPDATE GDI_TRC_LCD_SET_HW_UPDATE__enum,GDI_TRC_LCD_SET_HW_UPDATE_size

// GDI_TRC_LAYER_CREATE
#define GDI_TRC_LAYER_CREATE_size "åd"
#define GDI_TRC_LAYER_CREATE GDI_TRC_LAYER_CREATE__enum,GDI_TRC_LAYER_CREATE_size

// GDI_TRC_LAYER_FREE
#define GDI_TRC_LAYER_FREE_size "Çd"
#define GDI_TRC_LAYER_FREE GDI_TRC_LAYER_FREE__enum,GDI_TRC_LAYER_FREE_size

// GDI_TRC_LAYER_LAZY_FREE
#define GDI_TRC_LAYER_LAZY_FREE_size "Çd"
#define GDI_TRC_LAYER_LAZY_FREE GDI_TRC_LAYER_LAZY_FREE__enum,GDI_TRC_LAYER_LAZY_FREE_size

// GDI_TRC_LAYER_CONFIG_ELEMENT_HW_UPDATE
#define GDI_TRC_LAYER_CONFIG_ELEMENT_HW_UPDATE_size "Éd"
#define GDI_TRC_LAYER_CONFIG_ELEMENT_HW_UPDATE GDI_TRC_LAYER_CONFIG_ELEMENT_HW_UPDATE__enum,GDI_TRC_LAYER_CONFIG_ELEMENT_HW_UPDATE_size

// GDI_TRC_LAYER_CONFIG_ELEMENT
#define GDI_TRC_LAYER_CONFIG_ELEMENT_size "Ñd"
#define GDI_TRC_LAYER_CONFIG_ELEMENT GDI_TRC_LAYER_CONFIG_ELEMENT__enum,GDI_TRC_LAYER_CONFIG_ELEMENT_size

// GDI_LAYER_SET_BLT_LAYER
#define GDI_LAYER_SET_BLT_LAYER_size "Üd"
#define GDI_LAYER_SET_BLT_LAYER GDI_LAYER_SET_BLT_LAYER__enum,GDI_LAYER_SET_BLT_LAYER_size

// GDI_TRC_LAYER_PUSH_AND_SET_ACTIVE
#define GDI_TRC_LAYER_PUSH_AND_SET_ACTIVE_size "Édc"
#define GDI_TRC_LAYER_PUSH_AND_SET_ACTIVE GDI_TRC_LAYER_PUSH_AND_SET_ACTIVE__enum,GDI_TRC_LAYER_PUSH_AND_SET_ACTIVE_size

// GDI_TRC_LAYER_POP_AND_RESTORE_ACTIVE
#define GDI_TRC_LAYER_POP_AND_RESTORE_ACTIVE_size "Çdc"
#define GDI_TRC_LAYER_POP_AND_RESTORE_ACTIVE GDI_TRC_LAYER_POP_AND_RESTORE_ACTIVE__enum,GDI_TRC_LAYER_POP_AND_RESTORE_ACTIVE_size

// GDI_TRC_LAYER_SET_ACTIVE
#define GDI_TRC_LAYER_SET_ACTIVE_size "Çd"
#define GDI_TRC_LAYER_SET_ACTIVE GDI_TRC_LAYER_SET_ACTIVE__enum,GDI_TRC_LAYER_SET_ACTIVE_size

// GDI_TRC_LAYER_SET_ABLEND_SOURCE_LAYER
#define GDI_TRC_LAYER_SET_ABLEND_SOURCE_LAYER_size "Éd"
#define GDI_TRC_LAYER_SET_ABLEND_SOURCE_LAYER GDI_TRC_LAYER_SET_ABLEND_SOURCE_LAYER__enum,GDI_TRC_LAYER_SET_ABLEND_SOURCE_LAYER_size

// GDI_TRC_LAYER_PUSH_SOURCE_LAYER
#define GDI_TRC_LAYER_PUSH_SOURCE_LAYER_size "Éd"
#define GDI_TRC_LAYER_PUSH_SOURCE_LAYER GDI_TRC_LAYER_PUSH_SOURCE_LAYER__enum,GDI_TRC_LAYER_PUSH_SOURCE_LAYER_size

// GDI_TRC_LAYER_POP_SOURCE_LAYER
#define GDI_TRC_LAYER_POP_SOURCE_LAYER_size "Éd"
#define GDI_TRC_LAYER_POP_SOURCE_LAYER GDI_TRC_LAYER_POP_SOURCE_LAYER__enum,GDI_TRC_LAYER_POP_SOURCE_LAYER_size

// GDI_TRC_LAYER_PUSH_CLIP
#define GDI_TRC_LAYER_PUSH_CLIP_size "Çd"
#define GDI_TRC_LAYER_PUSH_CLIP GDI_TRC_LAYER_PUSH_CLIP__enum,GDI_TRC_LAYER_PUSH_CLIP_size

// GDI_TRC_LAYER_POP_CLIP
#define GDI_TRC_LAYER_POP_CLIP_size "Çd"
#define GDI_TRC_LAYER_POP_CLIP GDI_TRC_LAYER_POP_CLIP__enum,GDI_TRC_LAYER_POP_CLIP_size

// GDI_TRC_LAYER_LOCK_FRAME_BUFFER
#define GDI_TRC_LAYER_LOCK_FRAME_BUFFER_size "Çd"
#define GDI_TRC_LAYER_LOCK_FRAME_BUFFER GDI_TRC_LAYER_LOCK_FRAME_BUFFER__enum,GDI_TRC_LAYER_LOCK_FRAME_BUFFER_size

// GDI_TRC_LAYER_UNLOCK_FRAME_BUFFER
#define GDI_TRC_LAYER_UNLOCK_FRAME_BUFFER_size "Çd"
#define GDI_TRC_LAYER_UNLOCK_FRAME_BUFFER GDI_TRC_LAYER_UNLOCK_FRAME_BUFFER__enum,GDI_TRC_LAYER_UNLOCK_FRAME_BUFFER_size

// GDI_TRC_LAYER_SET_HW_UPDATE_LAYER
#define GDI_TRC_LAYER_SET_HW_UPDATE_LAYER_size "Éd"
#define GDI_TRC_LAYER_SET_HW_UPDATE_LAYER GDI_TRC_LAYER_SET_HW_UPDATE_LAYER__enum,GDI_TRC_LAYER_SET_HW_UPDATE_LAYER_size

// GDI_TRC_LAYER_BLT_BUFFER_LOCKED
#define GDI_TRC_LAYER_BLT_BUFFER_LOCKED_size "Öd"
#define GDI_TRC_LAYER_BLT_BUFFER_LOCKED GDI_TRC_LAYER_BLT_BUFFER_LOCKED__enum,GDI_TRC_LAYER_BLT_BUFFER_LOCKED_size

// GDI_TRC_LAYER_BLT_WITH_FLAG
#define GDI_TRC_LAYER_BLT_WITH_FLAG_size "Çd"
#define GDI_TRC_LAYER_BLT_WITH_FLAG GDI_TRC_LAYER_BLT_WITH_FLAG__enum,GDI_TRC_LAYER_BLT_WITH_FLAG_size

// GDI_TRC_LAYER_BLT_PREVIOUS
#define GDI_TRC_LAYER_BLT_PREVIOUS_size "Öd"
#define GDI_TRC_LAYER_BLT_PREVIOUS GDI_TRC_LAYER_BLT_PREVIOUS__enum,GDI_TRC_LAYER_BLT_PREVIOUS_size

// GDI_LAYER_BLT_ENTER
#define GDI_LAYER_BLT_ENTER_size "åd"
#define GDI_LAYER_BLT_ENTER GDI_LAYER_BLT_ENTER__enum,GDI_LAYER_BLT_ENTER_size

// GDI_LAYER_BLT_FREEZED
#define GDI_LAYER_BLT_FREEZED_size "Çd"
#define GDI_LAYER_BLT_FREEZED GDI_LAYER_BLT_FREEZED__enum,GDI_LAYER_BLT_FREEZED_size

// GDI_LAYER_BLT_START
#define GDI_LAYER_BLT_START_size "Éd"
#define GDI_LAYER_BLT_START GDI_LAYER_BLT_START__enum,GDI_LAYER_BLT_START_size

// GDI_LAYER_BLT_LEAVE
#define GDI_LAYER_BLT_LEAVE_size "Çd"
#define GDI_LAYER_BLT_LEAVE GDI_LAYER_BLT_LEAVE__enum,GDI_LAYER_BLT_LEAVE_size

// GDI_LAYER_FLATTEN_ENTER
#define GDI_LAYER_FLATTEN_ENTER_size "åd"
#define GDI_LAYER_FLATTEN_ENTER GDI_LAYER_FLATTEN_ENTER__enum,GDI_LAYER_FLATTEN_ENTER_size

// GDI_LAYER_FLATTEN_START
#define GDI_LAYER_FLATTEN_START_size "d"
#define GDI_LAYER_FLATTEN_START GDI_LAYER_FLATTEN_START__enum,GDI_LAYER_FLATTEN_START_size

// GDI_LAYER_FLATTEN_LEAVE
#define GDI_LAYER_FLATTEN_LEAVE_size "Çd"
#define GDI_LAYER_FLATTEN_LEAVE GDI_LAYER_FLATTEN_LEAVE__enum,GDI_LAYER_FLATTEN_LEAVE_size

// GDI_LAYER_FLATTEN_NB_CALLBACK
#define GDI_LAYER_FLATTEN_NB_CALLBACK_size "d"
#define GDI_LAYER_FLATTEN_NB_CALLBACK GDI_LAYER_FLATTEN_NB_CALLBACK__enum,GDI_LAYER_FLATTEN_NB_CALLBACK_size

// GDI_LAYER_BLT_WAIT_BLT_FINISH
#define GDI_LAYER_BLT_WAIT_BLT_FINISH_size "d"
#define GDI_LAYER_BLT_WAIT_BLT_FINISH GDI_LAYER_BLT_WAIT_BLT_FINISH__enum,GDI_LAYER_BLT_WAIT_BLT_FINISH_size

// GDI_LAYER_BLT_WAIT_BLT_CALLBACK
#define GDI_LAYER_BLT_WAIT_BLT_CALLBACK_size "d"
#define GDI_LAYER_BLT_WAIT_BLT_CALLBACK GDI_LAYER_BLT_WAIT_BLT_CALLBACK__enum,GDI_LAYER_BLT_WAIT_BLT_CALLBACK_size

// GDI_LAYER_ROTATOR_ENTER
#define GDI_LAYER_ROTATOR_ENTER_size "êd"
#define GDI_LAYER_ROTATOR_ENTER GDI_LAYER_ROTATOR_ENTER__enum,GDI_LAYER_ROTATOR_ENTER_size

// GDI_LAYER_ROTATOR_LEAVE
#define GDI_LAYER_ROTATOR_LEAVE_size "Çd"
#define GDI_LAYER_ROTATOR_LEAVE GDI_LAYER_ROTATOR_LEAVE__enum,GDI_LAYER_ROTATOR_LEAVE_size

// GDI_UTIL_ROTATOR_FAIL
#define GDI_UTIL_ROTATOR_FAIL_size "Éd"
#define GDI_UTIL_ROTATOR_FAIL GDI_UTIL_ROTATOR_FAIL__enum,GDI_UTIL_ROTATOR_FAIL_size

// GDI_LAYER_RESIZER_ENTER
#define GDI_LAYER_RESIZER_ENTER_size "ãd"
#define GDI_LAYER_RESIZER_ENTER GDI_LAYER_RESIZER_ENTER__enum,GDI_LAYER_RESIZER_ENTER_size

// GDI_LAYER_RESIZER_LEAVE
#define GDI_LAYER_RESIZER_LEAVE_size "Çd"
#define GDI_LAYER_RESIZER_LEAVE GDI_LAYER_RESIZER_LEAVE__enum,GDI_LAYER_RESIZER_LEAVE_size

// GDI_UTIL_RESIZER_FAIL
#define GDI_UTIL_RESIZER_FAIL_size "Çd"
#define GDI_UTIL_RESIZER_FAIL GDI_UTIL_RESIZER_FAIL__enum,GDI_UTIL_RESIZER_FAIL_size

// GDI_IMGDEC_ENTER
#define GDI_IMGDEC_ENTER_size "Öd"
#define GDI_IMGDEC_ENTER GDI_IMGDEC_ENTER__enum,GDI_IMGDEC_ENTER_size

// GDI_IMGDEC_INFO
#define GDI_IMGDEC_INFO_size "Üd"
#define GDI_IMGDEC_INFO GDI_IMGDEC_INFO__enum,GDI_IMGDEC_INFO_size

// GDI_IMGDEC_LEAVE
#define GDI_IMGDEC_LEAVE_size "Çd"
#define GDI_IMGDEC_LEAVE GDI_IMGDEC_LEAVE__enum,GDI_IMGDEC_LEAVE_size

// GDI_IMGDEC_ABORT
#define GDI_IMGDEC_ABORT_size NULL
#define GDI_IMGDEC_ABORT GDI_IMGDEC_ABORT__enum,GDI_IMGDEC_ABORT_size

// GDI_TRC_57
#define GDI_TRC_57_size "Çd"
#define GDI_TRC_57 GDI_TRC_57__enum,GDI_TRC_57_size

// GDI_TRC_AB2_PALETTE_ALLOC_ERR
#define GDI_TRC_AB2_PALETTE_ALLOC_ERR_size "Éd"
#define GDI_TRC_AB2_PALETTE_ALLOC_ERR GDI_TRC_AB2_PALETTE_ALLOC_ERR__enum,GDI_TRC_AB2_PALETTE_ALLOC_ERR_size

// GDI_TRC_9SLICE_SOURCE_INFO
#define GDI_TRC_9SLICE_SOURCE_INFO_size NULL
#define GDI_TRC_9SLICE_SOURCE_INFO GDI_TRC_9SLICE_SOURCE_INFO__enum,GDI_TRC_9SLICE_SOURCE_INFO_size

// GDI_TRC_9SLICE_MARGIN_ERROR_1
#define GDI_TRC_9SLICE_MARGIN_ERROR_1_size "Üd"
#define GDI_TRC_9SLICE_MARGIN_ERROR_1 GDI_TRC_9SLICE_MARGIN_ERROR_1__enum,GDI_TRC_9SLICE_MARGIN_ERROR_1_size

// GDI_TRC_9SLICE_MARGIN_ERROR_2
#define GDI_TRC_9SLICE_MARGIN_ERROR_2_size "Üd"
#define GDI_TRC_9SLICE_MARGIN_ERROR_2 GDI_TRC_9SLICE_MARGIN_ERROR_2__enum,GDI_TRC_9SLICE_MARGIN_ERROR_2_size

// GDI_TRC_9SLICE_MARGIN_INFO
#define GDI_TRC_9SLICE_MARGIN_INFO_size "àd"
#define GDI_TRC_9SLICE_MARGIN_INFO GDI_TRC_9SLICE_MARGIN_INFO__enum,GDI_TRC_9SLICE_MARGIN_INFO_size

// GDI_TRC_9SLICE_DRAW_ORIGINAL
#define GDI_TRC_9SLICE_DRAW_ORIGINAL_size "àd"
#define GDI_TRC_9SLICE_DRAW_ORIGINAL GDI_TRC_9SLICE_DRAW_ORIGINAL__enum,GDI_TRC_9SLICE_DRAW_ORIGINAL_size

// GDI_TRC_AB2_ONE_COLOR_PALETTE_ALLOC_ERR
#define GDI_TRC_AB2_ONE_COLOR_PALETTE_ALLOC_ERR_size "Ñd"
#define GDI_TRC_AB2_ONE_COLOR_PALETTE_ALLOC_ERR GDI_TRC_AB2_ONE_COLOR_PALETTE_ALLOC_ERR__enum,GDI_TRC_AB2_ONE_COLOR_PALETTE_ALLOC_ERR_size

// GDI_TRC_AB2_ALL_ALPHA_BLENDING_CF_ERR
#define GDI_TRC_AB2_ALL_ALPHA_BLENDING_CF_ERR_size "Çd"
#define GDI_TRC_AB2_ALL_ALPHA_BLENDING_CF_ERR GDI_TRC_AB2_ALL_ALPHA_BLENDING_CF_ERR__enum,GDI_TRC_AB2_ALL_ALPHA_BLENDING_CF_ERR_size

// GDI_2D_LT_NB_CALLBACK
#define GDI_2D_LT_NB_CALLBACK_size NULL
#define GDI_2D_LT_NB_CALLBACK GDI_2D_LT_NB_CALLBACK__enum,GDI_2D_LT_NB_CALLBACK_size

// GDI_2D_LT_NB_WAIT_FOR_PREVIOUS_FINISH
#define GDI_2D_LT_NB_WAIT_FOR_PREVIOUS_FINISH_size NULL
#define GDI_2D_LT_NB_WAIT_FOR_PREVIOUS_FINISH GDI_2D_LT_NB_WAIT_FOR_PREVIOUS_FINISH__enum,GDI_2D_LT_NB_WAIT_FOR_PREVIOUS_FINISH_size

// GDI_2D_LT_NB_WAIT_FOR_CURRENT_FINISH
#define GDI_2D_LT_NB_WAIT_FOR_CURRENT_FINISH_size NULL
#define GDI_2D_LT_NB_WAIT_FOR_CURRENT_FINISH GDI_2D_LT_NB_WAIT_FOR_CURRENT_FINISH__enum,GDI_2D_LT_NB_WAIT_FOR_CURRENT_FINISH_size

// GDI_2D_LT_NB_INIT_STATE
#define GDI_2D_LT_NB_INIT_STATE_size NULL
#define GDI_2D_LT_NB_INIT_STATE GDI_2D_LT_NB_INIT_STATE__enum,GDI_2D_LT_NB_INIT_STATE_size

// GDI_2D_LT_NB_RELEASE_G2D_HANDLE
#define GDI_2D_LT_NB_RELEASE_G2D_HANDLE_size NULL
#define GDI_2D_LT_NB_RELEASE_G2D_HANDLE GDI_2D_LT_NB_RELEASE_G2D_HANDLE__enum,GDI_2D_LT_NB_RELEASE_G2D_HANDLE_size

// GDI_2D_LT_NB_GET_G2D_HANDLE
#define GDI_2D_LT_NB_GET_G2D_HANDLE_size NULL
#define GDI_2D_LT_NB_GET_G2D_HANDLE GDI_2D_LT_NB_GET_G2D_HANDLE__enum,GDI_2D_LT_NB_GET_G2D_HANDLE_size

// GDI_2D_LT_NB_RELEASE_LT_EVENT
#define GDI_2D_LT_NB_RELEASE_LT_EVENT_size NULL
#define GDI_2D_LT_NB_RELEASE_LT_EVENT GDI_2D_LT_NB_RELEASE_LT_EVENT__enum,GDI_2D_LT_NB_RELEASE_LT_EVENT_size

// GDI_TRC_2D_FILL_RECT_RESULT
#define GDI_TRC_2D_FILL_RECT_RESULT_size "Çd"
#define GDI_TRC_2D_FILL_RECT_RESULT GDI_TRC_2D_FILL_RECT_RESULT__enum,GDI_TRC_2D_FILL_RECT_RESULT_size

// GDI_TRC_2D_FILL_RECT_CALLBACK
#define GDI_TRC_2D_FILL_RECT_CALLBACK_size "d"
#define GDI_TRC_2D_FILL_RECT_CALLBACK GDI_TRC_2D_FILL_RECT_CALLBACK__enum,GDI_TRC_2D_FILL_RECT_CALLBACK_size


#endif // GDI_TRC_GEN.H
