#ifndef _MMI_MRE_APP_INFO_TRC_GEN_H_
#define _MMI_MRE_APP_INFO_TRC_GEN_H_

// TRC_MMI_MRE_APP_INFO
#define TRC_MMI_MRE_APP_INFO_size "…d"
#define TRC_MMI_MRE_APP_INFO TRC_MMI_MRE_APP_INFO__enum,TRC_MMI_MRE_APP_INFO_size


#endif // MMI_MRE_APP_INFO_TRC_GEN.H
