#include "mmi_features.h"
#include "custresdef.h"


<?xml version="1.0" encoding="UTF-8"?>
<APP id="SRV_VENUS_COMPONENT_POPUP">
    <!-----------------------------------------------------String Resource Area----------------------------------------------------->

    <!----------------- Screen Id ----------------------------------------->
    <SCREEN id = "SCR_ID_GLOBAL_POPUP_BASE"/>
    
    <!-----------------------------------------------------Image Resource Area------------------------------------------------------>
#if defined(__MMI_VUI_COSMOS_CP__)
	<THEME>
	    <IMAGE id="VCP_IMG_POPUP_BACKGROUND"/>
	    <IMAGE id="VCP_IMG_POPUP_COMMAND_BACKGROUND"/>
	    <IMAGE id="VCP_IMG_POPUP_BACKGROUND_TOP"/>
	    <IMAGE id="VCP_IMG_POPUP_BACKGROUND_BOTTOM"/>
	    <IMAGE id="VCP_IMG_POPUP_TYPE_FAILURE_ALERT"/>
	    <IMAGE id="VCP_IMG_POPUP_TYPE_INFO_ALERT"/>
	    <IMAGE id="VCP_IMG_POPUP_TYPE_WARNING_ALERT"/>
	    <IMAGE id="VCP_IMG_POPUP_TYPE_SUCCESS_ALERT"/>
	    <IMAGE id="VCP_IMG_POPUP_TYPE_PROGRESS_ALERT"/>
	    <IMAGE id="VCP_IMG_POPUP_TYPE_QUESTION_ALERT"/>
	    <IMAGE id="VCP_IMG_POPUP_TYPE_FAILURE_CONFIRM"/>
	    <IMAGE id="VCP_IMG_POPUP_TYPE_INFO_CONFIRM"/>
	    <IMAGE id="VCP_IMG_POPUP_TYPE_WARNING_CONFIRM"/>
	    <IMAGE id="VCP_IMG_POPUP_TYPE_SUCCESS_CONFIRMT"/>
	    <IMAGE id="VCP_IMG_POPUP_TYPE_PROGRESS_CONFIRM"/>
	    <IMAGE id="VCP_IMG_POPUP_TYPE_QUESTION_CONFIRM"/>
	    <IMAGE id="VCP_IMG_POPUP_BUTTON_NORMAL_PRESSED"/>
	    <IMAGE id="VCP_IMG_POPUP_BUTTON_NORMAL_DISABLED"/>
	    <IMAGE id="VCP_IMG_POPUP_BUTTON_NORMAL_NORMAL"/>
	    <IMAGE id="VCP_IMG_POPUP_BUTTON_WARNING_PRESSED"/>
	    <IMAGE id="VCP_IMG_POPUP_BUTTON_WARNING_DISABLED"/>
	    <IMAGE id="VCP_IMG_POPUP_BUTTON_WARNING_NORMAL"/>
	    <IMAGE id="VCP_IMG_POPUP_BUTTON_CANCEL_PRESSED"/>
	    <IMAGE id="VCP_IMG_POPUP_BUTTON_CANCEL_DISABLED"/>
	    <IMAGE id="VCP_IMG_POPUP_BUTTON_CANCEL_NORMAL"/>
	    <IMAGE id="VCP_IMG_POPUP_WAITING_BACKGROUND"/>
	    <IMAGE id="VCP_IMG_POPUP_MORE_BACKGROUND_TOP"/>
	    <IMAGE id="VCP_IMG_POPUP_MORE_BACKGROUND_BOTTOM"/>
	    <COLOR id="CLR_COSMOS_INPUT_POPUP_TITLE_TXT" desc="Title text color"/>
        <COLOR id="VCP_COL_POPUP_TITLE_FONT" desc="Font color of popup title"/>
     	<COLOR id="CLR_COSMOS_INPUT_POPUP_HINT_TXT" desc="Hint text color"/>
     	<COLOR id="CLR_COSMOS_INPUT_POPUP_ERR_TXT" desc="Error text color"/>        
    </THEME>
#elif !defined(__VENUS_UI_ENGINE__)
    #define ROOT_PATH CUST_IMG_PATH"\\\\MainLCD\\\\VUI\\\\Shell\\\\Components\\\\Popup\\\\Empty\\\\"
    <IMAGE id="VCP_IMG_POPUP_BACKGROUND">ROOT_PATH"Pop_Alert_BG.9slice.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_BACKGROUND_TOP">ROOT_PATH"Pop_BG_Top.9slice.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_BACKGROUND_BOTTOM">ROOT_PATH"Pop_BG_Bottom.9slice.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_TYPE_FAILURE_ALERT">ROOT_PATH"APP_ERR.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_TYPE_INFO_ALERT">ROOT_PATH"APP_INF.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_TYPE_WARNING_ALERT">ROOT_PATH"APP_WARN.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_TYPE_SUCCESS_ALERT">ROOT_PATH"APP_DONE.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_TYPE_PROGRESS_ALERT">ROOT_PATH"APP_DONE.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_TYPE_QUESTION_ALERT">ROOT_PATH"APP_QMARK.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_TYPE_FAILURE_CONFIRM">ROOT_PATH"CPP_ERR.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_TYPE_INFO_CONFIRM">ROOT_PATH"CPP_INF.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_TYPE_WARNING_CONFIRM">ROOT_PATH"CPP_WARN.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_TYPE_SUCCESS_CONFIRMT">ROOT_PATH"CPP_DONE.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_TYPE_PROGRESS_CONFIRM">ROOT_PATH"CPP_DONE.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_TYPE_QUESTION_CONFIRM">ROOT_PATH"CPP_QMARK.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_BUTTON_PRESSED">ROOT_PATH"Button_Pre.9slice.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_BUTTON_NORMAL_DISABLED">ROOT_PATH"Normal_Dis.9slice.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_BUTTON_NORMAL_NORMAL">ROOT_PATH"Normal_Nor.9slice.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_BUTTON_WARNING_DISABLED">ROOT_PATH"Warning_Dis.9slice.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_BUTTON_WARNING_NORMAL">ROOT_PATH"Warning_Nor.9slice.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_BUTTON_CANCEL_DISABLED">ROOT_PATH"Cancel_Dis.9slice.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_BUTTON_CANCEL_NORMAL">ROOT_PATH"Cancel_Nor.9slice.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_WAITING_BACKGROUND">ROOT_PATH"Waiting_BG.9slice.png"</IMAGE>
    
    <IMAGE id="VCP_IMG_POPUP_COMMAND_BACKGROUND">ROOT_PATH"Pop_Command_BG.9slice.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_MORE_BACKGROUND_TOP">ROOT_PATH"Pop_ContextMenu_BG01.9slice.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_MORE_BACKGROUND_BOTTOM">ROOT_PATH"Pop_ContextMenu_BG02.9slice.png"</IMAGE>
#else 
    #define ROOT_PATH CUST_IMG_PATH"\\\\MainLCD\\\\VUI\\\\Shell\\\\Components\\\\Popup\\\\"
    <IMAGE id="VCP_IMG_POPUP_BACKGROUND">ROOT_PATH"Pop_Alert_BG.9slice.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_BACKGROUND_TOP">ROOT_PATH"Pop_BG_Top.9slice.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_BACKGROUND_BOTTOM">ROOT_PATH"Pop_BG_Bottom.9slice.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_TYPE_FAILURE_ALERT">ROOT_PATH"APP_ERR.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_TYPE_INFO_ALERT">ROOT_PATH"APP_INF.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_TYPE_WARNING_ALERT">ROOT_PATH"APP_WARN.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_TYPE_SUCCESS_ALERT">ROOT_PATH"APP_DONE.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_TYPE_PROGRESS_ALERT">ROOT_PATH"APP_DONE.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_TYPE_QUESTION_ALERT">ROOT_PATH"APP_QMARK.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_TYPE_FAILURE_CONFIRM">ROOT_PATH"CPP_ERR.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_TYPE_INFO_CONFIRM">ROOT_PATH"CPP_INF.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_TYPE_WARNING_CONFIRM">ROOT_PATH"CPP_WARN.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_TYPE_SUCCESS_CONFIRMT">ROOT_PATH"CPP_DONE.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_TYPE_PROGRESS_CONFIRM">ROOT_PATH"CPP_DONE.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_TYPE_QUESTION_CONFIRM">ROOT_PATH"CPP_QMARK.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_BUTTON_PRESSED">ROOT_PATH"Button_Pre.9slice.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_BUTTON_NORMAL_DISABLED">ROOT_PATH"Normal_Dis.9slice.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_BUTTON_NORMAL_NORMAL">ROOT_PATH"Normal_Nor.9slice.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_BUTTON_WARNING_DISABLED">ROOT_PATH"Warning_Dis.9slice.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_BUTTON_WARNING_NORMAL">ROOT_PATH"Warning_Nor.9slice.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_BUTTON_CANCEL_DISABLED">ROOT_PATH"Cancel_Dis.9slice.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_BUTTON_CANCEL_NORMAL">ROOT_PATH"Cancel_Nor.9slice.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_WAITING_BACKGROUND">ROOT_PATH"Waiting_BG.9slice.png"</IMAGE>
    
    <IMAGE id="VCP_IMG_POPUP_COMMAND_BACKGROUND">ROOT_PATH"Pop_Command_BG.9slice.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_MORE_BACKGROUND_TOP">ROOT_PATH"Pop_ContextMenu_BG01.9slice.png"</IMAGE>
    <IMAGE id="VCP_IMG_POPUP_MORE_BACKGROUND_BOTTOM">ROOT_PATH"Pop_ContextMenu_BG02.9slice.png"</IMAGE>
#endif
</APP>

