
/*****************************************************************************
 Definition
*****************************************************************************/

#undef VFX_APP_RES_DECLARE
#define VFX_APP_RES_DECLARE(_app, _range, _path)    MMI_RES_DECLARE(_app, _range, "..\\venusmmi\\app\\cosmos\\" _path)

/*****************************************************************************
 APP resource declaration
*****************************************************************************/

VFX_APP_RES_DECLARE(VAPP_HELLOWORLD, 20, "HelloWorld\\res\\")
VFX_APP_RES_DECLARE(VCUI_HELLOWORLD, 20, "HelloWorld\\res\\")

#if defined (__MMI_BAIDU_SEARCH_COSMOS__)
VFX_APP_RES_DECLARE(VAPP_BAIDU_SEARCH, 20, "WidgetBaiduSearch\\res\\")
#endif 

#if defined (__MMI_YOUTUBE_SHORTCUT__)
VFX_APP_RES_DECLARE(VAPP_YOUTUBE, 20, "YOUTUBE\\res\\")
#endif

VFX_APP_RES_DECLARE(VAPP_PACKAGE_CONCURRENT, EMPTY_RANGE, "interface\\app\\")

VFX_APP_RES_DECLARE(APP_COSMOS_GLOBAL, 100, "Resource\\ResourceRes\\")
VFX_APP_RES_DECLARE(VAPP_WAP_PROF, 50, "UPPApp\\res\\")

VFX_APP_RES_DECLARE(VAPP_BOOTUP, 200, "Bootup\\res\\")
VFX_APP_RES_DECLARE(VAPP_SHUTDOWN, 10, "Shutdown\\res\\")
VFX_APP_RES_DECLARE(VAPP_SECSET, 150, "SecSet\\res\\")
VFX_APP_RES_DECLARE(VCUI_VERIFY, 10, "SecSet\\res\\")
VFX_APP_RES_DECLARE(VAPP_SECSET_HPVERI, 10, "SecSet\\res\\")
VFX_APP_RES_DECLARE(VAPP_NW_INFO, 10, "NwInfo\\res\\")
VFX_APP_RES_DECLARE(VAPP_SIM_CTRL, 20, "SimCtrl\\res\\")

#if defined(__MMI_SAFE_MODE__)
VFX_APP_RES_DECLARE(VAPP_SAFE_MODE, 10, "SafeMode\\res\\")
#endif

VFX_APP_RES_DECLARE(VAPP_LAUNCHER, 5, "Launcher\\res\\")

#if defined(__MMI_VUI_SETTING_LAUNCHER_SELECTION__)
VFX_APP_RES_DECLARE(VAPP_LAUNCHER_SHUTTLE, 5, "LauncherShuttle\\res\\")
#endif

#ifdef __MMI_VUI_LAUNCHER_COSMOS__
VFX_APP_RES_DECLARE(VAPP_LAUNCHER_COSMOS, 30, "LauncherCosmos\\Home\\res\\")
#endif

#ifdef __MMI_VUI_LAUNCHER_ROBOT__
VFX_APP_RES_DECLARE(VAPP_LAUNCHER_ROBOT, 30, "LauncherRobot\\Home\\res\\")
VFX_APP_RES_DECLARE(VAPP_LAUNCHER_ROBOT_MAINMENU, 35, "LauncherRobot\\Mainmenu\\res\\")
#endif

#if defined(__MMI_VUI_LAUNCHER_ROBOT__) && defined(__MMI_VUI_HOME_SCREEN_SWITCH_EFFECT__)
VFX_APP_RES_DECLARE(VAPP_LAUNCHER_ROBOT_PAGE_TRANSITION_SETTING, 10, "LauncherRobot\\Home\\res\\")
#endif

VFX_APP_RES_DECLARE(VAPP_WIDGET_MUSIC_PLAYER, 30, "Widget\\res\\")
#ifdef __COSMOS_3D_V10__
VFX_APP_RES_DECLARE(VAPP_WIDGET_3D_CLOCK, 80, "Widget\\res\\")
VFX_APP_RES_DECLARE(VAPP_WIDGET_3D_MUSIC_PLAYER, 40, "Widget\\res\\")
#endif
VFX_APP_RES_DECLARE(VAPP_WIDGET_QUICK_SWITCH, 35, "Widget\\res\\")
VFX_APP_RES_DECLARE(VAPP_WIDGET_FM_RADIO, 40, "Widget\\res\\")
VFX_APP_RES_DECLARE(VAPP_WIDGET_CLOCK, 50, "Widget\\res\\")
#ifdef __MMI_VUI_WIDGET_CALENDAR__ 
VFX_APP_RES_DECLARE(VAPP_WIDGET_CALENDAR, 50, "Widget\\res\\")
#endif
#ifdef __MMI_VUI_WIDGET_VIP_CONTACT__
VFX_APP_RES_DECLARE(VAPP_WIDGET_VIP_CONTACT, 40, "Widget\\res\\")
#endif

#if defined(__MMI_VUI_WIDGET_GALLERY__)
VFX_APP_RES_DECLARE(VAPP_WIDGET_GALLERY, 50, "Widget\\res\\")
VFX_APP_RES_DECLARE(VAPP_WIDGET_GALLERY_SETTING, 50, "Widget\\res\\")
#endif

VFX_APP_RES_DECLARE(VAPP_WIDGET_3D_PET, 100, "Widget\\res\\")
#if defined(__MMI_GADGET_SUPPORT__)
VFX_APP_RES_DECLARE(VAPP_WIDGET_GADGET, 5, "Widget\\res\\")
#endif

#ifdef __MMI_VUI_WIDGET_FLIP_CLOCK__
VFX_APP_RES_DECLARE(VAPP_WIDGET_FLIP_CLOCK, 35, "Widget\\res\\")
#endif

VFX_APP_RES_DECLARE(VAPP_USBMMI, 50, "USBApp\\Res\\")
VFX_APP_RES_DECLARE(VAPP_WEBCAM,     20, "Webcam\\res\\")
VFX_APP_RES_DECLARE(VAPP_CLOCK, 400, "Clock\\res\\")
VFX_APP_RES_DECLARE(VAPP_ALARM_IND, 10, "Clock\\res\\")
VFX_APP_RES_DECLARE(VAPP_TIMER_IND, 10, "Clock\\res\\")
VFX_APP_RES_DECLARE(VAPP_MMS, 200, "Message\\res\\")
VFX_APP_RES_DECLARE(VCUI_MMS, 20, "Message\\res\\")
VFX_APP_RES_DECLARE(VAPP_MMS_SEND_URI, 5, "Message\\res\\")
VFX_APP_RES_DECLARE(VAPP_MMS_HEAP, 5, "Message\\res\\")
VFX_APP_RES_DECLARE(VAPP_MMS_EXTRA_BASE, 5, "Message\\res\\")
VFX_APP_RES_DECLARE(VAPP_MMS_FG, 5, "Message\\res\\")
VFX_APP_RES_DECLARE(VAPP_MMS_CUI_SRV, 5, "Message\\res\\")
VFX_APP_RES_DECLARE(VAPP_APP_MANAGER, 200, "AppManager\\res\\")
VFX_APP_RES_DECLARE(VAPP_MRE_APP_OPERATOR, 20, "AppManager\\res\\")
VFX_APP_RES_DECLARE(VCUI_WORLDCLOCK, 20, "Clock\\res\\")
VFX_APP_RES_DECLARE(VAPP_FONTMGR, 50, "FontMgr\\res\\")
VFX_APP_RES_DECLARE(VAPP_FMGR, 450, "FileMgr\\res\\")
VFX_APP_RES_DECLARE(VCUI_FMGR, 10, "FileMgr\\res\\")
VFX_APP_RES_DECLARE(VAPP_MSG, 200, "Message\\res\\")
VFX_APP_RES_DECLARE(VAPP_MSG_INBOX, 10, "Message\\res\\")
VFX_APP_RES_DECLARE(VAPP_SMS_CLASS0, 5, "Message\\res\\")
VFX_APP_RES_DECLARE(VAPP_SMS_SEND_URI, 5, "Message\\res\\")
VFX_APP_RES_DECLARE(APP_VAPP_SMS, 300, "Message\\res\\")
VFX_APP_RES_DECLARE(VAPP_SMS_HEAP, 5, "Message\\res\\")
VFX_APP_RES_DECLARE(VAPP_SMS_EXTRA_BASE, 5, "Message\\res\\")
VFX_APP_RES_DECLARE(VAPP_SMS_FG, 5, "Message\\res\\")
VFX_APP_RES_DECLARE(VAPP_WAP_PUSH, 200, "Message\\res\\")
VFX_APP_RES_DECLARE(VAPP_WAP_PUSH_HEAP, 5, "Message\\res\\")
VFX_APP_RES_DECLARE(VAPP_WAP_PUSH_EXTRA_BASE, 5, "Message\\res\\")
VFX_APP_RES_DECLARE(VAPP_WAP_PUSH_FG, 5, "Message\\res\\")
VFX_APP_RES_DECLARE(VAPP_WAP_PUSH_LAUNCH_VIEWER, 10, "Message\\res\\")
VFX_APP_RES_DECLARE(VCUI_WAP_PUSH_PROV, 200, "Message\\res\\")

VFX_APP_RES_DECLARE(VCUI_SMS_COMPOSER, 200, "Message\\res\\")
VFX_APP_RES_DECLARE(VAPP_SMS_COMPOSER, 5, "Message\\res\\")

VFX_APP_RES_DECLARE(VAPP_CBS, 200, "CBApp\\res\\")
VFX_APP_RES_DECLARE(VAPP_CB_NEW_MSG, 50, "CBApp\\res\\CBNewMsg\\")
VFX_APP_RES_DECLARE(VAPP_UNIFIEDCOMPOSER, 500, "UnifiedComposer\\res\\")
VFX_APP_RES_DECLARE(VCUI_MSGCOMPOSER, 20, "UnifiedComposer\\res\\")
VFX_APP_RES_DECLARE(VCUI_UC_MMS_SRV, 5, "UnifiedComposer\\res\\")
VFX_APP_RES_DECLARE(VCUI_EMAILCOMPOSER, 20, "UnifiedComposer\\res\\")
VFX_APP_RES_DECLARE(VCUI_SMSONLYCOMPOSER, 20, "UnifiedComposer\\res\\")
VFX_APP_RES_DECLARE(VCUI_LEMEICOMPOSER, 20, "UnifiedComposer\\res\\")
VFX_APP_RES_DECLARE(VAPP_UCM, 150, "ucm\\res\\")
VFX_APP_RES_DECLARE(VAPP_CALLSET, 200, "CallSetting\\res\\")
VFX_APP_RES_DECLARE(VAPP_SS, 50, "SupplementaryService\\res\\")
#if (MMI_MAX_SIM_NUM >= 2)
VFX_APP_RES_DECLARE(VAPP_SS_2, 10, "SupplementaryService\\res\\")
#if (MMI_MAX_SIM_NUM >= 3)
VFX_APP_RES_DECLARE(VAPP_SS_3, 10, "SupplementaryService\\res\\")
#if (MMI_MAX_SIM_NUM >= 4)
VFX_APP_RES_DECLARE(VAPP_SS_4, 10, "SupplementaryService\\res\\")
#endif /* (MMI_MAX_SIM_NUM >= 4) */
#endif /* (MMI_MAX_SIM_NUM >= 3) */
#endif /* (MMI_MAX_SIM_NUM >= 2) */
VFX_APP_RES_DECLARE(VAPP_CALLLOG, 100, "CallLog\\res\\")
VFX_APP_RES_DECLARE(VAPP_DEVICE, 30, "DeviceApp\\res\\")
VFX_APP_RES_DECLARE(VAPP_BROWSER, 300, "Browser\\res\\")
#ifdef __MMI_BROWSER_2__
VFX_APP_RES_DECLARE(VCUI_BKM, 30, "Browser\\res\\")
#endif
VFX_APP_RES_DECLARE(VAPP_GPS_SETTING, 100, "GPSSetting\\res\\")
VFX_APP_RES_DECLARE(VCUI_GPS_SETTING_OTAP, 5, "GPSSetting\\res\\")
VFX_APP_RES_DECLARE(VAPP_GPS_MGR, 5, "GPSSetting\\res\\")

#ifdef __MMI_GALLERY_SLIM__
VFX_APP_RES_DECLARE(VAPP_GALLERY, 140, "GallerySlim\\res\\")
VFX_APP_RES_DECLARE(VCUI_GALLERY_WALLPAPER_PICKER, 5, "GallerySlim\\res\\")
VFX_APP_RES_DECLARE(VCUI_GALLERY_IMAGE_VIEWER, 5, "GallerySlim\\res\\")
VFX_APP_RES_DECLARE(VCUI_GALLERY_VIDEO_PLAYER, 30, "GallerySlim\\res\\")
VFX_APP_RES_DECLARE(VCUI_GALLERY_IMAGE_PICKER, 10, "GallerySlim\\res\\")
VFX_APP_RES_DECLARE(VCUI_GALLERY_VIDEO_PICKER, 10, "GallerySlim\\res\\")
VFX_APP_RES_DECLARE(VAPP_GALLERY_STREAM_PLAYER, 30, "GallerySlim\\res\\")
VFX_APP_RES_DECLARE(VAPP_GALLERY_IMAGE_VIEWER, 50, "GallerySlim\\res\\")
VFX_APP_RES_DECLARE(VAPP_GALLERY_VIDEO_PLAYER, 30, "GallerySlim\\res\\")
#ifdef __MMI_VIDEO_PDL_YOUTUBE__
VFX_APP_RES_DECLARE(VAPP_GALLERY_YOUTUBE_PGDL_PLAYER, 30, "GallerySlim\\res\\")
#endif
#else
#ifdef __COSMOS_3D_V10__
VFX_APP_RES_DECLARE(VAPP_GALLERY, 200, "Gallery\\res\\")
#else
VFX_APP_RES_DECLARE(VAPP_GALLERY, 140, "Gallery\\res\\")
#endif
VFX_APP_RES_DECLARE(VCUI_GALLERY_WALLPAPER_PICKER, 5, "Gallery\\res\\")
VFX_APP_RES_DECLARE(VCUI_GALLERY_IMAGE_VIEWER, 5, "Gallery\\res\\")
VFX_APP_RES_DECLARE(VCUI_GALLERY_VIDEO_PLAYER, 30, "Gallery\\res\\")
VFX_APP_RES_DECLARE(VCUI_GALLERY_IMAGE_PICKER, 10, "Gallery\\res\\")
VFX_APP_RES_DECLARE(VCUI_GALLERY_VIDEO_PICKER, 10, "Gallery\\res\\")
VFX_APP_RES_DECLARE(VAPP_GALLERY_STREAM_PLAYER, 30, "Gallery\\res\\")
VFX_APP_RES_DECLARE(VAPP_GALLERY_IMAGE_VIEWER, 50, "Gallery\\res\\")
VFX_APP_RES_DECLARE(VAPP_GALLERY_VIDEO_PLAYER, 30, "Gallery\\res\\")
#ifdef __MMI_VIDEO_PDL_YOUTUBE__
VFX_APP_RES_DECLARE(VAPP_GALLERY_YOUTUBE_PGDL_PLAYER, 30, "Gallery\\res\\")
#endif
#endif
#ifdef __MMI_3D_MEDIA_CENTER__
VFX_APP_RES_DECLARE(VAPP_MEDIA_CENTER, 100, "MediaCenter\\res\\")
#endif

VFX_APP_RES_DECLARE(APP_BLUETOOTH, 20,    "Bluetooth\\res\\")
VFX_APP_RES_DECLARE(VAPP_BT_MAIN,    100,    "Bluetooth\\res\\")
VFX_APP_RES_DECLARE(VAPP_BT_SEND,    20,     "Bluetooth\\res")
VFX_APP_RES_DECLARE(VAPP_BT_PASSKEY_NOTIFY,    10,    "Bluetooth\\res\\")
VFX_APP_RES_DECLARE(VAPP_BT_FMGR_LAUNCHER,    10,    "Bluetooth\\res\\")
VFX_APP_RES_DECLARE(VCUI_BT_POWERON, 10,    "Bluetooth\\res\\")
VFX_APP_RES_DECLARE(VCUI_BT_SELDEV,  10,    "Bluetooth\\res\\")
VFX_APP_RES_DECLARE(VCUI_BT_SEND_PREPARE, 10, "Bluetooth\\res\\")
VFX_APP_RES_DECLARE(VAPP_BT_OBEX_AUTHTICATION, 10, "Bluetooth\\res\\")


VFX_APP_RES_DECLARE(VAPP_IMGEDT, 100, "ImageEditor\\res\\")
VFX_APP_RES_DECLARE(VCUI_IMGCLIP, 20, "ImageEditor\\res\\")

VFX_APP_RES_DECLARE(VAPP_SOUND_SETTINGS, 40, "SoundSettings\\res\\")
VFX_APP_RES_DECLARE(VAPP_VOL_DIALOG, 30, "SoundSettings\\res\\")
VFX_APP_RES_DECLARE(VCUI_TONE_SELECTOR, 30, "SoundSettings\\res\\")

#ifdef __MMI_FM_RADIO_SLIM__
VFX_APP_RES_DECLARE(VAPP_FM_RADIO, 50, "FMRadioSlim\\res\\")
#else
VFX_APP_RES_DECLARE(VAPP_FM_RADIO, 50, "FMRadio\\res\\")
#endif

VFX_APP_RES_DECLARE(VAPP_SCREEN_LOCK, 20, "ScreenLock\\res\\")

#ifdef __MMI_VUI_SETTING_SCREEN_LOCK_SELECTION__
VFX_APP_RES_DECLARE(VAPP_SCREEN_LOCK_SHUTTLE, 5, "ScreenLockShuttle\\res\\")
#endif
#ifdef __MMI_VUI_SCREEN_LOCK_STEAM__
VFX_APP_RES_DECLARE(VAPP_SCREEN_LOCK_STEAM, 50, "ScreenLockSteam\\res\\")
#endif
#ifdef __MMI_VUI_SCREEN_LOCK_COSMOS__
VFX_APP_RES_DECLARE(VAPP_SCREEN_LOCK_COSMOS, 50, "ScreenLockCosmos\\res\\")
#endif
#ifdef __MMI_VUI_SCREEN_LOCK_PATTERN__
VFX_APP_RES_DECLARE(VAPP_SCREEN_LOCK_PATTERN, 20, "ScreenLockPattern\\res\\")
#endif
#ifdef __MMI_VUI_SCREEN_LOCK_PAINTING__
VFX_APP_RES_DECLARE(VAPP_SCREEN_LOCK_PAINTING, 50, "ScreenLockPainting\\res\\")
#endif
#ifdef __MMI_VUI_SCREEN_LOCK_ZIPPER__
VFX_APP_RES_DECLARE(VAPP_SCREEN_LOCK_ZIPPER, 10, "ScreenLockZipper\\res\\")
#endif
#ifdef __MMI_VUI_SCREEN_LOCK_RHYTHM__
VFX_APP_RES_DECLARE(VAPP_SCREEN_LOCK_RHYTHM, 20, "ScreenLockRhythm\\res\\")
#endif

VFX_APP_RES_DECLARE(VAPP_SETTING, 240, "setting\\res\\")
VFX_APP_RES_DECLARE(VCUI_LANGUAGE_SETTING, 5, "setting\\res\\")
VFX_APP_RES_DECLARE(VCUI_PEN_CALIBRATION, 10, "setting\\res\\")
VFX_APP_RES_DECLARE(VCUI_WALLPAPER_SETTING, 10, "setting\\res\\")
VFX_APP_RES_DECLARE(VAPP_NETWORK_CHECKING, 10, "setting\\res\\")
VFX_APP_RES_DECLARE(VAPP_PEN_CALIBRATION, 10, "setting\\res\\")
VFX_APP_RES_DECLARE(VCUI_MOBILE_NW_SETTING, 50, "setting\\res\\")
VFX_APP_RES_DECLARE(VAPP_CERTMAN, 200, "Certman\\res\\")

#if defined(__MMI_THEMES_APPLICATION__) || defined(__MMI_VUI_APP_ICON_ROBOT__) || defined(__MMI_VUI_APP_ICON_MM__) || defined(__MMI_VUI_DOWNLOADABLE_APP_ICON__) \
    || defined(__MMI_VUI_SETTING_SCREEN_LOCK_SELECTION__) || defined(__MMI_VUI_SETTING_LAUNCHER_SELECTION__) 
VFX_APP_RES_DECLARE(VAPP_LAUNCHER_SETTING, 20, "setting\\res\\")
#endif

#ifdef __MMI_VUI_SETTING_SCREEN_LOCK_SELECTION__
VFX_APP_RES_DECLARE(VAPP_SCR_LOCK_SETTING, 20, "setting\\res\\")
#endif

VFX_APP_RES_DECLARE(VAPP_DLWP_SETTING,5, "setting\\res\\")

#ifdef __MMI_COSMOS_MOVIE_THEATER__
VFX_APP_RES_DECLARE(VAPP_MOVIE_THEATER, 20, "MovieTheater\\res\\")
#endif

#ifdef __MMI_SOUNDREC_SLIM__
VFX_APP_RES_DECLARE(VAPP_SOUNDREC, 50, "SoundRecSlim\\res\\")
#else
VFX_APP_RES_DECLARE(VAPP_SOUNDREC, 50, "SoundRec\\res\\")
VFX_APP_RES_DECLARE(VCUI_SOUNDREC, 20, "SoundRec\\res\\")
#endif

#if defined(__MMI_MUSIC_PLAYER_SLIM__)
VFX_APP_RES_DECLARE(VAPP_MUSIC_PLAYER_SLIM, 200, "MusicPlayerSlim\\res\\")
VFX_APP_RES_DECLARE(VAPP_MUSIC_SLIM_SINGLE_PLAYER, 10, "MusicPlayerSlim\\res\\")
VFX_APP_RES_DECLARE(VCUI_MUSIC_PLAYER, 20, "MusicPlayerSlim\\res\\")
#else
VFX_APP_RES_DECLARE(VAPP_MUSIC_PLAYER, 200, "MusicPlayer\\res\\")
VFX_APP_RES_DECLARE(VAPP_MUSIC_SINGLE_PLAYER, 10, "MusicPlayer\\res\\")
VFX_APP_RES_DECLARE(VCUI_MUSIC_PLAYER, 20, "MusicPlayer\\res\\")
#endif

#if defined(__LOW_COST_SUPPORT_COMMON__)
   #if defined(__MMI_CAMCO_SLIM__)
   		VFX_APP_RES_DECLARE(VAPP_CAMCO, 500, "CamcorderSlim\\res\\")
   		VFX_APP_RES_DECLARE(VAPP_CAMCO_D, 5, "CamcorderSlim\\res\\")
		VFX_APP_RES_DECLARE(VCUI_STANDARD_CAMERA, 20, "CamcorderSlim\\res\\")
		VFX_APP_RES_DECLARE(VCUI_STANDARD_RECORDER, 20, "CamcorderSlim\\res\\")
		VFX_APP_RES_DECLARE(VCUI_SLIM_CAMERA, 20, "CamcorderSlim\\res\\")
   #else
		VFX_APP_RES_DECLARE(VAPP_CAMCO, 500, "CamcorderExpress\\res\\")
		VFX_APP_RES_DECLARE(VAPP_CAMCO_D, 5, "CamcorderExpress\\res\\")
		VFX_APP_RES_DECLARE(VCUI_STANDARD_CAMERA, 20, "CamcorderExpress\\res\\")
		VFX_APP_RES_DECLARE(VCUI_STANDARD_RECORDER, 20, "CamcorderExpress\\res\\")
		VFX_APP_RES_DECLARE(VCUI_SLIM_CAMERA, 20, "CamcorderExpress\\res\\")
   #endif
#else
VFX_APP_RES_DECLARE(VAPP_CAMCO, 500, "Camcorder\\res\\")
VFX_APP_RES_DECLARE(VCUI_CAMCO, 20, "Camcorder\\res\\")
VFX_APP_RES_DECLARE(VCUI_STANDARD_CAMERA, 20, "Camcorder\\res\\")
VFX_APP_RES_DECLARE(VCUI_STANDARD_RECORDER, 20, "Camcorder\\res\\")
VFX_APP_RES_DECLARE(VCUI_SLIM_CAMERA, 20, "Camcorder\\res\\")
#endif

VFX_APP_RES_DECLARE(VAPP_AUTOCAP, 50, "AutoramaCam\\res\\")
VFX_APP_RES_DECLARE(VAPP_3D_CAMERA, 50, "AutoramaCam\\res\\")
VFX_APP_RES_DECLARE(VAPP_AUTOCAP_COMMON, 500, "AutoramaCam\\res\\")

#ifdef __MMI_NSS_SUPPORT__
VFX_APP_RES_DECLARE(VAPP_NOTIFICATION_SETTING, 30, "NotificationSetting\\Res\\")
#endif // __MMI_NSS_SUPPORT__

#if defined(__MMI_VUI_LAUNCHER_COSMOS__) || (defined(__MMI_VUI_WIDGET_FACTORY__) && defined(__COSMOS_MMI_PACKAGE__))
VFX_APP_RES_DECLARE(VAPP_LAUNCHER_COSMOS_MM, 50, "LauncherCosmos\\MM\\res\\")
#endif
#if defined(__MMI_VUI_LAUNCHER_COSMOS__) && defined(__MMI_VUI_MAIN_MENU_SWITCH_EFFECT__)
VFX_APP_RES_DECLARE(VAPP_LAUNCHER_COSMOS_MM_BARREL_SETTING, 20, "LauncherCosmos\\MM\\res\\")
#endif

#ifdef __MMI_VUI_LAUNCHER_MM__
VFX_APP_RES_DECLARE(VAPP_LAUNCHER_MM, 50, "LauncherMM\\res\\")
#ifdef __MMI_VUI_MAIN_MENU_SWITCH_EFFECT__
VFX_APP_RES_DECLARE(VAPP_LAUNCHER_MM_BARREL_SETTING, 20, "LauncherMM\\res\\")
#endif
#endif

VFX_APP_RES_DECLARE(VAPP_SAT, 20, "sat\\res\\")

VFX_APP_RES_DECLARE(VAPP_CALCULATOR, 200, "Calculator\\res\\")
VFX_APP_RES_DECLARE(VAPP_WGTINST, 50, "WidgetInstaller\\res\\")
VFX_APP_RES_DECLARE(VAPP_WIDGET_DELEGATOR, 50, "WidgetDelegator\\res\\")
VFX_APP_RES_DECLARE(VAPP_WIDGET_DELEGATOR_IDLE, 5, "WidgetDelegator\\res\\")
VFX_APP_RES_DECLARE(VAPP_WIDGET_ADP, 5, "WidgetDelegator\\res\\")
VFX_APP_RES_DECLARE(VAPP_WIDGET_CUI, 5, "WidgetDelegator\\res\\")
VFX_APP_RES_DECLARE(VAPP_CONVERTER, 50, "Converter\\res\\")

VFX_APP_RES_DECLARE(VAPP_CONTACT, 500, "Contact\\ContactRes\\")
VFX_APP_RES_DECLARE(VAPP_DIALER, 100, "Dialer\\res\\")
VFX_APP_RES_DECLARE(VCUI_CONTACT_LIST, 20, "Contact\\ContactRes\\")
VFX_APP_RES_DECLARE(VCUI_CONTACT_SAVE, 20, "Contact\\ContactRes\\")
VFX_APP_RES_DECLARE(VCUI_CONTACT_SAVE2, 20, "Contact\\ContactRes\\")
VFX_APP_RES_DECLARE(VCUI_CONTACT_VIEW, 20, "Contact\\ContactRes\\")
VFX_APP_RES_DECLARE(VCUI_SIM_LOCATE, 20, "Contact\\ContactRes\\")
VFX_APP_RES_DECLARE(VCUI_CONTACT_ADPTER, 20, "Contact\\ContactRes\\")
VFX_APP_RES_DECLARE(VCUI_CONTACT_ADPTER_NOTIFY, 10, "Contact\\ContactRes\\")
VFX_APP_RES_DECLARE(VCUI_CONTACT_VCARD_VIEW, 10, "Contact\\ContactRes\\")
VFX_APP_RES_DECLARE(VCUI_CONTACT_SETTING, 10, "Contact\\ContactRes\\")
VFX_APP_RES_DECLARE(VCUI_DIALER_MAKE_CALL, 10, "Dialer\\res\\")

#ifdef __OP02_0200__
VFX_APP_RES_DECLARE(VAPP_MOBILE_INTERNET, 5, "OPMmApp\\OP02MmApp\\OP02MmAppRes\\")
VFX_APP_RES_DECLARE(VAPP_WO_STORE, 5, "OPMmApp\\OP02MmApp\\OP02MmAppRes\\")
VFX_APP_RES_DECLARE(VAPP_ONLINE_SALES, 5, "OPMmApp\\OP02MmApp\\OP02MmAppRes\\")
VFX_APP_RES_DECLARE(VAPP_PUSH_MAIL, 5, "OPMmApp\\OP02MmApp\\OP02MmAppRes\\")
VFX_APP_RES_DECLARE(VAPP_USIM_APPLICATION, 5, "OPMmApp\\OP02MmApp\\OP02MmAppRes\\")
VFX_APP_RES_DECLARE(VAPP_WO_READ, 5, "OPMmApp\\OP02MmApp\\OP02MmAppRes\\")
VFX_APP_RES_DECLARE(VAPP_MOBILE_TV, 5, "OPMmApp\\OP02MmApp\\OP02MmAppRes\\")
VFX_APP_RES_DECLARE(VAPP_MOBILE_MUSIC, 5, "OPMmApp\\OP02MmApp\\OP02MmAppRes\\")
VFX_APP_RES_DECLARE(VAPP_MOBILE_GUIDE, 5, "OPMmApp\\OP02MmApp\\OP02MmAppRes\\")
#endif /* __OP02_0200__ */

#ifdef __OP01_3G__
VFX_APP_RES_DECLARE(VAPP_FETION, 5, "OPMmApp\\OP01MmApp\\OP01MmAppRes\\")
VFX_APP_RES_DECLARE(VAPP_MUSIC_WALKMAN, 5, "OPMmApp\\OP01MmApp\\OP01MmAppRes\\")
VFX_APP_RES_DECLARE(VAPP_MOBILE_STOCK, 5, "OPMmApp\\OP01MmApp\\OP01MmAppRes\\")
VFX_APP_RES_DECLARE(VAPP_MOBILE_MAP, 5, "OPMmApp\\OP01MmApp\\OP01MmAppRes\\")
VFX_APP_RES_DECLARE(VAPP_MOBILE_MARKET, 5, "OPMmApp\\OP01MmApp\\OP01MmAppRes\\")
VFX_APP_RES_DECLARE(VAPP_MOBILE_READ, 5, "OPMmApp\\OP01MmApp\\OP01MmAppRes\\")
VFX_APP_RES_DECLARE(VAPP_MOBILE_PORTAL, 5, "OPMmApp\\OP01MmApp\\OP01MmAppRes\\")
#endif /* __OP01_3G__ */

VFX_APP_RES_DECLARE(VAPP_DTCNT, 80, "Dataaccount\\res\\")
VFX_APP_RES_DECLARE(VCUI_DTCNT, 20, "Dataaccount\\res\\")
VFX_APP_RES_DECLARE(VAPP_DTCNT_SIM_PREFER, 10, "Dataaccount\\res\\")
VFX_APP_RES_DECLARE(VAPP_DTCNT_PROV, 5, "Dataaccount\\res\\")
VFX_APP_RES_DECLARE(VAPP_CBM, 30, "Cbm\\res\\")
VFX_APP_RES_DECLARE(VCUI_CBM, 5, "Cbm\\res\\")

#ifdef __MMI_CBM_CONNECTION_MANAGER__
VFX_APP_RES_DECLARE(VAPP_CNMGR, 30, "setting\\res\\")
#endif

VFX_APP_RES_DECLARE(VAPP_PIANO, 40, "Piano\\res\\")

#if defined(OPERA_BROWSER)
VFX_APP_RES_DECLARE(VCUI_BKM, 10, "BookmarkCui\\res\\")
#endif /* defined(OPERA_BROWSER) */

#ifdef __MMI_OP01_WIFI__
VFX_APP_RES_DECLARE(VAPP_WLAN_AUTH, 100, "Wlan\\res\\")
#endif

VFX_APP_RES_DECLARE(VAPP_DATA_ACCOUNT_WLAN, 300, "Wlan\\res\\")
VFX_APP_RES_DECLARE(VCUI_DATA_ACCOUNT_WLAN, 10, "Wlan\\res\\")
VFX_APP_RES_DECLARE(VCUI_DATA_ACCOUNT_WLAN_SETTING, 10, "Wlan\\res\\")

VFX_APP_RES_DECLARE(VAPP_NOTES, 100, "Notes\\NotesRes\\")
VFX_APP_RES_DECLARE(VCUI_WAP_PROV, 60, "UPPApp\\res\\")
VFX_APP_RES_DECLARE(VAPP_JAVA, 500, "JavaApp\\res\\")
#if defined(__J2ME__)
VFX_APP_RES_DECLARE(VAPP_JAVA_TEXTBOX, 2, "JavaApp\\res\\")
#endif
VFX_APP_RES_DECLARE(VAPP_EMAIL, 300, "Email\\res\\")
VFX_APP_RES_DECLARE(VCUI_EMAIL_OTAP, 5, "Email\\res\\")
VFX_APP_RES_DECLARE(VAPP_RMGR, 200, "RightsMgr\\res\\")
VFX_APP_RES_DECLARE(VAPP_CCA, 100, "CCA\\Res\\")
VFX_APP_RES_DECLARE(VAPP_PROV_MSG, 20, "Message\\res\\")
VFX_APP_RES_DECLARE(VAPP_PROV_HEAP, 5, "Message\\res\\")
VFX_APP_RES_DECLARE(VAPP_PROV_EXTRA_BASE, 5, "Message\\res\\")
VFX_APP_RES_DECLARE(VAPP_PROV_FG, 5, "Message\\res\\")

#ifdef __SYNCML_SUPPORT__
VFX_APP_RES_DECLARE(VAPP_SYNC, 200, "Sync\\res\\")
VFX_APP_RES_DECLARE(VCUI_SYNC, 10, "Sync\\res\\")
VFX_APP_RES_DECLARE(VCUI_SYNC_PROV, 50, "Sync\\res\\")
#endif /*__SYNCML_SUPPORT__  */
VFX_APP_RES_DECLARE(VAPP_TETHERING, 30, "Tethering\\res\\")
VFX_APP_RES_DECLARE(VAPP_CALENDAR, 200, "calendar\\res\\")
VFX_APP_RES_DECLARE(VAPP_CALENDAR_REMINDER, 2,"calendar\\res\\")
VFX_APP_RES_DECLARE(VCUI_CAL_LIST, 10, "calendar\\res\\")
VFX_APP_RES_DECLARE(VAPP_TASK, 20, "calendar\\res\\")
VFX_APP_RES_DECLARE(VAPP_DLAGENT, 200, "DLAgent\\res\\")
VFX_APP_RES_DECLARE(VAPP_OOM_SCR, 25, "OomScr\\res\\")
VFX_APP_RES_DECLARE(VAPP_VENUS_TST_FW_1, 10, "tst_sdk\\res\\")
VFX_APP_RES_DECLARE(VAPP_VENUS_TST_FW_2, 10, "tst_sdk\\res\\")
VFX_APP_RES_DECLARE(VAPP_VENUS_TST_FW_3, 10, "tst_sdk\\res\\")
VFX_APP_RES_DECLARE(VAPP_ENGINEER_MODE, 5, "EngineerMode\\res\\")
VFX_APP_RES_DECLARE(VAPP_ATV, 500, "ATV\\res\\")
#ifdef __MMI_3D_GAME_INTERGRAFX__
VFX_APP_RES_DECLARE(VAPP_3DGAME, 5, "3DGame\\res\\")
#endif

#if defined(__MMI_EM_MISC_TOUCH_SCREEN__)
VFX_APP_RES_DECLARE(VAPP_EM_GESTURE_TEST, 10, "GestureTest\\res\\")
#endif /* defined(__MMI_EM_MISC_TOUCH_SCREEN__) */

#if defined(__MMI_VENUS_RT__) && defined(__COSMOS_MMI_PACKAGE__)
VFX_APP_RES_DECLARE(VAPP_RT, 5, "..\\..\\test\\common\\res\\")
#endif /* defined(__MMI_VENUS_RT__) && defined(__COSMOS_MMI_PACKAGE__) */

#if defined(__MMI_OP02_LEMEI_FTO__)
VFX_APP_RES_DECLARE(VAPP_LEMEI, 30, "Lemei\\res\\")
#endif

#ifdef SYNCML_DM_SUPPORT
VFX_APP_RES_DECLARE(VAPP_DM, 20, "DM\\res\\")
#ifdef __CCA_SUPPORT__
VFX_APP_RES_DECLARE(VCUI_DM_OTAP, 5, "DM\\res\\")
#endif /* __CCA_SUPPORT__ */
#endif /* SYNCML_DM_SUPPORT */

#if defined(__MMI_VIDEO_CLIPPER__)
VFX_APP_RES_DECLARE(VCUI_VIDEOCLIPPER, 20, "VideoClipper\\res\\")
VFX_APP_RES_DECLARE(VAPP_VIDEOCLIPPER_SLIDER, 20, "VideoClipper\\res\\")
VFX_APP_RES_DECLARE(VAPP_VIDEOCLIPPER, 20, "VideoClipper\\res\\")
#endif

#ifdef __MMI_THEMES_APPLICATION__
VFX_APP_RES_DECLARE(VAPP_THEME, 100, "Theme\\res\\")
#endif

#if defined(__MMI_VUI_SETTING_LAUNCHER_SELECTION__) || defined(__MMI_THEMES_APPLICATION__)\
	|| defined(__MMI_VUI_APP_ICON_ROBOT__) || defined(__MMI_VUI_APP_ICON_MM__) || defined(__MMI_VUI_DOWNLOADABLE_APP_ICON__)
VFX_APP_RES_DECLARE(VCUI_THEME_SWITCH, 2, "Theme\\res\\")
#endif 

#if defined(__MMI_VUI_APP_ICON_ROBOT__) || defined(__MMI_VUI_APP_ICON_MM__) || defined(__MMI_VUI_DOWNLOADABLE_APP_ICON__)
VFX_APP_RES_DECLARE(VAPP_THEME_APPICON, 100, "Theme\\res\\AppIcon\\")
VFX_APP_RES_DECLARE(VAPP_APP_ICON, 5, "AppIcon\\res\\")
#endif

#ifdef  __MMI_CUSTOMER_SERVICE__
/* under construction !*/
#endif

#ifdef  __MMI_MOBILE_SERVICE__
/* under construction !*/
#endif

VFX_APP_RES_DECLARE(VCUI_SSO_SETTING, 50, "SSO\\res\\")
VFX_APP_RES_DECLARE(VAPP_SSO, 50, "SSO\\res\\")
VFX_APP_RES_DECLARE(VAPP_SNS_SSO_COMMON, 20, "SSO\\res\\")

VFX_APP_RES_DECLARE(VAPP_M_SPACE, 100, "M-Space\\res\\")

#ifdef __MMI_VPP_UPGRADE__
VFX_APP_RES_DECLARE(VAPP_UPGRADE, 5, "Upgrade\\res\\")
#endif /*__MMI_VPP_UPGRADE__*/
VFX_APP_RES_DECLARE(VAPP_BROWSER_LOW_MEM, 10, "Browser\\res\\")

VFX_APP_RES_DECLARE(VAPP_MRE_APP_FMGR, 20, "AppManager\\res\\")
VFX_APP_RES_DECLARE(VAPP_MRE_APP_DIALER, 20, "AppManager\\res\\")
VFX_APP_RES_DECLARE(VAPP_MRE_APP_DTCNT, 20, "AppManager\\res\\")

#ifdef __MMI_EBOOK_READER__
MMI_RES_DECLARE(APP_EBOOK, 200, "..\\plutommi\\MMI\\EbookReader\\EbookRes\\")

#endif
