#include "MMI_features.h"
#include "custresdef.h"

<?xml version="1.0" encoding="UTF-8"?>
#ifdef __MMI_VUI_SHELL_SHORTCUTS__
<APP id="APP_VENUS_SHELL_SHORTCUTS">

#ifdef __MMI_VUI_SHELL_SHORTCUTS_SLIM__
#define SHELL_SHORTCUT_IMG_PATH CUST_IMG_PATH"\\\\MainLCD\\\\VUI\\\\Shell_Low\\\\Shortcuts\\\\"
#else /* __MMI_VUI_SHELL_SHORTCUTS_SLIM__ */
#define SHELL_SHORTCUT_IMG_PATH CUST_IMG_PATH"\\\\MainLCD\\\\VUI\\\\Shell\\\\Shortcuts\\\\"
#endif /* __MMI_VUI_SHELL_SHORTCUTS_SLIM__ */

    <!--Include Area-->

    <!-----------------------------------------------------String Resource Area----------------------------------------------------->
    <STRING id="STR_ID_SHELL_SHORTCUTS_TITLE"/>
    <STRING id="STR_ID_SHELL_SHORTCUTS_REMOVE_SHORTCUT"/>
    <STRING id="STR_ID_SHELL_SHORTCUTS_REPLACE_SHORTCUT"/>
    <STRING id="STR_ID_SHELL_SHORTCUTS_JAVA_APPS"> "Java" </STRING>
    <STRING id="STR_ID_SHELL_SHORTCUTS_BOOKMARKS"/>

    <!-----------------------------------------------------Image Resource Area------------------------------------------------------>
    <IMAGE id="IMG_ID_SHELL_SHORTCUTS_ITEM_ICON_EMPTY"> SHELL_SHORTCUT_IMG_PATH"Add.png"</IMAGE>
    <IMAGE id="IMG_ID_SHELL_SHORTCUTS_ITEM_TEXT_BG"> SHELL_SHORTCUT_IMG_PATH"Font_BG.9slice.png"</IMAGE>
    <IMAGE id="IMG_ID_SHELL_SHORTCUTS_ITEM_ICON_ADD_CONTACT"> SHELL_SHORTCUT_IMG_PATH"Add_Contact.png"</IMAGE>
    <IMAGE id="IMG_ID_SHELL_SHORTCUTS_ITEM_ICON_ADD_TASK"> SHELL_SHORTCUT_IMG_PATH"Add_Task.png"</IMAGE>
    <IMAGE id="IMG_ID_SHELL_SHORTCUTS_ITEM_ICON_ALARM"> SHELL_SHORTCUT_IMG_PATH"Alarm.png"</IMAGE>
    <IMAGE id="IMG_ID_SHELL_SHORTCUTS_ITEM_ICON_BOOKMARK"> SHELL_SHORTCUT_IMG_PATH"Bookmark.png"</IMAGE>
    <IMAGE id="IMG_ID_SHELL_SHORTCUTS_ITEM_ICON_BLUETOOTH"> SHELL_SHORTCUT_IMG_PATH"Buletooth.png"</IMAGE>
    <IMAGE id="IMG_ID_SHELL_SHORTCUTS_ITEM_ICON_CALCULATOR"> SHELL_SHORTCUT_IMG_PATH"Calculator.png"</IMAGE>
    <IMAGE id="IMG_ID_SHELL_SHORTCUTS_ITEM_ICON_CALENDAR"> SHELL_SHORTCUT_IMG_PATH"Calendar.png"</IMAGE>
    <IMAGE id="IMG_ID_SHELL_SHORTCUTS_ITEM_ICON_CAMERA"> SHELL_SHORTCUT_IMG_PATH"Camera.png"</IMAGE>
    <IMAGE id="IMG_ID_SHELL_SHORTCUTS_ITEM_ICON_EBOOK"> SHELL_SHORTCUT_IMG_PATH"Ebook.png"</IMAGE>
    <IMAGE id="IMG_ID_SHELL_SHORTCUTS_ITEM_ICON_EMAIL"> SHELL_SHORTCUT_IMG_PATH"Email.png"</IMAGE>
    <IMAGE id="IMG_ID_SHELL_SHORTCUTS_ITEM_ICON_FILE_MAN"> SHELL_SHORTCUT_IMG_PATH"File_Man.png"</IMAGE>
    <IMAGE id="IMG_ID_SHELL_SHORTCUTS_ITEM_ICON_FM_RADIO"> SHELL_SHORTCUT_IMG_PATH"FM_Radio.png"</IMAGE>
    <IMAGE id="IMG_ID_SHELL_SHORTCUTS_ITEM_ICON_JAVA_APP"> SHELL_SHORTCUT_IMG_PATH"Java_App.png"</IMAGE>
    <IMAGE id="IMG_ID_SHELL_SHORTCUTS_ITEM_ICON_MEDIA"> SHELL_SHORTCUT_IMG_PATH"Media.png"</IMAGE>
    <IMAGE id="IMG_ID_SHELL_SHORTCUTS_ITEM_ICON_MMS"> SHELL_SHORTCUT_IMG_PATH"MMS.png"</IMAGE>
    <IMAGE id="IMG_ID_SHELL_SHORTCUTS_ITEM_ICON_NEW_MSG"> SHELL_SHORTCUT_IMG_PATH"New_Msg.png"</IMAGE>
    <IMAGE id="IMG_ID_SHELL_SHORTCUTS_ITEM_ICON_NOTE"> SHELL_SHORTCUT_IMG_PATH"Note.png"</IMAGE>
    <IMAGE id="IMG_ID_SHELL_SHORTCUTS_ITEM_ICON_SETTINGS"> SHELL_SHORTCUT_IMG_PATH"Settings.png"</IMAGE>
    <IMAGE id="IMG_ID_SHELL_SHORTCUTS_ITEM_ICON_TASKS_LIST"> SHELL_SHORTCUT_IMG_PATH"Tasks_List.png"</IMAGE>
    <IMAGE id="IMG_ID_SHELL_SHORTCUTS_ITEM_ICON_VIDEO_REC"> SHELL_SHORTCUT_IMG_PATH"Video_Rec.png"</IMAGE>
    <IMAGE id="IMG_ID_SHELL_SHORTCUTS_ITEM_ICON_WIFI"> SHELL_SHORTCUT_IMG_PATH"WiFi.png"</IMAGE>
    <IMAGE id="IMG_ID_SHELL_SHORTCUTS_ITEM_ICON_WORLD_CLOCK"> SHELL_SHORTCUT_IMG_PATH"World_Clock.png"</IMAGE>

    <!------------------------------------------------------Menu Resource Area------------------------------------------------------>
    <MENUITEM id="MENU_ID_SHELL_SHORTCUTS_JAVA_APPS" str="STR_ID_SHELL_SHORTCUTS_JAVA_APPS"/>
    <MENUITEM id="MENU_ID_SHELL_SHORTCUTS_BOOKMARKS" str="STR_ID_SHELL_SHORTCUTS_BOOKMARKS"/>

    <!------------------------------------------------------Other Resource---------------------------------------------------------->

</APP>
#endif /* __MMI_VUI_SHELL_SHORTCUTS__ */
