#include "mmi_features.h"
#include "custresdef.h"

<?xml version="1.0" encoding="UTF-8"?>

#ifndef __MMI_WLAN_FEATURES__

<APP id="VAPP_DATA_ACCOUNT_WLAN"></APP>

#else

<APP id="VAPP_DATA_ACCOUNT_WLAN" 
     package_name="native.mtk.wifi" 
     name="STR_ID_VAPP_WLAN" 
     img="IMG_ID_VAPP_WLAN_MAIN_MENU" 
     launch="vapp_dtcnt_wlan_launch"  
     type="venus">
    <INCLUDE file="GlobalResDef.h"/>
    <MEMORY 
#ifdef __MMI_OP01_WIFI__
	#ifdef __CERTMAN_SUPPORT__
     	heap="512*1000" cui="max(VCUI_FMGR, VAPP_CERTMAN)"/>
	#else
     	heap="512*1000" cui="VCUI_FMGR"/>
	#endif     
#else
     heap="512*1000" />
#endif

<!-- 
**************************************** String Id ****************************************
-->
    <STRING id="STR_ID_VAPP_WLAN"/>
    <STRING id="STR_ID_VAPP_WLAN_SIGNAL_STRENGTH_0"/>
    <STRING id="STR_ID_VAPP_WLAN_SIGNAL_STRENGTH_1"/>
    <STRING id="STR_ID_VAPP_WLAN_SIGNAL_STRENGTH_2"/>
    <STRING id="STR_ID_VAPP_WLAN_SIGNAL_STRENGTH_3"/>
    <STRING id="STR_ID_VAPP_WLAN_SIGNAL_STRENGTH_4"/>
    <STRING id="STR_ID_VAPP_WLAN_NETWORK_TYPE"/>
    <STRING id="STR_ID_VAPP_WLAN_NETWORK_TYPE_INFRA"/>
    <STRING id="STR_ID_VAPP_WLAN_NETWORK_TYPE_ADHOC"/>
    <STRING id="STR_ID_VAPP_WLAN_AUTH_MODE"/>
    <STRING id="STR_ID_VAPP_WLAN_AUTH_MODE_OPEN"/>
    <STRING id="STR_ID_VAPP_WLAN_AUTH_MODE_SHARED"/>
    <STRING id="STR_ID_VAPP_WLAN_AUTH_MODE_IEEE8021X"/>
    <STRING id="STR_ID_VAPP_WLAN_AUTH_MODE_WPAPSK"/>
    <STRING id="STR_ID_VAPP_WLAN_AUTH_MODE_WPA2PSK"/>
    <STRING id="STR_ID_VAPP_WLAN_AUTH_MODE_WPAWPA2PSK"/>
    <STRING id="STR_ID_VAPP_WLAN_AUTH_MODE_WPA"/>
    <STRING id="STR_ID_VAPP_WLAN_AUTH_MODE_WPA2"/>  
    <STRING id="STR_ID_VAPP_WLAN_AUTH_MODE_WPAWPA2"/>
    <STRING id="STR_ID_VAPP_WLAN_AUTH_MODE_WPA_NONE"/>
    <STRING id="STR_ID_VAPP_WLAN_AUTH_MODE_WAPI_CERT"/>
    <STRING id="STR_ID_VAPP_WLAN_AUTH_MODE_WAPI_PSK"/>
    <STRING id="STR_ID_VAPP_WLAN_ENCRYPT_MODE"/>
    <STRING id="STR_ID_VAPP_WLAN_ENCRYPT_MODE_NONE"/>
    <STRING id="STR_ID_VAPP_WLAN_ENCRYPT_MODE_WEP"/>
    <STRING id="STR_ID_VAPP_WLAN_ENCRYPT_MODE_TKIP"/>
    <STRING id="STR_ID_VAPP_WLAN_ENCRYPT_MODE_AESCCMP"/>
    <STRING id="STR_ID_VAPP_WLAN_ENCRYPT_MODE_TKIPAESCCMP"/>     
    <STRING id="STR_ID_VAPP_WLAN_ENCRYPT_MODE_WPI"/>

    <STRING id="STR_ID_VAPP_WLAN_WEP_KEY"/>
    <STRING id="STR_ID_VAPP_WLAN_WEP_IN_USE"/>
    <STRING id="STR_ID_VAPP_WLAN_WEP_FORMAT"/>
    <STRING id="STR_ID_VAPP_WLAN_WEP_ENCRYPT"/>
    <STRING id="STR_ID_VAPP_WLAN_WEP_SETTINGS"/>
    <STRING id="STR_ID_VAPP_WLAN_WEP_INDEX_1"/>
    <STRING id="STR_ID_VAPP_WLAN_WEP_INDEX_2"/>
    <STRING id="STR_ID_VAPP_WLAN_WEP_INDEX_3"/>
    <STRING id="STR_ID_VAPP_WLAN_WEP_INDEX_4"/>
    <STRING id="STR_ID_VAPP_WLAN_WEP_ENCRYPT_64"/>
    <STRING id="STR_ID_VAPP_WLAN_WEP_ENCRYPT_128"/>
    <STRING id="STR_ID_VAPP_WLAN_WEP_FORMAT_HEX"/>
    <STRING id="STR_ID_VAPP_WLAN_WEP_FORMAT_ASCII"/>

    <STRING id="STR_ID_VAPP_WLAN_WAPI_PSK_SETTINGS"/>
    <STRING id="STR_ID_VAPP_WLAN_WAPI_CERT_SETTINGS"/>

    <STRING id="STR_ID_VAPP_WLAN_WIFI"/>
    <STRING id="STR_ID_VAPP_WLAN_CONNECTED"/>
    <STRING id="STR_ID_VAPP_WLAN_SETTING_MAIN_TEXT"/>
    <STRING id="STR_ID_VAPP_WLAN_SETTING_HINT_TEXT"/>
    <STRING id="STR_ID_VAPP_WLAN_MGR_MAIN_TEXT"/>
    <STRING id="STR_ID_VAPP_WLAN_MGR_HINT_TEXT"/>
    <STRING id="STR_ID_VAPP_WLAN_MGR_DELETE_AP"/>
    <STRING id="STR_ID_VAPP_WLAN_MGR_ADD"/>
    <STRING id="STR_ID_VAPP_WLAN_MGR_CAPTION"/>
    <STRING id="STR_ID_VAPP_WLAN_CONN_FAIL_DEFAULT"/>
    <STRING id="STR_ID_VAPP_WLAN_CONN_FAIL_INPUT"/>
    <STRING id="STR_ID_VAPP_WLAN_CONN_FAIL_EAP"/>
    <STRING id="STR_ID_VAPP_WLAN_CONN_FAIL_AUTH"/>
    <STRING id="STR_ID_VAPP_WLAN_LINK_SPEED"/>
    <STRING id="STR_ID_VAPP_WLAN_CHANNEL"/>
    <STRING id="STR_ID_VAPP_WLAN_SIGNAL_STRENGTH"/>
    <STRING id="STR_ID_VAPP_WLAN_PASSWORD_FOR_NETWORK"/>
    <STRING id="STR_ID_VAPP_WLAN_CONN_TO_NETWORK"/>
    <STRING id="STR_ID_VAPP_WLAN_JOIN"/>
    <STRING id="STR_ID_VAPP_WLAN_REMEMBERED_NETWORK"/>
    <STRING id="STR_ID_VAPP_WLAN_INVALID_KEY"/>
    <STRING id="STR_ID_VAPP_WLAN_INPUT_USERNAME"/>
    <STRING id="STR_ID_VAPP_WLAN_INPUT_PASSWORD"/>
    <STRING id="STR_ID_VAPP_WLAN_INPUT_WAI_PSK_FORMAT"/>
    <STRING id="STR_ID_VAPP_WLAN_INPUT_WAI_PSK"/>    
    <STRING id="STR_ID_VAPP_WLAN_INPUT_WAPI_USER_CERT"/>
    <STRING id="STR_ID_VAPP_WLAN_INPUT_WAPI_ASE_CERT"/>
    <STRING id="STR_ID_VAPP_WLAN_INPUT_WAPI_CA_CERT"/>
    <STRING id="STR_ID_VAPP_WLAN_INPUT_WAPI_PRIVATE_KEY"/>
    <STRING id="STR_ID_VAPP_WLAN_INPUT_INDENTIFICATION"/>

    <STRING id="STR_ID_VAPP_WLAN_EAP_TYPES"/>
    <STRING id="STR_ID_VAPP_WLAN_EAP_TLS"/>
    <STRING id="STR_ID_VAPP_WLAN_EAP_PEAP"/>
    <STRING id="STR_ID_VAPP_WLAN_EAP_TTLS"/>
    <STRING id="STR_ID_VAPP_WLAN_EAP_ERROR_AT_LEAST_ONE_TYPE"/>
    
    <STRING id="STR_ID_VAPP_WLAN_EAP_TYPE_TLS"/>
    <STRING id="STR_ID_VAPP_WLAN_EAP_TYPE_MD5"/>
    <STRING id="STR_ID_VAPP_WLAN_EAP_TYPE_PEAP"/>
    <STRING id="STR_ID_VAPP_WLAN_EAP_TYPE_TTLS"/>
    <STRING id="STR_ID_VAPP_WLAN_EAP_TYPE_SIM"/>
    <STRING id="STR_ID_VAPP_WLAN_EAP_TYPE_FAST"/>
    <STRING id="STR_ID_VAPP_WLAN_EAP_TYPE_GTC"/>
    <STRING id="STR_ID_VAPP_WLAN_EAP_TYPE_MSCHAP2"/>
    <STRING id="STR_ID_VAPP_WLAN_EAP_TYPE_PAP"/>
    <STRING id="STR_ID_VAPP_WLAN_EAP_TYPE_CHAP"/>
    <STRING id="STR_ID_VAPP_WLAN_EAP_MSCHAP"/>
    <STRING id="STR_ID_VAPP_WLAN_EAP_MSCHAP2"/>
    <STRING id="STR_ID_VAPP_WLAN_EAP_AKA"/>
    
    <STRING id="STR_ID_VAPP_WLAN_MGR_CHANGE_PRIORITY"/>
    <STRING id="STR_ID_VAPP_WLAN_MGR_MULTI_DELETE"/>
    <STRING id="STR_ID_VAPP_WLAN_MGR_NOT_ALLOW_EDIT"/>
    <STRING id="STR_ID_VAPP_WLAN_MGR_NO_NETWORK"/>
    <STRING id="STR_ID_VAPP_WLAN_ERR_NO_AP_SELECTED"/>
    <STRING id="STR_ID_VAPP_WLAN_ERR_INVALID_NAME"/>
    <STRING id="STR_ID_VAPP_WLAN_ERR_INVALID_SSID"/>
    <STRING id="STR_ID_VAPP_WLAN_ERR_AP_EXISTED"/>
    <STRING id="STR_ID_VAPP_WLAN_ERR_INVALID_WEP_KEY"/>
    <STRING id="STR_ID_VAPP_WLAN_ERR_INVALID_HOMEPAGE"/>
    <STRING id="STR_ID_VAPP_WLAN_ERR_INVALID_IP_ADDR"/>
    <STRING id="STR_ID_VAPP_WLAN_ERR_INVALID_NETMASK"/>
    <STRING id="STR_ID_VAPP_WLAN_ERR_INVALID_GATEWAY"/>
    <STRING id="STR_ID_VAPP_WLAN_ERR_INVALID_PRIMARY_DNS"/>
    <STRING id="STR_ID_VAPP_WLAN_ERR_INVALID_SECONDARY_DNS"/>
    <STRING id="STR_ID_VAPP_WLAN_ERR_INVALID_PROXY_ADDR"/>
    <STRING id="STR_ID_VAPP_WLAN_ERR_INVALID_PROXY_PORT"/>
    <STRING id="STR_ID_VAPP_WLAN_ERR_IP_ADDR_CONFLICT"/>
    <STRING id="STR_ID_VAPP_WLAN_ERR_EMPTY_PROXY_PORT"/>
    <STRING id="STR_ID_VAPP_WLAN_ERR_DEFINE_NETWORK_FIRST"/>
    <STRING id="STR_ID_VAPP_WLAN_ERR_AP_NOT_EXISTED"/>
    <STRING id="STR_ID_VAPP_WLAN_ERR_CHIP_INVAILD"/>
    
    <STRING id="STR_ID_VCUI_WLAN_TITLE"/>
    <STRING id="STR_ID_VCUI_WLAN_CHOOSE_ANOTHER_AP"/>
    <STRING id="STR_ID_VCUI_WLAN_NO_AVAILABLE_AP"/>
    
    <STRING id="STR_ID_VAPP_WLAN_ADD_AP_TITLE"/>
    <STRING id="STR_ID_VAPP_WLAN_ADD_AP_SSID"/>
    <STRING id="STR_ID_VAPP_WLAN_ADD_AP_HINT_TEXT"/>
    <STRING id="STR_ID_VAPP_WLAN_FUNC_BAR_PREV"/>
    <STRING id="STR_ID_VAPP_WLAN_FUNC_BAR_NEXT"/>
    <STRING id="STR_ID_VAPP_WLAN_EDIT_AP_TITLE"/>
    <STRING id="STR_ID_VAPP_WLAN_EDIT_AP_NAME"/>
    <STRING id="STR_ID_VAPP_WLAN_EDIT_BASIC_SETTING"/>
    <STRING id="STR_ID_VAPP_WLAN_EDIT_OTHER_SETTING"/>
    <STRING id="STR_ID_VAPP_WLAN_EDIT_TCPIP_SETTING"/>
    <STRING id="STR_ID_VAPP_WLAN_EDIT_ADVANCED_SETTING"/>    
    <STRING id="STR_ID_VAPP_WLAN_EDIT_USE_DHCP"/>
    <STRING id="STR_ID_VAPP_WLAN_EDIT_IP_ADDR"/>
    <STRING id="STR_ID_VAPP_WLAN_EDIT_NETMASK"/>
    <STRING id="STR_ID_VAPP_WLAN_EDIT_GATEWAY"/>
    <STRING id="STR_ID_VAPP_WLAN_EDIT_DNS1"/>
    <STRING id="STR_ID_VAPP_WLAN_EDIT_DNS2"/>    
    <STRING id="STR_ID_VAPP_WLAN_EDIT_HOME_PAGE"/>
    <STRING id="STR_ID_VAPP_WLAN_EDIT_USE_PROXY"/>
    <STRING id="STR_ID_VAPP_WLAN_EDIT_PROXY_ADDR"/>
    <STRING id="STR_ID_VAPP_WLAN_EDIT_PROXY_PORT"/>
    <STRING id="STR_ID_VAPP_WLAN_EDIT_PROXY_USER_NAME"/>
    <STRING id="STR_ID_VAPP_WLAN_EDIT_PROXY_PASSWORD"/>    
    <STRING id="STR_ID_VAPP_WLAN_MAC_ADDR"/>
    <STRING id="STR_ID_VAPP_WLAN_PRE_SHARE_KEY"/>
    <STRING id="STR_ID_VAPP_WLAN_TURN_OFF"/>
    <STRING id="STR_ID_VAPP_WLAN_TURN_OFF_HOT_SPOT"/>
    <STRING id="STR_ID_VAPP_WLAN_DELETE_SELECTED_AP"/>
       
    <STRING id="STR_ID_VAPP_WLAN_CONNECT_TYPE_POPUP_TITLE"/>
    <STRING id="STR_ID_VAPP_WLAN_WPS_CONNECT"/>
    <STRING id="STR_ID_VAPP_WLAN_WPS_CONNECT_DESCRIPTION"/>
    <STRING id="STR_ID_VAPP_WLAN_PIN"/>
    <STRING id="STR_ID_VAPP_WLAN_PBC"/>
    <STRING id="STR_ID_VAPP_WLAN_SELECT"/>  
    <STRING id="STR_ID_VAPP_WLAN_TIME_LEFT"/>
    <STRING id="STR_ID_VAPP_WLAN_TIME_MINS"/>
    <STRING id="STR_ID_VAPP_WLAN_TIME_MIN"/>
    <STRING id="STR_ID_VAPP_WLAN_TIME_SECS"/>
    <STRING id="STR_ID_VAPP_WLAN_TIME_SEC"/>
    <STRING id="STR_ID_VAPP_WLAN_PIN_DESCRIPTION"/>
    <STRING id="STR_ID_VAPP_WLAN_WPS_OVERLAP"/>
    
    <STRING id="STR_ID_VAPP_WLAN_NETWORK_NOTI"/>
    <STRING id="STR_ID_VAPP_WLAN_AUTO_CONN"/>
     
    <STRING id="STR_ID_VAPP_WLAN_MGR_REMEMBERED_NETWORK"/> 
    <STRING id="STR_ID_VAPP_WLAN_MGR_BLOCKED_NETWORK"/>
    <STRING id="STR_ID_VAPP_WLAN_MGR_FORGET_NETWORK"/> 
    <STRING id="STR_ID_VAPP_WLAN_CHINA_MOBILE"/> 
    <STRING id="STR_ID_VAPP_WLAN_NON_PROXY_ADDRESSES"/> 
    <STRING id="STR_ID_VAPP_WLAN_REMEMBER_MAIN_TEXT"/>  
    <STRING id="STR_ID_VAPP_WLAN_BLOCK_MAIN_TEXT"/>  
    <STRING id="STR_ID_VAPP_WLAN_NON_PROXY_MAIN_TEXT"/>   
    <STRING id="STR_ID_VAPP_WLAN_ADD_ADDRESS"/> 
    <STRING id="STR_ID_VAPP_WLAN_EDIT_ADDRESS"/>   
    <STRING id="STR_ID_VAPP_WLAN_INPUT_URL_ADDRESS"/>     
    <STRING id="STR_ID_VAPP_WLAN_ERR_ADDRESS_EXISTED"/>      
    <STRING id="STR_ID_VAPP_WLAN_LOGIN_FAILED"/>  
    <STRING id="STR_ID_VAPP_WLAN_LOGIN_SUCCESS"/>   
    <STRING id="STR_ID_VAPP_WLAN_ERR_ADD_DEFAULT_AP_TO_BK"/>      
    <STRING id="STR_ID_VAPP_WLAN_ERROR_ADD_DEFAULT_AP"/>  
    <STRING id="STR_ID_VAPP_WLAN_DELETE_ADDRESS"/> 
    <STRING id="STR_ID_VAPP_WLAN_NO_ADDRESS"/>
    <STRING id="STR_ID_VAPP_WLAN_ERR_INVALID_ADDRESS"/>   
    <STRING id="STR_ID_VAPP_WLAN_MGR_DELETE_REMEMBER_AP"/>     
    <STRING id="STR_ID_VAPP_WLAN_MGR_DELETE_BLOCK_AP"/> 
    <STRING id="STR_ID_VAPP_WLAN_ERROR_EDIT_DEFAULT_AP"/>
    <STRING id="STR_ID_VAPP_WLAN_ADD_ADDRESS_HINT_TEXT"/> 
        
    <STRING id="STR_ID_VAPP_WLAN_WAPI_CERT_MGR"/>
    <STRING id="STR_ID_VAPP_WLAN_LOAD_WAPI_CERT"/>
    <STRING id="STR_ID_VAPP_WLAN_UNLOAD_WAPI_CERT"/>  
		<STRING id="STR_ID_VAPP_WLAN_ERROR_CONNECT_WAPI_NETWORK_FAIL"/> 
		<STRING id="STR_ID_VAPP_WLAN_NO_WLAN_TO_CELLULAR"/> 
 		<STRING id="STR_ID_VAPP_WLAN_ALWAYS_ASK"/> 	
 		<STRING id="STR_ID_VAPP_WLAN_NO_MORE_ASK"/> 	
 	
    <STRING id="STR_ID_VAPP_WLAN_IN_FLIGHT_MODE_ASK"/> 	
    <STRING id="STR_ID_VAPP_WLAN_IN_FLIGHT_MODE_TURN_ON"/> 
 
    <STRING id="STR_ID_VAPP_WLAN_SLEEP_POLICY"/>         	   
    <STRING id="STR_ID_VAPP_WLAN_SLEEP_POLICY_NEVER"/>     
    <STRING id="STR_ID_VAPP_WLAN_SLEEP_POLICY_NEVER_USB_PLUG_IN"/>  
    <STRING id="STR_ID_VAPP_WLAN_SLEEP_POLICY_SCREEN_TURN_OFF"/>
            
    <STRING id="STR_ID_VAPP_WLAN_ERR_INVLALID_AUTH_MODE"/>     
    
<!-- 
**************************************** Image section ****************************************
-->
    <THEME>
        <IMAGE id="IMG_ID_VAPP_WLAN_MAIN_MENU" desc="Main menu wireless lan icon">RES_IMG_ROOT"\\\\"__MMI_MAINMENU_ICON_DEFAULT_PATH__"\\\\WiFi.png"</IMAGE>
    </THEME>
    <IMAGE id="IMG_ID_VAPP_WLAN_STATION_ONE">RES_IMG_ROOT"\\\\Network\\\\OpenWifi_1.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_WLAN_STATION_SND">RES_IMG_ROOT"\\\\Network\\\\OpenWifi_2.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_WLAN_STATION_TRD">RES_IMG_ROOT"\\\\Network\\\\OpenWifi_3.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_WLAN_STATION_FUR">RES_IMG_ROOT"\\\\Network\\\\OpenWifi_4.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_WLAN_SECURED_STATION_ONE">RES_IMG_ROOT"\\\\Network\\\\EncryptWifi_1.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_WLAN_SECURED_STATION_SND">RES_IMG_ROOT"\\\\Network\\\\EncryptWifi_2.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_WLAN_SECURED_STATION_TRD">RES_IMG_ROOT"\\\\Network\\\\EncryptWifi_3.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_WLAN_SECURED_STATION_FUR">RES_IMG_ROOT"\\\\Network\\\\EncryptWifi_4.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_WLAN_CHANGE_PRIORITY">RES_IMG_ROOT"\\\\Settings\\\\ToolbarIcon\\\\ChangePriority.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_WLAN_EDIT_EAP_SETTING">RES_THEME_ROOT"\\\\Default\\\\Common\\\\Button\\\\Edit.png"</IMAGE>
#ifdef __MMI_OP01_WIFI__           
    <IMAGE id="IMG_ID_VAPP_WLAN_REMEMBER_NETWORK">RES_IMG_ROOT"\\\\Settings\\\\ToolbarIcon\\\\RememberedNetworks.png"</IMAGE>
    <IMAGE id="IMG_ID_VAPP_WLAN_BLOCK_NETWORK">RES_IMG_ROOT"\\\\Settings\\\\ToolbarIcon\\\\BlockedNetworks.png"</IMAGE>
#endif    
<!-- 
**************************************** Callback Manager Receiver ****************************************
-->
    <RECEIVER id="EVT_ID_SRV_DTCNT_WLAN_CONN_IND" proc="HandleDtcntServiceEvents"/>
    <RECEIVER id="EVT_ID_SRV_DTCNT_WLAN_DISC_IND" proc="HandleDtcntServiceEvents"/>
    <RECEIVER id="EVT_ID_SRV_DTCNT_WLAN_IPADDR_UPDATE" proc="HandleDtcntServiceEvents"/>
    <RECEIVER id="EVT_ID_SRV_DTCNT_WLAN_IPADDR_CONFLICT_IND" proc="HandleDtcntServiceEvents"/>
    <RECEIVER id="EVT_ID_SRV_DTCNT_WLAN_CURR_AP_INFO" proc="HandleDtcntServiceEvents"/>
    <RECEIVER id="EVT_ID_SRV_DTCNT_PROV_IND" proc="HandleDtcntServiceEvents"/>
    <RECEIVER id="EVT_ID_SRV_DTCNT_PROV_INSTALL_RES_IND" proc="HandleDtcntServiceEvents"/>
    <RECEIVER id="EVT_ID_SRV_DTCNT_ACCT_UPDATE_IND" proc="HandleDtcntServiceEvents"/>
    <RECEIVER id="EVT_ID_SRV_DTCNT_ACCT_DELETE_IND" proc="HandleDtcntServiceEvents"/>
    <RECEIVER id="EVT_ID_SRV_DTCNT_WLAN_INIT_RES_IND" proc="HandleDtcntServiceEvents"/>
    <RECEIVER id="EVT_ID_SRV_DTCNT_WLAN_DEINIT_RES_IND" proc="HandleDtcntServiceEvents"/>
    <RECEIVER id="EVT_ID_SRV_DTCNT_WLAN_CONN_RES_IND" proc="HandleDtcntServiceEvents"/>
    <RECEIVER id="EVT_ID_SRV_DTCNT_WLAN_DISC_RES_IND" proc="HandleDtcntServiceEvents"/>
    <RECEIVER id="EVT_ID_SRV_DTCNT_WLAN_SCAN_RES_IND" proc="HandleDtcntServiceEvents"/>
    <RECEIVER id="EVT_ID_SRV_DTCNT_WLAN_IPADDR_CHANGE_QRY" proc="HandleDtcntServiceEvents"/>
    <RECEIVER id="EVT_ID_SRV_DTCNT_WIFI_CHIP_INVALID" proc="HandleDtcntServiceEvents"/>
    <RECEIVER id="EVT_ID_SRV_MODE_SWITCH_PRE_NOTIFY" proc="HandleDtcntServiceEvents"/>
    <RECEIVER id="EVT_ID_SRV_MODE_SWITCH_FINISH_NOTIFY" proc="HandleDtcntServiceEvents"/>   
    <RECEIVER id="EVT_ID_SRV_DTCNT_WLAN_BEARER_STATUS" proc="HandleDtcntServiceEvents"/>
    <RECEIVER id="EVT_ID_SRV_DTCNT_WLAN_CONN_PROF" proc="HandleDtcntServiceEvents"/>    
#ifdef __WPS_SUPPORT__    
    <RECEIVER id="EVT_ID_SRV_DTCNT_WLAN_WPS_INFO" proc="HandleDtcntServiceEvents"/>
#endif   
    <RECEIVER id="EVT_ID_VAPP_LANGUAGE_CHANGED" proc="HandleDtcntServiceEvents"/> 

#ifdef __MMI_OP01_WIFI__      
    <RECEIVER id="EVT_ID_SRV_DTCNT_WLAN_LOGOUT_IND" proc="HandleDtcntServiceEvents"/>
    <RECEIVER id="EVT_ID_SRV_DTCNT_WLAN_IPADDR_CHANGE_CNF" proc="HandleDtcntServiceEvents"/>
#endif

    <RECEIVER id="EVT_ID_SRV_DTCNT_WLAN_SLEEP" proc="HandleDtcntServiceEvents"/>
        
#ifdef __MMI_OP01_WIFI__      
    <RECEIVER id="EVT_ID_VAPP_WLAN_CMCC_CLOSE_PAGE" proc="VappDtcntWlanClosePageEvent"/>       
#endif   

</APP>
#endif
