#include "mmi_features.h"
#include "custresdef.h"

<?xml version="1.0" encoding="UTF-8"?>
#ifdef __MMI_OP01_WIFI__
<APP id="VAPP_WLAN_AUTH" name="STR_ID_VAPP_WLAN_CMCC_AUTH_MAIN" type="venus">
    <MEMORY heap="102400" cui="VCUI_FMGR"/>
    
    <STRING id="STR_ID_VAPP_WLAN_CMCC_AUTH_MAIN"/>
		<STRING id="STR_ID_VAPP_WLAN_CMCC_APPLY_PASSWORD"/>
		<STRING id="STR_ID_VAPP_WLAN_CMCC_ACCT_SETTING"/>
		<STRING id="STR_ID_VAPP_WLAN_CMCC_OTHERS"/>
		<STRING id="STR_ID_VAPP_WLAN_CMCC_MODIFY_PASSWORD"/>
		<STRING id="STR_ID_VAPP_WLAN_CMCC_RESET_PASSWORD"/>
		<STRING id="STR_ID_VAPP_WLAN_CMCC_AUTO_AUTH"/>
		<STRING id="STR_ID_VAPP_WLAN_CMCC_NOTI_AUTH"/>
		<STRING id="STR_ID_VAPP_WLAN_CMCC_INSTALL_UPDATE"/>
		<STRING id="STR_ID_VAPP_WLAN_CMCC_OLD_PASSWORD"/>
		<STRING id="STR_ID_VAPP_WLAN_CMCC_NEW_PASSWORD"/>
		<STRING id="STR_ID_VAPP_WLAN_CMCC_NEW_PASSWORD2"/>
		<STRING id="STR_ID_VAPP_WLAN_CMCC_EMPTY_USERNAME"/>
		<STRING id="STR_ID_VAPP_WLAN_CMCC_EMPTY_PASSWORD"/>	
		<STRING id="STR_ID_VAPP_WLAN_CMCC_EMPTY_NEW2_PASSWORD"/>
		<STRING id="STR_ID_VAPP_WLAN_CMCC_EMPTY_NEW1_PASSWORD"/>
		<STRING id="STR_ID_VAPP_WLAN_CMCC_EMPTY_OLD_PASSWORD"/>
		<STRING id="STR_ID_VAPP_WLAN_CMCC_DIFFERENT_NEW_PASSWORD"/>
		<STRING id="STR_ID_VAPP_WLAN_CMCC_HTTP_AUTH_FAIL"/>
		<STRING id="STR_ID_VAPP_WLAN_CMCC_HTTP_AUTH_SUCC"/>
		<STRING id="STR_ID_VAPP_WLAN_CMCC_CORRECT_OLD_PASSWORD"/>
		<STRING id="STR_ID_VAPP_WLAN_CMCC_SEND_SMS_FAIL"/>
		<STRING id="STR_ID_VAPP_WLAN_CMCC_SEND_SMS_SUCC"/>
		<STRING id="STR_ID_VAPP_WLAN_CMCC_AUTH_NOTIFY"/>
		<STRING id="STR_ID_VAPP_WLAN_CMCC_HTTP_LOGIN_LOADING"/>
		<STRING id="STR_ID_VAPP_WLAN_CMCC_SMS_SEND_LOADING"/>
		<STRING id="STR_ID_VAPP_WLAN_CMCC_CONFIRM_AUTH"/>
		<STRING id="STR_ID_VAPP_WLAN_CMCC_CONFIRM_SMS"/>
		<STRING id="STR_ID_VAPP_WLAN_CMCC_SMS_FAIL"/>
		<STRING id="STR_ID_VAPP_WLAN_CMCC_SMS_BUSY"/>
		<STRING id="STR_ID_VAPP_WLAN_CMCC_HTTP_UPDATE_SUCC"/>
		<STRING id="STR_ID_VAPP_WLAN_CMCC_HTTP_UPDATE_FAIL"/>
		<STRING id="STR_ID_VAPP_WLAN_CMCC_REMIND"/>
    <SENDER id="EVT_ID_VAPP_WLAN_CMCC_AUTH" hfile="vapp_dtcnt_wlan_cmcc_auth_gprot.h"/>
    <SENDER id="EVT_ID_VAPP_WLAN_CMCC_CLOSE_PAGE" hfile="vapp_dtcnt_wlan_cmcc_auth_gprot.h"/>
</APP>   
#endif
 