/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2008
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES. ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *  vapp_cube_imgview_config.h
 *
 * Project:
 * --------
 *  Venus
 *
 * Description:
 * ------------
 *  Cube Image View Config File
 *
 * Author:
 * -------
 * -------
 *
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/

#ifndef __VAPP_3D_CUBE_APP_IMGVIEW_CONFIG_H__
#define __VAPP_3D_CUBE_APP_IMGVIEW_CONFIG_H__


/***************************************************************************** 
 * Include
 *****************************************************************************/

/***************************************************************************** 
 * Define
 *****************************************************************************/
// LCD check
#if defined(__MMI_MAINLCD_240X320__) || \
    defined(__MMI_MAINLCD_240X400__) || \
    defined(__MMI_MAINLCD_320X480__)
#else
    #error "Venus Cube Image View does not support this LCD resolution."
#endif

#ifdef __MMI_MAINLCD_240X320__

#define MMI_VAPP_CUBE_IMGVIEW_CELL_START_X      (53)
#define MMI_VAPP_CUBE_IMGVIEW_CELL_START_Y      (14) //15
#define MMI_VAPP_CUBE_IMGVIEW_CELL_COL_GAP      (25)
#define MMI_VAPP_CUBE_IMGVIEW_CELL_ROW_GAP      (13)
#define MMI_VAPP_CUBE_IMGVIEW_CELL_BG_WIDTH     (65)
#define MMI_VAPP_CUBE_IMGVIEW_CELL_BG_HEIGHT    (65)
#define MMI_VAPP_CUBE_IMGVIEW_CELL_WIDTH        (61)
#define MMI_VAPP_CUBE_IMGVIEW_CELL_HEIGHT       (61)
#define MMI_VAPP_CUBE_IMGVIEW_CELL_COL_COUNT    (2)
#define MMI_VAPP_CUBE_IMGVIEW_CELL_ROW_COUNT    (3)

/*view mode cell*/
#define MMI_VAPP_CUBE_IMGVIEW_BIG_CELL_START_X      (0)
#define MMI_VAPP_CUBE_IMGVIEW_BIG_CELL_START_Y      (0)
#define MMI_VAPP_CUBE_IMGVIEW_BIG_CELL_COL_GAP      (0)
#define MMI_VAPP_CUBE_IMGVIEW_BIG_CELL_ROW_GAP      (0)
#define MMI_VAPP_CUBE_IMGVIEW_BIG_CELL_BG_WIDTH     (220)
#define MMI_VAPP_CUBE_IMGVIEW_BIG_CELL_BG_HEIGHT    (203)
#define MMI_VAPP_CUBE_IMGVIEW_BIG_CELL_WIDTH        (200)
#define MMI_VAPP_CUBE_IMGVIEW_BIG_CELL_HEIGHT       (183)
#define MMI_VAPP_CUBE_IMGVIEW_BIG_CELL_COL_COUNT    (1)
#define MMI_VAPP_CUBE_IMGVIEW_BUTTON_OFFSET_X       (188)
#define MMI_VAPP_CUBE_IMGVIEW_BUTTON_OFFSET_Y       (15)
#define MMI_VAPP_CUBE_IMGVIEW_BUTTON_OFFSET_WIDTH       (44)
#define MMI_VAPP_CUBE_IMGVIEW_BUTTON_OFFSET_HEIGHT       (40)
#define MMI_VAPP_CUBE_IMGVIEW_BUTTON_HILIGHT_OFFSET_X       (180)
#define MMI_VAPP_CUBE_IMGVIEW_BUTTON_HILIGHT_OFFSET_Y       (4)
#define MMI_VAPP_CUBE_IMGVIEW_BUTTON_HILIGHT_OFFSET_WIDTH       (60)
#define MMI_VAPP_CUBE_IMGVIEW_BUTTON_HILIGHT_OFFSET_HEIGHT       (60)
#define MMI_VAPP_CUBE_IMGVIEW_UP_ARROW_OFFSET_X     (106)
#define MMI_VAPP_CUBE_IMGVIEW_UP_ARROW_OFFSET_Y     (23)
#define MMI_VAPP_CUBE_IMGVIEW_UP_ARROW_WIDTH     (28)
#define MMI_VAPP_CUBE_IMGVIEW_UP_ARROW_HEIGHT     (21)
#define MMI_VAPP_CUBE_IMGVIEW_DOWN_ARROW_OFFSET_X     (106)
#define MMI_VAPP_CUBE_IMGVIEW_DOWN_ARROW_OFFSET_Y     (246)
#define MMI_VAPP_CUBE_IMGVIEW_DOWN_ARROW_WIDTH     (28)
#define MMI_VAPP_CUBE_IMGVIEW_DOWN_ARROW_HEIGHT     (21)
#define MMI_VAPP_CUBE_IMGVIEW_TIMELINE_DUR          (1000)
#define MMI_VAPP_CUBE_IMGVIEW_TIMELINE_REP_COUNT    (2)
#define MMI_VAPP_CUBE_IMGVIEW_CORNER_GAP            (10)
#define MMI_VAPP_CUBE_IMGVIEW_LINE_HEIGHT           (24)
#define MMI_VAPP_CUBE_IMGVIEW_LINE_WIDTH            (12)
#define MMI_VAPP_CUBE_IMGVIEW_BIG_CELL_MIN_WIDTH          (50)
#define MMI_VAPP_CUBE_IMGVIEW_BIG_CELL_MIN_HEIGHT          (50)

/*null mode*/
#define MMI_VAPP_CUBE_IMGVIEW_TEXT_OFFSET_X         (12)
#define MMI_VAPP_CUBE_IMGVIEW_TEXT_OFFSET_Y         (85)
#define MMI_VAPP_CUBE_IMGVIEW_TEXT_WIDTH            (216)
#define MMI_VAPP_CUBE_IMGVIEW_TEXT_HEIGHT           (26)

#define MMI_VAPP_CUBE_IMGVIEW_LOADING_BG_OFFSET_X      (0)
#define MMI_VAPP_CUBE_IMGVIEW_LOADING_BG_OFFSET_Y      (48)
#define MMI_VAPP_CUBE_IMGVIEW_LOADING_BG_OFFSET_WIDTH  (240)
#define MMI_VAPP_CUBE_IMGVIEW_LOADING_BG_OFFSET_HEIGHT (146)
#define MMI_VAPP_CUBE_IMGVIEW_LOADING_OFFSET_X      (103)
#define MMI_VAPP_CUBE_IMGVIEW_LOADING_OFFSET_Y      (42)

#define MMI_VAPP_CUBE_IMGVIEW_ERROR_OFFSET_Y         (13)
#define MMI_VAPP_CUBE_IMGVIEW_ERROR_OFFSET_WIDTH    (240)
#define MMI_VAPP_CUBE_IMGVIEW_ERROR_OFFSET_HEIGHT   (160)
#define MMI_VAPP_CUBE_IMGVIEW_LOADING_ICON_STRING_GAP      (0)

#define MMI_VAPP_CUBE_IMGVIEW_CACHE_NUMBER          (10)

#define MMI_VAPP_CUBE_IMGVIEW_NAVIGATION_LAYER_COUNT (12)

#elif defined(__MMI_MAINLCD_240X400__)

/*navigation mode cell*/
#define MMI_VAPP_CUBE_IMGVIEW_CELL_START_X      (56)
#define MMI_VAPP_CUBE_IMGVIEW_CELL_START_Y      (13)
#define MMI_VAPP_CUBE_IMGVIEW_CELL_COL_GAP      (25)
#define MMI_VAPP_CUBE_IMGVIEW_CELL_ROW_GAP      (13)
#define MMI_VAPP_CUBE_IMGVIEW_CELL_BG_WIDTH     (65)
#define MMI_VAPP_CUBE_IMGVIEW_CELL_BG_HEIGHT    (65)
#define MMI_VAPP_CUBE_IMGVIEW_CELL_WIDTH        (61)
#define MMI_VAPP_CUBE_IMGVIEW_CELL_HEIGHT       (61)
#define MMI_VAPP_CUBE_IMGVIEW_CELL_COL_COUNT    (2)
#define MMI_VAPP_CUBE_IMGVIEW_CELL_ROW_COUNT    (4)

/*view mode cell*/
#define MMI_VAPP_CUBE_IMGVIEW_BIG_CELL_START_X      (0)
#define MMI_VAPP_CUBE_IMGVIEW_BIG_CELL_START_Y      (0)
#define MMI_VAPP_CUBE_IMGVIEW_BIG_CELL_COL_GAP      (0)
#define MMI_VAPP_CUBE_IMGVIEW_BIG_CELL_ROW_GAP      (0)
#define MMI_VAPP_CUBE_IMGVIEW_BIG_CELL_BG_WIDTH     (220)
#define MMI_VAPP_CUBE_IMGVIEW_BIG_CELL_BG_HEIGHT    (262)
#define MMI_VAPP_CUBE_IMGVIEW_BIG_CELL_WIDTH        (200)
#define MMI_VAPP_CUBE_IMGVIEW_BIG_CELL_HEIGHT       (242)
#define MMI_VAPP_CUBE_IMGVIEW_BIG_CELL_COL_COUNT    (1)
#define MMI_VAPP_CUBE_IMGVIEW_BUTTON_OFFSET_X       (189)
#define MMI_VAPP_CUBE_IMGVIEW_BUTTON_OFFSET_Y       (20)
#define MMI_VAPP_CUBE_IMGVIEW_BUTTON_OFFSET_WIDTH       (44)
#define MMI_VAPP_CUBE_IMGVIEW_BUTTON_OFFSET_HEIGHT       (40)
#define MMI_VAPP_CUBE_IMGVIEW_BUTTON_HILIGHT_OFFSET_X       (181)
#define MMI_VAPP_CUBE_IMGVIEW_BUTTON_HILIGHT_OFFSET_Y       (10)
#define MMI_VAPP_CUBE_IMGVIEW_BUTTON_HILIGHT_OFFSET_WIDTH       (60)
#define MMI_VAPP_CUBE_IMGVIEW_BUTTON_HILIGHT_OFFSET_HEIGHT       (60)
#define MMI_VAPP_CUBE_IMGVIEW_UP_ARROW_OFFSET_X     (106)
#define MMI_VAPP_CUBE_IMGVIEW_UP_ARROW_OFFSET_Y     (28)
#define MMI_VAPP_CUBE_IMGVIEW_UP_ARROW_WIDTH     (28)
#define MMI_VAPP_CUBE_IMGVIEW_UP_ARROW_HEIGHT     (21)
#define MMI_VAPP_CUBE_IMGVIEW_DOWN_ARROW_OFFSET_X     (106)
#define MMI_VAPP_CUBE_IMGVIEW_DOWN_ARROW_OFFSET_Y     (320)
#define MMI_VAPP_CUBE_IMGVIEW_DOWN_ARROW_WIDTH     (28)
#define MMI_VAPP_CUBE_IMGVIEW_DOWN_ARROW_HEIGHT     (21)
#define MMI_VAPP_CUBE_IMGVIEW_TIMELINE_DUR          (1000)
#define MMI_VAPP_CUBE_IMGVIEW_TIMELINE_REP_COUNT    (2)
#define MMI_VAPP_CUBE_IMGVIEW_CORNER_GAP            (12)
#define MMI_VAPP_CUBE_IMGVIEW_LINE_HEIGHT           (24)
#define MMI_VAPP_CUBE_IMGVIEW_LINE_WIDTH            (12)
#define MMI_VAPP_CUBE_IMGVIEW_BIG_CELL_MIN_WIDTH          (50)
#define MMI_VAPP_CUBE_IMGVIEW_BIG_CELL_MIN_HEIGHT          (50)

/*null mode*/
#define MMI_VAPP_CUBE_IMGVIEW_TEXT_OFFSET_X         (12)
#define MMI_VAPP_CUBE_IMGVIEW_TEXT_OFFSET_Y         (85)
#define MMI_VAPP_CUBE_IMGVIEW_TEXT_WIDTH            (216)
#define MMI_VAPP_CUBE_IMGVIEW_TEXT_HEIGHT           (26)

#define MMI_VAPP_CUBE_IMGVIEW_LOADING_BG_OFFSET_X      (0)
#define MMI_VAPP_CUBE_IMGVIEW_LOADING_BG_OFFSET_Y      (82)
#define MMI_VAPP_CUBE_IMGVIEW_LOADING_BG_OFFSET_WIDTH  (240)
#define MMI_VAPP_CUBE_IMGVIEW_LOADING_BG_OFFSET_HEIGHT (145)
#define MMI_VAPP_CUBE_IMGVIEW_LOADING_OFFSET_X      (103)
#define MMI_VAPP_CUBE_IMGVIEW_LOADING_OFFSET_Y      (40)

#define MMI_VAPP_CUBE_IMGVIEW_ERROR_OFFSET_Y         (13)
#define MMI_VAPP_CUBE_IMGVIEW_ERROR_OFFSET_WIDTH    (240)
#define MMI_VAPP_CUBE_IMGVIEW_ERROR_OFFSET_HEIGHT   (160)
#define MMI_VAPP_CUBE_IMGVIEW_LOADING_ICON_STRING_GAP      (0)

#define MMI_VAPP_CUBE_IMGVIEW_CACHE_NUMBER          (10)

#define MMI_VAPP_CUBE_IMGVIEW_NAVIGATION_LAYER_COUNT (14)

#elif defined(__MMI_MAINLCD_320X480__)

/*navigation mode cell*/
#define MMI_VAPP_CUBE_IMGVIEW_CELL_START_X      (77)
#define MMI_VAPP_CUBE_IMGVIEW_CELL_START_Y      (16) //17
#define MMI_VAPP_CUBE_IMGVIEW_CELL_COL_GAP      (30)
#define MMI_VAPP_CUBE_IMGVIEW_CELL_ROW_GAP      (16)
#define MMI_VAPP_CUBE_IMGVIEW_CELL_BG_WIDTH     (81)
#define MMI_VAPP_CUBE_IMGVIEW_CELL_BG_HEIGHT    (81)
#define MMI_VAPP_CUBE_IMGVIEW_CELL_WIDTH        (75)
#define MMI_VAPP_CUBE_IMGVIEW_CELL_HEIGHT       (75)
#define MMI_VAPP_CUBE_IMGVIEW_CELL_COL_COUNT    (2)
#define MMI_VAPP_CUBE_IMGVIEW_CELL_ROW_COUNT    (4)

/*view mode cell*/
#define MMI_VAPP_CUBE_IMGVIEW_BIG_CELL_START_X      (0)
#define MMI_VAPP_CUBE_IMGVIEW_BIG_CELL_START_Y      (0)
#define MMI_VAPP_CUBE_IMGVIEW_BIG_CELL_COL_GAP      (0)
#define MMI_VAPP_CUBE_IMGVIEW_BIG_CELL_ROW_GAP      (0)
#define MMI_VAPP_CUBE_IMGVIEW_BIG_CELL_BG_WIDTH     (303)
#define MMI_VAPP_CUBE_IMGVIEW_BIG_CELL_BG_HEIGHT    (314)
#define MMI_VAPP_CUBE_IMGVIEW_BIG_CELL_WIDTH        (280)
#define MMI_VAPP_CUBE_IMGVIEW_BIG_CELL_HEIGHT       (290)
#define MMI_VAPP_CUBE_IMGVIEW_BIG_CELL_COL_COUNT    (1)
#define MMI_VAPP_CUBE_IMGVIEW_BUTTON_OFFSET_X       (253)
#define MMI_VAPP_CUBE_IMGVIEW_BUTTON_OFFSET_Y       (20)
#define MMI_VAPP_CUBE_IMGVIEW_BUTTON_OFFSET_WIDTH       (56)
#define MMI_VAPP_CUBE_IMGVIEW_BUTTON_OFFSET_HEIGHT       (45)
#define MMI_VAPP_CUBE_IMGVIEW_BUTTON_HILIGHT_OFFSET_X       (231)
#define MMI_VAPP_CUBE_IMGVIEW_BUTTON_HILIGHT_OFFSET_Y       (-6)
#define MMI_VAPP_CUBE_IMGVIEW_BUTTON_HILIGHT_OFFSET_WIDTH       (92)
#define MMI_VAPP_CUBE_IMGVIEW_BUTTON_HILIGHT_OFFSET_HEIGHT       (95)
#define MMI_VAPP_CUBE_IMGVIEW_UP_ARROW_OFFSET_X     (140)
#define MMI_VAPP_CUBE_IMGVIEW_UP_ARROW_OFFSET_Y     (34)
#define MMI_VAPP_CUBE_IMGVIEW_UP_ARROW_WIDTH     (34)
#define MMI_VAPP_CUBE_IMGVIEW_UP_ARROW_HEIGHT     (26)
#define MMI_VAPP_CUBE_IMGVIEW_DOWN_ARROW_OFFSET_X     (140)
#define MMI_VAPP_CUBE_IMGVIEW_DOWN_ARROW_OFFSET_Y     (383)
#define MMI_VAPP_CUBE_IMGVIEW_DOWN_ARROW_WIDTH     (34)
#define MMI_VAPP_CUBE_IMGVIEW_DOWN_ARROW_HEIGHT     (26)
#define MMI_VAPP_CUBE_IMGVIEW_TIMELINE_DUR          (1000)
#define MMI_VAPP_CUBE_IMGVIEW_TIMELINE_REP_COUNT    (2)
#define MMI_VAPP_CUBE_IMGVIEW_CORNER_GAP            (12)
#define MMI_VAPP_CUBE_IMGVIEW_LINE_HEIGHT           (24)
#define MMI_VAPP_CUBE_IMGVIEW_LINE_WIDTH            (12)
#define MMI_VAPP_CUBE_IMGVIEW_BIG_CELL_MIN_WIDTH          (50)
#define MMI_VAPP_CUBE_IMGVIEW_BIG_CELL_MIN_HEIGHT          (50)

/*null mode*/
#define MMI_VAPP_CUBE_IMGVIEW_TEXT_OFFSET_X         (16)
#define MMI_VAPP_CUBE_IMGVIEW_TEXT_OFFSET_Y         (97)
#define MMI_VAPP_CUBE_IMGVIEW_TEXT_WIDTH            (288)
#define MMI_VAPP_CUBE_IMGVIEW_TEXT_HEIGHT           (26)

#define MMI_VAPP_CUBE_IMGVIEW_LOADING_BG_OFFSET_X      (0)
#define MMI_VAPP_CUBE_IMGVIEW_LOADING_BG_OFFSET_Y      (115)
#define MMI_VAPP_CUBE_IMGVIEW_LOADING_BG_OFFSET_WIDTH  (320)
#define MMI_VAPP_CUBE_IMGVIEW_LOADING_BG_OFFSET_HEIGHT (158)
#define MMI_VAPP_CUBE_IMGVIEW_LOADING_OFFSET_X      (138)
#define MMI_VAPP_CUBE_IMGVIEW_LOADING_OFFSET_Y      (43)

#define MMI_VAPP_CUBE_IMGVIEW_ERROR_OFFSET_Y         (33)
#define MMI_VAPP_CUBE_IMGVIEW_ERROR_OFFSET_WIDTH    (320)
#define MMI_VAPP_CUBE_IMGVIEW_ERROR_OFFSET_HEIGHT   (200)
#define MMI_VAPP_CUBE_IMGVIEW_LOADING_ICON_STRING_GAP      (0)

#define MMI_VAPP_CUBE_IMGVIEW_CACHE_NUMBER          (10)

#define MMI_VAPP_CUBE_IMGVIEW_NAVIGATION_LAYER_COUNT (14)

#endif

//#define MMI_VAPP_CUBE_IMGVIEW_SCRMEM_SIZE           (LCD_WIDTH*LCD_HEIGHT) // have lcd memory size
#define MMI_VAPP_CUBE_IMGVIEW_DEFAULT_BK_COLOR      (VFX_COLOR_BLACK)
#define MMI_VAPP_CUBE_IMGVIEW_BACKUP_BUFFER_COUNT   ((MMI_VAPP_CUBE_IMGVIEW_CELL_ROW_COUNT + 2) * MMI_VAPP_CUBE_IMGVIEW_CELL_COL_COUNT)

#define MMI_VAPP_CUBE_IMGVIEW_LOADING_COUNT_ALL		(7)
#define MMI_VAPP_CUBE_IMGVIEW_LOADING_INTERVAL		(100)

#define MMI_VAPP_CUBE_IMGVIEW_NAVIGATION_CACHE_COUNT (80)

#define MMI_VAPP_CUBE_IMGVIEW_NAVIGATION_CACHE_MEM_ONE (MMI_VAPP_CUBE_IMGVIEW_CELL_BG_WIDTH * MMI_VAPP_CUBE_IMGVIEW_CELL_BG_HEIGHT * 2)
#define MMI_VAPP_CUBE_IMGVIEW_NAVIGATION_CACHE_MEM_ONE_ALL (MMI_VAPP_CUBE_IMGVIEW_NAVIGATION_CACHE_COUNT * MMI_VAPP_CUBE_IMGVIEW_NAVIGATION_CACHE_MEM_ONE)

#define MMI_VAPP_CUBE_IMGVIEW_VIEW_CACHE_MEM_ALL (LCD_WIDTH * LCD_HEIGHT * 2)

#define MMI_VAPP_CUBE_IMGVIEW_DB_SIZE (SRV_MEDIACACHE_RUN_BUF_SIZE(MMI_VAPP_CUBE_IMGVIEW_NAVIGATION_CACHE_COUNT) + \
    SRV_MEDIACACHE_SQLITE_DB_BUF_SIZE_DEFAULT)

#define MMI_VAPP_CUBE_IMGVIEW_ADM_SYSTEM_GAP_BUFFER (1024)

#define MMI_VAPP_CUBE_IMGVIEW_MED_BUFFER_SIZE ( \
    MMI_VAPP_CUBE_IMGVIEW_DB_SIZE + \
    MMI_VAPP_CUBE_IMGVIEW_NAVIGATION_CACHE_MEM_ONE_ALL + \
    MMI_VAPP_CUBE_IMGVIEW_ADM_SYSTEM_GAP_BUFFER )
#endif
