/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_menu_shortcut_data.c
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   MTK resgenerator XML parser
 *
 *******************************************************************************/
#include "MMIDataType.h"
#include "mmi_rp_menu_shortcut_def.h"
#include "GlobalResDef.h"
#include "mmi_rp_all_defs.h"


/* Extern declarations for Shortcut launch functions*/
extern void EntryAlmMenu(void);
extern void CalcPreEntryApp(void);
extern void ClndrPreEntryApp(void);
extern void mmi_clog_dclt_launch(void);
extern void mmi_clog_mclt_launch(void);
extern void mmi_clog_rclt_launch(void);
extern void mmi_callset_call_setting_launch(void);
extern void mmi_camera_lauch(void);
extern void mmi_imgview_launch(void);
extern void mmi_fmgr_launch(void);
extern void EntryScrSettingMenu(void);
extern void mmi_phb_sc_add_new_entry(void);
extern void mmi_profiles_entry_main_screen(void);
extern void mmi_secset_phone_set_lock_by_shortcut(void);
extern void mmi_sms_vm_launch(void);
extern void mmi_sndrec_pre_entry_main_screen(void);
extern void mmi_tdl_entry_task_view_all(void);
extern void mmi_um_entry_main_message_menu_with_check(void);
extern void mmi_um_entry_write_msg_ext(void);
extern void mmi_um_entry_inbox(void);
extern void mmi_um_entry_sent(void);
extern void EntryWcBrowseCity(void);


/* Shortcut app array associated with menu IDs */
const mmi_shct_candidate_menu_info_struct mmi_shct_candidate_menu[] =
{
    {ORGANIZER_ALARM_MENU, STR_GLOBAL_ALARM, ORGANIZER_MENU_ALARMS_IMAGEID, EntryAlmMenu},
    {EXTRA_CALCULATOR_MENU, STR_ID_CALC_MENU, IMG_ID_CALC_MENU_ICON, CalcPreEntryApp},
    {ORGANIZER_CALENDER_MENU, ORGANIZER_MENU_CALENDER_STRINGID, ORGANIZER_MENU_CALENDER_IMAGEID, ClndrPreEntryApp},
    {MENU_ID_CLOG_DIALED_CALL, STR_GLOBAL_DIALLED_CALLS, IMG_ID_CLOG_DIALED_CALL, mmi_clog_dclt_launch},
    {MENU_ID_CLOG_MISSED_CALL, STR_GLOBAL_MISSED_CALLS, IMG_ID_CLOG_MISSED_CALL, mmi_clog_mclt_launch},
    {MENU_ID_CLOG_RECVED_CALL, STR_GLOBAL_RECEIVED_CALLS, IMG_ID_CLOG_RECVED_CALL, mmi_clog_rclt_launch},
    {MENU_ID_CALLSET_CALL_SETTING, STR_ID_CALLSET_CALL_SETTING, IMG_ID_CALLSET_CALL_SETTING, mmi_callset_call_setting_launch},
    {MENU_ID_CAMERA_APP, STR_ID_CAMERA_APP_NAME, IMG_ID_CAMERA_APP_ICON, mmi_camera_lauch},
    {MENU_ID_IMGVIEW_APP, STR_ID_IMGVIEW_NAME, IMG_ID_IMGVIEW_MAIN_ICON, mmi_imgview_launch},
    {MAIN_MENU_FILE_MNGR_MENUID, MAIN_MENU_FILE_MNGR_TEXT, MAIN_MENU_TITLE_ICON, mmi_fmgr_launch},
    {MAIN_MENU_SETTINGS_MENUID, MAIN_MENU_SETTINGS_TEXT, MAIN_MENU_TITLE_ICON, EntryScrSettingMenu},
    {MITEM102_PBOOK_NEW_ENTRY, STR_ID_PHB_ADD_NEW_CONTACT, IMG_ID_PHB_NEW_NUMBER, mmi_phb_sc_add_new_entry},
    {MAIN_MENU_PROFILES_MENUID, STR_ID_PROF_CAPTION, MAIN_MENU_PROFILES_ICON, mmi_profiles_entry_main_screen},
    {MENU_ID_SECSET_PHONE_LOCK, STR_ID_SECSET_PHONE_LOCK, IMG_SECSET_MENU_ENTRY, mmi_secset_phone_set_lock_by_shortcut},
    {MENU_ID_SMS_VM_VMAIL_MENUID, STR_ID_SMS_VM_VMAIL_MENUENTRY, IMG_SMS_VMAIL_MENUENTRY, mmi_sms_vm_launch},
    {MENU_ID_SNDREC_MAIN, STR_ID_SNDREC_MAIN, IMG_ID_SNDREC_MAIN_ICON, mmi_sndrec_pre_entry_main_screen},
    {ORGANIZER_TODOLIST_MENU, ORGANIZER_MENU_TODOLIST_STRINGID, ORGANIZER_MENU_TODOLIST_IMAGEID, mmi_tdl_entry_task_view_all},
    {MAIN_MENU_MESSAGES_MENUID, MAIN_MENU_MESSAGES_TEXT, MAIN_MENU_MESSAGES_ICON, mmi_um_entry_main_message_menu_with_check},
    {MENU_ID_UM_WRITE_MSG, STR_UM_WRITE_MSG_ID, IMG_UM_WRITE_MSG_ID, mmi_um_entry_write_msg_ext},
    {MENU_ID_UM_INBOX, STR_GLOBAL_INBOX, IMG_UM_INBOX_ID, mmi_um_entry_inbox},
    {MENU_ID_UM_SENT, STR_UM_SENT_ID, IMG_UM_SENT_ID, mmi_um_entry_sent},
    {ORGANIZER_WORLDCLOCK_MENU, ORGANIZER_MENU_WORLDCLOCK_STRINGID, 0, EntryWcBrowseCity},
};


/*****************************************************************************
 * FUNCTION
 *  mmi_shct_get_candidate_menu_list_num
 * DESCRIPTION
 *  Get size of mmi_shct_candidate_menu[] array 
 * PARAMETERS
 *  void
 * RETURNS
 *  Number of elements
 *****************************************************************************/
U32 mmi_shct_get_candidate_menu_list_num(void)
{
    return sizeof(mmi_shct_candidate_menu)/sizeof(mmi_shct_candidate_menu[0]);
}
