/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_cache_table.c
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   03 13 2011 yan.liang
 *
 *******************************************************************************/
/********************************************************
 *  This file is generated automatically by resource gen
 *  Please do not modify it here manually 
 ***********************************************************/
#include "common_nvram_editor_data_item.h"
#define MMI_CACHE_BYTE_NUMBER 110
#define MMI_CACHE_SHORT_NUMBER 40
#define MMI_CACHE_DOUBLE_NUMBER 38


kal_uint16 mmi_rp_mmi_cache_get_byte_number(void)
{
    return MMI_CACHE_BYTE_NUMBER;
}
kal_uint16 mmi_rp_mmi_cache_get_short_number(void)
{
    return MMI_CACHE_SHORT_NUMBER;
}
kal_uint16 mmi_rp_mmi_cache_get_double_number(void)
{
    return MMI_CACHE_DOUBLE_NUMBER;
}


const kal_uint16 MMI_CACHE_BYTE_ENUM_TABLE[MMI_CACHE_BYTE_NUMBER] =
{
    26262,   /* 0 -- NVRAM_BYTE_COVER_CLOSE_BACK_TO_IDLE */
    37590,   /* 1 -- NVRAM_WC_DST */
    27164,   /* 2 -- NVRAM_SETTING_LANG */
    26285,   /* 3 -- NVRAM_SETTING_PICTURE_QUALITY */
     9499,   /* 4 -- NVRAM_SMS_MISCELL_SETTING */
     9603,   /* 5 -- NVRAM_CALLSET_CUG_ACTIVATED_ID */
    26134,   /* 6 -- NVRAM_IME_ALPHABETIC_WORD_PREDICTION_FLAG */
     4811,   /* 7 -- NVRAM_MRE_SRV_DA_IS_WIFI_ONLY */
    32158,   /* 8 -- NVRAM_PHB_SAVE_CONTACT_NOTIFY */
    15644,   /* 9 -- NVRAM_SETTING_MMS_MSG_FILTER */
    26318,   /* 10 -- NVRAM_NETSET_3G_CAPACITY_SIM */
    46922,   /* 11 -- NVRAM_VDOPLY_PROXY_IP1 */
    46923,   /* 12 -- NVRAM_VDOPLY_PROXY_IP2 */
    46924,   /* 13 -- NVRAM_VDOPLY_PROXY_IP3 */
    46925,   /* 14 -- NVRAM_VDOPLY_PROXY_IP4 */
    35212,   /* 15 -- NVRAM_IMGVIEW_VIEW_SYTLE */
    41004,   /* 16 -- NVRAM_PHNSET_LIVE_WALLPAPER */
    14415,   /* 17 -- NVRAM_PNS_SWITCH */
     9612,   /* 18 -- NVRAM_CALLSET_BLACKLIST_MODE */
    28279,   /* 19 -- NVRAM_SETTING_AUTOKEYPADLOCK_TIME */
    37586,   /* 20 -- CURRENT_CITY */
    26133,   /* 21 -- NVRAM_IME_AUTO_COMPLETION_FLAG */
    26147,   /* 22 -- NVRAM_SETTING_HANDWRITING_ON */
    14313,   /* 23 -- NVRAM_EF_FMGR_SORT_OPTION_LID */
    41003,   /* 24 -- NVRAM_WALLPAPER_ROTATE_STATUS */
    32159,   /* 25 -- NVRAM_SSC_DISABLE_FLAG */
    32161,   /* 26 -- NVRAM_SETTING_SPEED_DIAL */
    42229,   /* 27 -- RESTORE_DEFAULT_OWNER_NO */
     9613,   /* 28 -- NVRAM_CALLSET_QUICK_END_FLAG */
    26259,   /* 29 -- NVRAM_BYTE_LED_SETTING */
    35555,   /* 30 -- NVRAM_AUTO_VM_SETTING_VM_SUPPORT */
     9611,   /* 31 -- NVRAM_CALLSET_IP_NUMBER_SETTING */
    32149,   /* 32 -- NVRAM_PHB_SPEAK_NAME_ON_OFF */
     9609,   /* 33 -- NVRAM_CALLSET_REJ_BY_SMS_SETTING */
    26149,   /* 34 -- NVRAM_SETTING_STROKE_COLOR_INDEX */
    35856,   /* 35 -- NVRAM_AUDPLY_SINGLE_VOL */
     9607,   /* 36 -- NVRAM_CALLSET_REDIAL */
    32154,   /* 37 -- NVRAM_PHB_NAME_DISPLAY_TYPE */
    14416,   /* 38 -- NVRAM_PNS_CHANGE_SIM */
     9606,   /* 39 -- NVRAM_CALLSET_CALL_TIME_DISPLAY */
     9498,   /* 40 -- NVRAM_SMS_ACTIVE_PROFILE_INDEX */
    30321,   /* 41 -- NVRAM_SRV_SNDREC_QUALITY */
    37587,   /* 42 -- FOREIGN_CITY */
     9500,   /* 43 -- NVRAM_SMS_PREFER_STORAGE */
    27159,   /* 44 -- TIME_FORMAT */
    27161,   /* 45 -- RESTORE_DEFAULT_TIME_FORMAT */
    37588,   /* 46 -- NVRAM_SETTING_DT_DST */
    26263,   /* 47 -- NVRAM_BYTE_COVER_CLOSE_REJECT_CALL */
    44407,   /* 48 -- RESTORE_DEFAULT_AUTOUPDATE_TIME */
    26145,   /* 49 -- NVRAM_SETTING_PEN_SPEED */
    26148,   /* 50 -- NVRAM_SETTING_PEN_WIDTH */
    26317,   /* 51 -- NVRAM_NETSET_PREFERRED_MODE_PREV_RF_MODE */
    32160,   /* 52 -- NVRAM_IDLE_DIALER_SEARCH_SETTING */
    15643,   /* 53 -- NVRAM_SETTING_PREFER_MMS_STORAGE_MODE */
    26255,   /* 54 -- NVRAM_SETTING_CONTRAST_SUBLCD_LEVEL */
    27160,   /* 55 -- DATE_FORMAT */
    27162,   /* 56 -- RESTORE_DEFAULT_DATE_FORMAT */
    32151,   /* 57 -- NVRAM_PHB_STARTUP_COPY_SIM2 */
    32152,   /* 58 -- NVRAM_PHB_STARTUP_COPY_SIM3 */
    32153,   /* 59 -- NVRAM_PHB_STARTUP_COPY_SIM4 */
    26139,   /* 60 -- NVRAM_IME_INPUT_PATTERN */
    32999,   /* 61 -- NVRAM_NPR_TTS_FLAG */
    32150,   /* 62 -- NVRAM_PHB_STARTUP_COPY_SIM */
    38112,   /* 63 -- NVRAM_UC_PREFERRED_MSG_TYPE */
    44601,   /* 64 -- NVRAM_CLNDR_FIRST_DAY_OF_WEEK */
     9610,   /* 65 -- NVRAM_CALLSET_CONNECT_NOTICE */
     7796,   /* 66 -- NVRAM_PROFILES_LASTACTIVATED */
    26146,   /* 67 -- NVRAM_SETTING_LANGUAGE_FOLLOW_VK */
    26260,   /* 68 -- NVRAM_BYTE_BL_SETTING_LEVEL */
    46920,   /* 69 -- NVRAM_VDOPLY_VOLUMN */
    42228,   /* 70 -- NVRAM_SETTING_OWNER_NO */
     9604,   /* 71 -- NVRAM_CALLSET_CTR_MODE */
     9602,   /* 72 -- NVRAM_CALLSET_CALLERID */
    37592,   /* 73 -- NVRAM_DOWNLOAD_CITY1 */
    37593,   /* 74 -- NVRAM_DOWNLOAD_CITY2 */
    14414,   /* 75 -- NVRAM_PNS_INTERVAL */
    15153,   /* 76 -- NVRAM_DEFAULT_USB_APP */
    30246,   /* 77 -- NVRAM_EF_SENSOR_UI_ROTATION_SWITCH */
    26131,   /* 78 -- NVRAM_IME_SMART_MODE_CONFIG */
    27163,   /* 79 -- NVRAM_DT_SEP_FORMAT */
    26254,   /* 80 -- NVRAM_SETTING_CONTRAST_LEVEL */
    26137,   /* 81 -- NVRAM_IME_VIBRATION_FLAG */
     9608,   /* 82 -- NVRAM_CALLSET_REJ_BY_SMS */
    33000,   /* 83 -- NVRAM_TTS_VOL_LEVEL */
    26135,   /* 84 -- NVRAM_IME_CHINESE_WORD_PREDICTION_FLAG */
    30299,   /* 85 -- NVRAM_TODO_SRV_SNS_REMINDER_SOURCE */
    30320,   /* 86 -- NVRAM_SRV_SNDREC_STORAGE */
    46921,   /* 87 -- NVRAM_VDOPLY_ACTIVE_PROFILE_IDX */
    27117,   /* 88 -- NVRAM_DUALMODE_MODE_SWITCH_TYPE */
    26138,   /* 89 -- NVRAM_IME_SOUND_FEEDBACK_FLAG */
    26316,   /* 90 -- NVRAM_NETSET_PREFERRED_MODE */
    26258,   /* 91 -- NVRAM_HDSET_MODE_VOICE_LEVEL */
    15645,   /* 92 -- NVRAM_UMMS_DEF_TMPLT_GEN_STATE */
    30322,   /* 93 -- NVRAM_AUTO_VM_SETTING_AUTO_VM */
    26257,   /* 94 -- NVRAM_LDSPK_MODE_VOICE_LEVEL */
    28278,   /* 95 -- NVRAM_SETTING_AUTOKEYPADLOCK */
    26256,   /* 96 -- NVRAM_NORMAL_MODE_VOICE_LEVEL */
    42230,   /* 97 -- NVRAM_SETTING_STATUS_DT_TIME */
     7795,   /* 98 -- NVRAM_PROFILES_ACTIVATED */
    27165,   /* 99 -- NVRAM_SETTING_DEF_ENCODING */
    46926,   /* 100 -- NVRAM_VDOPLY_PROXY_ON_OFF */
    26132,   /* 101 -- NVRAM_IME_AUTO_CAPITALIZATION_FLAG */
    26136,   /* 102 -- NVRAM_IME_AUTO_SPACE_FLAG */
    32335,   /* 103 -- NVRAM_SETTING_AUTOUPDATE_DT_TIME_STATUS */
    33001,   /* 104 -- NVRAM_TTS_VOICE_SEL */
    26264,   /* 105 -- NVRAM_BYTE_COVER_CLOSE_KEYPAD_LOCK */
    42231,   /* 106 -- NVRAM_AUTOUPDATE_DT_STATUS */
    28309,   /* 107 -- NVRAM_IDLE_DIALER_TTS_SETTING */
    38614,   /* 108 -- NVRAM_RMGR_DB_CHECK */
     9605,   /* 109 -- NVRAM_CALLSET_ANSWER_MODE */
};

const kal_uint16 MMI_CACHE_SHORT_ENUM_TABLE[MMI_CACHE_SHORT_NUMBER] =
{
     9502,   /* 0 -- NVRAM_SMSCOUNTERS_SENT_SHORT */
    26140,   /* 1 -- NVRAM_SETTING_PREFER_INPUT_METHOD */
    46929,   /* 2 -- NVRAM_VDOPLY_OPTION_BRIGHTNESS */
     9501,   /* 3 -- NVRAM_SMS_CONCAT_MSG_REF_VALUE */
    41204,   /* 4 -- NVRAM_CURRENT_POWER_OFF_DISPLAY */
    17715,   /* 5 -- NVRAM_WAP_PROF_ACTIVE_MMS_SIM1_DTCNT_INDEX */
    26142,   /* 6 -- NVRAM_SETTING_WRITING_LANG */
    15642,   /* 7 -- NVRAM_UMMS_LANGUAGE_CHANGE */
    41203,   /* 8 -- NVRAM_CURRENT_POWER_ON_DISPLAY */
    46928,   /* 9 -- NVRAM_VDOPLY_STORAGE */
    17714,   /* 10 -- NVRAM_WAP_PROF_ACTIVE_WAP_SIM1_DTCNT_INDEX */
     9615,   /* 11 -- NVRAM_CALLSET_QUICK_END_TIME */
    32155,   /* 12 -- NVRAM_PHB_STORAGE_LOCATION */
     9503,   /* 13 -- NVRAM_SMSCOUNTERS_RECD_SHORT */
    37591,   /* 14 -- NVRAM_FRN_TIMEZONE */
    26141,   /* 15 -- RESTORE_PREFER_INPUT_METHOD */
    34612,   /* 16 -- NVRAM_SCR_SNAPSHOT_SEQ_NO */
    41008,   /* 17 -- RESTORE_DEFAULT_SETWALLPAPER_SUB */
    26261,   /* 18 -- NVRAM_BYTE_BL_SETTING_HFTIME */
    46931,   /* 19 -- NVRAM_VDOPLY_OPTION_REPEAT */
    32157,   /* 20 -- NVRAM_PHB_VCARD_VERSION */
    26144,   /* 21 -- NVRAM_SETTING_ENABLED_WRITING_LANGUAGE */
    34611,   /* 22 -- NVRAM_CAM_FILENAME_SEQ_NO */
    46927,   /* 23 -- NVRAM_VDOPLY_SNAPSHOT_SEQ_NO */
    41202,   /* 24 -- NVRAM_RESTORE_POWER_OFF_DISPLAY */
    32156,   /* 25 -- NVRAM_PHB_NAME_LIST_FILTER */
    30300,   /* 26 -- NVRAM_TODO_SRV_SNS_REMINDER_ID_H */
    30301,   /* 27 -- NVRAM_TODO_SRV_SNS_REMINDER_ID_L */
    34114,   /* 28 -- NVRAM_POWER_ON_DISPLAY_SUCCESS */
     9614,   /* 29 -- NVRAM_CALLSET_CTR_TIME */
    41006,   /* 30 -- RESTORE_DEFAULT_FUNANDGAMES_SETWALLPAPER */
    37589,   /* 31 -- NVRAM_TIMEZONE */
    46932,   /* 32 -- NVRAM_VDOPLY_OPTION_PLAY_MODE */
    41201,   /* 33 -- NVRAM_RESTORE_POWER_ON_DISPLAY */
    26143,   /* 34 -- NVRAM_SETTING_WRITING_LANG_SUB */
    35213,   /* 35 -- NVRAM_IMGVIEW_STORAGE */
    46933,   /* 36 -- NVRAM_VDOPLY_STREAM_SEQ_NO */
    46930,   /* 37 -- NVRAM_VDOPLY_OPTION_CONTRAST */
    41005,   /* 38 -- NVRAM_FUNANDGAMES_SETWALLPAPER */
    41007,   /* 39 -- NVRAM_SETWALLPAPER_SUB */
};

const kal_uint16 MMI_CACHE_DOUBLE_ENUM_TABLE[MMI_CACHE_DOUBLE_NUMBER] =
{
    11919,   /* 0 -- NVRAM_AUDIO_DEBUG_INFO1 */
    11920,   /* 1 -- NVRAM_AUDIO_DEBUG_INFO2 */
    11921,   /* 2 -- NVRAM_AUDIO_DEBUG_INFO3 */
    11922,   /* 3 -- NVRAM_AUDIO_DEBUG_INFO4 */
    41002,   /* 4 -- NVRAM_DISPCHAR_AVATAR_ONOFF_SERIALNUM */
    46934,   /* 5 -- NVRAM_VDOPLY_PROXY_PORT */
    15641,   /* 6 -- NVRAM_UMMS_RESTORE_RETRIEVAL_SETTINGS */
    27128,   /* 7 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE1 */
    27129,   /* 8 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE2 */
    27130,   /* 9 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE3 */
    27131,   /* 10 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE4 */
    27132,   /* 11 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE5 */
    27133,   /* 12 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE6 */
    27134,   /* 13 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE7 */
    27135,   /* 14 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE8 */
    41000,   /* 15 -- NARAM_DISPCHAR_AVATAR_ONOFF */
     4803,   /* 16 -- NVRAM_MRE_SRV_DA_SIM1 */
     4805,   /* 17 -- NVRAM_MRE_SRV_DA_SIM2 */
     4807,   /* 18 -- NVRAM_MRE_SRV_DA_SIM3 */
     4809,   /* 19 -- NVRAM_MRE_SRV_DA_SIM4 */
    40999,   /* 20 -- NVRAM_DISPCHAR_AVATAR_WPSS */
    46936,   /* 21 -- NVRAM_VDOPLY_LOWEST_UDP_PORT */
     7797,   /* 22 -- NVRAM_SRV_PROF_EXT_MELODY_BITS */
    46935,   /* 23 -- NVRAM_VDOPLY_HIGHEST_UDP_PORT */
    27136,   /* 24 -- NVRAM_PEN_CALIBRATION_VALUE1 */
    27137,   /* 25 -- NVRAM_PEN_CALIBRATION_VALUE2 */
    27138,   /* 26 -- NVRAM_PEN_CALIBRATION_VALUE3 */
    27139,   /* 27 -- NVRAM_PEN_CALIBRATION_VALUE4 */
    27140,   /* 28 -- NVRAM_PEN_CALIBRATION_VALUE5 */
    27141,   /* 29 -- NVRAM_PEN_CALIBRATION_VALUE6 */
    27142,   /* 30 -- NVRAM_PEN_CALIBRATION_VALUE7 */
    27143,   /* 31 -- NVRAM_PEN_CALIBRATION_VALUE8 */
    41001,   /* 32 -- NVRAM_DISPCHAR_AVATAR_WPSS_SERIALNUM */
     4804,   /* 33 -- NVRAM_MRE_SRV_DA_SIM1_PX */
     4806,   /* 34 -- NVRAM_MRE_SRV_DA_SIM2_PX */
     4808,   /* 35 -- NVRAM_MRE_SRV_DA_SIM3_PX */
     4810,   /* 36 -- NVRAM_MRE_SRV_DA_SIM4_PX */
    15640,   /* 37 -- NVRAM_UMMS_RETRIEVAL_SETTINGS */
};



const kal_uint32 NVRAM_EF_MMI_CACHE_BYTE_KEY_DEFAULT[NVRAM_MMI_CACHE_BYTE_KEY_SIZE * NVRAM_MMI_CACHE_BYTE_KEY_TOTAL / sizeof(kal_uint32)] =
{
    0x0033E086,   /* 0 -- NVRAM_BYTE_COVER_CLOSE_BACK_TO_IDLE */
    0x0588B0F2,   /* 1 -- NVRAM_WC_DST */
    0x0C5FC9DD,   /* 2 -- NVRAM_SETTING_LANG */
    0x1047E32F,   /* 3 -- NVRAM_SETTING_PICTURE_QUALITY */
    0x10FD69C4,   /* 4 -- NVRAM_SMS_MISCELL_SETTING */
    0x112B814E,   /* 5 -- NVRAM_CALLSET_CUG_ACTIVATED_ID */
    0x14915C3B,   /* 6 -- NVRAM_IME_ALPHABETIC_WORD_PREDICTION_FLAG */
    0x14F6111C,   /* 7 -- NVRAM_MRE_SRV_DA_IS_WIFI_ONLY */
    0x19F031B5,   /* 8 -- NVRAM_PHB_SAVE_CONTACT_NOTIFY */
    0x20182051,   /* 9 -- NVRAM_SETTING_MMS_MSG_FILTER */
    0x21246C43,   /* 10 -- NVRAM_NETSET_3G_CAPACITY_SIM */
    0x22D82416,   /* 11 -- NVRAM_VDOPLY_PROXY_IP1 */
    0x22D82417,   /* 12 -- NVRAM_VDOPLY_PROXY_IP2 */
    0x22D82418,   /* 13 -- NVRAM_VDOPLY_PROXY_IP3 */
    0x22D82419,   /* 14 -- NVRAM_VDOPLY_PROXY_IP4 */
    0x2322B5A4,   /* 15 -- NVRAM_IMGVIEW_VIEW_SYTLE */
    0x25031C82,   /* 16 -- NVRAM_PHNSET_LIVE_WALLPAPER */
    0x25F873DE,   /* 17 -- NVRAM_PNS_SWITCH */
    0x282D3360,   /* 18 -- NVRAM_CALLSET_BLACKLIST_MODE */
    0x2A9FDCAF,   /* 19 -- NVRAM_SETTING_AUTOKEYPADLOCK_TIME */
    0x2E994CA8,   /* 20 -- CURRENT_CITY */
    0x338FF87D,   /* 21 -- NVRAM_IME_AUTO_COMPLETION_FLAG */
    0x33E27B20,   /* 22 -- NVRAM_SETTING_HANDWRITING_ON */
    0x33E2BC2F,   /* 23 -- NVRAM_EF_FMGR_SORT_OPTION_LID */
    0x3617F479,   /* 24 -- NVRAM_WALLPAPER_ROTATE_STATUS */
    0x3911329F,   /* 25 -- NVRAM_SSC_DISABLE_FLAG */
    0x3F180537,   /* 26 -- NVRAM_SETTING_SPEED_DIAL */
    0x410A8A93,   /* 27 -- RESTORE_DEFAULT_OWNER_NO */
    0x4214065D,   /* 28 -- NVRAM_CALLSET_QUICK_END_FLAG */
    0x455E5A65,   /* 29 -- NVRAM_BYTE_LED_SETTING */
    0x495D7ACE,   /* 30 -- NVRAM_AUTO_VM_SETTING_VM_SUPPORT */
    0x4A787FB7,   /* 31 -- NVRAM_CALLSET_IP_NUMBER_SETTING */
    0x4AC1FB21,   /* 32 -- NVRAM_PHB_SPEAK_NAME_ON_OFF */
    0x4C43C045,   /* 33 -- NVRAM_CALLSET_REJ_BY_SMS_SETTING */
    0x5A4072DE,   /* 34 -- NVRAM_SETTING_STROKE_COLOR_INDEX */
    0x5C355B2E,   /* 35 -- NVRAM_AUDPLY_SINGLE_VOL */
    0x5C5012DE,   /* 36 -- NVRAM_CALLSET_REDIAL */
    0x605F66F6,   /* 37 -- NVRAM_PHB_NAME_DISPLAY_TYPE */
    0x608C8352,   /* 38 -- NVRAM_PNS_CHANGE_SIM */
    0x613F6FD6,   /* 39 -- NVRAM_CALLSET_CALL_TIME_DISPLAY */
    0x61D48B89,   /* 40 -- NVRAM_SMS_ACTIVE_PROFILE_INDEX */
    0x62CC3DCF,   /* 41 -- NVRAM_SRV_SNDREC_QUALITY */
    0x63D46A2D,   /* 42 -- FOREIGN_CITY */
    0x65135232,   /* 43 -- NVRAM_SMS_PREFER_STORAGE */
    0x655C92B2,   /* 44 -- TIME_FORMAT */
    0x66FB6043,   /* 45 -- RESTORE_DEFAULT_TIME_FORMAT */
    0x670179A5,   /* 46 -- NVRAM_SETTING_DT_DST */
    0x694DA578,   /* 47 -- NVRAM_BYTE_COVER_CLOSE_REJECT_CALL */
    0x6A89B90E,   /* 48 -- RESTORE_DEFAULT_AUTOUPDATE_TIME */
    0x6C769ED2,   /* 49 -- NVRAM_SETTING_PEN_SPEED */
    0x6CABCC51,   /* 50 -- NVRAM_SETTING_PEN_WIDTH */
    0x747C6326,   /* 51 -- NVRAM_NETSET_PREFERRED_MODE_PREV_RF_MODE */
    0x796DC810,   /* 52 -- NVRAM_IDLE_DIALER_SEARCH_SETTING */
    0x7B607913,   /* 53 -- NVRAM_SETTING_PREFER_MMS_STORAGE_MODE */
    0x7E232E40,   /* 54 -- NVRAM_SETTING_CONTRAST_SUBLCD_LEVEL */
    0x82A4E6B1,   /* 55 -- DATE_FORMAT */
    0x8443B442,   /* 56 -- RESTORE_DEFAULT_DATE_FORMAT */
    0x8602068E,   /* 57 -- NVRAM_PHB_STARTUP_COPY_SIM2 */
    0x8602068F,   /* 58 -- NVRAM_PHB_STARTUP_COPY_SIM3 */
    0x86020690,   /* 59 -- NVRAM_PHB_STARTUP_COPY_SIM4 */
    0x88D6787D,   /* 60 -- NVRAM_IME_INPUT_PATTERN */
    0x8AA30627,   /* 61 -- NVRAM_NPR_TTS_FLAG */
    0x90B5BE24,   /* 62 -- NVRAM_PHB_STARTUP_COPY_SIM */
    0x916EC587,   /* 63 -- NVRAM_UC_PREFERRED_MSG_TYPE */
    0x93E2D83E,   /* 64 -- NVRAM_CLNDR_FIRST_DAY_OF_WEEK */
    0x95A8D7A8,   /* 65 -- NVRAM_CALLSET_CONNECT_NOTICE */
    0x9F895786,   /* 66 -- NVRAM_PROFILES_LASTACTIVATED */
    0x9FC8B78B,   /* 67 -- NVRAM_SETTING_LANGUAGE_FOLLOW_VK */
    0xA08D6C77,   /* 68 -- NVRAM_BYTE_BL_SETTING_LEVEL */
    0xA3B72AA6,   /* 69 -- NVRAM_VDOPLY_VOLUMN */
    0xA4F4B75C,   /* 70 -- NVRAM_SETTING_OWNER_NO */
    0xA502111C,   /* 71 -- NVRAM_CALLSET_CTR_MODE */
    0xAC9F41E1,   /* 72 -- NVRAM_CALLSET_CALLERID */
    0xB084A4EF,   /* 73 -- NVRAM_DOWNLOAD_CITY1 */
    0xB084A4F0,   /* 74 -- NVRAM_DOWNLOAD_CITY2 */
    0xB0C01AEF,   /* 75 -- NVRAM_PNS_INTERVAL */
    0xB1A07148,   /* 76 -- NVRAM_DEFAULT_USB_APP */
    0xB3C62531,   /* 77 -- NVRAM_EF_SENSOR_UI_ROTATION_SWITCH */
    0xB4319F6A,   /* 78 -- NVRAM_IME_SMART_MODE_CONFIG */
    0xB4ADFEE7,   /* 79 -- NVRAM_DT_SEP_FORMAT */
    0xBA41A116,   /* 80 -- NVRAM_SETTING_CONTRAST_LEVEL */
    0xBAB0B4B7,   /* 81 -- NVRAM_IME_VIBRATION_FLAG */
    0xBBD81354,   /* 82 -- NVRAM_CALLSET_REJ_BY_SMS */
    0xC3A43A2C,   /* 83 -- NVRAM_TTS_VOL_LEVEL */
    0xCA6F0937,   /* 84 -- NVRAM_IME_CHINESE_WORD_PREDICTION_FLAG */
    0xCACC3F80,   /* 85 -- NVRAM_TODO_SRV_SNS_REMINDER_SOURCE */
    0xCBABBF4B,   /* 86 -- NVRAM_SRV_SNDREC_STORAGE */
    0xD3B20E31,   /* 87 -- NVRAM_VDOPLY_ACTIVE_PROFILE_IDX */
    0xD4572DA9,   /* 88 -- NVRAM_DUALMODE_MODE_SWITCH_TYPE */
    0xD4BAD7B8,   /* 89 -- NVRAM_IME_SOUND_FEEDBACK_FLAG */
    0xD523D15B,   /* 90 -- NVRAM_NETSET_PREFERRED_MODE */
    0xD598E1F4,   /* 91 -- NVRAM_HDSET_MODE_VOICE_LEVEL */
    0xDA758A87,   /* 92 -- NVRAM_UMMS_DEF_TMPLT_GEN_STATE */
    0xDC4F3C00,   /* 93 -- NVRAM_AUTO_VM_SETTING_AUTO_VM */
    0xDCE10CA4,   /* 94 -- NVRAM_LDSPK_MODE_VOICE_LEVEL */
    0xDE69511D,   /* 95 -- NVRAM_SETTING_AUTOKEYPADLOCK */
    0xDEED7E73,   /* 96 -- NVRAM_NORMAL_MODE_VOICE_LEVEL */
    0xE4CB8EFE,   /* 97 -- NVRAM_SETTING_STATUS_DT_TIME */
    0xE639E6DC,   /* 98 -- NVRAM_PROFILES_ACTIVATED */
    0xE664395C,   /* 99 -- NVRAM_SETTING_DEF_ENCODING */
    0xE8C65B43,   /* 100 -- NVRAM_VDOPLY_PROXY_ON_OFF */
    0xE928235D,   /* 101 -- NVRAM_IME_AUTO_CAPITALIZATION_FLAG */
    0xEE1A67D7,   /* 102 -- NVRAM_IME_AUTO_SPACE_FLAG */
    0xEE6763CD,   /* 103 -- NVRAM_SETTING_AUTOUPDATE_DT_TIME_STATUS */
    0xF4D2F8E1,   /* 104 -- NVRAM_TTS_VOICE_SEL */
    0xF8A67B30,   /* 105 -- NVRAM_BYTE_COVER_CLOSE_KEYPAD_LOCK */
    0xFA0E117A,   /* 106 -- NVRAM_AUTOUPDATE_DT_STATUS */
    0xFC2179AD,   /* 107 -- NVRAM_IDLE_DIALER_TTS_SETTING */
    0xFC8E7A60,   /* 108 -- NVRAM_RMGR_DB_CHECK */
    0xFCAC03A9,   /* 109 -- NVRAM_CALLSET_ANSWER_MODE */
};

const kal_uint32 NVRAM_EF_MMI_CACHE_SHORT_KEY_DEFAULT[NVRAM_MMI_CACHE_SHORT_KEY_SIZE * NVRAM_MMI_CACHE_SHORT_KEY_TOTAL / sizeof(kal_uint32)] =
{
    0x07A09DA4,   /* 0 -- NVRAM_SMSCOUNTERS_SENT_SHORT */
    0x0C2C7116,   /* 1 -- NVRAM_SETTING_PREFER_INPUT_METHOD */
    0x1D0EF6F8,   /* 2 -- NVRAM_VDOPLY_OPTION_BRIGHTNESS */
    0x1D98ABC2,   /* 3 -- NVRAM_SMS_CONCAT_MSG_REF_VALUE */
    0x238E70B2,   /* 4 -- NVRAM_CURRENT_POWER_OFF_DISPLAY */
    0x2702029F,   /* 5 -- NVRAM_WAP_PROF_ACTIVE_MMS_SIM1_DTCNT_INDEX */
    0x2D593480,   /* 6 -- NVRAM_SETTING_WRITING_LANG */
    0x3BAC79B6,   /* 7 -- NVRAM_UMMS_LANGUAGE_CHANGE */
    0x3D11F342,   /* 8 -- NVRAM_CURRENT_POWER_ON_DISPLAY */
    0x3D2C6F38,   /* 9 -- NVRAM_VDOPLY_STORAGE */
    0x41A226EC,   /* 10 -- NVRAM_WAP_PROF_ACTIVE_WAP_SIM1_DTCNT_INDEX */
    0x421A59BE,   /* 11 -- NVRAM_CALLSET_QUICK_END_TIME */
    0x446216AE,   /* 12 -- NVRAM_PHB_STORAGE_LOCATION */
    0x4E468AE0,   /* 13 -- NVRAM_SMSCOUNTERS_RECD_SHORT */
    0x54329DD6,   /* 14 -- NVRAM_FRN_TIMEZONE */
    0x55C9E89D,   /* 15 -- RESTORE_PREFER_INPUT_METHOD */
    0x613FAB1F,   /* 16 -- NVRAM_SCR_SNAPSHOT_SEQ_NO */
    0x61E906E7,   /* 17 -- RESTORE_DEFAULT_SETWALLPAPER_SUB */
    0x6A59FE18,   /* 18 -- NVRAM_BYTE_BL_SETTING_HFTIME */
    0x6D716BC2,   /* 19 -- NVRAM_VDOPLY_OPTION_REPEAT */
    0x79A7A46A,   /* 20 -- NVRAM_PHB_VCARD_VERSION */
    0x84CB0748,   /* 21 -- NVRAM_SETTING_ENABLED_WRITING_LANGUAGE */
    0x86763729,   /* 22 -- NVRAM_CAM_FILENAME_SEQ_NO */
    0x86773879,   /* 23 -- NVRAM_VDOPLY_SNAPSHOT_SEQ_NO */
    0x890C4A87,   /* 24 -- NVRAM_RESTORE_POWER_OFF_DISPLAY */
    0x910F4C1A,   /* 25 -- NVRAM_PHB_NAME_LIST_FILTER */
    0xA006B2C9,   /* 26 -- NVRAM_TODO_SRV_SNS_REMINDER_ID_H */
    0xA006B2CD,   /* 27 -- NVRAM_TODO_SRV_SNS_REMINDER_ID_L */
    0xA203F3C0,   /* 28 -- NVRAM_POWER_ON_DISPLAY_SUCCESS */
    0xA5052A46,   /* 29 -- NVRAM_CALLSET_CTR_TIME */
    0xA9842A5C,   /* 30 -- RESTORE_DEFAULT_FUNANDGAMES_SETWALLPAPER */
    0xAD3C1B39,   /* 31 -- NVRAM_TIMEZONE */
    0xBAD27847,   /* 32 -- NVRAM_VDOPLY_OPTION_PLAY_MODE */
    0xBC370ACD,   /* 33 -- NVRAM_RESTORE_POWER_ON_DISPLAY */
    0xBCD765E1,   /* 34 -- NVRAM_SETTING_WRITING_LANG_SUB */
    0xBE99E6A4,   /* 35 -- NVRAM_IMGVIEW_STORAGE */
    0xC96B627D,   /* 36 -- NVRAM_VDOPLY_STREAM_SEQ_NO */
    0xCF035F69,   /* 37 -- NVRAM_VDOPLY_OPTION_CONTRAST */
    0xDC2A15F6,   /* 38 -- NVRAM_FUNANDGAMES_SETWALLPAPER */
    0xEF592C81,   /* 39 -- NVRAM_SETWALLPAPER_SUB */
};

const kal_uint32 NVRAM_EF_MMI_CACHE_DOUBLE_KEY_DEFAULT[NVRAM_MMI_CACHE_DOUBLE_KEY_SIZE * NVRAM_MMI_CACHE_DOUBLE_KEY_TOTAL / sizeof(kal_uint32)] =
{
    0x029A6DEE,   /* 0 -- NVRAM_AUDIO_DEBUG_INFO1 */
    0x029A6DEF,   /* 1 -- NVRAM_AUDIO_DEBUG_INFO2 */
    0x029A6DF0,   /* 2 -- NVRAM_AUDIO_DEBUG_INFO3 */
    0x029A6DF1,   /* 3 -- NVRAM_AUDIO_DEBUG_INFO4 */
    0x29B4FC84,   /* 4 -- NVRAM_DISPCHAR_AVATAR_ONOFF_SERIALNUM */
    0x382F8DD5,   /* 5 -- NVRAM_VDOPLY_PROXY_PORT */
    0x49F0E9C0,   /* 6 -- NVRAM_UMMS_RESTORE_RETRIEVAL_SETTINGS */
    0x4C5F3D2A,   /* 7 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE1 */
    0x4C5F3D2B,   /* 8 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE2 */
    0x4C5F3D2C,   /* 9 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE3 */
    0x4C5F3D2D,   /* 10 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE4 */
    0x4C5F3D2E,   /* 11 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE5 */
    0x4C5F3D2F,   /* 12 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE6 */
    0x4C5F3D30,   /* 13 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE7 */
    0x4C5F3D31,   /* 14 -- NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE8 */
    0x55D698C6,   /* 15 -- NARAM_DISPCHAR_AVATAR_ONOFF */
    0x62F30CB5,   /* 16 -- NVRAM_MRE_SRV_DA_SIM1 */
    0x62F30CB6,   /* 17 -- NVRAM_MRE_SRV_DA_SIM2 */
    0x62F30CB7,   /* 18 -- NVRAM_MRE_SRV_DA_SIM3 */
    0x62F30CB8,   /* 19 -- NVRAM_MRE_SRV_DA_SIM4 */
    0x98AE5398,   /* 20 -- NVRAM_DISPCHAR_AVATAR_WPSS */
    0xA595E229,   /* 21 -- NVRAM_VDOPLY_LOWEST_UDP_PORT */
    0xB68B1B79,   /* 22 -- NVRAM_SRV_PROF_EXT_MELODY_BITS */
    0xB6B3EF7D,   /* 23 -- NVRAM_VDOPLY_HIGHEST_UDP_PORT */
    0xC384715B,   /* 24 -- NVRAM_PEN_CALIBRATION_VALUE1 */
    0xC384715C,   /* 25 -- NVRAM_PEN_CALIBRATION_VALUE2 */
    0xC384715D,   /* 26 -- NVRAM_PEN_CALIBRATION_VALUE3 */
    0xC384715E,   /* 27 -- NVRAM_PEN_CALIBRATION_VALUE4 */
    0xC384715F,   /* 28 -- NVRAM_PEN_CALIBRATION_VALUE5 */
    0xC3847160,   /* 29 -- NVRAM_PEN_CALIBRATION_VALUE6 */
    0xC3847161,   /* 30 -- NVRAM_PEN_CALIBRATION_VALUE7 */
    0xC3847162,   /* 31 -- NVRAM_PEN_CALIBRATION_VALUE8 */
    0xD017390B,   /* 32 -- NVRAM_DISPCHAR_AVATAR_WPSS_SERIALNUM */
    0xD9F529D2,   /* 33 -- NVRAM_MRE_SRV_DA_SIM1_PX */
    0xD9F59E31,   /* 34 -- NVRAM_MRE_SRV_DA_SIM2_PX */
    0xD9F61290,   /* 35 -- NVRAM_MRE_SRV_DA_SIM3_PX */
    0xD9F686EF,   /* 36 -- NVRAM_MRE_SRV_DA_SIM4_PX */
    0xFED5954F,   /* 37 -- NVRAM_UMMS_RETRIEVAL_SETTINGS */
};



#ifdef __MTK_INTERNAL__
/* type (1: byte cache,  2: short cache   8:double cache) */
/* This API is only used for meta tool */
kal_int16 mmi_rp_mmi_cache_search_index(kal_uint16 nDataItemId, kal_uint8 nDataType)
{
    kal_uint16 index, total= 0;
    const kal_uint16 *tbl;

    switch(nDataType)
    {
    case 1:
        tbl = MMI_CACHE_BYTE_ENUM_TABLE;
        total = MMI_CACHE_BYTE_NUMBER;
        break;
    case 2:
        tbl = MMI_CACHE_SHORT_ENUM_TABLE;
        total = MMI_CACHE_SHORT_NUMBER;
        break;
    case 8:
        tbl = MMI_CACHE_DOUBLE_ENUM_TABLE;
        total = MMI_CACHE_DOUBLE_NUMBER;
        break;
    default:
        tbl = NULL;
        total = 0;
    }
    for( index = 0 ; index < total ; index++)
    {
        if (tbl[index] == nDataItemId)
            return index;
    }
    return -1;
}
#endif


/********************************************************
 *  This file is generated automatically by resource gen
 *  Please do not modify it here manually 
 ***********************************************************/



#include "mmi_res_range_def.h"
#include "nvram_enums.h"
#include "nvram_interface.h"



/*****************************************************************************
 * FUNCTION
 *  nvram_restore_byte_cache()
 * DESCRIPTION
 *  used to restore mmi_cache_byte to default value
 * PARAMETERS
 *  buffer    [IN]
 * RETURNS
 *  none
 *****************************************************************************/
void nvram_restore_byte_cache(nvram_reset_category_enum category,nvram_app_id_enum app_id, kal_uint8 *buffer)
{
    /*----------------------------------------------------------------*/
    /* Local Variables                                                */
    /*----------------------------------------------------------------*/

    /*----------------------------------------------------------------*/
    /* Code Body                                                      */
    /*----------------------------------------------------------------*/
    kal_uint8 *def_buf;
    nvram_get_default_value(NVRAM_EF_CACHE_BYTE_LID, 1, &def_buf);
    switch(app_id)
    {
    case 0:  /* for restore factory, reset all app item */
    case APP_MRE: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_BOOTUP: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_CAMERA: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_IMAGEVIEWER: 
        buffer[ 15] = def_buf[ 15];     /* 35212: NVRAM_IMGVIEW_VIEW_SYTLE */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_SOUNDRECORDER: 
        buffer[ 30] = def_buf[ 30];     /* 35555: NVRAM_AUTO_VM_SETTING_VM_SUPPORT */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_AUDIOPLAYER: 
        buffer[ 35] = def_buf[ 35];     /* 35856: NVRAM_AUDPLY_SINGLE_VOL */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_WORLDCLOCK: 
        buffer[ 20] = def_buf[ 20];     /* 37586: CURRENT_CITY */
        buffer[ 42] = def_buf[ 42];     /* 37587: FOREIGN_CITY */
        buffer[ 46] = def_buf[ 46];     /* 37588: NVRAM_SETTING_DT_DST */
        buffer[  1] = def_buf[  1];     /* 37590: NVRAM_WC_DST */
        buffer[ 73] = def_buf[ 73];     /* 37592: NVRAM_DOWNLOAD_CITY1 */
        buffer[ 74] = def_buf[ 74];     /* 37593: NVRAM_DOWNLOAD_CITY2 */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_UNIFIEDCOMPOSER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_RMGR: 
        buffer[108] = def_buf[108];     /* 38614: NVRAM_RMGR_DB_CHECK */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_WALLPAPER: 
        buffer[ 24] = def_buf[ 24];     /* 41003: NVRAM_WALLPAPER_ROTATE_STATUS */
        buffer[ 16] = def_buf[ 16];     /* 41004: NVRAM_PHNSET_LIVE_WALLPAPER */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PHNSET_ONOFF: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_PHONESETTING_NEW: 
        buffer[ 70] = def_buf[ 27];     /* 42228: NVRAM_SETTING_OWNER_NO = 42229: RESTORE_DEFAULT_OWNER_NO*/
        buffer[ 97] = def_buf[ 97];     /* 42230: NVRAM_SETTING_STATUS_DT_TIME */
        buffer[106] = def_buf[106];     /* 42231: NVRAM_AUTOUPDATE_DT_STATUS */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_NITZ: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_CALENDAR: 
        buffer[ 64] = def_buf[ 64];     /* 44601: NVRAM_CLNDR_FIRST_DAY_OF_WEEK */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_VDOPLY: 
        buffer[ 69] = def_buf[ 69];     /* 46920: NVRAM_VDOPLY_VOLUMN */
        buffer[ 87] = def_buf[ 87];     /* 46921: NVRAM_VDOPLY_ACTIVE_PROFILE_IDX */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PROF: 
        buffer[ 98] = def_buf[ 98];     /*  7795: NVRAM_PROFILES_ACTIVATED */
        buffer[ 66] = def_buf[ 66];     /*  7796: NVRAM_PROFILES_LASTACTIVATED */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_SMS: 
        buffer[  4] = def_buf[  4];     /*  9499: NVRAM_SMS_MISCELL_SETTING */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_EDITOR: 
        buffer[ 78] = def_buf[ 78];     /* 26131: NVRAM_IME_SMART_MODE_CONFIG */
        buffer[101] = def_buf[101];     /* 26132: NVRAM_IME_AUTO_CAPITALIZATION_FLAG */
        buffer[ 21] = def_buf[ 21];     /* 26133: NVRAM_IME_AUTO_COMPLETION_FLAG */
        buffer[  6] = def_buf[  6];     /* 26134: NVRAM_IME_ALPHABETIC_WORD_PREDICTION_FLAG */
        buffer[ 84] = def_buf[ 84];     /* 26135: NVRAM_IME_CHINESE_WORD_PREDICTION_FLAG */
        buffer[102] = def_buf[102];     /* 26136: NVRAM_IME_AUTO_SPACE_FLAG */
        buffer[ 81] = def_buf[ 81];     /* 26137: NVRAM_IME_VIBRATION_FLAG */
        buffer[ 89] = def_buf[ 89];     /* 26138: NVRAM_IME_SOUND_FEEDBACK_FLAG */
        buffer[ 60] = def_buf[ 60];     /* 26139: NVRAM_IME_INPUT_PATTERN */
        buffer[ 49] = def_buf[ 49];     /* 26145: NVRAM_SETTING_PEN_SPEED */
        buffer[ 67] = def_buf[ 67];     /* 26146: NVRAM_SETTING_LANGUAGE_FOLLOW_VK */
        buffer[ 22] = def_buf[ 22];     /* 26147: NVRAM_SETTING_HANDWRITING_ON */
        buffer[ 50] = def_buf[ 50];     /* 26148: NVRAM_SETTING_PEN_WIDTH */
        buffer[ 34] = def_buf[ 34];     /* 26149: NVRAM_SETTING_STROKE_COLOR_INDEX */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_ENGINEERMODE1: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_FILEMANAGER: 
        buffer[ 23] = def_buf[ 23];     /* 14313: NVRAM_EF_FMGR_SORT_OPTION_LID */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PNS: 
        buffer[ 75] = def_buf[ 75];     /* 14414: NVRAM_PNS_INTERVAL */
        buffer[ 17] = def_buf[ 17];     /* 14415: NVRAM_PNS_SWITCH */
        buffer[ 38] = def_buf[ 38];     /* 14416: NVRAM_PNS_CHANGE_SIM */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_USBSRV: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_MMS: 
        buffer[ 53] = def_buf[ 53];     /* 15643: NVRAM_SETTING_PREFER_MMS_STORAGE_MODE */
        buffer[  9] = def_buf[  9];     /* 15644: NVRAM_SETTING_MMS_MSG_FILTER */
        buffer[ 92] = def_buf[ 92];     /* 15645: NVRAM_UMMS_DEF_TMPLT_GEN_STATE */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_WAP_PROF: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_GPIO: 
        buffer[ 80] = def_buf[ 80];     /* 26254: NVRAM_SETTING_CONTRAST_LEVEL */
        buffer[ 29] = def_buf[ 29];     /* 26259: NVRAM_BYTE_LED_SETTING */
        buffer[ 68] = def_buf[ 68];     /* 26260: NVRAM_BYTE_BL_SETTING_LEVEL */
        buffer[  0] = def_buf[  0];     /* 26262: NVRAM_BYTE_COVER_CLOSE_BACK_TO_IDLE */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_GPIO: 
        buffer[  3] = def_buf[  3];     /* 26285: NVRAM_SETTING_PICTURE_QUALITY */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_NETSET: 
        buffer[ 90] = def_buf[ 90];     /* 26316: NVRAM_NETSET_PREFERRED_MODE */
        buffer[ 51] = def_buf[ 51];     /* 26317: NVRAM_NETSET_PREFERRED_MODE_PREV_RF_MODE */
        buffer[ 10] = def_buf[ 10];     /* 26318: NVRAM_NETSET_3G_CAPACITY_SIM */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_CALLSET: 
        buffer[ 72] = def_buf[ 72];     /*  9602: NVRAM_CALLSET_CALLERID */
        buffer[  5] = def_buf[  5];     /*  9603: NVRAM_CALLSET_CUG_ACTIVATED_ID */
        buffer[ 71] = def_buf[ 71];     /*  9604: NVRAM_CALLSET_CTR_MODE */
        buffer[109] = def_buf[109];     /*  9605: NVRAM_CALLSET_ANSWER_MODE */
        buffer[ 39] = def_buf[ 39];     /*  9606: NVRAM_CALLSET_CALL_TIME_DISPLAY */
        buffer[ 36] = def_buf[ 36];     /*  9607: NVRAM_CALLSET_REDIAL */
        buffer[ 82] = def_buf[ 82];     /*  9608: NVRAM_CALLSET_REJ_BY_SMS */
        buffer[ 33] = def_buf[ 33];     /*  9609: NVRAM_CALLSET_REJ_BY_SMS_SETTING */
        buffer[ 65] = def_buf[ 65];     /*  9610: NVRAM_CALLSET_CONNECT_NOTICE */
        buffer[ 31] = def_buf[ 31];     /*  9611: NVRAM_CALLSET_IP_NUMBER_SETTING */
        buffer[ 18] = def_buf[ 18];     /*  9612: NVRAM_CALLSET_BLACKLIST_MODE */
        buffer[ 28] = def_buf[ 28];     /*  9613: NVRAM_CALLSET_QUICK_END_FLAG */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_MODESWITCH: 
        buffer[ 88] = def_buf[ 88];     /* 27117: NVRAM_DUALMODE_MODE_SWITCH_TYPE */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PEN_CALIBRATION: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_GENERAL_SETTING: 
        buffer[ 44] = def_buf[ 44];     /* 27159: TIME_FORMAT */
        buffer[ 55] = def_buf[ 55];     /* 27160: DATE_FORMAT */
        buffer[ 79] = def_buf[ 79];     /* 27163: NVRAM_DT_SEP_FORMAT */
        buffer[  2] = def_buf[  2];     /* 27164: NVRAM_SETTING_LANG */
        buffer[ 99] = def_buf[ 99];     /* 27165: NVRAM_SETTING_DEF_ENCODING */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case CUI_DIALER: 
        buffer[107] = def_buf[107];     /* 28309: NVRAM_IDLE_DIALER_TTS_SETTING */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_SCR_LOCKER: 
        buffer[ 95] = def_buf[ 95];     /* 28278: NVRAM_SETTING_AUTOKEYPADLOCK */
        buffer[ 19] = def_buf[ 19];     /* 28279: NVRAM_SETTING_AUTOKEYPADLOCK_TIME */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_AUTO_ROTATE: 
        buffer[ 77] = def_buf[ 77];     /* 30246: NVRAM_EF_SENSOR_UI_ROTATION_SWITCH */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_TODOLIST: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_SOUNDREC: 
        buffer[ 86] = def_buf[ 86];     /* 30320: NVRAM_SRV_SNDREC_STORAGE */
        buffer[ 41] = def_buf[ 41];     /* 30321: NVRAM_SRV_SNDREC_QUALITY */
        buffer[ 93] = def_buf[ 93];     /* 30322: NVRAM_AUTO_VM_SETTING_AUTO_VM */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PHB: 
        buffer[ 32] = def_buf[ 32];     /* 32149: NVRAM_PHB_SPEAK_NAME_ON_OFF */
        buffer[ 37] = def_buf[ 37];     /* 32154: NVRAM_PHB_NAME_DISPLAY_TYPE */
        buffer[  8] = def_buf[  8];     /* 32158: NVRAM_PHB_SAVE_CONTACT_NOTIFY */
        buffer[ 52] = def_buf[ 52];     /* 32160: NVRAM_IDLE_DIALER_SEARCH_SETTING */
        buffer[ 26] = def_buf[ 26];     /* 32161: NVRAM_SETTING_SPEED_DIAL */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_NITZ: 
        buffer[103] = def_buf[103];     /* 32335: NVRAM_SETTING_AUTOUPDATE_DT_TIME_STATUS */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_NPR_TTS: 
        buffer[ 61] = def_buf[ 61];     /* 32999: NVRAM_NPR_TTS_FLAG */
        buffer[ 83] = def_buf[ 83];     /* 33000: NVRAM_TTS_VOL_LEVEL */
        buffer[104] = def_buf[104];     /* 33001: NVRAM_TTS_VOICE_SEL */
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    default:
        break;
    };
}



/*****************************************************************************
 * FUNCTION
 *  nvram_restore_short_cache()
 * DESCRIPTION
 *  used to restore mmi_cache_short to default value
 * PARAMETERS
 *  buffer    [IN]
 * RETURNS
 *  none
 *****************************************************************************/
void nvram_restore_short_cache(nvram_reset_category_enum category,nvram_app_id_enum app_id, kal_uint8 *buffer)
{
    /*----------------------------------------------------------------*/
    /* Local Variables                                                */
    /*----------------------------------------------------------------*/

    /*----------------------------------------------------------------*/
    /* Code Body                                                      */
    /*----------------------------------------------------------------*/
    kal_uint8 *def_buf;
    nvram_get_default_value(NVRAM_EF_CACHE_SHORT_LID, 1, &def_buf);
    switch(app_id)
    {
    case 0:  /* for restore factory, reset all app item */
    case APP_MRE: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_BOOTUP: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_CAMERA: 
        buffer[ 44] = def_buf[ 44];     /* 34611: NVRAM_CAM_FILENAME_SEQ_NO */
        buffer[ 45] = def_buf[ 45];
        buffer[ 32] = def_buf[ 32];     /* 34612: NVRAM_SCR_SNAPSHOT_SEQ_NO */
        buffer[ 33] = def_buf[ 33];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_IMAGEVIEWER: 
        buffer[ 70] = def_buf[ 70];     /* 35213: NVRAM_IMGVIEW_STORAGE */
        buffer[ 71] = def_buf[ 71];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_SOUNDRECORDER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_AUDIOPLAYER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_WORLDCLOCK: 
        buffer[ 62] = def_buf[ 62];     /* 37589: NVRAM_TIMEZONE */
        buffer[ 63] = def_buf[ 63];
        buffer[ 28] = def_buf[ 28];     /* 37591: NVRAM_FRN_TIMEZONE */
        buffer[ 29] = def_buf[ 29];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_UNIFIEDCOMPOSER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_RMGR: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_WALLPAPER: 
        buffer[ 76] = def_buf[ 76];     /* 41005: NVRAM_FUNANDGAMES_SETWALLPAPER */
        buffer[ 77] = def_buf[ 77];
        buffer[ 78] = def_buf[ 34];     /* 41007: NVRAM_SETWALLPAPER_SUB = 41008: RESTORE_DEFAULT_SETWALLPAPER_SUB*/
        buffer[ 79] = def_buf[ 35];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PHNSET_ONOFF: 
        buffer[ 16] = def_buf[ 66];     /* 41203: NVRAM_CURRENT_POWER_ON_DISPLAY = 41201: NVRAM_RESTORE_POWER_ON_DISPLAY*/
        buffer[ 17] = def_buf[ 67];
        buffer[  8] = def_buf[ 48];     /* 41204: NVRAM_CURRENT_POWER_OFF_DISPLAY = 41202: NVRAM_RESTORE_POWER_OFF_DISPLAY*/
        buffer[  9] = def_buf[ 49];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_PHONESETTING_NEW: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_NITZ: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_CALENDAR: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_VDOPLY: 
        buffer[ 18] = def_buf[ 18];     /* 46928: NVRAM_VDOPLY_STORAGE */
        buffer[ 19] = def_buf[ 19];
        buffer[  4] = def_buf[  4];     /* 46929: NVRAM_VDOPLY_OPTION_BRIGHTNESS */
        buffer[  5] = def_buf[  5];
        buffer[ 74] = def_buf[ 74];     /* 46930: NVRAM_VDOPLY_OPTION_CONTRAST */
        buffer[ 75] = def_buf[ 75];
        buffer[ 38] = def_buf[ 38];     /* 46931: NVRAM_VDOPLY_OPTION_REPEAT */
        buffer[ 39] = def_buf[ 39];
        buffer[ 64] = def_buf[ 64];     /* 46932: NVRAM_VDOPLY_OPTION_PLAY_MODE */
        buffer[ 65] = def_buf[ 65];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PROF: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_SMS: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_EDITOR: 
        buffer[  2] = def_buf[ 30];     /* 26140: NVRAM_SETTING_PREFER_INPUT_METHOD = 26141: RESTORE_PREFER_INPUT_METHOD*/
        buffer[  3] = def_buf[ 31];
        buffer[ 12] = def_buf[ 12];     /* 26142: NVRAM_SETTING_WRITING_LANG */
        buffer[ 13] = def_buf[ 13];
        buffer[ 68] = def_buf[ 68];     /* 26143: NVRAM_SETTING_WRITING_LANG_SUB */
        buffer[ 69] = def_buf[ 69];
        buffer[ 42] = def_buf[ 42];     /* 26144: NVRAM_SETTING_ENABLED_WRITING_LANGUAGE */
        buffer[ 43] = def_buf[ 43];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_ENGINEERMODE1: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_FILEMANAGER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PNS: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_USBSRV: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_MMS: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_WAP_PROF: 
        buffer[ 20] = def_buf[ 20];     /* 17714: NVRAM_WAP_PROF_ACTIVE_WAP_SIM1_DTCNT_INDEX */
        buffer[ 21] = def_buf[ 21];
        buffer[ 10] = def_buf[ 10];     /* 17715: NVRAM_WAP_PROF_ACTIVE_MMS_SIM1_DTCNT_INDEX */
        buffer[ 11] = def_buf[ 11];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_GPIO: 
        buffer[ 36] = def_buf[ 36];     /* 26261: NVRAM_BYTE_BL_SETTING_HFTIME */
        buffer[ 37] = def_buf[ 37];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_GPIO: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_NETSET: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_CALLSET: 
        buffer[ 22] = def_buf[ 22];     /*  9615: NVRAM_CALLSET_QUICK_END_TIME */
        buffer[ 23] = def_buf[ 23];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_MODESWITCH: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PEN_CALIBRATION: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_GENERAL_SETTING: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case CUI_DIALER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_SCR_LOCKER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_AUTO_ROTATE: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_TODOLIST: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_SOUNDREC: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PHB: 
        buffer[ 24] = def_buf[ 24];     /* 32155: NVRAM_PHB_STORAGE_LOCATION */
        buffer[ 25] = def_buf[ 25];
        buffer[ 50] = def_buf[ 50];     /* 32156: NVRAM_PHB_NAME_LIST_FILTER */
        buffer[ 51] = def_buf[ 51];
        buffer[ 40] = def_buf[ 40];     /* 32157: NVRAM_PHB_VCARD_VERSION */
        buffer[ 41] = def_buf[ 41];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_NITZ: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_NPR_TTS: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    default:
        break;
    };
}



/*****************************************************************************
 * FUNCTION
 *  nvram_restore_double_cache()
 * DESCRIPTION
 *  used to restore mmi_cache_double to default value
 * PARAMETERS
 *  buffer    [IN]
 * RETURNS
 *  none
 *****************************************************************************/
void nvram_restore_double_cache(nvram_reset_category_enum category,nvram_app_id_enum app_id, kal_uint8 *buffer)
{
    /*----------------------------------------------------------------*/
    /* Local Variables                                                */
    /*----------------------------------------------------------------*/

    /*----------------------------------------------------------------*/
    /* Code Body                                                      */
    /*----------------------------------------------------------------*/
    kal_uint8 *def_buf;
    nvram_get_default_value(NVRAM_EF_CACHE_DOUBLE_LID, 1, &def_buf);
    switch(app_id)
    {
    case 0:  /* for restore factory, reset all app item */
    case APP_MRE: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_BOOTUP: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_CAMERA: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_IMAGEVIEWER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_SOUNDRECORDER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_AUDIOPLAYER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_WORLDCLOCK: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_UNIFIEDCOMPOSER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_RMGR: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_WALLPAPER: 
        buffer[160] = def_buf[160];     /* 40999: NVRAM_DISPCHAR_AVATAR_WPSS */
        buffer[161] = def_buf[161];
        buffer[162] = def_buf[162];
        buffer[163] = def_buf[163];
        buffer[164] = def_buf[164];
        buffer[165] = def_buf[165];
        buffer[166] = def_buf[166];
        buffer[167] = def_buf[167];
        buffer[120] = def_buf[120];     /* 41000: NARAM_DISPCHAR_AVATAR_ONOFF */
        buffer[121] = def_buf[121];
        buffer[122] = def_buf[122];
        buffer[123] = def_buf[123];
        buffer[124] = def_buf[124];
        buffer[125] = def_buf[125];
        buffer[126] = def_buf[126];
        buffer[127] = def_buf[127];
        buffer[256] = def_buf[256];     /* 41001: NVRAM_DISPCHAR_AVATAR_WPSS_SERIALNUM */
        buffer[257] = def_buf[257];
        buffer[258] = def_buf[258];
        buffer[259] = def_buf[259];
        buffer[260] = def_buf[260];
        buffer[261] = def_buf[261];
        buffer[262] = def_buf[262];
        buffer[263] = def_buf[263];
        buffer[ 32] = def_buf[ 32];     /* 41002: NVRAM_DISPCHAR_AVATAR_ONOFF_SERIALNUM */
        buffer[ 33] = def_buf[ 33];
        buffer[ 34] = def_buf[ 34];
        buffer[ 35] = def_buf[ 35];
        buffer[ 36] = def_buf[ 36];
        buffer[ 37] = def_buf[ 37];
        buffer[ 38] = def_buf[ 38];
        buffer[ 39] = def_buf[ 39];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PHNSET_ONOFF: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_PHONESETTING_NEW: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_NITZ: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_CALENDAR: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_VDOPLY: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PROF: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_SMS: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_EDITOR: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_ENGINEERMODE1: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_FILEMANAGER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PNS: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_USBSRV: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_MMS: 
        buffer[296] = def_buf[ 48];     /* 15640: NVRAM_UMMS_RETRIEVAL_SETTINGS = 15641: NVRAM_UMMS_RESTORE_RETRIEVAL_SETTINGS*/
        buffer[297] = def_buf[ 49];
        buffer[298] = def_buf[ 50];
        buffer[299] = def_buf[ 51];
        buffer[300] = def_buf[ 52];
        buffer[301] = def_buf[ 53];
        buffer[302] = def_buf[ 54];
        buffer[303] = def_buf[ 55];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_WAP_PROF: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_GPIO: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_GPIO: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_NETSET: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_CALLSET: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_MODESWITCH: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PEN_CALIBRATION: 
        buffer[192] = def_buf[ 56];     /* 27136: NVRAM_PEN_CALIBRATION_VALUE1 = 27128: NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE1*/
        buffer[193] = def_buf[ 57];
        buffer[194] = def_buf[ 58];
        buffer[195] = def_buf[ 59];
        buffer[196] = def_buf[ 60];
        buffer[197] = def_buf[ 61];
        buffer[198] = def_buf[ 62];
        buffer[199] = def_buf[ 63];
        buffer[200] = def_buf[ 64];     /* 27137: NVRAM_PEN_CALIBRATION_VALUE2 = 27129: NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE2*/
        buffer[201] = def_buf[ 65];
        buffer[202] = def_buf[ 66];
        buffer[203] = def_buf[ 67];
        buffer[204] = def_buf[ 68];
        buffer[205] = def_buf[ 69];
        buffer[206] = def_buf[ 70];
        buffer[207] = def_buf[ 71];
        buffer[208] = def_buf[ 72];     /* 27138: NVRAM_PEN_CALIBRATION_VALUE3 = 27130: NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE3*/
        buffer[209] = def_buf[ 73];
        buffer[210] = def_buf[ 74];
        buffer[211] = def_buf[ 75];
        buffer[212] = def_buf[ 76];
        buffer[213] = def_buf[ 77];
        buffer[214] = def_buf[ 78];
        buffer[215] = def_buf[ 79];
        buffer[216] = def_buf[ 80];     /* 27139: NVRAM_PEN_CALIBRATION_VALUE4 = 27131: NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE4*/
        buffer[217] = def_buf[ 81];
        buffer[218] = def_buf[ 82];
        buffer[219] = def_buf[ 83];
        buffer[220] = def_buf[ 84];
        buffer[221] = def_buf[ 85];
        buffer[222] = def_buf[ 86];
        buffer[223] = def_buf[ 87];
        buffer[224] = def_buf[ 88];     /* 27140: NVRAM_PEN_CALIBRATION_VALUE5 = 27132: NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE5*/
        buffer[225] = def_buf[ 89];
        buffer[226] = def_buf[ 90];
        buffer[227] = def_buf[ 91];
        buffer[228] = def_buf[ 92];
        buffer[229] = def_buf[ 93];
        buffer[230] = def_buf[ 94];
        buffer[231] = def_buf[ 95];
        buffer[232] = def_buf[ 96];     /* 27141: NVRAM_PEN_CALIBRATION_VALUE6 = 27133: NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE6*/
        buffer[233] = def_buf[ 97];
        buffer[234] = def_buf[ 98];
        buffer[235] = def_buf[ 99];
        buffer[236] = def_buf[100];
        buffer[237] = def_buf[101];
        buffer[238] = def_buf[102];
        buffer[239] = def_buf[103];
        buffer[240] = def_buf[104];     /* 27142: NVRAM_PEN_CALIBRATION_VALUE7 = 27134: NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE7*/
        buffer[241] = def_buf[105];
        buffer[242] = def_buf[106];
        buffer[243] = def_buf[107];
        buffer[244] = def_buf[108];
        buffer[245] = def_buf[109];
        buffer[246] = def_buf[110];
        buffer[247] = def_buf[111];
        buffer[248] = def_buf[112];     /* 27143: NVRAM_PEN_CALIBRATION_VALUE8 = 27135: NVRAM_RESTORE_DEFAULT_PEN_CALIBRATION_VALUE8*/
        buffer[249] = def_buf[113];
        buffer[250] = def_buf[114];
        buffer[251] = def_buf[115];
        buffer[252] = def_buf[116];
        buffer[253] = def_buf[117];
        buffer[254] = def_buf[118];
        buffer[255] = def_buf[119];
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_GENERAL_SETTING: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case CUI_DIALER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_SCR_LOCKER: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_AUTO_ROTATE: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_TODOLIST: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_SOUNDREC: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_PHB: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case SRV_NITZ: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    case APP_NPR_TTS: 
        if (category == NVRAM_RESET_CERTAIN)
        {
            break;
        }
    default:
        break;
    };
}


