/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
#include "PixtelDatatypes.h"
#include "MMI_features.h"
#include "gui_themes.h"
#include "ThemeComponents.h"

#define MAX_MMI_THEMES 3


#if !defined (MMI_ON_HARDWARE_P)
__declspec(dllexport)
#endif
S32 mtk_n_MMI_themes=MAX_MMI_THEMES;

const MMI_theme theme_1={
(UI_filled_area*)&LSK_up_1,
(UI_filled_area*)&LSK_down_1,
(UI_filled_area*)&Disabled_items,
(UI_filled_area*)&RSK_up_1,
(UI_filled_area*)&RSK_down_1,
(UI_filled_area*)&Disabled_items,
(UI_filled_area*)&mtab_1,
(UI_filled_area*)&ibox_1,
(UI_filled_area*)&sbar_bkgrnd_1,
(UI_filled_area*)&sbar_indicator_1,
(UI_filled_area*)&Title_1,
(UI_filled_area*)&list_bkgrnd_1,
(UI_filled_area*)&list_normal_item_1,
(UI_filled_area*)&list_selected_item_1,
(UI_filled_area*)&Disabled_items,
(UI_filled_area*)&matrix_bkgrnd_1,
(UI_filled_area*)&matrix_normal_item_1,
(UI_filled_area*)&matrix_selected_item_1,
(UI_filled_area*)&Disabled_items,
(UI_filled_area*)&General_BG,
(UI_filled_area*)&fibox_normal_1,
(UI_filled_area*)&fibox_selected_1,
(UI_filled_area*)&mm_bkgrnd_1,
(UI_filled_area*)&General_BG,
(UI_filled_area*)&popup_description_bkgrnd_1,
(UI_filled_area*)&list_bkgrnd_1,
(UI_filled_area*)&list_normal_item_1,
(UI_filled_area*)&list_selected_item_1,
(UI_filled_area*)&Disabled_items,
(UI_filled_area*)&list_selected_item_1,
(UI_filled_area*)&General_BG,
(UI_filled_area*)&Unused,
(UI_filled_area*)&list_selected_item_1,
(UI_filled_area*)&common_screen_BG,
(UI_filled_area*)&common_screen_BG,
(UI_filled_area*)&common_screen_BG,
(UI_filled_area*)&common_screen_BG,
(UI_filled_area*)&dial_inputbox_bg_filler,
(UI_filled_area*)&virtual_keyboard_down_bkgrnd_1,
(color*)&black_color,
(color*)&white_color,
(color*)&lite_disp_scr_bg_col_1,
(color*)&LSK_up_txt_col_1,
(color*)&LSK_down_txt_col_1,
(color*)&Disabled_text_col,
(color*)&RSK_up_txt_col_1,
(color*)&RSK_down_txt_col_1,
(color*)&Disabled_text_col,
(color*)&mtab_selector_txt_col_1,
(color*)&mtab_normal_txt_col_1,
(color*)&mtab_selected_txt_col_1,
(color*)&ibox_normal_txt_col_1,
(color*)&ibox_selected_txt_col_1,
(color*)&ibox_selector_col_1,
(color*)&ibox_cursor_col_1,
(color*)&title_scut_txt_col_1,
(color*)&white_color,
(color*)&title_scut_txt_col_1,
(color*)&list_normal_txt_col_1,
(color*)&list_selected_txt_col_1,
(color*)&Disabled_text_col,
(color*)&list_normal_txt_col_1,
(color*)&list_selected_txt_col_1,
(color*)&Disabled_text_col,
(color*)&Unused_color,
(color*)&Unused_color,
(color*)&Unused_color,
(color*)&Unused_color,
(color*)&scut_indicator_txt_col_1,
(color*)&white_color,
(color*)&Unused_color,
(color*)&Unused_color,
(color*)&Unused_color,
(color*)&ibox_selector_col_1,
(color*)&ibox_normal_txt_col_1,
(color*)&Disabled_text_col,
(color*)&ibox_selected_txt_col_1,
(color*)&ibox_cursor_col_1,
(color*)&list_normal_txt_col_1,
(color*)&list_selected_txt_col_1,
(color*)&Disabled_text_col,
(color*)&list_normal_txt_col_1,
(color*)&list_selected_txt_col_1,
(color*)&Disabled_text_col,
(color*)&list_normal_txt_col_1,
(color*)&list_selected_txt_col_1,
(color*)&Disabled_text_col,
(color*)&white_color,
(color*)&black_color,
(color*)&popup_description_txt_col_1,
(color*)&white_color,
(color*)&white_color,
(color*)&black_color,
(color*)&black_color,
(color*)&black_color,
(color*)&black_color,
(color*)&button_bar_col_1,
(color*)&information_bar_col_1,
(color*)&input_method_txt_col_1,
(color*)&input_method_txt_col_1,
(color*)&Status_bar_col,
(color*)&black_color,
(color*)&ibox_normal_txt_col_1,
(color*)&ibox_selected_txt_col_1,
(color*)&ibox_selector_col_1,
(color*)&ibox_cursor_col_1,
(color*)&list_normal_txt_col_1,
(color*)&list_selected_txt_col_1,
(color*)&Disabled_text_col,
(color*)&ibox_normal_txt_col_1,
(color*)&ibox_selected_txt_col_1,
(color*)&ibox_selector_col_1,
(color*)&ibox_cursor_col_1,
(color*)&ibox_normal_txt_col_1,
(color*)&ibox_selected_txt_col_1,
(color*)&ibox_selector_col_1,
(color*)&ibox_cursor_col_1,
(color*)&virtual_keyboard_key_down_text_col_1,
(color*)&virtual_keyboard_key_up_text_col_1,
(color*)&virtual_keyboard_dead_key_down_text_col_1,
(color*)&virtual_keyboard_dead_key_up_text_col_1,
(color*)&virtual_keyboard_disp_area_text_col_1,
&MMI_medium_font,
&MMI_medium_font,
&MMI_medium_font,
&MMI_medium_font,
&MMI_default_font,
&MMI_default_font,
&MMI_default_font,
&MMI_default_font,
&MMI_default_font,
&MMI_default_font,
&MMI_default_font,
&MMI_default_font,
&MMI_default_font,
&MMI_virtual_keyboard_font,
UI_SCROLLBAR_WIDTH
};

const MMI_theme theme_2={
(UI_filled_area*)&LSK_up_2,
(UI_filled_area*)&LSK_down_2,
(UI_filled_area*)&Disabled_items,
(UI_filled_area*)&RSK_up_2,
(UI_filled_area*)&RSK_down_2,
(UI_filled_area*)&Disabled_items,
(UI_filled_area*)&mtab_2,
(UI_filled_area*)&ibox_2,
(UI_filled_area*)&sbar_bkgrnd_2,
(UI_filled_area*)&sbar_indicator_2,
(UI_filled_area*)&Title_2,
(UI_filled_area*)&list_bkgrnd_2,
(UI_filled_area*)&list_normal_item_2,
(UI_filled_area*)&list_selected_item_2,
(UI_filled_area*)&Disabled_items,
(UI_filled_area*)&matrix_bkgrnd_2,
(UI_filled_area*)&matrix_normal_item_2,
(UI_filled_area*)&matrix_selected_item_2,
(UI_filled_area*)&Disabled_items,
(UI_filled_area*)&General_BG,
(UI_filled_area*)&fibox_normal_2,
(UI_filled_area*)&fibox_selected_2,
(UI_filled_area*)&mm_bkgrnd_2,
(UI_filled_area*)&General_BG,
(UI_filled_area*)&popup_description_bkgrnd_2,
(UI_filled_area*)&list_bkgrnd_2,
(UI_filled_area*)&list_normal_item_2,
(UI_filled_area*)&list_selected_item_2,
(UI_filled_area*)&Disabled_items,
(UI_filled_area*)&list_selected_item_2,
(UI_filled_area*)&General_BG,
(UI_filled_area*)&Unused,
(UI_filled_area*)&list_selected_item_2,
(UI_filled_area*)&common_screen_BG,
(UI_filled_area*)&common_screen_BG,
(UI_filled_area*)&common_screen_BG,
(UI_filled_area*)&common_screen_BG,
(UI_filled_area*)&dial_inputbox_bg_filler,
(UI_filled_area*)&virtual_keyboard_down_bkgrnd_1,
(color*)&black_color,
(color*)&white_color,
(color*)&lite_disp_scr_bg_col_2,
(color*)&LSK_up_txt_col_2,
(color*)&LSK_down_txt_col_2,
(color*)&Disabled_text_col,
(color*)&RSK_up_txt_col_2,
(color*)&RSK_down_txt_col_2,
(color*)&Disabled_text_col,
(color*)&mtab_selector_txt_col_2,
(color*)&mtab_normal_txt_col_2,
(color*)&mtab_selected_txt_col_2,
(color*)&ibox_normal_txt_col_2,
(color*)&ibox_selected_txt_col_2,
(color*)&ibox_selector_col_2,
(color*)&ibox_cursor_col_2,
(color*)&title_scut_txt_col_2,
(color*)&white_color,
(color*)&title_scut_txt_col_2,
(color*)&list_normal_txt_col_2,
(color*)&list_selected_txt_col_2,
(color*)&Disabled_text_col,
(color*)&list_normal_txt_col_2,
(color*)&list_selected_txt_col_2,
(color*)&Disabled_text_col,
(color*)&Unused_color,
(color*)&Unused_color,
(color*)&Unused_color,
(color*)&Unused_color,
(color*)&scut_indicator_txt_col_2,
(color*)&white_color,
(color*)&Unused_color,
(color*)&Unused_color,
(color*)&Unused_color,
(color*)&ibox_selector_col_2,
(color*)&ibox_normal_txt_col_2,
(color*)&Disabled_text_col,
(color*)&ibox_selected_txt_col_2,
(color*)&ibox_cursor_col_2,
(color*)&list_normal_txt_col_2,
(color*)&list_selected_txt_col_2,
(color*)&Disabled_text_col,
(color*)&list_normal_txt_col_2,
(color*)&list_selected_txt_col_2,
(color*)&Disabled_text_col,
(color*)&list_normal_txt_col_2,
(color*)&list_selected_txt_col_2,
(color*)&Disabled_text_col,
(color*)&white_color,
(color*)&black_color,
(color*)&popup_description_txt_col_2,
(color*)&white_color,
(color*)&white_color,
(color*)&black_color,
(color*)&black_color,
(color*)&black_color,
(color*)&black_color,
(color*)&button_bar_col_2,
(color*)&information_bar_col_2,
(color*)&input_method_txt_col_2,
(color*)&input_method_txt_col_2,
(color*)&Status_bar_col,
(color*)&black_color,
(color*)&ibox_normal_txt_col_2,
(color*)&ibox_selected_txt_col_2,
(color*)&ibox_selector_col_2,
(color*)&ibox_cursor_col_2,
(color*)&list_normal_txt_col_2,
(color*)&list_selected_txt_col_2,
(color*)&Disabled_text_col,
(color*)&ibox_normal_txt_col_2,
(color*)&ibox_selected_txt_col_2,
(color*)&ibox_selector_col_2,
(color*)&ibox_cursor_col_2,
(color*)&ibox_normal_txt_col_2,
(color*)&ibox_selected_txt_col_2,
(color*)&ibox_selector_col_2,
(color*)&ibox_cursor_col_2,
(color*)&virtual_keyboard_key_down_text_col_1,
(color*)&virtual_keyboard_key_up_text_col_1,
(color*)&virtual_keyboard_dead_key_down_text_col_1,
(color*)&virtual_keyboard_dead_key_up_text_col_1,
(color*)&virtual_keyboard_disp_area_text_col_1,
&MMI_medium_font,
&MMI_medium_font,
&MMI_medium_font,
&MMI_medium_font,
&MMI_default_font,
&MMI_default_font,
&MMI_default_font,
&MMI_default_font,
&MMI_default_font,
&MMI_default_font,
&MMI_default_font,
&MMI_default_font,
&MMI_default_font,
&MMI_virtual_keyboard_font,
UI_SCROLLBAR_WIDTH
};

const MMI_theme theme_3={
(UI_filled_area*)&LSK_up_3,
(UI_filled_area*)&LSK_down_3,
(UI_filled_area*)&Disabled_items,
(UI_filled_area*)&RSK_up_3,
(UI_filled_area*)&RSK_down_3,
(UI_filled_area*)&Disabled_items,
(UI_filled_area*)&mtab_3,
(UI_filled_area*)&ibox_3,
(UI_filled_area*)&sbar_bkgrnd_3,
(UI_filled_area*)&sbar_indicator_3,
(UI_filled_area*)&Title_3,
(UI_filled_area*)&list_bkgrnd_3,
(UI_filled_area*)&list_normal_item_3,
(UI_filled_area*)&list_selected_item_3,
(UI_filled_area*)&Disabled_items,
(UI_filled_area*)&matrix_bkgrnd_3,
(UI_filled_area*)&matrix_normal_item_3,
(UI_filled_area*)&matrix_selected_item_3,
(UI_filled_area*)&Disabled_items,
(UI_filled_area*)&General_BG,
(UI_filled_area*)&fibox_normal_3,
(UI_filled_area*)&fibox_selected_3,
(UI_filled_area*)&mm_bkgrnd_3,
(UI_filled_area*)&General_BG,
(UI_filled_area*)&popup_description_bkgrnd_3,
(UI_filled_area*)&list_bkgrnd_3,
(UI_filled_area*)&list_normal_item_3,
(UI_filled_area*)&list_selected_item_3,
(UI_filled_area*)&Disabled_items,
(UI_filled_area*)&list_selected_item_3,
(UI_filled_area*)&General_BG,
(UI_filled_area*)&Unused,
(UI_filled_area*)&list_selected_item_3,
(UI_filled_area*)&common_screen_BG,
(UI_filled_area*)&common_screen_BG,
(UI_filled_area*)&common_screen_BG,
(UI_filled_area*)&common_screen_BG,
(UI_filled_area*)&dial_inputbox_bg_filler,
(UI_filled_area*)&virtual_keyboard_down_bkgrnd_1,
(color*)&black_color,
(color*)&white_color,
(color*)&lite_disp_scr_bg_col_3,
(color*)&LSK_up_txt_col_3,
(color*)&LSK_down_txt_col_3,
(color*)&Disabled_text_col,
(color*)&RSK_up_txt_col_3,
(color*)&RSK_down_txt_col_3,
(color*)&Disabled_text_col,
(color*)&mtab_selector_txt_col_3,
(color*)&mtab_normal_txt_col_3,
(color*)&mtab_selected_txt_col_3,
(color*)&ibox_normal_txt_col_3,
(color*)&ibox_selected_txt_col_3,
(color*)&ibox_selector_col_3,
(color*)&ibox_cursor_col_3,
(color*)&title_scut_txt_col_3,
(color*)&white_color,
(color*)&title_scut_txt_col_3,
(color*)&list_normal_txt_col_3,
(color*)&list_selected_txt_col_3,
(color*)&Disabled_text_col,
(color*)&list_normal_txt_col_3,
(color*)&list_selected_txt_col_3,
(color*)&Disabled_text_col,
(color*)&Unused_color,
(color*)&Unused_color,
(color*)&Unused_color,
(color*)&Unused_color,
(color*)&scut_indicator_txt_col_3,
(color*)&white_color,
(color*)&Unused_color,
(color*)&Unused_color,
(color*)&Unused_color,
(color*)&ibox_selector_col_3,
(color*)&ibox_normal_txt_col_3,
(color*)&Disabled_text_col,
(color*)&ibox_selected_txt_col_3,
(color*)&ibox_cursor_col_3,
(color*)&list_normal_txt_col_3,
(color*)&list_selected_txt_col_3,
(color*)&Disabled_text_col,
(color*)&list_normal_txt_col_3,
(color*)&list_selected_txt_col_3,
(color*)&Disabled_text_col,
(color*)&list_normal_txt_col_3,
(color*)&list_selected_txt_col_3,
(color*)&Disabled_text_col,
(color*)&white_color,
(color*)&black_color,
(color*)&popup_description_txt_col_3,
(color*)&white_color,
(color*)&white_color,
(color*)&black_color,
(color*)&black_color,
(color*)&black_color,
(color*)&black_color,
(color*)&button_bar_col_3,
(color*)&information_bar_col_3,
(color*)&input_method_txt_col_3,
(color*)&input_method_txt_col_3,
(color*)&Status_bar_col,
(color*)&black_color,
(color*)&ibox_normal_txt_col_3,
(color*)&ibox_selected_txt_col_3,
(color*)&ibox_selector_col_3,
(color*)&ibox_cursor_col_3,
(color*)&list_normal_txt_col_3,
(color*)&list_selected_txt_col_3,
(color*)&Disabled_text_col,
(color*)&ibox_normal_txt_col_3,
(color*)&ibox_selected_txt_col_3,
(color*)&ibox_selector_col_3,
(color*)&ibox_cursor_col_3,
(color*)&ibox_normal_txt_col_3,
(color*)&ibox_selected_txt_col_3,
(color*)&ibox_selector_col_3,
(color*)&ibox_cursor_col_3,
(color*)&virtual_keyboard_key_down_text_col_1,
(color*)&virtual_keyboard_key_up_text_col_1,
(color*)&virtual_keyboard_dead_key_down_text_col_1,
(color*)&virtual_keyboard_dead_key_up_text_col_1,
(color*)&virtual_keyboard_disp_area_text_col_1,
&MMI_medium_font,
&MMI_medium_font,
&MMI_medium_font,
&MMI_medium_font,
&MMI_default_font,
&MMI_default_font,
&MMI_default_font,
&MMI_default_font,
&MMI_default_font,
&MMI_default_font,
&MMI_default_font,
&MMI_default_font,
&MMI_default_font,
&MMI_virtual_keyboard_font,
UI_SCROLLBAR_WIDTH
};

#if !defined (MMI_ON_HARDWARE_P)
__declspec(dllexport)
#endif

const MMI_theme *mtk_MMI_themes[MAX_MMI_THEMES]={
(MMI_theme *)&theme_1,
(MMI_theme *)&theme_2,
(MMI_theme *)&theme_3,
};

